### ISSUE TITLE
Project Lombok plugin is required for contributors using IntelliJ - not documented

### ISSUE THREAD

**Issue by asafm** [testcontainers/testcontainers-java#100]
Lots of methods are missing, probably due to Lombok not activating its code generation when importing Maven projects to IntelliJ.

**Comment by asafm** [comment]
Ok, so apparently you need to install Lombok plugin for IntelliJ. 
If you want I can open a PR for adding this to the README - adding a CONTRIBUE section

**Comment by rnorth** [comment]
Thanks, and sorry you encountered this. There's a section on Contributing in docs/index.md. Perhaps a link to that in the README would also be a useful thing to have!

**Comment by sskorol** [comment]
By the way, I've faced with the same and even wanted to raise some issues. :) However, after installing Lombok plugin, everything was resolved.

**Comment by rnorth** [comment]
:(

Much as I like some of the conveniences of Lombok, perhaps it would be a good idea to remove it...

**Comment by asafm** [comment]
@rnorth Maybe switch to Kotlin :)

**Comment by buckett** [comment]
Using lombok also means that the maven sources don't look correct in IntelliJ. When using the testcontainers artifact in another project and downloading the source, it still contains all the lombok annotations and IntelliJ then shows lots of errors because all the processing isn't done. This is even the case if the plugin is instal in IntelliJ.

**Comment by bsideup** [comment]
@buckett to avoid IDEA complaining about binary changes one can use Delombok ( https://projectlombok.org/features/delombok.html ), maybe it makes sense to apply http://awhitford.github.io/lombok.maven/lombok-maven-plugin/ for distribution of TestContainers.

**Comment by buckett** [comment]
@bsideup I'd be in favour of adding the delombok to the sources artifact, although I can see the point of keeping the sources exactly as it was when compiling the artifact.

**Comment by bsideup** [comment]
Delombok added in 1.7.0, we also migrated to Gradle and recommend compiling the project with "Delegate to Gradle" option on. 

I assume we can close this issue now :)

**Comment by JJonesAtAvaya** [comment]
Delombok tasks doesn't seem to work though?
