### ISSUE TITLE
Running testcintainers inside Dockerfile?

### ISSUE THREAD

**Issue by kkocel** [testcontainers/testcontainers-java#1013]
Hello, I have a question. I run testcontiners in junit5 test when generating new Docker Image.
Is such workflow supported?

My Dockerfile:

    FROM openjdk:8-jdk as builder
    COPY . /usr/src/user-and-device
    WORKDIR /usr/src/user-and-device
    USER root
    RUN ./gradlew test  booJar

and during the test inside I have:

    21:50:39.821 [DEBUG] [TestEventLogger] com.openbrewery.user.docs.DeviceDocumentationTest > classMethod FAILED
    21:50:39.822 [DEBUG] [TestEventLogger]     java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration```

**Comment by rnorth** [comment]
Sadly no, as mentioned on Slack, there is no way for Testcontainers to access the docker daemon from within a Docker build.
