### ISSUE TITLE
Feature request: a way to "docker exec" on a GenericContainer

### ISSUE THREAD

**Issue by ostacey** [testcontainers/testcontainers-java#103]
It would be nice to have a way to perform a "docker exec" operation on a running container. Currently it's possible if a user:
 - subclasses GenericContainer to get access to the dockerClient and containerId, and
 - writes the code to use dockerClient directly

... but it would be nice to just have the functionality available on GenericContainer.

**Comment by rnorth** [comment]
This sounds great - I'm keen to give it a try!
Thank you :)
Rich
