### ISSUE TITLE
Container with TTY and the log output

### ISSUE THREAD

**Issue by vektory79** [testcontainers/testcontainers-java#1100]
If I start the container with enabled TTY, then log output of this container is completely missing.
Quick investigation shows, that in this case in this line of code: 

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/transport/okhttp/OkHttpInvocationBuilder.java#L357

the `payloadSize` variable have extremely big size (757935405 in my case) and call to `source.request(payloadSize)` is never returns.

May be it's better to manually limit the `palyloadSize` if `streamType == RAW`?

**Comment by rnorth** [comment]
Fix was released in [1.10.4](https://github.com/testcontainers/testcontainers-java/releases/tag/1.10.4)!
