### ISSUE TITLE
Latest release 1.10.4 not showing in maven central

### ISSUE THREAD

**Issue by RobMaskell** [testcontainers/testcontainers-java#1107]
I looked, can see 1.10.3 but not the latest one https://mvnrepository.com/artifact/org.testcontainers/postgresql

**Comment by rnorth** [comment]
Sorry, we’re having a problem with Bintray, which is a step in our release process (artifacts are published to Bintray first and then synced to maven central). 

We’ll get this sorted today, and I’ll update this ticket once it’s solved. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RobMaskell** [comment]
No worries, not urgent for me, just wanted to make sure you knew

**Comment by rnorth** [comment]
We're finally synced to Maven Central now - phew!
