### ISSUE TITLE
Cannot run testscontainers in Dockerfile build step

### ISSUE THREAD

**Issue by modestukasai** [testcontainers/testcontainers-java#1110]
Hi,
I cannot build my project from Dockerfile, because it fails in step of docker file with error:
```
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:157) ~[testcontainers-1.10.4.jar:na]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_181]
```
Command to use on project: `docker build .`

Here is the sample link to the project which I have created: https://github.com/modestukasai/spring-boot-testcontainers-docker

Link to failing build: 
https://travis-ci.org/modestukasai/spring-boot-testcontainers-docker/builds/474195893

Thanks a lot.

**Comment by bsideup** [comment]
Hi @modestukasai!

There is no Docker available when you run `docker build`.
Try adding `RUN docker run hello-world` to your Dockerfile to demonstrate it :)

**Comment by modestukasai** [comment]
Hi @bsideup!
The problem is that I cannot start docker daemon in build. I did `RUN apk add --no-cache docker` and then `docker -v` to see if it's installed, but docker daemon cannot be started when I run `docker build .`

I have updated the base image to use `docker` image as base and install java8 on it.
I get the same result. Please see https://travis-ci.org/modestukasai/spring-boot-testcontainers-docker/builds/474334240

Thanks a lot
