### ISSUE TITLE
Release of 1.10.4 of junit-jupiter module contains wrong classes - REPUBLISHED AS 1.10.5

### ISSUE THREAD

**Issue by michael-simons** [testcontainers/testcontainers-java#1111]
I was investigating why https://github.com/testcontainers/testcontainers-java/issues/1019 still fails me even if https://github.com/testcontainers/testcontainers-java/pull/1020 was merged. 

The test in the project works (I have checked it several times), so I tried to build super plain reproducers (for [Maven](https://github.com/testcontainers/testcontainers-java/files/2720487/tcjunit5.zip) and [Gradle](https://github.com/testcontainers/testcontainers-java/files/2720488/tcjunit5gradle.zip)), which both fail with 1.10.4.

So I finally ended up debugging and make my way through the delomboked sources and in 1.10.4  `TestcontainersExtension` still only implements `BeforeEachCallback` and *not* `BeforeAllCallback`.

Please see the sources from central: 
https://search.maven.org/remotecontent?filepath=org/testcontainers/junit-jupiter/1.10.4/junit-jupiter-1.10.4-sources.jar

I think one solution would be just drafting a new release in time. Being able to use the shared container in a `BeforeAll` seems to be crucial (at least from my perspective).

Thanks.

**Comment by bsideup** [comment]
@michael-simons thanks a lot for the investigation! 
We had a major issue with Bintray and publishing, and it seems that wrong binaries were published by Bintray 😱

We will work on a new release process ASAP, directly to the Maven Central (without Bintray in the middle), such issues are too critical 😑

/cc @jbaruch

**Comment by rnorth** [comment]
We're running a new release right now, 1.10.5, using the Bintray->Maven Central model.

Hopefully this will fix whatever's gone wrong here without taking the time of reverting to direct Maven Central publication.

**Comment by rnorth** [comment]
https://dl.bintray.com/testcontainers/releases/org/testcontainers/junit-jupiter/1.10.5/junit-jupiter-1.10.5-sources.jar seems to contain the correct code:

```
...
class TestcontainersExtension implements BeforeEachCallback, BeforeAllCallback, TestInstancePostProcessor {
...
```

`bintrayPublish` has also succeeded on this release, instead of timing out the build: https://travis-ci.org/testcontainers/testcontainers-java/jobs/474365588

**Comment by rnorth** [comment]
Synced 1.10.5 to Maven Central, and verified that the resultant JAR is correct. I'll put out some messages to prompt people to upgrade.

I have no idea what happened with the 1.10.4 publication, but we'll have to try and figure it out.

Thanks so much for noticing and raising the issue to our attention, @michael-simons.

**Comment by michael-simons** [comment]
I can confirm things regarding the JUnit 5 extension work now as expected (i.e. https://github.com/michael-simons/bootiful-music/commit/8759a485a7b429adb5cb848df321639e7a46fe7a) 

I didn't check other artefacts, so I leave this issue for you to close. From my side, it's fixed. Thanks everyone.

**Comment by rnorth** [comment]
Closed, as there's probably been enough time for people to see this ticket and act on it.
