### ISSUE TITLE
Cannot run testscontainers in Dockerfile build step

### ISSUE THREAD

**Issue by modestukasai** [testcontainers/testcontainers-java#1112]
Hi, this issue is created because #1110 was closed.

The code is here: https://github.com/modestukasai/spring-boot-testcontainers-docker

I have current docker file which should run gradlew build inside with docker testcontainers.
```
FROM docker as builder
USER root
RUN docker -v
RUN apk add --no-cache openjdk8
WORKDIR /app
COPY . .
RUN ./gradlew build -i
```
The problem is that docker is not started during build of docker image.

I have updated the base image to use docker image as base and install java8 on it.
I get the same result. Please see https://travis-ci.org/modestukasai/spring-boot-testcontainers-docker/builds/474334240

Thanks a lot!

**Comment by bsideup** [comment]
Hi again, @modestukasai!

Sorry, I'm closing this one with the same message:
You need to have a running Docker daemon in your environment. Your example is incorrect - it does not communicate with Docker daemon. 
But if you put `RUN docker run hello-world`, you will see that there is **no docker running**. 
You code simply prints Docker **client**'s version.

**Comment by modestukasai** [comment]
Hi #bsideup,
Yes, I understand it and I'm asking you for help in this case, because your tutorial in documentation does not tell anything about how to run this in docker build step.
https://www.testcontainers.org/usage/inside_docker.html

**Comment by bsideup** [comment]
@modestukasai this is not an issue of Testcontainers project. 

There is **no docker daemon** inside your build container (when you run `docker build`). Nothing to connect to.

Please ask a question in the Docker community, "How to run Docker commands during Dockerfile build".

**Comment by kiview** [comment]
AFAIK this is not possible Docker. 

There might we other container tools that might allow this use case, but Testcontainers will only support Docker for the foreseeable future.

The linked docs describe how to use Testcontainers inside a running container, not during a `docker build`.

**Comment by modestukasai** [comment]
Thanks a lot #bsideup and #kiview. This is proper answer which I have expected :)

**Comment by bonitao** [comment]
This can be done by injecting the docker socket through the --network parameter in docker build, and then mounting it in the build step. You can use socat for both actions. It took me a long time to figure out the details, so I wrote them up here:

https://daviws.medium.com/using-docker-for-integration-tests-dfc02b5ffc8c
