### ISSUE TITLE
Example needed: exposing host port

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1136]
It would be nice to add an example of `Testcontainers.exposeHostPorts` method. It is very helpful when you're running something inside a container but want to access a port from the host.

Let's say:
1) start a very simple Spring Boot app in the test with some HTML page
1) use `Testcontainers.exposeHostPorts(serverPort)` to expose it to the containers network.
1) start `BrowserWebDriverContainer`
1) run some very simple Selenium assertion of the HTML page

Here is a test for the feature:
https://github.com/testcontainers/testcontainers-java/blob/bcecd5cd9f9325517fd45db585312df2624315bb/core/src/test/java/org/testcontainers/containers/ExposedHostTest.java

**Comment by stsefanenko** [comment]
I'll add it
