### ISSUE TITLE
Example needed: modern Spring Boot example

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1137]
One could apply our workshop ( https://testcontainers.gitbook.io/workshop/ ) to the Spring Boot example ( https://github.com/testcontainers/testcontainers-java/tree/master/examples/spring-boot )

1) add PostgreSQL database to that example
2) use [the JDBC URL support](https://www.testcontainers.org/usage/database_containers.html#jdbc-url) and set it as a property in `@SpringBootTest` annotation
3) start Redis with `static { }` block, set system properties to wire it

**Comment by artjomka** [comment]
Will take that issue, if no one is doing it already

**Comment by bsideup** [comment]
@artjomka first comment, first served ;)

**Comment by bsideup** [comment]
Closed by #1175
