### ISSUE TITLE
Example needed: Cucumber tests

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1139]
Testcontainers supports some testing engines out of the box, but can also be used with any other testing engine like Cucumber.

The easiest way to start a container is to call `.start()` method. But some containers (e.g. browser containers) support advanced features like video recording.  
This is why we have `TestLifecycleAware` interface:  
https://github.com/testcontainers/testcontainers-java/blob/bcecd5cd9f9325517fd45db585312df2624315bb/core/src/main/java/org/testcontainers/lifecycle/TestLifecycleAware.java

An example could start a browser container integrated with Cucumber's lifecycle, call `beforeTest` before the execution and `afterTest` after, to make the video recording work.

**Comment by stsefanenko** [comment]
I'll add it

**Comment by bsideup** [comment]
Hi @stsefanenko!
it's been a week since you took it, do you have something to submit yet?

**Comment by stsefanenko** [comment]
hi @bsideup no, I don't have. I'll try to add it in a few days.

**Comment by stsefanenko** [comment]
@bsideup  this one can be closed https://github.com/testcontainers/testcontainers-java/pull/1180 merged
