### ISSUE TITLE
waitingFor(Wait.forHttp(String path) not working when exposing more than one port

### ISSUE THREAD

**Issue by ocker-docker-gummi-klokker** [testcontainers/testcontainers-java#1174]
I have an acceptance test exposing a fixed port and waiting for a http response before proceeding.
The problem is that when I expose more than one port, waitingFor waits for a response on both ports.
Is there no way to specify the full path or port in the Wait.forHttp method (or something similar)?

**I get the following error:**
*Timed out waiting for URL to be accessible (http://myip:9000/path/to/rest/service/healthcheck should return HTTP [200])*

I have tried to pass the complete url to waitingFor, but this does not work.

```javascript
int servicePort = 8080; // HEALTH CHECK RETURNS 200
int debugPort = 9000; // NO HEALTH CHECK HERE
GenericContainer containerTwo = new FixedHostPortGenericContainer("localDockerTwo:latest")
	.withFixedExposedPort(servicePort , servicePort )
	.withFixedExposedPort(debugPort , debugPort )
	.withCommand("./startTest.sh").withNetworkAliases("containertwo")
	.withNetwork(network)
	.waitingFor(Wait.forHttp("/path/to/rest/service/healthcheck")  // TRIES ON BOTH PORTS
		.forStatusCode(200).withStartupTimeout(Duration.ofSeconds(30)));
containerTwo.start();
```

**Comment by ocker-docker-gummi-klokker** [comment]
Thank you Kevin.
Question: Why do you think it was waiting for both ports and not just checking the wrong port?
Answer: Just a quick assumption based on nothing but a thought.

**Comment by kiview** [comment]
Alright, in this case, I will close the issue.
Please re-open if something is still not working as expected, thanks.
