### ISSUE TITLE
Documentation examples should provide self-contained, runnable sample code

### ISSUE THREAD

**Issue by bmuschko** [testcontainers/testcontainers-java#1193]
Currently, documentation examples live in the subproject `docs-example`. If you wanted to support more examples in regards to https://github.com/testcontainers/testcontainers-java/issues/1162, then it would be beneficial to model this differently for the following reasons:

- Each sample should be a standalone "project" that users can copy/paste and run. At the moment the examples depend on other subprojects in the build.
- Supporting different test frameworks or versions will be hard as you'll likely run into version conflicts. At the moment, there's no issue as you only depend on JUnit 4 but adding Spock-based or JUnit 5-based examples will likely break or result transitive dependencies on the test runtime classpath you'll likely not want.

I am proposing the following:

- The subproject `docs-example` continues to exist, however, its sole purpose will be to run tests against standalone projects with a Gradle `Test` task.
- Each example project in `docs-example` will live under the directory `src/docs` or a similar directory. There will be no more need for `src/main/java`.
- Example projects will be decoupled from the rest of the multi-project build. Dependencies on the current TestContainer code will be injected at runtime.
- Test execution will be performed with the help of [Gradle TestKit](https://docs.gradle.org/current/userguide/test_kit.html).

**Comment by kiview** [comment]
Thanks a lot for your thoughts @bmuschko.
You have some valid points and we also were thinking about some of them.

That's why we are currently in the process of migrating the examples as part of #1177.
It would be great if you could add some feedback in the PR.

I'm especially interested in 
> Example projects will be decoupled from the rest of the multi-project build. Dependencies on the current TestContainer code will be injected at runtime.
> Test execution will be performed with the help of Gradle TestKit.

, can you give an example how to do this?

**Comment by bmuschko** [comment]
@kiview Happy to help out! Will have a look at the PR later today.

Here's an example of what I have done for one of my Gradle plugins:

- Self-contained projects: https://github.com/bmuschko/gradle-docker-plugin/tree/master/src/docs/samples/code
- Test class that uses TestKit to run through examples (the runtime injection of the classpath would likely have to look different as you are not testing a Gradle plugin): https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/docTest/groovy/com/bmuschko/gradle/docker/AbstractDocumentationTest.groovy
- Set up of documentation source set (IMHO optional in your case): https://github.com/bmuschko/gradle-docker-plugin/blob/master/buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/DocumentationTestPlugin.kt

**Comment by bmuschko** [comment]
@kiview Added some comments in your PR. Happy to make a proposal on the approach laid out in my initial description once your PR got merged.

**Comment by bmuschko** [comment]
@kiview Is this something you are still pursuing?

**Comment by kiview** [comment]
@bmuschko So the migration is done (and PR merged), do you thing there is something big missing?

**Comment by bmuschko** [comment]
@kiview The main driver for this issue is to have self-contained examples. In its current state many of the example projects have included project dependencies as part of a composite build. A user that tries to copy one of your examples wouldn't be able to use them without further modification. I also think that those example aren't actually tested e.g. run from a user's perspective. They are only compiled as part of a composite build.

It's OK if you decide not to go down that route and close the issue but in essence the arguments above capture the reasons for opening the issue.
