### ISSUE TITLE
Checks fail if Docker version contains a non-numeric classifier.

### ISSUE THREAD

**Issue by ysb33r** [testcontainers/testcontainers-java#1220]
On one of my Linux system the version `from docker version` is reported as `18.06.0-dev`. This causes the version check to fail as it assumes that the version should be purely dots and numbers.

*Edit*:  The correct fix for this should be the following:

- [ ] Have the ability to turn off the version check (either on it's own or as part of `checks.disable=true`
- [ ] Only compare numerical parts of the version and remove and non-numeric classifiers. (For instance this is how Grolifant does version comparisons: https://gitlab.com/ysb33rOrg/grolifant/blob/master/src/main/groovy/org/ysb33r/grolifant/api/Version.groovy#L234)

**Comment by ysb33r** [comment]
Mmm.. no, It seemingly reports the version of the server just as `dev`. I think this is rather a case for the specific distribution's package maintainer rather than testcontainers. 

What is just sad is that I cannot skip this check by setting `checks.disable=true`.

**Comment by kiview** [comment]
Hey Schalk, cool to see you using Testcontainers :slightly_smiling_face: 
You are correct, here is the bug and we always check for the version:
https://github.com/testcontainers/testcontainers-java/blob/8acee4d804c125beb3774f509744f31b58ad7fc8/core/src/main/java/org/testcontainers/DockerClientFactory.java#L145

**Comment by ysb33r** [comment]
I think just the ability to turn the check off would be good enough.  In general I think the version check is important. I'll update the title of this issue and add some clarification too.

As the issue that triggered this is with a specific Linux distro I have also raised the appropriate bg with them: https://bugs.mageia.org/show_bug.cgi?id=24321

**Comment by rnorth** [comment]
Yeah, lets go with letting this check be turned off. Docker 1.6.0 is pretty ancient, so as a check it's not _really_ that valuable.

**Comment by aivinog1** [comment]
Hello there!
I'm new in contributing, but this issue for me is pretty clear.
Do you mind if I take this issue?

**Comment by kiview** [comment]
Hey @aiviniog1,
Would be great, thx.

**Comment by aivinog1** [comment]
I have create PR with a new setting to disable check Docker version.
Path of the setting will be:`checks.docker.disable` (by default value is false). 

I think I need to update docs, but I can't find appropriate article. Any advice? Or may be I need to create a new one?

**Comment by rnorth** [comment]
Hmm, this page is probably the right one: https://www.testcontainers.org/features/configuration/

However, it already _implies_ that the version check is disabled by `checks.docker.disable`. So we can probably keep the docs as-is and make the behaviour match what's there more closely.

Thank you!

**Comment by aivinog1** [comment]
@rnorth Thank you for your answer. It's stands more clear now. I understand so there don't need additional setting. I have already changed my PR accordingly.

Bottom line: The setting `checks.disable` turn off the Docker version check.
