### ISSUE TITLE
Publishing snapshots

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#123]
I noticed an issue in 1.0.3 whereby TC would start all my services in their containers, but my "ping" command would fail to find the service API endpoint. After banging my head for some time I tried 1.0.4-SNAPSHOT and voila - everything worked perfectly. I don't know what goes right or wrong with 1.0.3; just happy to see that the issue is resolved. 

Are we going to see 1.0.4 released soon? In the meantime, is there a snapshot repo where the artefact is getting published?

- Mike

**Comment by bsideup** [comment]
@monowai, I strongly recommend https://jitpack.io/ :

https://jitpack.io/#testcontainers/testcontainers-java/master-SNAPSHOT

You can also refer commit (to avoid snapshots):
https://jitpack.io/#testcontainers/testcontainers-java/4f569d208d

**Comment by rnorth** [comment]
Yes, jitpack is a great way to do this, which I'd definitely support. I'll add to the documentation.

**Comment by rnorth** [comment]
Added brief note to docs - will close.
