### ISSUE TITLE
VNC Recording not working with vanilla integration

### ISSUE THREAD

**Issue by bopi-** [testcontainers/testcontainers-java#1232]
This is not working:
```
package testcontainers;

import java.io.File;

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testcontainers.containers.BrowserWebDriverContainer;
import org.testcontainers.containers.BrowserWebDriverContainer.VncRecordingMode;

public class TestContainerWebdriveVanilla {

	private BrowserWebDriverContainer<?> firefox;
	
	@Before
	public void before() {
		
		firefox = new BrowserWebDriverContainer<>()
		  .withCapabilities(new FirefoxOptions())
		  .withRecordingMode(VncRecordingMode.RECORD_ALL, new File("C:\\tmp\\"));
		
		firefox.start();			
		
	}
	
	@Test
	public void test() {
		firefox.getWebDriver().get("https://www.testcontainers.org");
	}

}
```
But this works:
```
package testcontainers;

import java.io.File;

import org.junit.Rule;
import org.junit.Test;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testcontainers.containers.BrowserWebDriverContainer;
import org.testcontainers.containers.BrowserWebDriverContainer.VncRecordingMode;

public class TestContainerWebdriveRule {

	@Rule
	public BrowserWebDriverContainer<?> firefox = new BrowserWebDriverContainer<>()
          .withCapabilities(new FirefoxOptions())
	  .withRecordingMode(VncRecordingMode.RECORD_ALL, new File("C:\\tmp\\"));	
	
	@Test
	public void test() {
		firefox.getWebDriver().get("https://www.testcontainers.org");
	}

}
```

How can I get VNC Recording to work with vanilla integration?

**Comment by bsideup** [comment]
Hi @bopi-,

VNC recording requires test lifecycle awareness, you need to trigger `afterTest` (that is what `@Rule` is doing):
https://github.com/testcontainers/testcontainers-java/blob/b1445ffd5d0d46338a4da9f1cf43db4221699814/examples/cucumber/src/test/java/org/testcontainsers/examples/Stepdefs.java#L38-L48

**Comment by bopi-** [comment]
Hi @bsideup,

thank you for super fast response!

If I understand your suggestion correctly this means that I need a cucumber dependency and also have to run my tests with cucumber.
That feels a little heavy to me.

So I came up with this solution:

```
package testcontainers;

import java.io.File;
import java.util.Optional;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestWatcher;
import org.junit.runner.Description;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testcontainers.containers.BrowserWebDriverContainer;
import org.testcontainers.containers.BrowserWebDriverContainer.VncRecordingMode;
import org.testcontainers.lifecycle.TestDescription;

public class TestContainerWebdriveVanilla2 {

	@Rule
	public TestWatcher testWatcher = new TestWatcher() {

		private TestDescription toTestDescription(Description description) {
			return new TestDescription() {
				public String getTestId() {
					return description.getDisplayName();
				}
				public String getFilesystemFriendlyName() {
					return description.getClassName() + "-" + description.getMethodName();
				}
			};
		}

		protected void failed(Throwable e, Description description) {
			firefox.afterTest(toTestDescription(description), Optional.of(e));
		};

		protected void succeeded(Description description) {
			firefox.afterTest(toTestDescription(description), Optional.empty());
		};

	};

	private BrowserWebDriverContainer<?> firefox;

	@Before
	public void before() {

		firefox = new BrowserWebDriverContainer<>()
		  .withCapabilities(new FirefoxOptions())
		  .withRecordingMode(VncRecordingMode.RECORD_ALL, new File("C:\\tmp\\"));
		
		firefox.start();

	}

	@Test
	public void test() {
		firefox.getWebDriver().get("https://www.testcontainers.org");
	}

}
```

**Comment by bsideup** [comment]
Hi @bopi-,

What I meant is that if you skip `@Rule` and use `firefox.start();` then the container will never be notified that the test finished and it doesn't know when to perform the recording, this is why you need to call `afterTest`.

But, if you execute your tests with JUnit (as seen in your latest example), why would you use `TestWatcher` instead of putting `@Rule` on browser's field?

**Comment by kiview** [comment]
@bopi- 
You misunderstood @bsideup, he just took the code example from our Cucumber example. This is nothing Cucumber related.

**Comment by bopi-** [comment]
Hi @bsideup,

What I'am trying to do is to write a JUnit test that starts a local FirefoxDriver if installed (developer machine) but uses testcontainers FirefoxDriver if not installed (bulid machine).

Therefore I don't want to define the `BrowserWebDriverContainer` as `@Rule`. Otherwise the `BrowserWebDriverContainer` would be started but not needed in case of the local FirefoxDriver.

You are of course right, the `TestWatcher` solution is also not solving my problem. So I decided to simply not use VNC Recording. But I wanted to share the solution anyway. Maybe it helps somebody else with a similar problem.

Hi @kiview,

Actually the code is cucumber related. It is an cucumber `@After` annotation and `Scenario` object. I also guess that the scenario object is only provided if the test is run by an cucumber testrunner

**Comment by kiview** [comment]
The actual code example comes from a Cucumber test, calling the `afterTest` method, to which @bsideup was referring to, is not.

Never the less, thanks for sharing your scenario and your ideas, I'm closing this issue, since `BrowserWebDriverContainer` works as expected.
