### ISSUE TITLE
BitBucket Pipelines docs needed

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1247]
Would be great to have a page describing how to use Testcontainers on BitBucket Pipelines, also mentioning [the need to disable the Ryuk](https://www.testcontainers.org/features/configuration/#disabling-ryuk).

**Comment by mschnitzler** [comment]
I added a pull request for this: #1439

**Comment by rnorth** [comment]
This ticket should have been closed when we merged #1439! Will close now.
