### ISSUE TITLE
Show browser and clicks when using BrowserWebDriverContainer

### ISSUE THREAD

**Issue by meldmy** [testcontainers/testcontainers-java#1248]
Hi,

I'm using BrowserWebDriverContainer with chrome driver. Is it possible to show browser and test's clicks?

**Comment by rnorth** [comment]
Hi @meldmy

The `getVncAddress()` method on `BrowserWebDriverContainer` gives you a VNC URL through which you can watch (and interact with) the browser during the test run.

Note that using this URL is platform specific and depends on what VNC viewing tools are installed.

I hope this answers your question.
Richard
