### ISSUE TITLE
Still want to use Forking?

### ISSUE THREAD

**Issue by swissarmykirpan** [testcontainers/testcontainers-java#125]
so Github has now released two new interesting features:

1. Allowing squashing and merging with ff via the UI when merging a pull request. 
https://github.com/blog/2141-squash-your-commits
2. Setting security on branches to only allow specific groups/users to be able to push - thus meaning that members can be added to the testcontainers project and you can only allow specific people who you trust to do a proper code review. This feature is especially great if you are working on a private repository.
https://github.com/blog/2137-protected-branches-improvements

Thoughts?
@rnorth

**Comment by rnorth** [comment]
Hi Gurpreet
Yes, thanks, I'd seen that. For now I'm happy with the as-is, but if we find a need to change it we can reconsider!
Thanks
Rich
