### ISSUE TITLE
possibility to run containers with fsync=off

### ISSUE THREAD

**Issue by alexanderkjall** [testcontainers/testcontainers-java#1256]
According to this article: https://pythonspeed.com/articles/faster-db-tests/ a lot of speed can be gained when running postgresql in docker with fsync=off.

When I look at the docker image that testcontainers start with "docker inspect" it doesn't seem to run it with fsync off, and I have tried to play around with the .withCommand() and .addEnv() functions without success.

Is there a recommended way to set -c fsync=off in the docker run command? If yes, could this maybe be a bit better exposed?

**Comment by kiview** [comment]
Sounds interesting.
Btw. you can already use the Testcontainers Postgres module with tempfs (
https://docs.docker.com/storage/tmpfs/), which might provide the same speed
boost.

Alexander Kjäll <notifications@github.com> schrieb am Di., 19. Feb. 2019,
20:24:

**Comment by alexanderkjall** [comment]
That was a good suggestion, setting tmpfs to "/var/lib/postgresql/data" moved my heaviest tests from taking roughly 17 seconds to 3 seconds and the whole testsuite from about 90 seconds to 60 seconds.

**Comment by bsideup** [comment]
Whoa! Nice, we should set it by default!
Perhaps you want to contribute? 🤞

**Comment by alexanderkjall** [comment]
Sure, I'll try to write a pull request tomorrow or the day after.

**Comment by alexanderkjall** [comment]
@bsideup I looked at creating a pull request yesterday, but I'm not really friends with gradle and the testsuite completely hosed my old laptop, but it looked like it might just be a one line change.

I'm sorry to say that someone else needs to create the pull request, I don't have enough free time to do it and do it well.

**Comment by rnorth** [comment]
Releasing this in [1.11.0](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.0) 🎉
