### ISSUE TITLE
the connection returned by ContainerDatabaseDriver doesn't set Catalog or MetaData

### ISSUE THREAD

**Issue by jeacott1** [testcontainers/testcontainers-java#1281]
the connection object returned by the ContainerDatabaseDriver doesnt set Catalog or MetaData objects.
instead they appear to be left with default settings and as such, multiple databases look identical from the connection.
at a minimum it would be helpful if the catalog Name was returned by connection.getCatalog();
and if connection.getMetaData().getURL(); reflected the url that was passed in.

Cheers.

**Comment by rnorth** [comment]
I’ll add the help wanted label. This hasn’t been a priority item for us, so a PR would be welcomed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
