### ISSUE TITLE
Running into com.github.dockerjava.api.exception.DockerClientException:  Could not pull image

### ISSUE THREAD

**Issue by tmuthuk** [testcontainers/testcontainers-java#1283]
I'm trying to setup testcontainers to use GenericContainer for running `mongo:3.6.10` in my JUnit4 tests. 

In my local environment, things seems to be okay. Whereas in the Jenkins CI, I'm seeing the following exception. In the CI we're running tests from within a docker container. So I'm running docker using the following command `docker run -v /var/run/docker.sock:/var/run/docker.sock  {image}`

```
Caused by: org.testcontainers.containers.ContainerFetchException: Retry limit reached while trying to pull image: mongo:3.6.10
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Digest: sha256:701c2a16f31db77ff74aa080ffaae7bee4b889365c1128c65526e65706449287
```

Code snippet from my tests

```
@ClassRule
public static GenericContainer mongo = new GenericContainer("mongo:3.6.10").withExposedPorts(27017);

MongoClient mongoClient = new MongoClient(mongo.getContainerIpAddress(), mongo.getMappedPort(27017));
```

**Comment by tmuthuk** [comment]
Noticed some additional logging.
```
14:01:43 [main] INFO docker[mongo:3.6.10] - Pulling docker image: mongo:3.6.10. Please be patient; this may take some time but only needs to be done once.
14:01:46 [main] ERROR docker[mongo:3.6.10] - Retry limit reached while trying to pull image: mongo:3.6.10. Please check output of `docker pull mongo:3.6.10`
```

**Comment by rnorth** [comment]
@tmuthuk what happens when you run `docker pull mongo:3.6.10` from the CLI in your CI environment? You'd need to run this from within your dockerized build.

This ought to tell you why the pull is failing.

**Comment by tmuthuk** [comment]
@rnorth : The CI has no problem pulling the image through the CLI. 

Screenshot below:

<img width="668" alt="screen shot 2019-03-04 at 1 20 40 pm" src="https://user-images.githubusercontent.com/5536131/53753954-8c2ce800-3e80-11e9-92e0-115c15eca7d1.png">

**Comment by tmuthuk** [comment]
I see this when the tests start

<img width="1297" alt="screen shot 2019-03-04 at 1 24 06 pm" src="https://user-images.githubusercontent.com/5536131/53754130-09585d00-3e81-11e9-85d8-bfa8e6ff701a.png">
