### ISSUE TITLE
execInContainer exit code

### ISSUE THREAD

**Issue by dmarkhas** [testcontainers/testcontainers-java#1309]
I am trying to find a way to determine if a command executed inside a container via execInContainer is successful or not, however ExecResult only returns stdout and stderr which does not really help..

There is a comment in the code "due to the limitations of the docker API, there's no easy way to get the result code from the process we ran" however it is quite old so I am not sure it is relevant anymore. Furthermore, docker-java exposes an API to inspect the command status via "inspectExecCmd", which returns the exit code.

Is it possible to add the exit code from inspectExecCmd to the ExecResult?

**Comment by bsideup** [comment]
Hi @dmarkhas,

You're right, `inspectExecCmd` returns the exit code and can be used for this use case.

We a class for the exec pattern:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/ExecInContainerPattern.java

The implementation should be as simple as adding a field to `ExecResult` class and calling the API you discovered before constructing it:
https://github.com/testcontainers/testcontainers-java/blob/604fd0ee0e8aba424c8ea63e887b4b941bb533d5/core/src/main/java/org/testcontainers/containers/ExecInContainerPattern.java#L86-L88

Would you like to contribute it? 😊

**Comment by dmarkhas** [comment]
I'll be happy to :) 
Will try to get it done tomorrow..

**Comment by bsideup** [comment]
@dmarkhas that would be great, thank you!

There is also:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/internal/InternalCommandPortListeningCheck.java

and it will benefit a lot from this change 👍 We had to use a string constant to check the result :D

**Comment by dmarkhas** [comment]
Thank you for your inputs and merging the PR! I forgot to update the docs to reflect this new API, so I have done so now in #1319 .

**Comment by dmarkhas** [comment]
@bsideup are you guys planning to publish a release soon? or is there a snapshots repository I can use in the meanwhile? 😄

**Comment by bsideup** [comment]
@dmarkhas we prefer [Jitpack](https://www.testcontainers.org/jitpack_dependencies/) for it :)

**Comment by dmarkhas** [comment]
Awesome 😸
