### ISSUE TITLE
TestNG support

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#132]
Sub-task of #87

**Comment by laurikimmel** [comment]
The second birthday is almost there!
Any news on this one?

**Comment by bsideup** [comment]
@laurikimmel actually yes :) 
We're working on the unified, framework-agnostic API as part of JUnit 5:
https://github.com/testcontainers/testcontainers-java/pull/636

The reason why TestNG didn't receive enough attention is because you can already use TC with TestNG by calling `.start()`/`.stop()`. And since there is no such thing as rule in TestNG, there is not much we can do

**Comment by kiview** [comment]
We basically support this, see the examples:
https://github.com/testcontainers/testcontainers-java/blob/master/examples/redis-backed-cache-testng/src/test/java/RedisBackedCacheTest.java

**Comment by olyv** [comment]
@kiview did you by any chance try to run tests in parallel using TestNG?
