### ISSUE TITLE
Add support for image pull policy

### ISSUE THREAD

**Issue by dmarkhas** [testcontainers/testcontainers-java#1324]
There does not seem to be a way to retrieve the latest image version for a GenericContainer via the library. This is not a problem for the provided application containers, but when using a custom image we are forced to manually run `docker pull` outside of the test project before running the tests to ensure we are using the latest image.

It would be nice if the library could be extended with something like `imagePullPolicy` that would allow users to always pull the latest image version of the GenericContainer by leveraging the `pullImageCmd` API in docker-java.

This would also allow to address this long standing issue in Docker:
https://github.com/moby/moby/issues/13331

And would allow to easily support the behavior that is proposed here:
https://github.com/docker/cli/pull/1498

**Comment by remal** [comment]
Are there any plans to implement it?

**Comment by senyor** [comment]
+1

**Comment by rnorth** [comment]
Reopening this issue - should be addressed by #1345. Sorry for letting this get stale. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tyagiakhilesh** [comment]
+1

**Comment by mangan77** [comment]
+1
