### ISSUE TITLE
OneShotStartupCheckStrategy fails if the container is already gone

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1331]
Consider the following test:

```java
    @Test(timeout = 5_000)
    public void testExitingContainer() {
        try (
            GenericContainer container = new GenericContainer<>()
                .withCreateContainerCmdModifier(it -> it.getHostConfig().withAutoRemove(true))
                .withStartupCheckStrategy(new OneShotStartupCheckStrategy())
        ) {
            container.start();
        }
    }
```

It will fail because the container exits immediately and `OneShotStartupCheckStrategy` receives `NotFoundException`.

The question is - what should we do? `StartupStatus.SUCCESSFUL` or `StartupStatus.FAILED`?

**Comment by rnorth** [comment]
Ergh. Yeah, the problem is that there's no right `StartupStatus` for this.

I think actually `OneShotStartupCheckStrategy` is not right - how about a new strategy? e.g. a strategy that checks that the container is no longer present (although this is a pretty useless check)?

In this case, short execution + autoremove, there's not much we can actually do to verify what happened, is there? It almost seems like a scenario worth avoiding altogether!

**Comment by bsideup** [comment]
As observed in #1327, Socket exits immediately if no ports are exposed, but the check fails due to some race condition. It seems that we can't easily avoid it.

**Comment by rnorth** [comment]
Got it - but hasn't #1328 avoided this?

**Comment by bsideup** [comment]
@rnorth there are more such places and races.
Another one - containerized Docker Compose, when commands exit faster than the check.
Also, we recommend `OneShotStartupCheckStrategy` for simple commands because there isn't anything to prevent it from failing.
Maybe we need a `NoopStartupCheckStrategy` ? :D

**Comment by rnorth** [comment]
Yeah, `NoopStartupCheckStrategy` was vaguely in my mind 😁 

Still, do we need to use `autoRemove`? It seems like it causes two problems:
 * This race condition
 * It's impossible to tell whether the invocation succeeded or failed

**Comment by bsideup** [comment]
`autoRemove` here is to demonstrate the problem, but I was also thinking about adding it to our one-off commands like DockerCompose ones, because currently I see many exited compose containers during the execution
