### ISSUE TITLE
Support of SAP Hana express database

### ISSUE THREAD

**Issue by carstenartur** [testcontainers/testcontainers-java#1337]
See https://hub.docker.com/_/sap-hana-express-edition/plans/f2dc436a-d851-4c22-a2ba-9de07db7a9ac?tab=instructions
Would be great if SAP Hana could be supported.

**Comment by kiview** [comment]
Hey @carstenartur,
thanks for the suggestion.

The provided image seems quite container unfriendly and we'll also run into several license issues when trying to provide this ourselves I assume.

If you want to use SAP Hana together with Testcontainers, I'd recommend to implement a sublcass of `GenericContainer` in your organization. You can get some inspiration about how to do this from #860.

In case you think I'm wrong regarding the license hassle, feel free to provide further information, we might be able to reconsider implementing it then.
