### ISSUE TITLE
[Windows] Could not find a valid env.

### ISSUE THREAD

**Issue by DynamicBit** [testcontainers/testcontainers-java#1349]
I have problems with `not find a valid env.`.

```
17:15:09.952 [main] ERROR o.t.d.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
17:15:09.952 [main] ERROR o.t.d.DockerClientProviderStrategy - NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
17:15:09.952 [main] ERROR o.t.d.DockerClientProviderStrategy - WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: connect) 
17:15:09.952 [main] ERROR o.t.d.DockerClientProviderStrategy - DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (Exception when executing docker-machine status ) 
17:15:09.952 [main] ERROR o.t.d.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
```

**Comment by bsideup** [comment]
Hi. Please provide more information, like:
1) testcontainers version
2) Windows version
3) Are you running Docker for Mac (with Hyper-V) or docker-machine from Docker Toolbox (VirtualBox)?
4) does normal `docker run hello-world` works for you

**Comment by DynamicBit** [comment]
1. `1.11.1`
2. Windows 10 Pro
3. Docker for Windows (Hyper-V)
4. yes, but very slow

**Comment by bsideup** [comment]
From the log I see that it failed to connect to the npipe socket:
> NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)

You said that even a simple `hello-world` runs very slow, I would suggest to double check your Docker setup first.

**Comment by DynamicBit** [comment]
> You said that even a simple `hello-world` runs very slow, I would suggest to double check your Docker setup first.

How?

What I have done so far: reinstall Docker

**Comment by bsideup** [comment]
>> I would suggest to double check your Docker setup first.

> How?

I would ask for a help in Docker's community.

**Comment by DynamicBit** [comment]
I have fixed the performance issues but I have the problems farther.

Here are more logging-informations:

18:10:02.222 [main] DEBUG o.t.u.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/xxx/.testcontainers.properties
18:10:02.303 [main] INFO  o.t.d.DockerClientProviderStrategy - Will use 'okhttp' transport
18:10:02.880 [ducttape-0] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
18:10:03.025 [ducttape-0] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@2ab4bd22
18:10:12.885 [main] DEBUG o.t.d.DockerClientProviderStrategy - NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
18:10:12.887 [main] INFO  o.t.d.DockerClientProviderStrategy - Will use 'okhttp' transport
18:10:12.890 [ducttape-2] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
18:10:12.890 [ducttape-2] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@2f9bc6d4
18:10:13.567 [ducttape-0] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
18:10:13.567 [ducttape-0] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@30d1c5e0
18:10:15.411 [ducttape-2] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
18:10:15.411 [ducttape-2] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@11bde0d2
18:10:17.892 [main] DEBUG o.t.d.DockerClientProviderStrategy - WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: connect)
18:10:17.894 [main] DEBUG o.testcontainers.utility.CommandLine - Executing shell command: `docker-machine.exe ls -q`
18:10:17.903 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Executing [docker-machine.exe, ls, -q].
18:10:17.907 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Started java.lang.ProcessImpl@52e6fdee
18:10:17.947 [main] DEBUG o.t.s.o.z.exec.WaitForProcess - java.lang.ProcessImpl@52e6fdee stopped with exit code 0
18:10:17.949 [main] DEBUG o.t.utility.DockerMachineClient - DOCKER_MACHINE_NAME is not set and no machine named 'default' found; Using first machine found with `docker-machine ls`: 
18:10:17.949 [main] INFO  o.t.d.DockerMachineClientProviderStrategy - Found docker-machine, and will use machine named 
18:10:17.949 [main] DEBUG o.testcontainers.utility.CommandLine - Executing shell command: `docker-machine status `
18:10:17.949 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Executing [docker-machine, status, ""].
18:10:17.951 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Started java.lang.ProcessImpl@158da8e
18:10:17.974 [ducttape-2] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
18:10:17.974 [ducttape-2] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@514b4127
18:10:17.991 [main] DEBUG o.t.s.o.z.exec.WaitForProcess - java.lang.ProcessImpl@158da8e stopped with exit code 1
18:10:17.992 [main] DEBUG o.t.d.DockerClientProviderStrategy - DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (Exception when executing docker-machine status )
18:10:17.992 [main] ERROR o.t.d.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
18:10:17.992 [main] ERROR o.t.d.DockerClientProviderStrategy -     NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
18:10:17.993 [main] ERROR o.t.d.DockerClientProviderStrategy -     WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: connect)
18:10:17.993 [main] ERROR o.t.d.DockerClientProviderStrategy -     DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (Exception when executing docker-machine status )
18:10:17.993 [main] ERROR o.t.d.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue

**Comment by DynamicBit** [comment]
I have solved the problem by reinstall Docker and adding my user to the docker-user group.
