### ISSUE TITLE
Add WSL section

### ISSUE THREAD

**Issue by BalmungSan** [testcontainers/testcontainers-java#1359]
I would like to suggest the adding of a section explaining how to use `testcontainers` from **Windows** within the **WSL** _(Windows Subsystem for Linux)_.

Basically you only need to follow this [post](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) to configure docker on the **WSL**, and that's all. `testcontainers` will work out-of-the-box™️.

### tl;dr;

+ Install docker for widows _(use linux containers)_.
+ Configure docker for windows to expose docker over tcp without TLS.
+ Install docker-cli on your **WSL** instance.
+ `$ export DOCKER_HOST=tcp://localhost:2375`.
+ Enjoy :D

**Comment by kiview** [comment]
Thanks for the heads up.

Would you like to contribute a PR for the docs to add the missing information?

I think it's enough to mention, that you need to get Docker CLI working from inside WSL and then link to the blog post (isn't there even an official one from Microsoft?).

**Comment by BalmungSan** [comment]
Of course.

I will be opening the **PR** in a while.
Just a quick question first. Where would you like it? As another sub-section inside the **Windows** _page_ or as a new _page_? (IMHO, subsection is the best option, since it should not be big).

Regarding the windows post.
I believe not. However, I setup **Docker** on my **WSL** instance, more than a year ago.
Thus, I will give it another search.

**Comment by kiview** [comment]
Subsection sounds good.

Luis Miguel Mejía Suárez <notifications@github.com> schrieb am Sa., 6. Apr.
2019, 14:58:

**Comment by casz** [comment]
With WSL 2.0 and Docker edge this changes completely.

You can now use `wsl docker run` to start a docker container in the Linux subsystem.
