### ISSUE TITLE
tenforce/virtuoso container:latest image seems to be failing builds regularly

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#136]
We're seeing build failures hitting the virtuoso module for a few days now:

- https://circleci.com/gh/testcontainers/testcontainers-java/517 - affects @outofcoffee's PR #133
- https://circleci.com/gh/testcontainers/testcontainers-java/518 - affects @tbinias's PR #135 
- also on the `windows-support` branch, which is a clean fork of a stable master branch 

It looks like the latest image was changed six days ago: https://hub.docker.com/r/tenforce/virtuoso/tags/

I suspect the fact that the module is using the `latest` tag is a bad thing - perhaps there's an issue with this. I'll try and locate a stable named tag and get that into master ASAP.

@v-schulz are you aware of any problems with Virtuoso support from your own experience?

**Comment by v-schulz** [comment]
@rnorth No, but currently I'm not working with the container. Sorry for the problems, I think tag 1.0.0-virtuoso7.2.0 should be fine.

**Comment by rnorth** [comment]
@v-schulz no worries - I'll give that tag a try. Thanks

**Comment by v-schulz** [comment]
Let me correct that, tag virtuoso-v7.2.0-latest works fine for me.

**Comment by rnorth** [comment]
@v-schulz thanks. I had similar issues with that one until adding a 5s 'stabilisation period' to the container object's liveness checks. I'm not quite sure what has changed in Virtuoso, but it seems it would consistently (a) respond OK to the 'SELECT 1' in the liveness check then (b) drop the next few connection attempts for <1s or so.

I've now made it so that the Virtuoso container has to respond to the SELECT 1 query consistently for 5 seconds. This seems to work.

I've tried this on a few of the available tags and it now works, so I've gone for 1.0.0-virtuoso7.2.2 as it seems to be the most recent.

This is all in PR #138

**Comment by rnorth** [comment]
It seems this is still falling apart on CI so I'm going to disable the Virtuoso module for the time being. I think we need to bring the container image we use under our control to prevent this happening in the future.

I'd like to reinstate it before 1.0.5 release, but will evaluate depending on the relative importance of other features in 1.0.5.
