### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.Kernel32

### ISSUE THREAD

**Issue by TobseF** [testcontainers/testcontainers-java#1371]
In my unittest I set up a athenapdf docker service on start with the ClassRule. The test works including the docker setup, but it's not reliable. But sometimes it fails with a 
`NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.Kernel32`.
The next test run solves the problem.

```
Caused by: java.lang.NoClassDefFoundError: 
    Could not initialize class com.sun.jna.platform.win32.Kernel32
    at org.testcontainers.dockerclient.transport.okhttp.
            NamedPipeSocketFactory$1.lambda$connect$0(NamedPipeSocketFactory.java:50)
    at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0
        (Unreliables.java:41)
```
📑 Full Stacktrace: [stacktracke.txt](https://github.com/testcontainers/testcontainers-java/files/3054850/stacktracke.txt)

**Setup**: 
TestContainers **v1.11.1**
Docker version 18.09.2, build 6247962
Win 10 x64, DE, IntelliJ Ultimate 2019.1 
``` java 
@ClassRule
new GenericContainer("arachnysdocker/athenapdf-service:latest")
  .withEnv("WEAVER_AUTH_KEY", "someSecret")
  .withExposedPorts(8080)
  .withEnv("WEAVER_ATHENA_CMD",
  "athenapdf --stdout --pagesize A4")
  .waitingFor(forHttp(""));
```

Sometimes this Error also occurs after the test, on stop:
```
On stop
java.lang.RuntimeException: java.lang.NoSuchMethodError: 
  com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)
     Lcom/sun/jna/Library;
    at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
    at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:43)
at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:38)
```
📑 Full Stacktrace 2: [stacktracke-2.txt](https://github.com/testcontainers/testcontainers-java/files/3054869/stacktracke-2.txt)

**Comment by bsideup** [comment]
Hi @TobseF,

Does it fail on Testcontainers version 1.10.7?

**Comment by TobseF** [comment]
No, on the latest v1.11.1

**Comment by bsideup** [comment]
@TobseF could you please try 1.10.7? I'm afraid this is a regression we introduced in 1.10.0, but I need to verify it first

**Comment by TobseF** [comment]
Unfortunately it also fails on 1.10.7. - After the 3rd run.
[stacktrace3.txt](https://github.com/testcontainers/testcontainers-java/files/3055070/stacktrace3.txt)

**Comment by bsideup** [comment]
@TobseF it seems that there is a version conflict of the JNA library. We use 5.2.0. 
Do you have Elasticsearch on classpath by any chance? They seem to include (not shade) JNA v4.5.1 as `org.elasticsearch:jna`. You can try excluding it

**Comment by TobseF** [comment]
Sergei, thanks for the fast reply. Yes, that makes sense. I don't fight often with such dependency problems, so it wasn't my first assumption. Indeed we are using `org.seleniumhq.selenium:selenium-server:3.4.0` with `net.java.dev.jna:jna-platform:4.1.0`. So it's a good point to track and check all overwritten dependencies in every module.
