### ISSUE TITLE
Connecting to daemon testcontainer postgres

### ISSUE THREAD

**Issue by argoyb** [testcontainers/testcontainers-java#1373]
Hello.

I'm using liquibase for DB migrations and would like to use [JOOQ](jooq.org) with dynamic schema generation and thinking of following use case for testcontainers:

1. Run liquibase gradle plugin to run migrations against newly created DB instance
1. Run jooq schema migration to generate Java classes based on just created schema

However I'm having trouble with connecting to started testcontainer. Since I want schema to be preserved I'm using "daemon" property when specifying jdbc url for liquibase: `jdbc:tc:postgresql:9.6.8://hostname/databasename?TC_DAEMON=true`

However I'm not able to connect to created DB from next step - when running jooq. If I set same url it would just start a new container. And regular jdbc url like `jdbc:postgres://localhost:5432/service` fails (likely because postgres container is running on a different port, not 5432. And I can dynamically set correct port because it's not code, but gradle thing).

Gradle configuration is following:

```
// Liquibase plugin to run migration script
liquibase {
  activities {
    main {
      changeLogFile 'src/main/resources/ddl/master-changelog.yaml'
      url 'jdbc:tc:postgresql:9.6.8://hostname/databasename?TC_DAEMON=true'
      driver 'org.testcontainers.jdbc.ContainerDatabaseDriver'
      username 'postgres'
      password ''
    }
  }
  runList = 'main'
}

jooq {
  version = '3.10.4'
  edition = 'OSS'
  service(sourceSets.main) {
    jdbc {
      driver = 'org.testcontainers.jdbc.ContainerDatabaseDriver'
      url = 'jdbc:postgres://localhost:5432/service'
      user = 'postgres'
      password = ''
    }
    generator {
      name = 'org.jooq.util.DefaultGenerator'
      strategy {
        name = 'org.jooq.util.DefaultGeneratorStrategy'
      }
      database {
        name = 'org.jooq.util.postgres.PostgresDatabase'
        inputSchema = 'service'
      }
      generate {
        relations = true
        records = true
        pojos = true
        fluentSetters = true
      }
      target {
        packageName = 'com.example.service.persistence.jooq'
        directory = './build/generated/source/jooq/main'
      }
    }
  }
}

generateServiceJooqSchemaSource.dependsOn dbUpdate
```

Could you please advice if it is possible to connect to daemon using only gradle configuration?

Thanks.

**Comment by bsideup** [comment]
In your JOOQ config, you should be using the same JDBC string:
```
'jdbc:tc:postgresql:9.6.8://hostname/databasename?TC_DAEMON=true'
```

**Comment by rnorth** [comment]
Actually, I tried something similar with Flyway and jOOQ, and hit a fatal problem.

IIRC the Gradle jOOQ plugin runs in a forked JVM to avoid classpath conflicts, and unfortunately this means that you end up with two instances of Testcontainers, each with its own connection:container cache. Right now we have no way to share containers between JVMs.

I'm afraid I've not yet found a way to do this with Testcontainers.

**Comment by argoyb** [comment]
Thank you @rnorth, that answers the question
