### ISSUE TITLE
Can not connect to Ryuk on Raspberry Pi

### ISSUE THREAD

**Issue by bmuschko** [testcontainers/testcontainers-java#1380]
I ran into the following error when executing TestContainers on a Raspberry Pi.

```
15:44:43.181 [testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:32769
    java.net.ConnectException: Connection refused
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at java.net.Socket.connect(Socket.java:538)
    	at java.net.Socket.<init>(Socket.java:434)
    	at java.net.Socket.<init>(Socket.java:211)
    	at org.testcontainers.utility.ResourceReaper.lambda$start$1(ResourceReaper.java:112)
    	at java.lang.Thread.run(Thread.java:745)
```

This is the output from `docker version`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

Can you give me an idea on how to debug this issue? What is Ryuk being used for? Let me know if you need any additional information.

**Comment by bsideup** [comment]
Hi @bmuschko,

Raspberry Pi is not supported at this moment.
[Ryuk](https://github.com/testcontainers/moby-ryuk) is a sidecar we start as a container to kill the containers even if the JVM got `kill -9`ed.

**Comment by bsideup** [comment]
@bmuschko FYI you can try to set `TESTCONTAINERS_RYUK_DISABLED` to disable Ryuk. Not recommended, but at least should unblock you. 
Although I'm not sure that the native code we have (e.g. unix socket support) will work.
There are also some linux-only images like sshd, socat and others.

**Comment by bmuschko** [comment]
@bsideup Thanks for the background info. Setting the environment variable does get pass the original error. Seems like there are other issues later as you mentioned. Looks like ARM is not a supported entry into the Docker Compose and other images I use.

```
 com.github.dockerjava.api.exception.DockerClientException: Could not pull image: no matching manifest for unknown in the manifest list entries
```

This was more or less an experiment on Raspberry Pi. I am going to close the issue for now. Thanks!

**Comment by kiview** [comment]
@bmuschko Cool to see this experiment.
But you are right, we are probably missing ARM images for all our sidecar container images, at least our custom built ones.

**Comment by Ordiel** [comment]
Is there a follow up enhancement/request for this?

**Comment by bsideup** [comment]
Unless someone volunteers {him,her}self to work on the ARM support across all features supported by the library - no, not yet. Note that it is not only about Ryuk, but **every** image _plus_ native libraries that are used (e.g. transports in `docker-java`)
