### ISSUE TITLE
Could not find file in MountableFile.forClasspathResource

### ISSUE THREAD

**Issue by DynamicBit** [testcontainers/testcontainers-java#1395]
Hi,

I have following code snippet

`container = (FixedHostPortGenericContainer) new FixedHostPortGenericContainer("xxx-oracle-xe-11g:v03")
              .withFixedExposedPort(Integer.parseInt(properties.getProperty("database.port")), 1521)
              .withCopyFileToContainer(MountableFile.forClasspathResource("db/" + provider + ".sql"), "/docker-entrypoint-initdb.d/");`

my file is lying in `.\src\test\resources\db`

everytime My programm passes the snippet the produce an error with the following message:

java.lang.IllegalArgumentException: Resource with path db/E2.sql could not be found on any of these classloaders: [sun.misc.Launcher$AppClassLoader@5c647e05]
	at XXX.setUp(XXX.java:72)

**Comment by DynamicBit** [comment]
Problem solved.
fixed per .pom file.

**Comment by imaffe** [comment]
Hi! I ran into a similar problem, do you still remember how you fixed this ? Thanks !

**Comment by colossatr0n** [comment]
I ran into a similar problem as well. I was using `MountableFile.forClasspathResource("resources")`. I had accidentally specified in the pom that this directory was located in `${basedir}/src/test/java` when it was actually located in `${basedir}/src/test/kotlin`.  


```xml
<!--  Corrected pom.xml  -->
<project>
    ...
    <build>
        <testResources>
            <testResource>
                <!--  Make sure this path is correct  -->
                <directory>${basedir}/src/test/kotlin</directory>
                <excludes>
                    <exclude>**/*.kt</exclude>
                </excludes>
            </testResource>
        </testResources>
</project>
```
