### ISSUE TITLE
There is no need to call toLowerCase() on string parameter of containsSubstringAtOffset(String string, String substring, int offset)

### ISSUE THREAD

**Issue by mumukiller** [testcontainers/testcontainers-java#1396]
String parameter of [containsSubstringAtOffset](https://github.com/testcontainers/testcontainers-java/blob/master/modules/database-commons/src/main/java/org/testcontainers/ext/ScriptUtils.java#L225) is always a parsed script content, it's not necessary to call toLowerCase() each time in loop. 
It might be done only once before for loop

**Comment by rnorth** [comment]
Released in [1.11.2](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.2)!
