### ISSUE TITLE
Example of TC with Spring

### ISSUE THREAD

**Issue by swissarmykirpan** [testcontainers/testcontainers-java#14]
@rnorth I guess what I am looking for is an example. The scenario is that a datasource @bean is injected into a test class

        public class TestClass {
            public static final String ID = "101";
            public static final String REF_ID = "101";
   
            @Inject
            private DataSource dataSource;
            private ExampleDao exampleDao;
   
            @Before
            public void before() throws Exception {
                exampleDao = new ExampleDaoImpl(dataSource);
            }

            @Test
            public void testRetrieveExample_withValidId() {
                assertThat(customerNumberDao.retrieveExampleFromUserId(ID), is(REF_ID));
            }
       }

Bean: 

        @Bean
        public DataSource dataSource() {
            final DriverManagerDataSource ds = new DriverManagerDataSource();
            dataSource.setDriverClassName(ds.DRIVER);
            dataSource.setUrl(ds.URL);
            dataSource.setUsername(ds.USERNAME);
            dataSource.setPassword(ds.PASSWORD);
            return dataSource;
        }

Excuse the formatting/code, I've just whacked this together

**Comment by gusohal** [comment]
@rnorth I guess what I am looking for is an example. The scenario is that a datasource @bean is injected into a test class

public class TestClass {
  public static final String ID = "101";
  public static final String REF_ID = "101";
   @Inject
    private DataSource dataSource;
    private ExampleDao exampleDao;

    @Before
    public void before() throws Exception {
        exampleDao = new ExampleDaoImpl(dataSource);
    }

    @Test
    public void testRetrieveExample_withValidId() {
        assertThat(customerNumberDao.retrieveExampleFromUserId(ID), is(REF_ID));
    }
}

**Comment by rnorth** [comment]
To be honest I'm not quite sure how much is needed here; ultimately this
should just be showing modification of the declaration of the DataSource
bean to use a 'tc' JDBC URL. That's easy to show.

The test itself should not need to change at all.

Or have I misunderstood what you're asking for?

**Comment by gusohal** [comment]
yes, the problem is how do you initiate a ContainerRule? The bean sits in a configuration class which then gets loaded into the test class. 

If you place the ContainerRule in the configuration class, the before and after methods do not get executed and so the JDBC URL never gets generated.

**Comment by rnorth** [comment]
Oh in that case you'd use the JDBC driver proxying, and not use the JUnit rule at all...

**Comment by gusohal** [comment]
Cool - just wanted to make sure there wasn't a more elegant way of doing this.

**Comment by rnorth** [comment]
I'll make an example anyway, because it's obviously not quite clear enough :)

**Comment by gusohal** [comment]
Agreed - an example would be good

**Comment by rnorth** [comment]
@swissarmykirpan do you still want this? It's the oldest open issue, which is the only reason I'm asking...!

**Comment by swissarmykirpan** [comment]
Nope. Can close this.
