### ISSUE TITLE
No explicit documentation for .docker/config.json usage for registry auth

### ISSUE THREAD

**Issue by athlordJojo** [testcontainers/testcontainers-java#1419]
If this is a duplicate: i'am sorry, but i couldn't find any help in the docs...

I have the following setup: 
Jenkins runs a gradle-task inside docker (so i use docker.sock). From the gradle-job, i start my Integration test using testcontainers.
My problem starts, when i want to use private repositories from jffrog (public images works fine). I tried to set the environment variables to the docker command which runs the gradle command via:

`-e \"registryUsername=foo\" -e \"registryPassword=bar\" -e \"registryUrl=https://companyname.jfrog.io\"
`

 Inside the container which runs gradle, i can see that the values are set correctily. But none of the values are picked up from testcontainers, which results in an error, complining about not be able to load the images...

What am i missing ? I found this [change log](https://github.com/testcontainers/testcontainers-java/releases/tag/1.8.1) but no docs how to configure it...

Any help is welcome, thank you!

**Comment by athlordJojo** [comment]
Ok, i found a solution:
Create this file ~/.docker/config.json via the following command in the jenkins, before the tests are started via gradle:

`sh 'echo "{\\"auths\\":{\\"https://company-docker.jfrog.io\\":{\\"auth\\": \\"\$(echo -n \$JFROG_USR:\$JFROG_PWD | base64)\\"}}}" > ~/.docker/config.json'`

I really think, that this should be documented in testcontainers, even if it's part of docker-java.

**Comment by kiview** [comment]
Hi @athlordJojo, thanks for the remarks and providing the solution with an example.
Do you think we should duplicate this into our docs, or just add references to docker-java?

**Comment by athlordJojo** [comment]
Hey @kiview !

I really think, that this should be part of testcontaines documentation.
For example: I didn't even knew, that textcontainers uses docker-java, so i didn't looked at there documentation.

**Comment by kiview** [comment]
Yes, this definitely makes sense.
But we could just link to https://github.com/docker-java/docker-java#properties-docker-javaproperties for example.

By the way, the `$HOME/.docker/config.json` is a general Docker approach, not docker-java specific I just realized: https://docs.docker.com/engine/reference/commandline/login/

**Comment by athlordJojo** [comment]
ok, so will add the documentation ? becasue then we could close this issue.

**Comment by rnorth** [comment]
I'd agree that this needs to be in the documentation. If anyone would like to raise a PR to add, it would be appreciated!
