### ISSUE TITLE
OracleContainer extends JdbcDatabaseContainer without generic type

### ISSUE THREAD

**Issue by SoftwareTipi** [testcontainers/testcontainers-java#1423]
It means I need explicit cast when using methods from super type, eg:
```java
@ClassRule
public static OracleContainer db = (OracleContainer) new OracleContainer("foo")
        .withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger("db container logger")));
```
Following screams compilation errors, because `#withLogConsumer` returns `GenericContainer`:
```java
@ClassRule
public static OracleContainer db = new OracleContainer("foo")
        .withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger("db container logger")));
```

**Comment by bsideup** [comment]
Hi @SoftwareTipi,

Have you tried `public static OracleContainer db = new OracleContainer<>("foo")` as a workaround?

**Comment by SoftwareTipi** [comment]
Hi `OracleContainer` does not have generic type on itself so diamond syntax won't apply to this.
And still this would be workaround.

**Comment by kiview** [comment]
@SoftwareTipi Yes, you are right. Are you interested in providing a PR?

**Comment by bsideup** [comment]
@kiview already submitted: #1425
