### ISSUE TITLE
Upgrade from 1.10.7 to 1.11.x broke compilation when on module path on Java 11

### ISSUE THREAD

**Issue by alexanderkjall** [testcontainers/testcontainers-java#1424]
When upgrading the org.testcontainers:postgresql package from version 1.10.7 to 1.11.0 my project ( https://github.com/pgjdbc/pgadba ) stopped compiling. 

A new warning that was added is a good hint on what's wrong:

    [WARNING] Can't extract module name from testcontainers-1.11.2.jar: Provider class org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl not in module

And this is an example of the errors that are generated:

    [ERROR] /home/capitol/project/pgsql2/src/test/java/org/postgresql/adba/testutil/ConnectUtil.java:[22,27] cannot access org.testcontainers.containers.traits.LinkableContainer
      class file for org.testcontainers.containers.traits.LinkableContainer not found

How to reproduce:

1. git clone git@github.com:pgjdbc/pgadba.git
2. update pom.xml and upgrade the dependency version to 1.11.0
3. mvn clean test

**Comment by bsideup** [comment]
Hi! Have you tried the latest version (1.11.2)?

**Comment by alexanderkjall** [comment]
Yes, sorry for not spelling that out. All three of 1.11.0, 1.11.1 and
1.11.2 behaves the same.

Den tors 25 apr. 2019 22:54 skrev Sergei Egorov <notifications@github.com>:

**Comment by bsideup** [comment]
@alexanderkjall ok, thanks.
We did a few changes to the shading config in 1.11.x, it seems that something sneaked into the final JAR.
Thank you for reporting!

**Comment by alexanderkjall** [comment]
Also tested with 1.11.3, same problem.

**Comment by alexanderkjall** [comment]
Not stale, problem still exists in version 1.12.0

**Comment by alexanderkjall** [comment]
Not stale, problem still exists in version 1.12.4

**Comment by tgolden-andplus** [comment]
Can confirm the issue still exists in 1.12.5.

Does downgrading to the last patch release in the 1.11.x line work?

**Comment by alexanderkjall** [comment]
@tgolden-andplus Version 1.10.7 works, 1.11.0 and onwards doesn't work

**Comment by TomRK1089** [comment]
Issue still exists in 1.13.0 as well.

Is this on the roadmap for Testcontainers developers at all? Modules are not going away anytime soon....

**Comment by Gunthervg** [comment]
Still the same in 1.14.0

**Comment by bsideup** [comment]
This will not be fixed until Testcontainers 2.0 due to JPMS limitation (unique packages).

**Comment by nedis-ua** [comment]
This issue not found in 1.15.0. Please update your testcontainers

**Comment by alexanderkjall** [comment]
I can't seem to reproduce this with 1.15.0 and java 15, thanks for fixing it.
