### ISSUE TITLE
How do I access Kafka Broker on localhost in my tests?

### ISSUE THREAD

**Issue by voplex95** [testcontainers/testcontainers-java#1431]
Currently, I am trying to write integration tests using JUnit 5 and Kafka container.
As I can see, on line 69 of `KafkaContainer` class, broker is accessible only via randomly generated network alias:
```java
withEnv("KAFKA_ADVERTISED_LISTENERS", "BROKER://" + networkAlias + ":9092" + "," + getBootstrapServers());
```
How can make broker visible on localhost?
To be more precise, I would like it to be something like below:
```java
withEnv("KAFKA_ADVERTISED_LISTENERS", "BROKER://" + getContainerIpAddress() + getMappedPort(9092));
```
This way I can run tests locally on my machine as well as on GitLab CI

**Comment by bsideup** [comment]
Hi @voplex95,

There is `getBootstrapServers()` method, you should use it.

**Comment by voplex95** [comment]
@bsideup Thanks, it helped
