### ISSUE TITLE
How can I use the Containers test with a Swarm cluster?

### ISSUE THREAD

**Issue by viniciusxyz** [testcontainers/testcontainers-java#1435]
Good evening everyone,

Today I have a Swarm Hybrid cluster with Linux and Windows, my Jenkins pipelines are configured to run on Windows, but I would like to use SQL Server with Linux container on my linux nodes, is there any way to use Stack Deploy together with the testContainer to ensure that the tests are performed on the correct nodes?

**Comment by kiview** [comment]
Hey @viniciusxyz,
as of now, Testcontainers doesn't support Docker-Swarm. We might add it in the future (maybe as part of the Docker-Compose support or something distinct altogether), but we don't have any concrete plans for this.

**Comment by viniciusxyz** [comment]
thanks for the quick response and great work on the project!
