### ISSUE TITLE
primary index not created when couchbase community edition is used

### ISSUE THREAD

**Issue by martin8877** [testcontainers/testcontainers-java#1440]
Hi, 
primary index is not created when community edition is used:

```
    @ClassRule
    public static CouchbaseContainer container = initCouchbaseContainer();

    private static CouchbaseContainer initCouchbaseContainer() {
        CouchbaseContainer couchbaseContainer = new CouchbaseContainer("couchbase/server:community-6.0.0");
        couchbaseContainer.withClusterAdmin(CLUSTER_USER, PASSWORD);

        final UserSettings communityAdminUserSettings =
                UserSettings.build()
                        .password(PASSWORD)
                        .roles(Collections.singletonList(new UserRole("admin")));

        couchbaseContainer.withNewBucket(getDefaultBucketSettings(), communityAdminUserSettings);
        couchbaseContainer.start();
        return couchbaseContainer;
    }

    protected static BucketSettings getDefaultBucketSettings() {
        return DefaultBucketSettings.builder()
                .enableFlush(true)
                .name(BUCKET_NAME)
                .password(PASSWORD)
                .quota(100)
                .replicas(0)
                .type(BucketType.COUCHBASE)
                .build();
    }
```

I think the problem is that community edition does not support memory_optimized storage mode (configured in CouchbaseContainer):

`
callCouchbaseRestAPI("/settings/indexes", "indexerThreads=0&logLevel=info&maxRollbackPoints=5&storageMode=memory_optimized");`

Only forestdb is supported:
https://docs.couchbase.com/server/6.0/rest-api/post-settings-indexes.html

It would be nice if we could configure storage mode, for example:
`withStorageMode(String storageMode)`

**Comment by juanmanuelz** [comment]
+1 For this feature. I used `container.callCouchbaseRestAPI("/settings/indexes", "indexerThreads=0&logLevel=info&maxRollbackPoints=5&storageMode=forestdb");` to be able to use community edition with this library.

**Comment by rnorth** [comment]
As suggested by @martin8877, a PR to specify a storage mode sounds like a good idea. Contributions would be welcomed!
