### ISSUE TITLE
JUnit Jupiter should include field's name if its type does not implement Startable

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1456]
Relevant code piece:
https://github.com/testcontainers/testcontainers-java/blob/51333a64b596260845c230e15ef038a367833cd2/modules/junit-jupiter/src/main/java/org/testcontainers/junit/jupiter/TestcontainersExtension.java#L91-L104

/cc @wilkinsona

**Comment by rnorth** [comment]
I didn't realise the link at the time, but I believe this is fixed in #1488 which is released in [1.11.3](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.3).
