### ISSUE TITLE
Incorrect Auth encoding

### ISSUE THREAD

**Issue by atomfrede** [testcontainers/testcontainers-java#1466]
I think there is potential bug when parsing/decoding a custom auth config (e.g. for gcr).
We have create a `config.json` which looks like this:

```json
{
  "auths": {
    "eu.gcr.io": {
      "auth": "BASE64-ENCODED-JSON"
    }
  }
}
```

The decoded `auth` contains a [json key file](https://cloud.google.com/container-registry/docs/advanced-authentication?hl=en#json_key_file):

```json
_json_key:{
  "type": "service_account",
  "project_id": "XXX",
  "private_key_id": "XXX",
  "private_key": "XXX",
  "client_email": "XXX",
  "client_id": "XXX",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/...",
  "client_x509_cert_url": "https://www.googleapis.com/..."
}⏎ 
```

In [RegistryAuthLocator#findExistingAuthConfig](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L157) the decoded string is splitted and checked if there are two parts (username & password). This fails for the above json, such that you are not able to pull from a private gcr registry. 

[Docker java](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/DockerConfigFile.java#L208) has similar logic, but limits the amount of splits to two, which results in having `_json_key` as username and the complete json key file definition as password. I have implemented the same splitting in testcontainers and tested it in our environment (using gitlab ci with dind) and pulling from our private gcr registry works just fine. 
If you are okay with that change I can provide a PR for that.

**Comment by rnorth** [comment]
Hi @atomfrede, thanks for raising this - seems worth fixing. If you could please raise a PR I'd really appreciate it!
Thanks

**Comment by atomfrede** [comment]
Sure will do.
