### ISSUE TITLE
Starting stack should fail if an DC error occurs

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#147]
The DockerComposeContainer continued to try the stack despite a configuration error in the YML. Starting from the command line yielded:
`ERROR: Validation failed in file './docker-compose.yml', reason(s)`

Can DCC fail the test the test if it encounters such a fatal condition as `docker-compose` does when starting from the command line?

**Comment by rnorth** [comment]
Hi
I'm working on this, together with #146, to make some fairly major alterations to the docker compose support. My intention is to fix the currently slightly awkward abstraction of the DockerComposeContainer class being a container object in its own right: really, it should be a class that invokes containerized docker-compose as and when necessary to bring up the environment.

This should open more opportunities for cleaning up the logs output, amongst other improvements.

Richard

**Comment by rnorth** [comment]
Refactoring continues on branch - still not implemented fail-fast for docker-compose errors yet I'm afraid.
