### ISSUE TITLE
docker-compose logging at WARN

### ISSUE THREAD

**Issue by ftardif** [testcontainers/testcontainers-java#1472]
if there a reason why these log entries are configured at ERROR ? This looks more like a DEBUG level to me…

2569 [Thread-7] ERROR 🐳 [docker-compose] - Pulling zookeeper       ...  
2569 [Thread-7] ERROR 🐳 [docker-compose] - Pulling broker          ...  
2569 [Thread-7] ERROR 🐳 [docker-compose] - Pulling schema-registry ...  
3392 [Thread-7] ERROR 🐳 [docker-compose] -  
3393 [Thread-7] ERROR 🐳 [docker-compose] - Pulling zookeeper       ... pulling from confluentinc/cp-zook... 
3393 [Thread-7] ERROR 🐳 [docker-compose] -  
3393 [Thread-7] ERROR 🐳 [docker-compose] - Pulling zookeeper       ... digest: sha256:a0577899f62e17d195... 
3393 [Thread-7] ERROR 🐳 [docker-compose] -  
3393 [Thread-7] ERROR 🐳 [docker-compose] - Pulling zookeeper       ... status: image is up to date for c... 
3393 [Thread-7] ERROR 🐳 [docker-compose] -  
3393 [Thread-7] ERROR 🐳 [docker-compose] - Pulling zookeeper       ... done 
3942 [Thread-7] ERROR 🐳 [docker-compose] -  

### thread on slack:
![image](https://user-images.githubusercontent.com/221462/57855300-537e8880-77b8-11e9-847e-3ef59b6e1a33.png)

**Comment by ftardif** [comment]
@kiview  , were you planning to adjust the logging redirection as you were proposing above in a future release?

**Comment by kiview** [comment]
@ftardif Thanks for documenting the issue here.
I think INFO and ERROR/WARN are the correct log level and Docker-Compose is behaving wrongly by sending the pull logs to `stderr`, however we just have to live with this.

Therefore I would propose to send both outputs to our INFO logger, WDYT @rnorth @bsideup?

**Comment by bsideup** [comment]
@kiview I'm okay with that :)

**Comment by rnorth** [comment]
Yeah, fine by me!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ftardif** [comment]
great, thanks guys. 👍
