### ISSUE TITLE
Performance drop with withFileSystemBind

### ISSUE THREAD

**Issue by CSchulz** [testcontainers/testcontainers-java#1474]
I am playing a little bit with testcontainers and noticed the usage `withFileSystemBind` of results into a performance drop.

Following setup is being used:
```
    GenericContainer postgresql = new GenericContainer("postgres:9.5.7")
          .withFileSystemBind("testdata/", "/var/lib/postgresql/data/", BindMode.READ_WRITE)
          .withEnv("POSTGRES_DB", "db")
          .withEnv("POSTGRES_USER", "db")
          .withEnv("POSTGRES_PASSWORD", "db")
          .withCommand("postgres", "-c", "fsync=off");
    postgresql.setPortBindings(Collections.singletonList("5432:5432"));
    postgresql.waitingFor(new LogMessageWaitStrategy()
      .withRegEx(".*database system is ready to accept connections.*")
      .withTimes(2)
      .withStartupTimeout(Duration.of(60, SECONDS)));
    postgresql.start();
```

without `withFileSystemBind`: 9s
with `withFileSystemBind`: 27s

Is there any limiting factor I forgot?

**System info**
JDK 1.8
Docker version 18.09.2, build 6247962
MacOS 10.14.4

**Comment by aguibert** [comment]
How much data is in the `testdata/` folder? I believe all of this data needs to be sent to the docker daemon, which could be where the perf drop is coming from. Also, are you making use of a `.dockerignore` file? I believe the underlying `docker-java` API supports this now.

**Comment by CSchulz** [comment]
We are talking about 46 MB. They are created by the initial database setup of postgres.
