### ISSUE TITLE
Source code does not match byte code for version 1.11.2

### ISSUE THREAD

**Issue by nhooey** [testcontainers/testcontainers-java#1489]
When I select "download sources" in IntelliJ IDEA CE 2019.1, I get the "source code does not match byte code" error, and the breakpoints don't work.

This is for TestContainers version 1.11.2.

**Comment by rnorth** [comment]
This is unfortunately a duplicate of #762. Something we need to fix; there doesn't look to be a great solution to the problem so it's fairly low on our priorities I'm afraid.

Closing as a duplicate.
