### ISSUE TITLE
Add support for localstack's secretsmanager service

### ISSUE THREAD

**Issue by ausarb** [testcontainers/testcontainers-java#1496]
Localstack supports secretsmanager and it would be nice to be able to use testcontainers instead of issuing the following docker command.

`docker run --rm -d -p 4584:4584 -e SERVICES=secretsmanager --name secretsmanager localstack/localstack`

**Comment by rnorth** [comment]
Certainly - this should be coming in #1504!

**Comment by ausarb** [comment]
Closing as fixed by #1504.

**Comment by ausarb** [comment]
Closing as fixed by #1504.
