### ISSUE TITLE
Allow DockerComposeModule to start only certain services

### ISSUE THREAD

**Issue by HaMatthias** [testcontainers/testcontainers-java#1497]
Hi everyone,

Actually I am using the DockerComposeContainer of Testcontainers for CDCTs of my services. For the provider verification it is necessary to start up the services, and that is the part, where Testcontainers helps me out.

Actually, my compose file comprises out of 22 services and 500 lines and I only want to start one of these services. So the enhancement of just starting up certain containers would be a really nice approach to me.

I really would like to see this feature and I will keep following the development of this framework. Thanks to the team of Testcontainers and keep going on like that you helped me a lot!

**Comment by HaMatthias** [comment]
I already did some changes in my fork.
I can make a PR to this, would that be fine ?

**Comment by rnorth** [comment]
Thank you - this sounds like an excellent proposal. 

This actually makes a major improvement for one of my previous personal use cases for this, where I put services in separate docker compose files to enable this kind of split.

Your proposal is much better - thanks!

**Comment by dforegger** [comment]
We're trying to convert over to using the DockerComposeModule and since we're on docker-compose v3 we can't use the `extends` syntax. It'd be a pain to convert over to overrides, so we're really happy to see this and just in the nick of time (for us)! 
Thank you HaMatthias! (and the testcontainers team, of course)

**Comment by rnorth** [comment]
This was released in [1.11.4](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.4) 🎉

**Comment by willianantunes** [comment]
@rnorth I was in need of this feature. I tested with [1.13.0](https://github.com/testcontainers/testcontainers-java/releases/tag/1.13.0) (the latest one now) and sadly it does not work anymore. I had to use [1.11.4](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.4) version instead.
