### ISSUE TITLE
Type-casting issues with fluent interface

### ISSUE THREAD

**Issue by haines** [testcontainers/testcontainers-java#151]
The `Container#self()` method doesn't return the correct type for subclasses of implementations. For example, the following will not compile because `withEnv` returns a `GenericContainer` not a `DockerComposeContainer`:

```
@ClassRule
public static DockerComposeContainer environment =
    new DockerComposeContainer(new File("src/test/resources/compose-test.yml"))
            .withEnv("SOMETHING", "hello world");
```

**Comment by rnorth** [comment]
@haines I think that #238 covers this issue and also includes a workaround, so I'll close this if that's OK with you?

**Comment by haines** [comment]
Yep, that's fine!
