### ISSUE TITLE
When to add etcd Support  ? 

### ISSUE THREAD

**Issue by lovepoem** [testcontainers/testcontainers-java#1515]
When to add [etcd](https://github.com/etcd-io/etcd) Support  ?

**Comment by rnorth** [comment]
Hi @lovepoem 

It's not been something that people have asked for; I only know of one other person who used etcd with Testcontainers.

If we don't have a module for something, then it is still possible for you to use it via the `GenericContainer` class.

I'll leave the ticket open for a little while in case anyone wants to add upvotes or example code for how they've done it.

Richard

**Comment by bsideup** [comment]
For the reference, there is Etcd container class in jetcd:
https://github.com/etcd-io/jetcd/blob/f66c081de1723fc730ad4f72ec3db14c229ac90f/jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdContainer.java

**Comment by lovepoem** [comment]
>  For the reference, there is Etcd container class in jetcd:
https://github.com/etcd-io/jetcd/blob/f66c081de1723fc730ad4f72ec3db14c229ac90f/jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdContainer.java

Thank you , I will have a try. I think the author can donate the code to  https://github.com/testcontainers/testcontainers-java

**Comment by eddumelendez** [comment]
Given there is already a module provided by `etcd` itself and it is well-maintained, the issue will be closed. In the future, we will make sure to list this third-party module.
