### ISSUE TITLE
Generic container fails to start on Gitlab.com CI

### ISSUE THREAD

**Issue by jelovac** [testcontainers/testcontainers-java#1519]
Hi all,

I use test containers for my Gradle multiproject build using Spring Boot 2.

What I am having trouble currently is spawning the GenericContainer which uses mongo image to run my integration tests as part of my GitLab.com CI build.

On my local system everything works fine, running `./gradlew build` the application is built, containers started, tests performed and passed. However when doing the same command as part of CI job on GitLab.com the GenericContainer does not start for some reason.

Here is my gitlab-ci.yml config: [gitlab-ci.txt](https://github.com/testcontainers/testcontainers-java/files/3243422/gitlab-ci.txt)

And this is how I start the GenericContainer:

    @Bean
    public GenericContainer mongoContainer() throws IOException {

        File mongoInitFile = createMongoInitDbScript();
        String mongoInitFilePath = mongoInitFile.getCanonicalPath();

        final GenericContainer mongoContainer = new GenericContainer("mongo:4.0-xenial")
                .withEnv("MONGO_ROOT_USERNAME", mongoRootUsername())
                .withEnv("MONGO_ROOT_PASSWORD", String.valueOf(mongoRootPassword()))
                .withEnv("MONGO_INITDB_DATABASE", mongoDatabase())
                .withFileSystemBind(
                        mongoInitFilePath, 
                        "/docker-entrypoint-initdb.d/init.js", 
                        BindMode.READ_ONLY
                )
                .withExposedPorts(27017)
                .waitingFor(Wait.forListeningPort());

        mongoContainer.start();

        System.setProperty("spring.data.mongodb.host", mongoContainer.getContainerIpAddress());
        System.setProperty("spring.data.mongodb.port", String.valueOf(mongoContainer.getFirstMappedPort()));

        return mongoContainer;
    }

And the following is the summarized error stacktrace:

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.testcontainers.containers.GenericContainer]: Factory method 'mongoContainer' threw exception; nested exception is org.testcontainers.containers.ContainerLaunchException: Container startup failed

...

> Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed

...

> Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception

...

> Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container

...

> Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (docker ports: [32769] should be listening)

Any clues what could be the issue?

**Comment by bsideup** [comment]
hi @jelovac,

Could you please try replacing `withFileSystemBind` with `withCopyToContainer`? It will copy the file instead of doing a file system bind.

I assume the paths are not 1-1 between the Docker daemon in Gitlab and your worker

**Comment by jelovac** [comment]
> hi @jelovac,
> 
> Could you please try replacing `withFileSystemBind` with `withCopyToContainer`? It will copy the file instead of doing a file system bind.
> 
> I assume the paths are not 1-1 between the Docker daemon in Gitlab and your worker

Yep that was it, thank you very much for your help.
