### ISSUE TITLE
[help wanted] How to write integration test with Dubbo and  testcontainers?

### ISSUE THREAD

**Issue by lovepoem** [testcontainers/testcontainers-java#1520]
Hi ,all
    Now I am write integration test case for the [Apache Dubbo](https://github.com/alibaba/dubbo) project . Dubbo is a  java based,  RPC framework.

I will
1. Start a DemoProvider provider service and expose the DemoService. say (String content) service, which is an independent Java process.

2. Start a DemoConsumer consumer service and call the DemoService. say ("hello") method to verify that the return value is correct. This is also an independent Java process.

The DemoConsumer service will call DemoProvider service on Dubbo protocol (a protocol based on TCP)

Excuse me, how can I design this test case with test containers?

**Comment by kiview** [comment]
Hi @lovepoem,

You would need to have a Docker image available (or build it using Testcontainers) of both services.
You can also create a Testcontainers network for your test.
Then you would start each image as a `GenericContainer`, attaching both containers to the network.

Somehow you need to verify the interaction, since I don't now Dubbo, I'm not sure who you stimulate your system under test and how you perform the verification.

Let me try some Pseudocode:

```java
@Test
public void dubboTest() {

    Network dubboNetwork = Network.newNetwork();


    GenericContainer provider = new GenericContainer("demoProvider")
        .withExposedPorts(4711)
        .withNetwork(dubboNetwork)
        .withNetworkAliases("provider");

    GenericContainer consumer = new GenericContainer("demoConsumer")
        .withExposedPorts(4711)
        .withNetwork(dubboNetwork);

    Stream.of(provider, consumer).forEach(GenericContainer::start);

    
    String providerAddress = provider.getContainerIpAddress() + ":" + provider.getFirstMappedPort();
    String consumerAddress = consumer.getContainerIpAddress() + ":" + consumer.getFirstMappedPort();

    dubboClient.callMethod(providerAddress, "myString");

    assert dubboClient.callMethod(consumerAddress).equals("myString");

}
```

**Comment by lovepoem** [comment]
> Hi @lovepoem,
> 
> You would need to have a Docker image available (or build it using Testcontainers) of both services.
> You can also create a Testcontainers network for your test.
> Then you would start each image as a `GenericContainer`, attaching both containers to the network.
> 
> Somehow you need to verify the interaction, since I don't now Dubbo, I'm not sure who you stimulate your system under test and how you perform the verification.
> 
> Let me try some Pseudocode:
> 
> ```java
> @Test
> public void dubboTest() {
> 
>     Network dubboNetwork = Network.newNetwork();
> 
> 
>     GenericContainer provider = new GenericContainer("demoProvider")
>         .withExposedPorts(4711)
>         .withNetwork(dubboNetwork)
>         .withNetworkAliases("provider");
> 
>     GenericContainer consumer = new GenericContainer("demoConsumer")
>         .withExposedPorts(4711)
>         .withNetwork(dubboNetwork);
> 
>     Stream.of(provider, consumer).forEach(GenericContainer::start);
> 
>     
>     String providerAddress = provider.getContainerIpAddress() + ":" + provider.getFirstMappedPort();
>     String consumerAddress = consumer.getContainerIpAddress() + ":" + consumer.getFirstMappedPort();
> 
>     dubboClient.callMethod(providerAddress, "myString");
> 
>     assert dubboClient.callMethod(consumerAddress).equals("myString");
> 
> }
> ```
@kiview thank you very much . I will have a try .

**Comment by rnorth** [comment]
@lovepoem were you able to try? Please let us know so we can close the ticket.
