### ISSUE TITLE
Introduce new Aerospike module

### ISSUE THREAD

**Issue by maxkraynov** [testcontainers/testcontainers-java#153]
We're using the same approach in our project for testing integration with [Aerospike](http://www.aerospike.com/). Here is our library - [embedded-aerospike](https://github.com/getintent/embedded-aerospike). @bsideup said us about testcontainers-java, and we've decided to join with your project. If you don't mind, I'd like to add new **aerospike** module.

**Comment by bsideup** [comment]
Hi. First of all, thanks for your contribution!

However, I think if TestContainers will add all such modules to the main repository, test execution time will grow really fast. 

@rnorth WDYT if we will create separate repositories for integrations? i.e. `testcontainers/aerospike` or something?

**Comment by maxkraynov** [comment]
@bsideup sounds good

**Comment by rnorth** [comment]
@maxkraynov thanks - that's awesome 😄 !

Yes, this sounds like a good idea to me. I'd like to move the Virtuoso module out in such a way too, as there have been problems with the upstream container image and this gives us a bit more isolation.

@maxkraynov if you'd like to put the minimal elements together into a repo, let's collaborate on setting up  the remaining boilerplate/CI/docs etc for this.

Thank you!

**Comment by bsideup** [comment]
@rnorth then I think we can start with Virtuoso to provide an example of such 3rd party module, then @maxkraynov can contribute aerospike in the same way with Virtuoso as an example

**Comment by rnorth** [comment]
If we manage to get the Virtuoso module extracted ahead of when @maxkraynov wants to integrate, of course that's the most logical sequence.
I'm going on holiday in a couple of days, so don't want to be the bottleneck on this if I don't have time, that's all! 

@maxkraynov roughly when do you think you'd be ready to do this? If you've got something almost ready to go we could do it together with Virtuoso, but if you need a bit of time do you mind waiting a couple of weeks for an exemplar project?

**Comment by bsideup** [comment]
@rnorth I think can help you and extract Virtuoso :)

**Comment by rnorth** [comment]
@bsideup thanks!

**Comment by bsideup** [comment]
@rnorth :+1: I will do it soon and help @maxkraynov, so no worries, continue with refactorings, I'll take care :)

**Comment by maxkraynov** [comment]
Thank you very much @rnorth and @bsideup for your help! Right now, I'm going to vacation and I'd be ready to contribute aerospike module at the end of next week. I think Virtuoso module will be extracted by this time.

**Comment by maxkraynov** [comment]
Guys, I'm sorry for confusion, I had to read documentation carefully. Aerospike is NoSQL database and Generic container is perfect for it. 

```java
    public static GenericContainer aerosike =
            new GenericContainer("aerospike:latest")
                    .withExposedPorts(3000)
                    .withClasspathResourceMapping("aerospike.conf", "/etc/aerospike/aerospike.conf", BindMode.READ_ONLY);
```

Anyway, decomposing of modules is good idea. I think we can close this issue, but if you need more hands I'd like to help you with TestNG integration ticket.

**Comment by bsideup** [comment]
@maxkraynov great! :D I'm happy to see that GenericContainer is generic enough for your case as well :D

**Comment by brushmate** [comment]
Hey @bsideup & @rnorth! I saw that there is a Aerospike module for Testcontainers for Go which led to the question if you still think that there should not be a dedicated module for Testcontainers for Java?
