### ISSUE TITLE
Javadoc seems to be unavailable because of S3 permissions?

### ISSUE THREAD

**Issue by jennyowen** [testcontainers/testcontainers-java#1531]
Hi, I'm not sure if this is the best place to report this but...

It looks like the java doc links on the website are linking to some pages that are giving an Access Denied error, that looks a lot like an S3 message.

For example:
https://www.testcontainers.org/features/startup_and_waits/

Links to:
https://static.javadoc.io/org.testcontainers/testcontainers/1.11.3/org/testcontainers/containers/wait/strategy/WaitStrategy.html

Which to me is just:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AA54F0EA1955349C</RequestId>
<HostId>
AZBkjSKwN7Jm8g2+Fr1wqMkNJ+eAgxu8VNwten8KUjLL1nOaOpeFL8g7MZdP6W4STOaXD/sAyY0=
</HostId>
</Error>
```
Possibly your link is out of date, or maybe the hosting service is broken?
Your older documentation seems to still be available here: https://javadoc.io/doc/org.testcontainers/testcontainers/1.11.2

**Comment by kiview** [comment]
Thanks for pointing this out, you are right.
We (meaning @rnorth :wink: ) will look into it.

**Comment by eddumelendez** [comment]
Nowadays, javadocs can be found at https://javadoc.io/doc/org.testcontainers/testcontainers/latest/index.html
