### ISSUE TITLE
DockerComposeContainer may exit before the "is running" check

### ISSUE THREAD

**Issue by haines** [testcontainers/testcontainers-java#154]
I'm running a test in debug mode through IntelliJ and I think the execution is slow enough that the `docker-compose` process exits successfully before the check for `isContainerRunning`, so fails with `"Container has already stopped."`

**Comment by rnorth** [comment]
Can you think of a way to reliably reproduce this? 😄

**Comment by haines** [comment]
You could chuck a breakpoint in between the container starting and the running check to pause execution until docker-compose has exited?

**Comment by rnorth** [comment]
I was thinking something more like an automated test 😉 
But yes, I can use this too.

I suspect that #156 might have resolved this (though it's incomplete) - in any event I'll probably aim to fix this on the #156 branch.

**Comment by rnorth** [comment]
Should be resolved in the #156 branch through use of [OneShotStartupCheckStrategy](https://github.com/testcontainers/testcontainers-java/blob/docker-compose-refactor/core/src/main/java/org/testcontainers/containers/startupcheck/OneShotStartupCheckStrategy.java)
