### ISSUE TITLE
How to use Testcontainers with Bamboo CI?

### ISSUE THREAD

**Issue by Muraligowtham** [testcontainers/testcontainers-java#1540]
Team, 
We are using bamboo for our CI. In this case, How can I run my integration tests inside the bamboo agent docker?

TIA

**Comment by kiview** [comment]
You can either use docker socket mounting or dind. This doesn't seem to be a Testcontainers related question, but more general Docker usage and CI setup.

Or is there anything Testcontainers specific that I'm missing here?

**Comment by rnorth** [comment]
@Muraligowtham please see https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/ for more information on what @kiview has said.

**Comment by Muraligowtham** [comment]
Hi @kiview / @rnorth ,
Sorry If my question was unclear.

**Comment by Muraligowtham** [comment]
Hi @kiview / @rnorth,
Sorry if my question was unclear.

**Comment by Muraligowtham** [comment]
Hi @kiview / @rnorth ,
I got the docker inside docker working in my local. Thanks you for the documentation.
