### ISSUE TITLE
Apache Solr Support!

### ISSUE THREAD

**Issue by aadrian** [testcontainers/testcontainers-java#1562]
Please add support for [Apache Solr](http://lucene.apache.org/solr/) too. It already has an official [Docker Image](https://docs.docker.com/samples/library/solr/).

Thank you.

**Comment by aadrian** [comment]
> If you believe this is a mistake, please reply to this comment to keep it open

Of course it's a mistake to just close issues :)

**Comment by rnorth** [comment]
We have some guidelines on contributing new modules - I'll link. If people think this would meet the criteria and someone is willing to contribute, then we'd be happy to review a PR!

**Comment by raynigon** [comment]
Hi @rnorth,

i think the world needs to have solr Testcontainers.
Too many people are using embedded Solr for testing...
Here is my proposal for an implementation.
If you have any ideas how to improve the implementation, please let me know.
If this PR doesnt fit your criterias, please also let me know what i can to to meet them.
Thanks for reviewing.
Have a nice day :D

**Comment by raynigon** [comment]
> We have some guidelines on contributing new modules - I'll link. If people think this would meet the criteria and someone is willing to contribute, then we'd be happy to review a PR!
> 
> https://www.testcontainers.org/contributing/

Hi @rnorth ,

would be nice if you could review this [PR](https://github.com/testcontainers/testcontainers-java/pull/2123). 
If this PR doesnt fit your expectations for a module, or your currently busy with other important work, please let me know.

**Comment by raynigon** [comment]
@stalebot The PR just waits to be merged ;)
