### ISSUE TITLE
Windows + docker in vagrant, EnvironmentAndSystemPropertyClientProviderStrategy don't work

### ISSUE THREAD

**Issue by Benoit2R** [testcontainers/testcontainers-java#1573]
Hi,

My issue looks like similar than #291: my setup is testContainers on windows that I need to connect to a docker daemon inside a vagrant box with port 2300 forwarded.

I have 3 environment variables set ;
DOCKER_HOST=tcp://%COMPUTERNAME%:2300
DOCKER_CERT_PATH=C:\git_clones\acs-localdev\docker-cert (shared forder in vagrant box)
DOCKER_TLS_VERIFY=1

I tried with docker-java (3.1.2) and spotify docker-client (8.16.0) ant it works near out-of-the-box:
```
  public static void dockerClient() throws Exception {
    final DockerClient docker = DefaultDockerClient.fromEnv()
        .build();
    // Pull an image
    docker.pull("couchbase/server:enterprise-5.5.3");
    docker.close();
  }
```

```
  public static void dockerJava() throws Exception {
    com.github.dockerjava.api.DockerClient dockerClient = DockerClientBuilder.getInstance()
        .withDockerCmdExecFactory(new JerseyDockerCmdExecFactory())
        .build();
    List<Container> containers = dockerClient.listContainersCmd().exec();
    dockerClient.close();
  }
```

But I'm unable to make it work with testcontainers, all the provider strategies failed.
ping fails with a javax.net.ssl.SSLPeerUnverifiedException: Hostname xxx not verified

How can I bypass it ?

**Comment by kiview** [comment]
Just to get some context, why aren't you using docker-machine?

**Comment by Benoit2R** [comment]
Because I have to use the stack given by the tools team of my company.

**Comment by alinbutura** [comment]
Is there a plan to merge this PR in the near future? I am facing the same error and I was wondering if I should wait for the new release.
Thank you!
