### ISSUE TITLE
Add Support For MongoDB

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1574]
On going through documentation I can't find support fr MongoDB.
https://www.testcontainers.org
Kindly add support for MongoDB as well.

**Comment by bsideup** [comment]
MongoDB was added as an example in #1288 instead of a module because it is too simple:
https://github.com/testcontainers/testcontainers-java/tree/master/examples/mongodb-container

**Comment by ankurpathak** [comment]
What is the issue in adding the new module for MondoDB? Its might be simple but inbuild support for help community a lot as MongoDB is very widely used Document Store. If current contributors have less time to work they can invite community to join and work on it as a PR. We are supporting many databases and we must add support for MongoDB as well.

**Comment by bsideup** [comment]
@ankurpathak
every new module adds an overhead to our CI, maintainability and release process.

> We are supporting many databases and we must add support for MongoDB as well.

Testcontainers project provides support for many databases that are not trivial to use with `GenericContainer` only.

In case of MongoDB, we're talking about the following lines:
```java
new GenericContainer("mongo:4.0").withExposedPort(27017);
```

Why would you need a dedicated module for that? Isn't it leftpad-ish?

**Comment by ankurpathak** [comment]
This example work like a champ. @bsideup I agree with u.

**Comment by ankurpathak** [comment]
@bsideup MongoDB 4 support Trnsactions. But to test those transactions we need run MongoDb in
Replica Set mode,and its a pain. Can we add a new module for MongoDb to support replica set mode
or give an example for same. So we can test MongoDb Transactions. 
Here is a reference url for same:
https://www.baeldung.com/spring-data-mongodb-transactions
