### ISSUE TITLE
[help wanted] Reuse container instance in Gradle multi module project

### ISSUE THREAD

**Issue by Mawster** [testcontainers/testcontainers-java#1582]
Hi guyz,

we have multiple modules which have their own subset of entities. Actually the domain is quite big (grew over time as always) - so the initial construction of the database (we are using an oracle 18c container) needs quite some time and we want to reuse the database container in each module. Actually the container is built up every time the tests of a new module trigger.

Anyone an idea? Would be really helpful.

Thanks in advance

**Comment by jannis-baratheon** [comment]
How do you prepare your database container? Do every test have it's own set of data? Do the tests set up the data they need on their own or are the datasets prebuilt into the container?

**Comment by Mawster** [comment]
Hi @jannis-baratheon,

sorry for my late reply. We are using junit with a BeforeAllCallback:

```
class TestcontainersExtension : BeforeAllCallback {
    override fun beforeAll(context: ExtensionContext?) {
        val dbContainer = CustomOracleContainer.INSTANCE
    }
}

class CustomOracleContainer private constructor() : OracleContainer(IMAGE_VERSION) {
    companion object {
        private const val IMAGE_VERSION = "registry.company.cc/oracle-xe-mini:18.4.0-xe"
        private val container: CustomOracleContainer = CustomOracleContainer()

        val INSTANCE: CustomOracleContainer
            get() = if (container.isRunning) container else {
                container.withUsername("test").withPassword("test").withInitScript("schema.sql").start()

                container
            }
    }

    override fun getSid(): String {
        return "XS"
    }

    override fun start() {
        super.start()
        System.setProperty("DB_URL", container.jdbcUrl)
        System.setProperty("DB_USERNAME", container.username)
        System.setProperty("DB_PASSWORD", container.password)
    }

    override fun stop() {
        //do nothing, JVM handles shut down
    }
}
```
In fact it works pretty well - the container gets started on each module test run, but the build up of the container needs around 2 minutes. There are too much modules so we would like to start the container once and just reuse it.

Do every test have it's own set of data? Do the tests set up the data they need on their own or are the datasets prebuilt into the container?
Unfortunately not. The used schema.sql builds up the database with needed base data.

**Comment by jannis-baratheon** [comment]
How do you run your tests? Are the tests for each module run in a different JVM?

**Comment by kiview** [comment]
Hey @Mawster,

So if you are running each module tests in the same JVM process, you can fall back to using [Singleton Container Pattern](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/), that's also what I would recommend for this use case.

If you are spawning new JVM processes, Ryuk will at one point clean up the old container once the process finished, no matter what.

The other thing you can think about is baking this code into your image:
```
container.withUsername("test").withPassword("test").withInitScript("schema.sql").start()
```
So building a custom image with the `schema.sql` already applied. This will of course only work if the processing of this file is your pain point. If the the actual container startup is slow, this won't help.

As a side note, @bsideup is currently working on a reusable container feature, but this would not be intended for this use case (it's suited towards faster TDD cycles).

**Comment by Mawster** [comment]
hi @jannis-baratheon, hi @kiview ,

thanks for your replies! 

"Are the tests for each module run in a separate JVM process?" 
It seems that gradle spins up a JVM for every module. Looked through the documentation but didn't see any possibility to restrict gradle to just use one JVM and run all tests on that JVM.

"So building a custom image with the schema.sql already applied. This will of course only work if the processing of this file is your pain point. If the the actual container startup is slow, this won't help."
Will try this and check the test time. If this is also not a solution maybe I will use the gradle-docker plugin with our oracle image.

Thanks for your help guyz!

**Comment by jannis-baratheon** [comment]
Keep an eye on #781 @Mawster. I think this is what you're looking for.

**Comment by Mawster** [comment]
Thanks - subscribed ;)
