### ISSUE TITLE
Add Support For Redis

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1595]
On going through documentation I can't find support for Redis.
https://www.testcontainers.org
Kindly add support for Redis as well.

**Comment by bsideup** [comment]
Hi. The same as in #1574 - it is too simple:
```
new GenericContainer("redis").withExposedPorts(6379);
```

See this example:
https://github.com/testcontainers/testcontainers-java/blob/master/examples/redis-backed-cache/src/test/java/RedisBackedCacheTest.java#L18-L20
