### ISSUE TITLE
How to load container from tar?

### ISSUE THREAD

**Issue by TannerYoung** [testcontainers/testcontainers-java#1598]
Is it possible to load a container from a tar file (generated from docker save), instead of from a registry? This container is local only, and I don't want to depend on it being in the local registry.

Thoughts on how I could accomplish this?

**Comment by kiview** [comment]
It's not possible with Testcontainers, but how does your use case work?
You can e.g. just run the `docker load` command from the CLI before running your tests.

If you have to do it from your test code, you can fallback to the underlying `docker-java` client in Testcontainers and use [LoadImageCmd](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/LoadImageCmd.java).

Does this answer your question?

**Comment by TannerYoung** [comment]
Yeah, I ended up loading it from the underlying docker client api. This works, but the load api is a bit lacking; (it returns void instead of information about the image such as the container name).

My use case was for repeatable tests in bazel - I have a test bazel target which depends on the output of a container image bazel target. The image target builds a tar file for which can then be loaded into a docker registry. Having the tar file makes the test hermetic (it doesn't have to depend on the external registry being set up properly).

**Comment by bsideup** [comment]
Interesting. From the API description ( https://docs.docker.com/engine/api/v1.24/#32-images ) I see that it returns the image id:
```
HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked

{"status":"Loading layer","progressDetail":{"current":32768,"total":1292800},"progress":"[=                                                 ] 32.77 kB/1.293 MB","id":"8ac8bfaff55a"}
{"status":"Loading layer","progressDetail":{"current":65536,"total":1292800},"progress":"[==                                                ] 65.54 kB/1.293 MB","id":"8ac8bfaff55a"}
{"status":"Loading layer","progressDetail":{"current":98304,"total":1292800},"progress":"[===                                               ]  98.3 kB/1.293 MB","id":"8ac8bfaff55a"}
{"status":"Loading layer","progressDetail":{"current":131072,"total":1292800},"progress":"[=====                                             ] 131.1 kB/1.293 MB","id":"8ac8bfaff55a"}
...
{"stream":"Loaded image: busybox:latest\n"}
```

but Docker Java does not expose it. I would suggest raising a ticket in https://github.com/docker-java/docker-java, as we depend on it

**Comment by TannerYoung** [comment]
Looks like there already is an issue there:

https://github.com/docker-java/docker-java/issues/1194

I'll comment on it.
