### ISSUE TITLE
Make it possible to automatically rerun selected flaky tests

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1629]
There are a few tests that fail due to the underlying Docker issues. Some examples:

- shared memory test - fails from time to time on Azure Pipelines
- [stdout/stderr ordering](https://github.com/testcontainers/testcontainers-java/blob/4373d1fb3540aea5be684daf32ab4b0eec7cb0cb/core/src/test/java/org/testcontainers/containers/output/ContainerLogsTest.java#L16)
- Couchbase k/v

Since we agreed in #1594 that we should only rerun the tests that are known to be flaky, we should have a mechanism (e.g. with a help form JUnit) to rerun them automatically, N times (where N is ~1..3)

Such test cases (important! not classes) should be explicitly marked (e.g. with an annotation) as flaky. This will also make it possible to find usages of that annotation and discover all flaky tests in the project.

---
"Flaky test" here means a test that fails randomly, due to some timing issues, or CIs problem with resource allocation or the underlying Docker issues

**Comment by bsideup** [comment]
If somebody wants to work on this, please comment here, to avoid multiple contributors working on the same task.

**Comment by chungngoops** [comment]
I would like to work on this issue.

**Comment by bsideup** [comment]
@chungngoops thank you! Feel free to ask any questions you have before implementing it 👍

**Comment by bsideup** [comment]
FYI the current state can be found here:
https://github.com/testcontainers/testcontainers-java/pull/1680

**Comment by rnorth** [comment]
@chungngoops I wanted to have a play with one possible way of doing it in #1680, as it's causing us a lot of pain at the moment (our build should not be failing as it is right now, and we need to fix this urgently).

Consider #1680 an experimental approach though - if you have a better way, it'd be good to hear about it.

**Comment by chungngoops** [comment]
@rnorth: I have a similar approach, mine just directly implement `TestRule` interface.
I think you can have a variable to define how many time should we re-run a flaky test.

**Comment by rnorth** [comment]
@chungngoops thanks - I think being able to specify the number of retries is a nice thing to have, so I will add as an annotation property.

Shall we just use #1680? I think I'd like to try and complete this before next week.
