### ISSUE TITLE
Docker 1.12 support: "starting container with HostConfig was deprecated since v1.10 and removed in v1.12"

### ISSUE THREAD

**Issue by haines** [testcontainers/testcontainers-java#163]
This looks like an upstream issue with docker-java, but I can't quite reconcile it -- it looks like the deprecated options were removed some time ago (docker-java/docker-java#248)

```
org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:239)
	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:160)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	... 33 more
Caused by: org.testcontainers.shaded.com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.testcontainers.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.testcontainers.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:182)
```

**Comment by rnorth** [comment]
Yes, it's docker-java/docker-java#615. Which version of docker is this
affecting you on?

On Wed, 22 Jun 2016 at 15:15 Andrew Haines <notifications@github.com> wrote:

> This looks like an upstream issue with docker-java, but I can't quite
> reconcile it -- it looks like the deprecated options were removed some time
> ago (docker-java/docker-java#248
> <https://github.com/docker-java/docker-java/pull/248>)
>
> org.testcontainers.containers.ContainerLaunchException: Could not create/start container
>     at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:239)
>     at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:160)
>     at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
>     ... 33 more
> Caused by: org.testcontainers.shaded.com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
>
>     at org.testcontainers.shaded.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
>     at org.testcontainers.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
>     at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
>     at org.testcontainers.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
>     at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
>     at org.testcontainers.shaded.com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
>     at org.testcontainers.shaded.com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
>     at org.testcontainers.shaded.com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
>     at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
>     at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
>     at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:182)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/testcontainers/testcontainers-java/issues/163>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAIET5KzzhFzXpj7yc8FLqUC6Hvy_vguks5qOUOUgaJpZM4I71Ia>
> .
>
-- 
Richard

**Comment by haines** [comment]
I'm on 1.12.0-rc2, installed via Docker for Mac beta16 (build: 9493)

**Comment by sevikkk** [comment]
I can confirm this issue on Docker for Mac.

Looks like it's built not from official github Docker repo, as code it repo still considers HostConfig as a warning, not error.

This issue breaks PyCharm support for Docker as well.

**Comment by sevikkk** [comment]
DockerVersion 1.12.0-rc2-beta16 (build: 9493)
f615be9fb245904fbdf1aa0cad251d418c869428

**Comment by rnorth** [comment]
Which version of Testcontainers is this affecting you on? The main 1.0.5 release?

I've been mainly working on the [docker-compose-refactor](https://github.com/testcontainers/testcontainers-java/tree/docker-compose-refactor) branch recently, but have gone back to its predecessor [1.1-rc1](https://github.com/testcontainers/testcontainers-java/tree/1.1-rc1) branch to test - that seems to be working.

I'd like to try and get the 1.1 release out this weekend for Docker for Mac support, so I hope this will help. Any extra testing would be much appreciated, though.

**Comment by sevikkk** [comment]
Sorry, I'm not using testcontainers, I've got to this issue from docker-java/docker-java#615

**Comment by margic** [comment]
I see this error with the integration tests in the docker-java directly using 1.12 server api. The unit tests pass ok.

**Comment by stepan-romankov** [comment]
+1

**Comment by rnorth** [comment]
@margic it sounds like you're encountering this problem on the docker-java project, not the testcontainers project which this ticket belongs to. Is that correct?

@stepan-romankov similarly, are you a testcontainers user?

**Comment by IhabSoliman** [comment]
Here they pushed changes to fix this issue

https://github.com/fsouza/go-dockerclient/issues/537

**Comment by rnorth** [comment]
I'd be interested to see if this is occurring for people now with Testcontainers v1.1.0 and Docker for Mac beta releases - it works for me.

**Comment by IhabSoliman** [comment]
I get this on linux
```
2:30:40.262 [main] ERROR o.t.d.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause ChannelException (epoll_create1() failed: Too many open files)
12:30:40.266 [pool-1-thread-2] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@5f7506c0
12:30:40.266 [main] ERROR o.t.d.DockerClientProviderStrategy -     DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (docker-machine executable was not found on PATH (...)
```
On Mac I get this
```
13:18:28.086 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@6cd40e18
13:18:28.087 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@7c041201
13:18:28.087 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@4c1ffadc
13:18:28.090 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@4c244638
13:18:28.090 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@4c256a
13:18:28.091 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@5c84bb78
13:18:28.091 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@6ffe732e
13:18:28.092 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@185ed6f
13:18:28.092 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@6003ff40
13:18:28.092 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@19a5c743
13:18:28.093 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@55ea05a
13:18:28.093 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@2b9ecb0b
```
in a loop that never ends

**Comment by IhabSoliman** [comment]
Also, found this in the logs
```13:41:52.488 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@b115c37
13:41:52.488 [pool-1-thread-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.netty.exec.PingCmdExec@6d6a1fee
13:41:52.493 [main] DEBUG o.t.d.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause NativeIoException (newSocketDomain() failed: Too many open files)
13:41:52.493 [main] INFO  o.t.d.DockerClientProviderStrategy - Looking for Docker environment. Trying docker-machine
```

**Comment by rnorth** [comment]
@IhabSoliman thanks - those logs you've pasted look like a different thing to what's in this ticket, but do look like #170. Let's continue that analysis over there.

**Comment by IhabSoliman** [comment]
Ah sorry, mixed up tabs, yea your right.

**Comment by rnorth** [comment]
I'm inclined to mark as closed, since I've not been able to reproduce since the earlier dev version of DfM support, and since there have been no reports since 1.1.0.
