### ISSUE TITLE
copyFileFromContainer - is there a way to copy a folder?

### ISSUE THREAD

**Issue by chomhanks** [testcontainers/testcontainers-java#1647]
I am using `copyFileFromContainer` to copy a specific file. Often, I am not sure about the name of the file ahead. I want to copy the entire folder to a temp directory and want to perform some operations to find the file. Is there a way we can copy the entire folder? 

I am using: 

`genericContainer.copyFileFromContainer("/data/lib/com/printing-out-params-5.jar",
                                        tempFilePath.toAbsolutePath().toString());`

**Comment by chomhanks** [comment]
Can I please get an answer to this question ^^?

**Comment by silver-mx** [comment]
An alternative approach is to create a tar.gz file to include the target folder and then copy the tar.gz file:

```
container.execInContainer("tar",  "-czvf", "/tmp/tarFileName.tar.gz", "/targetFolder")
container.copyFileFromContainer("/tmp/tarFileName.tar.gz", "/folder-to-copy/tarFileName.tar.gz")
```

**Comment by LvargaDS** [comment]
Another approach is to copy file by file... You can use my gist if you want. There is also sample usage https://gist.github.com/LvargaDS/da3562c57abffb6edaa4c32ccefa0350

**Comment by gianninia** [comment]
> An alternative approach is to create a tar.gz file to include the target folder and then copy the tar.gz file:
> 
> ```
> container.execInContainer("tar",  "-czvf", "/tmp/tarFileName.tar.gz", "/targetFolder")
> container.copyFileFromContainer("/tmp/tarFileName.tar.gz", "/folder-to-copy/tarFileName.tar.gz")
> ```

As the image from my container doesn't have any tar or zip installed, I ended up using the `ls` command to list the files and copied file by file recursively. Here is the code (in Kotlin) in case someone wants to use (or get inspired by) this approach:
```kotlin
fun GenericContainer<*>.copyFolderContentFromContainer(containerPath: String, destinationPath: String) {
    // ls -p -1 -> -p adds a / to directories and -1 prints each file in a separate line
    execInContainer("ls", "-p", "-1", containerPath).stdout
        .lineSequence().mapNotNull { it.emptyToNull() }
        .forEach { fileName ->
            if (fileName.endsWith('/')) {
                val folderName = fileName.substringBeforeLast('/')
                File(destinationPath, folderName).mkdirs()
                copyFolderContentFromContainer("$containerPath/$folderName", "$destinationPath/$folderName")
            } else {
                copyFileFromContainer("$containerPath/$fileName", "$destinationPath/$fileName")
            }
        }
}
```
