### ISSUE TITLE
Add Support For RabbitMQ

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1648]
On going through documentation I can't find support for RabbitMq(https://www.rabbitmq.com).
https://www.testcontainers.org
Kindly add support for  RabbitMq as well.

**Comment by bsideup** [comment]
Duplicate of #1447

**Comment by ankurpathak** [comment]
@bsideup I can see #1447 merged. Which version will have that module for rabbit mq?

**Comment by bsideup** [comment]
@ankurpathak it is released in 1.12.0
