### ISSUE TITLE
jacoco cannot instrument classes when using testcontainers

### ISSUE THREAD

**Issue by kunickiaj** [testcontainers/testcontainers-java#165]
Haven't done too much digging yet, but I noticed that any integration tests which use testcontainers don't show up in the instrumented classes list in a jacoco coverage report resulting in coverage of 0%. Commenting out any use of testcontainers (and allowing the tests to file) will result in properly instrumented classes.

Does testcontainers rewrite any of the class files when it runs?

**Comment by kunickiaj** [comment]
I think this may actually be related to issue #163 so closing for now.

**Comment by rnorth** [comment]
Hi Adam
I've not tested this in conjunction with jacoco., but there shouldn't be
any big issues I can foresee You say you think this relates to #163, but
that's a pretty different issue which I can't see how could be linked to
use of Jacoco. Is this just a case of mysterious symptoms/coincidence
leading you to think that jacoco was involved in the problem?

I'd just like to be confident that you've not encountered #163 plus another
unknown bug at the same time :)

Thanks
Richard

On Tue, 28 Jun 2016 at 02:34 Adam Kunicki <notifications@github.com> wrote:

> Closed #165
> <https://github.com/testcontainers/testcontainers-java/issues/165>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/testcontainers/testcontainers-java/issues/165#event-705744872>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIET0k2ZvSWXP3fvIFPOuBIuyNsa-iGks5qQHo3gaJpZM4I_p_S>
> .
>
-- 
Richard

**Comment by kunickiaj** [comment]
Created a fresh setup with a downgraded docker and it was def just #163. Was a bit too quick to open an issue. 



		_____________________________

**Comment by rnorth** [comment]
Cool, no probs. Thanks for the update!
On Tue, 28 Jun 2016 at 08:18 Adam Kunicki <notifications@github.com> wrote:

> Created a fresh setup with a downgraded docker and it was def just #163.
> Was a bit too quick to open an issue.
>
>
>
> _____________________________
> From: Richard North <notifications@github.com>
> Sent: Tuesday, June 28, 2016 12:16 AM
> Subject: Re: [testcontainers/testcontainers-java] jacoco cannot instrument
> classes when using testcontainers (#165)
> To: testcontainers/testcontainers-java <
> testcontainers-java@noreply.github.com>
> Cc: Adam Kunicki <kunickiaj@gmail.com>, State change <
> state_change@noreply.github.com>
>
>
> Hi Adam
> I've not tested this in conjunction with jacoco., but there shouldn't be
> any big issues I can foresee You say you think this relates to #163, but
> that's a pretty different issue which I can't see how could be linked to
> use of Jacoco. Is this just a case of mysterious symptoms/coincidence
> leading you to think that jacoco was involved in the problem?
>
> I'd just like to be confident that you've not encountered #163 plus another
> unknown bug at the same time :)
>
> Thanks
> Richard
>
> On Tue, 28 Jun 2016 at 02:34 Adam Kunicki <notifications@github.com>
> wrote:
>
> > Closed #165
> > <https://github.com/testcontainers/testcontainers-java/issues/165>.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/testcontainers/testcontainers-java/issues/165#event-705744872
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAIET0k2ZvSWXP3fvIFPOuBIuyNsa-iGks5qQHo3gaJpZM4I_p_S
> >
> > .
> >
> --
> Richard
>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/testcontainers/testcontainers-java/issues/165#issuecomment-228970944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIET1Z-Nhy6y7KXqMimapY7vzWt_pIsks5qQMragaJpZM4I_p_S>
> .
>
-- 
Richard

**Comment by Asisranjan** [comment]
Is it solved. In my case, I am not able to get code coverage as though I am able to attach jacoco agent to container. I am trying with -javaagent:/tmp/conf/jacocoagent.jar=output=file,destfile=/opt/test.exec


It is possible to get coverage report if I pass output as tcpserver instead of output=file. But in this case I have to make explicitly send http request. I am not sure how should I do this in test container.
I mean as per my knowledge the container terminated immediately after test completed. Could you please suggest how to handle it or is there any other mechanism to extract code coverage.
