### ISSUE TITLE
Deprecated MySQL class name is used

### ISSUE THREAD

**Issue by idontusenumbers** [testcontainers/testcontainers-java#1655]
Starting a MySQL container results in:
```
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary
```

**Comment by idontusenumbers** [comment]
Flyway does some fancy detection here
https://github.com/flyway/flyway/blob/bf6eaae95837876a80e55771fdce6abab9c536c6/flyway-core/src/main/java/org/flywaydb/core/internal/jdbc/DriverDataSource.java

**Comment by rnorth** [comment]
Yeah, this is a bit an annoying to see in logs.

We could probably do some simple detection of the current versus legacy driver when we determine which to use.

A PR to improve this would be welcomed!

**Comment by turackangal** [comment]
Hello rnorth,
Can I work on this issue ?
