### ISSUE TITLE
How to run two containers using testcontainers

### ISSUE THREAD

**Issue by Asisranjan** [testcontainers/testcontainers-java#1662]
In my test class, i want to run two container for example, database container and application container. But Always it is running application container. here is my sample code.

public class Test
{
    int hostPort = 3000;
    int containerExposedPort = 3000;
    Consumer<CreateContainerCmd> cmd = e -> {
        e.withPortBindings(new PortBinding(Ports.Binding.bindPort(hostPort),
                new ExposedPort(containerExposedPort)));
        e.withHostName("db-host");
        e.withName("db-container-name");
    };

    Consumer<CreateContainerCmd> cmd1 = e -> {
        e.withPortBindings(new PortBinding(Ports.Binding.bindPort(8080),
                new ExposedPort(8080)));
        e.withHostName("app-host");
        e.withName("app-container-name");
    };

    @Rule
    public GenericContainer db = new GenericContainer(
            "db:latest")
            .withExposedPorts(containerExposedPort)
            .withClasspathResourceMapping("db.conf",
                    "db.conf", BindMode.READ_ONLY)
            .withCommand("--config-file db.conf")
            .withCreateContainerCmdModifier(cmd);

    @Rule
    public GenericContainer app = new GenericContainer(
            "app:latest")
            .withExposedPorts(8080)
            .withCreateContainerCmdModifier(cmd1);   

    @Test
    public void test()
    {
		System.out.println("asis");
    }
}

**Comment by Krishan-Sharma** [comment]
Hi @Asisranjan,

Do you see any errors reported by TestContainers in this particular scenario? Would you be able to post that error message? I tried something similar to your code and it worked. Here is the working code:

public class TwoContainerTest {
    Consumer<CreateContainerCmd> cmd = e -> {
        e.withHostName("db-host");
        e.withName("db-container-name");
    };

    Consumer<CreateContainerCmd> cmd1 = e -> {
        e.withHostName("app-host");
        e.withName("app-container-name");
    };


    @Rule
    public GenericContainer ol1 = new OpenLdapContainer()
            .withClasspathResourceMapping("db1.ldif",
                    "/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif", BindMode.READ_WRITE)
            .withCommand("--copy-service")
            .withCreateContainerCmdModifier(cmd);

    @Rule
    public GenericContainer ol2 = new OpenLdapContainer()
            .withClasspathResourceMapping("db1.ldif",
                    "/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif", BindMode.READ_WRITE)
            .withCommand("--copy-service")
            .withCreateContainerCmdModifier(cmd1);

    @Test
    public void test()
    {
        System.out.println("asis");
    }
}

Observation: I saw two containers named appropriately coming up in this case. I also saw some errors with port binding code initially so I removed that from this test code.

**Comment by rnorth** [comment]
This is quite an old issue, unfortunately. @Asisranjan did you manage to resolve this?

**Comment by Asisranjan** [comment]
Yes Richard. I followed as you suggested [here](https://github.com/testcontainers/testcontainers-java/issues/1659#issuecomment-517932080)

**Comment by Asisranjan** [comment]
Hi Richard
There are couple of queries. I am mentioning here.

1. I am trying to test REST webservices. REST webservice based application running in Container. Observing my test cases running before my server started, hence my test case is failing. How to wait for the server ready before any test execution
2. I am setting up in Oracle Virtual Box, Since I am trying to get mapped port for consuming rest service and the same port is not forwarded by default, Hence the test case is failing. Is there any way to resolve this issue.

Thanks
Asisranjan Nayak
