### ISSUE TITLE
Add Support For MongoDB 4 Transaction Support Testing

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1666]
@bsideup MongoDB 4 support Transactions. But to test those transactions we need run MongoDb in
Replica Set mode,and its a pain. Can we add a new module for MongoDb to support replica set mode
or give an example for same. So we can test MongoDb Transactions.
Here is a reference url for same:
https://www.baeldung.com/spring-data-mongodb-transactions

**Comment by bsideup** [comment]
Duplicate of #1387
