### ISSUE TITLE
Redis How to Enable KeySpace Notification In Docker Test Conatiner

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1668]
Can you please tell how I can enable Redis Key Space Notification In Redis Docker Conatiner
to test Spring Session by Test Container. Here is a reference URL for Redis Key Space 
Notification. We enable key space notification in Redis by:
redis-cli config set notify-keyspace-events KEA

**Comment by bsideup** [comment]
Hi @ankurpathak,

Testcontainers does not provide a Redis container, but you can use Redis image with `GenericContainer` class. You then can use `execInContainer` to run any command you wish inside it.
You can also override `containerIsStarted` and perform the command there, to keep it self-contained.

Also, consider using StackOverflow for questions, there is a tag you can use:
https://stackoverflow.com/questions/tagged/testcontainers
