### ISSUE TITLE
Selenium shared memory defaults

### ISSUE THREAD

**Issue by leonard84** [testcontainers/testcontainers-java#1670]
https://github.com/SeleniumHQ/docker-selenium#running-the-images states that
> When executing docker run for an image with Chrome or Firefox please either mount -v /dev/shm:/dev/shm or use the flag --shm-size=2g to use the host's shared memory.

These defaults are not applied for the `BrowserWebDriverContainer` as far as I can tell, which can cause hanging browsers on complex sites.

**Comment by rnorth** [comment]
That seems sensible, @leonard84.

Would anyone care to submit a PR for this?

**Comment by glefloch** [comment]
Hi, I would to contribute to the project, can I work on this issue? Should I add the flag or mount the volume? Maybe on Windows, the volume could cause issue no?

**Comment by heruan** [comment]
Great that this is being taken care of! Thanks! Until next release, how can I manually set a bigger `/dev/shm` when running the `BrowserWebDriverContainer`?
