### ISSUE TITLE
Spawning containers in a defined network like 'docker run --net=my_network

### ISSUE THREAD

**Issue by sourcecase** [testcontainers/testcontainers-java#168]
Hi testcontainers coders,
thanks @rnorth for the hint to add this issue in the correct space.

I'm running testcontainers to spawn Docker containers for unit testing. The Jenkins server which executes the tests is running in a Docker container as well. The Jenkins Container is spawned in a defined Docker network with the option "docker run --net".

The problem is, that code which runs in the Jenkins container, like JUnit tests, which are executed with "mvn test" can not access the MySql testcontainer, which is spawned in the default network.

Is there a way to spawn a testcontainer from java in a non default network?

Best regards and thanks
Chris

**Comment by rnorth** [comment]
Hi Chris

Thanks for raising this :)

The ability to specify a network is something I recently added to the v1.1 branch, in preparation for release of that. It's mainly there to aid docker-compose v2 support, but I think ought to work for your purposes as well. It's the new `withNetworkMode(String)` method on `GenericContainer`.

Would you mind giving the v1.1 branch a try and report back if it doesn't do what you need it to? As it's pre-release, you can obtain the binary libs through jitpack, as described [here](http://testcontainers.viewdocs.io/testcontainers-java/#user-content-jitpack-unreleased-versions)

Thanks

Richard

**Comment by rnorth** [comment]
Added some JUnit tests to illustrate this - you'll need to use the correct network name instead, obviously!

https://github.com/testcontainers/testcontainers-java/blob/1.1/core/src/test/java/org/testcontainers/junit/DockerNetworkModeTest.java

**Comment by sourcecase** [comment]
Hi Richard,

thanks for your support. I will give this a try as soon as possible.

Best regards
Chris

**Comment by sourcecase** [comment]
Hi Richard,

finally finished testing this on our integration server.

```
<dependency>
      <groupId>com.github.testcontainers</groupId>
      <artifactId>testcontainers-java</artifactId>
      <version>68f6488</version>
    </dependency>
```

It works now!

For reasons I still investigate I can only access the container via its Container IP Address
```java
String containerIpAddress = container.getContainerInfo()
                                .getNetworkSettings()
                                .getNetworks()
                                .get(DOCKER_NETWORK)
                                .getIpAddress();
```
And the exposed port 3306

This why I switched from the MySQLContainer to the GenericContainer with my own WaitStrategy.

But the testcontainers new feature "withNetworkMode" is working as expected.

Thanks for your support!

Best regards
Chris

**Comment by rnorth** [comment]
Hi Chris
Thanks for the update - glad to hear that it's working for you. Please do
let me know if you come up with ideas for implementing the getter for
container IP address in this situation! It seems it could be a difficult
thing to bring into the library itself, but perhaps there's an elegant
solution!
Thanks

Richard

On Fri, 8 Jul 2016 at 14:23, sourcecase <notifications@github.com> wrote:

> Hi Richard,
>
> finally finished testing this on our integration server.
>
> <dependency>
>       <groupId>com.github.testcontainers</groupId>
>       <artifactId>testcontainers-java</artifactId>
>       <version>68f6488</version>
>     </dependency>
>
> It works now!
>
> For reasons I still investigate I can only access the container via its
> Container IP Address
>
> String containerIpAddress = container.getContainerInfo()
>                                 .getNetworkSettings()
>                                 .getNetworks()
>                                 .get(DOCKER_NETWORK)
>                                 .getIpAddress();
>
> And the exposed port 3306
>
> This why I switched from the MySQLContainer to the GenericContainer with
> my own WaitStrategy.
>
> But the testcontainers new feature "withNetworkMode" is working as
> expected.
>
> Thanks for your support!
>
> Best regards
> Chris
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/testcontainers/testcontainers-java/issues/168#issuecomment-231357960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIET_G-xzLtkhsdtMjs99V3BdAAUY-Lks5qTk9HgaJpZM4JEHf->
> .
>
-- 
Richard
