### ISSUE TITLE
Missing MySQL driver reeks havoc with Gradle

### ISSUE THREAD

**Issue by idontusenumbers** [testcontainers/testcontainers-java#1698]
The `org.testcontainers:mysql` package doesn't include a MySQL driver, but it does require one in it's detection system. If the driver isn't included by the application/tests using the test container, the test container code will try to connect over and over, once every 10 ms, constantly erroring because of the missing driver. These exceptions are swallowed as if they were indicitave of the container not being loaded. After two minutes, testcontainers gives up and then tries 2 more times. This leads to 150k log messages (when set to trace, see below for why) and 6 minutes until testcontainers FINALLY gives up and prints the actual problem: the driver couldn't be found.

Coincidentally, using the prescribed method of a @ClassRule to attach to a JUnit test, and running in Gradle, Gradle appears to hijack STDOUT and then buffer all the log messages or something, easily reaching OutOfMemory exception before TestContainers gives up trying to spin up the container. Because of the hijack, there's no indication test containers is having trouble; it simply says:
```
> Task :setup:test
```
This leads to the escelation of the log level to trace to answer the question "what the heck is going on", causing the above mentioned out of memory exception.

Proposal:
* Include a reference to the required MySQL driver since it's very explicitly being loaded by FQCN.
* Catch the driver loading error and exit early; don't retry because it's very unlikely that class will suddenly be accessible to the class loader

**Comment by bsideup** [comment]
Hi @idontusenumbers,

Have you tried 1.12.0?
@rnorth have implemented a better handling of missing JDBC drivers in this PR: #1434
