### ISSUE TITLE
Support fort Selenium 2.53.1

### ISSUE THREAD

**Issue by pavelpp** [testcontainers/testcontainers-java#171]
When is this going to be added? Currently I'm getting `org.testcontainers.containers.ContainerFetchException: Retry limit reached while trying to pull image: selenium/standalone-chrome-debug:2.53.1`

**Comment by rnorth** [comment]
Hi
The selenium docker images are maintained by the SeleniumHQ team, not by
us. If you're using a newer version of the selenium Java libs than there is
a container image for you'd see this issue.

I'd imagine they'd appreciate a PR in case the missing 2.53.1 is just a
simple omission.

In the meantime can you fall back to a version of selenium for which the
docker image is also available?

Richard
-- 
Richard

**Comment by dmart28** [comment]
Hi, just curious - why not give an easy way to change version directly with BrowserWebDriverContainer? I faced the same issue, and haven't found quick way (probably I misread some docs after all).

**Comment by rnorth** [comment]
@dmart28 yes - probably would be a good idea to allow the selenium container image to be overridden (not just the version tag).

**Comment by magnusb** [comment]
Yes, the containers for 3.01 published by selenium seem to have a suffix so they can not be used at the moment. See the tags here: https://hub.docker.com/r/selenium/standalone-firefox/tags/

Being able to override the container template string would be very helpful.
