### ISSUE TITLE
RegistryAuthLocator does not set identitytoken when resolving from a credentials helper

### ISSUE THREAD

**Issue by rszewczyk** [testcontainers/testcontainers-java#1723]
I'm trying to use `AuthDelegatingDockerClientConfig` because of the nifty way it resolves the Docker `AuthConfig`. However, I ran into issue when a registry that uses a token is stored in a credentials helper (I'm using version `1.12.0`).

I'm doing something very similar to:

```
final DockerClientConfig config = new AuthDelegatingDockerClientConfig(fallbackConfig);
final DockerClient client = DockerClientBuilder.getInstance(config).build();
```

However, when trying to do a pull command, this results in...

```
com.github.dockerjava.api.exception.InternalServerErrorException: Get https://some-registry/some/repo/manifests/tag: unauthori
zed: authentication required
```
...if the authorization is stored in a creds helper and if the credential is a token. It works fine if the auth is stored in `config.json` or if the creds are a username and password. When debugging I noted that when the credentials helper returns `<token>` for the user, the `RegistryAuthLocator` still populates the `AuthConfig` username and password fields instead of setting the `identitytoken` field.

I've written a test case that shows the desired behavior and and implemented a fix here: https://github.com/rszewczyk/testcontainers-java/tree/fix-helpercreds-with-token

With the above fix, I'm able to successfully pull images when the creds helper is storing an identity token. I'd be happy to open PR if this looks OK to you. Thanks!

**Comment by rnorth** [comment]
Ah, thanks @rszewczyk! It's a clear gap in our current processing, so it would be great to address it. If you wouldn't mind raising a PR that would be fantastic.

I had a quick look at your fork and it looks pretty good already; one question I had was whether it would make sense to copy the `ServerURL` field from the creds helper response, as we do for the username/password mode. Is that field not set in your creds helper response, and/or are things working without it? (I can imagine this is quite possible)

Just out of curiosity, which registry are you using? I've not personally used Testcontainers with a registry that uses identitytoken based auth, so it'd be interesting to have a look and maybe set up a private repo to conduct manual tests against from time to time.

Cheers!

**Comment by rszewczyk** [comment]
@rnorth I'll get to work on opening the PR this afternoon.

I based the test case on the [API spec for authentication](https://docs.docker.com/engine/api/v1.40/#section/Authentication). It looks like only the `identitytoken` is needed. That appears to be the case for older versions of the API as well - I couldn't find an example where `identitytoken` was used where it wasn't only field sent. Still, I suppose there's no harm in copying the `ServerURL` if you prefer.

I'm using Azure Container Instances with an Azure Container Registry.

Thanks for the quick response!

**Comment by rszewczyk** [comment]
Oops - I mispoke. We are using Azure Container Instances, but that's not the use case where we encountered this issue. We're also using Docker with an Azure Container Registry.
