### ISSUE TITLE
Docker environment should have more than 2GB free disk space

### ISSUE THREAD

**Issue by andredasilvapinto** [testcontainers/testcontainers-java#1726]
I'm getting a `Docker environment should have more than 2GB free disk space` error with 1.12.0 even though I have 140GiB available on my local disk. I tried to debug this but with Lombok it is basically impossible.

**Comment by bsideup** [comment]
Your Docker VM should have 2gb of space, not your host drive. Please allocate more space to the Docker daemon.

**Comment by andredasilvapinto** [comment]
Thanks. I didn't know Docker for Mac still had a disk space limitation. For anyone reading you can change it in the UI (Docker > Preferences > Disk).

**Comment by djdenv** [comment]
> Thanks. I didn't know Docker for Mac still had a disk space limitation. For anyone reading you can change it in the UI (Docker > Preferences > Disk).

The UI has updated since this comment. New location is Preferences > Resources > Disk image dize.

**Comment by bsideup** [comment]
FTR the latest release of Testcontainers (1.17.2) no longer checks this.
