### ISSUE TITLE
DockerComposeContainer Working Directory 

### ISSUE THREAD

**Issue by qoomon** [testcontainers/testcontainers-java#173]
DockerComposeContainer should set working directory for dduportal/docker-compose to folder of  given docker-compose-file.

We need this to be able to work with relative path e.g. volumes declaration within docker compose file.

To achieve this you just need to add working directory support to GenericContainer.java, and set working directory within DockerComposeContainer.java 

Regards

**Comment by rnorth** [comment]
I think that makes sense to me - can I just check?

1. Right now Testcontainers is [mapping](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L277) the docker-file's parent directory to `/compose` while docker-compose is running. However, it is *not* setting the working directory to `/compose`.
2. You'd like to add support for setting the working directory of the container (i.e. The equivalent of the `-w` or `--workdir` option for the CLI `docker create` command)?

If so, that doesn't sound terribly difficult - I can't see any problems with implementing that in the near future.
