### ISSUE TITLE
RabbitMQ: withBinding() is broken

### ISSUE THREAD

**Issue by thoec** [testcontainers/testcontainers-java#1737]
In RabbitMQContainer::withBinding(String source, String destination, Map<String, Object>...) there is a syntax error. routing-key and destination-type should be routing_key and destination_type respectively. I.e. replace the hyphens with underscores.

**Comment by glefloch** [comment]
Yes, I tried running a small test using `withBinding(String source, String destination, Map<String, Object>...)` and it fails with the following error: 

    14:07:10.202 [Test worker] ERROR 🐳 [rabbitmq:3.7-management-alpine] - Could not execute command [rabbitmqadmin, declare, binding, source=direct-exchange, destination=queue1, routing-key=.*, destination-type=QUEUE, arguments={"x-message-ttl":1000}]: 
    ERROR: Argument "routing-key" is not recognised

    rabbitmqadmin --help for help

I'm going to open a PR to fix this with a dedicated test.
