### ISSUE TITLE
Postgres module ignores exposed ports

### ISSUE THREAD

**Issue by blekione** [testcontainers/testcontainers-java#1738]
Creating postgres container with `withExposedPorts()` has no effect as a port(s) given as argument are ignored. The same goes when trying with `addExposedPort()`.

For running tests this behaviour is OK as ports are chosen by random. But when I write the test I want to have sometimes access to created database. Without possibility to set exposed port I need to change the DB connection configuration every time test is running.

**Comment by rnorth** [comment]
Hi,
It’s unlikely that we’d ever support mapping DB containers to a fixed host port. Still, I suspect you might be able to achieve what you’re looking to do via the approach set out in this post by @bsideup: 
https://bsideup.github.io/posts/debugging_containers/

Does this help?
Richard

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blekione** [comment]
Hi Richard,

Thank you for quick response. For what I need it the proxy solution from the blog works perfectly. Great stuff.

Thank you
Marcin
