### ISSUE TITLE
Wait.forLogMessage doesn't work if container restarts (on crash)

### ISSUE THREAD

**Issue by Zanndorin** [testcontainers/testcontainers-java#1743]
`Testcontainer 1.12.0`
docker compose module

My docker-compose has 2 containers, one of them is my own SpringBoot app and the other one is `mysql 8.0.17` 
In my docker-compose the containers have `restart: unless-stopped`.

When starting my docker-compose my own container normally crashes because mysql takes too long to start, then restarts and works perfectly fine if the mysql container is up and running (yes, we have been to lazy to add a waitFor script to the compose file avoid this). 

After this first crash the `LogMessageWaitStrategy.outputFrame.getUtf8String().matches` does no longer seem to get any log messages at all so I am guessing that it loses its connection to the container on the crash (& restart).

If I instead use the HTTP strategy everything works as expected.

**Comment by Zanndorin** [comment]
Update: The bug more specifically seems to be that the LogConsumer doesn't work anymore if the container restarts / crashes.

Happens with all instances of `.withLogConsumer(LN, logInstance);`

**Comment by mcgizzle** [comment]
Any workaround for this?
