### ISSUE TITLE
Add support for running containers inside WSL 2.0

### ISSUE THREAD

**Issue by casz** [testcontainers/testcontainers-java#1766]
Would be great to support running the containers inside wsl by running `wsl docker` instead of the regular `docker`

This currently requires windows insiders and docker edge channel to run.

I would be happy to contribute a PR as a draft and have tests disable until CI can support it.

**Comment by bsideup** [comment]
Isn't WSL 2.0 runs just a "normal" Docker? If so, it is already supported (as long as the env vars are set correctly)

**Comment by casz** [comment]
you would have to prefix the cli with `wsl` to avoid hitting the regular docker daemon that could be running in Windows mode.

**Comment by bsideup** [comment]
But isn't it what the users want, to use their main "Docker for Windows" installation?
Also, I guess soon Docker for Windows will use WSL 2.0 under the hood.

**Comment by casz** [comment]
You can actually run both Linux and Windows containers at the same time with WSL 2.0 :)
Just by prefixing the docker command with `wsl`

This way in the future you don't have to be concerned about the OSType

**Comment by casz** [comment]
This will still use their main docker for windows installation.

**Comment by bsideup** [comment]
Ok, two things I see here:
1) in the strategy, we should check that the OS type is Linux, so that we avoid a positive result of the strategy if it cannot be used later - this sounds like a trivial change, also a good first issue btw ;)
2) somehow detect "WSL 2.0" docker installation - this one is tricky (and hard to develop since it requires a special insider access). Would love to see a draft of it tho 👍

**Comment by rnorth** [comment]
> Would be great to support running the containers inside wsl by running wsl docker instead of the regular docker

> you would have to prefix the cli with wsl

You're probably aware, but just to make sure it's clear for all readers: we don't invoke the `docker` CLI at all, and access Docker via its API.

I have zero knowledge about how `wsl docker` is implemented, but we'd need there to be feature parity for this in the API as a basic prerequisite.

**Comment by casz** [comment]
`wsl` is just a way to execute a command inside the WSL. With Docker edge it knows the context and runs the container inside WSL.

**Comment by casz** [comment]
I wasn't aware that you access docker via API.

**Comment by casz** [comment]
Any help in how to explore the docker API? maybe there is a way to do the same from API?

**Comment by kiview** [comment]
How can you access network ports that are running inside WSL 2.0? Are they automatically/transparently mapped to the host? If yes, a similar workaround to WSL 1.0 would work, just the other way around. Expose the Docker daemon inside WSL 2.0 over TCP.

Else you would need to expose the Unix socket from inside WSL to the Windows host, I don't think this is currently possible.

**Comment by casz** [comment]
Here are some of the benefits when using WSL 2.0 context: https://github.com/docker/for-win/issues/4374#issuecomment-517338773

**Comment by casz** [comment]
I think this could be solved in upstream by adding support for named pipes on Windows: https://github.com/docker-java/docker-java/issues/765#issuecomment-523428713

**Comment by casz** [comment]
Or be added here: https://github.com/testcontainers/testcontainers-java/blob/52d7126c19cbde76937dcabe1b589662fd15f9a5/core/src/main/java/org/testcontainers/dockerclient/NpipeSocketClientProviderStrategy.java#L17

**Comment by bsideup** [comment]
@casz we could have two strategies, one for `//./pipe/docker_engine`, and one for `//./pipe/docker_wsl`

**Comment by casz** [comment]
I'll see what I can do 😅 Hopefully have some time in the weekend to focus on this 👍

**Comment by casz** [comment]
@bsideup I haven't looked too much into the code base but perhaps a strategy that would check if `docker_wsl` pipe is available if not try and use `docker_engine` and check if OSType is linux.

**Comment by rnorth** [comment]
Two discrete strategies would do the trick, I think.

Working out which order to evaluate them in could be interesting - I'm not sure what the right answer would be, but we have to assume that one will be attempted first, and will normally win if available.

What's going to be the safest default?

FWIW, users can manually override the strategy via a setting in `~/.testcontainers.properties`, but we can't end up in a situation where a majority of users need to do this. We should be aiming to make a sensible choice automatically.

**Comment by casz** [comment]
I think once Windows 10 1909 is out the default should be `docker_wsl` IMHO. As that will run the container outside the very limited HyperV VM that the old `docker_engine` socket uses for running containers.

**Comment by casz** [comment]
As you can see here: the newer WSL 2 docker daemon has access to all 16 threads and 32 GB of memory. Whereas the old docker daemon only has 2 threads and 2 GB of memory.
![image](https://user-images.githubusercontent.com/1661688/63465177-f6ead380-c460-11e9-8445-8290ef732c65.png)

So this would help improve the developer experience when running testcontainers 😆

**Comment by kiview** [comment]
I also don't see an disadvantage of using `docker_wsl` if available.

**Comment by casz** [comment]
Well it could stay in draft PR till ready :)

**Comment by casz** [comment]
Here is an announcement that says they will switch people over to WSL 2 when generally available: https://engineering.docker.com/2019/10/new-docker-desktop-wsl2-backend/

**Comment by casz** [comment]
This will most like end up being a won't do due to the blog post above from docker engineering.

>The future of Docker Desktop
Once Microsoft makes WSL 2 generally available, we plan to enable the WSL 2 engine on all supported Windows versions by default. We will still support the Hyper-V backend until Microsoft stops supporting Windows versions without WSL 2 though, but only as a fallback mechanism.
>
>By moving to this “WSL 2 first” approach, we also want to take advantage of its unique characteristics to unlock new features in the future. As an example, WSL 2 is supported on Windows 10 Home. We want to take advantage of that to reach new users in the future (nothing to announce yet, but it is definitely in our backlog).
>
>This new backend paves the way for exciting new features to come, and we are eager to hear your feedback.
>
>We will be releasing the new WSL 2 architecture as part of the next Docker Desktop Edge release. For Windows users already with WSL 2 Download Edge today to get access to the latest Docker architecture in the next couple of weeks.


The new WSL 2 Docker engine named pipe is back to being named `docker_engine`

```
> get-childitem \\.\pipe\

    Directory:  \\.\pipe

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
------       01-01-1601     01:00        2   docker_engine
------       01-01-1601     01:00       18   docker_engine_linux
------       01-01-1601     01:00        1   dockerBackend
------       01-01-1601     01:00        2   dockerBackendApiServer
------       01-01-1601     01:00        3   dockerBackendApiServerForGuest
------       01-01-1601     01:00        2   dockerDiagnosticd
------       01-01-1601     01:00        2   dockerExport
------       01-01-1601     01:00        2   dockerGuiToDriver
------       01-01-1601     01:00        4   dockerLifecycleServer
------       01-01-1601     01:00        1   dockerLogs
------       01-01-1601     01:00        3   dockerMemlogdq
------       01-01-1601     01:00        2   dockerVolume
------       01-01-1601     01:00        5   dockerVpnkit
------       01-01-1601     01:00        2   dockerVpnKitControl
------       01-01-1601     01:00        2   dockerVpnkitData
------       01-01-1601     01:00        4   dockerVpnKitDiagnostics
------       01-01-1601     01:00        6   dockerWebApiServer
------       01-01-1601     01:00        2   dockerWsl2BootstrapExposePorts
```
