### ISSUE TITLE
Ryuk not always able to cleanup docker-compose networks

### ISSUE THREAD

**Issue by slnowak** [testcontainers/testcontainers-java#1767]
We've recently discovered a bug with ryuk not being able to cleanup some networks. 
It seems like the bug only happens with some specific environment setup and assumptions:
- create a docker-compose file that references external network. This network will be then created at runtime by testcontainers. 
- within a docker-compose file, specify a container that does some networking. For example, I'm able to reproduce the bug with zookeeper, but it's not happening with busybox

It looks like Ryuk container is not always able to cleanup networks. However, if you disconnect all containers from network before the JVM exits, it seems to delete it just fine.
I thin there's also some race condition involved, because I'm not able to always reproduce the issue.

Here's the example project that tries to reproduce that issue https://github.com/slnowak/testcontainers-network-cleanup-bug
It contains 2 docker-compose files and a few test cases that create docker-compose containers based on these files. After you run these tests (`./mvnw test`), there should be no orphaned networks left, but that's not the case:
```
➜  testcontainesrnetworkcleanupbug git:(master) ✗ docker ps           
CONTAINER ID        IMAGE                               COMMAND             CREATED             STATUS                  PORTS                     NAMES
9f61f12929c2        quay.io/testcontainers/ryuk:0.2.3   "/app"              1 second ago        Up Less than a second   0.0.0.0:38075->8080/tcp   testcontainers-ryuk-ed9721b7-21ee-4ed3-aac9-e11dc694af4e
➜  testcontainesrnetworkcleanupbug git:(master) ✗ docker logs -f 9f61f12929c2           
2019/08/21 15:41:10 Starting on port 8080...
2019/08/21 15:41:11 Connected
2019/08/21 15:41:11 Adding {"label":{"org.testcontainers.sessionId=ed9721b7-21ee-4ed3-aac9-e11dc694af4e":true,"org.testcontainers=true":true}}
2019/08/21 15:41:12 Adding {"label":{"com.docker.compose.project=lr5sdwrrruq8":true}}
2019/08/21 15:41:17 Adding {"label":{"com.docker.compose.project=mvg8xbtdstfh":true}}
2019/08/21 15:41:24 Adding {"label":{"com.docker.compose.project=nvttrjgujrsp":true}}
2019/08/21 15:41:33 Adding {"label":{"com.docker.compose.project=heymnubatgwm":true}}
2019/08/21 15:41:39 EOF
2019/08/21 15:41:39 Disconnected
2019/08/21 15:41:49 Timed out waiting for connection
2019/08/21 15:41:49 Deleting {"label":{"org.testcontainers.sessionId=ed9721b7-21ee-4ed3-aac9-e11dc694af4e":true,"org.testcontainers=true":true}}
2019/08/21 15:41:50 Deleting {"label":{"com.docker.compose.project=lr5sdwrrruq8":true}}
2019/08/21 15:41:50 Deleting {"label":{"com.docker.compose.project=mvg8xbtdstfh":true}}
2019/08/21 15:41:50 Deleting {"label":{"com.docker.compose.project=nvttrjgujrsp":true}}
2019/08/21 15:41:51 Deleting {"label":{"com.docker.compose.project=heymnubatgwm":true}}
2019/08/21 15:41:51 Removed 8 container(s), 3 network(s), 0 volume(s)
➜  testcontainesrnetworkcleanupbug git:(master) ✗ docker network ls          
NETWORK ID          NAME                                                                                               DRIVER              SCOPE
f7ed3d947bcb        bridge                                                                                             bridge              local
c3bd9abac8b6        host                                                                                               host                local
27c3a714a6d6        none                                                                                               null                local
e2890689fb4e        not-cleaned-up-with-zookeeper-and-external-container-76176a39-554d-45e9-bfb0-6f25b5003724          bridge              local
b3358bdb615e        not-cleaned-up-with-zookeper-and-without-external-container-e577486c-5f65-4146-9d7d-e31feb9303f9   bridge              local
➜  testcontainesrnetworkcleanupbug git:(master) ✗ 
```

**Comment by rnorth** [comment]
Thanks @slnowak - I think I noticed something similar at work recently, so I’ll try and look into this as well. Thank you for your investigation so far. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slnowak** [comment]
I think this might be due to the fact that ryuk container iterates over labels and then for each label it tries to delete containers, then networks, then volumes. Because of that, docker might not be able to prune networks, because it can be still used by some container.

I think i got it working by changing the ryuk code so that it first tries to delete all containers, then all volumes and then all networks, like this: https://gist.github.com/slnowak/ce0780432c08d50e412a18dcb7edcf6b

**Comment by slnowak** [comment]
Any updates on this?

**Comment by rnorth** [comment]
I have a fix, I think, via https://github.com/docker/compose/issues/6636

In short, by upgrading docker-compose and using v2.1+ syntax compose files, Ryuk is able to clean up in all the cases I've tested so far.

I'll push a WIP PR in a minute.

**Comment by slnowak** [comment]
@rnorth 
But I was able to reproduce it using local compose + docker-compose 3.7 format. Have you checked the examples in my repo?
