### ISSUE TITLE
UnixSocketClientProviderStrategy does not obtain DOCKER_HOST env variable

### ISSUE THREAD

**Issue by usmanovbf** [testcontainers/testcontainers-java#1770]
Based on this comment https://github.com/testcontainers/testcontainers-java/issues/854#issuecomment-523671909 there is a problem when first valid strategy "UnixSocketClientProviderStrategy" could not obtain environment variable "DOCKER_HOST" even if it was set. Because value "SOCKET_LOCATION" is hardcoded. I will prepare pull request for that

**Comment by rnorth** [comment]
This was tackled in #2985, so can be closed
