### ISSUE TITLE
RabbitMQContainer builder style vs overloaded methods

### ISSUE THREAD

**Issue by philsttr** [testcontainers/testcontainers-java#1775]
I have a suggestion for the `RabbitMQContainer` api.

Currently, `RabbitMQContainer` has a bunch of overloaded methods, for example:

```java
RabbitMQContainer withVhost(String name)
RabbitMQContainer withVhost(String name, boolean tracing)
RabbitMQContainer withQueue(String name)
RabbitMQContainer withQueue(String name, boolean autoDelete, boolean durable, Map<String, Object> arguments)
RabbitMQContainer withExchange(String name, String type)
RabbitMQContainer withExchange(String name, String type, boolean autoDelete, boolean internal, boolean durable, Map<String, Object> arguments)
```

Here's an example usage:

```
new RabbitMQContainer()
    .withVhost("myvhost", false)
    // note: can't declare exchange in the above vhost
    .withExchange("foo", "direct", true, false, true, Collections.emptyMap()) 
```

I had a need to declare an exchange in a vhost, which is not currently possible using the current `withExchange` methods.  So, a new overload would be needed.
However, it seems like the current approach of having a bunch of overloaded methods is going to become cumbersome very quickly.
Additionally, for declaring things like a queue, anything more than the simple `withQueue(String name)` requires specifying _all_ of the other attributes with `withQueue(String name, boolean autoDelete, boolean durable, Map<String, Object> arguments)`, even if I just want to change one of the attributes.

So, I'd like to propose an api change for the `RabbitMQContainer` api.

I'm thinking something like this:

```java
new RabbitMQContainer()
	.declare(vhost("myvhost")
		.tracing(false))    // only if needed
	.declare(exchange("foo")
		.type("direct")     // only if needed
		.vhost("myvhost")   // only if needed
		.autoDelete(true)   // only if needed
		.internal(false)    // only if needed
		.durable(true)      // only if needed
		.arguments(Collections.emptyMap()));    // only if needed
```

Could potentially declare vhost-specific things under the vhost as well...

```java
new RabbitMQContainer()
	.declare(vhost("myvhost")
		.tracing(false)    // only if needed
		.declare(exchange("foo")
			.type("direct")     // only if needed
			.autoDelete(true)   // only if needed
			.internal(false)    // only if needed
			.durable(true)      // only if needed
			.arguments(Collections.emptyMap())));    // only if needed
```

Behind the scenes, there would be
* a `Declarable` interface, 
* a `Declarables` class with a bunch of static methods on it (e.g. `vhost(String name)`, `exchange(String name)`).
  * Those static methods would return concrete `Declarable` classes with fluent modifier methods.
  * users could use static imports to simplify declarations
* a `declare(Declarable)` method on `RabbitMQContainer` and the vhost declarable

This style of api would prevent the growth of overloaded methods on `RabbitMQContainer`, and allow selectively overriding specific attributes of a declarable, without having to specify _all_ attributes (like the current api).

We could leave the existing methods for backwards compatibility, but deprecate them.

Thoughts?  Naming suggestions?  Other suggestions?

I could probably put some time into this and submit a PR, but I didn't want to do that without a quick discussion.

**Comment by philsttr** [comment]
revive 🧟

**Comment by eddumelendez** [comment]
Closing it. In order to know more, please read the comment left [here](https://github.com/testcontainers/testcontainers-java/pull/1833#issuecomment-1190543550)
