### ISSUE TITLE
Class org.testcontainers.containers.MySQLContainer generic with no purpose?

### ISSUE THREAD

**Issue by raffig** [testcontainers/testcontainers-java#1776]
Either I do not see something or there is no purpose for class 

org.testcontainers.containers.MySQLContainer<SELF>

to be generic, and the fact that is generic generates lots of warnings (I don't know what could be provided as SELF parameter).

**Comment by bsideup** [comment]
You can use `new MySQLContainer<>()` to avoid the warnings.

Testcontainers 2.0 will not use the self-typing anymore. It is being tracked in https://github.com/testcontainers/testcontainers-java/issues/107 and you can find a bit of info here:
https://speakerdeck.com/bsideup/geecon-2019-testcontainers-a-year-in-review?slide=74

**Comment by raffig** [comment]
Diamond operator cannot be used in declaration, so warning remains. It's good to know that it will be changed :-).

**Comment by sanderploegsma** [comment]
I don't see why the containers like MySQLContainer have a type argument though, what is wrong with the following?

``` java
public class MySQLContainer extends JdbcDatabaseContainer<MySQLContainer> {
    public MySQLContainer withX() {
        // configure X
        return self();
    }
}
```

**Comment by matul3jan** [comment]
This works for me 

`MySQLContainer<?> mySQLContainer = new MySQLContainer<>("");`

**Comment by kiview** [comment]
@sanderploegsma You are right with regards to `MySQLContainer`, it is there for legacy reasons.
