### ISSUE TITLE
exec a container which is not running

### ISSUE THREAD

**Issue by chomhanks** [testcontainers/testcontainers-java#1783]
I am trying to use `copyFileFromContainer` on a container which is not running and it is failing. Is there a way I can copy files from a container which is not running?

**Comment by bsideup** [comment]
By "not running" do you mean that the container is created but not started, or an instance of container that was never `.start()`-ed?

**Comment by chomhanks** [comment]
The container is started but exited by the time files are copied from the container. Here is the code:

```
 gc = new GenericContainer("registry.xxx.com/xxx:" + BRANCH_NAME);
            gc.start();

            Path tempFilePath = Files.createTempFile("temp", ".jar");
            gc.copyFileFromContainer("/data/xxx/lib/com.xxx.xxx-printing-out-params.jar",
                                            tempFilePath.toAbsolutePath().toString());

            JarFile jar = new JarFile(tempFilePath.toFile());
```
