### ISSUE TITLE
Is it possible to pass parameters to TC_INITFUNCTION?

### ISSUE THREAD

**Issue by chomhanks** [testcontainers/testcontainers-java#1790]
I am using TC_INITFUNCTION to pass connection to my init function. Is there a way to pass parameters to my init function as well? I tried using TC_TMPFS but not able to figure out. Can someone please help?

`jdbc:tc:postgresql:11.4://localhost:5432/xxx?TC_INITFUNCTION=com.xxx.xxx.config.DatabaseSetup::migrate`

**Comment by rnorth** [comment]
Hi @chomhanks,
Sorry but it's not possible to pass parameters to the init function - only a `java.sql.Connection`, as per [the docs](https://www.testcontainers.org/modules/databases/#using-an-init-function).

What parameter are you wanting to pass?

**Comment by rnorth** [comment]
Right, OK. Sorry, but there's no way to pass an arbitrary parameter in this way. I'd suggest trying to find another route to pass the value you need.
