### ISSUE TITLE
Why it does not find the initscript file in the resources folder?

### ISSUE THREAD

**Issue by ghost** [testcontainers/testcontainers-java#1801]
Hi all 

I am using [cassandra module][1] from testcontainer to build a testing environment. 
The class cassandra provides a method to execute an [initial script][2]:

    /**
     * Initialize Cassandra with init CQL script
     * <p>
     * CQL script will be applied after container is started (see using WaitStrategy)
     *
     * @param initScriptPath relative classpath resource
     */
    public SELF withInitScript(String initScriptPath) {
        this.initScriptPath = initScriptPath;
        return self();
    }

I've created a file, namely the `akka.cql` in the resources folder under the test folder as you can see on the image blow with red border:
[![enter image description here][3]][3]

I am using the cassandra module as follows: 

     private val cassandra = Container.cassandra()
      cassandra.withInitScript("/akka.cql")
      cassandra.start()
          .wait()

then I've got the exception, that the `akka.cql` can not be found. 

In the debug modus, I've figured out, where the exception was throwed https://github.com/testcontainers/testcontainers-java/blob/master/modules/cassandra/src/main/java/org/testcontainers/containers/CassandraContainer.java#L61 and the responsible statement is: 

    URL resource = Thread.currentThread().getContextClassLoader().getResource(initScriptPath);

the resource variable is `null`. 

What am I doing wrong?

  [1]: https://www.testcontainers.org/modules/databases/cassandra/
  [2]: https://github.com/testcontainers/testcontainers-java/blob/master/modules/cassandra/src/main/java/org/testcontainers/containers/CassandraContainer.java#L110
  [3]: https://i.stack.imgur.com/z8Q17.png

Thanks

**Comment by eddumelendez** [comment]
An example about how to use it can be found [here](https://github.com/testcontainers/testcontainers-java/blob/main/modules/cassandra/src/test/java/org/testcontainers/containers/CassandraContainerTest.java#L76-L85)

**Comment by eddumelendez** [comment]
We are closing it due to the example provided already shows it works. @ghost feel free to reopen if needed.
