### ISSUE TITLE
New JdbcDatabaseContainer#withUrlParam(String, String) method

### ISSUE THREAD

**Issue by knutwannheden** [testcontainers/testcontainers-java#1802]
As discussed in #1764 it would be useful to have a new `JdbcDatabaseContainer#withUrlParam(String, String)` method, which would allow specifying arbitrary parameters to be included in the query part of the JDBC URL, whenever there is no dedicated Java method to control the corresponding query parameter.

For MySQL there are for instance many parameters (see https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html). One parameter I would like to be able to set for instance is `allowMultiQueries`.

**Comment by knutwannheden** [comment]
AFAICT this issue can now be closed.

**Comment by kiview** [comment]
Closed by #1874.
