### ISSUE TITLE
Global Container Lifecycle

### ISSUE THREAD

**Issue by Gaibhne** [testcontainers/testcontainers-java#1806]
We are looking at refactoring a ton of legacy integration tests to use Docker containers as the database to test against. Currently, many of these old tests expect the database they run against to be permanent between tests,  and unfortunately, not all tests are in the same class (or we would be able to simply use a class rule).

While long term we aim to decouple these tests, short term we are looking for a way to say "Fire this Docker container up once per total run of jUnit/mvn test (and clean up once)". Is this at all possible with Testcontainers, and if not, is it a functionality that may be implemented in the future ?

**Comment by bsideup** [comment]
@Gaibhne if the database is SQL, you may want to use the JDBC URL support with the daemon flag set:
https://www.testcontainers.org/modules/databases/#running-container-in-daemon-mode

For other types of containers, we recommend the singleton container approach:
https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers

**Comment by Gaibhne** [comment]
Thanks, I did not come across that during my Google research. It seems a combination of the two would solve our problems and allow us to slowly untangle our tests one by one.
