### ISSUE TITLE
Use the library in an Android project

### ISSUE THREAD

**Issue by jabrena** [testcontainers/testcontainers-java#1821]
Hi,

I would like to know if it is possible to use `testcontainers-java` in an Android project.

Is it possible?

Juan Antonio

**Comment by kiview** [comment]
Hey @jabrena,
depends very much on where in the project you want to use it.

In general it is possible, but remember that the executing host needs some way to communicate with a Docker daemon.

Why don't you give it a try and re-open if you stumble upon any problem?

**Comment by jabrena** [comment]
Hi @kiview, I will try it.
This answer is a good starting point.

Many thanks.
