### ISSUE TITLE
/docker-entrypoint.sh": permission denied

### ISSUE THREAD

**Issue by sviridov13** [testcontainers/testcontainers-java#1828]
``` 
public static GenericContainer postgreSQLContainer = new PostgreSQLContainer("postgres:9.6")
            .withDatabaseName("test")
            .withUsername("test")
            .withPassword("test")
            .withCopyFileToContainer(MountableFile.forHostPath("fix.sh", 755), "docker-entrypoint-initdb.d/fix.sh");
```

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/fix.sh
09:55:02.487 [main] DEBUG org.testcontainers.containers.output.WaitingConsumer - STDOUT: 
09:55:02.488 [main] DEBUG org.testcontainers.containers.output.WaitingConsumer - STDERR: bash: /docker-entrypoint-initdb.d/fix.sh: Permission denied
```

**Comment by bsideup** [comment]
Hi @sviridov13,

`withCopyFileToContainer` (since it is "copy", not mounting) does not set the file permissions, so you may need to set them manually in the command / entrypoint

**Comment by sviridov13** [comment]
@bsideup How can i do this?

**Comment by bsideup** [comment]
@sviridov13 see https://www.testcontainers.org/features/commands/#container-startup-command

**Comment by sviridov13** [comment]
if I use method "withCommand"
``` 
.withDatabaseName("test")
            .withUsername("test")
            .withPassword("test")
            .withCopyFileToContainer(MountableFile.forClasspathResource("fix.sh", 777), "/docker-entrypoint-initdb.d/fix.sh")
            .withCommand("chmod +x /docker-entrypoint-initdb.d/fix.sh")
```
Then I see container status 
```
postgres:9.6                        "docker-entrypoint.s…"   10 seconds ago      Exited (0) 9 seconds ago
```

**Comment by bsideup** [comment]
@sviridov13 you're literally saying that you container is `chmod +x /docker-entrypoint-initdb.d/fix.sh` now, so it runs the command and.... exits :)

It is like doing `docker run postgres chmod +x /docker-entrypoint-initdb.d/fix.sh`.

To fix that, you need to call the original command as well start starts the Postgres process

**Comment by sviridov13** [comment]
@bsideup  How can i do this?

**Comment by bsideup** [comment]
@sviridov13 see my previous comment ( https://github.com/testcontainers/testcontainers-java/issues/1828#issuecomment-528234491 )

**Comment by kiview** [comment]
@sviridov13 Please consider asking usage questions in our Slack channel or on SO if you are still struggling with this:
https://www.testcontainers.org/getting_help/
