### ISSUE TITLE
Move release process from Travis to GitHub Actions

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1835]
Follow-up of #1720

To keep everything in one place, it makes sense to use GitHub Actions for doing the release.

This does not move the CI to GHA (GitHub Actions) yet since Azure Pipelines provide more features like self-hosted agents and test result aggregation, there is a separate issue for that:
https://github.com/testcontainers/testcontainers-java/issues/1836

**Comment by rnorth** [comment]
Merged #1991
