### ISSUE TITLE
Make Testcontainers annotation inheritable

### ISSUE THREAD

**Issue by heruan** [testcontainers/testcontainers-java#1844]
I'm using the `junit-jupiter` integration to create a common superclass for my tests, but `@Testcontainers` isn't `@Inherited` so my test classes don't inherit it. Also, `TestcontainerExtension` is private so I cannot create my own annotation as a workaround.

Would it be possible to have `@Testcontainers` inheritable?

**Comment by bsideup** [comment]
Thanks for the report!

It seems to be a duplicate of #1843

**Comment by heruan** [comment]
Darn, 5 hours late! 😅
