### ISSUE TITLE
How to get the DatabaseContainer instances launched via JDBC URL scheme

### ISSUE THREAD

**Issue by agentraymond232** [testcontainers/testcontainers-java#1898]
I was able to create a MySqlDatabaseContainer using the JDBC URL scheme as mentioned here. Please find the application-integration-test.properties below.

`spring.datasource.url=jdbc:tc:mysql:5.7.8://localhost:3306/myTable`
`spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver`
`spring.main.allow-bean-definition-overriding=true`
`spring.flyway.enabled=false`
`spring.datasource.username = root`
`spring.datasource.password =`

My integration test class is as shown below

  `@RunWith(SpringRunner.class)`
  `@SpringBootTest(`
    `classes = com.mycompany.myorg.myproduct.mainApp.class,`
    `webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT`
    `)`
  `@ActiveProfiles("test")`
  `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`
  `@TestPropertySource( locations = "classpath:application-integration-test.properties")`

  `public  class BaseFunctionalTest {`
    `  @Test`
    `  public void test { `
     `   //  ...`
      `}`
  `}`
With this, I am able to launch a mysql server in a docker, and connected to it. However, I am unable to get an instance of the thus created MySQLContainer. I need that to run queries on that as I may need. If I use MySQLContainer container = new MySQLContainer(), it launches another MySql container , in addition to the one that was already created and had the flyway tables migrated to it automatically.

So, can anyone help me with getting the reference to the MySQlContainer instantiated through the JDBC URl scheme? I would be grateful.

**Comment by agentraymond232** [comment]
Any responses on this?

**Comment by sergiomichels** [comment]
Haven't used test containers for database so far and maybe I'm sending you to wrong direction, but looking from your code, it configured the data source connection for Spring, so you could use same approach as if you were using a local database, don't you have repositories already for this application?

**Comment by AndyMacDroo** [comment]
As @sergiomichels has suggested, from what you've described, it seems like you're having no trouble launching a container, you have successfully verified it's running and would just like to query your newly created datasource in its container in your spring integration test?

If that's the case - this isn't really a `testcontainers-java` specific issue and is more how you implement a database test container using spring boot. 

In your `application.properties`, you've created a `DataSource` bean, so you should be able to autowire a `JdbcTemplate` (or use an already created repository / DAO in your test) - e.g.

```java
@RunWith(SpringRunner.class)
@SpringBootTest(
classes = com.mycompany.myorg.myproduct.mainApp.class,
webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
)
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource( locations = "classpath:application-integration-test.properties")
public class BaseFunctionalTest {

  @Autowired
  private JdbcTemplate jdbcTemplate;

  @Test
  public void test {
    Integer result = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM MY_SCHEMA.MY_TABLE", Integer.class);
  }
}
```

**Comment by rnorth** [comment]
Thanks @sergiomichels and @AndyMacDroo for the above. @agentraymond232 do these answers help?

**Comment by eddumelendez** [comment]
Closing because of there is no reply. @agentraymond232 feel free to reopen this.
