### ISSUE TITLE
Localstack Module: Step Functions Service Name is Incorrect

### ISSUE THREAD

**Issue by stejohnson** [testcontainers/testcontainers-java#1902]
Hi,

The [step functions service](https://docs.aws.amazon.com/step-functions) in the Localstack container fails to start as the name is incorrect. It should be `stepfunctions` but is typed `stepsfunctions`.

https://github.com/testcontainers/testcontainers-java/blob/8e871d03c0082474b3a7e304362e97aca4de0740/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L136

Thanks

**Comment by rnorth** [comment]
Ah good catch - would anybody like to raise a quick PR to fix?
