### ISSUE TITLE
DockerCompose does not log OutputFrame.OutputType.STDOUT

### ISSUE THREAD

**Issue by sourcecase** [testcontainers/testcontainers-java#191]
Hey testcontainer contributors,

in case new images have to be downloaded it is not visible, that this is actually happening. The dduportal/docker-compose is logging on std out, if something has to be downloaded.

An idea would be to log in org.testcontainers.containers.DockerCompose OutputFrame.OutputType.STDERR to log level ERROR and OutputFrame.OutputType.STDOUT to log level INFO or DEBUG

Thank and best regards
Chris

**Comment by qoomon** [comment]
should be done by #192
