### ISSUE TITLE
Configure GenericContainer for all tests in Spring Boot

### ISSUE THREAD

**Issue by pas2al** [testcontainers/testcontainers-java#1915]
Is there any way to configure a `GenericContainer` for all tests in a Spring Boot based application? 

Let's take mongo for example. The corresponding properties for host and port in Spring Boot are:

- `spring.data.mongodb.host`
- `spring.data.mongodb.port`

Currently, I know two ways to configure a `GenericContainer`. Either by providing an initializer class in a `@ContextConfiguration(initializers =...)` or by setting the properties for Spring Boot directly with `System.setProperty(...)`.

Both happens directly in my test class and uses the generic container itself to get the host and port like this:

`mongoContainer.getContainerIpAddress();`
`mongoContainer.getFirstMappedPort();`

I would love to set the configuration in a more general way so that it applies to all my tests. One way would be to create an abstract class that defines this configuration but then every test has to inherit this class.

Are there any other ways?

**Comment by rnorth** [comment]
@pas2al have you had a look at the [singleton containers](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers) pattern in our docs?

Would this work?

**Comment by pas2al** [comment]
@rnorth But then every test class has to inherit from the `AbstractContainerBaseTest`. For the relational databases with jdbc you can configure a jdbc url in the `application.properties`. Mentioned in the guide https://www.testcontainers.org/modules/databases/#jdbc-url-examples

Is there any way to do something similar for a generic container. I would like to configure the container in a general way so that the configuration applies to all my tests.

**Comment by bsideup** [comment]
@pas2al Testcontainers is a library, not framework.

You can use your test framework's features to achieve "global" resources.

Singleton pattern is basically a feature of Java.
You can also define your containers in a separate singleton class and then refer to it from other tests without having to extend it.

You could also create a singleton context initializer and use it with each `@SpringBootTest`:
https://github.com/testcontainers/testcontainers-java/blob/232e9b03f199299f8e01cc60e8fa3e5ca0c549ed/examples/spring-boot-kotlin-redis/src/test/kotlin/com/example/redis/AbstractIntegrationTest.kt#L27

**Comment by pas2al** [comment]
@bsideup I did that and that's a good way to start. I am just curious about how to improve the configuration even more ;-). Don't get me wrong. This is an awesome library and super useful! Incredible work!

For the jdbc containers, we can configure the jdbc url. Which is specified with a defined port. Like in the examples in the documentation https://www.testcontainers.org/modules/databases/#database-containers-launched-via-jdbc-url-scheme

In the case of mongo db with Spring Boot I have the properties:

`spring.data.mongodb.host`
`spring.data.mongodb.port`

Can I configure a generic mongo db container the same way by just saying on which port it will run and the host?
