### ISSUE TITLE
No option to retrieve container logs when docker-compose configuration used.

### ISSUE THREAD

**Issue by leCandas** [testcontainers/testcontainers-java#1916]
I want to retrieve a container log on the fly due to a failed test case when using docker-compose configuration. But this is not possible.

Only option to get logs of a container when compose used is to register log consumer before compose started.

**Comment by rnorth** [comment]
Thanks for reporting. We'd be happy to accept a PR to allow logs to be retrieved from Compose; I think it would be fairly simple to implement.

**Comment by bsideup** [comment]
Superseded by #2302
