### ISSUE TITLE
ResourceReaper using user defined networks

### ISSUE THREAD

**Issue by dom54** [testcontainers/testcontainers-java#1922]
- We have an environment which uses user defined networks to talk to all containers
- The "hostIP" is resolved incorrectly for docker in docker on our setup
- We would like the ability to override the hostname, port and user defined network for the resource reaper, allowing connection to it directly on 8080.

**Comment by dom54** [comment]
https://github.com/testcontainers/testcontainers-java/pull/1923/files

**Comment by rnorth** [comment]
Please see comments on #1923 as to why we felt supporting this use case would not be feasible.
