### ISSUE TITLE
withCopyFileToContainer fails silently

### ISSUE THREAD

**Issue by steghio** [testcontainers/testcontainers-java#1938]
Hello,

I create and start a container as:

````
new FixedHostPortGenericContainer<>(
        "myimage")
        .withCreateContainerCmdModifier(cmd -> cmd.withName(hostname))
        .withFixedExposedPort(port, port)
        .withEnv("JAVA_OPTS", "-Xms512m -Xmx512m")
        .withEnv("SCHEMA_ZK_CONNECT", "blabla")
        .withEnv("HOSTNAME", "localhost")
        .withCopyFileToContainer(
            MountableFile.forHostPath(myFile.getAbsolutePath(), 777),
            "/var/confluent/etc/confluent.properties")
        .withCommand("something")
        .waitingFor(Wait.forHttp("/"));
````

I am forced to use the image I have so I am also forced to go with `FixedHostPortGenericContainer` and all other strange things you might see. 

Also I cannot use `copyFileToContainer` in this particular instance as this file must be present there before the startup command is executed, and calling `start()` myself will fail as the image restricts startup commands to only a few possibilities.

Long story short, issue is in this line:

````
.withCopyFileToContainer(
            MountableFile.forHostPath(myFile.getAbsolutePath(), 777),
            "/var/confluent/etc/confluent.properties")
````

I develop on Windows 7 + Docker Toolbox but the build server is a RHEL7 with native Docker.

On the build environment that command does NOT copy the file in the container, but also does NOT report any exception, if I login to the container and look in that folder it is simply empty.

If I do the same operation on my DEV machine, the file is there.

The file permissions on DEV machine are:

`-rw-r--r--` 

and on build machine are:

`-rw-r-----`

Passing the mode parameter as `0777` or leaving it empty doesn't change a thing.

Leaving all the suggestions and debugging aside, my request is: could you please make it so that `withCopyFileToContainer` includes debug statements AND raises an exception if something goes wrong while trying to copy the file to the container?

Thank you

**Comment by jelovac** [comment]
Hi,

I am having similar issue.

When I run my tests on my Kotlin Spring Boot project test-containers fail to copy temporary file during the container creation.

```
    val mongoInitFile = createMongoInitDbScript()
    val mongoInitFilePath = mongoInitFile.canonicalPath
    val mongoInitMountableFile = MountableFile.forHostPath(mongoInitFilePath)

    var mongoContainer = GenericContainer("mongo:4.0-xenial")
            .withEnv("MONGO_INITDB_DATABASE", getMongoDatabase())
            .withCopyFileToContainer(mongoInitMountableFile, "/docker-entrypoint-initdb.d/init.js")
            .withExposedPorts(27017)
            .waitingFor(Wait.forListeningPort())

    mongoContainer.start()
```

I checked mongoInitFilePath and it points to %USER%\AppData\Local\Temp\mongo-initdb3028214640156320517

Also checked the permissions of that file and all seems good.

Some details:

OS: Windows 10
JAVA: JDK 11
Kotlin: 1.3.50
Docker: Docker for Windows 2.1.0.4

**Comment by jelovac** [comment]
Update, I solved my issue.

I created my own GenericContainer class which extended org.testcontainers.containers.GenericContainer in Kotlin.

What I unfortunately did not do was pass the constructor parameter to the parent class constructor.

Therefore it was running default Alpine image and failing instead of running Mongo.
