### ISSUE TITLE
Create a "pattern" for NAT-unfriendly systems (Kafka, Couchbase, etc)

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1940]
There are some containers that are hard to deal with due to their protocol.

 A good example would be Kafka, and some users can't use our built-in Kafka module (#1939).

It would be nice to provide an easy-to-use pattern as part of the core library to simplify dealing with such systems that require the port to be known before their **process** is started.

**Comment by bsideup** [comment]
How we do it in Kafka:
https://github.com/testcontainers/testcontainers-java/blob/ca8a35dc5ccf31142919c5fb5635c664d4f89302/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L83-L105

... in Couchbase:
https://github.com/testcontainers/testcontainers-java/blob/ca8a35dc5ccf31142919c5fb5635c664d4f89302/modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java#L133-L141

**Comment by solarmosaic-kflorence** [comment]
Yes please. I want to use a different Kafka docker image, and so I would need to duplicate a lot of logic just to get it to work (all because of the advertised listeners port being random). It's a pain.

**Comment by bsideup** [comment]
@solarmosaic-kflorence it is possible to override the image used in `KafkaContainer`

**Comment by solarmosaic-kflorence** [comment]
Perhaps a hook on the container to allow defining environment variables to export into the docker command?

**Comment by solarmosaic-kflorence** [comment]
@bsideup I can override the image, but I would also have to change the ENV configuration. In my case, I was using https://hub.docker.com/r/bitnami/kafka/

**Comment by bsideup** [comment]
@solarmosaic-kflorence 

> Perhaps a hook on the container to allow defining environment variables to export into the docker command?

There is a bit of the chicken/egg problem. To obtain the port, we need to start the container. To start the container (or, actually, the process) with the environment variables, we need to know the ports :D 

This is why in Kafka we start the actual Kafka process after starting the container (see the implementation)

**Comment by solarmosaic-kflorence** [comment]
Can the port be reserved prior to the container starting? If that's not possible, maybe a "ghost" container can be started which reserves the port, and then shuts down when the real container comes up?

**Comment by bsideup** [comment]
> Can the port be reserved prior to the container starting?
unfortunately no.

> maybe a "ghost" container can be started which reserves the port
that was our previous approach (with Socat) :D see #1458

**Comment by solarmosaic-kflorence** [comment]
It's possible to override the default command in the image, if we could get the bound port from inside the container perhaps we could construct a command in docker-compose that could define proper environment variables prior to running the service?
