### ISSUE TITLE
Stop publishing sources after applying Delombok

### ISSUE THREAD

**Issue by remal** [testcontainers/testcontainers-java#1966]
As I understand, Testcontainers project uses Lombok library:
* The sources are compiled using Lombok annotation-processor
* Source files are passed through Delombok tool before publishing.

It breaks debugging, as the IDE can't match lines in bytecode with line in the source files.

I see two solutions:
1. First delombok the sources and only then run compilations
1. Publish true sources without applying Delombok tool
IMHO the second solution is more preferable, as Delombok tool sometimes produces sources that can't be compiles.

**Comment by rnorth** [comment]
Hi,
Yes, we're aware of this, and have #1788 open to change it. I hope we can merge this shortly.

**Comment by rnorth** [comment]
#1788 Merged and will be released shortly.
