### ISSUE TITLE
JdbcDatabaseContainer. constructUrlForConnection() returning malformed URLs

### ISSUE THREAD

**Issue by mahwy** [testcontainers/testcontainers-java#1976]
JdbcDatabaseContainer. constructUrlForConnection() is a simple method that concatenates JDBC URL and a query string starting with `?`. 

https://github.com/testcontainers/testcontainers-java/blob/d3ba8428d7494a522b49792bc04d528fb70fea4f/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java#L222-L224

But `PostgreSQLContainer. getJdbcUrl ()` returns a JDBC URL with the query string `?loggerLevel=OFF` (The change was introduced from this PR: https://github.com/testcontainers/testcontainers-java/pull/1434/files#diff-d62130004eb8d994f60b87f95b1488be)

https://github.com/testcontainers/testcontainers-java/blob/d3ba8428d7494a522b49792bc04d528fb70fea4f/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L62

This returns invalid URLs for `PostgreSQLContainer`s with custom parameters. For example, given the following URL:
`jdbc:tc:fevopostgresql:9.6.11://hostname/databasename?stringtype=unspecified`,
the produced connection URL is
`jdbc:postgresql://localhost:32793/databasename?loggerLevel=OFF?stringtype=unspecified` instead of `...&stringtype=unspecified`

**Comment by francoiskha** [comment]
Please re-open

**Comment by rnorth** [comment]
This was released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0 🎉

Thanks for the contribution!
