### ISSUE TITLE
Service Unavailable | unable to connect to https://quay.io/v2/ inside private network 

### ISSUE THREAD

**Issue by juancdelgado** [testcontainers/testcontainers-java#1981]
I'm inside my company network which I go through a proxy to access external sites.

When building my container inside y spring boot application, I'm receiving a `Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: Service Unavailable"}`

When I access the link, I'm able to connect via chrome

I have tried using a docker compose file (which i am able to run with no issues using `docker-compose up`) and my container starts up with no issues.

I tried two different methods: one starting up using the docker image name and another with the docker compose file passed in, both fail.
```
@Testcontainers
public class ElasticSearchServiceTest {

  @Container
  public static DockerComposeContainer compose =
      new DockerComposeContainer(
          new File("src/test/resources/docker-compose.yml"))
          .withExposedService("elasticsearch", 9200);
```

I also tried creating it with the docker image name:
```
@Testcontainers
public class ElasticSearchServiceTest {

  @Container
  public static ElasticsearchContainer compose =
      new ElasticsearchContainer(
          "hub.docker.prod.<company_name>.com/library/elasticsearch:7.0.0")
          .withExposedPorts(8080);
```

since i am able to hit the the site with no issues via chrome and I am able to start the container via `docker-compose up` I am not sure what the issue may be.

I get the exact same error for both. 

The dependencies i'm using are:
```
  <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>1.12.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>elasticsearch</artifactId>
      <version>1.12.2</version>
      <scope>test</scope>
    </dependency>
```

What can i do to work around it? Can someone provide examples?

**Comment by borisklug** [comment]
We have the same problem in our company network.
