### ISSUE TITLE
Container exited immediately. Trying to copy jacoco agent jar

### ISSUE THREAD

**Issue by Asisranjan** [testcontainers/testcontainers-java#1982]
I would like to mount volume to docker container. But failed all the time. I would like to attach jacoco agent to container. Let me know if there is alternate available.

I tried following approach

.withFileSystemBind("./build/jacoco-report", "/tmp", BindMode.READ_WRITE)
                .withEnv("JAVA_TOOL_OPTIONS", "-javaagent:/opt/org.jacoco.agent-0.8.5.jar=destfile=/tmp/jacoco-it.exec")
                .withCopyFileToContainer(MountableFile.forHostPath("./lib/org.jacoco.agent-0.8.5.jar"),"/opt/")

and also tried withClasspathResourceMapping. In this case org.jacoco.agent-0.8.5.jar presents in resources.

my container exited immediately

**Comment by Asisranjan** [comment]
Solved.

**Comment by schowave** [comment]
Hey @Asisranjan : How did you solve the problem?

**Comment by Asisranjan** [comment]
Hi @schowave 

In test code, i could able to manage to write mapped port of jacoco agent to properties file. Then from build code using command, able to dump exec.

sample build code (used gradle)

task integrationTest(type: Test) {

    useJUnitPlatform() {
        includeTags 'Integration'
    }

    doLast{
        ext{
            file("/tmp/config.properties").withReader {
                Properties props = new Properties()
                props.load(it)
                JACOCO_PORT = props.getProperty("jacoco.port")
            }
        }

        def buildDir = project.buildDir.absolutePath
        def rootDir = project.rootDir.absolutePath

        def jacocoCliCmd = "java -jar " + rootDir + "/lib/jacococli.jar dump --destfile " +
                buildDir + "/jacoco/jacoco-itest.exec --port " + JACOCO_PORT

        Process process = jacocoCliCmd.execute()
        def out = new StringBuffer()
        def err = new StringBuffer()
        process.consumeProcessOutput( out, err )
        process.waitFor()
        if( out.size() > 0 ) println out
        if( err.size() > 0 ) println err
    }
}

**Comment by schowave** [comment]
Thanks @Asisranjan for that code snipped! 

I managed to get this to be running, but right after the connection is established from the jacococli, the socket closes unexpectedly. I have a microshed test running with a sharedcontainerconfig:

`@MicroShedTest
@SharedContainerConfig(IntegrationTestContainer.class)
public class TestIT {..}`

This is the container:
`  @Container
  public static ApplicationContainer app =
      new ApplicationContainer()
          .withAppContextRoot("/backend")
          .withReadinessPath("/health/ready")
          .withNetwork(network)
          .withExposedPorts(9080, 6300)
          .dependsOn(db2Container);`

So the container seems to be shutting down before the cli can get the jacoco informations. Do you have any hint on that issue?

Thanks again!
