### ISSUE TITLE
deprecation notice of CreateContainerCmd methods in docker-java 3.1.5

### ISSUE THREAD

**Issue by nixgadget** [testcontainers/testcontainers-java#1988]
`docker-java` upgrade to 3.1.5 introduced deprecation of `withPortBindings`.

So this is no longer possible for instance,
`static Consumer<CreateContainerCmd> cmd = e -> e.withPortBindings(new PortBinding(Ports.Binding.bindPort(VAULT_PORT), new ExposedPort(VAULT_PORT)))`

I specially use to override the behaviour in VaultContainer as I'd like to use a fixed port in the tests.

Whats the best way forward for this ?

I tried the following to no avail,
```
static Consumer<CreateContainerCmd> cmd = e -> e.withHostConfig(HostConfig.newHostConfig().withPortBindings(new PortBinding(Ports.Binding.bindPort(VAULT_PORT), new ExposedPort(VAULT_PORT))).withPublishAllPorts(true))
```

**Comment by chinthaka-dinadasa** [comment]
We have the same requirement when running cucumber tests running with keycloak test container. This is because we need to identify keycloack API URL on the application configuration level. hence we need to add a hardcoded port number.

**Comment by bsideup** [comment]
Please raise an issue (or find an existing one) in docker-java project.
