### ISSUE TITLE
Issue using @Transactional annotation above integration test class for multithreading  environment

### ISSUE THREAD

**Issue by arakorno** [testcontainers/testcontainers-java#1994]
Application stack: Spring boot 2.1v+ testcontainers postgresql  1.10.3v+ JUnit 4.12v
When I run the integration test for code which calls JPA repository within a new thread I'm getting data which was populated during starting PostgreSQLContainer and I can't receive data from the script above class test( @Sql(scripts ="data.sql"). But when I remove @Transactional annotation above the test I can get data both from SQL script from test and test container. 
My question is it possible to get data in multithreading environment from test script without removing @Transactional annotation?
Thank you for your answer!

**Comment by bsideup** [comment]
Sorry, but this is not related to Testcontainers project. Consider asking help from Spring Boot + Spring Data communities.
Feel free to reopen if they bounce back to us, which is unlikely :)
