### ISSUE TITLE
DockerComposeContainer fails on Travis-CI

### ISSUE THREAD

**Issue by arcuri82** [testcontainers/testcontainers-java#1998]
Hi,
  I have a series of tests using DockerComposeContainer (latest 1.12.2). All of them pass on my local machines (Windows 10 and Mac). However, one of those tests fails on Travis.
The only special thing (compared to the other tests) is that I expose a port directly from Testcontainer, ie:

```
@Container
@JvmField
 val env = KDockerComposeContainer("gateway", File("../docker-compose.yml"))
       .withExposedService("eureka", 8761,
                    Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(240)))
       .withLocalCompose(true)
```

as Travis is quite slow, I explicitly wait up to 4 minutes for that service to be available.

However, the test on Travis fails with:
```
[ERROR] org.tsdes.advanced.microservice.gateway.e2etests.GatewayRestIT  Time elapsed: 29.656 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container gateway18z92y_eureka_1 as it is not running
```

The problem is that it fails within 30 seconds. It looks like somehow the 240 value I set is ignored.

The test is in a public open-source project, and you can find the code at [GatewayIntegrationDockerTestBase](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/microservice/gateway/gateway-e2e-tests/src/test/kotlin/org/tsdes/advanced/microservice/gateway/e2etests/GatewayIntegrationDockerTestBase.kt)  and [GatewayRestIT](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/microservice/gateway/gateway-e2e-tests/src/test/kotlin/org/tsdes/advanced/microservice/gateway/e2etests/GatewayRestIT.kt).

**Comment by adaykin** [comment]
I'm experiencing issues as well where tests pass locally and fail in TravisCI. For reference, here's the class that is being ran https://github.com/CMSgov/ab2d/blob/master/e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
