### ISSUE TITLE
Ryuk disabled but test-containers pull an undesired Alpine Image

### ISSUE THREAD

**Issue by majonga88** [testcontainers/testcontainers-java#2012]
Hello,

First of all, thank you for your great work about this library, it's very usefull for me. 

I have an issue when i'm pulling an image, i disable ryuk with this parameter `TESTCONTAINERS_RYUK_DISABLED` and it works well. The ryuk image is not pull, but i have an Alpine image pulled.

My code is like this :

```
SystemUtils.setEnv(Map.of("TESTCONTAINERS_RYUK_DISABLED", "true"));

DefaultDockerClientConfig clientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder()
          .withRegistryUrl("https://hub.docker.com")
          .withRegistryUsername(USERNAME)
          .withRegistryPassword(PASSWORD)
          .build();

DockerClient dockerClient = DockerClientBuilder.getInstance(clientConfig).build();

DockerClientFactory.instance().checkAndPullImage(dockerClient, "store/oracle/database-enterprise:12.2.0.1-slim");
```
There is any way to avoid the pull of Alpine image ?

Thank you for your help !

Ps: The class `SystemUtils` is an homemade class to put environment variables when i'm running my integration tests.

**Comment by bsideup** [comment]
The image is required when we initialize the client in `DockerClientFactory.instance()` and run the checks.

You can [disable them](https://www.testcontainers.org/features/configuration/#disabling-the-startup-checks), but there are some other images we may use, and I am not sure why you are concerned about the images we pull on a first place

**Comment by majonga88** [comment]
Ok i see. The cause is, i work for a company who disallow to bring images from DockerHub. I will override them by images pushed in our repository. Thank you for your quick answer.
