### ISSUE TITLE
please allow to configure ryuk port

### ISSUE THREAD

**Issue by peter-ponzel** [testcontainers/testcontainers-java#2021]
hello,

according to https://www.testcontainers.org/features/configuration/#disabling-the-startup-checks it is possible to disable ryuk completely but there is no way of changing ryuk default port (8080).

could you please add a way to configure this?

regards,
peter

**Comment by bsideup** [comment]
Hi @peter-ponzel,

Testcontainers starts everything on random ports, including Ruyk. Even tho the Ryuk process listens on 8080, it will be random on your machine (something like 35123).

**Comment by peter-ponzel** [comment]
mea culpa, had more than one change at a time which caused some confusion.
you're right, everything is works as expected :+1:
