### ISSUE TITLE
Use 'docker-compose down' in place of 'docker rm'

### ISSUE THREAD

**Issue by pcornish** [testcontainers/testcontainers-java#203]
If we switch to using `docker-compose down` we get network cleanup [for free](https://docs.docker.com/compose/reference/down/), meaning we can remove the network reaping code from the `ResourceReaper`.

This also means fewer exceptions thrown due to race conditions when a container is in the process of being killed by the current `docker-compose rm` method, but hasn't died by the time we try and remove the network, which results in:

    docker network rm net1      
    Error response from daemon: network net1 has active endpoints

**Comment by rnorth** [comment]
Was implemented in 1.1.5
