### ISSUE TITLE
checks.disable flag on the classpath does not work since 1.12.1

### ISSUE THREAD

**Issue by ClaudioConsolmagno** [testcontainers/testcontainers-java#2041]
I use testcontainers with spring-boot 2.19 having the `testcontainers.properties` file in the test resources directory. That file has a single line: `checks.disabled = true`. I upgraded recently from 1.12.0 to 1.12.3 and noticed the check.disabled property stopped working and that issue is present in all versions since and including 1.12.1.

Using `checks.disabled` in the global config file (home directory) works fine.

Looking through testcontainers code there was a refactoring that went in on 1.12.1 related to classpath properties so it's likely a regression bug from that.

**Comment by bsideup** [comment]
It is not a regression because this property was never supposed to be set in classpath's properties.
Checks are very important for understanding what's going wrong with your env and should be explicitly disabled per environment.

**Comment by ClaudioConsolmagno** [comment]
Ok, I'm confused. The doc page (https://www.testcontainers.org/features/configuration/) says configuration can be loaded from multiple locations, including the classpath. I've been using testcontainers since version 1.8 and this always worked for me.

I would have preferred to have this configuration in the classpath instead of having it set it globally as it's much simpler for me to add the config to my resources folder in my project than having to ssh to my build server and add that file there. It's just more self-contained that way and makes it explicit that my project only is excluding those checks and I can put a comment as to why I'm excluding it. Other projects don't have to.

**Comment by bsideup** [comment]
@ClaudioConsolmagno 

By putting this setting into the classpath, you implicitly disable the checks for **everyone** who will run these tests. We believe that the checks help to analyze the issues with environment and that they should only be disabled when one knows that the environment works correctly.

Hint: you don't need to SSH to your build server, you can just change it in `$HOME/.testcontainers.properties` as a shell step before running Maven/Gradle

**Comment by ClaudioConsolmagno** [comment]
:+1:
