### ISSUE TITLE
Support for absolute URL in Wait.forHttp 

### ISSUE THREAD

**Issue by agmyrek** [testcontainers/testcontainers-java#2047]
Currently **'Wait.forHttp**' only allows to pass relative paths, so that the base url is fix. The HttpWaitStrategy is always calling localhost.
It would be great if there is a possibility to make the Wait-strategy to call an absolute url different then localhost.

**Comment by neillfontes-sl** [comment]
What is the use case? Is your service url not reachable via `localhost` because of reasons? Or are you talking about another system/service url?

**Comment by agmyrek** [comment]
In my test im using testcontainers to launch an apache webserver as a http proxy. It is routing http calls to different services in our network. The webserver is not listening on localhost calls but on local.mydomain.de.
I would like to wait for a resource like 'local.mydomain.de/home' to reply with http status 200 because in my Selenium-Geb tests im dependent on that specific resource/service to be available.

**Comment by neillfontes-sl** [comment]
Thanks for sharing @agmyrek - Makes a lot of sense.
