### ISSUE TITLE
Wait.forLogMessage only matching entire lines

### ISSUE THREAD

**Issue by ravenblackdusk** [testcontainers/testcontainers-java#2064]
Why does Wait.forLogMessage only works if it could match an entire line?
If it is necessary to be this way, this should be mentioned at [docs](https://www.testcontainers.org/features/startup_and_waits/) and in the javadoc.

**Comment by bsideup** [comment]
The docs do mention regexp to match the line:
```java
Wait.forLogMessage(".*Ready to accept connections.*\\n", 1)
```

**Comment by ravenblackdusk** [comment]
@bsideup The docs show an example which is matching a line. They don't explicitly say the regex must match a line nor does the javadoc say so. If it was up to me I'd even name the method `Wait.forLogLine` and deprecate the current method. As you can see [here](https://github.com/testcontainers/testcontainers-java/issues/900) I am not the only one confused by this. Other people are probably wasting their time debugging this...

**Comment by bsideup** [comment]
The issue you linked was improved by #982 and now `.*` includes the line ending.
You can see some examples here:
https://github.com/testcontainers/testcontainers-java/blob/dd88880eee0a8f115c9222d45189bd23621d94d9/core/src/test/java/org/testcontainers/junit/wait/strategy/LogMessageWaitStrategyTest.java
