### ISSUE TITLE
DockerComposeContainer has to be started explicitly?!

### ISSUE THREAD

**Issue by ravenblackdusk** [testcontainers/testcontainers-java#2065]
This is unlike `GenericContainer`(which is not good because it makes it unfamiliar) and I'm not sure if its intentional; However if it is intentional this should be mentioned in the [docs](https://www.testcontainers.org/modules/docker_compose/).

**Comment by bsideup** [comment]
Both `DockerComposeContainer` and  `GenericContainer` implement `Startable` and have to be either explicitly started with `Startables#start` or by using the JUnit rules / extensions.

There is `@ClassRule` in the docs.

**Comment by ravenblackdusk** [comment]
I am using testcontainers-spock and looks like the `@org.testcontainers.spock.Testcontainers` annotation starts the containers that are **non static** fields of the class if the fields are explicitly typed(you cannot omit the type in groovy for these fields). Again `@org.testcontainers.spock.Testcontainers` lacks any javadoc to explain these stuff, but it seems you are no fan of documentation.
