### ISSUE TITLE
using MSSQLServerContainer logs messages about mysql at runtime 

### ISSUE THREAD

**Issue by carstenartur** [testcontainers/testcontainers-java#2084]
The reason is it starts com.mysql.cj.jdbc.AbandonedConnectionCleanupThread which might be fine but has a hardcoded thread name "mysql-cj-abandoned-connection-cleanup". Not sure if this is a problem. At least it is somehow confusing.

**Comment by bsideup** [comment]
`MSSQLServerContainer` does not start `AbandonedConnectionCleanupThread`.
I would suggest raising an issue in MySQL driver's tracker.

**Comment by carstenartur** [comment]
Thanks for checking this issue. Can you point me to the MySQL driver's tracker?

**Comment by bsideup** [comment]
No, unfortunately I am not aware of how they track the issues
