### ISSUE TITLE
release 1.1.4 to maven central

### ISSUE THREAD

**Issue by CodingFabian** [testcontainers/testcontainers-java#210]
Hi,
it seems that 1.1.4 was not yet successfully synced to central. Since the build is 2 days old, I thought I give you a ping

http://central.maven.org/maven2/org/testcontainers/testcontainers/

Thanks!

**Comment by rnorth** [comment]
Thanks - Maven Central sync had failed for some reason. Trying to resync
now!
-- 
Richard

**Comment by CodingFabian** [comment]
It has been synced now. thanks. http://central.maven.org/maven2/org/testcontainers/testcontainers/1.1.4/
