### ISSUE TITLE
Could not start container Timed out waiting for container port to open

### ISSUE THREAD

**Issue by Asisranjan** [testcontainers/testcontainers-java#2107]
getting "Could not start container Timed out waiting for container port to open" in jenkin ci. here is gist link https://gist.github.com/Asisranjan/f1adf2f81add7c1d144ef096682a31bc#file-testcontainer-logs-with-ryuk

**Comment by bsideup** [comment]
From the log it is clear that your test host can communicate to the container (because it can talk to Ryuk).

Make sure that the container is actually listening and still running (e.g. did not crash due to Out Of Memory).
