### ISSUE TITLE
Unable to access individual container(s) (or names) from DockerComposeContainer

### ISSUE THREAD

**Issue by snappy88** [testcontainers/testcontainers-java#2108]
After starting containers with DockerComposeContainer it would be nice to be able to access containers or have access to container names. The problem is the names are changed when testContainers starts the containers so they are unknown and different each execution.

I want to be able to stop and start individual containers during testing. If I could access the containers or the container names so I could use Citrus (or another tool) to stop and start.

**Comment by bsideup** [comment]
Stopping and starting will cause the ports to be re-assigned and likely to break your setup.

Consider using `GenericContainer`s and/or [the ToxiProxy module](https://www.testcontainers.org/modules/toxiproxy/) for chaos testing
