### ISSUE TITLE
check for docker availability

### ISSUE THREAD

**Issue by mvysny** [testcontainers/testcontainers-java#2110]
It would be good to have a way to check whether Docker is actually available or not, as a simple static boolean function, e.g. `public static boolean DockerClient.isDockerAvailable()`. That would allow us to use JUnit/TestNG-specific ways to skip tests which require docker containers.

**Comment by mvysny** [comment]
There is a similar feature request here: #343 . However, this feature request is much simpler.

**Comment by mvysny** [comment]
The PR https://github.com/testcontainers/testcontainers-java/pull/2605 can be used as follows: `DockerClientFactory.instance().isDockerAvailable()`.

Meanwhile you can add the following Kotlin code to your project as a workaround:

```kotlin
@Synchronized
fun DockerClientFactory.isDockerAvailable(): Boolean {
    // todo Remove when https://github.com/testcontainers/testcontainers-java/issues/2110 is fixed.
    val m = DockerClientFactory::class.java.getDeclaredMethod("getOrInitializeStrategy")
    m.isAccessible = true
    return try {
        m.invoke(this)
        true
    } catch (ex: Exception) {
        false
    }
}
```

**Comment by hardikarora26** [comment]
In java one can use the following:
```
try {
	DockerClientFactory.instance().client();
} catch (Exception e) {
      	Assert.fail(e.getMessage());
}
```

**Comment by jkosternl** [comment]
For others searching for a similar solution, this works in the current version of TestContainers:
`@Testcontainers(disabledWithoutDocker = true)`
The unit tests are skipped without errors.
