### ISSUE TITLE
withFileFromClasspath does not work for resources within a jar

### ISSUE THREAD

**Issue by hcoles** [testcontainers/testcontainers-java#213]
As per the title `ClasspathTrait.withFileFromClassPath` fails with

> Can't get size from blah blah blah path/SKYNET-0.7-SNAPSHOT.jar!/com/example/Dockerfile

When it is given a classpath resource within a jar.

For the moment I'm working round this with a transferable that copies the resource to a byte array

``` java
  static Transferable fromClasspath(final String resourcePath) {
    URL resource = ClasspathTrait.class.getClassLoader()
        .getResource(resourcePath);

    try (InputStream stream = resource.openStream()) {
      byte[] bytes = IOUtils.toByteArray(stream);

      return new Transferable() {
        @Override
        public long getSize() {
          return bytes.length;
        }

        @Override
        public void transferTo(OutputStream outputStream) {
          try {
            IOUtils.write(bytes, outputStream);
          } catch (IOException e) {
            throw new RuntimeException(
                "Can't transfer resource " + resourcePath, e);
          }
        }
      };
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  };
```

But it would be preferable for the DSL to support this.

**Comment by rnorth** [comment]
Fix released in 1.1.7 - sorry for the delay in getting this out.

The mounting of classpath resources from JAR files entails copying them out to a temporary folder, from where docker is able to mount it. This is used for loading default MySQL and MariaDB configurations now, so hopefully functions for your use case as well. There's no API change - just use `withClasspathResourceMapping` on any subclass of `GenericContainer`.
