### ISSUE TITLE
Ryuk container not removed

### ISSUE THREAD

**Issue by jsauvain** [testcontainers/testcontainers-java#2146]
While using the reusable container feature in #1781 the ryuk container will not be destroyed when manually stopping the testcontainer.

For example when starting an OracleContainer which has already been started and is being reused it won't destroy the "latest" ryuk container which has been created. 
```java
GenericContainer container = new OracleContainer(..)
  .withReuse(true)
  .start();
container.stop()
```

After further inspections it doesn't matter whether it already has a container or not.

**Comment by bsideup** [comment]
@jsauvain 

I just tried running a code that is similar to yours and it seems to work. Please share a demo project.

**Comment by jsauvain** [comment]
I found out that the ryuk container won't stop because it runs in the context of gradle. By using the --no-daemon option the ryuk container will shutdown. I don't know whether this is a bug, or not

**Comment by bsideup** [comment]
This is not a bug, Ryuk runs as long as the JVM that started it runs.
Since Gradle runs a daemon, it is expected that Ryuk will be running until you stop the daemon.
