### ISSUE TITLE
Bom points to version of library not published

### ISSUE THREAD

**Issue by gunkelolaf** [testcontainers/testcontainers-java#2147]
The testcontainers bom version 1.12.4 points to 

org.testcontainers:test-support:1.12.4
and
org.testcontainers:jdbc-test:1.12.4 

Both jars aren't published in the defined version.

Please publish the libraries or redefine the bom.

**Comment by bsideup** [comment]
Thanks, we just merged https://github.com/testcontainers/testcontainers-java/pull/2118 for that. Will be available in the next release.

Did it cause any troubles for you, btw? If so, what build system are you using?

**Comment by gunkelolaf** [comment]
We're using gradle and the spring dependencymanagement plugin.
Within our project we create a bom based on many dependency definitions and
boms which we audit and use in every Gradle project.
During our Audit process we found out that a dependency was defined that
isn't released, therefore we couldn't check for CVE-Audit markers.

**Comment by bsideup** [comment]
I see. Ok, thanks! The next version is expected to be released this week, I hope this will work for you.

P.S. is it only for 1.12.4 or previous versions were also affected?

**Comment by gunkelolaf** [comment]
affected versions: 1.12.4 - 1.12.0(excluded)

**Comment by bsideup** [comment]
Should be released in 1.12.5
