### ISSUE TITLE
Add documentation on JUnit5 "dependsOn"

### ISSUE THREAD

**Issue by orevial** [testcontainers/testcontainers-java#2166]
A great feature of JUnit5 resides in the ability to declare containers that depend on each other.

For example if I need a Kafka container that will use a schema registry, then I also need to spawn a schema registry container that `dependsOn` my kafka container, as described in the following example:

```java
@Container
private static MyKafkaContainer kafka = new MyKafkaContainer<>();

@Container
private static MySchemaRegistryContainer registry = new MySchemaRegistryContainer("5.2.2")
    .withKafka(kafka)
    .dependsOn(kafka);
```

This is a common scenario and should probably be documented for users to find it :slightly_smiling_face: 

I will make a pull request with this suggested change.

**Comment by bsideup** [comment]
FYI it works with any container, not just JUnit 5 :)

**Comment by orevial** [comment]
Hum interesting, so the same thing applies using JUnit4 `@Rule` annotation or Spok system ?

If so I might suggest adding this doc under `Features` menu, for example here:

![Capture du 2019-12-10 16-53-07](https://user-images.githubusercontent.com/5528566/70545829-7d413780-1b6e-11ea-88c2-78ba33de3ce7.png)

**Comment by bsideup** [comment]
> so the same thing applies using JUnit4 @Rule annotation or Spok system ?

Yes, that's correct. It is part of the `Startable` protocol and is not framework dependent:)

You suggestion sounds good 👍

**Comment by eddumelendez** [comment]
This has been added [here](https://www.testcontainers.org/features/startup_and_waits/#depending-on-another-container)
