### ISSUE TITLE
Generate GitHub Actions test configs for subprojects 

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#2177]
With GitHub Actions on the free tier we can run up to 20 concurrent steps. We should utilise this to speed up our CI test time for builds. 

If we split our test invocation into smaller units (e.g. one discrete parallel job for each Gradle sub project) we should be able to reduce the length of our feedback loop. Currently we have some manually defined, pretty arbitrary, divisions of modules into different jobs, but automating this would be a maintainability improvement.

**Comment by rnorth** [comment]
See also #1836

**Comment by eddumelendez** [comment]
Closing due to it is already implemented via #2520
