### ISSUE TITLE
NetworkImpl.NetworkImplBuilder should not allow to reassign id()

### ISSUE THREAD

**Issue by leventov** [testcontainers/testcontainers-java#2185]
NetworkImpl.NetworkImplBuilder should not allow to reassign `id()` because it will have no effect on the actual id.

Also, strictly speaking, `close()` may not see the `id` value if called from another thread than `getId()`. To ensure that, `close()` method should be synchronized as well as `getId()`. I'm not sure how relevant this is, but since `getId()` is synchronized itself it might be.

**Comment by bsideup** [comment]
Hi @leventov,

Thanks for reporting. The issue is up for grabs in case somebody wants to convert the suggestions into a PR.

**Comment by Mariochino** [comment]
#2450

**Comment by quincy** [comment]
I've submitted a PR to resolve this issue.  https://github.com/testcontainers/testcontainers-java/pull/2807
