### ISSUE TITLE
Foundationdb support

### ISSUE THREAD

**Issue by ngbinh** [testcontainers/testcontainers-java#2193]
It would be great if testcontainers support foundationdb https://www.foundationdb.org/

**Comment by ngbinh** [comment]
no

**Comment by bsideup** [comment]
I am afraid we will have to close it, unless someone is willing to work on it:
https://www.testcontainers.org/contributing/#contributing-new-modules

**Comment by everlylfc** [comment]
Having this would have saved me hours of research, so here is what I used for anyone who needs it:
```java
	private static final String FDB_NETWORKING_MODE_KEY = "FDB_NETWORKING_MODE";
	private static final int FDB_PORT = 4500;

	@ClassRule
	private FixedHostPortGenericContainer<?> fdbContainer = new FixedHostPortGenericContainer<>("foundationdb/foundationdb:6.2.19")
			.withFixedExposedPort(FDB_PORT, FDB_PORT)
			.withExposedPorts(FDB_PORT)
			.withEnv(FDB_NETWORKING_MODE_KEY, "host").withFileSystemBind("./etc", "/etc/foundationdb")
			.waitingFor(Wait.forLogMessage(".*FDBD joined cluster.*\\n", 1));
```

This gives you a container to work with. You still need to set up the FDB cluster file and create the database and so on.

**Comment by rnorth** [comment]
Please avoid using FixedHostPortGenericContainer - it’s really risky in terms of port conflicts, and we will be moving to deprecate it.
