### ISSUE TITLE
Localstack - Amazon SNS - Topic does not exists - Unable to Send SMS

### ISSUE THREAD

**Issue by piotrmackowiak** [testcontainers/testcontainers-java#2198]
There is is impossible to send SMS with testcontainer because of 

`com.amazonaws.services.sns.model.NotFoundException: Topic does not exist (Service: AmazonSNS; Status Code: 404; Error Code: NotFound; Request ID: 193cc1a7)` 

the problem is that original amazon sdk does not require topic to do this. Here is source code what works correctly with Amazon SDK (and not with testcontainer) 

`PublishResult publishResult = amazonSNS.publish(new PublishRequest()
			.withMessage(smsMessage.getFormattedMessage())
			.withPhoneNumber(smsMessage.getPhoneNumber())
			.withMessageAttributes(smsConfigurationAttributes)
);` 

Amazon SDK version:  1.11,642
Testcontainers version: 1.12.3

**Comment by bsideup** [comment]
Please report it to the LocalStack project.
