### ISSUE TITLE
 A connection to http://docker.socket/ was leaked

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#2209]
Hi guys, just noticed that the following warning happens from time to time (not easy to reproduce):

```
12:08:27.540 [main] INFO  o.x.t.d.i.j.XWikiDockerExtension - (*) Start VNC container...
12:08:32.120 [main] INFO  o.x.t.d.i.j.XWikiDockerExtension - (*) Starting test [deleteChildren]
Dec 22, 2019 12:08:52 PM org.testcontainers.shaded.okhttp3.internal.platform.Platform log
WARNING: A connection to http://docker.socket/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
12:08:52.845 [main] INFO  o.x.t.d.i.j.XWikiDockerExtension - (*) Stopping test [deleteChildren]
```

Anything that can be done?

I'll try to reproduce with the log level set to FINE.

**Comment by bsideup** [comment]
Hi @vmassol,

Thanks for the report!
There was an issue in docker-java that caused some InputStreams to leak:
https://github.com/docker-java/docker-java/pull/1290

We're working on releasing docker-java 3.2.0 (that includes the fix) and will upgrade it in Testcontainers shortly after.

**Comment by vmassol** [comment]
Excellent! Thanks

**Comment by vmassol** [comment]
I guess this should stay open... Unless the last version of TC (1.13.0) includes docker-java 3.2.0 already?

**Comment by rnorth** [comment]
@bsideup is actively working on this - not stale!

**Comment by nachevn** [comment]
@bsideup any updates here?

Thanks
Nikolay

**Comment by bsideup** [comment]
@nachevn good question! Any updates? Is it still reproducible with the latest Testcontainers that depends on docker-java 3.2.x? :)

**Comment by nachevn** [comment]
@bsideup yes, indeed it is a good question. It occurs but not every time which makes it (unfortunately) not reproducible. Just for information we are using testcontainers version 1.15.0-rc1

**Comment by ravenblackdusk** [comment]
@bsideup I'm getting this on 1.15.0

**Comment by bsideup** [comment]
@ravenblackdusk please try 1.15.1 then :)

**Comment by ravenblackdusk** [comment]
@bsideup I'm still getting this with 1.15.1

**Comment by perlun** [comment]
@bsideup Regretfully also seeing this on 1.15.1 sometimes.
