### ISSUE TITLE
Running TestContainers outside of Junit context

### ISSUE THREAD

**Issue by imochurad** [testcontainers/testcontainers-java#2247]
This is more a question than an issue: 
I would like to use TestContainers also when I start my app in local environment via IDE or by running a jar directly. I would like to start a container (ElasticSearch) and let my app rely on it. So that I do not have to deploy locally ElasticSearch cluster.
But TestContainers are tightly coupled with JUnit. I think this coupling is not necessary.
Thoughts?

**Comment by bsideup** [comment]
> But TestContainers are tightly coupled with JUnit

It is not. There is built-in support for JUnit Rules (hence strict dependency on junit4, to be removed soon) but it only calls methods of `Startable` (read: `.start()` and `.stop()/.close()`) and, if implemented, `TestLifecycleAware`.

That said, Testcontainers 2.0 will ship a real "core" module that does not depend on any testing framework, and the integrations will be implemented as modules (in the same manner as JUnit 5 / Spock / ScalaTest support is implemented ATM)

**Comment by bsideup** [comment]
See https://github.com/testcontainers/testcontainers-java/issues/970 for more details.

I will close this question since it duplicates [the previous ones from the 2.0 milestone](https://github.com/testcontainers/testcontainers-java/milestone/20).
