### ISSUE TITLE
Database container withInitScript() doesn't run MySQL statements accurately

### ISSUE THREAD

**Issue by rehevkor5** [testcontainers/testcontainers-java#2256]
When starting a `MySQLContainer` and using `withInitScript`, the SQL statements in the script are not run faithfully, because testcontainers-java is using its own SQL parsing logic in order to extract individual SQL statements from the script.

In particular, the issue I am seeing is that the `#` character is not recognized as an inline comment character (see https://dev.mysql.com/doc/refman/5.6/en/comments.html ), therefore the first statement after an inline comment is combined with the comment. A single line string including the whole inline comment(s) plus the following statement (without any line breaks) is executed against the database. And, of course, is ignored as being a comment.

This is also problematic/confusing because from testcontainer's perspective, the statement executed successfully (there's no way for it to fail because from the database's perspective it's a comment)! Therefore, you might only notice this issue occurring if it causes a referential integrity error in a later statement, or if you have some other mechanism which allows you to notice the absence of the statement's effect on your database. Otherwise, it fails silently.

Ideas/alternatives:

- Remove ad-hoc SQL parsing logic from the code base entirely, and rely on mounting files to `/docker-entrypoint-initdb.d` for MySQL, for example. This library will no longer need to maintain its own SQL parsing logic which may yet be the source of more undiscovered bugs.
- Update ScriptUtils to support `#` for inline comments
- Add javadoc to `withInitScript` (right now it has none) and other relevant documentation and mention that `#` for comments is not supported.
- Depend on a well-maintained open source implementation of SQL parsing which works properly, if one exists.

**Comment by AllirionX** [comment]
I am facing the same issue. Is there a workaround to this problem?
