### ISSUE TITLE
System Check getting stuck

### ISSUE THREAD

**Issue by IainVM** [testcontainers/testcontainers-java#2269]
Running this on a Jenkins slave and when Test Containers does the System Check it does the following:

```
configFile: /var/jenkins/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /var/jenkins/.docker/config.json (No such file or directory) 
2020-01-20 15:48:09,938 INFO [org.testcontainers.DockerClientFactory] - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit 
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
```
Though doesn't move on after that, we don't see the "Must have 2GB storage" message after.

**Comment by bsideup** [comment]
Hi @IainVM,

Please add more details like the Testcontainers version you're using, Java version, environment details (OS, version, Docker's version, etc etc)

**Comment by IainVM** [comment]
```
TestContainers Version: 1.11.3
Java Version: java version "1.8.0_101"
Env Details:
    OS: Centos 7
    Docker Version: Docker version 1.13.1, build 7f2769b/1.13.1
    Available Storage: 34GB
```

Using it to bring up a postgres container.

**Comment by bsideup** [comment]
> Docker version 1.13.1

This is a very old version of Docker and may no longer work, consider updating to the latest Docker CE

**Comment by IainVM** [comment]
We're in the process of updating that, though I have other Jenkins slaves with the same java version, docker version, os, and testcontainers version which isn't showing this issue.

**Comment by bsideup** [comment]
Then I would suggest checking the differences since it does not sound like an issue with Testciontainers if other similar configs work just fine

**Comment by IainVM** [comment]
Agreed, didn't realise that part until after getting the environment information.

Though they were all set up with Ansible playbooks. So a little lost where they could differ.  

I'll close the issue since it seems to be environmental possibly.
