### ISSUE TITLE
Version 1.12.5 not available on Maven Central

### ISSUE THREAD

**Issue by dreis2211** [testcontainers/testcontainers-java#2274]
Hi,

I saw that 1.12.5 seems to be released, but not available on Maven Central. To the best of my knowledge you're publishing to Bintray and then it gets synced to Maven Central. I'm wondering if the sync failed.

Cheers,
Christoph

**Comment by bsideup** [comment]
We have an ongoing issue with Bintray, see this thread on Twitter:
https://twitter.com/bsideup/status/1219269843830091776

**Comment by dreis2211** [comment]
Thanks @bsideup

**Comment by surli** [comment]
Any open issue to follow on this matter? Just to be informed when it's solved. Looks like it's still not available on central.

**Comment by dreis2211** [comment]
I was hoping that the switch to Travis sorted things out, but apparently it didn't (yet)

**Comment by bsideup** [comment]
I will update the status here.

We've progressed with the publication (apparently there was an issue with GitHub Actions + Bintray) but now it is missing on JCenter :D 
See https://twitter.com/bsideup/status/1220283519085223936

**Comment by bsideup** [comment]
It should be available on Maven Central now. Thanks for reporting!
