### ISSUE TITLE
Problems with hebrew data being inserted

### ISSUE THREAD

**Issue by vicmosin** [testcontainers/testcontainers-java#2278]
With the following connection string: 

`jdbc:tc:mariadb://localhost/some?TC_MY_CNF=mysql&useUnicode=yes&characterEncoding=utf8mb4` 

my.conf add the following settings (in addition to default ones)

```
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
...
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

Any SQL insert query with unicode data fails with:
`Caused by: java.sql.SQLException: Incorrect string value: '\xD7\x94\xD7\x92\xD7\x9C...' for column 'Name' at row 1`

**Comment by Freeongoo** [comment]
please fix it
