### ISSUE TITLE
Add files or directories to container does not work

### ISSUE THREAD

**Issue by jboesl** [testcontainers/testcontainers-java#229]
I'm on linux and using docker-machine to connect to virtualbox boot2docker instance.
Now I want to add my current application I'm working on to the container. My first shot was using volumes with 'withClasspathResourceMapping'. For each file I tried to map it created a directory on my boot2docker instance. So after a few tries I had a lot of persisted directories on my docker host but no files in my containers. 
Then I found out that volume mapping doesn't work with native docker client to the container, too. So the next try was building an image with my resources included. That works fine when I create a Dockerfile with a line like 'ADD . /target'. I tried the same with testcontainers. First problem was that I was not able to add directories. But that's okay. I can zip my files and the unpack it in the container. But then again when I call 'new ImageFromDockerfile("servlet").withFileFromPath' the file is added to the docker host only and not to the container.

Maybe I'm just doing it wrong I'm not too sure. Here is an example of what I tried:

```
GenericContainer c = new GenericContainer<>(
      new ImageFromDockerfile("servlet")
          .withDockerfileFromBuilder(builder -> builder.from("tomcat:9"))
          .withFileFromPath("/usr/local/tomcat/webapps/ROOT.war", Paths.get("target/ROOT.war")));
c.start();
```

**Comment by rnorth** [comment]
Sorry for the delayed response to this. @bsideup do you have any thoughts about what could be going wrong here?

**Comment by bsideup** [comment]
@rnorth @jboesl I guess the order of arguments in `withFileFromPath`

**Comment by bsideup** [comment]
First of all, I don't really recommend you to do that. It will pollute your Docker images because for each new .war build it will create a new image.

There is `withFileSystemBind` in GenericContainer, it should cover the case. 
Also, I highly recommend you to verify that `Paths.get("target/ROOT.war")` is a valid path and points to your file (check an absolute path of it)

**Comment by jboesl** [comment]
I'm quite sure `withFileSystemBind` did not work. I tried a lot of different configurations.
I now got it working with following code:

`public GenericContainer c = new GenericContainer<>(
      new ImageFromDockerfile()
          .withDockerfileFromBuilder(builder -> builder
              .from("tomcat:9")
              .run("rm -rf /usr/local/tomcat/webapps/ROOT")
              .copy("ROOT.war", "/usr/local/tomcat/webapps/ROOT.war")
          )
          .withFileFromPath("ROOT.war", Paths.get("target/ROOT.war")));`

**Comment by bsideup** [comment]
Ah, yes. `withFileFromPath` will just put a file to the context. But you have to call "ADD" or "COPY", of course

**Comment by jboesl** [comment]
Okay, that wasn't clear to me.
If that is the way it's thought to be used everything is fine.
So I'm closing this issue.

**Comment by electrocnic** [comment]
I have the same issue, but I think it might also be just me incorrectly using `withClasspathResourceMapping`:

I do not have the option to bind a file which I need inside the container directly when I create the docker container.

I want to bind a file somewhere in the middle of my code.
`withClasspathResourceMapping` does not seem to work:
I can clearly see the bind itself was somehow successful, as the return value of this method has an attribute `binds` which is a List containing the expected file mapping. The file path from the host is correct and the mapped path in the container as well.

But when I bash into my container from my commandline with `docker exec -ti <container-id> /bin/bash` I simply cannot find the file anywhere. I should find it in the directory which I provided for the bind, should'nt I?

```
runningContainer.withClasspathResourceMapping(filename, "/tmp/" + filename, BindMode.READ_ONLY);
```
But the file is not in `/tmp/`.

Thanks!
