### ISSUE TITLE
Make it possible to obtain a reference of type `Container` to services started by Docker Compose

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#2302]
Since `DockerComposeContainer#project` is private, there is currently no way of accessing containers started by Docker Compose.

We should add a public API to access them, something like:
```java
public ContainerState getServiceContainer(String serviceId);
```

We already do something similar here:
https://github.com/testcontainers/testcontainers-java/blob/500fd7404c07712c1f8af2d5f6ba51a048b9f6da/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L256-L263
And store it in:
https://github.com/testcontainers/testcontainers-java/blob/500fd7404c07712c1f8af2d5f6ba51a048b9f6da/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L71

Which means that the implementation should be a simple look up.

This will also solve #1916 and similar requests.

**Comment by artjomka** [comment]
I would like to work on it
