### ISSUE TITLE
Checks not disabled by .testcontainers.properties?

### ISSUE THREAD

**Issue by membersound** [testcontainers/testcontainers-java#2312]
I have the `.testcontainers.properties` with content `checks.disable=true` in both `/src/test/resources` and also in the root of my project.

Anyhow checks are not disabled:
```
2020-01-30 13:26:00.745  INFO 17417 --- [           main] org.testcontainers.DockerClientFactory   : Checking the system...
2020-01-30 13:26:00.745  INFO 17417 --- [           main] org.testcontainers.DockerClientFactory   : ✔︎ Docker server version should be at least 1.6.0
2020-01-30 13:26:00.992  INFO 17417 --- [           main] org.testcontainers.DockerClientFactory   : ✔︎ Docker environment should have more than 2GB free disk space
```

Sample:
```
@SpringBootTest
@Testcontainers
public class MainAppTest {
	@Container
	private MariaDBContainer db = new MariaDBContainer();

	@Test
	public void testInit() {
		assertTrue(db.isRunning());
		assertTrue(TestcontainersConfiguration.getInstance().isDisableChecks()); //fails
	}
}
```

```
spring.datasource.url=jdbc:tc:mariadb:///test
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
```
[testcontainers-example.zip](https://github.com/testcontainers/testcontainers-java/files/4133950/testcontainers-example.zip)

**Comment by bsideup** [comment]
We intentionally changed it.

It always was a property of the environment, not project, and disabling the checks for every user of the repo is not the behaviour we want to support.

It is an optimization for those who already checked that their environment works correctly (and know how to debug it) that should not be applied to the new users who run the tests for the first time and observe issues with their environment without any information why it fails.

**Comment by bsideup** [comment]
To disable the checks per environment, see:
https://www.testcontainers.org/features/configuration/#disabling-the-startup-checks

**Comment by membersound** [comment]
Is there any way I could disable the checks during a gitlab ci docker build? I mean, via environment variable for example?

**Comment by bsideup** [comment]
only with file at the moment.

**Comment by membersound** [comment]
I can confirm the following setting in a `gitlab-ci.yml` disables testcontainers checks:

```
variables:
  TESTCONTAINERS_CHECKS_DISABLE: "true"
```
