### ISSUE TITLE
Oracle XE: very long wait times until container is ready

### ISSUE THREAD

**Issue by davidkron** [testcontainers/testcontainers-java#2315]
Hello

We are currently evaluating Testcontainers for new Projects as it seems like a very nice library and a good idea. We are using **Oracle XE** databases for development and would also like to run integration tests during development with this database setup by using Testcontainers.

Unfortunately the startup time until the Testcontainer ist ready takes about **4 minutes**, which is not very practical during development.

We are using a self-built **Oracle XE 18.4.0** docker image according to the official repository: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles

Are there any measures to optimize the startup time?

We are using the following Java code to initialize Testcontainers:
`OracleContainer oracleContainer = new OracleContainer("oracle/database:18.4.0-xe");`

We also found and tried the following option to reuse an existing container in the API, but this doesn't affect the startup time at all:
```
OracleContainer oracleContainer =
        new OracleContainer("oracle/database:18.4.0-xe")
                .withReuse(true);
```

**Comment by AnEmortalKid** [comment]
How long does the container take just by doing docker run? In my experience it hasn’t been the test containers startup time but the actual startup time for the container that is the problem.

**Comment by davidkron** [comment]
You are right. I ran the image manually and it does take a lot of time as well. From the log output it seems that the Oracle image always does a full installation of the oracle database first.

**Comment by AnEmortalKid** [comment]
Our XE version took about 15 seconds to start. We based it off the first wnameless image. Could you potentially start the image, take a snapshot and tag that as your new image. Then you use that already created database instead?

**Comment by bsideup** [comment]
> but this doesn't affect the startup time at all

Have you followed the steps to enable the reuse on your environment as [described in the PR](https://github.com/testcontainers/testcontainers-java/pull/1781), `Prerequisites` section?

**Comment by davidkron** [comment]
@bsideup Yes I configured it like this, but no effect.

Since I don't know the implementation of the reuse functionality I am not sure how it should work. What I would expect from the naming but without actually knowing the implementation detail is, that Testcontainers would not stop containers after testing and reuse an already running container for new test runs. Is this correct or did I misunderstand the feature?

What I discovered is, that the container is always stopped after testing when using `docker ps`.

Maybe I should add that I am trying to use Testcontainers with Spock Framework, since the Spock extension might act differently to JUnit.

**Comment by bsideup** [comment]
@davidkron 
That's correct, yes. Note that if you call `stop()` (or annotate it with `@Rule`/`@Container`) then it will be stopped, no magic here.
You can use [the Singleton Container Pattern](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers) to avoid stopping it after the tests

**Comment by davidkron** [comment]
Thank you for the support. I now understand Testcontainers a bit better!

I now think the problem really is the Oracle XE docker image and Testcontainers seems to work as expected. It seems I have to look more into the docker side and find a way to optimize the Oracle XE image. Unfortunately the `docker commit` as suggested by @AnEmortalKid doesn't work well with the Oracle docker image (doesn't startup when using commited image).

So, if you want you can close this issue since the slow start of the Oracle image isn't really something Testcontainers can do something about.

**Comment by AnEmortalKid** [comment]
We used a RUN command in our own extension that just called the same
command the wnameless one does when it uses the CMD directive. So part of
the image building would be starting it and loading the data.

**Comment by KyleAure** [comment]
@davidkron another thing you will want to do to ensure a quick startup time with oracle is to follow their guide on creating a docker image with a prebuilt database. https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb

The problem with the default script for creating an oracle-xe docker image is that on startup a script is run to create the database.  In my experience this does take around 4 minutes (same as you have experienced).  By creating a prebuilt image the container should come up and just check that the database is ready.

**Comment by davidkron** [comment]
@KyleAure Thank you for the tip. I did create an image according to the guide and it did take down the startup time significantly!
