### ISSUE TITLE
Does docker compose module support Image Pull Policy?

### ISSUE THREAD

**Issue by askfor** [testcontainers/testcontainers-java#2317]
It seems docker compose module only pulls image if the image not present.
Does it support Image Pull Policy
https://www.testcontainers.org/features/advanced_options/#image-pull-policy ?

**Comment by bsideup** [comment]
No, it doesn't. This is an advanced feature of `GenericContainer`. Consider using `GenericContainer` instead of Docker Compose if you have some specific needs, since it gives more power and control.

**Comment by askfor** [comment]
I think it's a very useful feature for docker compose module. 
Right now I use this method to pull images instead. ( it's a little inconvenient RemoteDockerImage is not a public class).

`public void pullImages(List<File> composeFiles) {
        Set<ParsedDockerComposeFile> parsedComposeFiles = composeFiles.stream()
            .map(ParsedDockerComposeFile::new)
            .collect(Collectors.toSet());

        parsedComposeFiles.stream()
            .flatMap(it -> it.getServiceImageNames().stream())
            .forEach(imageName -> {
                try {
                    new RemoteDockerImage(imageName).withImagePullPolicy(PullPolicy.alwaysPull())
                        .get();
                } catch (Exception e) {
                    logger.warn("Failed to pull image '{}'. Exception message was {}", imageName,
                        e.getMessage());
                }
            });
    }`
So can DockerComposeContainer also change to use RemoteDockerImage to pull images? If it can, then make docker compose module support image pull policy is an easy job.

**Comment by bsideup** [comment]
uh? `RemoteDockerImage` is public.
It would be hard to support proper Image Pull Policy in Compose, since we cannot intercept Compose's pulling mechanism.

**Comment by askfor** [comment]
Sorry, I meant ParsedDockerComposeFile is not public.

Docker compose module didn't use docker compose pull. It just pulls very image one by one if image is missing.
