### ISSUE TITLE
Viewdocs links to example CI config files not resolving - was "docs missing example circle.yml"

### ISSUE THREAD

**Issue by ags799** [testcontainers/testcontainers-java#232]
Would like to use testcontainers in my Circle CI build, checked the [docs](http://testcontainers.viewdocs.io/testcontainers-java/) for assistance. They include [a link to an "example circle.yml"](http://testcontainers.viewdocs.io/circle.yml). This link leads to a 404.

Is there an existing example circle.yml for reference? Thanks.

**Comment by rnorth** [comment]
Hi @ags799 - sorry for the slow response. Sorry that the viewdocs link isn't resolving. The file that it's supposed to point to is this one: https://github.com/testcontainers/testcontainers-java/blob/master/circle.yml

It looks like the links in the docs index file need to be fixed to resolve files correctly in both Github and Viewdocs. Thanks for flagging this.

**Comment by ags799** [comment]
Thanks @rnorth. I can get my testcontainers setup running on Circle now.

[This](https://github.com/testcontainers/testcontainers-java/blob/master/circle.yml#L15) is the line I had to add to get testcontainers working on Circle. Do you mind explaining what that line does? Would be much appreciated.

**Comment by bsideup** [comment]
The link works now, so I'm closing this issue, but feel free to ask questions :)
