### ISSUE TITLE
How to ensure containers stop after spring ApplicationContext stoped?

### ISSUE THREAD

**Issue by pan3793** [testcontainers/testcontainers-java#2326]
I'm using testcontainers with spring boot test, here is a brief code snippet
```
@RunWith(SpringRunner.class)
@SpringBootTest
public abstract class IntegrationTestBase {
    @ClassRule
    public static MySQLContainer<?> mysql = new MySQLContainer<>("mysql:5.7.22")
            .withDatabaseName("publisher")
            .withUsername("test_user")
            .withPassword("test_password")
            .withInitScript("mysql/init.sql");
}
```
And there is a DisposableBean like it
```
@Component
public class JobService implements DisposableBean {
    @Override
    public void destroy() {
        .....
        // access mysql to insert one record
        jdbcTemplate.update(INSERT_JOB_SQL, some_params);
        ....
    }
}
```
But when I run it like this
```
    @Test
    public void test() {
        ...
        appCtx.stop();
    }
```
The database operate failed with the exception
```
11:49:01  WARN hikari.pool.PoolBase @176: HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@731dbeee (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
```
Then I set a breakpoint on method `destroy()`, and use `docker ps` to check running containers, the mysql container already has been destroyed.

I think it's sensible to ensure all thridparty services stop after spring ApplicationContext stoped. 
Is this a bug? Or it's by design and I use it in wrong way?

**Comment by bsideup** [comment]
`ClassRule` in the abstract class is dangerous because a new container will be created for each test class. Please check [our examples](https://github.com/testcontainers/testcontainers-java/tree/master/examples) on how to integrate it properly (either as a singleton container or by writing an initializer)
