### ISSUE TITLE
Custom responsebody checks on HttpWaitStrategy

### ISSUE THREAD

**Issue by davidegiannella** [testcontainers/testcontainers-java#2334]
I have the use case where I'd like to additionally check a `health` end point of my application that replies with a response body in a format as custom json.

In practice, at current state, my custom code would do something like
```
class MyWait extends HttpWaitStrategy {
...
   @Override
   protected void waitUntilReady() {
      if (super.waitUntilReady()) {
         // reopen connection, fetch body, check json and either return true/false
      }
   }
}
```

However by looking at the code we could add some "custom" additonal predicates around this area https://github.com/testcontainers/testcontainers-java/blob/7cb8ef5850533717b78d78381d40fd7af0b8bf1a/core/src/main/java/org/testcontainers/containers/wait/strategy/HttpWaitStrategy.java#L204-L206

and we could register those in a format something like lambda giving tha they will receive in the active connection. Something like the following when creating the container

```
.waitingFor((new HttpWaitStrategy())
   .forPort(8080)
   .forPath("/health")
   .forStatusCode(200)
   .withCustom(connection -> {
      // connection.getBody
      // do my assertions
      // either return true or false
   }
);
```

I'm not that familiar with the testcontainers-java codebase internals but as first thought it sounds reasonable approach to me.

If there's a generic agreement I could work out a PR if I have enough time.

**Comment by kirmandi** [comment]
if you want to check the response body, that is what the ResponsePredicate check is for:
```
.waitingFor((new HttpWaitStrategy())
   .forPort(8080)
   .forPath("/health")
   .forStatusCode(200)
   .forResponsePredicate(s -> s.contains("something")
);
```

**Comment by davidegiannella** [comment]
Awesome! thanks very much @kirmandi. I'll give it a try as soon as I can. I'll close this.
