### ISSUE TITLE
Unable to pass arguments to delegate PostgreSQL JDBC Driver

### ISSUE THREAD

**Issue by brunopalos** [testcontainers/testcontainers-java#2339]
Hi,

Due to `?loggerLevel=OFF` at the end of the constructed URL on PostgresSQL module, is not possible to pass arguments to the underlying driver, causing the connection to hang.

https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L62

When the URL is being constructed on the bellow line, the `queryString` already has a `?` with the query arguments.
https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java#L189

Example: `jdbc:postgresql://localhost:5432/my_database??loggerLevel=OFF?currentSchema=my_schema`.

Removing `?loggerLevel=OFF` doesn't seem to have any effect on the logs. If you agree, I'm happy to create a PR and remove the `loggerLevel` from the URL.

Thanks in advance,
Bruno

**Comment by marcelstoer** [comment]
Looks like this was fixed with #2049.
