### ISSUE TITLE
Allow for customization of the Kafka container image

### ISSUE THREAD

**Issue by gunnarmorling** [testcontainers/testcontainers-java#2340]
Hey, great work with Testcontainers! The Debezium community is currently working on Testcontainers [support for Debezium](https://github.com/debezium/debezium/pull/1209), aiming to simplify integration tests of CDC pipelines.

We're currently using the existing Kafka TC container; we'd like to be able to use our own Kafka image for that purpose.

**Comment by bsideup** [comment]
Thank you for the feedback!

Do you want to use a re-published Confluent Platform image or a custom Kafka one?
In our Kafka container we rely on some scripts from Confluent Platform (as the only semi-official source of Kafka Docker images, unfortunately), but we could also extract some common parts I guess.

**Comment by gunnarmorling** [comment]
> Do you want to use a re-published Confluent Platform image or a custom Kafka one?

We'd like to use the [Kafka image](https://hub.docker.com/r/debezium/kafka) built by the Debezium community. What are these scripts exactly about?

**Comment by bsideup** [comment]
See 
https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L108 

and
https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L145
