### ISSUE TITLE
OracleContainer allow custom password

### ISSUE THREAD

**Issue by KyleAure** [testcontainers/testcontainers-java#2356]
Currently the withPassword method on OracleContainer changes the field value but does not actually change the password on the container.

https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java#L87-L91

Given that we are supporting the Oracle XE container we should be able to update the password by providing an environment variable to the container in the form:
```
ORACLE_PWD="SecretPassword"
```

See Oracle container documentation here: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#running-oracle-database-18c-express-edition-in-a-docker-container

**Comment by kiview** [comment]
Hey @KyleAure,
thanks, good observation. What confuses me is the fact, that it was working before. The Oracle docs say about the password:
> (default: auto generated)

Since we were only exposing `oracle` as a password value before, can I assume that the behaviour of the Oracle image did change?

**Comment by KyleAure** [comment]
@kiview Everything does work as it is right now, and there hasn't been a behavior change on oracle's side.  Their default password is still the same (`oracle`)

The official docker documentation from oracle, and if your build your image from there, says you should be able to set a custom password during the container run phase using the environment variable I mentioned above.  Though, the "oracle images" floating out there have usually stripped out a bunch of features to make the container smaller. (I.E. oracleinanutshell and wnameless/oracle-xe-11g-r2).

So I guess we have two options:
1. add in the functionally to set a different password at container runtime and those developers who are using an unofficial oracle build will just need to stick to the default password.
2. have the withPassword method return an exception as it is not supported by ever docker image distribution. 

Thoughts?

**Comment by kiview** [comment]
Thanks for the clarification.
Since there is now an "official" way how to use Oracle in Docker (in the repository you linked), I think we should target to be compatible to this one and support it as best as possible.

This means I am in favour of 1.

WDYT @rnorth?

**Comment by KyleAure** [comment]
So I went ahead and did some more testing myself with this and here is another thing to consider.

There are two ways for users to build/run oracle database images per Oracle's instructions.  
1. Database is built at runtime
2. Database is pre-built (https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb)

I think for most of our users are going to choose the pre-built option, since having the database be built at runtime will take upwards of 4min per test suite.  
In that case, the simple environment variable solution above does not work.  Since the db is already built the startup script will skip the portion where it updates the password.

So maybe we leave things how they are?  If during the process of building an oracle image a user decides to change the system password, they can use the `withPassword` option in testcontainers to note the change and successfully connect.  

Otherwise, if a user wants to use the setPassword.sh script in the container at runtime they can still do so:
```java
    @BeforeClass
    public static void setUp() throws Exception {  
    	ExecResult result = oracle.execInContainer("/bin/sh", "-c", "/setPassword.sh " + DB_PASSWORD);
    	if(result.exitCode == 0) {
    		//Successful
    		oracle.withPassword(DB_PASSWORD);
    	} else {
    		//Likely using an unofficial container that does not have a setPassword script
    	}
    }
```
In which case perhaps some more detailed documentation is in order. 

Thoughts?

**Comment by KyleAure** [comment]
Closing issue.  This does not seem viable given that this will only work if the database is built during container startup.  Instead `withPassword()` method should be used if you built an official oracle image with a non-default password.
