### ISSUE TITLE
Docker Elasticsearch Loggers not having silenceable parent for logs

### ISSUE THREAD

**Issue by hamzayoucefkaced** [testcontainers/testcontainers-java#2368]
There are Loggers which names go by this format: docker[blacktop/elasticsearch:version] that are generated by DockerLoggerFactory. We sometimes don't want some of its logs, but it's difficult silencing them since the Loggers do not share a common parent which is silenceable (Logger parent is root) and we do not want to hardcode the Loggers for each Elasticsearch version to silence. It would be great if the Loggers parent was org.testcontainers for example so that it is easily accessible instead of having only root as a parent.

**Comment by davido** [comment]
The problem is here: https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L594-L601

```java
/**
     * Provide a logger that references the docker image name.
     *
     * @return a logger that references the docker image name
     */
    protected Logger logger() {
        return DockerLoggerFactory.getLogger(this.getDockerImageName());
    }
```

If we support dozen of different ES versions:

```java
  private static String getImageName(ElasticVersion version) {
    switch (version) {
      case V5_6:
        return "blacktop/elasticsearch:5.6.16";
      case V6_2:
        return "blacktop/elasticsearch:6.2.4";
      case V6_3:
        return "blacktop/elasticsearch:6.3.2";
      case V6_4:
        return "blacktop/elasticsearch:6.4.3";
      case V6_5:
        return "blacktop/elasticsearch:6.5.4";
      case V6_6:
        return "blacktop/elasticsearch:6.6.2";
      case V6_7:
        return "blacktop/elasticsearch:6.7.2";
      case V6_8:
        return "blacktop/elasticsearch:6.8.6";
      case V7_0:
        return "blacktop/elasticsearch:7.0.1";
      case V7_1:
        return "blacktop/elasticsearch:7.1.1";
      case V7_2:
        return "blacktop/elasticsearch:7.2.1";
      case V7_3:
        return "blacktop/elasticsearch:7.3.2";
      case V7_4:
        return "blacktop/elasticsearch:7.4.2";
      case V7_5:
        return "blacktop/elasticsearch:7.5.2";
      case V7_6:
        return "blacktop/elasticsearch:7.6.0";
    }
    throw new IllegalStateException("No tests for version: " + version.name());
  }
```

and would like to suppress all Testcontainers specific logging output, we would have to add something like this:

```java
    .put("🐳 [blacktop/elasticsearch:5.6.16]", Level.WARN)
    .put("🐳 [blacktop/elasticsearch:6.8.6]", Level.WARN)
    .put("🐳 [blacktop/elasticsearch:7.6.0]", Level.WARN)
    .put("docker[blacktop/elasticsearch:5.6.16]", Level.WARN)
    .put("docker[blacktop/elasticsearch:6.8.6]", Level.WARN)
    .put("docker[blacktop/elasticsearch:7.6.0]", Level.WARN)
[...]
```

This raises the question how could this be changed, so that it would be simpler to maintain, if ES docker versions are upgraded, without touching the logging configuration.

**Comment by bsideup** [comment]
`logger()` is protected, you can override it and return something like `LoggerFactory.getLogger("🐳 elasticsearch")`
