### ISSUE TITLE
database data mock 

### ISSUE THREAD

**Issue by fitmate-app** [testcontainers/testcontainers-java#2374]
Are there any plans to add a sort of  "mock data" feature to database containers, just like what you've already done with the Mockserver Module.
Thank you!

**Comment by rnorth** [comment]
We have ways to run an SQL script from a file: https://www.testcontainers.org/modules/databases/#using-a-classpath-init-script

Plus, you are free to use your own code to insert data into the DB after your container starts, and before your test runs.

People use various approaches, but personally I tend to use Testcontainers to create the containers, and Flyway to apply schemas and load test data.
