### ISSUE TITLE
Problematic use of generic types

### ISSUE THREAD

**Issue by ldcasillas-progreso** [testcontainers/testcontainers-java#238]
Using TestContainers 1.1.6, the following code produces a compile time error:

``` java
private static final PostgreSQLContainer postgres =
        new PostgreSQLContainer("postgres:9.5.4")
                .withDatabaseName("test")
                .withEnv("PGDATA", CONTAINER_PGDATA)
                .withFileSystemBind(HOST_PGDATA.toString(), CONTAINER_PGDATA, BindMode.READ_WRITE);
```

Compilation error:

```
/Users/my-user-name/my-project/my/path/to/IntegrationTest.java:71: error: incompatible types: GenericContainer cannot be converted to PostgreSQLContainer
                    .withFileSystemBind(HOST_PGDATA.toString(), CONTAINER_PGDATA, BindMode.READ_WRITE)
```

The problem stems from the fact that the `PostgreSQLContainer` class starts like this, with a recursive bound on its generic type parameter (_à la_ `class Enum<E extends Enum<E>>`):

``` java
public class PostgreSQLContainer<SELF extends PostgreSQLContainer<SELF>> 
        extends JdbcDatabaseContainer<SELF>
```

So this is a generic class, but the documentation and [example test case](https://github.com/testcontainers/testcontainers-java/blob/master/modules/postgresql/src/test/java/org/testcontainers/junit/SimplePostgreSQLTest.java) use it with no type parameter, as a raw type:

``` java
@Rule
public PostgreSQLContainer postgres = new PostgreSQLContainer();
```

And in this situation Java can't figure out that in my use of the `withFileSytemBind()` method, the `SELF` return type unifies with `PostgreSQLContainer`.

My workaround for this issue illustrates the fix:

``` java
// A dummy class whose sole purpose is to instantiate the `SELF`
// type parameter.
private static final class MyPostgreSQLContainer extends PostgreSQLContainer<MyPostgreSQLContainer> {
    public MyPostgreSQLContainer(String dockerImageName) {
        super(dockerImageName);
    }
}

private static final MyPostgreSQLContainer postgres =
        new MyPostgreSQLContainer("postgres:9.5.4")
                .withDatabaseName("test")
                .withEnv("PGDATA", CONTAINER_PGDATA)
                .withFileSystemBind(HOST_PGDATA.toString(), CONTAINER_PGDATA, BindMode.READ_WRITE);
```

This argues that the existing "end user facing" classes like `PostgreSQLContainer` in the library ought to be split into two classes:

``` java
public abstract class AbstractPostgreSQLContainer<SELF extends AbstractPostgreSQLContainer<SELF>> 
        extends JdbcDatabaseContainer<SELF> {
    ...
}

public class PostgreSQLContainer extends AbstractPostgreSQLContainer<PostgreSQLContainer> {
    ...
}
```

People who want to extend `PostgreSQLContainer` should be discouraged from doing so as well, and pointed to `AbstractPostgreSQLContainer` as the proper class for extension.  (Making `PostgreSQLContainer` a final class is one alternative here, but with the downside that it's a backwards-incompatible change.)

**Comment by bsideup** [comment]
@ldcasillas-progreso thanks for the report! 

As a temporary workaround, I can suggest this:

```java
private static final PostgreSQLContainer postgres =
   new PostgreSQLContainer<>("postgres:9.5.4")
    .withDatabaseName("test")
    .withEnv("PGDATA", CONTAINER_PGDATA)
    .withFileSystemBind(HOST_PGDATA.toString(), CONTAINER_PGDATA, BindMode.READ_WRITE);
```

(note the diamond operator)

**Comment by ldcasillas-progreso** [comment]
@bsideup Ah, good one!

**Comment by rnorth** [comment]
@ldcasillas-progreso yes, I can see how this would be annoying, and we're keen to come up with a more user-friendly model (which will probably be a breaking change and the focus of a future 2.0.0 release). 

In the meantime @bsideup's workaround is the right way, and I'd like to think about your suggested fix too. It looks pretty sensible to me. It might be a good solution for users on the 1.x.x series and something we can integrate reasonably soon.

**Comment by mpecan** [comment]
This issue also makes it very hard to use Testcontainers in Kotlin (and still exists in the current 1.2.1 version).

Is there any progress on this? Can I help out with a PR?

**Comment by bsideup** [comment]
Hi @mpecan,

If you have an idea how to solve self-referencing without breaking current behavior it would be great!

You can also submit a bug to Kotlin... Well... Because it's a bug in Kotlin and a valid JVM bytecode :D

**Comment by martin-g** [comment]
The solution I've shared at https://github.com/testcontainers/testcontainers-java/issues/318#issuecomment-290692749 works without any issues for me.

**Comment by mpecan** [comment]
@martin-g Agreed. And I can see why.

@bsideup I will give it a stab in the next couple of days.

**Comment by martinandersson** [comment]
Reopen please. Should be an absolute top priority if you ask me.

**Comment by missingfaktor** [comment]
Could you please reopen this issue? I'm trying to use this library in Scala, and with the way generics are currently used here, it's really difficult. I'm happy to help out with PRs.

**Comment by mikelhamer** [comment]
Is this "2.0" I see mentioned in this issue and other related issues about generic types actually happening? Even though it seems like a minor thing, I can't stand the thought of using something where I had to tell the IDE to suppress warnings for constantly

**Comment by bsideup** [comment]
We're experimenting with a new "container definitions API" that will be an experimental alternative API in 1.x and get promoted as the main one in 2.0 if the feedback is good.

You can preview it here:
https://github.com/testcontainers/testcontainers-java/pull/4465

**Comment by mikelhamer** [comment]
Thank you I love you and I love this project. Keep up the good work everyone! Really awesome tool youve built here.
