### ISSUE TITLE
Unable to pass JDBC URL query parameters for PostgreSQLContainer

### ISSUE THREAD

**Issue by Fotonix** [testcontainers/testcontainers-java#2389]
When you are trying to define a JDBC URL with query parameters the final URL becomes invalid
E.g., the following URL
*jdbc:tc:postgresql:9.5://localhost/db?stringtype=unspecified*
will become 
*jdbc:postgresql://localhost:32953/db?loggerLevel=OFF?stringtype=unspecified*
This happens because *PostgreSQLContainer#getJdbcUrl* method has hardcoded *?loggerLevel=OFF* query parameter but *JdbcDatabaseContainer#constructUrlForConnection* uses a simple URL and Query concatenation to create a final URL (*getJdbcUrl() + queryString*)

**Comment by bsideup** [comment]
Duplicate of #1976
