### ISSUE TITLE
Cannot recognise ImageFromDockerfile class

### ISSUE THREAD

**Issue by daggerok** [testcontainers/testcontainers-java#2403]
Hello

* I'm using testcontainers 1.12.5 (and also tried 1.13.0):
   ```xml
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>selenium</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
   ```
* I'm using this documentation: https://www.testcontainers.org/features/creating_images/
* Target `ImageFromDockerfile` class doesn't available for use:
   ![image](https://user-images.githubusercontent.com/2445604/76012754-80ef1b00-5f1f-11ea-9dea-6512670af38c.png)
* It's strange, because I clearly see that file is in a repo [here](https://github.com/testcontainers/testcontainers-java/blob/1.12.5/core/src/main/java/org/testcontainers/images/builder/ImageFromDockerfile.java)
* available implementation of image to pass in GenericContainer constructor is only `RemoteDockerImage`:
   ![image](https://user-images.githubusercontent.com/2445604/76014765-d547ca00-5f22-11ea-8a98-679392529423.png)

I didn't found anything in release notes. Last mentioned release: 1.12.0:
![image](https://user-images.githubusercontent.com/2445604/76015036-45565000-5f23-11ea-9808-fc4e4a9939d7.png)

Where is `ImageFromDockerfile`? I want to reuse existing Dockerfile in tests, please help me if you 
know what I'm doung wrong...

Thanks

**Updates:**

Maybe my Idea is getting crazy.... I have remover ~/.m2/repository folder, rebuild and this is what I now can see:
![image](https://user-images.githubusercontent.com/2445604/76016292-3d97ab00-5f25-11ea-9c61-3158a1bdcb36.png)

Please, let me know which minimal java version is required?
Thanks

**Update 2:**

Don't know why IDEA cannot recognise this class (see line 21), but I have implemented custom container without intellisense and code completion ...and seems like tests are working as expected:
![image](https://user-images.githubusercontent.com/2445604/76021246-9d924f80-5f2d-11ea-8170-b220da7bb226.png)

hm... anyway, please, let me know If someone faced with similar problem. Thanks

PS: I have prepared repository with code examples [here](https://github.com/daggerok/testcontainers-examples/blob/2bc665a44140741a5ab9f06648642dc714a61f2e/jboss-testcontainers-selenide-dockerfile-e2e-tests/src/test/java/daggerok/jboss/JBossEapContainer.java#L21). Feel free to try clone and import in your idea...

---
Regards,
Max

**Comment by daggerok** [comment]
Created issue https://youtrack.jetbrains.com/issue/IDEA-234674

**Comment by bsideup** [comment]
Closing as it seems to be an issue in IDEA, not us :)
