### ISSUE TITLE
On Jenkins test container throws network bridge not found

### ISSUE THREAD

**Issue by dheerajjoshim** [testcontainers/testcontainers-java#2428]
I am using MariaDB test container for integration testing. And everything works fine in development setups.

In our organisation Jenkins test container is not starting and it throws following error

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@331e1fb8[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"network bridge not found"}
```
I am trying to create a new network with bridge network mode.

```
@ClassRule
 public static final MariaDBContainer<?> mariadbSQLContainer = new MariaDBContainer<>()
                    .withNetworkMode("bridge")
                    .withNetwork(network)
                    .withDatabaseName("integration-tests-db")
                    .withUsername("sa")
                    .withPassword("sa");
```
Does this error mean the Docker network modes?

**Comment by bsideup** [comment]
@dheerajjoshim you should use either `withNetworkMode` or `withNetwork`, not both.

**Comment by dheerajjoshim** [comment]
I tried just `withNetwork` and it didn't work. So used `withNetworkMode`. Let me try now `withNetworkMode` alone and report

**Comment by bsideup** [comment]
Also, please post `docker network ls` from your Jenkins environment, perhaps you don't have bridge network on Jenkins at all

**Comment by dheerajjoshim** [comment]
I tried `withNetworkMode("bridge")` and it is not working.
I do not have access to Jenkins build farm(Just as in any other organisation :D ). Will ask our DevOps and get back to you.

**Comment by bsideup** [comment]
@dheerajjoshim may I also ask why you need to force the network to be the one named "bridge"? What are you trying to achieve?

**Comment by dheerajjoshim** [comment]
Without any network configurations too i get the same error

My initial commit to CI has just following

```
@ClassRule
public static final MariaDBContainer<?> mariadbSQLContainer = new MariaDBContainer<>()
                    .withDatabaseName("integration-tests-db")
                    .withUsername("sa")
                    .withPassword("sa");
```
It throwed

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@331e1fb8[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"network bridge not found"}
```

So i began wondering if it is docker network related issue in our build farm.

**Comment by bsideup** [comment]
@dheerajjoshim ah, okay. Is it Testcontainers 1.12.5 or higher? If so, can you try 1.12.4?

**Comment by dheerajjoshim** [comment]
I am using `1.13.0`. Latest i believe.
Ok. Let me downgrade it to  `1.12.4` version

**Comment by dheerajjoshim** [comment]
@bsideup  Well. With `1.12.4` I get this error.

`java.lang.IllegalArgumentException: Requested port (3306) is not mapped`

I did try `withMappedPort(3306)`

**Comment by bsideup** [comment]
@dheerajjoshim there is no `withMappedPort`, only `withExposedPort`. Are you talking about `withExposedPort`?

**Comment by bsideup** [comment]
Anyways, if downgrading to `1.12.4` works, then you're hitting https://github.com/testcontainers/testcontainers-java/issues/2239 and it will be fixed soon. I will close this issue as a duplicate.
