### ISSUE TITLE
ImageFromDockerfile not working when FROM references image in private registry

### ISSUE THREAD

**Issue by JakobFels** [testcontainers/testcontainers-java#2430]
I'm using TC to test an image that is built by TC via ImageFromDockerfile.
I recently refactored my Dockerfile to be built on top of a custom Image to speed up my tests. 
This image is stored in a private registry. At first I thought everything was fine, but after I ran docker prune my Tests started failing locally.

```
[main] INFO org.testcontainers.images.builder.ImageFromDockerfile - Transferred 0 bytes to Docker daemon
[tc-okhttp-stream-1989332276] ERROR docker[my-image] - Get https://registry.private.com/v2/base/image/manifests/latest: denied: access forbidden
```
Credentials are stored via credstore 'osxkeychain'.

Using the docker client TC uses directly yields the same result:
```java
Logger logger = DockerLoggerFactory.getLogger("test");
BuildImageResultCallback resultCallback = new BuildImageResultCallback() {
    @Override
    public void onNext(BuildResponseItem item) {
        super.onNext(item);
	if (item.isErrorIndicated()) {
	    logger.error(item.getErrorDetail().getMessage());
	} else {
	    logger.debug(StringUtils.chomp(item.getStream(), "\n"));
	}
    }
};
DockerClient instance = DockerClientFactory.lazyClient();
String s = instance.buildImageCmd(new File(".")) //Dockerfile lies here.   
    .exec(resultCallback)
    .awaitImageId();
```

While using the client to pull the image directly works fine:
```java
Logger logger = DockerLoggerFactory.getLogger("test");
DockerClient instance = DockerClientFactory.lazyClient();
instance
    .pullImageCmd("registry.private.com/base/image")
    .exec(new TimeLimitedLoggedPullImageResultCallback(logger))
    .awaitCompletion();
```

My current workaround would be to add a dummy container with the base image and 'link' it via dependsOn

```java
@Container
protected static final GenericContainer BASE_CONTAINER = new GenericContainer("registry.private.com/base/image");
@Container
protected static final MyTestContainer TEST_CONTAINER = new MyTestContainer().dependsOn(BASE_CONTAINER);
```

**Comment by bsideup** [comment]
@rnorth you may know something about it :)

**Comment by JakobFels** [comment]
After doing some digging, the root cause seems to be directly in docker-java in combination with using a credential helper.

I'm using Mac OSX with the `osxkeychain` credStore. Unlike PullImageCmd, BuildImageCmd will not determine any effective auth configs, only supplying the empty placeholder auth from local dockerConfig.

Removing the credential helper and directly storing auth in dockerConfig will successfully build my image.

I guess I should re-file this with docker-java then?

**Comment by JakobFels** [comment]
Seeing the release notes for 1.14.0 I realised that my issue is actually fixed as well (several items pointing to authenticated pulls with docker-compose/build)

so this was actually a duplicated of one of those issues, sorry

**Comment by bsideup** [comment]
@JakobFels yes, @rnorth added authenticated pre-pulls for Compose & `ImageFromDockerfile`, which also fixed your issue I suppose :) Thanks for reporting!
