### ISSUE TITLE
Daemon container incorrectly stopped

### ISSUE THREAD

**Issue by sergey-morenets** [testcontainers/testcontainers-java#2433]
Hi

We started using Testcontainers in our project and we're interested in daemon mode. So that MySQL container doesn't stop after all the tests (JUnit 5) have passed.

We created new settings for the database connection in our tests:

db.url=jdbc:tc:mysql:8:///test?TC_DAEMON=true
db.driver=org.testcontainers.jdbc.ContainerDatabaseDriver

Testcontainers work fine but MySQL container was stopped and removed after all the tests finished. Debugging showed that it wasn't stopped from the library code. So it was probably killed by resource reaper.

Testcontainers version: 1.13.0

Thanks

**Comment by bsideup** [comment]
Daemon mode preserves it between tests in the same JVM. If you want to reuse containers between test sessions, see #1781 :)

**Comment by sergey-morenets** [comment]
@bsideup Thank you. Reusable containers is great feature.
But if we reuse the same MySQL container the database will share the same test data for all test sessions. And our tests will fail because they expect empty database.
What we need here is to clean database in the beginning of any tests session. Is there any possibility to do that with TestContainers?

**Comment by bsideup** [comment]
@sergey-morenets you don't need Testcontainers support for it, you can always clean the database state yourself with `TRUNCATE TABLE` or similar, can't you?

**Comment by bsideup** [comment]
There is also `containerIsStarted` hook that you can override and perform the cleanup in it

**Comment by sergey-morenets** [comment]
@bsideup Yes, we already use TC_INITSCRIPT parameter: `db.url=jdbc:tc:mysql:8:///test?TC_DAEMON=true&TC_REUSABLE=true&TC_INITSCRIPT=testcontainers/init.sql `

And ideal option is to have init.sql like this:
`DROP DATABASE test;`

However it's not possible because this script is executed against database connection to the same test database. So we have to insert multiple SQL statements which is not very scalable:

`DROP TABLE IF EXISTS Account;`

We can't use TRUNCATE TABLE because the first time we run tests the tables don't exist and TRUNCATE statement doesn't support IF EXISTS syntax.
