### ISSUE TITLE
Can't resolve localhost in selenium on linux

### ISSUE THREAD

**Issue by slabiak** [testcontainers/testcontainers-java#2434]
Hi,
I have very simple test in sprinng boot 2.2.5 with testcontainers 1.13.0 and selenium 3.141.59. 
It looks like this:

    @RunWith(SpringRunner.class)
    @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
    @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
    @ActiveProfiles("integration-test")
    public class LoginPageIT {

    @LocalServerPort
    private int port;

    @Rule
    public BrowserWebDriverContainer chrome = new BrowserWebDriverContainer()
            .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL, new File("./target/"))
            .withCapabilities(new ChromeOptions());

    @Test
    public void shouldShowLoginPageAndSuccessfullyLoginToAdminAccountUsingAdminCredentials() {
        RemoteWebDriver driver = chrome.getWebDriver();
        String url = "http://host.docker.internal:" + port + "/";

        driver.get(url);

        WebElement elementById = driver.findElementById("login-form");
        assertNotNull(elementById);
    }
}

On windows 10 it works as expected but on linux (ubuntu 18.0.4) it doesn't work. When I look at video for failed test I see that it's trying to reach this url "data:,". Is that a known issue?

**Comment by bsideup** [comment]
`host.docker.internal` is not cross platform. Consider using https://www.testcontainers.org/features/networking/#exposing-host-ports-to-the-container 

You will find an example here:
https://github.com/testcontainers/testcontainers-java/blob/3f9216ebda2087b3311de979a96918e3ccaefc2d/examples/selenium-container/src/test/java/SeleniumContainerTest.java#L31
