### ISSUE TITLE
Support for withVolumesFrom from dockerjava

### ISSUE THREAD

**Issue by peterbollen** [testcontainers/testcontainers-java#244]
Hi,

is mounting volumes from another (data) container is supported?

Dockerjava supports this by using _withVolumesFrom_.

Regards,
Peter

**Comment by peterbollen** [comment]
I've added it on a local branch.

I'll create a PR for this.

Thanks,
Peter

**Comment by rnorth** [comment]
Peter
Thanks, that's not currently supported, so the PR would be good. Thank you!
Richard

**Comment by bsideup** [comment]
Hey @peterbollen, 

any luck?

**Comment by peterbollen** [comment]
@bsideup Lost track of this. I'll create the PR in a bit.

**Comment by bsideup** [comment]
Fixed in #289
