### ISSUE TITLE
Support Couchbase Java SDK 3

### ISSUE THREAD

**Issue by daschl** [testcontainers/testcontainers-java#2447]
Hi,

I've been chatting a bit with @bsideup, but I wanted to open an actual issue about it so we can track it. Currently the couchbase container only supports SDK 2, because 2 and 3 on the same classpath do not work. I'm working on a version that does not need the SDK at all to perform its work so ideally it can support both versions at the same time. Since there are dependencies on other projects they can link to this issue if needed.

I'm going to open a PR once the work is ready to review.

**Comment by unhuman** [comment]
I was just looking for this!  Excited that this will go in.

**Comment by rnorth** [comment]
This was released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0 🎉

Thanks for the contribution!

**Comment by johnspade** [comment]
Have SDK 2/3 incompatibility issues been resolved?

**Comment by bsideup** [comment]
@johnspade yes. The module is SDK-free now thanks to @daschl :)
