### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by diwu01** [testcontainers/testcontainers-java#2458]
I found a translation problem with version 12

**Comment by bsideup** [comment]
@diwu01 please provide more information (and links, if possible)

**Comment by diwu01** [comment]
the error code file : addons\web\i18n\zh_CN.po
error code : #. module: web
          #. openerp-web
         #: code:addons/web/static/src/js/core/misc.js:17
         #, python-format
        msgid """You may not believe it,<br />but the application is actually loading..."
        msgstr "请内心等待，<br />应用仍在加载..."
right code:

msgstr “”请耐心等待，<br />应用仍在加载...“”

**Comment by bsideup** [comment]
This does not seem to be Testcontainers related at all.
