### ISSUE TITLE
Make `CassandraContainer` extend `FixedHostPortGenericContainer` to allow fixed mapping of ports

### ISSUE THREAD

**Issue by tomekl007** [testcontainers/testcontainers-java#2468]
Currently, the `CassandraContainer` is extending `GenericContainer`.
When you are creating a new container, the internal Cassandra port Is mapped to a random port exposed on the localhost. 
To retrieve the port, one should do:
```
int CASSANDRA_INTERNAL_PORT = 9042;
cassandraContainer.getMappedPort(CASSANDRA_INTERNAL_PORT));
```
If the `CassandraContainer` will extend `FixedHostPortGenericContainer` it could use `.withFixedExposedPort` method. Is such a case, one could create a container in the following way:
```
new FixedHostPortGenericContainer<>(CASSANDRA_311)
                .withFixedExposedPort(CASSANDRA_INTERNAL_PORT, CASSANDRA_INTERNAL_PORT);
```
(it can be abstracted away behind existing `CassandraContainer()` constructor). 
This is a goal of this ticket.

The biggest benefit of it is, that it simplifies the configuration mechanism for frameworks in tests.

For example in spring framework, the `application-integration.configuration` can have setting:
`contact-points: 127.0.0.1:9042`
instead of retrieving dynamically assigned port and set it dynamically or via the system property:
```
String randomPort = Integer.toString(cassandraContainer.getMappedPort(CASSANDRA_INTERNAL_PORT));
System.setProperty("cassandra_docker_port", randomPort);
```
and then in `application-integration.properties`:
```
contact-points: 127.0.0.1:${cassandra_docker_port}
```

For other frameworks (i.e. quarkus) it may be even harder because the lifecycle of configuration mechanism is different.

**Comment by bsideup** [comment]
No, sorry, we have no plans to make it easier to use static ports.

You can read the following article to get more details:
https://bsideup.github.io/posts/testcontainers_fixed_ports/

You will find a plenty of good examples of using Testcontainers with Spring Boot, including some provided in our examples folder:
https://github.com/testcontainers/testcontainers-java/tree/master/examples

Quarkus and others work well too. Have a look at their `QuarkusTestResourceLifecycleManager`, here is an example:
https://github.com/cescoffier/quarkus-todo-app/blob/master/src/test/java/io/quarkus/sample/DatabaseResource.java

**Comment by bsideup** [comment]
Also note that not only port, but host *must* also be taken into consideration. It is not always `localhost` (see the article)

**Comment by tomekl007** [comment]
Ok, it seems reasonable. Thank You for the explanation @bsideup
