### ISSUE TITLE
Including Service.KMS

### ISSUE THREAD

**Issue by bskinny** [testcontainers/testcontainers-java#2506]
Hello,

Is it possible to get Service.KMS("kms", 4599) exposed in LocalStackContainer? 

Thanks,
Brian

**Comment by rnorth** [comment]
@bskinny sorry for letting this get stale. This was added in #2812, which we should be releasing very soon.

**Comment by bskinny** [comment]
Excellent. Thanks @rnorth

**Comment by rnorth** [comment]
#2812 was merged, so I'll close the ticket. We're looking to release this weekend.
