### ISSUE TITLE
Container is not reused because the hash mismatched

### ISSUE THREAD

**Issue by deen13** [testcontainers/testcontainers-java#2515]
I'm currently optimizing our end-to-end tests and trying to reuse one of our containers but it isn't reused because the createCommand-hash mismatches. 

### Test Setup
```kotlin
@Testcontainers
abstract class InfrastructureBase {

    private val logger = LoggerFactory.getLogger(this::class.java)
    private val logConsumer = Slf4jLogConsumer(logger)

    @Container
    private val vernemq = KGenericContainer("vernemq/vernemq")
        .withCopyFileToContainer(MountableFile.forClasspathResource("vmq.passwd"), "/etc/vernemq/vmq.passwd")
        .withEnv("DOCKER_VERNEMQ_ACCEPT_EULA", "yes")
        .withNetworkAliases("vernemq")
        .waitingFor(Wait.forLogMessage(".*cluster event handler 'vmq_cluster' registered.*", 1)) // this is way faster than the basic health check
        .withExposedPorts(1883)
        .withNetwork(Network.SHARED)
        .withLogConsumer(logConsumer)
        .withReuse(true)
}
```

### Point of Failure

The container reusage fails because `findContainerForReuse(hash)` returns null.
#### Comparison
```kotlin
String hash = hash(createCommand);

containerId = findContainerForReuse(hash).orElse(null);

if (containerId != null) {
    logger().info("Reusing container with ID: {} and hash: {}", containerId, hash);
    reused = true;
} else {
    logger().debug("Can't find a reusable running container with hash: {}", hash);
    createCommand.getLabels().put(HASH_LABEL, hash);
}
```

#### Hash Generation

The hash mismatches because the `aliases`-Array contains a value like `tc-G2Lbgs6Y` (which is different for each test) besides my own alias `vernemq`.

```kotlin
if (network != null) {
    createCommand.withNetworkMode(network.getId());
    createCommand.withAliases(this.networkAliases);
} else if (networkMode != null) {
    createCommand.withNetworkMode(networkMode);
}
```

**Comment by bsideup** [comment]
Yes, that's a known limitation - reusable containers cannot be used with networks (their ids are random, too).

Note that reusable mode is an experimental feature in preview. Once it reaches the stable state, it will provide support for connecting reusable containers with networks.

**Comment by Ant-avnk** [comment]
I have a similar problem with hash mismatch, but it is caused by a different order in hostConfig.portBindings.ports in the createCommand object, which were created from one block of code.
Is it correct behavior?
```
        dse = new FixedHostPortGenericContainer("datastax/dse-server:6.0.8")
            .withFixedExposedPort(9142, 9042)
            .withFixedExposedPort(7299, 7199)
            .waitingFor(Wait.forLogMessage(".*DSE startup complete.*\\n", 1)
                .withStartupTimeout(Duration.ofSeconds(120L)))
            .withNetworkAliases("dse-testcontainer")
            .withEnv("DS_LICENSE", "accept")
            .withEnv("JVM_EXTRA_OPTS", "-Dcassandra.jmx.remote.port=7199 "
                + "-Dcom.sun.management.jmxremote.authenticate=false "
                + "-Dcom.sun.management.jmxremote.rmi.port=7199 "
                + "-Djava.rmi.server.hostname=localhost");
```
```
 ... "portBindings": {
    "7199/tcp": [
      {
        "HostIp": "",
        "HostPort": "7299"
      }
    ],
    "9042/tcp": [
      {
        "HostIp": "",
        "HostPort": "9142"
      }
    ]
  }...
```
```
    ..."PortBindings": {
      "9042/tcp": [
        {
          "HostIp": "",
          "HostPort": "9142"
        }
      ],
      "7199/tcp": [
        {
          "HostIp": "",
          "HostPort": "7299"
        }
      ]
    }...
```

**Comment by bsideup** [comment]
@Ant-avnk there are many reasons why `FixedHostPortGenericContainer` is bad and this one can be one of them :)

**Comment by s-kramer** [comment]
@bsideup 
> Note that reusable mode is an experimental feature in preview. Once it reaches the stable state, it will provide support for connecting reusable containers with networks.

When will reusable mode be considered stable? Network support can be hacked, but container hash depends also on `authConfig.password` part of the docker command, and when using docker `credHelpers` you can get different  different passwords for the same container, which prevents reuse

**Comment by bsideup** [comment]
> container hash depends also on `authConfig.password` part of the docker command

This is super weird - are you sure? `authConfig.password` should only be involved in image pulls, container creation flow doesn't even access it

**Comment by s-kramer** [comment]
I'm basing this on checking the docket command just before the hash is calculated (`org.testcontainers.containers.GenericContainer#hash`). I've run the following command and observed that only the `authConfig.password` part was changed in the command between some of the runs
```
System.err.println("docker command: " + ((DefaultDockerClientConfig) dockerClientConfig).getObjectMapper().copy().enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY).enable(     SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS).writeValueAsString(createCommand));
```
I'm using `testcontainers-postgresql 1.16.2`. I'm running docker images authorized using `gcloud auth configure-docker` which renders `.docker/config.json` with `credHelpers` set to `gcloud` for all URLs.

**Comment by bsideup** [comment]
@s-kramer ooooh, I see now. Actually, I think there is a bug in docker-java - `authConfig` should not end up in generated JSON for `CreateContainerCmd`. Could you please report it?
https://github.com/docker-java/docker-java
