### ISSUE TITLE
Outdated MockServer version

### ISSUE THREAD

**Issue by gabrielkirsten** [testcontainers/testcontainers-java#2523]
I'm trying to use testcontainers to create a MockServer docker instance, but when I use mockserver-junit-jupiter module at version 5.10.0 I realize that this version is outdated (v5.4.0) and the with a simple test: 

```kotlin 
@Test
fun mockContainer() {
	MockServerClient(mockServer.containerIpAddress, mockServer.serverPort)
		.`when`(HttpRequest.request()
			.withPath("/person")
			.withQueryStringParameter("name", "peter"))
		.respond(HttpResponse.response()
			.withBody("Peter the person!"))
}
```

I received the error: 
```
java.lang.IllegalArgumentException: 1 error:
 - object instance has properties which are not allowed by the schema: ["id","priority"]

	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:192)
	at org.mockserver.client.MockServerClient.upsert(MockServerClient.java:844)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:49)
	at ...
```
I created [this issue](https://github.com/mock-server/mockserver/issues/755) on MockServer but I realize that the problem on testcontainers.

**Comment by gabrielkirsten** [comment]
I created this [PR](https://github.com/testcontainers/testcontainers-java/pull/2524) to solve this issue

**Comment by JakobFels** [comment]
You can pass in the required version when creating the mockserver container ie 
```
new MockServer("5.10.0");
```

**Comment by gabrielkirsten** [comment]
@JakobFels, unfortunately, I can't. the current docker hub repository is no longer maintained and the most recent version is 5.7.2 (17 Nov 2019). https://hub.docker.com/r/jamesdbloom/mockserver/

**Comment by bsideup** [comment]
That's not very true:
https://hub.docker.com/r/jamesdbloom/mockserver/tags

**Comment by gabrielkirsten** [comment]
I'm sorry, I checked again and realize that the @JakobFels tip worked. Just the docker hub documentation is outdated.
