### ISSUE TITLE
PostgreSQL versions

### ISSUE THREAD

**Issue by dabraham02124** [testcontainers/testcontainers-java#2536]
First off, I apologize if this is the wrong place for this, but I couldn't find anywhere that looked more correct.  If there is one, please point me at it, and I'll use it.

Is there a way to get a testcontainer with a more current version of PostgreSQL than `PostgreSQL 9.6.12 on x86_64-pc-linux-gnu (Debian 9.6.12-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`.  Perhaps "current" is the wrong word, "higher initial version number"?  Like 11.X, 12.Y, or 13.Z?

In addition is there any documented mapping from org.testcontainers.postgresql versions to postgresql versions?  I couldn't find a map, then I assumed that 1.13.0 was a container of pre-alpha PostgreSQL 13, but I was wrong...

Thank you very much.

**Comment by artjomka** [comment]
Module version have nothing to do with PostgreSQL version, you can specify version of container while creating container
` new PostgreSQLContainer("postgres:9.6-alpine")`

**Comment by bsideup** [comment]
Hi @dabraham02124,

We use PostgreSQL's official Docker images, you will find all requires info about them here:
https://hub.docker.com/_/postgres

> then I assumed that 1.13.0 was a container of pre-alpha PostgreSQL 13

FYI Testcontainers' version is independent from PostgreSQL's.

**Comment by dabraham02124** [comment]
@artjomka  & @bsideup thank you to both of you.

Would it be appropriate if I submitted a PR with javadoc on the PostgreSQLContainer describing this?
