### ISSUE TITLE
Toxiproxy with getSSHdImage not working

### ISSUE THREAD

**Issue by ebramirez** [testcontainers/testcontainers-java#2538]
I'm using `TestcontainersConfiguration.getInstance().getSSHdImage()` to create a container to ssh into, and wanted to try to cut the connection after the initial handshake with `proxy.setConnectionCut( true );`.

If I use the same port for the proxy and the container, the connection fails even before the `setConnectionCut()`.
If I use a different port, the connection cut has no effect.

I've created a reproducer here: https://github.com/ebramirez/toxicontainers

**Comment by bsideup** [comment]
@ebramirez 

I think this line is the problem:
https://github.com/ebramirez/toxicontainers/blob/890e4c7903b85693a857ea7651e3a7925afd2c9c/src/test/java/com/github/reproducer/toxicontainer/ge/boundary/GuidedExerciseValidatorTest.java#L54

Please see the docs on how to use the Toxiproxy container:
https://www.testcontainers.org/modules/toxiproxy/

**Comment by bsideup** [comment]
And here too:
https://github.com/ebramirez/toxicontainers/blob/890e4c7903b85693a857ea7651e3a7925afd2c9c/src/test/java/com/github/reproducer/toxicontainer/ge/boundary/GuidedExerciseValidatorTest.java#L90

**Comment by ebramirez** [comment]
Hi @bsideup,

If you mean that the problem is the offset, I did try without it, as in this revision: https://github.com/ebramirez/toxicontainers/blob/282586f1c02b2b369fbf54b89ce06cc48f353174/src/test/java/com/github/reproducer/toxicontainer/ge/boundary/GuidedExerciseValidatorTest.java

If something else is the problem, I don't know what you mean.

Anyway, thanks for having a look at it.

**Comment by bsideup** [comment]
@ebramirez as per docs, you should use `getProxy`'s result to access the proxy.

But, instead, you're calling `getDockerSshClient`:
https://github.com/ebramirez/toxicontainers/blob/282586f1c02b2b369fbf54b89ce06cc48f353174/src/test/java/com/github/reproducer/toxicontainer/ge/boundary/GuidedExerciseValidatorTest.java#L56

which uses `getFirstMappedPort`:
https://github.com/ebramirez/toxicontainers/blob/282586f1c02b2b369fbf54b89ce06cc48f353174/src/test/java/com/github/reproducer/toxicontainer/ge/boundary/GuidedExerciseValidatorTest.java#L91

But the first mapped port of Toxiproxy is Toxiproxy's API endpoint.

See "Obtaining proxied host and port" in the docs.

**Comment by ebramirez** [comment]
As usual, you where right, I skimmed over that docs to fast.

Thanks!

**Comment by bsideup** [comment]
@ebramirez I am glad that it works now 🎉
