### ISSUE TITLE
Can not set custom container name

### ISSUE THREAD

**Issue by pavelpp** [testcontainers/testcontainers-java#254]
Tried to set container name via .setContainerName(), however upon start container still has some random name assigned to it automatically. Did anyone test this? Works from command line with `docker run -d --name bla my/image`

**Comment by pavelpp** [comment]
Managed to rename container after it got started with this snippet:

` DockerClientFactory.instance().client().renameContainerCmd(oldName).withName(newName).exec();`

**Comment by bsideup** [comment]
Where did you find `setContainerName`? :D it's not a part of TestContainers API, so I assume you were using, I don't know, docker-java directly?

**Comment by pavelpp** [comment]
maybe it got removed later? I can see it in 1.1.7  [http://share.pho.to/AahDI](url)

**Comment by rnorth** [comment]
Eugh: I bet this is Lombok exposing a setter for what was originally intended to be a read-only field :(
No wonder it doesn't work. 

We'll probably need to put `AccessLevel.NONE` on a couple of the internal fields like this one.

Also, we should probably think about explicitly letting people set the container name via a `withContainerName(...)` fluent setter. My main concern, though, would be the potential for name collisions. This might be something we want to steer ordinary users away from...

**Comment by pavelpp** [comment]
IMHO there is always a way to screw things up when configuring containers and hiding existing docker functionality isn't gonna make testcontainers more valuable. Also it would make sense adding container labelling.

**Comment by asafm** [comment]
I have to add that I find it very valuable to have the option to set the name using 'withContainerName' on `GenericContainer`. It seems to be a very small codebase addition to support it.

**Comment by HaVonTe1** [comment]
Any chance this will be implemented? I have a very frustrating Jenkins Setup here on my hands. The StartUp checks (Wait.forHostPort()) doesnt work because the mapped port of the fresh started container is not reachable. The only think that would work is an access to $containerName:$internalPort. But it only works when the container was started with "-- name $NAME". Using the random generated name or the containerId oder the containerIP doesnt work. I think its because the strange Jenkins  VM Network settings here. No chance to get around this.

**Comment by HaVonTe1** [comment]
Dont mind. I found a nice workaround:
```
            .withCreateContainerCmdModifier(new Consumer<CreateContainerCmd>() {
                @Override
                public void accept(CreateContainerCmd createContainerCmd) {
                    createContainerCmd.withHostName(CNAME);
                    createContainerCmd.withName(CNAME);
                }
            })
```

**Comment by RobMaskell** [comment]
I'd like to see this too, the use case for me is being able to set the names so they match config that works because when the containers are started on the same network I can do DNS based service discovery.

**Comment by bsideup** [comment]
@RobMaskell if you use Networks you can (and should) use `withNetworkAliases` to provide a DNS name for your container, see:
https://github.com/testcontainers/testcontainers-java/blob/4471878f332dd8e7880fc8a55879a45834556e5e/core/src/test/java/org/testcontainers/containers/NetworkTest.java#L23

**Comment by RobMaskell** [comment]
Thanks @bsideup will try but two questions, do I still need to add containers to a network for this to work and how can I `.withNetworkAliases()` on a PostgreSQLContainer like so
```
@ClassRule
public static PostgreSQLContainer postgres = new PostgreSQLContainer("postgres:alpine")
		.withDatabaseName("postgres")
		.withUsername("postgres")
		.withPassword("password")
		.withNetworkAliases("db");
```
because doing this I get an incompatible type error in intellij

**Comment by kiview** [comment]
@RobMaskell This has to do with the usage of Generics in Testcontainers. It will work if you would use `GenericContainer` as a Type on the left side.

However, what exactly are you trying to achieve? You haven't added a network in this case, other containers will only be able to access this container using the alias if they are inside the same network. Or are you trying to access the container from your host? In this case, you should rely on the dnymaic port binding and use `getMappedPorts()` or `getJdbcUrl()` in this case.

**Comment by RobMaskell** [comment]
@kiview  thanks, I saw the network was needed in the examples so I'll add that, and now I know the options I should be able to make it work. Not trying to access the container from the host, this is container to container, I need to start up two (db, api) to be able to test a third from the host.

**Comment by IgorPerikov** [comment]
I'm initializing cluster of 3 etcd nodes, where I should link them during start command and this `.withNetworkAliases("foo")` works perfectly for me, thanks!

**Comment by bsideup** [comment]
Given the presence of `withCreateContainerCmdModifier` I will close this issue

**Comment by claussni** [comment]
The documentation of `withCreateContainerCmdModifier` says:
>**Warning**: this does expose the underlying docker-java API so might change outside of our control.

To me, this seems like a **strong** indication for extending the interface of `GenericContainer`.
