### ISSUE TITLE
The docs index.md fails to link to useful doc pages

### ISSUE THREAD

**Issue by georgespalding** [testcontainers/testcontainers-java#255]
When navigating to the docs site (http://testcontainers.viewdocs.io/testcontainers-java/), 
the page does not link to [/usage](../tree/master/docs/usage.md) or any other useful page.

It is probably a good idea to link to the docs if you want people to read them.

**Comment by bsideup** [comment]
TestContainers has new awesome docs published at https://www.testcontainers.org

Where did you get a link to http://testcontainers.viewdocs.io/testcontainers-java/ ?

**Comment by rnorth** [comment]
I've updated the docs link in the main repo readme to point to the new docs site. Sorry for missing that before, but please refer to www.testcontainers.org for a far more usable docs experience.

There are probably a few links to the old docs site floating around on external sites, so I'll review and try and get them changed. Or set up meta-refresh to redirect people.

**Comment by bsideup** [comment]
I think we can close this one because of the new docs ( www.testcontainers.org )

@georgespalding let us know if you still miss something there :)
