### ISSUE TITLE
JUnit 4 dependency

### ISSUE THREAD

**Issue by ebramirez** [testcontainers/testcontainers-java#2564]
I just realised that the toxiproxy module brings JUnit 4 as a depencency (or I'm missing something).

Are this dependencies intentional?
![testcontainers-dependencies](https://user-images.githubusercontent.com/42619854/79105424-276cde00-7d60-11ea-9d90-b7def6beb1be.png)

**Comment by bsideup** [comment]
Duplicate of #970
