### ISSUE TITLE
Idea - chaos testing

### ISSUE THREAD

**Issue by slnowak** [testcontainers/testcontainers-java#258]
There is a project called pumba https://github.com/gaia-adm/pumba, that kind of simulates chaos testing that netflix does, on container level. 

There's also dockerized pumba, that could be easily started without the need of having pumba installed on your OS. 

@rnorth What do you think about creating a module/project that provides dockerized pumba and a small DSL for running it? 
Arquillian has something similar (http://arquillian.org/blog/2016/08/30/arquillian-cube-q-1-0-0-Alpha1/, check Container Chaos).

I think it would be useful to have such tools integrated with testcontainers.

**Comment by rnorth** [comment]
I still consider this a really valuable potential feature, and am quite looking forward to #283 when it comes. 

Not a stale issue, despite the age!

**Comment by rnorth** [comment]
Reopening- I’d still like to do this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnorth** [comment]
This is now done since a while ago, in the form of #1330 - Toxiproxy support. I'll close this issue.
Thank you for the inspiration @slnowak.
