### ISSUE TITLE
hardcoded images

### ISSUE THREAD

**Issue by mabn** [testcontainers/testcontainers-java#259]
Some classes use hardcoded images which makes it impossible to use testcontainers with private registry. In particular [richnorth/ambassador:latest](https://github.com/testcontainers/testcontainers-java/blob/f4368427e8c6a07a8cfe51caedde4962f10dfed1/core/src/main/java/org/testcontainers/containers/AmbassadorContainer.java#L27).

It should be adjustable, e.g. via a config file or env variable. Or with additional parameters to junit rules.

Also:
[richnorth/vnc-recorder:latest](https://github.com/testcontainers/testcontainers-java/blob/f4368427e8c6a07a8cfe51caedde4962f10dfed1/core/src/main/java/org/testcontainers/containers/VncRecordingSidekickContainer.java)

**Comment by rnorth** [comment]
@mabn thanks, yes, it's probably about time to make these configurable. I think a config file on the classpath would be the right answer.
