### ISSUE TITLE
Misspelled service name in DockerComposeContainer#waitingFor is hard to debug

### ISSUE THREAD

**Issue by jannis-baratheon** [testcontainers/testcontainers-java#2600]
So I've just spent a few hours debugging a problem with DockerComposeContainer. It didn't wait for a service to start and the problem turned out to be a misspelled service name in DockerComposeContainer#waitingFor:

	new DockerComposeContainer(dockerComposeFile)
		.waitingFor("some_srevice", Wait.forLogMessage("started", 1))

I assumed that Testcontainers would at least warn me that the waiting condition is wrong (and even better - crash), but it turned out otherwise.

Looking at the code I think it's a low-hanging fruit to have this done. A quick verification in DockerComposeContainer#waitUntilServiceStarted() woud get it easily done (check if all entries in `waitStrategyMap` have a corresponding service instance in `serviceInstanceMap` and fail fast).

I can post an MR for this if you agree with me.

**Comment by kiview** [comment]
Hey @jannis-baratheon,
I haven't checked the code now, but I think you are right, specifying a non-existing service should IMO throw an exception.

A PR for this sounds great, do @bsideup and @rnorth agree that fail fast is the best approach here?

**Comment by askfor** [comment]
Hi I think #2637 may have some issues. After we upgrade testcontainers from 1.12.5 to 1.14.2, the test failed with following error. (We used multiple compose file to start service, don't know if it matters)

java.lang.IllegalStateException: Services named [xxx_1] do not exist, but wait conditions have been defined for them. This might mean that you misspelled the service name when defining the wait condition.
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:227)

**Comment by jannis-baratheon** [comment]
@askfor You'd need to provide more details. Some code (inl. docker-compose files) would be useful.

**Comment by askfor** [comment]
When we got some more detailed info, I'll post it here. Currently, we rolled back to 1.12.5.
