### ISSUE TITLE
Container stop is killing the container

### ISSUE THREAD

**Issue by diegolovison** [testcontainers/testcontainers-java#2608]
`container.stop()` is calling -> `dockerClient.killContainerCmd`

**ResourceReaper.java**
```java
        if (running) {
            try {
                LOGGER.trace("Stopping container: {}", containerId);
                dockerClient.killContainerCmd(containerId).exec();
```

When calling stop I am expecting a graceful shutdown.

**Comment by bsideup** [comment]
@diegolovison Testcontainers is a testing library, there is no point in doing a graceful shutdown of throwaway resources.

If you need to destroy the container gracefully, consider overriding `containerIsStopping` and sending a soft kill signal.

**Comment by shaburov** [comment]
@bsideup This is not so, I have a java service running in testcontainers, and due to the fact that the container is killed, and not stopped via SIGTERM, the application does not correctly close the pool of connections to the database and then they hang idle on the database side.
This is a bug
