### ISSUE TITLE
Hardcoded InfluxDb image name for InfluxDbContainer implementation

### ISSUE THREAD

**Issue by alexromanov** [testcontainers/testcontainers-java#2632]
Hi. 
Most of the container implementations (CocroachDb, Postgres, MariaDB, OrientDb) have an additional constructor beside the default one. The additional constructor takes one String parameter - dockerImageName. 
For InfluxDbContainer [https://github.com/testcontainers/testcontainers-java/blob/master/modules/influxdb/src/main/java/org/testcontainers/containers/InfluxDBContainer.java](url) we have the same approach, but constructor takes only image version. The image name is hardcoded value and can't be modified. 
Is it a common approach for all upcoming container implementations? Or I should make PR for fixing it?

**Comment by bsideup** [comment]
Hi @alexromanov,

It is not common and should not be used, but, due to String-typed API, we can't easily change it now I am afraid.

FYI was a workaround, you can use `setDockerImageName` method after creating but before starting the container.

**Comment by alexromanov** [comment]
Thanks a lot, @bsideup. I just used setDockerImageName() method for keeping our API consistent.
