### ISSUE TITLE
Add support for gcloud emulators

### ISSUE THREAD

**Issue by eddumelendez** [testcontainers/testcontainers-java#2633]
[google cloud sdk](https://hub.docker.com/r/google/cloud-sdk/) is available via docker hub. I think `testcontainers` can provide an easy way to start emulators like `pubsub`, `datastore`, `firestore`, `spanner`.

If you agreed, I can work on it.

**Comment by rnorth** [comment]
Yes please! I'd use this myself 😄

**Comment by saturnism** [comment]
for record, this being implemented by @eddumelendez in #2690

**Comment by eddumelendez** [comment]
#2690 is merged!
