### ISSUE TITLE
ImageFromDockerfile does not remove images

### ISSUE THREAD

**Issue by Brutt** [testcontainers/testcontainers-java#2640]
Hi.
Based on [this answer](https://github.com/testcontainers/testcontainers-java/issues/417#issuecomment-318064857) I created an abstract class to share one Tomcat container between all tests:
```
abstract class AbstractTestContainer {
    private static final String APP_NAME = "ImageFromDockerFileTest-1.0-SNAPSHOT";
    private static final String WAR_NAME = APP_NAME + ".war";

    private static String parent = new File(
            AbstractTestContainer.class.getProtectionDomain().getCodeSource().getLocation().getPath()
    ).getParent();
    private static Path dockerfileFolder = Paths.get(
            new File(
                    AbstractTestContainer.class.getClassLoader().getResource("Dockerfile").getFile()
            ).getParent()
    );

    protected static final GenericContainer TOMCAT = new GenericContainer(
            new ImageFromDockerfile("tomcat_test")
                    .withFileFromPath(WAR_NAME, Paths.get(parent, WAR_NAME))
                    .withFileFromPath(".", dockerfileFolder)
    )
            .withExposedPorts(8080);

    static {
        TOMCAT.start();
    }
}
```

Dockerfile:
```
FROM tomcat:9.0.31

ADD ImageFromDockerFileTest-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]
```
All project you can find [here](https://github.com/Brutt/ImageFromDockerFileTest).

However, when all tests have done I still see test images:
<a href="https://i.postimg.cc/CKqrXXjZ/images.png" rel="some text">![Link](https://i.postimg.cc/CKqrXXjZ/images.png)</a>

So I have to remove them myself. 
Is this the correct behavior?

**Comment by bsideup** [comment]
Hi @Brutt,

I haven't looked into the actual issue yet, but wanted to mention that you don't need to build an image for your use case at all.

Just use something like:
```
new GenericContainer("tomcat:9.0.31")
    .withExposedPorts(8080)
    .withCopyFileToContainer(warFile, "/usr/local/tomcat/webapps/app.war")
```

**Comment by Brutt** [comment]
Thank you @bsideup. Your code is working.
Nevertheless, I believe that the mentioned behavior should be checked.

**Comment by vcvitaly** [comment]
@Brutt Just to make sure, do you stop container as well?

something like
`@AfterAll
    public static void afterAll() {
        TOMCAT.stop();
    }`

**Comment by Brutt** [comment]
> @Brutt Just to make sure, do you stop container as well?
> 
> something like
> `@AfterAll public static void afterAll() { TOMCAT.stop(); }`
> 
> you might want to move `TOMCAT.start();` to `@BeforeAll` as well

Thanks @vcvitaly, but it`s not my case. I want to raise one container per all test methods from all test classes that extend my abstract class. In your suggestion container will run and stop for every test class, so it will be a waste of time.

**Comment by vcvitaly** [comment]
> > @Brutt Just to make sure, do you stop container as well?
> > something like
> > `@AfterAll public static void afterAll() { TOMCAT.stop(); }`
> > you might want to move `TOMCAT.start();` to `@BeforeAll` as well
> 
> Thanks @vcvitaly, but it`s not my case. I want to raise one container per all test methods from all test classes that extend my abstract class. In your suggestion container will run and stop for every test class, so it will be a waste of time.

If you do that in abstract class, container will be started and stopped only once I belive

**Comment by Brutt** [comment]
@vcvitaly 
[@BeforeAll](https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/BeforeAll.html) is used to signal that the annotated method should be executed before all tests in the **current** test class.

```
abstract class AbstractTest {
    @BeforeAll
    static void beforeAll(){
        System.out.println("Before all");
    }

    @AfterAll
    static void afterAll(){
        System.out.println("After all");
    }
}

class Test1 extends AbstractTest{
    @Test
    void test1(){
        System.out.println("test 1");
    }

    @Test
    void test11(){
        System.out.println("test 11");
    }
}

class Test2 extends AbstractTest{
    @Test
    void test2(){
        System.out.println("test 2");
    }

    @Test
    void test21(){
        System.out.println("test 21");
    }
}
```

Output:
```
Before all

test 21

test 2

After all
Before all

test 11

test 1

After all
```

**Comment by vcvitaly** [comment]
@Brutt 
I see, that's my mistake.

Then the only thing that comes to mind is something like this:

> This is now possible in JUnit5 by creating a custom Extension, from which you can register a shutdown hook on the root test-context.
> ...
> When you use this extension on multiple classes, the startup and shutdown logic will only be invoked once.

https://stackoverflow.com/a/51556718/8587732
