### ISSUE TITLE
Unable to run a simple node.js script from testcontainers

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [testcontainers/testcontainers-java#2684]
I was trying to run node.js from testcontainers but I do not see a way to just perform "docker run" kind of use-case with TestContainers. I basically do not want to start the container, but just run a command on it.

For example, I do not find an easy way to run something as simple as 

docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:alpine node node.js

**Comment by bsideup** [comment]
`docker run` starts a container. See https://www.testcontainers.org/features/commands/#container-startup-command for more information.
