### ISSUE TITLE
Draft a roadmap

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#27]

**Comment by swissarmykirpan** [comment]
TC as a service?

**Comment by rnorth** [comment]
I've written up a roadmap here based on my current intentions for where to take this: https://github.com/testcontainers/testcontainers-java/wiki/ROADMAP

**Comment by rnorth** [comment]
> TC as a service?

I'd say we should probably just let people use any docker-compatible cluster they want. There would be certain disadvantages of this though; for example, the selenium/webdriver support needs to be able to mount local folders as volumes to capture videos. I don't think you could do this if the docker host wasn't quite coupled to the local developer machine.

Turning this into a service would basically be entering the Docker-as-a-Service (basically IaaS) space, which would be a huge undertaking!

**Comment by swissarmykirpan** [comment]
That's exactly what I'm suggesting. Especially for running things like CI  I can imagine that people won't want to have to create an entire infrastructure in order to house containers in CI. We could make it work with priority queues and get it to scale up and down as necessary.

**Comment by rnorth** [comment]
I think the standard mode of usage for TC in CI is that the docker containers run on the same machine as the CI build slave. This really ought to work for 95% of cases. (I'm not excluding running the build inside a container and using docker environment variables to allow the test to talk to the local docker daemon).

If you wanted to set up Docker-as-a-Service like this it might be an interesting startup, but it's way too much for this little project (and I don't think the two things need to be coupled together at all).

Because a container can basically do anything, you'd have to be _really_ careful about billing, security, abuse, etc - it's basically a level of effort on par with setting up a cloud IaaS provider, just based on containers not virtualization...

**Comment by swissarmykirpan** [comment]
Yeah, that seems reasonable. Would you have an issue with me acquiring testcontainers.io ?

**Comment by rnorth** [comment]
Hmm, if it just permanently redirected to testcontainers.org I guess that
would be OK, though I can't really see why you'd want to spend money to do
that ;)

(NB there's no website at testcontainers.org yet, but we should put a
simple web page up there).

**Comment by swissarmykirpan** [comment]
haha! it was worth a shot!

**Comment by rnorth** [comment]
I guess I'll close this ticket and take pull requests on the wiki for further comments and suggestions!
