### ISSUE TITLE
Help needed regarding MySqlContainer

### ISSUE THREAD

**Issue by rupam16** [testcontainers/testcontainers-java#2756]
I have a `Dockerfile` with some instructions like below
```Docekrfile
FROM mysql:5.7.22
RUN cp -r /var/lib/mysql /var/lib/mysql-no-volume
CMD ["--datadir", "/var/lib/mysql-no-volume"]
COPY sql/some.sql /docker-entrypoint-initdb.d/
```

How should I create the similar image but on the fly ? 

I was trying the following
```java
MySQLContainer container = new MySQLTestContainer("mysql:5.7.22"); // FROM Equivalent
// TODO: what will be the equivalent for the RUN ?
container.withCommand("--datadir", "/var/lib/mysql-no-volume"); // CMD Equivalent
container.withInitScript("sql/some.sql"); // COPY Equivalent
```

**Comment by raynigon** [comment]
Take a look at the documentation: https://www.testcontainers.org/features/creating_images/

**Comment by rupam16** [comment]
I need the jdbc url after starting the container. I think thats my blocker.

I need the url for timezone related changes. Currently in my dockerfile, I am manipulating some paths to put timezone info. and while using that with hikari config, I need the jdbc url overridden to append timezone in the connection string.

**Comment by Stexxen** [comment]
Could you not call `MySQLContainer.getJdbcUrl()` then append the timezone either directly or by converting it to a `URI`.

**Comment by rnorth** [comment]
I think this is a usage question and not a Testcontainers bug/feature request, so I'm going to close.
