### ISSUE TITLE
Utility container images with `latest` tags should be replaced by a versioned image

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#276]
`richnorth/ambassador:latest` and `richnorth/vncrecorder:latest` can't be safely upgraded because Testcontainers uses the 'latest' tag. As such, for a future version of Testcontainers we should create new container images within a new namespace, and set an explicit version number.

**Comment by bsideup** [comment]
Seems to be fixed and released in 1.1.8
