### ISSUE TITLE
Optionally map resources to current user in r/o mode

### ISSUE THREAD

**Issue by redcatbear** [testcontainers/testcontainers-java#2762]
## Situation

Especially in debugging situations it is often useful to map log files or a whole log directory from inside the container to a local file system so that you can analyze the logs software inside the container produces after a test run.

For this we are using the volume mapping described here: https://www.testcontainers.org/features/files/

While that function is already quite useful, the files are created with their original UID and GID. For the software _inside_ the container that is exactly what you want, since access rights depend on it.

For debugging from the outside however it is an obstacle. What you really need in that case is to have the files belonging to the user under which the test ran. Or a configurable (UID/GID).

Now if you simply squash the mapped files to that user / group, software inside the container might malfunction.

I don't know if that is feasible, but being able to get a self-updating copy of mapped resource would be very nice.

## Environment

* Testcontainers: 1.14.2
* Java: `openjdk version "11.0.7" 2020-04-14`
* OS: `Linux 5.4.0-29-generic #33-Ubuntu SMP (and other Linux versions)`

**Comment by PandarinDev** [comment]
What you'd need is to be able to specify UID/GID just like you can do when running Docker from the CLI with the `--user` switch. This issue describes the use-case better: [Link](https://github.com/testcontainers/testcontainers-java/issues/2590). Unfortunately there is no support for this right now AFAIK.

**Comment by bsideup** [comment]
There is, see my answer:
https://github.com/testcontainers/testcontainers-java/issues/2590#issuecomment-658120759
