### ISSUE TITLE
Reusable containers are not affected by classpath property

### ISSUE THREAD

**Issue by renannprado** [testcontainers/testcontainers-java#2766]
So according from what I've seen in the code [here](https://github.com/testcontainers/testcontainers-java/blame/43a76abb5d27f322a6a7a30ffc148beb31cd5736/core/src/test/java/org/testcontainers/utility/TestcontainersConfigurationTest.java#L41) it's by intention that the reusable test containers config is not picked up from the classpath, which IMO is very confusing. While running my tests, I don't expect that I need some kind of "setup" (even though it's optional) before I can simply run my `./gradlew test`, neither locally or inside of my CI. 

Is there a workaround for it?

**Comment by bsideup** [comment]
It is an optimization, not prerequisite.

See https://github.com/testcontainers/testcontainers-java/pull/1781#discussion_r369160221
