### ISSUE TITLE
Upgrade Cassandra driver to 4.x

### ISSUE THREAD

**Issue by emerkle826** [testcontainers/testcontainers-java#2768]
Currently, the CassandraContainer makes use of the DataStax [3.7.1 driver](https://github.com/testcontainers/testcontainers-java/blob/master/modules/cassandra/build.gradle#L5). The 3.x series of the driver is effectively in maintenance mode and only receiving critical fixes.

The 4.x driver series has been released for a while, with the current latest version being [4.6.1](https://docs.datastax.com/en/developer/java-driver/4.6/), however, the new driver is not a drop-in binary compatible replacement.

I would be happy to post a PR to upgrade the driver, if acceptable.

**Comment by adutra** [comment]
Please don't close this. There is a PR for this issue: #2830.

**Comment by rnorth** [comment]
Reopening, and labelling so that it won't be closed automatically.

**Comment by eddumelendez** [comment]
A new implementation has been added in #8616 and it doesn't rely on the cassandra client.
