### ISSUE TITLE
Supports custom docker engine port in DockerMachineClientProviderStrategy

### ISSUE THREAD

**Issue by fuminchao** [testcontainers/testcontainers-java#2769]
The port is hardcoded as ```2376``` in
https://github.com/testcontainers/testcontainers-java/blob/f113979ad5207464490cc4f19f488bb27795802c/core/src/main/java/org/testcontainers/dockerclient/DockerMachineClientProviderStrategy.java#L57

It should be parsed from the output of ```docker-machine ls```

**Comment by rnorth** [comment]
Let's keep this open.

**Comment by vcvitaly** [comment]
I can take it.

**Comment by vcvitaly** [comment]
@rnorth is it still relevant? The change is straightforward, it looked and the code, it will take a little time to implement it, but the `DockerMachineClientProviderStrategy` class is deprecated.
