### ISSUE TITLE
[Envinroment issue] - Own Kafka container doesn not start in the Travis CI

### ISSUE THREAD

**Issue by see-quick** [testcontainers/testcontainers-java#2774]
Hello guys, I have implemented my own version of Kafka container, which inherits from the GeneralContainer. Everything works fine locally, also on Azure pipelines, Jenkins and so on. The problem comes when I run the Kafka Container on Travis CI. The Kafka port `does not open` and it will end on timeout.
here is my code ->  https://github.com/strimzi/strimzi-kafka-operator/blob/master/test-container/src/main/java/io/strimzi/StrimziKafkaContainer.java
here  is the log from the Travis CI -> https://gist.github.com/see-quick/422bfac6795043b34d4968b956adbc08

test-container/src/main/java/io/strimzi/StrimziKafkaContainer.java

**Comment by bsideup** [comment]
> mkdir: cannot create directory '/opt/kafka/bin/../logs': Permission denied

I think that's pretty clear from the logs. Looks like an issue with permissions and Docker, not Testcontainers related.

**Comment by see-quick** [comment]
This is the log from the `Azure pipelines`, and there you can see the same error but all tests passed. Definitely, it is something different.

log azure -> https://gist.github.com/see-quick/bee9714caa9d91683182d9bde0f104f9

**Comment by see-quick** [comment]
I have fixed this issue instead of using executor use the dynamic creating the command and run inside the container
```
String command = "#!/bin/bash \n";
        command += "bin/zookeeper-server-start.sh config/zookeeper.properties &\n";
        command += "bin/kafka-server-start.sh config/server.properties --override listeners=BROKER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:" + KAFKA_PORT +
            " --override advertised.listeners=" + advertisedListeners.toString() +
            " --override zookeeper.connect=localhost:" + ZOOKEEPER_PORT +
            " --override listener.security.protocol.map=BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT" +
            " --override inter.broker.listener.name=BROKER\n";

        LOGGER.info("Copying command to 'STARTER_SCRIPT' script.");

        copyFileToContainer(
            Transferable.of(command.getBytes(StandardCharsets.UTF_8), 700),
            STARTER_SCRIPT
        );
```
