### ISSUE TITLE
ParsedDockerComposeFile will get more images than actually needed when multiple Compose files were used

### ISSUE THREAD

**Issue by askfor** [testcontainers/testcontainers-java#2782]
When the same service with different images specified in different Compose files, the last image should be the one, but ParsedDockerComposeFile will combine all images. then more images were fetched than actually needed.

**Comment by rnorth** [comment]
Hi @askfor 
Please could you give an example?

**Comment by askfor** [comment]
for example, there're two compose file:
compose-a.yaml
```
services:
  redis:
    image: "redis"

  app:
    image: "app:dev"
```
compose-b.yaml
```
services:

  app:
    image: "app:prod"
```

`
new DockerComposeContainer("compose-a.yaml", "compose-b.yaml").start()
`

When org.testcontainers.containers.DockerComposeContainer#pullImages tries to pull the images, it'll pull both app:dev, app:prod instead of only pull app:prod.  

I think ParsedDockerComposeFile  should return both service name and image and then DockerComposeContainer can keep the last image for every service.

**Comment by rnorth** [comment]
Aha, got it. That's a good suggestion, let's do that. Thank you.

I _guess_ this is only an inconvenience and not a blocker - is that right?

**Comment by askfor** [comment]
Thanks, and yes it's not a blocker.

**Comment by askfor** [comment]
Hi, @rnorth can you take a look at #3787 if it can be merged? Thanks.
