### ISSUE TITLE
ServiceConfigurationError DockerClientProviderStrategy EnvironmentAndSystemPropertyClientProviderStrategy not a subtype

### ISSUE THREAD

**Issue by ruddy32** [testcontainers/testcontainers-java#2790]
Hi,
The system is installed with Linux and Podman 1.9.2.
Both system and user podman API service are started.
System is using `/var/run/podman/podman.sock`.  User is using `/var/run/user/1000/podman/podman.sock`.

Maven surefire configuration define DOCKER_HOST environment variable lke this:
`<DOCKER_HOST>unix:///run/user/1000/podman/podman.sock</DOCKER_HOST>`

Running unit test on IntelliJ using OpenJDK 11 on Linux provide the following error:
`java.util.ServiceConfigurationError: org.testcontainers.dockerclient.DockerClientProviderStrategy: org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy not a subtype`

Sample code:
```
public class KeycloakContainer implements BeforeAllCallback, AfterAllCallback {
    private GenericContainer keycloak;

    @Override
    public void beforeAll(ExtensionContext extensionContext) {
        try {
            ...
            keycloak = new FixedHostPortGenericContainer(imageName.concat(":").concat(imageTag))
                    .withFixedExposedPort(port, 8080)
                    .withEnv("KEYCLOAK_USER", user)
                    .withEnv("KEYCLOAK_PASSWORD", password)
                    .withEnv("KEYCLOAK_IMPORT", importPath)
                    .withClasspathResourceMapping(realm, importPath, BindMode.READ_ONLY)
                    .waitingFor(Wait.forHttp(authPath));
            keycloak.start();
        } catch (ContainerLaunchException | ServiceConfigurationError e) {
            LoggerFactory.getLogger(getClass()).error("Failed to run Keycloak container", e);
        }
    }
    ...
}
```

Is it a problem with maven configuration ? OpenJDK 11 ?
Thanks.

**Comment by rnorth** [comment]
It seems like you probably have a classpath problem - I'd expect this kind of error to occur if you have more than one version of code on the classpath. I'd suggest checking your Maven dependencies tree to see if you have more than one version of the Testcontainers libs being pulled in.

By the way you're in fairly uncharted territory trying to use Testcontainers. I may not be fully up to date on the state of things, but at the last check podman did not support the full Docker API. I'd be quite surprised if this works - happy (!), but surprised.

BTW 2, we really do not recommend using `FixedHostPortGenericContainer` if you can avoid it, for reasons [described here](https://bsideup.github.io/posts/testcontainers_fixed_ports/).

Sorry for giving you more tips than you were after!

As I don't think there's an actual Testcontainers bug at play here I'll close the ticket, but if you do track this down to a Testcontainers bug please feel free to reopen with extra info.

**Comment by ruddy32** [comment]
I solve this problem by implementing feature using another way.
But I still facing a problem using Podman API socket.
Thanks for your feedback and advises.
