### ISSUE TITLE
disabledWithoutDocker swallows exceptions unrelated to build environment

### ISSUE THREAD

**Issue by StefWin** [testcontainers/testcontainers-java#2792]
With the recent outages of quay i've noticed a problem with the junit-jupiter extension when `disabledWithoutDocker` is set to true. When quay is unavailable the entire test is marked as skipped rather then failed. This happens because 'disabledWithoutDocker' does not only check for an existing daemon it also bootstraps `ryuk`.

> [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://docker:2376
[main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is docker
[main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 19.03.9
  API Version: 1.40
  Operating System: Alpine Linux v3.11 (containerized)
  Total Memory: 7967 MB
[tc-okhttp-stream-462044372] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: received unexpected HTTP status: 500 Internal Server Error"}
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s

Proposal:
Only check the existence of an docker daemon in` isDockerAvailable`, or fail the build when `ryuk` cannot be downloaded.

**Comment by bsideup** [comment]
The point of `disabledWithoutDocker` is to skip the tests if there is something wrong and they cannot continue anyways.
If you're _relying_ on these tests, consider not using it, and maybe add some custom logic that will skip the test when you feel that it should be skipped.
