### ISSUE TITLE
Allow named and reusable Networks

### ISSUE THREAD

**Issue by aaronjwhiteside** [testcontainers/testcontainers-java#2793]
The current `Network.newNetwork()` when used with multiple container that set `.withReuse(true)` is not meaningful, network ids need to remain static.

I propose something along the lines of:

```
Network network = Network.named("test").withReuse(true);
```

We are currently using a custom `Network` implemention that supports naming the network, it supports `.withReuse(true)` much the same way that `GenericContainer` does. It first checks for a matching network by its name, then compares a hash of `CreateNetworkCmd` stored in the labels.

If the network is `.withReuse(true)`, then `.close()` does nothing.

It would be good to have this functionality officially support so that others may take advantage of it.

**Comment by bsideup** [comment]
As a general rule, to avoid conflicts, we do not support static resource names / ports / etc

The issue (reusable containers with networks) is known and we have ideas how to handle it.

Meanwhile, if you _really_ need to use a named network, you can implement `Network` interface yourself.

**Comment by aaronjwhiteside** [comment]
That's what I currently have, a custom implementation of Network. As stated in another GH issue comment, I'd love to understand what ideas you have around this. And I'm willing to contribute to make it happen.
