### ISSUE TITLE
ContainerisedDockerCompose causes high cpu by polling to frequently

### ISSUE THREAD

**Issue by kadaan** [testcontainers/testcontainers-java#2796]
ContainerisedDockerCompose's use of IndefiniteWaitOneShotStartupCheckStrategy causes high cpu because IndefiniteWaitOneShotStartupCheckStrategy only sleeps 100ms between attempts. 
 Additionally IndefiniteWaitOneShotStartupCheckStrategy seems to be a "hack" to allow indefinite polling.

**Comment by rnorth** [comment]
Do you have a suggestion for an improvement? With polling, there's an obvious tradeoff between rate of checks and responsiveness when the task has finished.

How much of a CPU load problem is this causing for you?
