### ISSUE TITLE
CouchbaseContainer checkSuccessfulResponse() does not include the actual error response from Couchbase

### ISSUE THREAD

**Issue by aaronjwhiteside** [testcontainers/testcontainers-java#2799]
On line:
https://github.com/testcontainers/testcontainers-java/blob/master/modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java#L389

the `Response.toString()` does not actually read the body of the response, that needs to be done manually.. without the body of the response it is impossible to know what the underlying error was..

**Comment by rnorth** [comment]
Aha, thanks. WDYT @daschl?

**Comment by daschl** [comment]
Makes sense to me to include the body as well - @aaronjwhiteside do you want to come up with a PR?

**Comment by daschl** [comment]
Note that there is an outstanding refactoring in that code path, once that is merged I can also take it on and get it fixed.
