### ISSUE TITLE
Add support for a pre-container-start/reuse callback.

### ISSUE THREAD

**Issue by aaronjwhiteside** [testcontainers/testcontainers-java#2800]
My use case is bootstrapping microservices, we have seperate containers for bootstrapping, which are one-short containers that only need to be run only once.

`.dependsOn(bootstrapper)` is not sufficent for this use case, and it will always be triggered (although our bootstrap containers are idempotent, they still take away precious startup time we are trying to gain back by using `.withReuse(true)`).

What would work for us though, is a pre start/reuse callback called before a container is actually started/reused to indicate if test containers intents to start a new contain or reuse an existing one.

At first glance it seems that `containerIsCreated()` could be used this way, however it seems there is an explict check that prevents anyone overriding this and using `.withReuse(true)` which is perplexing.. no documentation on what `containerIsCreated()` was actually intended for?

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L334-L350

Open to suggestions here..

Ideally we want a hook/callback we can get that indicates that the container isn't being reused, so that we can kick off our bootstrap container BEFORE the actual container in question starts.

**Comment by bsideup** [comment]
@aaronjwhiteside you can override both `containerIsCreated` and `canBeReused`.

The check is there to force you to think whether `containerIsCreated` is not doing something that will break the reuse (does not seem to be your case).
By overriding `canBeReused`, you give you "consent" that you understand that.

**Comment by aaronjwhiteside** [comment]
Gotcha, thanks for the quick answer!
