### ISSUE TITLE
.withReuse(true) is broken out of the box because of randomly assigned network alias

### ISSUE THREAD

**Issue by aaronjwhiteside** [testcontainers/testcontainers-java#2801]
On line:

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L136-L139

A random network alias is assigned during field initialization time, this ALWAYS prevents the computed hash from matching, unless one calls `container.getNetworkAliases().clear()` before adding their own network alias with `.withNetworkAliases("some static value")`.

I propose that the default behaviour to allocate a random network alias be changed to happen lazily and when no other explictly specified network alias is set.

And also perhaps print a warning/error when no explict network alias is defined and `.withReuse(true)` is used.

**Comment by bsideup** [comment]
@aaronjwhiteside yes, Reusable Containers are not compatible with networks as stated in the PR:
https://github.com/testcontainers/testcontainers-java/pull/1781

Also, I would not call it "broken", but rather "not supported" (yet). We have some ideas how to support Networks (even if you fix the aliasing, the Network id is still random), but it requires a bit of time.

**Comment by aaronjwhiteside** [comment]
I have it working by clearing the assigned network aliases and using a custom implementation of Network. 

I'd be interested to hear what ideas you have, even if I may better use them in our setup. I'd be happy to contribute too.

**Comment by bharath-tw** [comment]
A simpler way would be to directly set the networkAliases via `setNetworkAliases(List.of("kafka"))`
