### ISSUE TITLE
quay.io host is down, testcontainers are not working

### ISSUE THREAD

**Issue by Bryksin** [testcontainers/testcontainers-java#2806]
Hi, seems like quay.io host is down

Now our builds are failing:

```
Error creating bean with name 'mySQLContainerProvider': Invocation of init method failed; nested exception is org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@3e0600a4[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: 
{"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: received unexpected HTTP status: 500 Internal Server Error"}
```

Host: https://quay.io/ resolves as https://quay.io/500 with the message:
![](https://i.gyazo.com/2c1c97158594c27e1ae332ae20544016.png)

and URL: https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3

![](https://i.gyazo.com/7053fd50a3dbd34ed4b113b4c501811c.png)

By the time when this ticket will be actioned, the host more likely will be up and running, but just want to keep a note here.
In case if that will happen often, possibly `testcontainers` will need to move to another more reliable container host

**Comment by seglo** [comment]
Same issue for us.  What is the purpose of this API call?

https://travis-ci.com/github/akka/akka-projection/jobs/340956572#L486

**Comment by bsideup** [comment]
This is not an API call, but standard Docker image pulling that fails.

Please see #2763 for the discussion.

**Comment by seglo** [comment]
Thanks @bsideup

**Comment by Bryksin** [comment]
oh duplicate, sorry, but general search by default search within open tickets only, and #2763 is closed.
But now we know that problems with quay.io happen often :)

**Comment by bsideup** [comment]
It was quite stable over the past few years (and, in fact, was even more stable that Docker Hub back then when we needed it), but this month Quay became terribly unstable.

We're working on migrating to Docker Hub. It is almost done, and you can start using some of the images already:
http://hub.docker.com/r/testcontainersofficial/

If not sure how, see this:
https://www.testcontainers.org/features/configuration/#customizing-images
