### ISSUE TITLE
Push Ryuk to dockerhub?

### ISSUE THREAD

**Issue by jamsesso** [testcontainers/testcontainers-java#2808]
Is it possible for the Ryuk docker image to be pushed to dockerhub? Quay.io has been pretty unstable and caused a lot of turbulence in our builds recently. We're currently using a forked image hosted by someone else on dockerhub (https://hub.docker.com/r/humio/ryuk) just to get the benefit of stability, but don't really like the idea of relying on community-driven forks.

**Comment by bsideup** [comment]
Please see #2763
