### ISSUE TITLE
Strong coupling with "alpine:3.2" image in DockerClientFactory

### ISSUE THREAD

**Issue by dddpaul** [testcontainers/testcontainers-java#281]
Hello.

When #267 was merged running docker inside docker works fine :)  This feature is very useful for CI pipelines when Jenkins slave executes in Docker container, for example.

But build servers may have partial Internet connectivity  - to the local Docker registry only (just like in my case). So despite of wonderful docker-in-docker support build fails nevertheless on DockerClientFactory.instance().client() invoke.

Can we get rid of this builtin image dependency or make it customizable at least? For example, pass image name  to DockerClientFactory through environment variable?

**Comment by bsideup** [comment]
Hi @dddpaul,

I suppose https://github.com/testcontainers/testcontainers-java/pull/277 will help; we just have to make `TINY_IMAGE` configurable.

Will it work for you? (properties file configuration of the images)

**Comment by rnorth** [comment]
Yes, sorry - I should have remembered to include this in #277

**Comment by dddpaul** [comment]
@bsideup Yes it's will be perfect.

**Comment by dddpaul** [comment]
@bsideup @rnorth Can I help with this issue? I can try to make #277-like PR by myself.

**Comment by bsideup** [comment]
@dddpaul Sure! Fine by me, we're always welcome any contributions :)
