### ISSUE TITLE
incorrect docker host when running docker with ssh

### ISSUE THREAD

**Issue by pcazzola** [testcontainers/testcontainers-java#2811]
I didn't see this as an existing issue.

We have used testcontainers before but we recently moved into an environment where docker was setup using ssh to connect to a docker host.

The docker client strategy resolves to this:

docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy

The docker environment variables look like this:
DOCKER_HOST=ssh://some-user@255.255.255.255
DOCKER_HOST_IP=255.255.255.255
(I've changed the actual IP address to 255 x4).

Some of the functionality works like images are downloaded and started but the docker host  seems to resolve to localhost and starting the test fails.

This issue causes can be seen when testcontainers cannot detect the container has started. 

The error message is

11:20:26.037 [main] ERROR 🐳 [mycontainer:latest] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32792] should be listening)

which shows that testcontainers is using "localhost" instead of the actual docker host.

Also, for a postgres container the "withInitScript()" function fails, but that may just because testcontainers fails to detect the container is actually running.

Since the startup failed I wasn't able to check getHost(), but it will probably incorrectly resolve to localhost.

running a "docker ps" shows the containers did start

From a quick look at the code it looks like DockerClientProviderStrategy and/or EnvironmentAndSystemPropertyClientProviderStrategy might need to be updated.

**Comment by bsideup** [comment]
@pcazzola unlike other transports, the SSH one is basically a "proxy", and needs to be supported by the client libraries.

Since we use http://github.com/docker-java/docker-java as a client, I am closing this one.
Please file an issue there. Although I cannot guarantee that it will be added anytime soon, it is a bit challenging.

Re the "localhost" observation - I believe that's something different, because it shouldn't even connect to Docker on a first place.

**Comment by pcazzola** [comment]
Thanks for the reply.  Looking at the setup more, they have a local socket mapped to the docker host /var/run/docker.sock so the docker commanding using socket works, but http needs to have the docker host.   The maven command is aliased to setup the pipe and reassign the DOCKER_HOST environment variable to the local socket so the host info is lost.

It doesn't sound like testcontainers can do much with this setup.  The only potential I can think of is to have an optional property to override the getHost() return.
