### ISSUE TITLE
Failure on executing postgresql create function on init script

### ISSUE THREAD

**Issue by cvgaviao** [testcontainers/testcontainers-java#2814]
I'm using version 1.14.2 and I'm trying to execute an initial script that contains the statement below:
```
CREATE FUNCTION common.trigger_set_audit_update ()
	RETURNS trigger
	LANGUAGE plpgsql
	VOLATILE 
	RETURNS NULL ON NULL INPUT
	SECURITY INVOKER
	COST 1
	AS $$
       BEGIN
            IF (TG_OP != 'UPDATE') THEN
                RAISE EXCEPTION 'TRIGGER : % called on unsuported op : %',TG_NAME, TG_OP;
            END IF;    
            NEW.updated_at = now(); 
            NEW.updated_by = current_user;
            RETURN NEW;
       END;

$$;
-- ddl-end --
```

```
[ERROR] ]: Script execution failed (file:/home/cvgaviao/Development/Java/C8Tech-Projects/c8tech-mmarket-backend/br.com.c8tech.mmarket.backend/src/main/resources/db/migration/V00_00_01__mmarketdb.sql:74): CREATE FUNCTION common.trigger_set_audit_update () RETURNS trigger LANGUAGE plpgsql VOLATILE RETURNS NULL ON NULL INPUT SECURITY INVOKER COST 1 AS $$ BEGIN
[ERROR]             IF (TG_OP != 'UPDATE') THEN
[ERROR]                 RAISE EXCEPTION 'TRIGGER : % called on unsuported op : %',TG_NAME, TG_OP;
[ERROR]             END IF: Unterminated dollar quote started at position 147 in SQL CREATE FUNCTION common.trigger_set_audit_update () RETURNS trigger LANGUAGE plpgsql VOLATILE RETURNS NULL ON NULL INPUT SECURITY INVOKER COST 1 AS $$ BEGIN
[ERROR]             IF (TG_OP != 'UPDATE') THEN
[ERROR]                 RAISE EXCEPTION 'TRIGGER : % called on unsuported op : %',TG_NAME, TG_OP;
[ERROR]             END IF. Expected terminating $$

```
am I missing something ?

**Comment by rnorth** [comment]
I think that when using reasonably complicated SQL scripts it goes beyond the limit of what our built-in script splitting is able to handle. We're unfortunately not able to invest in SQL splitting the can handle all DB dialects.

Can I suggest using another tool - e.g. Flyway - to apply your database schemas in this case?

I'm intending to make the documentation more clear, to the effect that the SQL init script support is for basic SQL only. Sorry if this has inconvenienced you.

**Comment by cvgaviao** [comment]
@rnorth , did you see the sql? It has 6 lines ! :D

I'm using flyway at runtime, but until now I was not able to find a way to get a postgresql container up in order to run a jooq generator at maven building.

**Comment by rnorth** [comment]
Ah OK, you probably want to read/follow this: https://github.com/jOOQ/jOOQ/issues/6551

Much as I'd love for this to be easily done it's surprisingly hard. Personally, for Gradle projects, I use https://github.com/revolut-engineering/jooq-plugin. I don't know if there's a Maven equivalent.

Re the 6 lines of SQL 😂: the challenge is to split the script into statements that the DB driver will accept. Spring's ScriptUtils (which we actually forked) just splits on `;`, but obviously that falls apart with procedures/functions. It gets worse and worse when comments (multiple styles!), string quoting, etc, and different SQL syntaxes come into play. All in all, splitting an arbitrary SQL script into statements is a hard challenge. We tried, and frankly failed, hence why I'd recommend using a specialised, dialect-aware, tool like Flyway 😄

**Comment by cvgaviao** [comment]
> Ah OK, you probably want to read/follow this: [jOOQ/jOOQ#6551](https://github.com/jOOQ/jOOQ/issues/6551)

It was exactly that page that brought me to here :D

I was able to start on testcontainer and run flyway on it. 

I used the same URL in jooq, but it seems that another container is being created. would it be possible to share the same Postgresql testcontainer between those two plugins executions (flyway and jooq) ?

**Comment by jeacott1** [comment]
@cvgaviao I did provide a pr that was rejected once upon a time that I'm pretty sure will work for you.
https://github.com/testcontainers/testcontainers-java/pull/624
