### ISSUE TITLE
Running GenericContainer with CMD isn't working properly

### ISSUE THREAD

**Issue by borisborowsky** [testcontainers/testcontainers-java#2837]
What I understand from https://www.testcontainers.org/features/commands/ the docs for creating a container with CMD is that the following command

docker container run \
   --publish 9092:9082 \
   --detach \
   --name h2 \
   nemerosa/h2

must be equivalent to 

@ClassRule
    public static GenericContainer h2db =
            new GenericContainer("nemerosa/h2")
                    .withCommand("--publish 9092:9082", "--detach", "--name lm", "nemerosa/h2")
                    .withStartupTimeout(Duration.ofSeconds(Constants.TIMEOUT_DURATION));

In test-containers. Which is not the case or I am missing something ?

**Comment by bsideup** [comment]
`publish`, `detach` and others are Docker's flags. "command" is what comes after the image (empty, in your case)

**Comment by borisborowsky** [comment]
Thank you for the verification

**Comment by borisborowsky** [comment]
Btw is there a way to use publish or detach, somehow with the library ?

**Comment by bsideup** [comment]
for publish see https://www.testcontainers.org/features/networking/#exposing-container-ports-to-the-host

detach - you don't really need it, since it is Docker CLI's feature (to start in background), while in Testcontainers everything is "started in background", if one can call it so
