### ISSUE TITLE
Can't use @Container in multiple tests classes (Spring-boot app)

### ISSUE THREAD

**Issue by borisborowsky** [testcontainers/testcontainers-java#2854]
I have the following code in two test classes in spring-boot app. When I try to run one of them I got the error "java.lang.IllegalStateException: Mapped port can only be obtained after the container is started". The strange thing is if I comment out @Container in one of the test classes the error is gone. I have tried with Junit4 and @BeforeClass annotation, it's the same issue. Do i miss something or this behaviour must be correct ? The only way I have made it working was to use singleton container which I don't want to do.

@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ActiveProfiles(Constants.DEV_PROFILE)
@DirtiesContext
@Testcontainers
public class IntegrationTest {

```
@Container
public static GenericContainer h2Database =
            new ImageFromDockerfile().withFileFromPath(".", Paths.get(Constants.H2_DOCKER_FILE))
        ).waitingFor(Wait.forListeningPort())
```

```
@Bean
public DataSource dataSource() {
            return DataSourceBuilder.create()
                    .url(JDBC_URL)
                    .username(Constants.DB_USERNAME)
                    .password(Constants.DB_PASSWORD)
                    .build();
        }
}
```

**Comment by tdanylchuk** [comment]
@igouss you may try https://github.com/testcontainers/testcontainers-spring-boot/tree/develop/embedded-redis with spring boot, should simplify your test code a bit

**Comment by ubhetwal** [comment]
I need help in setting up redis testcontainers in kotlin-spring boot application. I configured it but when I try to run   I got failed to load applicationcontext. Is there anyone who can help me?
