### ISSUE TITLE
Use a checksum of Dockerfile as a name for the resulting image

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-java#2859]
There's a functionality to create image from Dockerfile [on the fly](https://www.testcontainers.org/features/creating_images/), which is nice, but I quote:

> By default the no-args constructor will use an image name of the form testcontainers/ + random string.

Which is kind of a terrible idea. It's currently neutralized by the fact that:

> Temporary container images will be automatically removed when the test JVM shuts down. 

However why not have an option to retain that image for later re-use, if dev so desires? And while there can be an option to enable such behavior, meanwhile why not use a checksum of Dockerfile as a name for the image instead of something random. That way procedure could check if an image already exists for the given Dockerfile and re-use it, or generate fresh one if not.

**Comment by rnorth** [comment]
Uhm, the name of the image (a tag) is just a label. The layers that make up the image are already uniquely identified by SHA256 checksums based upon their content (Dockerfile plus any files that are copied in, etc).

You already can retain an image for re-use - just use the `ImageFromDockerfile(String dockerImageName, boolean deleteOnExit)` constructor and pass in a sensible name as the first parameter, and `false` as the second.

That way, _Docker_ decides whether anything needs to be rebuilt, and does so in a proven, robust way. I don't think there's anything to be gained by us adding our own checksumming on top of the existing checksumming.
