### ISSUE TITLE
Docker volumes created by TC not being removed

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#2884]
Hi, reporting what was discussed at https://testcontainers.slack.com/archives/C1SUBPZK6/p1590522616469300 about docker volumes not being cleaned on XWiki.

The issue is still present and there are hundreds more volumes added each day to your agents that are not cleaned.

Let me know if there's anything I can do to help debugging it. 

Thanks

**Comment by rnorth** [comment]
Thanks - I think we'll have some work to do to reproduce.

If anyone else has this issue, please do comment, as to our knowledge this is not a common issue.

**Comment by bsideup** [comment]
FTR I checked our self-hosted Windows node that runs hundreds of builds per week and there wasn't a single dangling volume.

@vmassol do you explicitly create volumes in your tests?

**Comment by vmassol** [comment]
@bsideup we do https://github.com/xwiki/xwiki-platform/blob/eaced75f5a08b4131e36504fb5f6c71d6b392fa8/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/AbstractContainerExecutor.java#L78

**Comment by vmassol** [comment]
@bsideup Are we supposed to clean this up?

**Comment by bsideup** [comment]
@vmassol this does not create a volume. Even `withFileSystemBind` won't.

Could you please `docker inspect` some of the dangling volumes and post it here?

**Comment by vmassol** [comment]
> Even withFileSystemBind won't.

Ok was going to ask since we use that.

> Could you please docker inspect some of the dangling volumes and post it here?

It doesn't show much:

```
docker inspect ff89704d84b5b058c20713863a768d8340a1dbadec8b3ba7a43e7bad39fd8f2c
[
    {
        "CreatedAt": "2020-06-06T03:13:48Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/home/docker/volumes/ff89704d84b5b058c20713863a768d8340a1dbadec8b3ba7a43e7bad39fd8f2c/_data",
        "Name": "ff89704d84b5b058c20713863a768d8340a1dbadec8b3ba7a43e7bad39fd8f2c",
        "Options": null,
        "Scope": "local"
    }
]
```

One thing to note and one idea: we use Jenkins with the Docker Cloud plugin which means that docker agents are provisioned as docker containers. It could be possible that it would be jenkins not cleaning the volumes I guess. It's started with 3 volumes mounted:

```
/var/run/docker.sock:/var/run/docker.sock
/home/hudsonagent/.m2/settings.xml:/root/.m2/settings.xml
/home/hudsonagent/.ssh:/tmp/xwiki/.ssh:ro
```

FTR I did a docker inspect on a running docker container for a jenkins agent to see the mounts and got:

```
       "Mounts": [
            {
                "Type": "volume",
                "Name": "245c144e6f796b4395c99444b8214e61648f01e54f05e20cf74ddf4b8c1fb581",
                "Source": "/home/docker/volumes/245c144e6f796b4395c99444b8214e61648f01e54f05e20cf74ddf4b8c1fb581/_data",
                "Destination": "/run",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "e21a54313554d2119ee597b8a14debb636f268a4df06b729d815f4c801ba2598",
                "Source": "/home/docker/volumes/e21a54313554d2119ee597b8a14debb636f268a4df06b729d815f4c801ba2598/_data",
                "Destination": "/tmp",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "82bfb31d87e6c733295cfbcd44d44abfed058f87cb450cd9725b750f7e438ca7",
                "Source": "/home/docker/volumes/82bfb31d87e6c733295cfbcd44d44abfed058f87cb450cd9725b750f7e438ca7/_data",
                "Destination": "/var/run",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/hudsonagent/.m2/settings.xml",
                "Destination": "/root/.m2/settings.xml",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/hudsonagent/.ssh",
                "Destination": "/tmp/xwiki/.ssh",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "536e47d8e18cb16cbdd68d96c5eaacf874dc0508bec119c38620614783c5cdc6",
                "Source": "/home/docker/volumes/536e47d8e18cb16cbdd68d96c5eaacf874dc0508bec119c38620614783c5cdc6/_data",
                "Destination": "/home/jenkins",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

So the question now is to try to find to what docker container the dangling volumes belonged to I guess. 

Thx

**Comment by bsideup** [comment]
@vmassol we assign `org.testcontainers=true` volume to the containers we create, which should also assign it to the volumes.
`"Labels": null,` makes me think that your problem is completely unrelated to Testcontainers.

**Comment by vmassol** [comment]
@bsideup yes I agree. Sorry for this false alarm. It seems the issue is with Jenkins and not TC. I have just found that Jenkins has an option to remove volumes that is off by default. Will try it.
