### ISSUE TITLE
withMemory method of CreateContainerCmd deprecated

### ISSUE THREAD

**Issue by pmpred** [testcontainers/testcontainers-java#2887]
Hi,

I try to limit the memory use by the container I want to launch following this url : https://www.testcontainers.org/features/advanced_options/

`val container = new ElasticsearchContainer("elastic/elasticsearch:7.7.0") // for icu related plugins
        .withCreateContainerCmdModifier(
          new Consumer[CreateContainerCmd]() {
            override def accept(t: CreateContainerCmd): Unit = {
              t.withMemory(400 * 1024 * 1024.toLong) //400mb
            }
          }
        )`

It works but the.withMemory method is deprecated. Is any change to solve this is planned ?
Many thanks

**Comment by bsideup** [comment]
This is `docker-java`'s method. See https://github.com/docker-java/docker-java/issues/1281
