### ISSUE TITLE
Database container checkpoint/restore

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#29]
Some projects have complex test data that is time consuming to reload. This means that either testing takes a very long time (test data has to be reloaded often), or tests aren't sufficiently independent (test data is not reloaded and therefore tests aren't independent). Testcontainers should provide a way to snapshot DB state and quickly reload that state. Docker [native Checkpoint/Restore In Userspace](http://blog.kubernetes.io/2015/07/how-did-quake-demo-from-dockercon-work.html) looks like the best way to accomplish this.

Follow this PR:
https://github.com/docker/docker/pull/13602

**Comment by bsideup** [comment]
Since 1.13 will have production-ready checkpoint/restore, we might try to integrate it (ofc after docker-java)

**Comment by andersonkyle** [comment]
I would love to see support for this.  Has there been any progress lately?

**Comment by kiview** [comment]
Right now quite unlikely, since we are unsure if this Docker will come to all supported platforms. 
Here is a more recent discussion:
https://github.com/moby/moby/issues/20300

**Comment by mpfz0r** [comment]
Just wondering if any of the mentioned restrictions have changed by now.
It would be great to have docker checkpoint support.
