### ISSUE TITLE
Docker for Windows support

### ISSUE THREAD

**Issue by Villane** [testcontainers/testcontainers-java#291]
Would be nice to get support for Docker for Windows.

I switched to Docker for Windows recently, and now I can't run our testcontainers tests locally, because it seems one can't use VirtualBox and Hyper-V at the same time for Docker on Windows 10.

**Comment by kiview** [comment]
I think the underlying [docker-java](https://github.com/docker-java/docker-java) library provided basic support for Windows by specifying `DOCKER_HOST=tcp://127.0.0.1:2376`, not a smooth experience, but it worked.

Maybe this setup is simply not considered a valid environment when determining the strategy, although it might work in theory?

**Comment by bsideup** [comment]
@kiview did you try tcp? How is it so far?

**Comment by kiview** [comment]
It works fine with the docker-java client, but testcontainers doesn't recognize the environment based of this parameters it seems.

**Comment by bsideup** [comment]
@kiview ok, cool. @Villane is sitting next to me, I'll try to fix TestContainers on his machine then :) Or did you plan to contribute Docker for Windows support? I got lost a bit :)

**Comment by kiview** [comment]
@bsideup yes, I was indeed planning to help with Docker for Windows support, but that's not high on my priority list right now, since we are using Linux after all. I just think this shouldn't be too hard, since there are already valid workarounds regarding docker-java and docker-groovy of how to achieve this.

**Comment by Villane** [comment]
Generally seems to work with this PR https://github.com/testcontainers/testcontainers-java/pull/297

Getting some connection errors in our tests, but this might be on our side.
