### ISSUE TITLE
How to wait for container exit?

### ISSUE THREAD

**Issue by Sammers21** [testcontainers/testcontainers-java#2917]
There is no strategy for that at the moment.

**Comment by vcvitaly** [comment]
Have you tried _Indefinite one-shot startup strategy_? That's what you want if I understood correctly.

https://www.testcontainers.org/features/startup_and_waits/

**Comment by bsideup** [comment]
@Sammers21 we only have startup & wait strategies. You can inspect the container's state and wait for it to exit.

**Comment by bernhof** [comment]
Stumbled across this today, and just wanted to add that `OneShotStartupCheckStrategy` is not applicable out of the box with `DockerComposeContainer`, which only supports `WaitStrategy` via `DockerComposeContainer.waitingFor`.

We solved this by wrapping the `OneShotStartupCheckStrategy` in a new `WaitStrategy`:

    class OneShotStartupWaitStrategy extends AbstractWaitStrategy {

        @Override
        protected void waitUntilReady() {
            if (!new OneShotStartupCheckStrategy().waitUntilStartupSuccessful(waitStrategyTarget.dockerClient, waitStrategyTarget.containerId)) {
                // throw an exception to indicate failure
            }
        }
