### ISSUE TITLE
Jenkins passing docker.sock to Docker Build Container spawning sibling (test)containers 

### ISSUE THREAD

**Issue by Ordiel** [testcontainers/testcontainers-java#2946]
As the title reads, I am trying to get a Docker container that is used by Jenkins as a build node to run a java maven project using testcontainers to spawn a mysql DB, in order to get a functional docker environment to the container besides installing the cli, I am passing the socket and indicating the container the correct user and group to run as so that it does not conflict the permissions of the host docker socket. I have tested the socket is passed correctly within my Jenkins build by running `docker ps` and observing the desired output showing the host running containers (so the issue does not seem to be there). I was reading the following issues:

* https://github.com/testcontainers/testcontainers-java/issues/572
* https://github.com/testcontainers/testcontainers-java/issues/1274

since the symptoms were similar; I am either:

1) Unable to connect to ryuk using the conf described above:

       java.lang.IllegalStateException: Can not connect to Ryuk
         at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:150)
         at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:131)
         at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:175)
         at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:36)
         at org.testcontainers.containers.MySQLContainer.<init>(MySQLContainer.java:29)

2) Apparently testcontainers depends on the TCP port (2375) to be exposed, after checking it is and port is correct on `/etc/systemd/system/docker.service.d/override.conf` on the host, I get my container hanging indefinitely performing anything (in my case creating a dir) when setting `DOCKER_HOST=<HOST_IP>:2375`. I also tried binding the port by adding `args '-p 2375:2375 ...` but it obviously didn't work since the port is already in use.

Do you have any ideas/suggestions on how can I overcome this blocker?

Here is how I am passing the socket

**Jenkinsfile passing sock**

    pipeline {
      agent {
        dockerfile {
          args '-v /var/run/docker.sock:/var/run/docker.sock -u <User ID>:<Group ID>'
          ...

**Comment by Ordiel** [comment]
Nevermind I managed to overcome it usng `--network host` to my args

**Comment by wkurosawa** [comment]
@Ordiel , you saved my life sir. I've been having a similar problem running testcontainers inside Jenkins using the Docker agent and I spent days to get it working. Thanks to your commented solution! 

It seems that there is already PR to address network problems in Jenkins, but again, thanks for your comment.
