### ISSUE TITLE
Spock @TestContainers missing inherited

### ISSUE THREAD

**Issue by tlefevre** [testcontainers/testcontainers-java#2968]
I see this has been fixed in one of the other modules, but the Spock module could use an upgrade along these same lines:

Juniper version:
https://github.com/testcontainers/testcontainers-java/blob/master/modules/junit-jupiter/src/main/java/org/testcontainers/junit/jupiter/Testcontainers.java

Spock version:
https://github.com/testcontainers/testcontainers-java/blob/master/modules/spock/src/main/groovy/org/testcontainers/spock/Testcontainers.groovy

**Comment by tlefevre** [comment]
Ping?

**Comment by tlefevre** [comment]
Still relevant.

**Comment by tlefevre** [comment]
See: https://github.com/testcontainers/testcontainers-java/pull/4053

**Comment by eddumelendez** [comment]
#4053 merged and it's available since 1.16.0
