### ISSUE TITLE
Is there a way to set the memory capacity for a `GenericContainer`?

### ISSUE THREAD

**Issue by macks22** [testcontainers/testcontainers-java#298]
I have the following `GenericContainer`:

```
/**
 * A docker container that can be used with an @ClassRule to start the container before
 * and tear it down after a test class. This container exposes port 9200 as 9201 and port 9300 as 9301.
 * It also copies over the elasticsearch.yml file from the test resources.
 */
public class ElasticsearchTestContainer extends GenericContainer {

    private static final ImageFromDockerfile IMAGE_FROM_DOCKERFILE =
            new ImageFromDockerfile("test-es-image", false)
                    .withDockerfileFromBuilder(builder -> builder
                            .from("elasticsearch:2.2")
                            .run("/usr/share/elasticsearch/bin/plugin install analysis-icu")
                            .run("/usr/share/elasticsearch/bin/plugin install delete-by-query")
                            .copy("elasticsearch.yml", "/usr/share/elasticsearch/config/elasticsearch.yml")
                            .build()
                    ).withFileFromClasspath("elasticsearch.yml", "docker/elasticsearch.yml");

    public ElasticsearchTestContainer() {
        super(IMAGE_FROM_DOCKERFILE);
        this.setPortBindings(Arrays.asList("9201:9200", "9301:9300"));
        this.setNetworkMode("devhost.hostname.com");
        this.setWaitStrategy(Wait.forHttp("/"));
    }
}
```

Normally, I would specify the memory using the `-m` flag to docker. How can I do this with this container?

**Comment by kiview** [comment]
So you want to set a memory limit? AFAIK testcontainers doesn't expose an API for this yet.

I also only found a fitting API in docker-java inside the [UpdateContainerCmd](https://github.com/docker-java/docker-java/blob/419900d074e6d9754dcd5c6290d93c3350bab010/src/main/java/com/github/dockerjava/api/command/UpdateContainerCmd.java) class, not inside `CreateContainerCmd`.

**Comment by benhinssen** [comment]
+1
I was also looking for this feature.

**Comment by kiview** [comment]
@benhinssen could you please give some context for use cases for which this feature is needed?

**Comment by rnorth** [comment]
It looks like [it's there](https://github.com/docker-java/docker-java/blob/419900d074e6d9754dcd5c6290d93c3350bab010/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java#L355) on CreateContainerCmd. It's worth supporting, but we might be opening a can of worms if we add this directly to the GenericContainer API.

Perhaps the more maintainable approach is to use some upcoming preconfig/postconfig hooks that @bsideup was working on that allow you to modify the CreateContainerCmd directly before it's created. How does that sound?

**Comment by bsideup** [comment]
+1 from me on hooks :)

Something like:
```java
new GenericContainer(...)
    .withCreateCmdHook(cmd -> cmd.withMemory(1024))
```

(naming is not final)

**Comment by benhinssen** [comment]
@kiview of course.
In our development build, we use testcontainers to simulate our production environment to run E2E tests.   So during our build testcontainers spins up about 10 docker images that must be tested together.

At this moment we are having some problems that our build server is running out of resources when running multiple builds simultaneously.  The obvious way to prevent this from happening is to limit the max resources that can be used by each docker container.
We have all the docker images that are being started on our build server limited, except the ones the are spun up by testcontainers.  We can also limit it using parameter of the java process inside the docker testcontainer, but it would be nice to be able to limit cpu usage when starting the container.

**Comment by bsideup** [comment]
See https://github.com/testcontainers/testcontainers-java/pull/301

**Comment by bsideup** [comment]
@macks22 @benhinssen since 1.2.0 is out, does https://www.testcontainers.org/usage/options.html#customizing-the-container sounds good enough for you? :)

**Comment by macks22** [comment]
@bsideup yes this meets the need; thank you! @benhinssen feel free to close if your use case is satisfied.

**Comment by benhinssen** [comment]
Looks good and fits the requirement!  Thanks!

**Comment by rnorth** [comment]
Great, thanks @benhinssen, @macks22!

I'll close the ticket then 😄
