### ISSUE TITLE
Containers started with withReuse(true) are killed when the JVM exits abruptly

### ISSUE THREAD

**Issue by aaronjwhiteside** [testcontainers/testcontainers-java#2986]
I start my containers from Spring Cloud @BootstrapConfiguration classes

When there is some bean/applicationcontext error and the JVM exists abruptly, any containers started before this point are killed. The withReuse(true) seems to be completely ignored...

If there is no bean/applicationcontext issue and the Spring Boot application starts sucessfully and I gracefully exit it, then the containers stay running. And are happily reused next time I start the Spring Boot application.

Any ideas on what might be going on?

P.S.

Interesting tidbit, if I debug the Spring Boot application and set a breakpoint before the application receives an error and then terminate the application from intellij, the containers stay running..

**Comment by bsideup** [comment]
@aaronjwhiteside the behaviour you described usually means that you `stop()` the container somewhere in your code. Calling `stop()` on a reusable container is valid, behaves the same as with regular containers and means "I don't need it anymore".

The easiest would be to override container's `stop()` method and check who is calling it.

**Comment by aaronjwhiteside** [comment]
thanks @bsideup, it was indeed that sometimes stop() was called on some containers and other times not.. due to https://github.com/spring-cloud/spring-cloud-commons/issues/752

I have another questions, under what concumstances does the container reaper ryuk reap containers? I haven't been able to find good documentation on it on the testcontainers.org site.. And in my experience sometimes it seems to reap the contiainers as expected other times it does not..

**Comment by bsideup** [comment]
@aaronjwhiteside it should reap them unconditionally after the testing session. See https://github.com/testcontainers/moby-ryuk

Have you observed "dangling" containers?
