### ISSUE TITLE
Can't set startupTimeout

### ISSUE THREAD

**Issue by ikosarim** [testcontainers/testcontainers-java#2990]
In my tests I use org.testcontainers.containers.PostgreSQLContainer. I have docker postgres image which starts in 1 minute and 20 seconds. And I can't run tests because in default LogMessageWaitStrategy.waitUntilReady() I have default timeout 1 minute. 
I try to override startupTimeout with help .withStartupTimeout(Duration.ofSeconds(120)) in builder of PostgreSQLContainer, but it use constructor value - Duration.of(60, SECONDS).
I can resolve it issue by this method:
.waitingFor(
                              new LogMessageWaitStrategy()
                                      .withRegEx(".*database system is ready to accept connections.*\\s")
                                      .withTimes(2)
                                      .withStartupTimeout(Duration.of(120, SECONDS))
                      )
but it is strange that I need to override the strategy in order to set a new value of startupTimeout. Moreover, there is a method that should do this.
version - 1.14.3
P.S. Also it it would be cool if it were possible to set this value through the constructor.

**Comment by vcvitaly** [comment]
@ikosarim 

 .withStartupTimeout() overrides the value after the construction of an object, it's not a builder pattern but a [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface).

**Comment by ikosarim** [comment]
Okey, I understood.

**Comment by eddumelendez** [comment]
This should work as mentioned by @vcvitaly
