### ISSUE TITLE
Attach to StdIn

### ISSUE THREAD

**Issue by rdoepke** [testcontainers/testcontainers-java#3000]
Hi everyone,

i am currently working on performing integration tests using an OpenSSL container. Therefore, i have to perform a "s_client" connect, wait for the connection to be established reading the log, and then send my plain commands via StdIn.

I've already managed to get this working using plain "docker-java" and Apache HttpClient 5. However, I would like to use the testcontainers API as far as possible. Unfortunately, there is no way to "attach" to a running container by API. I therefore decided to do retrieve the dockerclient from the container and reuse the code from my (working but dirty) docker-java test case:

```
GenericContainer<?> openssl = new GenericContainer<>("frapsoft/openssl").withCommand("s_client", ...);
openssl.start();

// ...

// After having successfully waited for the connection here my stdin commands shortened for minimal example
String ehlo = "EHLO localhost";
InputStream commands = new ByteArrayInputStream(ehlo.getBytes(StandardCharsets.UTF_8));
AttachContainerCmd attachContainerCmd = openssl.getDockerClient()
            .attachContainerCmd(openssl.getContainerId())
            .withStdIn(commands)
            .withStdOut(true)
            .withStdErr(true)
            .withFollowStream(true);
// Stripped creation of logging callback here
attachContainerCmd.exec(resultCallback);
```

However, the commands seem not be be passed to my container as nothing happens after execution. Am I doing something wrong or is it simply not possible due to used client of testcontainers?

Thanks and best regards,
Roland

**Comment by bsideup** [comment]
@rdoepke consider starting a container with a dummy command and using `execInContainer` (or `exec{Create,Start}Cmd`)

**Comment by rdoepke** [comment]
Wow, fast reaction :+1: 

I've already tinked with execInContainer. However, i cannot manage to get this working with a "oneshot" command, as I have to wait for successful (mail-)connection and then send my commands to the connected machine. Reconnecting to the execInContainer is not possible to my understanding.
