### ISSUE TITLE
Add logstash module

### ISSUE THREAD

**Issue by yevtsy** [testcontainers/testcontainers-java#3012]
I want to have the ability to use [Logstash docker](https://hub.docker.com/_/logstash) image in the container for test purposes. 
The use case is to test Kafka -> Logstash -> Elastic configuration

**Comment by vcvitaly** [comment]
@yevtsy You can use any image with a `GenericContainer`, would something like this work for you? I do not imply here that a separate module is not required, but such decision is up to maintainers.

**Comment by yevtsy** [comment]
The reason for this feature request is to be able to use it later in the project https://github.com/testcontainers/testcontainers-spring-boot. See the example issue: https://github.com/testcontainers/testcontainers-spring-boot/issues/278

It will allow to easily auto-configure logstash for testing in spring-boot-based projects
