### ISSUE TITLE
Exposing a random port which is the same on the host and container?

### ISSUE THREAD

**Issue by vab2048** [testcontainers/testcontainers-java#3020]
I am trying to allow for VisualVM to connect to running containers from testcontainers whilst debugging. 

Unfortunately the host ->container port mapping must be the same port. 

From https://forums.docker.com/t/exposing-mapped-jmx-ports-from-multiple-containers/5287:

> You should be aware that JMX over RNI is communicating its host and port in the protocol. So when you map a port to your host you must set het jmx_server to the host and the port to the mapped port. And the port of jmx should be exactly the same as the jmx port. -p 1099:2099 is not going to work.

This makes it problematic for me to create containers using testcontainers unless we use fixed exposed ports. But I do not care particularly that the host and container port be fixed to something I only care that they are the same (so test containers could randomly select 32785 but it would be mapped to 32785 in the container too).

What would be the best way to do this?

**Comment by bsideup** [comment]
@vab2048 have a look at https://github.com/testcontainers/testcontainers-java/pull/2192#issuecomment-567909070
