### ISSUE TITLE
Document any situations where the TC JDBC driver needs to be explicitly configured

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#305]
#304 covered a case where this needs to be done for Spring Boot.
Are there any other cases where the developer has to manually select the TC JDBC driver for driver-based testing?

**Comment by bsideup** [comment]
@rnorth shall we close it after 1 year of inactivity? :D

**Comment by kiview** [comment]
I think we will find other examples once a problem occurs in real life usage, so it should be okay to close this^^
