### ISSUE TITLE
Running different version of elasticsearch

### ISSUE THREAD

**Issue by ykoasanto** [testcontainers/testcontainers-java#3051]
Is there a way to run elasticsearch module with a different version than the one hardcoded in the `ElasticsearchContainer.java`? I can fork the branch and change it, but it would be nice if there is a way to change it dynamically? May be can be passed in as an annotation argument from the test class?

**Comment by raynigon** [comment]
See https://github.com/testcontainers/testcontainers-java/blob/master/modules/elasticsearch/src/test/java/org/testcontainers/elasticsearch/ElasticsearchContainerTest.java#L87

Simply use the constructor and pass the image with the version you want

**Comment by rnorth** [comment]
Thanks for answering @raynigon - that's the answer!

**Comment by ykoasanto** [comment]
Thanks @raynigon! Somehow missed that one constructor... I am all set
