### ISSUE TITLE
Why is the reuse property only evaluated from the environment properties and not additionally from the classpath file

### ISSUE THREAD

**Issue by Chr3is** [testcontainers/testcontainers-java#3056]
In `org.testcontainers.utility.TestContainersConfiguration#environmentSupportsReuse` the environment properties (.testcontainer.properties in user's home directory) are used for the evaluation of `testcontainers.reuse.enable` . Why don't we use the merged properties from environment AND `testcontainers.properties` from classpath (https://www.testcontainers.org/features/configuration/)

Version: 1.14.3

**Comment by bsideup** [comment]
See #1781 (comment)
