### ISSUE TITLE
How to properly setup singleton container with flyway?

### ISSUE THREAD

**Issue by marcelomorgado** [testcontainers/testcontainers-java#3058]
Hi there,

I have a question about that, The container itself (startup/destruction) is running with great performance among test cases but in my case, I have to prepare the DB with migrations scripts before be able to run each test case and it's slowing me down a bit. I want to have DB cleaned (new container+fresh migrations) before each test case to keep them isolated. Is there a way to run flyway migrations once?

Here my super class code:

```kotlin
@Testcontainers
open class RepositoryTest {

    private val POSTGRES_IMAGE = "postgres:10.3"
    private val DB_NAME = "..."
    private val DB_USER = "..."
    private val DB_PASS = "..."

    private val INIT_SCRIPT = "init.sql"

    private var ctx : DSLContext? = null

    private fun startPostgresSQL(): PostgreSQLContainer<Nothing> {
        val postgres = PostgreSQLContainer<Nothing>(POSTGRES_IMAGE).apply {
            withDatabaseName(DB_NAME)
            withUsername(DB_USER)
            withPassword(DB_PASS)
            withInitScript(INIT_SCRIPT)
        }
        postgres.start()
        return postgres
    }

    private fun runMigrations(jdbcUrl : String) {
        Flyway.configure().dataSource(jdbcUrl, DB_USER, DB_PASS).load().migrate()
    }

    fun getDSLContext(): DSLContext {
        return ctx!!
    }

    @BeforeEach
    fun setUp() {

        val postgres = startPostgresSQL()
        runMigrations(postgres.jdbcUrl)

        ctx = DSL.using(postgres.jdbcUrl, DB_USER, DB_PASS)
    }
}
```

Thanks!

**Comment by marcelomorgado** [comment]
An update here, I've tried to append all my migration scripts to the `init.sql` script to get it executed once but I've same the same issue as https://github.com/testcontainers/testcontainers-java/issues/2814#issuecomment-635914455

**Comment by vcvitaly** [comment]
@marcelomorgado 
It's possible to create a static field with a container in a super class and it will be loaded only once for all tests.
After that you can just perform a clean up after each test case without recreating the whole schema.

Is that something you were looking for?

**Comment by marcelomorgado** [comment]
Hmmm, I wouldn't like to do so to avoid having to write clean up code. I was looking for a way to optimize the execution a bit more, actually, the time that it's taking isn't too bad.
