### ISSUE TITLE
Include name of service (which is failed to start within timeout) in the error message 

### ISSUE THREAD

**Issue by vipulnewaskar7** [testcontainers/testcontainers-java#3059]
When service (say my-service) running on original port 80 mapped with 32803 port fails to start, testcontainer throws below error :

> Caused by: org.testcontainers.containers.**ContainerLaunchException**: Timed out waiting for URL to be accessible (http://localhost:32803/ should return HTTP 200)

Since 32803 port is assigned by TestContainers, the end-user is unaware of that and may not be meaningful for him.
We should return the service name (i.e my-service) in addition to the original error message??

**Comment by vcvitaly** [comment]
**Testcontainers** usually includes container name in log messages, for ex:
`17:02:45.399 INFO    [mysql:5.7.22]`

If an error is logged, you should see such message above. Is that what you meant?
