### ISSUE TITLE
Handle the interdependency among the containers

### ISSUE THREAD

**Issue by vipulnewaskar7** [testcontainers/testcontainers-java#3060]
Containers in DockerComposeContainers should start only after the "parent" container is started.
e.g. 
containers A and B
B depends on A
Though the docker-compose file contains the "depends_on" feature, it's not sufficient because B does not wait until A is up.
But we can bring this feature to TestContainers.
We can use WaitStrategy itself

**Comment by bsideup** [comment]
We can't intercept Docker Compose's start process, it is a black box.

If you want more features (such as waiting for the wait strategies), consider using `GenericContainer` and `Network` instead of Docker Compose.
