### ISSUE TITLE
getHost() not returning the good IP

### ISSUE THREAD

**Issue by RemiBou** [testcontainers/testcontainers-java#3080]
Hi,

I have this Jenkins setup where my build are executed in docker (locally everything is fine). When I get the ip address of my container I get "172.17.0.1" which results in connection error.

If I execute docker commands when the startup check is running I get

> 2020-08-06T08:11:21.800 [INFO ] [                ] [:46] [main                ] - DOCKER PS
> 2020-08-06T08:11:22.044 [INFO ] [                ] [:107] [main                ] - CONTAINER ID        IMAGE                                         COMMAND                   CREATED              STATUS                  PORTS                                              NAMES
> 2020-08-06T08:11:22.045 [INFO ] [                ] [:107] [main                ] - b39e1f75339c        XXX   "/YYY"    26 seconds ago       Up Less than a second   0.0.0.0:32776->8081/tcp, 0.0.0.0:60671->8082/tcp   pedantic_satoshi
> 2020-08-06T08:11:22.045 [INFO ] [                ] [:107] [main                ] - 1eb2c53ddeef        testcontainersofficial/sshd:1.0.0             "sh -c 'echo \"root:$XXX"   About a minute ago   Up About a minute       0.0.0.0:32775->22/tcp                              thirsty_cohen
> 2020-08-06T08:11:22.045 [INFO ] [                ] [:107] [main                ] - 1d678edfe008        testcontainersofficial/ryuk:0.3.0             "/app"                    About a minute ago   Up About a minute       0.0.0.0:32774->8080/tcp                            testcontainers-ryuk-a104bb7e-f71c-4e23-90cc-85db631ca292
> 2020-08-06T08:11:22.050 [INFO ] [                ] [:48] [main                ] - DOCKER IPs
> 2020-08-06T08:11:22.322 [INFO ] [                ] [:107] [main                ] - 172.17.0.4 pedantic_satoshi
> 2020-08-06T08:11:22.322 [INFO ] [                ] [:107] [main                ] - 172.17.0.3 thirsty_cohen
> 2020-08-06T08:11:22.322 [INFO ] [                ] [:107] [main                ] - 172.17.0.2 testcontainers-ryuk-a104bb7e-f71c-4e23-90cc-85db631ca292

From this information it seems that the IP "172.17.0.4" would be better right ?

**Comment by bsideup** [comment]
@RemiBou `getHost` returns the host on which the containers are _exposed_ (usually with random ports), not the container's host. `172.17.0.1` should be correct here, as long as you're using the mapped port values and your firewall is configured correctly and allows traffic from containers to the host.
