### ISSUE TITLE
ImageFromDockerfile: Pass through build logs

### ISSUE THREAD

**Issue by twoodhouse** [testcontainers/testcontainers-java#3093]
Currently, when using ImageFromDockerfile, it is possible to see log messages about which line in the dockerfile is failing, but that appears to be all. There is no way to output the actual logs that occur when running the docker build.

My team's use-case, however, requires that we see all logs output during the docker build process within testcontainers.

Is there a way to do this? If not, is this a feature that could be pursued?

**Comment by twoodhouse** [comment]
This seems similar to the request here, but it was never resolved: https://github.com/testcontainers/testcontainers-java/issues/2629

**Comment by guss77** [comment]
@twoodhouse - did you ever manage to resolve this issue?

**Comment by guss77** [comment]
Upon further investigation, setting the system property
`org.slf4j.simpleLogger.log.com.github.dockerjava.api.command.BuildImageResultCallback` to `debug` solved the problem for me.

**Comment by Jozott00** [comment]
I think @guss77 is referring to 
https://github.com/testcontainers/testcontainers-java/blob/751aa4eee75aa135d365647d8b0b32347f98151d/core/src/main/java/org/testcontainers/images/builder/ImageFromDockerfile.java#L104-L115
So setting the log level of the `com.github.dockerjava.api.command.BuildImageResultCallback` class to `DEBUG` will print the `BuildResponseItem‎`'s stream output from the image build process. 

Unfortunately, this just prints a bunch of 
```
[docker-java-stream--733698671] DEBUG c.g.d.a.c.BuildImageResultCallback - BuildResponseItem()
``` 
in the console (at least in my case).  

Having such a feature is still pretty relevant, in my opinion.
