### ISSUE TITLE
Image Pulled, Container doesn't start

### ISSUE THREAD

**Issue by LiamMaru** [testcontainers/testcontainers-java#310]
Love the sound of this tool but I can't get it to work. Given the following test:
```
public class ApnicLdapStorageProviderTestIT extends TestCase {

    @ClassRule
    public static GenericContainer redis =
        new GenericContainer("redis:3.0.2")
                .withExposedPorts(6379);
    
    @Test
    public void testSomething() throws Exception {
        String addr = String.format("%s:%s", redis.getContainerIpAddress(), redis.getMappedPort(6379));
        assertTrue(!addr.equals("not this"));
    }       
}
```

I receive receive: 

```
testSomething(org.apnic.keycloak.ApnicLdapStorageProviderTestIT)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.apnic.keycloak.ApnicLdapStorageProviderTestIT.testSomething(ApnicLdapStorageProviderTestIT.java:24)
```

The image is being pulled but not run. Any ideas?

**Comment by bsideup** [comment]
> extends TestCase

Are you sure you use JUnit 4?

**Comment by LiamMaru** [comment]
@bsideup

Yes, version 4.1.2.

**Comment by bsideup** [comment]
@LiamMaru may I ask you to provide a full log?

**Comment by rnorth** [comment]
I was going to ask the same thing. I'm also wondering, perhaps, if there could be a dependency clash (i.e. more than one JUnit JAR on the classpath).

**Comment by rnorth** [comment]
@LiamMaru did you manage to get any further with this? Please let us know if we can help.

**Comment by LiamMaru** [comment]
Hey @rnorth, apologies re. delay. I've had a further look into this and there doesn't *appear* to be a dependency clash. I'll investigate this further and get back to you all soon.

**Comment by rnorth** [comment]
Great! Glad to hear you were able to solve it. I'll close this ticket then.
