### ISSUE TITLE
Start container with hostname

### ISSUE THREAD

**Issue by rahul-swaminathan** [testcontainers/testcontainers-java#311]
We are using GenericContainer and we need to set a specific hostname for our container. Right now, we are using `withExtraHosts` and hardcoding the ip address that the container always starts with. This creates 2 entries in `/etc/hosts` with the same ip address. We'd rather have a function `withHostName` that leverages 
```
dockerClient.createContainerCmd().withHostName
```

**Comment by rnorth** [comment]
Hi Rahul
Thanks for using Testcontainers and for raising this - seems perfectly sensible to me and isn't a big change. We can probably do this quickly. However, if it's urgent, if you'd care to raise a PR we'd be able to include this even sooner!
Thanks
Richard

**Comment by bsideup** [comment]
FYI this PR will make it possible to configure hostname manually:
https://github.com/testcontainers/testcontainers-java/pull/301

**Comment by rnorth** [comment]
@bsideup yes, you're right!

**Comment by rahul-swaminathan** [comment]
awesome, thanks!

**Comment by bsideup** [comment]
@rahul-swaminathan version 1.2.0 was released, you can find how to tune CreateContainerCmd in the docs now:
https://www.testcontainers.org/usage/options.html#customizing-the-container

Do you still want it implemented as `container.withHostName()`? If not, I assume we can close this issue for now :)

**Comment by edgarvonk** [comment]
Hi all, the CreateContainerCmd works fine with the GenericContainer (in our case we use it to set the name of the container upon creation). However I think it is not supported for the JdbcDatabaseContainers? We would like to use the CreateContainerCmd with e.g. the OracleContainer.

**Comment by edgarvonk** [comment]
Ah sorry, it is possible with a JdbcDatabaseContainer as well. Just a little bit more cumbersome. E.g.:

```
   @ClassRule
    public static GenericContainer oracleContainer = new OracleContainer()
        .withCreateContainerCmdModifier((Object createContainerCmd) -> {
            ((CreateContainerCmd)createContainerCmd).withName("oracle");
        });
```

**Comment by bsideup** [comment]
@edgarvonk 

or 
```java
    @ClassRule
    public static GenericContainer oracleContainer = new OracleContainer<>()
        .withCreateContainerCmdModifier(it -> it.withName("oracle"));
```

(note the diamond <> )

**Comment by edgarvonk** [comment]
Hi @bsideup, I did try that but that is not possible because OracleContainer is not a parameterised type (in contrast to GenericContainer)? This code does not compile for me anyway.

**Comment by bsideup** [comment]
@edgarvonk,

hm-hm... Does it happen if you change `GenericContainer oracleContainer` to `OracleContainer  oracleContainer`? without <>

Sorry for that anyway, we're going to polish generics in 2.0

**Comment by edgarvonk** [comment]
hi @bsideup, no it happens regardless of whether I use GenericContainer or OracleContainer as the variable type. 

No problem at all!

**Comment by rahul-swaminathan** [comment]
@bsideup yup, we switched over to using `withCreateContainerCmdModifier` and everything works great, thanks!

**Comment by bsideup** [comment]
Awesome! I'm closing the issue :)
