### ISSUE TITLE
dockerClientStrategyClassName cannot be set from env/system variable

### ISSUE THREAD

**Issue by bedla** [testcontainers/testcontainers-java#3124]
Hi,
I found that `docker.client.strategy` can be set only by `.testcointaners.properties` file. For my usecase (setting it as system property during surefire configuration) I would prefer to be able to set it by environment variable or system property.
Is it intened behavior?
Thx,
Ivos

**Comment by bsideup** [comment]
Hi @bedla,

This property is set by Testcontainers itself and is used as a "cache" value. It is not intended to be set by the end user.
Why do you need to force some value?

**Comment by bedla** [comment]
I want to have deterministic configuration (customized by same ENV variables) for local development and when run on CI. This means that I want configuration for `DOCKER_HOST`.
