### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by wlad** [testcontainers/testcontainers-java#3129]
here https://www.testcontainers.org/supported_docker_environment/

![image](https://user-images.githubusercontent.com/64201310/90722993-2de60600-e2bc-11ea-957b-4eeaa4dcc81f.png)

**Comment by wlad** [comment]
this may be helpful for anybody who tries to open the broken link

https://github.com/testcontainers/testcontainers-java/blob/master/docs/supported_docker_environment/continuous_integration/circle_ci.md

**Comment by bsideup** [comment]
Hey @wlad,

I just marked the issue as "good first issue" in case someone is looking to contribute to the project.

**Comment by wpanas** [comment]
Hi @bsideup, I can take this one!

**Comment by wpanas** [comment]
This issue can be closed

**Comment by wlad** [comment]
@wpanas thank you ❤️ 

FYI: If you use special keywords like `fixes [link to issue]` (i.e. fixes https://github.com/testcontainers/testcontainers-java/issues/3129) in your PR description when the related issue is closed automatically when your PR is accepted and merged.

check [this ](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)for more details

other special keywords are:

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

**Comment by wpanas** [comment]
@wlad thanks for feedback 👍
