### ISSUE TITLE
Bouncycastle (and others) twice in jdbc artifact

### ISSUE THREAD

**Issue by kaiwinter** [testcontainers/testcontainers-java#316]
One of my tests doesn't run with testcontainers > 1.1.1 because of a bouncycastle class which comes with testcontainers and is used instead of the class from my application code.

I guess the use of maven-shade-plugin should prevent me from this problem. But when I look into the `jdbc-1.2.0.jar` I find bouncycastle two times in it:
- `jdbc-1.2.0.jar\org\testcontainers\shaded\org\bouncycastle\`
- `jdbc-1.2.0.jar\org\bouncycastle\`

This `jdbc-1.2.0.jar` gets generated when I run a `mvn clean install` from testcontainer root. But when I call `mvn clean install` from /modules/jdbc I get a `jdbc-1.2.0.jar` which does not have `jdbc-1.2.0.jar\org\bouncycastle\`. Further the following paths are missing:
- `com/github/dockerjava`
- `io/netty`
- `javax/annotation`
- `org/apache/http`

but they are still at `jdbc-1.2.0.jar\org\testcontainers\shaded\`. I guess this is what is expected. Currently I'm not sure what causes this different behavior or how to fix this. Maybe filtering/excluding the packages in the `jdbc/pom.xml`?
```
<filter>
   <artifact>org.bouncycastle:*</artifact>
   <excludes>
      <exclude>**</exclude>
   </excludes>
</filter>
```

**Comment by bsideup** [comment]
Fixed long time ago
