### ISSUE TITLE
Add a property for Localstack SQS queue prefix

### ISSUE THREAD

**Issue by raulvc** [testcontainers/testcontainers-java#3178]
I just spent a few hours trying to work around a misleading error saying a SQS consume request was wrong
 when actually it was a `/queue` missing from localstack endpoint:

```
new LocalStackContainer().getEndpointOverride(SQS) + "/queue"
```

**Comment by vcvitaly** [comment]
@raulvc Testcontainers contains modules contributed by different people, so it's better to describe the context, ie what the endpoint was and what it should be. Also a stack trace would be handy.

**Comment by eddumelendez** [comment]
`LocalStackContainer` will only return the base url `http://<host>:<port>`, path should be added if it required by the service in use.
