### ISSUE TITLE
@Testcontainers isn't failing by default if docker isn't available

### ISSUE THREAD

**Issue by aheritier** [testcontainers/testcontainers-java#3222]
Hi team,

When using the annotation @Testcontainers for JUnit 5 if docker isn't available the tests are all ignored.

I have such kind of result:

```
[INFO] Running com.cloudbees.foo.BarRepositoryTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.95 s - in com.cloudbees.foo.BarRepositoryTest
```

My code (Spring Boot app) is doing something something like

```
@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Testcontainers
class BarRepositoryTest {
    @Container
    private static final ElasticsearchContainer ELASTICSEARCH_CONTAINER =
        new ElasticsearchContainer("docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2");

    @Test
    void aTest() {
        // ...
    }

    @TestConfiguration
    static class ContextConfiguration extends AbstractElasticsearchConfiguration {
        @Override
        @Bean
        public RestHighLevelClient elasticsearchClient() {
            final ClientConfiguration clientConfiguration = ClientConfiguration.builder()
                .connectedTo(ELASTICSEARCH_CONTAINER.getHttpHostAddress())
                .build();

            return RestClients.create(clientConfiguration).rest();
        }
    }

}

```

My understanding from `Testcontainers#disabledWithoutDocker` ( https://github.com/testcontainers/testcontainers-java/blob/master/modules/junit-jupiter/src/main/java/org/testcontainers/junit/jupiter/Testcontainers.java#L64 ) is that by default it should fail if docker isn't accessible and setting `disabledWithoutDocker=true` should disable the test

> Whether tests should be disabled (rather than failing) when Docker is not available.

Is there an error in the doc and `rather than failing` is wrong or there is an issue in the code ?

**Comment by bsideup** [comment]
@aheritier this does not look `@Testcontainers`-related.
If `disabledWithoutDocker` is set to `false`, it won't ignore anything and just let the test run (so that it fails later).

Make sure that you're using the correct JUnit runner and that it discovers the tests correctly.

**Comment by bsideup** [comment]
I just created a project with https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.3.3.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=testcontainers,postgresql,webflux and the following test fails when Docker is not available:
```java
@SpringBootTest
@Testcontainers
class DemoApplicationTests {

	@Container
	static PostgreSQLContainer postgres = new PostgreSQLContainer();

	@Test
	void contextLoads() {
	}
}
```

Feel free to reopen the issue if you find that, after fixing your testing setup, you still get the issue.

**Comment by aheritier** [comment]
thanks @bsideup I will verify on my side and reopen if necessary
