### ISSUE TITLE
Customize docker.client.strategy through classpathProperties instead of environmentProperties

### ISSUE THREAD

**Issue by FpyrypT** [testcontainers/testcontainers-java#3229]
I think it could be a convenient feature to customize docker.client.strategy also through classpathProperties instead of environmentProperties only. Would you like to rollback
`return (String) properties.get("docker.client.strategy");`
instead of 
`return (String) environmentProperties.get("docker.client.strategy");`
at this line?
https://github.com/testcontainers/testcontainers-java/blob/9b3c87eb2f350c6211dfa5eadea61f8eb00e2097/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L167

**Comment by bsideup** [comment]
The value stored in the file is a "cache" and is not supposed to be manually set.

Also, client strategies is a property of an environment. It does not make sense to force the Unix Socket strategy, for example, because it will fail on Windows.
