### ISSUE TITLE
Review dependencies and JAR shading approach

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#325]
We have a complex chain of dependencies, and we should make sure that we're definitely shading the right things and in the most appropriate way.

**Comment by dbyron0** [comment]
With 1.3.0 I see what I think is docker-java unshaded in both jdbc-1.3.0.jar and testcontainers-1.3.0.jar.  Here's one class as an example:
```
$ jar tf testcontainers-1.3.0.jar  | grep com/github/dockerjava/api/DockerClient.class
com/github/dockerjava/api/DockerClient.class
```
```
$ jar tf jdbc-1.3.0.jar  | grep com/github/dockerjava/api/DockerClient.class
com/github/dockerjava/api/DockerClient.class
```
For me it would be a big improvement if only testcontainers had this, though I think I remember seeing something about being close to removing it completely from both.

**Comment by bsideup** [comment]
@rnorth is it still relevant?
