### ISSUE TITLE
Cannot Enable x-delayed-message plugin on RabbitMQ Container

### ISSUE THREAD

**Issue by NoelOmo** [testcontainers/testcontainers-java#3258]
I am trying to start a rabbitMQ test container to be used in my tests with the following pom.xml:

`        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>rabbitmq</artifactId>
            <version>1.14.3</version>
            <scope>test</scope>
        </dependency>
`

Then the class rule is as follows:

`    @ClassRule
    public static RabbitMQContainer rabbitMQContainer = new RabbitMQContainer()
            .withPluginsEnabled("rabbitmq_delayed_message_exchange")
            .withExposedPorts(5672);
`

But upon starting the application, I get the following error thrown:

`
15:26:24.172 [main] ERROR 🐳 [rabbitmq:3.7-management-alpine] - Could not execute command [rabbitmq-plugins, enable, rabbitmq_delayed_message_exchange]: Error:
{:plugins_not_found, [:rabbitmq_delayed_message_exchange]}
`

**Comment by DarrenForsythe** [comment]
Have you tried moving to the latest version of Testcontainers? I couldn't re-create this with your sample.

**Comment by MatthewRyanRead** [comment]
I see this as well:

```
ERROR 🐳 [rabbitmq:3.9.13-alpine] - Could not execute command [rabbitmq-plugins, enable, rabbitmq_delayed_message_exchange]: Error:
{:plugins_not_found, [:rabbitmq_delayed_message_exchange]}
```

This is on 1.16.3, released January 2022.

It's not surprising that this fails since it's not an integrated plugin (unlike, say, `rabbitmq_consistent_hash_exchange`).  It probably needs to be manually installed into the container ... I'll see if I can figure that out.

**Comment by eddumelendez** [comment]
According to the [docs](https://www.rabbitmq.com/installing-plugins.html)
> Any plugins that do not ship with the server will need to be installed. Plugins are distributed as .ez archives (which are zip files with metadata). The files must be copied to one of the plugins directories specified by $RABBITMQ_PLUGINS_DIR.

List of plugins ship with rabbitmq https://github.com/rabbitmq/rabbitmq-server/tree/master/deps
List of community plugins https://www.rabbitmq.com/community-plugins.html

Those community plugins as `rabbitmq_delayed_message_exchange` need manual installation.

**Comment by MatthewRyanRead** [comment]
Yep, manual install worked fine.  I just downloaded it locally and used `.withCopyFileToContainer(MountableFile.forHostPath(pathToPlugin), "plugins/")`.

**Comment by eddumelendez** [comment]
Closing this issue since third-party plugins in rabbitmq should be downloaded and installed manually.
