### ISSUE TITLE
Multiple databases on a container instance

### ISSUE THREAD

**Issue by phixMe** [testcontainers/testcontainers-java#3260]
I am using the [PostgreSQLContainer](https://github.com/locationlabs/testcontainers-java/blob/master/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java), but I expect this applies more generally.

The class file contains the following getter which only will create a single database on the image. It would be great to be able to configure more than one database here with different names, usernames, and passwords. 

```java
@Override
public String getDatabaseName() {
    return databaseName;
}
```

I've looked at some of the other database Container classes and they appear to follow a similar pattern. This feature appears to be a larger rewrite of the aforementioned classes and might not be something on the roadmap.

**Comment by bountin** [comment]
How about starting two container instances each configured to the individual needs?

**Comment by phixMe** [comment]
Sure, that makes sense. Thanks for your quick feedback. I feel comfortable closing this since it looks like a major rewrite to support multiple databases on a single container instance.

**Comment by solarprime** [comment]
I'm looking for this exact feature.  We have integration tests where each scenario spins up a postgres testcontainer.  The vast majority of the time is spent spinning up these containers.  Ideally we would be able to start a single container, and create a separate database for each test.

**Comment by bsideup** [comment]
@solarprime it is already possible. Just share the same instance (e.g. with the [Singleton Container Pattern](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers)) and create databases as you would in production (`CREATE DATABASE xxx`)
