### ISSUE TITLE
Cannot mix public and private remote docker registries in one run

### ISSUE THREAD

**Issue by dharezlak** [testcontainers/testcontainers-java#3263]
I am using testcontainers to setup a mix of containers coming from our private docker registry (application images) as well as from the main docker registry (services like PostgreSQL and Kafka). Our private registry is password protected so I am setting the user name and password with `registry.username` and `registry.password` system properties. As soon as I launch the whole thing I am getting to following error:

```
ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://registry-1.docker.io/v2/library/postgres/manifests/9.6.12: unauthorized: incorrect username or password"}
```

It looks like credentials for our private registry are used for the public one hence the error:

```
DEBUG org.testcontainers.utility.RegistryAuthLocator - Looking up auth config for image: postgres:latest at registry: index.docker.io
DEBUG org.testcontainers.utility.RegistryAuthLocator - No matching Auth Configs - falling back to defaultAuthConfig [AuthConfig{username=private.user, password=hidden non-blank value, auth=blank, email=null, registryAddress=https://index.docker.io/v1/, registryToken=blank}]
DEBUG org.testcontainers.dockerclient.auth.AuthDelegatingDockerClientConfig - Effective auth config [AuthConfig{username=private.user, password=hidden non-blank value, auth=blank, email=null, registryAddress=https://index.docker.io/v1/, registryToken=blank}]
```

Is there any workaround for this or some specific configuration I can use only for one of the registries? If I fetch the images with console client using `docker login` only for the private registry everything works.

**Comment by rnorth** [comment]
Hi @dharezlak  
I'd suggest not using `registry.username` or `registry.password` at all, and just configure Docker's native auth. Testcontainers will use Docker's native credential store/helper framework (described [here](https://docs.docker.com/engine/reference/commandline/login/)).

Basically, if `docker pull ...` works for your image, Testcontainers should also be able to pull it.
