### ISSUE TITLE
TestContainers won't allow copying files from stopped containers - but it is possible.

### ISSUE THREAD

**Issue by eastlondoner** [testcontainers/testcontainers-java#3264]
According to the docker docs container statuses are:
`created, restarting, running, removing, paused, exited, or dead`

I believe that it is possible with docker to copy files from all of these states except, perhaps `removing`.

However testContainers will only allow copying files from containers that are `created` or `running`.

In `ContainerState#copyFileFromContainer` there is a check `isCreated()` which is preventing me from copying files e.g. from paused containers: 
https://github.com/testcontainers/testcontainers-java/blob/780b8e33811f046e64c7cdf6a25b49fb0fe79ce8/core/src/main/java/org/testcontainers/containers/ContainerState.java#L309

If I remove that check I am able to use the existing code to copy files from paused or stopped containers.

**Comment by eastlondoner** [comment]
The docker docs on cp says for copy:
> The CONTAINER can be a running or stopped container. 
https://docs.docker.com/engine/reference/commandline/cp/ 

I think that the solution is either to change the `isCreated()` method to be less picky about the container status OR to change the check that is used in the `copyFileFromContainer` method to something more permissive.

I wonder if having a containerId is sufficient?

**Comment by michael-simons** [comment]
Ping @bsideup What do you think about these statuses and how to make it possible to get files from stopped containers? We would really appreciate your feedback here. Thanks.

**Comment by bsideup** [comment]
@michael-simons I am wondering what will be the behaviour if we remove the check on our side and let the Docker API call fail instead, so that it is up to Docker to decide whether it is okay to perform the operation or not

@eastlondoner would you like to try it?

**Comment by eastlondoner** [comment]
@bsideup sure thing :-)

**Comment by eastlondoner** [comment]
@bsideup I've tested the behaviour if the `isCreated` check is removed and as far as I can tell it is an improvement.

Starting with the worst cases - these are unchanged:

# If the docker container is totally removed without the test containers framework knowing about it
A RuntimeException (caused by a `java.io.EOFException`) is thrown whether or not the test containers isCreated check is used.

# If GenericContainer#stop is called before a file copy is attempted
`java.lang.NullPointerException: containerId was not specified` is thrown whether or not the testContainers isCreated check is used.

n.b. this is because calling `GenericContainer#stop` actually stops _and removes_ the docker container.

Then the improvements:

#  If the docker container is stopped (without `GenericContainer#stop` being called) or exited or paused
With the isCreated check `copyFileFromContainer` fails with `IllegalStateException: copyFileFromContainer can only be used when the Container is created.`
Without the isCreated check `copyFileFromContainer` works perfectly.


So I will put up a PR with that change and some tests.

**Comment by bsideup** [comment]
@eastlondoner could you please call `client().stopContainerCmd()` and make it stop but not remove and test the behaviour?

Also, I would add a check for `containerId` to avoid NPE with a message like "`copyFileFromContainer` before `start()` was called"

**Comment by eastlondoner** [comment]
@bsideup regarding `stopContainerCmd()` I do that here: https://github.com/testcontainers/testcontainers-java/pull/3555/files#diff-5b39cc62592f583d08a99cafd5076c65f78584d3e79dc2e9e5039aafa7cc48c6R207

I see your point about calling the method before start is called, I didn't think of that! Let me see...

**Comment by eastlondoner** [comment]
@bsideup I think I've addressed your comments, are you able to take another look ?
Thanks

**Comment by eastlondoner** [comment]
Happy new year @bsideup, is there any chance that you could take another look at the linked PR?
