### ISSUE TITLE
Add 'internal' flag for NetworkImpl

### ISSUE THREAD

**Issue by vab2048** [testcontainers/testcontainers-java#3272]
The current `Network` definition has the following fields:

```java
private final String name = UUID.randomUUID().toString();
private Boolean enableIpv6;
private String driver;
@Singular private Set<Consumer<CreateNetworkCmd>> createNetworkCmdModifiers;
private String id;
private final AtomicBoolean initialized = new AtomicBoolean();
```

Could an additional field be added: `private Boolean internal;` which has its corresponding value effect the final `CreateNetworkCmd` which is used in the `create()` method:

```java
private String create() {
       // ..... snipped

       // add the following...
       if(internal != null) {
            createNetworkCmd.withInternal(internal);
       }

       // ... snipped
 }
```

This will allow us to easily create `internal` networks.

**Comment by bsideup** [comment]
Given the presence of `createNetworkCmdModifiers` and that the internal flag is rarely used, I'd say we should not overcomplicate our public API. @rnorth @kiview WDYT?

**Comment by vab2048** [comment]
I'll close this issue because you are right - it is very easy to use `createNetworkCmdModifiers` like so to achieve the same effect:

```java
private Network generateInternalNetwork() {
    Consumer<CreateNetworkCmd> cmdModifier = (createNetworkCmd) -> {
        createNetworkCmd.withInternal(true);
    };

    return Network.builder()
            .createNetworkCmdModifier(cmdModifier)
            .build();
}
```
