### ISSUE TITLE
Update to MockServer version 5.11.1

### ISSUE THREAD

**Issue by odidev** [testcontainers/testcontainers-java#3289]
Hi,

MockServer version [5.11.1](https://mvnrepository.com/artifact/org.mock-server/mockserver-core/5.11.1) is available and it is using netty (4.0.50.Final), which includes both security fixes and AArch64 performance improvements. Refer release notes for detail:
https://netty.io/news/2020/05/13/4-1-50-Final.html

Currently, MockServer version 5.5.4 is being used by testcontainers. So, is there any plan to update latest MockServer in testcontainers package?

**Comment by bsideup** [comment]
Hi @odidev,

I noticed that you submit quite a lot of issues/PRs to various projects mentioning some minor dependency updates (especially the Netty one).

May I kindly ask you to not submit them to Testcontainers/docker-java? We have Dependabot to automatically update our dependencies and perform the updates regularly when it makes sense.

Feel free to update the dependency in your project and/or pass the MockServer image's version to `MockServerContainer`'s constructor.
