### ISSUE TITLE
@Container(s) should support arbitrary containers 

### ISSUE THREAD

**Issue by manosbatsis** [testcontainers/testcontainers-java#3306]
My use-case required for the JUnit5 `TestcontainersExtension` to scan a test for arbitrary (number of) containers, i.e. something like:

```java
@Testcontainers
public class MyTest {
    
    @Container//(s?)
    public List<GenericContainer> containersCollection = //...
}
```
In the end i had to clone and customize my own equivalents of `@Testcontainers`, `@Container` and  `TestcontainersExtension` from scratch, especially due a number of methods in the latter being private. It works just fine, but it's annoyingly redundant.

Can we add support for arbitrary containers to `TestcontainersExtension`? I would be happy to submit a PR and take it from there. Otherwise, can it's private methods at least be protected instead?

**Comment by bsideup** [comment]
`@Container` works on any `Startable` (+`TestLifecycleAware` when implemented) - just implement the interface(s) and you're good to go.
