### ISSUE TITLE
Document: quickstart code cannot compile

### ISSUE THREAD

**Issue by gabrielhao** [testcontainers/testcontainers-java#3314]
quickstart https://www.testcontainers.org/quickstart/junit_4_quickstart/ uses code in version 1.15.0, however dependency is 1.14.3.

there is compile error on DockerImageName.parse(). This method is only added in version 1.15.0.

The document needs to update the dependency version to1.15.0-rc2.

**Comment by bsideup** [comment]
The page seems to be referencing `1.15.0-rc2` now 👍
