### ISSUE TITLE
Add a keycloak module

### ISSUE THREAD

**Issue by naderghanbari** [testcontainers/testcontainers-java#3320]
[Keycloak](https://github.com/keycloak/keycloak) as an open source identity and access management 
solution is widely used. Setting it up is pretty straightforward as a [docker image](https://hub.docker.com/r/jboss/keycloak/)
but getting anything useful out of it, such as adding test users and identity providers,
is pretty tedious and needs a lot of context. 

I think supporting it as a module makes sense. I am intimately familiar with it and I offer to make an initial MR (if that helps 
deciding if it's worth as a module or not).

**Comment by bsideup** [comment]
It is already available and actively maintained by @dasniko:
https://github.com/dasniko/testcontainers-keycloak

Have you tried it? :)

**Comment by dasniko** [comment]
@bsideup Thanks for mentioning.
Should we come up with a page listing worthy community modules? WDYT?

@naderghanbari You're welcome to give my module a try and to leave some thoughts and ideas in https://github.com/dasniko/testcontainers-keycloak/issues.
PRs with new features are also appreciated, but we should discuss them before!

**Comment by naderghanbari** [comment]
Very nice! Thanks. @dasniko I gave it a quick try and works like a charm. I like the simplicity of importing a realm as a JOSN.
I am about to give it a try in our actual projects as well.
 
@bsideup Thanks, please feel free to close this issue.
