### ISSUE TITLE
Add RocketMQ module

### ISSUE THREAD

**Issue by xuesongxs** [testcontainers/testcontainers-java#3348]
Add RocketMQ module in testcontainers.

**Comment by bsideup** [comment]
Hi @xuesongxs,

Is there any trouble using RocketMQ with `GenericContainer`? If so, consider contributing a module as per https://www.testcontainers.org/contributing/#contributing-new-modules

**Comment by xuesongxs** [comment]
> Hi @xuesongxs,
> 
> Is there any trouble using RocketMQ with `GenericContainer`? If so, consider contributing a module as per https://www.testcontainers.org/contributing/#contributing-new-modules

I want to use RocketMQ in testcontainers, but testcontainers doesn't have this feature.

**Comment by ruanwenjun** [comment]
@bsideup Is there any progress about support rocketmq module?

**Comment by bsideup** [comment]
@ruanwenjun Testcontainers provides `GenericContainer` that can be used with any Docker image, it does not need to be *supported* by Testcontainers.

If somebody wants to contribute a module, just to make it more convenient, here is the docs page that describes the process:
https://www.testcontainers.org/contributing/#contributing-new-modules

**Comment by kiview** [comment]
In addition, if some can outline the already encountered issues (in case there are any) in using RocketMq with `GenericContainer`  here, we can further assess and discuss the need for a dedicated module.

**Comment by vongosling** [comment]
Good catch, I'd like this feature shape :-)

**Comment by echooymxq** [comment]
I create a project(https://github.com/echooymxq/testcontainers-rocketmq) for Apache RocketMQ, i can contribute to this module if necessary.

**Comment by eddumelendez** [comment]
Hi @echooymxq 

Thanks for creating the module and sorry for the late reply. Nowadays, Testcontainers offers a [Module Catalog](https://testcontainers.com/modules/) and your module can be listed there, you only need to submit a PR to [this repository](https://github.com/testcontainers/community-module-registry).

Looking forward to it.
