### ISSUE TITLE
"DNS lookup failure for: host.testcontainers.internal" but only for Generic container

### ISSUE THREAD

**Issue by eliasbalasis** [testcontainers/testcontainers-java#3355]
I have successfully managed to access "host.testcontainers.internal" from within a WebDriver containerm using "Testcontainers.exposeHostPorts(...)"

However, when I try to do the same from a generic container (e.g. custom HTTPD) I am getting "DNS lookup failure for: host.testcontainers.internal"

Could this be something missing from generic containers? or am I doing something wrong?

FYI, this problem occurs with Docker server running either on Linux or Windows 10

**Comment by bsideup** [comment]
You need to enable it. See https://www.testcontainers.org/features/networking/

**Comment by bsideup** [comment]
Also note that the port must be exposed _before_ starting the container

**Comment by eliasbalasis** [comment]
Thanks,

I am very well aware of this technique, and as I said I have successfully used it with the WebDriver container.

This time I am using a Generic container running HTTPD and mod_proxy to simulate reverse proxy access to applications runing on test host machine, exposing the test host machine ports using "Testcontainers.exposeHostPorts(...)", just as I did in the past for the WebDriver container.

Therefore, having used the exact same techniques, I can only suspect that Generic container is working differently compared to WebDriver container.

Is my suspicion correct?

**Comment by eliasbalasis** [comment]
My suspicion is finally correct,

any container other than "Generic" understands "Testcontainers.exposeHostPorts(...)" before starting the container and adds the respective entry to "/etc/hosts"
e.g. WebDriver, Nginx

This sounds more like a bug

**Comment by eliasbalasis** [comment]
Cancel the above, my suspicion was wrong.

There are however condition under which "Testcontainers.exposeHostPorts(...)" before starting the container is not adding the respective entry to "/etc/hosts"

I will keep investigating...

**Comment by eliasbalasis** [comment]
I have found the problem.

I was trying to remap the default ports by using "container.withCreateContainerCmdModifier(modifier)" and "HostConfig.newHostConfig()" instead of "command.getHostConfig();" in "modifier" implementation, practically cancelling all the good work "testcontainers" had done.

There is no bug, just my negligence.
