### ISSUE TITLE
Do not deprecate GenericContainer(String dockerImageName)

### ISSUE THREAD

**Issue by dturanski** [testcontainers/testcontainers-java#3404]
I don't understand why this would be deprecated.  DockerImageName seems to provide more value to the framework than the user. In most cases, it's just an unnecessary step for the user. 

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L240

**Comment by bsideup** [comment]
Hey @dturanski,

It was left deprecated by a mistake and is already fixed in #3102. Sorry for that!

**Comment by JavaGalaxy** [comment]
I am using 1.17.1 and it still says deprecated.
