### ISSUE TITLE
Export test-videos (Webdriver/VNC) as mp4

### ISSUE THREAD

**Issue by AB-xdev** [testcontainers/testcontainers-java#3405]
It would be very helpful, if it's possible to export Webdriver/VNC test-videos as ``.mp4`` instead of ``.flv`` so you can open it in a "normal" videoplayer (e.g. Windows Media Player)  and don't have to install and configure a external player (e.g. VLC; still didn't figure out how to stop videos at a specific point).

May be related to #512

**Comment by AB-xdev** [comment]
Found out, that this will be possible with https://github.com/testcontainers/testcontainers-java/pull/3180 🎉 
→ https://github.com/testcontainers/testcontainers-java/pull/3180#issuecomment-743190247

**Comment by eddumelendez** [comment]
As the previous comment said this is already in place. For that reason, the issue will be closed.
