### ISSUE TITLE
Run testcontainer test OK in local environment but failed in jenkins

### ISSUE THREAD

**Issue by lsongseven** [testcontainers/testcontainers-java#3407]
# Background
In my application, it needs to connect to zookeeper to get some useful information. So I start a zookeeper container in my integration test with port binding like -p 2859:2181.
```
        zookeeper = new GenericContainer<>("zookeeper:3.6.1")
                .withEnv("ZOOKEEPER_CLIENT_PORT", "2181")
                .withExposedPorts(2181);
        zookeeper.setPortBindings(Arrays.asList("2859:2181"));
        zookeeper.start();
```
Then I use the following command to run the test. It goes smoothly connecting to localhost:2859 without any problems. 
```
mvn -Dtest=xxxIntegrationTest.java test
```

# Problem
However, when I use jenkins to run the same test with same command, it cannot connect to  localhost:2859, complaining that
```
2020-10-28 12:16:04.282 INFO  [main-SendThread(localhost:2859)] Opening socket connection to server localhost/127.0.0.1:2859. Will not attempt to authenticate using SASL (unknown error)
2020-10-28 12:16:04.283 WARN  [main-SendThread(localhost:2859)] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
```

I don't know why it behaves differently in these two senarios. Could anyone give me some suggestions?

**Comment by bsideup** [comment]
1) consider not using fixed ports
2) for the reason described in the article, it may fail to connect because the container isn't exposed on "localhost" - more logs would help here.

Since it gets past starting the container just fine, I'd say there is an issue in your setup, so I am going to close this issue.

**Comment by lsongseven** [comment]
> 1. consider not using fixed ports
> 2. for the reason described in the article, it may fail to connect because the container isn't exposed on "localhost" - more logs would help here.
> 
> Since it gets past starting the container just fine, I'd say there is an issue in your setup, so I am going to close this issue.

Thanks!

**Comment by bsideup** [comment]
Sorry, the link seems to be missing:

https://bsideup.github.io/posts/testcontainers_fixed_ports/
