### ISSUE TITLE
Wait fails when test container is started within another container

### ISSUE THREAD

**Issue by wbiller** [testcontainers/testcontainers-java#341]
I've a build setup where the test containers are started inside a build container.
The Docker host socket is mapped into the build container. 

This is the command I use to run the build container
```bash
docker run --privileged=true -v /var/run/docker.sock:/var/run/docker.sock -t ${BUILD_IMAGE}
```

Everything is fine when I run the tests from my local machine. But when I start the tests inside the the build container wait fails to check if the port specified port ist opened.

This is how I start the test container
```java
@ClassRule
public static GenericContainer = new GenericContainer("rabbitmq:3").withExposedPorts(5672).waitingFor(Wait.forListeningPort());
```

**Comment by bsideup** [comment]
Hi @wbiller,

You mentioned build container. Are you talking about the latest Docker with multi-stage Dockerfiles?

Thanks,
Sergei

**Comment by wbiller** [comment]
Hi Sergei, 

no, it's just a container which is run by Jenkins to build an application.
