### ISSUE TITLE
Simplify configuration of registry

### ISSUE THREAD

**Issue by markusa380** [testcontainers/testcontainers-java#3430]
This issue is based on the [changes regarding rate limiting of pulls from Docker hub](https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/).

This means that many projects are currently switching to their own image registries where the images required for e.g. CI are re-tagged and re-pushed to avoid requesting Docker hub.

Currently, some modules, like `kafka` for example, only allow providing the version of the image tag as parameter.
It's still possible to define a modified image using `testcontainers.properties` file, but this leads to it's own set of problems.

Take this example:
* A project called _my-kafka-test-library_ defines some utilities for setting up and testing with Kafka containers.
* A project called _my-pulsar-test-library_ defines some utilities for setting up and testing with Pulsar containers.
* Two projects called _my-service-1_ and _my-service-2_ depend on these utilities for their tests.
* The developer now wants to avoid hitting the rate limit.
** The dev cannot use `testcontainers.properties` in the two library projects as they will collide on the classpath.
** The dev should not define `testcontainers.properties` in the services projects as it causes coupling between the test library code and the configuration in the services.
** The dev should not use any hacks to change configuration at runtime

So it is clear that the best option is to provide the ability to pass the *full* image tag as a parameter.

**Comment by bsideup** [comment]
see #3102

**Comment by rnorth** [comment]
Yep, sorry we've not managed to ship all these changes before the rate limit's official start. The constructor allowing the full docker image name to be specified _is_ published in [1.15.0-rc2](https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.0-rc2) though.

We're working on 1.15.0, and hope to release very soon!

**Comment by eddumelendez** [comment]
Closing this as resolved
