### ISSUE TITLE
Should we add Pause/Unpause public API methods for GenericContainer class?

### ISSUE THREAD

**Issue by Hixon10** [testcontainers/testcontainers-java#3432]
Hello,

Right now we have methods for starting and stoping a container. Maybe we also can add Pause/Unpause methods to the `GenericContainer` class? What do you think?

Current solution, if I need to pause my container, looks like this:
```java
DockerClientFactory.instance().client().pauseContainerCmd(myContainer.getContainerId())
```

**Comment by bsideup** [comment]
It is actually even shorter:
```java
myContainer.getDockerClient().pauseContainerCmd(myContainer.getContainerId())
```

I am not sure that adding such "shortcuts" to our public API surface is required, given how easy it is to achieve the same already today. Especially given that the use case is... exotic :)
@rnorth @kiview WDYT?

**Comment by Hixon10** [comment]
yep, I agree with you, you version of this code is definitely solve my problem. Thank you.

**Comment by kiview** [comment]
I agree with both of you. No need to create a facade API for each docker-java command, especially since docker-java is nearly a 1st-party dependency nowadays 🙂
