### ISSUE TITLE
Ability to provide classloader for JdbcDatabaseContainer

### ISSUE THREAD

**Issue by npetzall** [testcontainers/testcontainers-java#344]
Would be nice if one could supply a Driver classloader to the JdbcDatabaseContainer.

This is more or less specific to Oracle test container. Since it's problematic to have the proprietary drivers in a repository.

**Comment by npetzall** [comment]
Haven't checked mig be possible if it used thread context classloader.

**Comment by npetzall** [comment]
Ok to do PR?

**Comment by kiview** [comment]
Everyone I know who is working with Oracle JDBC drivers has them in their own Artifactory or deploys them in the local Maven repository on the dev machines. So TBH, I'm not sure if this would help a lot.

Could you explain your use case?

**Comment by npetzall** [comment]
Use-Case:
I'm helping out on a project SchemaSpy which is open-source. We would like to be able to test Oracle.
We don't want to put oracle driver on the classpath. Since one might assume it will exist on the classpath.

So we/I want to have the driver side-loaded.

**Comment by npetzall** [comment]
For instance, you could in this project assume that the Oracle driver was located in ${project.baseDir}/proprietary and run Oracle tests when the driver is located in that folder. If the assumption passes. If it can't find the driver it will just ignore the test, which differs from right now as it ignores the whole module.

**Comment by npetzall** [comment]
No reason to keep this open if it's not wanted.

**Comment by kiview** [comment]
Let's wait for the opinion of @rnorth.

**Comment by rnorth** [comment]
I'm sorry, to be honest with this one I think it's just a bit too much complexity to add. Would you be able to find another way to do this?

Sorry, but thanks for taking the time to suggest it.

**Comment by npetzall** [comment]
@rnorth 
Yepp, I've done it in my fork and I've got jitpack so I'm good.

**Comment by npetzall** [comment]
@rnorth manage to solve it with maven and a cpl of settings for the failsafe plugin.
So solving 343 and we can retire the fork. 
Might be able to create custom launcher for IDE so it can be run from IDE.
