### ISSUE TITLE
Toxiproxy cut connection behavior

### ISSUE THREAD

**Issue by aartigao** [testcontainers/testcontainers-java#3453]
Hi! 

I'm proxying Kafka broker with Toxiproxy and I found that `setConnectionCut` all it does is disabling the bandwidth in either directions. This is useful if what you try to simulate a timeout on client side but not if you want to test a closed connection.

Turns out that Toxiproxy supports this closing connection by `enable`/`disable` the whole proxy (supported also by the Toxiproxy client). So my question is, can I open a PR with modifications to allowing `enable`/`disable` the proxy? Also I would like to update the Toxiproxy version to the latest stable because the default one is not working well with my Kafka version (which is an old one, by the way).

Thanks!

**Comment by bsideup** [comment]
Since Testcontainers 1.15.0, we discourage "default" image versions and ask the users to provide a version they want to use.

But there is an opportunity for contribution - adding `getToxyPort()` or similar method, so that the users can instantiate their own client and perform operations on it.
FTR It is possible even with the current version of `ToxiproxyContainer`, just one has to know the port number (`8474`).

**Comment by aartigao** [comment]
Thanks, I didn't know about the `default` thingy, so turns out I was doing it right already 😄 

About exposing the Toxy port, what I understand with this decision is that it sort of deprecates the current logic of `ToxiproxyContainer.ContainerProxy`, right? I mean, what is the purpose of having `setConnectionCut` and `toxics` methods if we want users to use their own Toxi client? 🤔 I find it confusing because it opens to use mixed approaches: one can use the current approach to cut bandwidth but needs to create another Toxy client to disable proxy.

Either way, I will be happy to implement whatever approach you decide 👌🏽

**Comment by bsideup** [comment]
it is rather an addition to the API that we provide in case you need to do something that is not supported by the module. Think about the currently provided API as a set of shortcuts :)

**Comment by gtrefs** [comment]
@bsideup I am not sure if I understand your argument. As @aartigao described it is confusing that a method called `setConnectionCut(Boolean)` actually does not cut the connection but rather lowers the bandwith to 0. When it comes to toxics, the module itself exposes a `ToxicList` class which is part of the original Java client. So, the toxic action which is not supported is to close a connection. I am all in for adding methods `enable` and `disable` to `ToxiproxyContainer.ContainerProxy`. If you don't mind, I am more than willing to do it.

**Comment by slovdahl** [comment]
I'm a little bit with @gtrefs here. I do understand that testcontainers can't cater for every single use-case and want to keep the API surface as small as possible, but at the moment, creating a custom `ToxiproxyClient` requires duplicating quite a lot of code from `ToxiproxyContainer`.

1. Set up some new ports that are exposed by the Toxiproxy container. Testcontainers exposes 32 ports by default, but there's no way to use those, so the code that does that needs to be duplicated.
2. Create the client based on `getHost()` and `getControlPort()` (this is perfectly fine).
3. Whenever a new proxy is wanted, get the next unused proxy port, get the correct mapped port for the proxy port, create the new proxy.

I do feel there's room for improvement here. What about exposing a method that creates a new `Proxy` instance? Or alternatively just expose the internal `ToxiproxyClient`?

**Comment by mikymigs** [comment]
Same need over here. +1
