### ISSUE TITLE
gcloud module default to a container image

### ISSUE THREAD

**Issue by saturnism** [testcontainers/testcontainers-java#3456]
Currently gcloud containers requires a user to put in an explicit image name.  Will it be OK if we have a no-arg constructor that defaults to `gcr.io/google.com/cloudsdktool/cloud-sdk:emulators`?

Secondly, how about a 1-arg constructor that takes the `gcloud` version number, such as `317.0.0`?

/cc @eddumelendez

**Comment by bsideup** [comment]
@saturnism this (no-args constructors and tag-only constructors) is exactly what we _removed_ in 1.15.0 :D 

There is an open issue about DX ( #3381 ). We got some ideas on how to improve it, but we needed more time and Docker Hub's rate limits were pressuring us :)

**Comment by saturnism** [comment]
I see. The gcloud containers are not hosted on Dockerhub and won't have the rate limit restrictions. Would the image name thing only be applicable to dockerhub hosted images?

**Comment by bsideup** [comment]
Sorry for confusing - these are two separate things: the team was busy delivering required changes for the rate limit restrictions so we didn't have time to improve the DX. But the decision to not expose default/tag-only constructors was independent from the rate limits and just something that we wanted to do for a long time to make it less confusing: #2839

**Comment by eddumelendez** [comment]
Closing for the reasons mentioned by Sergei.
