### ISSUE TITLE
gcloud spanner container should use gcr.io/google.com/cloudsdktool/cloud-sdk image

### ISSUE THREAD

**Issue by saturnism** [testcontainers/testcontainers-java#3458]
Current it uses `gcr.io/cloud-spanner-emulator/emulator`

It should use `gcr.io/google.com/cloudsdktool/cloud-sdk` ?

@olavloite would you know if there are any differences btwn these 2?

/cc @eddumelendez

**Comment by olavloite** [comment]
@saturnism No, I don't know if there's any difference between the two. I would however expect it to use the former, as that is also what the [official Spanner documentation](https://cloud.google.com/spanner/docs/emulator#docker) mentions.

**Comment by eddumelendez** [comment]
when running `gcloud beta emulators spanner start` a `spanner emulator` docker image is downloaded. That would work for every developer on their own machines but not in this case where testcontainers already start a container with `cloud-sdk`

**Comment by saturnism** [comment]
interesting, w/ the `gcr.io/google.com/cloudsdktool/cloud-sdk:emulators` image, `spanner start` doesn't download additional docker image.

the benefit of defaulting to `gcr.io/google.com/cloudsdktool/cloud-sdk:emulators` is to avoid excessive docker image download since these images are also pretty large. Will follow up w/ @olavloite internally.
