### ISSUE TITLE
gcloud datastore container to allow configuration for consistency

### ISSUE THREAD

**Issue by saturnism** [testcontainers/testcontainers-java#3461]
`gcloud beta emulators datastore start` takes an optional `--consistency` argument. For local tests, setting this to 1.0 can be useful.

Propose adding `.withConsistency(Float)` to configure the startup command.

/cc @eddumelendez wdyt?

**Comment by eddumelendez** [comment]
I agree. not an expert with the emulators but improvements like this will improve the DX. Thanks Ray!

**Comment by eddumelendez** [comment]
See https://github.com/testcontainers/testcontainers-java/pull/5993 😃

**Comment by kiview** [comment]
Fixed by #5993.
