### ISSUE TITLE
NoSuchMethodError when trying to create PostgreSQLContainer

### ISSUE THREAD

**Issue by bnjns** [testcontainers/testcontainers-java#3494]
I have an application built with Quarkus that I use testcontainers for the PostgreSQL database. Everything is dandy with Docker for Mac 2.3.0.5 and testcontainers v0.14.3 but I would like to upgrade Docker and in order to use >=2.4.0 I also need to use testcontainers v0.15 to avoid #3166. 

However when I do I get the following error:

```
Caused by: java.lang.NoSuchMethodError: 'org.testcontainers.utility.DockerImageName org.testcontainers.utility.DockerImageName.parse(java.lang.String)'
	at org.testcontainers.containers.PostgreSQLContainer.<clinit>(PostgreSQLContainer.java:21)
	at com.ovofieldforce.incidentlog.testcontainers.PostgresTestResource.<init>(PostgresTestResource.kt:7)
	... 67 more
```

The container is configured with the following:

```kotlin
PostgreSQLContainer<Nothing>("postgres:11-alpine")
    .apply {
        withDatabaseName("database-name")
        withUsername("test")
        withPassword("test")
        withExposedPorts(5600)
    }
```

and my gradle config is

```gradle
testImplementation platform("org.testcontainers:testcontainers-bom:1.15.0")
testImplementation "org.testcontainers:testcontainers"
testImplementation "org.testcontainers:junit-jupiter"
testImplementation "org.testcontainers:postgresql"
```

I also get this error if I use `DockerImageName.parse("postgres:11-alpine")`.

Java version 11.0.8
macOS 10.15.7
Docker for Mac 2.5.0.1
Docker engine 19.03.13

**Comment by bnjns** [comment]
Turns out I had some really weird dependency version conflict that was super hard to find 🙄

**Comment by kalilmvp** [comment]
> ependency version conflict that was super hard to find 🙄

Hi @bnjns , i´m trying to find this weird conflict, what was your problem, maybe it can help me. Thanks!

**Comment by bnjns** [comment]
Hey @kalilmvp 

I had a library included in my `build.gradle` that uses the `enforcedPlatform` configuration for some Quarkus dependencies, which in turn sets the version of testcontainers to 0.14.3 so using `exclude` in that dependency solved the issue.

I used `./gradlew build --scan` to find this - it gives you a nifty UI that helps you see which dependencies are the ones restricting the versions 🙂
