### ISSUE TITLE
ElasticSearch: Add builder method to create an index

### ISSUE THREAD

**Issue by huehnerlady** [testcontainers/testcontainers-java#3495]
Hi,

I am currently looking into using the ElasticSearch Testcontainer. I can see you did have methods like username and password.

Another really handy method would be to be able to add an index while creating the docker image as well. Not sure how/if that is possible though

**Comment by RavitejaBatta** [comment]
Hi @huehnerlady , Did you get the Above query. how to create Index and push some data in to elasticsearch Test Containers ?
If yes, please paste the respective code here which will be helpfull

**Comment by eddumelendez** [comment]
Hi, this is not Testcontainers responsibility. Testcontainers provides the pre-configure container in a state that can be used. Username and password are set via env vars.
