### ISSUE TITLE
Docker client dependencies can cause conflicts with Jersey, Jackson and other libs

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#35]
When attempting to integrate Testcontainers into a project that uses Dropwizard 0.8.1 (Jersey 2.17), I've been getting some bad dependency clashes despite our use of the shaded docker-client lib.

After some head-scratching and experimenting with various options, what eventually worked was 
* making a temporary version of testcontainers that depends on the non-shaded version of docker-client
* use maven dependencyManagement to force the crossover Jersey dependencies into sync:

            <dependency>
                <groupId>org.glassfish.jersey.core</groupId>
                <artifactId>jersey-client</artifactId>
                <version>2.17</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.core</groupId>
                <artifactId>jersey-common</artifactId>
                <version>2.17</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.connectors</groupId>
                <artifactId>jersey-apache-connector</artifactId>
                <version>2.17</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-json-jackson</artifactId>
                <version>2.17</version>
            </dependency>

I think it would be better to either not use the shaded version of the docker-client library, or make it optional (e.g. via a classifier).

**Comment by swissarmykirpan** [comment]
Yeah I had this problem and it was horrible to exclude the conflicting dependencies in the project making use of TC

**Comment by rnorth** [comment]
On reflection, I think the right solution is probably to use a classifier and basically have two versions of org.testcontainers:testcontainers (core).

**Comment by rnorth** [comment]
Work on the [shade experiment](https://github.com/testcontainers/testcontainers-java/tree/shade-experiment) branch seems to be going fairly well - have set up automated tests to check that the new approach works with clashing versions of Jackson and Jersey on the classpath, and it seems to work.

The successful approach involves shading and relocating, in their entirety, the following dependencies into core:
```
                            org.apache.httpcomponents:*
                            org.glassfish.*:*
                            javax.annotation:*
                            javax.inject:*
                            javax.ws.rs:*
                            com.fasterxml.*:*
                            com.github.docker-java:*
```
I've yet to find any ill effects of doing this, and the outcomes only seem to be positive so far.

Note that I've had to work around an issue described here, which I suspect will ultimately be fixed by a patch to the maven shade plugin: KostyaSha/docker-java-shade#1. The workaround that has worked is to manually create service entries in META-INF named with the eventual *relocated* interface names but *pre-relocated* implementation names. This causes shade resource transformation to get both the interface and implementation references correct. I'll look forward to seeing if changes to shade resolve this in a simpler way, though.

**Comment by rnorth** [comment]
Reopen pending release of 1.0.0

**Comment by rnorth** [comment]
@swissarmykirpan - v1.0.0 should do a lot for resolving Jersey version conflicts. Please give it a try if you have a chance :)
Rich
