### ISSUE TITLE
Add Amazon RedShift Container

### ISSUE THREAD

**Issue by ericdotdata** [testcontainers/testcontainers-java#3546]
I would like a container for amazon redshift.  This was one of the first google hits: https://github.com/GuildEducationInc/docker-amazon-redshift

**Comment by bsideup** [comment]
> At this time, the container is merely PostgreSQL 8.0.2 running on port 5439 inside the container. No other changes have been made to make it more closely match the behavior of Redshift.


Since we already support PostgreSQL, it doesn't make much sense, does it?

**Comment by ericdotdata** [comment]
@bsideup  I noticed https://github.com/HearthSim/docker-pgredshift is similar, but also implements additional functions.

That said, I now suspect https://github.com/localstack/localstack is a better and already supported: https://www.testcontainers.org/modules/localstack/
