### ISSUE TITLE
Why does TastContainers not support docker swarm integration？

### ISSUE THREAD

**Issue by Alice-czxy** [testcontainers/testcontainers-java#3551]
Testcontainers uses the docker-java client library，Why does TestContainers not support docker swarm integration？I hope TestContainers comes up with a good solution.

**Comment by bsideup** [comment]
@Alice-czxy could you please be more precise about it? Testcontainers works well with Docker running in a Swarm mode.

**Comment by BigDataScholar** [comment]
> @Alice-czxy could you please be more precise about it? Testcontainers works well with Docker running in a Swarm mode.

I would like to know how TestContainers can be combined with Swarm. Do you have specific documents

**Comment by BigDataScholar** [comment]
> @Alice-czxy could you please be more precise about it? Testcontainers works well with Docker running in a Swarm mode.

To put it simply, how to configure the parameters of Swarm in TestContainers? Without knowing how to configure it, I can't see the difference between the Docker in Swarm mode and the Docker in stand-alone machine
