### ISSUE TITLE
404 link in Jupiter / JUnit 5 docs page

### ISSUE THREAD

**Issue by luka-j** [testcontainers/testcontainers-java#3552]
On page for [Jupiter / JUnit 5](https://www.testcontainers.org/test_framework_integration/junit_5), in section Singleton containers there's a link which leads to <https://www.testcontainers.org/manual_lifecycle_control/#singleton-containers>, which doesn't exist.

**Comment by eddumelendez** [comment]
this is due to how the link is shared... if it finishes with `/` then everything ok otherwise it fails. Not a testcontainers issue but one for mkdocs.

Using https://www.testcontainers.org/test_framework_integration/junit_5/ it works as expected.
