### ISSUE TITLE
Provide a mock server module adding support for WireMock

### ISSUE THREAD

**Issue by galegofer** [testcontainers/testcontainers-java#3554]
It will be very nice to be able to have more choices when adding mock server modules, but just having Mockserver, given WireMock is the most popular one, I think it will be a very good adding.

**Comment by Haple** [comment]
Up!

**Comment by josejuanmontiel** [comment]
Hi, not exactly... 

but with [this](https://www.testcontainers.org/features/creating_container/).. you can do something like this...

`
public static final DockerImageName WIREMOCK_IMAGE = DockerImageName.parse("wiremock/wiremock:2.32.0-alpine");
public static GenericContainer<?> mockServer = new GenericContainer<>(WIREMOCK_IMAGE).withExposedPorts(8080).waitingFor(Wait.forHttp("/__admin/mappings").withMethod("GET").forStatusCode(200)); 
`

**Comment by kiview** [comment]
Since it's trivial to use WireMock with `GenericContainer`, I am closing this issue for now.

If someone has some thoughts and arguments why a dedicated module (as per [docs](https://www.testcontainers.org/contributing/#does-it-need-to-be-a-module)) for WireMock is necessary, please comment on this issue and we can consider reopening it.

**Comment by oleg-nenashev** [comment]
@kiview @bsideup  could you please reopen it? I want to tinker with it on WireMock's side https://github.com/wiremock/ecosystem/issues/1

**Comment by kiview** [comment]
Hey @oleg-nenashev, happy to collaborate with you on this. Given we now have https://testcontainers.com/modules/ (where we can also link to external repositories), WDYT about hosting it in its own repository (e.g. under the WireMock org)?

**Comment by oleg-nenashev** [comment]
Yes, I think it would be the best approach

**Comment by oleg-nenashev** [comment]
To whomever is interested, here is the alpha version of the module: https://github.com/wiremock/wiremock-testcontainers-java
