### ISSUE TITLE
SpringBoot Integration issue with Kafka TestContainer

### ISSUE THREAD

**Issue by priyanshus** [testcontainers/testcontainers-java#3578]
I am using testcontainer 1.15.0 on my Mac OS for testing SpringBoot App. The spring boot app consumes the event produced on a particular topic. My test looks like as below:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class MyTestClass {

@BeforeAll
static void beforeAll() {
        KafkaContainer kafka = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:6.0.0"));
        kafka.setPortBindings(Arrays.asList("9092:9092", "9093:9093", "2181:2181"));
        kafka.start();
   }

@Test 
void basicTest() {
       produceEvent(onTopicA, message);
       await.ForCertainCondition();
       Assert.ThatEventConsumedBySpringBootApp();
   }
}
```

**The strange thing which I am facing is when I run above test, my springboot app does not consume the event produced in the test.** But if I keep  a connection alive in my terminal using Kafka binaries as `bin/kafka-console-consumer.sh --topic onTopicA --bootstrap-server localhost:9093 --from-beginning`, the test works as expected. Not able to figure it out what could be the reason.

**Comment by priyanshus** [comment]
Let me know if one needs my test to reproduce the issue, I have a public repository of above test.

**Comment by bsideup** [comment]
You should use `KafkaContainer#getBootstrapServers()` to talk to the instance, as per the docs:
https://www.testcontainers.org/modules/kafka/

**Comment by priyanshus** [comment]
Connection is fine as I am able to produce the events.
