### ISSUE TITLE
Need a way to specify custom database configuration when using a 'tc' JDBC URL

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#36]
e.g. for a MySQL container type, we need a way to specify a custom `my.ini` file as part of the URL. e.g. `jdbc:tc:mysql://hostname/databasename?TC_MY_INI=somepath/my.ini`

**Comment by swissarmykirpan** [comment]
Does the ini file then exist within the container? 
If yes - Wouldn't it be better/nicer to inject an ini file in?

**Comment by rnorth** [comment]
Ah no, the ini file would be injected via a volume/bind. 

:)

**Comment by swissarmykirpan** [comment]
Cool - just validating my assumption :)

**Comment by rnorth** [comment]
This is done for MySQL, which AFAICT is the database which most needs it (other DBs are more configurable after launch)... I'll close this for now, and if we need this feature for other DBs we should raise a separate ticket for each.
