### ISSUE TITLE
gitlab pipeline + docker 20.10.0 + Testcontainers 1.15.1 - Can not connect to Ryuk at 172.17.0.1:49153

### ISSUE THREAD

**Issue by rain2581** [testcontainers/testcontainers-java#3601]
Hi. Since last Friday after moving to docker 20.10.0 we had a problem with   Testcontainers and No such image: testcontainers/ryuk:0.3.0" and were waiting for the fix in 1.15.1
Today we have changed to new version 1.15.1 and got another error
Can not connect to Ryuk at 172.17.0.1:49153 Connection refused
<img width="1670" alt="Screen Shot 2020-12-14 at 2 50 19 PM" src="https://user-images.githubusercontent.com/10186749/102087118-bebf8f00-3e21-11eb-829f-cc43505a7b58.png">

**Comment by max402** [comment]
Set environment variable TESTCONTAINERS_RYUK_DISABLED=true helped in my case

**Comment by rain2581** [comment]
Works. Thanks @max402
