### ISSUE TITLE
Remove wait from excluded dependencies

### ISSUE THREAD

**Issue by ppartarr** [testcontainers/testcontainers-java#3605]
After upgrading from 1.14.3 to 1.15.1, I am getting this error:
```
The import org.testcontainers.containers.wait.Wait cannot be resolved
```

It seems like this comment in the build.gradle was ignored before the latest release: 
https://github.com/testcontainers/testcontainers-java/blob/1.15.1/core/build.gradle#L92

Any chance you can re-include them?

**Comment by bsideup** [comment]
It was deprecated for many releases and got removed.

Use `org.testcontainers.containers.wait.strategy.Wait` instead.

**Comment by ppartarr** [comment]
I see, thanks!  👍
