### ISSUE TITLE
Bind#getPath different between 1.15.0 and 1.15.1

### ISSUE THREAD

**Issue by wimdeblauwe** [testcontainers/testcontainers-java#3614]
When using Testcontainers 1.15.0, then the String returned from getPath() of a `Bind` (returned via `getBinds()` on the container) will have a trailing slash (`/`). E.g. `/Users/wdb/projects/testcontainers-cypress/target/test-classes/e2e/`

However, when running under Testcontainers 1.15.1, the trailing slash is no longer there: E.g. `/Users/wdb/projects/testcontainers-cypress/target/test-classes/e2e`.

Is this an intentional change? It currently breaks testcontainers-cypress. I can work around this on my side, but I wanted to be sure the change was intentional. I could not find anything in the release notes related to it.

**Comment by bsideup** [comment]
@wimdeblauwe could you please provide more info on how it breaks testcontainers-cypress? Do you assume the trailing slash?

**Comment by wimdeblauwe** [comment]
`testcontainers-cypress` has an option to automatically remove the test reports before the test run starts. By default, this assumes a path of `target/test-classes/e2e/cypress/reports/mochawesome`.
The deletion is done running in the container via `rm -rf path/in/container`. This is the method that converts the path on the host to the corresponding path in the container:

```
    @Nonnull
    private String getReportsPathInContainer() {
        String pathOnHost = gatherTestResultsStrategy.getReportsPath().toAbsolutePath().toString();
        String pathInContainer = null;
        List<Bind> binds = getBinds();
        for (Bind bind : binds) {
            String path = FilenameUtils.separatorsToSystem(bind.getPath());
            if (pathOnHost.startsWith(path)) {
                pathInContainer = pathOnHost.substring(path.length());
            }
        }

        if (pathInContainer == null) {
            throw new IllegalArgumentException("Could not find matching container path in the binds: " + binds);
        }
        return pathInContainer;
    }
```

Using Testcontainers 1.15.0:
* `pathOnHost` is for example `/Users/wdb/Projects/testcontainers-cypress/target/test-classes/e2e/cypress/reports/mochawesome`
* `path` from the `Bind` is `/Users/wdb/Projects/testcontainers-cypress/target/test-classes/e2e/`
* The resulting `pathInContainer` is `cypress/reports/mochawesome`
* Doing `rm -rf cypress/reports/mochawesome` does the expected thing

Using Testcontainers 1.15.1:

* `pathOnHost` is for example `/Users/wdb/Projects/testcontainers-cypress/target/test-classes/e2e/cypress/reports/mochawesome`
* `path` from the `Bind` is `/Users/wdb/Projects/testcontainers-cypress/target/test-classes/e2e`
* The resulting `pathInContainer` is `/cypress/reports/mochawesome`
* Doing `rm -rf /cypress/reports/mochawesome` would _not_ be good

**Comment by bsideup** [comment]
@wimdeblauwe ah, I see. I am afraid this is an implementation detail that was assumed by Cypress but we never guaranteed it to work like that.

We removed `toURI()` in #3514 because it was causing issues on Windows, and I guess this is a consequence.
Consider using the file system API and checking whether the path is a folder or not instead of relying on the presence of `/`, because `/foo/bar` and `/foo/bar/` are two valid binds from the file system point of view.

**Comment by wimdeblauwe** [comment]
@bsideup What do you mean exactly with "the file system API" ?

**Comment by wimdeblauwe** [comment]
I can get it working with both 1.15.0 and 1.15.1 by using `Path#relativize()`:

```
    @Nonnull
    private String getReportsPathInContainer() {
        Path pathOnHost = gatherTestResultsStrategy.getReportsPath().toAbsolutePath();
        String pathInContainer = null;
        List<Bind> binds = getBinds();
        for (Bind bind : binds) {
            String path = FilenameUtils.separatorsToSystem(bind.getPath());
            if (pathOnHost.startsWith(path)) {
                pathInContainer = Paths.get(path).relativize(pathOnHost).toString();
            }
        }

        if (pathInContainer == null) {
            throw new IllegalArgumentException("Could not find matching container path in the binds: " + binds);
        }
        return pathInContainer;
    }
```

I will update Testcontainers-Cypress like this. Thanks for the help!

**Comment by bsideup** [comment]
> @wimdeblauwe  
> What do you mean exactly with "the file system API" ?

Sorry, I wasn't clear :) Something like `new File(hostPath).isDirectory()`, or `relativize` as you did 👍

I am glad that you was able to fix the issue, and the new code IMO looks better and more bulletproof 💯

**Comment by wimdeblauwe** [comment]
Indeed, the code is a lot better like this.

**Comment by aaronjwhiteside** [comment]
FYI this was reported here, https://github.com/testcontainers/testcontainers-java/issues/3614
