### ISSUE TITLE
Testing a error scenario by stopping and then restarting container => new port chose each time

### ISSUE THREAD

**Issue by cer** [testcontainers/testcontainers-java#3615]
I wanted to test the scenario where my Spring Boot-based service's DB is temporarily down.
It looks like calling stop()/start() recreates the DB container on a different random port.
It would be handy to be able to restart on the same host port or be able to specify the host port.

**Comment by bsideup** [comment]
For this, I would highly recommend restarting the process inside the container (with exec)

Docker does not allow restarting the containers reliability without loosing the ports, see https://github.com/testcontainers/testcontainers-java/issues/606 for more details :)
