### ISSUE TITLE
Error: java.lang.NoSuchMethodError: org.testcontainers.utility.DockerImageName.parse with the version 1.15.1

### ISSUE THREAD

**Issue by joedayz** [testcontainers/testcontainers-java#3616]
I am getting it error in my project with java 8 with the version 1.15.1 of testcontainers:

```
public class DatabaseResource implements QuarkusTestResourceLifecycleManager {

    private static final PostgreSQLContainer<?> DATABASE = new PostgreSQLContainer<>("postgres:10.5")
        .withDatabaseName("heroes_database")
        .withUsername("superman")
        .withPassword("superman")
        .withExposedPorts(5432);
...

}
```

The dependencies are:

    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>1.15.1</version>
    </dependency>
    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>postgresql</artifactId>
        <version>1.15.1</version>
    </dependency>

My docker for mac is:

version: 3.0.2
engine: 20.10.0
compose: 1.27.4
Use gRPC FUSE for file sharing is disabled 

The error is:

[ERROR] io.quarkus.workshop.superheroes.hero.HeroResourceTest.shouldGetInitialItems  Time elapsed: 0.022 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoSuchMethodError: org.testcontainers.utility.DockerImageName.parse(Ljava/lang/String;)Lorg/testcontainers/utility/DockerImageName;

Some idea, please?

Joe

**Comment by bsideup** [comment]
Hi Joe!

Something is wrong with your classpath and `org.testcontainers:testcontainers` dependency is older than 1.15.0. Use your build tool’s capabilities to detect what overrides the version (I see you’re using Quarkus, perhaps it is coming from their parent BOM)
