### ISSUE TITLE
KafkaContainer: Error while fetching metadata with correlation id LEADER_NOT_AVAILABLE

### ISSUE THREAD

**Issue by kcmvp** [testcontainers/testcontainers-java#3647]
Environment :  Macos  11.0.1
Docker Env: Docker version 20.10.0, build 7287ab3
jar version:

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>kafka</artifactId>
            <version>1.15.1</version>
            <scope>test</scope>
        </dependency>

code
```@TestConfiguration
public class IntegratedEnvironment implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    private static final Logger logger = LoggerFactory.getLogger(IntegratedEnvironment.class);

    static final KafkaContainer kaf = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:5.5.1"));

    @PreDestroy
    public void stop() {
        kaf.stop();
    }
    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
        kaf.withEnv("KAFKA_ADVERTISED_HOST_NAME","localhost");
        kaf.start();
        TestPropertySourceUtils.addInlinedPropertiesToEnvironment(applicationContext, "spring.kafka.producer.bootstrap-servers=" + kaf.getBootstrapServers());
        TestPropertySourceUtils.addInlinedPropertiesToEnvironment(applicationContext, "spring.kafka.consumer.bootstrap-servers=" + kaf.getBootstrapServers());
    }
}
```

error message:

```
2020-12-30 22:31:41.997  INFO 8127 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 2.5.0
2020-12-30 22:31:41.997  INFO 8127 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 66563e712b0b9f84
2020-12-30 22:31:41.998  INFO 8127 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1609338701997
2020-12-30 22:31:42.155  WARN 8127 --- [ntainer#0-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-localGroup-1, groupId=localGroup] Error while fetching metadata with correlation id 2 : {payment=LEADER_NOT_AVAILABLE}
2020-12-30 22:31:42.155  WARN 8127 --- [ook-Pro.local-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=Kens-MacBook-Pro.local-1] Error while fetching metadata with correlation id 1 : {payment=LEADER_NOT_AVAILABLE}
2020-12-30 22:31:42.157  INFO 8127 --- [ntainer#0-0-C-1] org.apache.kafka.clients.Metadata        : [Consumer clientId=consumer-localGroup-1, groupId=localGroup] Cluster ID: nkMWp3e5RLK61Bi-g254xw
```

**Comment by kcmvp** [comment]
can use this repository to reproduce this issue 
https://github.com/kcmvp/kaf-cookbook

**Comment by mbugua-samuel** [comment]
Same issue here +1

**Comment by Vostan** [comment]
Is there any news about this issue?

**Comment by enesaltinok** [comment]
Same issue +1

**Comment by bsideup** [comment]
@kcmvp why do you set `KAFKA_ADVERTISED_HOST_NAME` to `localhost`?

Also, I do not see any errors, only warnings.

Please see https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/test/java/org/testcontainers/containers/KafkaContainerTest.java for an example of `KafkaContainer` with `KafkaProducer`/`KafkaConsumer`.

**Comment by enesaltinok** [comment]
I'm using spring and creating a new topic fixed it for me.

```
@Bean
@Primary
public NewTopic newTopic() {
    return TopicBuilder.name("topic-name")
        .compact()
        .build();
}
```

**Comment by emrekgn** [comment]
I can also confirm @enesaltinok 's answer. When we create the topic beforehand, there is no issue.
That may also mean this is not related to _testcontainers_ but actually something about how Kafka handles auto-created topics.

**Comment by Vostan** [comment]
Thanks @enesaltinok 
@emrekgn it seems to me also that this is something related to Kafka itself, not TestContainers.

So if you ask me this issue must be closed :) thanks for tips

**Comment by vivek-rao-1985** [comment]
I think [this](https://www.bigdatainrealworld.com/how-to-fix-the-leader_not_available-error-in-kafka/) might have something to do with the error. I don't see an env entry for ```KAFKA_ADVERTISED_LISTENERS``` in the constructor call. Perhaps this should be added?

**Comment by remal** [comment]
I'm also facing this issue. What could I do to fix it?

**Comment by eddumelendez** [comment]
This should not be an issue nowadays. See https://github.com/wurstmeister/kafka-docker/issues/233#issuecomment-347303518
