### ISSUE TITLE
Error using .dockerenv to detect running in a container

### ISSUE THREAD

**Issue by olausson** [testcontainers/testcontainers-java#3681]
We are running a Jenkins server in GKE. Have not investigated why, but the file "/.dockerenv" that you use to detect that we are in a docker container, does not exist in our environment.

Things seem to work if we create this file in the Jenkins pod when it starts.

It may be beneficial for others if you add to the documentation that this file need to exist; 
https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/

**Comment by bsideup** [comment]
This file is automatically created by Docker, there is no need to create it manually.

It can be that Kubernetes' recent change (the removal of `docker-shim`) have affected you, and you no longer run your build inside a _Docker_ container (but containerd-based). If that's the case, consider setting `TESTCONTAINERS_HOST_OVERRIDE` environment variable.
