### ISSUE TITLE
Sidebar url's for 'Test framework integration' not working correctly when navigated to from a 3rd party site (google)

### ISSUE THREAD

**Issue by Razsiel** [testcontainers/testcontainers-java#3686]
Hi, 

I was googling to find more information about testcontainers and landed on [this](https://www.testcontainers.org/test_framework_integration/junit_5) (https://www.testcontainers.org/test_framework_integration/junit_5) page. 

Having read the documentation on this page I decided to click on the sidebar's "Test framework integration/JUnit 4" link and noticed it went to a 404 Not Found. Examining the href of the link I found it's missing the middle part of the url ('/test_framework_integration/').

 Other url's in the sidebar are correct and navigating to those pages and checking the href again it's correct. I assume this part of some state-issue.

Below is an image of the href (note the url in the bottom left and the highlighted JUnit 4)

<img src="https://i.ibb.co/5kwqLXQ/test-containers.png" height="500px"></a>

**Comment by eddumelendez** [comment]
This is due to how mkdocs works by default. In this case, the issue is because the initial url https://www.testcontainers.org/test_framework_integration/junit_5 should be https://www.testcontainers.org/test_framework_integration/junit_5/ instead, note the trailing slash at the end.
