### ISSUE TITLE
Can not connect to Ryuk at localhost:49156 on Windows, Docker Desktop 3.1.0, Engine 20.10.2

### ISSUE THREAD

**Issue by mrsalt** [testcontainers/testcontainers-java#3689]
I just updated to Docker Desktop 3.1.0 and now I'm seeing this exception when I try to start tests:

```
[testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:49156
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:160)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:158)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

I tried setting environment variable TESTCONTAINERS_RYUK_DISABLED=true, but this had no effect.
I also tried Docker Settings -> General -> "Expose daemon on tcp://localhost:2375" without TLS, but this did not help either.

**Comment by bsideup** [comment]
@mrsalt please share full logs

**Comment by mrsalt** [comment]
@bsideup Where do I find the logs?  Is there a troubleshooting guide?
Also, I just updated to 3.1.0, 3.0.4 was working.

**Comment by bsideup** [comment]
@mrsalt see https://www.testcontainers.org/supported_docker_environment/logging_config/

**Comment by mrsalt** [comment]
![About_Docker_Desktop](https://user-images.githubusercontent.com/3916784/104612851-dae26600-5643-11eb-8abf-2e231cd9741a.png)

**Comment by mrsalt** [comment]
@bsideup , sorry, I've been trying to get more detailed logs but I don't know how to get logback working.

Here's what I've tried:
1.  Add logback dependency in my project's pom.xml:
```
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
			<scope>test</scope>
		</dependency>
```
2. Copy the XML snippet you shared at https://www.testcontainers.org/supported_docker_environment/logging_config/ into logback-test.xml, save this file into my project's src/test/resources
3. While debugging my test, `getClass().getClassLoader().getResource("logback-test.xml")` returns a URL, but `getClass().getClassLoader().getResource("/logback-test.xml")` returns NULL.
4. I also tried -Dlogback.configurationFile, but this didn't make a difference either.

Because the format of the log output isn't changing, it appears logback is not receiving the logging and providing extra details from org.testcontainers.  See attached 
[test-output.txt](https://github.com/testcontainers/testcontainers-java/files/5815862/test-output.txt)
(I've replaced a few paths with <internal> where details are private/not important)

I noticed that my classpath also includes log4j...  I'll try to get that removed (since I'm not that good at log4j configuration) and just get logback in my classpath.

**Comment by bsideup** [comment]
@mrsalt thanks for sharing the logs! log4j would also be fine, logback was given as a (preferred) example.

Is it really all the logs you get? Usually, when Ryuk fails to start, Testcontainers would print its logs for debugging - that's the part I was looking for, actually :)

Alternatively, you could `docker ps -a` and then `docker logs $RYUK_ID`

**Comment by mrsalt** [comment]
RYUK is starting up fine --
```
$ docker logs df3f9f6642b9
2021/01/14 18:28:33 Pinging Docker...
2021/01/14 18:28:33 Docker daemon is available!
2021/01/14 18:28:33 Starting on port 8080...
2021/01/14 18:28:33 Started!
```
It's just the connection to it that's failing...

**Comment by mrsalt** [comment]
@bsideup , thanks for your help and I am sorry to waste your time.  I downgraded to Docker 3.0.4 -- and the problem persisted.  So I restarted Windows.  Voila!  Problem solved.  I've also updated to Docker 3.1.0 again, and the problem is not occurring.  So there is no issue with the Docker 3.1.0 update.  Just Windows being flaky.  (Or who knows really...  There are a lot of pieces in the stack here).

**Comment by bsideup** [comment]
@mrsalt thanks for sharing! 👍

We have seen similar reports of this flaky behaviour of Docker for Windows, where a simple restart helped, which makes me think that it will eventually be fixed in Docker for Windows as this is not something we can change on our side :)

**Comment by javageek79** [comment]
I just faced the exact same error message on my windows 10 system.

running `netsh interface ipv4 show excludedportrange protocol=tcp`, I found out, that the port mentioned, was within a excluded port range on my machine. The following range was listed amongst others... `49152 . . . 49251`

**Comment by KaiStapel** [comment]
I faced the very same problem many times now. It is super annoying if you have to restart windows for this to go away. It would be better if testcontainers could somehow try to prevent taking a restricted port on windows (see @javageek79 's comment above).

**Comment by bsideup** [comment]
@KaiStapel I agree that it is annoying :) The port assignment is delegated to Docker (Testcontainers itself doesn't pick any ports), so I would recommend reporting this bug to Docker, as there is not much we can do, unfortunately.

**Comment by KaiStapel** [comment]
@bsideup There already is: https://github.com/docker/for-win/issues/3171
