### ISSUE TITLE
Direct support for Spring

### ISSUE THREAD

**Issue by Marssmart** [testcontainers/testcontainers-java#3691]
Hi all

First of all let me say that we have been using Testcontainers on our projects for while now ,and we absolutely love it. 
We've been creating our own implementation that extend MongoContainer,KafkaContainer,etc and add logic to bind the url's of the containerized services to the properties from Spring modules, like **spring.data.mogndob.uri** or **spring.kafka.bootstrap-servers**. This than in affect allows you to just throw the container in and your @SpringBootTest will automatically connect to it. Which effectively allows you to start your whole app as it would be in normal operation.

The shortest implementation of this I could compile would be something like this(Junit 5):

```
public class TestMongo extends MongoDBContainer implements BaseTestContainer {

    public static final String DEFAULT_IMAGE = "mongo:4.4.3";
    public static final String DATABASE_PROP = "spring.data.mongodb.database";
    public static final String URI_PROP = "spring.data.mongodb.uri";

    private boolean springPropsInitialized;

    public TestMongo() {
        super(DEFAULT_IMAGE);
    }

    @Override
    public void beforeTestExecution(ExtensionContext extensionContext) {
        if (!springPropsInitialized) {
            final ConfigurableApplicationContext context = (ConfigurableApplicationContext) SpringExtension.getApplicationContext(extensionContext);

            final String url = Optional.of(context.getEnvironment())
                    .map(a -> a.getProperty(DATABASE_PROP))
                    .map(this::getReplicaSetUrl)
                    .orElse(this.getReplicaSetUrl());

            TestPropertySourceUtils.addInlinedPropertiesToEnvironment(context, format("%s=%s", URI_PROP, url));
            springPropsInitialized = true;
        }
    }
}
```

Which can be than used in a test like this

```
@Testcontainers
@SpringBootTest(classes = TestMongoTest.TestConfig.class)
public class TestMongoTest {

    @Container
    @RegisterExtension
    static TestMongo mongo = new TestMongo();

    @Autowired
    MongoTemplate mongoTemplate;

    @RepeatedTest(5)
    @Execution(ExecutionMode.CONCURRENT)
    void testStartedAndReady() {
        mongoTemplate.getCollectionNames().forEach(System.out::println);
    }

    @Configuration
    @EnableAutoConfiguration
    @EnableMongoRepositories
    static class TestConfig {

    }
}
```

I was thinking about contributing a module that would have variants of all the available containers with this kind of compatibility to Spring. The use of Spring APIs is minimal, so the compatibility going forward or backwards should be great. I've tested this with Spring boot 2.2.12,.2.3.7 and 2.4.1 and it worked on all of those(and I'm sure it would work wit even older versions)

Containers/Modules we actively use with this:

- Mongo
- Kafka
- MailHog
- SMTP
- Oracle 
- Postgres
- Sold

Thing's I haven't tested/tried:

- behavior if the container would not be static
- trying to implement the same for Junit4

Does this sound interesting ?

**Comment by Saljack** [comment]
Do you mean this?:
https://github.com/Playtika/testcontainers-spring-boot

**Comment by eddumelendez** [comment]
Spring Boot 3.1.0 will be adding Service Connections with directly support for [Testcontainers](https://docs.spring.io/spring-boot/docs/3.1.0-RC1/reference/htmlsingle/#features.testing.testcontainers). There is also a section about [Dev Mode](https://docs.spring.io/spring-boot/docs/3.1.0-RC1/reference/htmlsingle/#features.testing.testcontainers.at-development-time)
