### ISSUE TITLE
Allow to disable ryuk and check by classpath properties

### ISSUE THREAD

**Issue by scalony2002** [testcontainers/testcontainers-java#3707]
Ryuk can be disabled only by setting env variable TESTCONTAINERS_RYUK_DISABLED

checks can be disabled either by setting TESTCONTAINERS_CHECKS_DISABLE=true or by property in user properties 
checks.disable=true. Unfortunately check.disable does not work when set in classpath properties.

It would be nice to also add ryuk.disabled option as configurable by user or classpath properties, so all the configuration can be in one place

**Comment by bsideup** [comment]
Disabling Ryuk is highly not recommended. It should be a (last resort) decision of a user to disable it, an explicit one. Disabling it at project level would mean that some users may unexpectedly start getting stale containers.

Also... could you please commend why you would want to disable it?

Could you please clarify why you wanted to disable it, btw?

**Comment by AnandTiwari1997** [comment]
@bsideup, keep getting cannot connect to ryuk, connection refused exception that is why want to disable it.

**Comment by kiview** [comment]
@AnandTiwari1997 I think the root issue is that you get that exception. There is an existing mechanism for disabling Ryuk (using the ENV variable), but this is often used as a bandaid to workaround other issues with the environment (often networking-related). 

As said before, there are no plans to allow disabling Ryuk at the project level.

**Comment by hfhbd** [comment]
Do you have any plans to allow disabling Ryuk user-wide using `.testcontainers.properties in user's home folder.` to configure Podman only once and not per ENV for each project (to not forget it or accidentally check it in)?
