### ISSUE TITLE
UnsupportedOperationException: View 'unix' not available

### ISSUE THREAD

**Issue by glebsts** [testcontainers/testcontainers-java#371]
Hello,
thank you for cool library. I was impressed at Geekout and started building project with that.
My desktop OS is Windows. 

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/MountableFile.java#L269 
`try {
            return (int) Files.getAttribute(path, "unix:mode");
        } catch (IOException e) {
            // fallback for non-posix environments
.....`

If we look at javadoc for Files.getAttribute(), and its source in JDK, we can see and trace that in case of not-existing attribute view (as 'unix' if file is on windows file system), UnsupportedOperationException is thrown, not IOException. Everything fails here without any fallback to non-posix env. 

Is it a (known) bug, or I am doing something wrong?

**Comment by rnorth** [comment]
Ah, thanks for using the library and reporting this @glebsts.

It looks like this is a bug - I must have missed that it's an UnsupportedOperationException that's thrown, so I apologise. We can fix this fairly easily, though.

**Comment by glebsts** [comment]
Added PR https://github.com/testcontainers/testcontainers-java/pull/376

Wonder why selenium tests failed on that? https://travis-ci.org/testcontainers/testcontainers-java/jobs/244861859

**Comment by bsideup** [comment]
Hi @glebsts,

Flaky test, I'll re-trigger. See #373
