### ISSUE TITLE
Is the new DSL still on the roadmap?

### ISSUE THREAD

**Issue by raman-nbg** [testcontainers/testcontainers-java#3715]
I found slides about a new DSL for testcontainers on [speakerdeck.com](https://speakerdeck.com/bsideup/geecon-2019-testcontainers-a-year-in-review?slide=74). Is this still on the roadmap?

**Comment by kiview** [comment]
Hi @raman-nbg,
yes, it is, but there is no ETA and we can't comment on when and how it will eventually land in Testcontainers at this point in time.

**Comment by bsideup** [comment]
Hey @raman-nbg,

The author of the deck here :) Yes, we do plan to work on this new DSL. However, the covid global situation have affected our plans and dramatically reduced our workpower, hence the delay.

That said, @rnorth and I had a very successful mini hackathon at @kiview's wedding (OSS is a family, lol :D) where we drafted most of the ideas behind this new DSL. We even came up with a plan how it can be added to 1.x, to make it easier to migrate between the versions.


I am going to close this issue (as it is rather a question. Consider asking questions [on our Slack](http://slack.testcontainers.org), btw), but... Stay tuned! ;)
