### ISSUE TITLE
Remove dependency on JUnit 4 API in Testcontainers core

### ISSUE THREAD

**Issue by gastaldi** [testcontainers/testcontainers-java#3756]
It would be nice if `Testcontainers core` didn't depend on the JUnit 4 API (`junit:junit:4.12`), given that this dependency is available even when your tests only depend on the `junit-jupiter` dependency.

**Comment by bsideup** [comment]
Duplicate of #970

**Comment by gastaldi** [comment]
Oops, I missed that one while searching. Thanks!
