### ISSUE TITLE
Aerospike enterprise docker image not initializing.

### ISSUE THREAD

**Issue by ankitjain1997** [testcontainers/testcontainers-java#3776]
I am trying to create a generic test-container using aerospike enterprise edition docker image. (https://github.com/aerospike/aerospike-server-enterprise.docker) 

When I run the command mentioned in the readme of this github repo, it works properly I am able to connect and execute commands. 

However, I am not able to mount the directory from test-containers (docker -v tried .withCommand() still facing same error) .  Getting following error: 

`java.lang.IllegalArgumentException: Resource with path  could not be found on any class loader.`

Has anyone else faced this issue ? 

Any help would be appreciated.

**Comment by bsideup** [comment]
@ankitjain1997 please share your code, otherwise it is impossible to understand that fails and why.

**Comment by ankitjain1997** [comment]
```
aerospikeContainer
                    .withExposedPorts(3000, 3001, 3002, 3003)
                    .withEnv("NAMESPACE", "gpl2")
            .withFileSystemBind("/opt/aerospike","/opt/aerospike/etc",BindMode.READ_ONLY)
                    .withEnv("FEATURE_KEY_FILE", "path to feature file");
```
docker being used to run locally -
`sudo docker run -tid --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 -v "$(pwd):/opt/aerospike" -e "FEATURE_KEY_FILE=~/feature.conf" aerospike/aerospike-server-enterprise`

The code snippet being used does not work even if the path is changed to any other location.


Error thrown -> `java.lang.IllegalArgumentException: Resource with path could not be found on any class loader.`

Is there any other way to pass the `docker -v` option to test-container?

**Comment by bsideup** [comment]
@ankitjain1997 could you please also share more logs (and full exception, not just the message)?

Also, in your `docker run`, you mount a folder under `/opt/aerospike`, while with `withFileSystemBind`, the destination is `/opt/aerospike/etc` - is it intentional?

**Comment by ankitjain1997** [comment]
@bsideup 

I had made some changes and now getting following error while starting the container. 


`java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:470)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:326)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:324)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:312)
        at com.tests.impl.AerospikeContainerClient.lambda$start$0(AerospikeContainerClient.java:90)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
14:51:34.810 [RxCachedThreadScheduler-1] ERROR 🐳 [aerospike/aerospike-server-enterprise] - Log output from the failed container:
link eth0 state up

link eth0 state up in 0

Feb 09 2021 09:20:34 GMT: INFO (as): (as.c:306) <><><><><><><><><><>  Aerospike Enterprise Edition build 5.4.0.3  <><><><><><><><><><>

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) # Aerospike database configuration file.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) # This stanza must come first.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) service {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   user root

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   group root

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   paxos-single-replica-limit 1 # Number of nodes where the replica count is automatically reduced to 1.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   pidfile /var/run/aerospike/asd.pid

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # service-threads 6 # default is 5 x cpus

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # transaction-queues 6  # obsolete as of 4.7

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # transaction-threads-per-queue 4 #obsolete as of 4.7

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   proto-fd-max 15000

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   feature-key-file -~/features.conf
Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) logging {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # Log file must be an absolute path.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   file /dev/null {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           context any info

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # Send log messages to stdout

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   console {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           context any info 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) network {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   service {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           address any

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           port 3000

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # Uncomment the following to set the `access-address` parameter to the

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # IP address of the Docker host. This will the allow the server to correctly

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # publish the address which applications and other nodes in the cluster to

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # use when addressing this node.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # access-address <IPADDR>

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   heartbeat {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)         address any

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # mesh is used for environments that do not support multicast

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           mode mesh

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           port 3002

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # use asinfo -v 'tip:host=<ADDR>;port=3002' to inform cluster of

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           # other mesh nodes

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           interval 150

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           timeout 10

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   fabric {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)       address any

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           port 3001

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   info {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)       address any

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           port 3003

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) namespace gpl2 {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   replication-factor 2

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   memory-size 1G

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   default-ttl 30d # 5 days, use 0 to never expire/evict.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   nsup-period 120 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   #       storage-engine memory

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # To use file storage backing, comment out the line above and use the

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   # following lines instead.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) 

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   storage-engine device {

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           file /opt/aerospike/data/gpl2.dat

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           filesize 4G

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)           data-in-memory true # Store data in memory in addition to file.

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937)   }

Feb 09 2021 09:20:34 GMT: INFO (config): (cfg.c:3937) }

Feb 09 2021 09:20:34 GMT: WARNING (misc): (fetch.c:211) unable to open file -~/features.conf: No such file or directory

Feb 09 2021 09:20:34 GMT: CRITICAL (config): (features_ee.c:129) failed to get feature key -~/features.conf

Feb 09 2021 09:20:34 GMT: WARNING (as): (signal.c:166) SIGINT received, shutting down Aerospike Enterprise Edition build 5.4.0.3 os debian9

Feb 09 2021 09:20:34 GMT: WARNING (as): (signal.c:169) startup was not complete, exiting immediately
`

Mounting of the directory is still the issue AFAIK. Could you please guide how to pass the `docker -v` option through code that should solve the problem. 

Also, the destination will be the same that was a typo.

**Comment by bsideup** [comment]
@ankitjain1997 I think the failure is obvious:
> unable to open file -~/features.conf: No such file or directory

Most probably, when you run it from CLI, `~` gets expanded into something like `/home/your_user/`. Consider replacing with an explicit value, as it is static anyways.

> Could you please guide how to pass the docker -v option through code that should solve the problem.

P.S. `withFileSystemBind` is the correct API to use.

---

I am closing this issue as it does not seem to be related to Testcontainers and rather a misconfiguration.

**Comment by ankitjain1997** [comment]
@bsideup I replaced `~/features.conf` with an explicit value. 

In the logs which I presented above, I just replaced the entire path with `~/features.conf` so as not to disclose sensitive company information.  

I already tried replacing the path with the absolute and relative path.

**Comment by bsideup** [comment]
@ankitjain1997 I recommend asking the Aerospike community for help. The container starts, files are mounted, but the process fails, which means that the process is misconfigured.

FTR other users were successful with Testcontainers and Aerospike:
https://github.com/testcontainers/testcontainers-java/issues/153#issuecomment-223946490
