### ISSUE TITLE
authorization denied by plugin hbm: Volume /var/run/docker.sock:/var/run/docker.sock:rw is not allowed to be mounted"

### ISSUE THREAD

**Issue by mpet** [testcontainers/testcontainers-java#3777]
I am trying 1.15.0

DEBUG : Cmd: org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl@3d3ba765[name=testcontainers-ryuk-ef45fd0e-f957-4196-b56a-46452d36cf78,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env=<null>,cmd=<null>,healthcheck=<null>,argsEscaped=<null>,entrypoint=<null>,image=testcontainers/ryuk:0.3.0,volumes=com.github.dockerjava.api.model.Volumes@57ac5227,workingDir=<null>,macAddress=<null>,onBuild=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@4ba302e0,stopSignal=<null>,stopTimeout=<null>,hostConfig=HostConfig(binds=[/var/run/docker.sock:/var/run/docker.sock:rw], blkioWeight=null, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=null, capAdd=null, capDrop=null, containerIDFile=null, cpuPeriod=null, cpuRealtimePeriod=null, cpuRealtimeRuntime=null, cpuShares=null, cpuQuota=null, cpusetCpus=null, cpusetMems=null, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=null, groupAdd=null, ipcMode=null, cgroup=null, links=[], logConfig=LogConfig(type=null, config=null), lxcConf=null, memory=null, memorySwap=null, memoryReservation=null, kernelMemory=null, networkMode=null, oomKillDisable=null, init=null, autoRemove=true, oomScoreAdj=null, portBindings=null, privileged=false, publishAllPorts=true, readonlyRootfs=null, restartPolicy=null, ulimits=null, cpuCount=null, cpuPercent=null, ioMaximumIOps=null, ioMaximumBandwidth=null, volumesFrom=null, mounts=null, pidMode=null, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=null, volumeDriver=null, shmSize=null, pidsLimit=null, runtime=null, tmpFs=null, utSMode=null, usernsMode=null, sysctls=null, consoleSize=null),labels={org.testcontainers=true},shell=<null>,networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,authConfig=<null>]

**com.github.dockerjava.api.exception.DockerException: Status 403: {"message":"authorization denied by plugin hbm: Volume /var/run/docker.sock:/var/run/docker.sock:rw is not allowed to be mounted"}**

We have limited access to docker.

Is there a workaround for this? What will happen if I disable ryuk?

I guess this is quite common in large organizations..

Any input?

br,

//mike

**Comment by bsideup** [comment]
@mpet Ryuk makes sure that containers are destroyed after the tests. You can disable it, but then `kill -9` your tests (e.g. by pressing "stop" on Jenkins' jobs) would leave containers running because there is nothing that would stop them.

BTW since the tests have access to `/var/run/docker.sock`, disallowing mounting of it makes little sense anyways.

I am going to close this issue as it is not actionable, but feel free to reach out to me on Slack if you need further assistance 👍
