### ISSUE TITLE
Missing Localstack services

### ISSUE THREAD

**Issue by ppalaga** [testcontainers/testcontainers-java#3785]
Comparing the entries in `org.testcontainers.containers.localstack.LocalStackContainer.Service` with https://github.com/localstack/localstack/tree/master/localstack/services gives the following diff:

LocalStackContainer.Service  | Localstack
-- | --
  | acm
API_GATEWAY | apigateway
CLOUDFORMATION | cloudformation
CLOUDWATCH | cloudwatch
CLOUDWATCHLOGS | logs
DYNAMODB | dynamodb
DYNAMODB_STREAMS | dynamodbstreams
  | ec2
  | es
  | events
FIREHOSE | firehose
IAM | iam
KINESIS | kinesis
KMS | kms
LAMBDA | awslambda
REDSHIFT | redshift
ROUTE53 | route53
S3 | s3
SECRETSMANAGER | secretsmanager
SES | ses
SNS | sns
SQS | sqs
SSM | ssm
STEPFUNCTIONS | stepfunctions
STS | sts

I wonder what needs to be done to support the missing services?

* Upgrade `LocalStackContainer.DEFAULT_TAG`
* Add the missing enum entries
* Anything else?

**Comment by ppalaga** [comment]
I'd like to try to fix this, but I'd like to understand the scope first. Could please somebody comment on the question above?

**Comment by maciejwalkowiak** [comment]
@ppalaga To use services that are missing in the `Services` enum, you can use `LocalStackContainer.EnabledService.named("ec2")` instead

**Comment by eddumelendez** [comment]
As @maciejwalkowiak mentioned, there is a way to do it and also, thanks to his contribution given that in latest versions of LocalStack, `SERVICES` is optional, this will not required anymore in the next release. See https://github.com/testcontainers/testcontainers-java/pull/6430
