### ISSUE TITLE
Docs for JDBC support are misleading for Spring boot 2.4.x

### ISSUE THREAD

**Issue by straurob** [testcontainers/testcontainers-java#3788]
The current documentation for the JDBC support states:

> For Spring Boot (Before version 2.3.0) you need to specify the driver manually spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

It seems as if this also true for Spring Boot 2.4.x. I'm running my application on Spring Boot 2.4.1. Without specifying this driver I get the following exception when starting a test:

`Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:tc:mariadb:10.4.16://localhost/mydb`

Setting the driver to `org.testcontainers.jdbc.ContainerDatabaseDriver` works.

**Comment by bsideup** [comment]
@straurob this sounds like a regression in Spring Boot. Consider reporting to them:
https://github.com/spring-projects/spring-boot/issues/new/choose
