### ISSUE TITLE
testcontainer initializationError while running a test suite

### ISSUE THREAD

**Issue by aiqency** [testcontainers/testcontainers-java#3811]
I have multiple test classes running the same docker-compose.

The suite fails with `initializationError` although each test passes when performed separately.

Similar question on [SO](https://stackoverflow.com/questions/66259110/testcontainer-initializationerror-while-running-a-test-suite).

Any help would be welcome.

**Comment by bsideup** [comment]
@aiqency please avoid double posting. We monitor both StackOverflow and GitHub issues.
