### ISSUE TITLE
Wait.forListeningPort() does not work for distroless images

### ISSUE THREAD

**Issue by lgathy** [testcontainers/testcontainers-java#3835]
Since distroless images do not contain a shell, the `InternalCommandPortListeningCheck` fails when called from `HostPortWaitStrategy`.
Would it be possible to make this check either optional or check if the files `/bin/sh` and `/bin/bash` exist inside the container before doing the checks?

**Comment by vcvitaly** [comment]
Relates to https://github.com/testcontainers/testcontainers-java/issues/3317

**Comment by jesperancinha** [comment]
I had an issue like this recently. I changed this to a health check and now it works. We did had to figure out a way to do the health check, but it works now.

**Comment by eddumelendez** [comment]
Closing as duplicated
