### ISSUE TITLE
RemoteDockerImage.get() fails when `list images` image name doesn't match `pull` name

### ISSUE THREAD

**Issue by pshapiro4broad** [testcontainers/testcontainers-java#384]
We have a case where our use of `RemoteDockerImage.get()` failed with the error `Retry limit reached while trying to pull image`. With logging we were able to determine that the `docker pull` step was successful but since the container name returned by `list images` didn't match the name passed to pull, it couldn't tell that it was loaded.

The returned container name had the prefix `docker.io/` added to it. We were able to fix this by adding the prefix to the name passed to the `RemoteDockerImage` constructor, but that broke when running it locally (on MacOS), where this prefix was stripped off in the response.

We are using two different versions of docker and running them in two different environments, which could account for these different behaviors. Unfortunately we're not able to use the same version of docker everywhere, so we've added code to work around this issue, by trying both versions of the name and using whichever one works.

Regardless of the different behaviors, it seems like in either case it was easy to create a docker image name that would cause `RemoteDockerImage` to fail. It would be better if there was a way to query docker about loaded images that didn't rely on an exact string match of the image name, since docker itself (apparently) considers the names to be interchangeable.

Docker versions:
On Linux: 1.12.6
On MacOS: 17.03.1-ce

**Comment by asafm** [comment]
Seems that the issue mentioned in RemoteDockerImage as fixed by
https://github.com/moby/moby/pull/11281. So we can break out of the while
loop when pull is succesfull and save the image name as requested by the
caller into the cache.

**Comment by pshapiro4broad** [comment]
I was wondering why the code wasn't written that way, since as far as I could tell `docker pull` would return an error if the pull failed. I guess the intent was leverage the existing code that checks for the case where the image already exists? But then why would the code have a retry unless there's a case where pull doesn't return an error _and_ the image wasn't pulled?

**Comment by kiview** [comment]
Is there an image that can be used for an integration test, to check for this bug?
