### ISSUE TITLE
As no valid configuration was found, execution cannot continue" error while running tests from Jenkins on the  CentOS Linux 7 

### ISSUE THREAD

**Issue by shijukuchelan1985** [testcontainers/testcontainers-java#3850]
Hi, 

**The environment:**
Host machine: AWS EC2 Jenkins(master-slave)  
I am using test containers-java in my project and have few integration tests which get executed when the build happens, these integration tests used to perform DB operations with Postgres(org.testcontainers:postgresql:1.15.2). 

This is my jenkins pipeline build stage
              steps {
                sh 'ls -la /var/run/docker.sock'
                sh 'docker -v'
                sh 'docker info'
                sh 'sudo usermod -a -G docker $USER'  //user=centos //             
                sh "docker build --target builder -t test-app."
            }     

I am getting the below error when the docker build happens
 
 Obtained Jenkinsfile from 2a11d91fb43ca687a4658f4704dabcec1c9w2422241697b
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on EC2 (ec2-default) - jenkins-ec2-builder (i-0c2222429) in /home/centos/workspace/test-app
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE 
Commit message: "Update Jenkinsfile" 
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] sh
+ ls -la /var/run/docker.sock
srw-rw----. 1 root docker 0 Mar  4 05:13 /var/run/docker.sock
[Pipeline] sh
+ docker -v
Docker version 19.03.12, build 48a6e2424
[Pipeline] sh
+ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad1233131133313429
 runc version: dc920232323223239dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.26GiB
 Name: ip-10-313-3-100.us-east-1. UU. 
 ID: FIVH:TJ4U:ZFAB:BPU4:MTEU:MNUR:K64F:2D4K:V7DG:OILJ:5CFZ:HCDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

[Pipeline] sh
+ sudo usermod -a -G docker centos
[Pipeline] sh
+ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
 
[Pipeline] sh
+ docker build --target builder -t test-app 

  **[Test worker] WARN org.testcontainers.utility.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
 [Test worker] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/opt/java/openjdk/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin])
  [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is not set.
 [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/root/.docker/run' does not exist.
 [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/0' does not exist.
 [Test worker] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
 [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
  [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
  [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue**

Any thoughts?

**Comment by bsideup** [comment]
You're building an image. There is no `/var/run/docker.sock` inside the container that builds the image.
