### ISSUE TITLE
Ryuk port is random or possible to set?

### ISSUE THREAD

**Issue by mpet** [testcontainers/testcontainers-java#3865]
Hi,

We are running testcontainers and we have docker installed on a separate server in a separate domain. The server where we run our testcontainer don't have access to all ports on the machine where we have docker installed. Which ports are used for Ryuk? Could it be configured?

//mike

**Comment by bsideup** [comment]
Hi @mpet.

Testcontainers uses random ports for everything, including Ryuk. You can disable Ryuk to unblock yourself, although this would mean that a killed test session could leave containers running.
