### ISSUE TITLE
Make TimescaleDB available with JDBC syntax

### ISSUE THREAD

**Issue by raynigon** [testcontainers/testcontainers-java#3890]
As a Developer i want to use TimescaleDB in Testcontainers similar to PostGIS.

Currently a PostGIS container can be started when following JDBC Url is given: 
`jdbc:tc:postgis:9.6-2.5:///databasename`

I want to have the same behavior for Timescale DB. I propose following JDBC Url: 
`jdbc:tc:timescaledb:///databasename`

**Comment by bsideup** [comment]
> I propose following JDBC Url

what is the official JDBC URL type for TimescaleDB?

**Comment by raynigon** [comment]
Same as the Postgres JDBC Url, since timescale DB is an Extension in PostgreSQL it works pretty similar to PostGIS.
