### ISSUE TITLE
Weird networking on Windows 10

### ISSUE THREAD

**Issue by kyrrek** [testcontainers/testcontainers-java#3892]
Hi.

I've had a lot of problems getting testcontainers to work with networking and Windows 10.
I've basically implemented the code from the "Creating custom networks" section from the homepage https://www.testcontainers.org/features/networking/ (except I've changed "foo" to "my-server" and "bar" to "my-client")

This does not work, with the following output from the client side:
```
Connecting to my-server:8080 (172.31.0.2:8080)
wget: can't connect to remote host (172.31.0.2): Connection refused
```
Which I interpret as the client being able to find the other container, but the connection is being cut by some intermediate means. 
The weird thing is that I have created the same example in WSL (not WSL2, neither on the client or docker backend) using shell scripts, and it works!

Here's a docker network inpect output of the one network created by me (docker-test-network) and the testcontainers one.

`[
    {
        "Name": "docker-test-network",
        "Id": "fa5c30c915cf245f3552dfe44ebc66604bb1cf7c698884526b88f274c47c1324",
        "Created": "2021-03-18T13:49:13.5312317Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.27.0.0/16",
                    "Gateway": "172.27.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    },
    {
        "Name": "7d511be3-6b13-4689-8414-3c5f21a38763",
        "Id": "a839ba7f7d9c03e3e90784ca1efac6e07a838012adbd7918f6133d6187ede883",
        "Created": "2021-03-18T14:30:03.9193692Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.0.0/20",
                    "Gateway": "192.168.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "24fd5d988e941945ac9f1933547455b81b69f94a07c63c52533a56ea0833f1ae": {
                "Name": "loving_dubinsky",
                "EndpointID": "d31747b09c7220289b9eb19ffc01b28476a8c3e86e1c86d5bfba9ad93f4d097a",
                "MacAddress": "02:42:c0:a8:00:02",
                "IPv4Address": "192.168.0.2/20",
                "IPv6Address": ""
            },
            "47be6ee2cb615636f542ae0b083fe4fa107611d59de1c4ed48ce87878547e0a0": {
                "Name": "admiring_austin",
                "EndpointID": "a1a2abaf5d51591f6819b4361ea61368b320a965f1b8eea444aa9e6fbeb235d0",
                "MacAddress": "02:42:c0:a8:00:03",
                "IPv4Address": "192.168.0.3/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "org.testcontainers": "true",
            "org.testcontainers.sessionId": "a554d7ae-ca99-4009-8baf-becdfe64c890"
        }
    }
]
`
Am I doing something wrong in setting up the network, creating the containers, or something else?

Really hope someone can help :-)

**Comment by bsideup** [comment]
Hi @kyrrek,

This is really a question to Docker and not Testcontainers. Especially given that it works fine with WSL, but not with WSL2. Since the WSL2 backend is new, it might as well be a bug. Consider reporting to them.

**Comment by kyrrek** [comment]
Thanks for the reply. Just one more details, the scripts are runnning under WSL, and the Java code is running on Windows (through Intellij). But you're probably right. I'll try to raise an issue with Docker.
