### ISSUE TITLE
Set database, username and password for Postgres db created from URI

### ISSUE THREAD

**Issue by andredasilvapinto** [testcontainers/testcontainers-java#3919]
Is it possible to specify the database name, username and password of the testcontainers created database when using the approach "Database containers launched via JDBC URL scheme" specified in https://www.testcontainers.org/modules/databases/jdbc/? If it is possible, how can we do it?

**Comment by bsideup** [comment]
You can change the username/password by providing `user`/`password` query parameters.

Database name is provided as part of the "main" URL:
```
jdbc:tc:postgresql:9.6.8:///databasename
```
