### ISSUE TITLE
Allow insecure TLS for HTTPS Wait Strategy

### ISSUE THREAD

**Issue by ncouse** [testcontainers/testcontainers-java#3924]
The current wait strategy using `Wait.forHttps()` requires validated TLS connection.
Therefore I require a truststore to be set up for my JVM.

There are cases where I don't want a truststore setup in my test JVM, such as in a negative test case for incorrectly configured truststore.

I see that "testcontainers-go" has already added `withAllowInsecure` option there. This should be replicated in the Java version.

**Comment by ncouse** [comment]
"testcontainer-go" issue: https://github.com/testcontainers/testcontainers-go/issues/45

**Comment by bademux** [comment]
looks like there is PR https://github.com/testcontainers/testcontainers-java/pull/4951

**Comment by eddumelendez** [comment]
This is already available in `HttpWaitStrategy`
