### ISSUE TITLE
prestosql/presto removed from Dockerhub

### ISSUE THREAD

**Issue by HJK181** [testcontainers/testcontainers-java#3928]
The `PrestoContainer` is using prestosql/presto which does no longer exists on Dockerhub. 
Not sure whats the proper substitution, as far as I've read Presto got renamed to [Trino](https://github.com/trinodb/trino/tree/master/core/docker) so it might be https://hub.docker.com/r/trinodb/trino, but then `LogMessageWaitStrategy` must be adjusted as the package name differs:
```
INFO    main    io.trino.server.Server    ======== SERVER STARTED ========
```

**Comment by rnorth** [comment]
This was resolved in #3668 - Presto was deprecated and replace with `TrinoContainer`
