### ISSUE TITLE
Set container's env when it's started by means of modifying a url string

### ISSUE THREAD

**Issue by yerzhant** [testcontainers/testcontainers-java#3929]
Hi,

I changed a url string according to [this](https://www.testcontainers.org/modules/databases/jdbc/). Is it possible to set container's env (like `.withEnv`)? Or it would be nice if that would be possible to set env in `testcontainers.properties`.

**Comment by bsideup** [comment]
Hi @yerzhant,

If you need some advanced customization of the database container, we recommend instantiating the container objects manually and applying the modifications:
https://www.testcontainers.org/modules/databases/jdbc/#database-container-objects

**Comment by yerzhant** [comment]
@bsideup Thanks for the reply.
