### ISSUE TITLE
Create test for multiJoin

### ISSUE THREAD

**Issue by flyaruu** [testcontainers/testcontainers-java#3961]
Multijoin is untested, there is a case in Sportlink, but not in the movie demo or the Quin case. Should create one in testTopology for the Sportlink case

**Comment by bsideup** [comment]
It seems to be reported in the wrong repo, since we don't have any of the mentioned technologies 😅

**Comment by flyaruu** [comment]
Ahahaha so sorry, those github tabs all look the same
