### ISSUE TITLE
Allow to bind the specified physical machine port ?

### ISSUE THREAD

**Issue by wenyangchou** [testcontainers/testcontainers-java#3967]
Allow to bind the specified physical machine port instead of randomly specifying a physical machine port. 
For example:
I have test kudu with testcontainer . Kudu has one master and three tsservers. When I insert rows into kudu, kudu would return tsservers' host which are intranet address. I wanted to set rpc_advertised_addresses parameter enables the client to connect to it normally without knowing its port number.

**Comment by bsideup** [comment]
Fixed ports isn't a good idea:
https://bsideup.github.io/posts/testcontainers_fixed_ports/

If you **really** need to set them, consider looking at `withCreateContainerCmdModifier`.

But I would highly advice using an approach similar to KafkaContainer that has a similar protocol with advertised addresses:
https://github.com/testcontainers/testcontainers-java/blob/1.15.2/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java
