### ISSUE TITLE
add statement separator for postgres

### ISSUE THREAD

**Issue by haste100** [testcontainers/testcontainers-java#3971]
add statement separator for postgres
[separ_patch.txt](https://github.com/testcontainers/testcontainers-java/files/6286190/separ_patch.txt)

**Comment by vcvitaly** [comment]
If you suggest a code change, would you be able to fork a repo, make a change in a separate branch and create a PR from that branch to testcontainers/master?

**Comment by eddumelendez** [comment]
It is highly recommended to do

```java
new PostgreSQLContainer<>("postgres:15.2-alpine").withCopyFileToContainer(
    MountableFile.forClasspathResource(
    "init-db.sql"), "/docker-entrypoint-initdb.d/"
);

```

due to the limitations in `withInitScript`

**Comment by haste100** [comment]
[eddumelendez](https://github.com/eddumelendez), Thank you for your decision.
