### ISSUE TITLE
Make MariaDBContainer.MARIADB_PORT constant public

### ISSUE THREAD

**Issue by nielspardon** [testcontainers/testcontainers-java#3996]
Similar to other JDBC containers (e.g. MySQL) it would be helpful if the `MARIADB_PORT` constant would be `public` instead of `protected`.

https://github.com/testcontainers/testcontainers-java/blob/dabc99c73eb9832ed2971c42412dd56bbd4d15be/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java#L26

**Comment by eddumelendez** [comment]
Hi,

In the future those internal properties will be package-private or private. Feel free to reopen the issue and elaborate more on your need.
