### ISSUE TITLE
DynaliteContainer's default constructor deprecated

### ISSUE THREAD

**Issue by huehnerlady** [testcontainers/testcontainers-java#4009]
Hi,

I have seen that the [default constructor of DynaliteContainer ](https://github.com/testcontainers/testcontainers-java/blob/master/modules/dynalite/src/main/java/org/testcontainers/dynamodb/DynaliteContainer.java#L24) is deprecated and you have to provide an image to do so. BUT the `DEFAULT_IMAGE_NAME` is private. So what is the expected usage of this?

**Comment by bsideup** [comment]
Hi @huehnerlady,

Like this:
```java
new DynaliteContainer(DockerImageName.parse("quay.io/testcontainers/dynalite:v1.2.1-1"));
```

**Comment by huehnerlady** [comment]
@bsideup thanks for the quick answer. But why do we have to provide that now ourselves instead of having the convenience of using the defaults?

**Comment by bsideup** [comment]
@huehnerlady because it should be a conscious decision which version of the container to use, instead of relying to the default provided by Testcontainers (and changed by upgrading Testcontainers). The version you're using in production is most probably defined by you as well and not by Testcontainers :)

**Comment by huehnerlady** [comment]
@bsideup well in production we use AWS dynamoDB so that version is managed by AWS 😅 

I can appreciate that you want to have a conscious decision which version you wanna use. But for me it feels odd to write that I want a dynalite container and then have to declare the image name as well. So maybe it would make sense to have a constructor where you just add the version?

**Comment by bsideup** [comment]
@huehnerlady we have some ideas for that, but they most probably will come as part of our new API. Stay tuned!
