### ISSUE TITLE
Kafka Cleanup

### ISSUE THREAD

**Issue by vepo** [testcontainers/testcontainers-java#4011]
I'm using TestContainers with Kafka, but I'm getting come cache on my tests.

I have built the Hello World Kafka Stream application, and on my tests, I'm getting the answer:

```
Flat Map: Hello World!
Grouping: key=null work=hello
Grouping: key=null work=world
Key=hello value=7
```

My test is very simple, I'm creating the `KafkaContainer` and sending a message to the input topic, and checking the output topic.

```
@Container
public static KafkaContainer kafka = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:5.4.3"));
```

How can I clean up all Kafka data (or all container data)? Can I do it between tests? 

I believe that every time I run the tests I need to use a brand new Kafka Cluster, not the old one. I create a GitHub repository with [my test][1].

  [1]: https://github.com/vepo/kafka-stream-with-testcontainers/blob/main/src/test/java/io/vepo/kafka/stream/delay/KafkaStreamTest.java

**Comment by vepo** [comment]
@bsideup, I would be please if you do not close the issue so fast. I believe you did not understand the question.

Let me change the question: how can I clean up the container data. 

If you read the question you will see that some data is been kept between different test executions. This is not a Kafka issue, because if I use a new container Kafka will start without any data.

**Comment by bsideup** [comment]
@vepo there is no shared data between containers. Since your container is defined as `static`, it is reused between tests of the same class - maybe that's the case? If you want "1 container per test", then you should not define it as `static`, as per https://www.testcontainers.org/test_framework_integration/junit_5/

**Comment by vepo** [comment]
Just for the record.

It was not a TestContainer problem. Kafka Streams creates a local cache on `%AppData%\Local\Temp\kafka-streams`

**Comment by bsideup** [comment]
@vepo or that :D I am glad you got it solved 👍
