### ISSUE TITLE
JdbcDatabaseContainer not loading script from file:relative/path/init.sql

### ISSUE THREAD

**Issue by Morpheu5** [testcontainers/testcontainers-java#4012]
The documentation says that if a relative path to an init script is prefixed with `file:`, then it will be loaded from the working directory. Assuming that the working directory is the root of my project, I'm initializing a `PostgreSQLContainer` like so:

```java
LogMessageWaitStrategy postgresWaitStrategy = new LogMessageWaitStrategy();
postgresWaitStrategy.withRegEx(".*database system is ready to accept connections.*");
PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(DockerImageName.parse("postgres:12"))
        .withDatabaseName("dbname")
        .withEnv("POSTGRES_HOST_AUTH_METHOD", "trust")
        .withUsername("myusername")
        .withPassword("somerandompassword")
        .withInitScript("file:src/main/resources/db_scripts/postgres-create-script.sql")
        .waitingFor(postgresWaitStrategy)
        ;
postgres.start();
```

Please note that this script is in the main scope's resources, not test's, as I don't want to have to duplicate it. I tried other ways, including passing in the full absolute path, but when I break at `ScriptUtils.java:190`, I invariably find that `URL resource == null`.

What could I possibly be doing wrong?

EDIT: I tried moving the script to `src/test/resources` and I still get `URL resource == null`.

EDIT 2: I also tried going the `withUrlParam("TC_INITSCRIPT", "file:src/main/resources...");` route to no avail. I get no errors and no messages, the script doesn't seem to run.

**Comment by vcvitaly** [comment]
I'm not sure why, but if you set path relative to the resources, "db_scripts/postgres-create-script.sql", it should work.
You can break in ScriptUtils and try evaluating different paths to see when URL will be resolved correctly, that's how I troubleshooted this.

**Comment by Morpheu5** [comment]
@vcvitaly Yes, with that I can load a file located in the `test` target's resources, but I'd like to read it from the `main`'s. Do you know of any alternative?

**Comment by bsideup** [comment]
@Morpheu5 it makes no sense to use `file:` with `src/main/resources/`, just use `/db_scripts/postgres-create-script.sql`, it will load it from classpath.

**Comment by Morpheu5** [comment]
Huh. I am sure I tried that first and didn't work. It works now. Who knows. Thanks anyway, I'm closing this!
