### ISSUE TITLE
Add a Warp10 module

### ISSUE THREAD

**Issue by BlackYoup** [testcontainers/testcontainers-java#4013]
Hello,

I'm opening this issue to ask if a Warp10 module would make sense in this project. Warp10 is a Geo Time series databases developed by SenX: https://warp10.io/. We ([Clever Cloud](https://www.clever-cloud.com/)) use it since a few years now at the heart of our Metrics and Billing system and we will continue to use it in the future.

### Checklist

*Suggestion: copy and paste this list into PRs for new modules.*

Every item on this list will require judgement by the Testcontainers core maintainers. Exceptions will sometimes be possible; items with `should` are more likely to be negotiable than those items with `must`.

#### Default docker image

- [x] Should be a Docker Hub official image, or published by a reputable source (ideally the company or organisation that officially supports the technology) 

The editor publishes its own images: https://hub.docker.com/r/warp10io/warp10/tags

- [x] Should have a verifiable open source Dockerfile and a way to view the history of changes

The docker repository is here: https://github.com/senx/warp10-docker

- [x] MUST show general good practices regarding container image tagging - e.g. we do not use `latest` tags, and we do not use tags that may be mutated in the future

It does, each version has a tagged image

- [x] MUST be legal for Testcontainers developers and Testcontainers users to pull and use. Mechanisms exist to allow EULA acceptance to be signalled, but images that can be used without a licence are greatly preferred.

The code is under Apache-2.0 license and I'm not aware of such things (main repo is https://github.com/senx/warp10-platform)

#### Module dependencies

- [x] The module should use as few dependencies as possible
- [ ] Regarding libraries, either:
    - they should be `compileOnly` if they are likely to already be on the classpath for users' tests (e.g. client libraries or drivers) 
    - they can be `implementation` (and thus transitive dependencies) if they are very unlikely to conflict with users' dependencies.
- [ ] If client libraries are used to test or use the module, these MUST be legal for Testcontainers developers and Testcontainers users to download and use.

I don't really know about those two since I never wrote any testcontainers module. I think it would only need a JSON dependency because the initial authentication tokens are generated and available under a JSON structure. Other than that, Warp10 gets queried over HTTP, so probably an HTTP dependency for the tests.

I believe it would look like a bit as the Elasticsearch module.

I've let the other items of the checklist as they are not relevant to the issue, more like a PR.

Let me know if Warp10 would fit there and I'll make a pull request once I (or someone else I'm working with) gets a workable implementation :)

**Comment by bsideup** [comment]
Hi @BlackYoup,

There is an important section that you skipped:
https://www.testcontainers.org/contributing/#does-it-need-to-be-a-module

Warp10 looks like a cool technology, but I am not too sure whether it will be beneficial to a wide group of users, or just a few.
Do you have more info on how widely the technology is used?

Thanks in advance!

**Comment by BlackYoup** [comment]
Thanks for your response!

> I am not too sure whether it will be beneficial to a wide group of users, or just a few

I think it would only be beneficial to a few users as of now as I don't think that a lot of people are using it.

Based on that, I guess you would prefer we publish our own third party library? I'm fine with that :)
