### ISSUE TITLE
Weird error using jitpack master-SNAPSHOT:

### ISSUE THREAD

**Issue by sscarduzio** [testcontainers/testcontainers-java#402]
I still have annoyances for test cases that involve more than one container, I was thinking to give a try to the latest updates, and tried to depend on jitpack master snapshot

```
    compile 'com.github.testcontainers.testcontainers-java:testcontainers:master-SNAPSHOT'
```

But when I try to build it, I get this non-JVM error I cannot interpret:

```
:core:test
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/1k/45f3yx9n5ds8qv13sg_fxr8c0000gn/T/liborg-testcontainers-shaded-netty-transport-native-kqueue2484198301727123789.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/1k/45f3yx9n5ds8qv13sg_fxr8c0000gn/T/liborg-testcontainers-shaded-netty-transport-native-kqueue2484198301727123789.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

:core:test FAILED
```

I use MacOS el capitan.

**Comment by bsideup** [comment]
@sscarduzio it's known issue in 1.4.0/1.4.1 with Mac OS X <= 10.11, we're working on a hotfix and will release it ASAP.
Thanks for reporting!

**Comment by sscarduzio** [comment]
Got it. I'm downloading Sierra right now. Never thought something like this would be the thing making me upgrade 😆

**Comment by sscarduzio** [comment]
BTW, just curious, would a simple downgrade in Netty dependencies fix the issue? Do you rely on something Netty introduced in this new version?

**Comment by bsideup** [comment]
@sscarduzio yes, we updated `docker-java` to the new version with native support of unix socket in Netty and removed our own solution for that, but it works only on 10.12. We're going to fallback to our previous solution if <= 10.11 to provide the best experience for every user :)

**Comment by rnorth** [comment]
Just for visibility, this is the underlying issue: netty/netty#6837
