### ISSUE TITLE
upgrade from 1.15.2 to 1.15.3 and mysql container can not create and run

### ISSUE THREAD

**Issue by lehug** [testcontainers/testcontainers-java#4035]
I only change the version from 1.15.2 to 1.15.3,and exec `gradle test`, and get `docker ps`, mysql container do not create, only ryuk and redis created.

so my test cannot run, and do not have a timeout.

what is wrong? how can I get more information?

os: linux deepin, linux kernel 5.10 and 5.11

I must add @SpringBootTest.properties with spring.datasource  then test can work.
I also add `ActiveProfiles("test")` and config in that file. In 1.15.2 test can work, but 1.15.3 not work

**Comment by rnorth** [comment]
What do the logs say?

**Comment by lehug** [comment]
maybe some problem with spring boot config rule with spring boot 2.2. I add properties here and works.
`
@SpringBootTest(classes = {AccountApplication.class},
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {
                "spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver",
                "spring.datasource.url=jdbc:tc:mysql:8.0.22:///databasename?TC_DAEMON=true"
        }
)
`

**Comment by rnorth** [comment]
Ok, glad you got it working...
