### ISSUE TITLE
any idea for support apple m1(arm64) and mysql?

### ISSUE THREAD

**Issue by lehug** [testcontainers/testcontainers-java#4036]
ubuntu/mysql support arm64, can I use it, and how can I use?

I try to change `"spring.datasource.url=jdbc:tc:ubuntu/mysql:///databasename?TC_DAEMON=true"` ,but not works.
any idea?

**Comment by vcvitaly** [comment]
I think you can only use urls like `jdbc:tc:mysql:5.6.23:///databasename` where official Mysql image will be used, you cannot use some custom image to start container in that way. For that you probably have to create a Generic container and construct jdbc url manually like this:
"localhost:" + container.getMappedPort(3306) + "/databasename"

You can read more about extracting the mapped port here:
https://www.testcontainers.org/features/networking/#exposing-container-ports-to-the-host

**Comment by lehug** [comment]
> I think you can only use urls like `jdbc:tc:mysql:5.6.23:///databasename` where official Mysql image will be used, you cannot use some custom image to start container in that way. For that you probably have to create a Generic container and construct jdbc url manually like this:
> "localhost:" + container.getMappedPort(3306) + "/databasename"
> 
> You can read more about extracting the mapped port here:
> https://www.testcontainers.org/features/networking/#exposing-container-ports-to-the-host

thanks,but I don't know how to set spring.datasource.url before @DataResource does.
Now I set two config file, and change the @ActiveProfiles, this works well, but I need to care about git commit, do not commit the ActiveProfiles change.

**Comment by eddumelendez** [comment]
Hi @lehug, [here](https://github.com/eddumelendez/testcontainers-samples/blob/main/spring-boot-postgresql-flyway/src/test/java/com/example/springbootpostgresqlflyway/PostgresHostLessTest.java) you can find an example using spring boot with testcontainers (postgres), the configuration should be the same for mysql. If you are running on M1 and have docker installed then the image with arm support will be pulled.
