### ISSUE TITLE
Migration to Gradle

### ISSUE THREAD

**Issue by wlsc** [testcontainers/testcontainers-java#404]
Guys, have you considered to migrate this project from Maven to Gradle?

**Comment by bsideup** [comment]
Hi @wlsc,

Thanks for raising it :) Personally I would definitely prefer Gradle over Maven, we might also solve some potential shading issues and simplify shading tests. 

We can do both during the migration by using my https://github.com/bsideup/gradle-maven-sync-plugin to keep the deps in sync between Maven and Gradle

@rnorth WDYT?

**Comment by rnorth** [comment]
Sorry, I'm going to make myself unpopular and say no. I'm afraid I'm not as much of a fan of Gradle (though I work with it on a daily basis). I think I would prefer that we move in the direction of doing less in our build scripts rather than more.

**Comment by wlsc** [comment]
@rnorth are you not even considering if someone will do it and offer your project a pull request?

**Comment by asafm** [comment]
I cast my personal opinion here: we learned to dislike Gradle at my company
and placed a technical debt of moving away to Maven. I would consider it if
your build script is quite complicated
