### ISSUE TITLE
Vault Testcontainers secret engine support

### ISSUE THREAD

**Issue by cgraving** [testcontainers/testcontainers-java#4079]
It would be ideal if the Vault container could support more engine types than just the KV secrets engine.

Transit Engine:
create, read, list, delete, update, export, encrypt, decrypt

Database Engine:
configure, read, list, delete

I know there are an ever growing number of engines, but getting a couple started would be a huge help.

**Comment by eddumelendez** [comment]
In order to enable them `vault secrets enable <consul,database,rabbitmq>` must be executed and Testcontainers API already provides those capabilities. Can you elaborate more about about what's expected?
