### ISSUE TITLE
Ryuk failed to delete container if reuse is enabled

### ISSUE THREAD

**Issue by sergey-morenets** [testcontainers/testcontainers-java#4107]
TestContainers 1.15.3

Hi

I tried to implement Singleton Container as described in the documentation:
https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/

```
static final MongoDBContainer mongo;
	
static {
     mongo = new MongoDBContainer("mongo:4.4");
     mongo.start();
}
```

It worked properly and Ryuk deleted Mongo container at the end. However at the beginning the first Mongo container was still created. If I try to reuse containers:

```
	static {
		mongo = new MongoDBContainer("mongo:4.4").withReuse(true);
		mongo.start();
	}
```

then tests will be run much faster because TestContainers picks up existing container. However this container is not stopped/deleted at end (by Ryuk?).
So is it by design? And if yes then what is the purpose of reuse flag and when we should use it and not Singleton container pattern?

**Comment by bsideup** [comment]
Reusable containers are preserved between test sessions, so it is by design that the container is not terminated.

Singleton pattern simply allows sharing the same container between tests in the same JVM.

**Comment by sergey-morenets** [comment]
@bsideup Ok, so does it mean that if we use **reuse** flag then we need to manually stop/remove created containers?

**Comment by bsideup** [comment]
@sergey-morenets yes, this is correct. Note that the reusable container mode is an experimental feature shipped as preview, and the final version will eventually terminate containers.
