### ISSUE TITLE
GenericContainer::isRunning throws exception if container not started

### ISSUE THREAD

**Issue by dhargo** [testcontainers/testcontainers-java#411]
GenericContainer::isRunning throws exception if container not started. 
This caused by null value in GenericContainer::containerId.
Expected: call GenericContainer::isRunning returns false if container not started.

**Comment by bsideup** [comment]
Hi @dhargo,

Thanks for reporting, it's an annoying bug we should finally fix. It's a trivial change to `catch()` block, let me know if you want to submit a PR for that 👍
