### ISSUE TITLE
Docker-in-Docker fails with Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

### ISSUE THREAD

**Issue by sergey-morenets** [testcontainers/testcontainers-java#4111]
Hi

I have pretty simple base test that works fine locally but fails if I run it inside Docker container:

```
@Testcontainers
public abstract class BaseMongoTest {
	static final MongoDBContainer mongo;
	
	static final int MONGO_LOCAL_PORT;
	
	static {
		mongo = new MongoDBContainer("mongo:4.4");
		mongo.start();
		MONGO_LOCAL_PORT = mongo.getMappedPort(27017);
	}
}
```

The exception stack-trace:

```
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
```

My Dockerfile:

```
# syntax=docker/dockerfile:experimental
FROM gradle:7-jdk16 as gradle7

USER root

COPY sources/ /home/gradle/sources/

RUN --mount=type=cache,target=/home/gradle/.gradle gradle --no-daemon build
```

I read this article: https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/
but I don't use volume mapping so I'm not sure how to resolve it. Can you please advise?

TestContainers 1.15.3

**Comment by bsideup** [comment]
This is not "Docker in Docker". When you're building Docker images, there is no Docker daemon available inside the build container.

You can easily verify that by running the following command:
```shell
$ curl --unix-socket /var/run/docker.sock http:/_/_ping
```

**Comment by sergey-morenets** [comment]
> 
> 
> This is not "Docker in Docker". When you're building Docker images, there is no Docker daemon available inside the build container.
> 
> You can easily verify that by running the following command:
> 
> ```shell
> $ curl --unix-socket /var/run/docker.sock http:/_/_ping
> ```

Ok, thank you for the answer.
Is there any chance to use TestContainers during Docker build?

**Comment by loop-ozav** [comment]
Anyone investigated the issue?
This [proposal](https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/#docker-only-example) does not work.

**Comment by ivelasquez-rl** [comment]
why was this marked as completed? there's no solution provided. Is it a "don't care" ending?
