### ISSUE TITLE
remove labels when creating container

### ISSUE THREAD

**Issue by Budlee** [testcontainers/testcontainers-java#4129]
Hi,

I have been running testcontainers and I modified the create command to remove all labels.
I was not expecting it then to add any labels as part of the create.
What would be ideal is if the label format was a modifiable property

I notice that the GenericContainer.java adds in labels.
These are:
- DockerClientFactory.TESTCONTAINERS_LABEL
- DockerClientFactory.TESTCONTAINERS_SESSION_ID_LABEL

The others I think should be modifiable are:
- HASH_LABEL
- COPIED_FILES_HASH_LABEL

If this is acceptable I would like to put in a PR to make the label format modifiable from a environmet variable

**Comment by bsideup** [comment]
Hi @Budlee,

Please explain why you need to change them.

They are used internally to make everything work as expected, and we intentionally force them to our own values, versus the user provided one (as they are in `org.testcontainers` namespace)

**Comment by Budlee** [comment]
Hey,
I would like to run my containers with no labels at all or apply labels that only fit with my own naming convention.

**Comment by bsideup** [comment]
@Budlee without these labels, Testcontainers will be unable to destroy the containers after the session. Is it expected?

**Comment by Budlee** [comment]
I may have misread the code. I thought the labels is used by the  ryuk container? I am running with this off.

Basically I would like to achieve  the following:
when ryuk  is  off to not add labels
or be able to configure my own label naming convention. so instead of  org.testcontainers be able to set a property property TEST_CONTAINERS_LABLEL_FORMAT=com.budlee

Fully understand this is a change that may not  want to go in so can happily close it.

**Comment by bsideup** [comment]
Since it doesn't look like something is broken or anything, nor it is forbidden to use custom labels for Docker containers, I suggest we close it :)
