### ISSUE TITLE
Support for explicit mapping of ports?

### ISSUE THREAD

**Issue by PGryllos** [testcontainers/testcontainers-java#413]
I am wondering why isn't there the option for explicitly mapping of a container port to a specific port on the host machine? This seems like a useful feature to me as I sometimes need to be able to control the port of the host to which the exposed port is mapped to.

**Comment by kiview** [comment]
This works using the `FixedHostPortGenericContainer`, but it's not recommended, since you are making assumptions regarding your test environment. 

Since this is already supported, I'll close the issue.

**Comment by PGryllos** [comment]
Oh thanks a lot both for letting me know of the FixedHostPort class and the recommendation. It seems like the docs are missing some parts. Also I noticed an inconsistency in the docs regarding that

```
new GenericContainer(...)
        .withExposedPorts("22", "80/tcp", "8080/tcp")

```
Version `1.4.1` does not include such a method.
