### ISSUE TITLE
Copy statements in Dockerfile fail

### ISSUE THREAD

**Issue by PGryllos** [testcontainers/testcontainers-java#414]
When trying to build a container from Dockerfile using 

```
    @Rule
    public GenericContainer dslContainer = new GenericContainer(
        new ImageFromDockerfile()
            .withFileFromFile("Dockerfile", new File("service/Dockerfile")))
```

the `COPY` statements in my Dockerfile fail with

> COPY failed: stat /var/lib/docker/tmp/docker-builder276737305/docker-entrypoint.sh: no such file or directory

**Comment by bsideup** [comment]
@PGryllos please take a look at the docs:
https://www.testcontainers.org/usage/dockerfile.html

you need to do `withFileFromClasspath` for `docker-entrypoint.sh` also

**Comment by PGryllos** [comment]
Sorry, I just figured what the docs mean. So I understood correctly, all external resources needed for the build context have to be provided explicitly. It seems like this is not the case when building using the docker-compose functionality.

**Comment by bsideup** [comment]
@PGryllos yes, it is so. You can also use `withFileFromFile` with a directory
