### ISSUE TITLE
Local Docker compose impossible on Windows

### ISSUE THREAD

**Issue by declension** [testcontainers/testcontainers-java#416]
Hi

In 1.4.1, the implementation for the `LocalDockerCompose` class has [a constant specifying the executable name of local Docker Compose](https://github.com/testcontainers/testcontainers-java/blob/testcontainers-1.2.1/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L444). 

This is hard-coded to `docker-compose` which is fine on *nix / OS X, but fails on Windows, which is expecting `docker-compose.exe`.

It might be nice if this auto-detected Windows and used the `.exe` version, or even just tried both in turn...

**Comment by bsideup** [comment]
Hi @declension,

Thanks for reporting! 

We already have an issue regarding `.exe` (Damn you, Windows! :D ) here: https://github.com/testcontainers/testcontainers-java/issues/62 

But it's about `docker-machine`. Do you want to fix it yourself? Shouldn't be hard, and we're more than happy to receive PRs :)

**Comment by barrycommins** [comment]
I managed to get this working by adding a copy of docker-compose to my path without the .exe extension.

Obviously a hack, but it seems to work

**Comment by declension** [comment]
Thanks!
