### ISSUE TITLE
Allow MySQL containers to use MariaDB connector instead of MySQL connector

### ISSUE THREAD

**Issue by robertdanci** [testcontainers/testcontainers-java#4165]
Currently using `ContainerDatabaseDriver` with mysql jdbc url or `MySQLContainer` only supports the MySQL Connector (it is hardcoded in org.testcontainers.containers.MySQLContainer#getDriverClassName). Because of the licensing requirements of the MySQL Connector I want to use the MariaDB connector while still using MySQL database.

Provisionally I extended `MySQLContainer` and overrode the `getDriverClassName` method but this is not ideal. `ContainerDatabaseDriver` cannot be used with MariaDB connector and MySQL DB even if I create my own `JdbcDatabaseContainerProvider` because **the last** provider is used to provision the container:
`ContainerDatabaseDriver#connect`
```
 for (JdbcDatabaseContainerProvider candidateContainerType : databaseContainers) {
    if (candidateContainerType.supports(connectionUrl.getDatabaseType())) {
        container = candidateContainerType.newInstance(connectionUrl);
        container.withTmpFs(connectionUrl.getTmpfsOptions());
        delegate = container.getJdbcDriverInstance();
    }
}
```

What are your thoughts on allowing the driver class to be configured for MySQL containers?

**Comment by bsideup** [comment]
Hi@robertdanci,

Why don't you use the [`MariaDBContainer`](https://github.com/testcontainers/testcontainers-java/blob/1.15.3/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java)? :)

**Comment by robertdanci** [comment]
Hi @bsideup, because it spins a MariaDB container not a MySQL one. :)

Although it should be a drop in replacement, I saw at least one instance where using Hibernate native sql statements gave different results.

**Comment by bsideup** [comment]
@robertdanci ah, okay, I see. Then I think a custom `JdbcDatabaseContainerProvider` is the best choice, and `getDriverClassName` override sounds reasonable and allows your use case.

Since the use case is rather advanced / unusual, I don't think adding a config property for it makes a lot of sense. WDYT?

**Comment by robertdanci** [comment]
In order to be able to add a custom `JdbcDatabaseContainerProvider` we need to add a `break;` in the for loop I posted in the original message after a container has been found and instantiated. In case there are multiple providers we want the `ContainerDatabaseDriver` to stop after the first matching provider it finds. That `break;` should be there anyway regardless of the present issue, because there is no point in iterating over the remaining providers once one was found. I presume the assumption was that there will be only one provider that supports a given database type. Coming back to our issue, even if we add a `break;`, I'm not 100% sure the `ServiceLoader.load` will load our provider first over the `MySQLContainerProvider`. It happened to be so when I tested but looking at the java doc for `ServiceLoader#load` it is not clear. 

We could as well add a method on the `JdbcDatabaseContainer` `withDriverClassName` for e.g. that would allow the customisation of the driver class. This might be useful for other non-standard drivers like http://jtds.sourceforge.net.

**Comment by bsideup** [comment]
there is no need for changing anything in Testcontainers' code base, just implement your own `JdbcDatabaseContainerProvider` and make sure that you're using an unique `databaseType` while implementing `JdbcDatabaseContainerProvider#supports`

**Comment by FrostbittenKing** [comment]
Oh, that also answers my issue regarding the PostgreSQLContainer via jdbc:tc url and switching from the org.postgresql jdbc driver to pgjdbc-ng. I for now copied the ContainerProvider class and changed the url format + getDriverClassName methods. But I guess your suggestion to make a unique db type works too.
