### ISSUE TITLE
disabledWithoutDocker annotation option (for JUnit 5) isn't documented

### ISSUE THREAD

**Issue by tedyoung** [testcontainers/testcontainers-java#4174]
While this is documented at the API level, one would have to know that the `disabledWithoutDocker` parameter was available in order to see it.

Happy to add this to the documentation, but wanted to make sure that was OK.

Seems like `/docs/test_framework_integration/junit_5.md` is the appropriate place for this.

**Comment by eddumelendez** [comment]
This is available [here](https://java.testcontainers.org/quickstart/junit_5_quickstart/#4-additional-attributes).
