### ISSUE TITLE
Expose a way to check file existence

### ISSUE THREAD

**Issue by davidegiannella** [testcontainers/testcontainers-java#418]
Expose an API end point that will allow the check of file existence within the container before accessing it, for example with `container.getDockerClient().copyArchiveFromContainerCmd(String, String)`

**Comment by kiview** [comment]
Isn't it enough to catch the `NotFoundException` for most use cases?

**Comment by davidegiannella** [comment]
while catching the NFE is fine from an functional point of view, it still tracks in the logs an nasty error with exception which for a test of file existence should not happen. Hence asking for a way to cleanly check this aspect.

FTR I've currently achieved the same by using the following code

    private boolean containerFileExists(
        @Nonnull final GenericContainer container, String path)
        throws IOException, InterruptedException {
        checkNotNull(container);
        checkArgument(!Strings.isNullOrEmpty(path));

        ExecResult r = container.execInContainer("/bin/sh", "-c",
            "if [ -f " + path
            + " ] ; then echo '0' ; else (>&2 echo '1') ; fi");

        return !r.getStderr().contains("1");
    }

**Comment by kiview** [comment]
Do you have a use case example, where this would be useful? I assume a test should fail, if the expected file is not existent?

**Comment by davidegiannella** [comment]
my test, starts and stops an application within the container several times, before, during and after tests. I do suck with `execInContainer`; but the internal start-up is async and the starting is completed once the file is there.
