### ISSUE TITLE
Need to configure ryuk memory size

### ISSUE THREAD

**Issue by jamesdschmidt** [testcontainers/testcontainers-java#4199]
Don't own or maintain the build servers in my organization. Need to be able to configure the memory and swap size of the ryuk container. Currently the default it is using the Docker default of allocation 2GB per container.

Example (in a Spring Boot app):
src/resources/testcontainers.properties
ryuk.container.memory = 8388608
ryuk.container.swap = 16777216

**Comment by bsideup** [comment]
Hi @jamesdschmidt,

There is no "default memory allocation" in Docker. By default, Docker containers are not limited in memory, and Ryuk process is a tiny Golang process that requires ~4Mb of RAM:
<img width="150" alt="Screenshot 2021-06-15 at 09 48 06" src="https://user-images.githubusercontent.com/1050762/122013816-d53da780-cdbe-11eb-8c34-700ead391575.png">
