### ISSUE TITLE
Download link now broken

### ISSUE THREAD

**Issue by birbilis** [testcontainers/testcontainers-java#4204]
at
https://github.com/testcontainers/testcontainers-java/blob/master/README.md 
the link saying "Download" (https://bintray.com/testcontainers/releases/testcontainers/_latestVersion) is now broken 

going to https://bintray.com/ one reads "JFrog Bintray" now and "Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th. "

so if you were using some paid account probably you need to migrate and update that link, if not I'm not sure what is the path you need to take...

**Comment by vgarmash** [comment]
![image](https://user-images.githubusercontent.com/1226001/122749613-391c1080-d296-11eb-851f-2e1cde4eac8a.png)

**Comment by rnorth** [comment]
We're just going to remove this link in #3434; please use [standard Maven/Gradle ways](https://www.testcontainers.org/#maven-dependencies) to obtain the library as a dependency rather than trying to download from (now defunct) bintray.
Thank you!
