### ISSUE TITLE
Problems with sentence create procedure with pl/sql code

### ISSUE THREAD

**Issue by Jorge2M** [testcontainers/testcontainers-java#4205]
There is a problem with sentences of type "create procedure" in the init script when the sentence contains PL/SQL code.

The code is:

`
    @ClassRule
    public static OracleContainer oracleContainer = new OracleContainer("oracleinanutshell/oracle-xe-11g")
    	.withInitScript("create_productos.sql");
`

The create_productos.sql contains the sentence:

  create or replace PROCEDURE load_product_info IS
      ltimestamp_begin        timestamp	;
  BEGIN 
      ltimestamp_begin := systimestamp	;
  END load_product_info	;
  /

Then the next error is obtained:

_Caused by: Error : 6550, Position : 68, Sql = BEGIN 
    ltimestamp_begin := systimestamp	;
END load_product_info, OriginalSql = BEGIN 
    ltimestamp_begin := systimestamp	;
END load_product_info, Error Msg = ORA-06550: line 3, column 21:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ;
The symbol ";" was substituted for "end-of-file" to continue._
  

The problem is that TestContainer separates each SQL statement when appears the ';' character and then uses the ';'s that are in the PLSQL code and generates incorrect SQL sentences of type:

create or replace PROCEDURE load_product_info IS
      ltimestamp_begin        timestamp	;

**Comment by havardge** [comment]
Same issue here

**Comment by MuffinTheMan** [comment]
Looks like I might have the same issue with a MySQL procedure
`java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$ CREATE PROCEDURE insert_schema_change(IN majorRelease INT, IN minor' at line 1`

**Comment by MuffinTheMan** [comment]
I'm trying to debug and look through the code in `org/testcontainers/ext/ScriptUtils.java`, and it appears that in my case, after I set the delimiter to `$$` (via `DELIMITER $$` in my SQL script), it doesn't get set back via `DELIMITER ;`, since the `;` is treated as the separator to split the script as opposed to part of the actual SQL statement (so the end of the statement in question in the `statements` `LinkedList` after the call to `splitSqlScript()` is `END $$ DELIMITER` in my case, when it should actually be `END $$ DELIMITER ;`).

**Comment by rnorth** [comment]
Please see https://github.com/testcontainers/testcontainers-java/issues/2814#issuecomment-635926521; unfortunately there are practical limits to what `ScriptUtils` can be patched to support. 

I haven't looked lately, but I'm not aware of any libraries we could use to replace `ScriptUtils`. I'd be delighted if there was a multi-dialect, syntax aware SQL script splitting library that we could replace it with 😄 

For now we have to point you towards using a proper DB migration tool to run your scripts, after the container is started.

**Comment by MuffinTheMan** [comment]
@rnorth is there not a way to just run the `.sql` file (source it) instead of trying to parse and execute each statement one at a time? MariaDB4J does this like so: https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java#L344

**Comment by MuffinTheMan** [comment]
I'm trying to do some combination of

    final MySQLContainer<?> mysql = new MySQLContainer<>(DockerImageName.parse("mysql:5.6"))
		    .withCopyFileToContainer(MountableFile.forClasspathResource("baseline.sql"), "/tmp/")
		    .withDatabaseName("test");
    mysql.start();
    mysql.execInContainer("mysql", "-u", mysql.getUsername(), "test", "< /tmp/baseline.sql");

But I can't pass the password directly using `-p` or `--password=`, and I've been unsuccessful so far with a couple other methods to get this to work in a headless way.

Something like this should be possible, right?

**Comment by vkadam** [comment]
> Please see [#2814 (comment)](https://github.com/testcontainers/testcontainers-java/issues/2814#issuecomment-635926521); unfortunately there are practical limits to what `ScriptUtils` can be patched to support.
> 
> I haven't looked lately, but I'm not aware of any libraries we could use to replace `ScriptUtils`. I'd be delighted if there was a multi-dialect, syntax aware SQL script splitting library that we could replace it with 😄
> 
> For now we have to point you towards using a proper DB migration tool to run your scripts, after the container is started.

@rnorth I been using https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java successfully with mysql & oracle, both using different delimiter, supports single line statements, multi-line procedures/functions without any issue. 
Hope this helps

**Comment by kiview** [comment]
@MuffinTheMan 
I would suggest using your own mechanisms to apply more complex SQL scripts after startup, especially if you are already using a library to handle migrations, e.g. Flyway or Liquibase. 

Of course, you can also execute commands in the container if you prefer this. If you know the Docker CLI command that would work, it is generally 1:1 transferable to Testcontainers.
