### ISSUE TITLE
support alternative image repositories such as public.ecr.aws

### ISSUE THREAD

**Issue by SingingBush** [testcontainers/testcontainers-java#4219]
Now that docker hub is limiting the amount of calls that can be made it's getting more common for developers to use images from alternative repositories such as _public.ecr.aws_ (see images in https://gallery.ecr.aws). I was hoping to use the Bitnami MySQL image from there so that the following:

```java
new MySQLContainer("mysql:5.7")
            .withUsername("username")
            .withPassword("pass")
            .withDatabaseName("testdb");
```

get replaces with:

```java
new MySQLContainer("public.ecr.aws/bitnami/mysql:5.7")
            .withUsername("username")
            .withPassword("pass")
            .withDatabaseName("testdb");
```

unfortunately _org.testcontainers.containers.MySQLContainer_ won't work with this image, even though it's similar in configuration and could potentially be used instead of the image on docker hub.

**Comment by rnorth** [comment]
Hi @SingingBush 
Please see our pinned issue for this: https://github.com/testcontainers/testcontainers-java/issues/3099

As well as the solution for users: https://github.com/testcontainers/testcontainers-java/pull/3102
Documented here: https://www.testcontainers.org/features/image_name_substitution/

If this approach is not working for you please reopen, but I'll close this ticket for now.

**Comment by SingingBush** [comment]
thanks for this, I see I was just missing the `.asCompatibleSubstituteFor("mysql")`
