### ISSUE TITLE
Support for using mariadb driver with mysql container

### ISSUE THREAD

**Issue by djarnis73** [testcontainers/testcontainers-java#4222]
Hi

When using aurora on aws, [the recommended jdbc driver](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Connecting.html) is actually the mariadb driver.

It would be nice if it was possible to override which jdbc driver to use when connecting to the database so tests can be run with the same driver as will be used in production.

Best regards Jens

**Comment by tw-kang-namas** [comment]
And now we have aws-mysql-jdbc. Due to this limitation, I had to include mysql-connector-j with test scope.

**Comment by eddumelendez** [comment]
`MySQLContainer` can be extended and override the `getDriverClassName`.
