### ISSUE TITLE
MariaDB, Oracle and other jars not updated to 1.4.2

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#424]
See https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.testcontainers%22

Not having the same version for all subjars makes it a mess to update the testcontainers dependency to newer version as they get released. Alternatively consider publishing a BOM artifact.

**Comment by rnorth** [comment]
Sorry about this; release 1.4.3 included all non-core JARs. I'm going to close this ticket but keep #431 open as a reminder that either the release process needs to be improved or we need to do as you suggest there.
