### ISSUE TITLE
Complex Docker-compose does not work

### ISSUE THREAD

**Issue by bsushant-athena** [testcontainers/testcontainers-java#428]
I'm trying to use my docker-compose file with testcontainers. But it fails. Then I tried with dockercompose rule > https://github.com/palantir/docker-compose-rule.
It failed with not able to pull from our private docker artifactory. Then I tried to add insecure registry but still failing. Can somebody please help me ?
` version: '2' `
`services:`
` gateway:`
`    image: gateway_nginx:latest `
    ports:
      - ${GATEWAY_PORT}:8080
      - ${GATEWAY_SSL_PORT}:443
    container_name: ${ENV_NAME}_gateway_nginx
    networks:
      - auth
      - zuul
    env_file:
      - .env
    environment:
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      GATEWAY_SCHEME: ${GATEWAY_SCHEME}
      GATEWAY_SSL_PORT: ${GATEWAY_SSL_PORT}
      ZUUL_SERVICE_SCHEME: ${ZUUL_SERVICE_SCHEME}
      ZUUL_SERVICE_NAME: ${ZUUL_SERVICE_NAME}
      ZUUL_SERVICE_PORT: ${ZUUL_SERVICE_PORT}
      LOGIN_SERVICE_NAME: ${LOGIN_SERVICE_NAME}
      LOGIN_SERVICE_PORT: ${LOGIN_SERVICE_PORT}

  nodegateway:
    image: gateway_node:latest
    container_name: ${ENV_NAME}_gateway_node
    networks:
      - auth
      - zuul
    env_file:
      - .env
    environment:
      EUREKA_HOST: ${GATEWAY_HOST}
      EUREKA_PORT: ${GATEWAY_PORT}
      EUREKA_PATH: ${EUREKA_PATH}
      HOST: ${NODE_SERVICE_NAME}
      PORT_3000: ${NODE_SERVICE_PORT}

  docgateway:
    image: gateway_doc:latest
    container_name: ${ENV_NAME}_gateway_doc
    networks:
      - zuul
    env_file:
      - .env

  iams_auth:
    image: ${IAM_IMAGE}
    ports:
    container_name: ${ENV_NAME}_auth_service
    environment:
          OKTA_API_TOKEN: "testtoken"
          APIGATEWAY_OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    networks:
      - auth
      - zuul

    env_file:
      - .env

  zuulgateway:
    image: gateway_java:latest
    container_name: ${ENV_NAME}_gateway_zuul
    networks:
      - auth
      - zuul
    environment:
      ATHENA_PLATFORM_eureka.client.enabled: 'true'
      ATHENA_PLATFORM_eureka.instance.preferIpAddress: 'false'
      ATHENA_PLATFORM_eureka.client.serviceUrl.defaultZone: 'http://gateway:8080/public/eureka/'
      ATHENA_PLATFORM_eureka.client.initialInstanceInfoReplicationIntervalSeconds: 1
      ATHENA_PLATFORM_eureka.client.instanceInfoReplicationIntervalSeconds: 1
      ATHENA_PLATFORM_eureka.client.registryFetchIntervalSeconds: 1
      ATHENA_PLATFORM_ribbon.ServerListRefreshInterval: 5000
      ATHENA_PLATFORM_zuul.routes.iam.url: 'http://iams_auth:2003'
      zuul.routes.iam.url: 'http://iams_auth:2003'
    env_file:
      - .env

networks:
  auth:
    ipam:
      config:
        -
          subnet: ${AUTH_SUBNET}
  zuul:
    ipam:
      config:
        -
          subnet: ${ZUUL_SUBNET}
`

**Comment by kiview** [comment]
Please ask such question in our [Slack](http://slack.testcontainers.org/), we'll try to help if possbile :wink:
