### ISSUE TITLE
execInContainer mysql script unintended results

### ISSUE THREAD

**Issue by steve0341** [testcontainers/testcontainers-java#4284]
**Description:**
The following code ends up creating a regular table rather than a mysql view table.
There is a difference.
```
mysql.execInContainer("mysql", "-uroot", "-ptest", "-e use [db name]; CREATE VIEW v_view_name as ....")
````

According to the java note(s) in the test containers library, the exec command is just calling a docker exec command.
Notes in ContainerState.java:225
```
Run a command inside a running container, as though using "docker exec", and interpreting the output as UTF8.
```

Replicating this process manually using docker command(s) 
creates a mysql view table successfully and correctly.

```
docker exec -it 580e2b08a093 mysql -uroot -ptest -e "use db_name; CREATE VIEW v_view_table as SELECT * FROM  tablexxx"
```

Not sure why the method call via the library would create a regular table.
Any help is appreciated.
Thank you!

**Comment by bsideup** [comment]
Hi @steve0341,

I am pretty sure it should be:
```
mysql.execInContainer("mysql", "-uroot", "-ptest", "-e", "use [db name]; CREATE VIEW v_view_name as ....")
```

Also, have you considered using the JDBC driver to perform this query instead of exec-ing it? Exec should also work, so I am just curious :)

**Comment by eddumelendez** [comment]
@bsideup suggestion just work well. I'll close the issue.
