### ISSUE TITLE
environmentSupportsReuse() method in TestcontainersConfiguration class not looking at the classpathProperties

### ISSUE THREAD

**Issue by erincgucer** [testcontainers/testcontainers-java#4289]
environmentSupportsReuse() method in TestcontainersConfiguration class is not looking at the classpathProperties but only env variables and userProperties. (getEnvVarOrUserProperty method is used inside, instead of getEnvVarOrProperty method)

There is a comment like "specifically not supported as an environment variable or classpath property" but i am curious on why we cannot use the classpath properties for reusing the container.

Is it a bug? If it is not, i'd be glad to hear the rationale behind it.

**Comment by bsideup** [comment]
By design. See https://github.com/testcontainers/testcontainers-java/pull/1781#discussion_r369160221
