### ISSUE TITLE
Default log level is set to DEBUG - should not be specified

### ISSUE THREAD

**Issue by HenrikSkriver** [testcontainers/testcontainers-java#43]
Hi Richard

I noticed a lot of debug log when using your test containers and noticed that it is specified in the logback.xml file in the core module.
Can you not specify the level and instead leave that to the project using testcontainers?

Regards Henrik

**Comment by rnorth** [comment]
Hi Henrik
Yes - absolutely, thank you for raising this. I think I left in in by mistake, and didn't notice because I tend to have a logback-test.xml file in my tests out of habit.
I'll remove this stray file!
Thank you
Richard

**Comment by rnorth** [comment]
Candidate fix for this merged in - unfortunately logback's default level is debug, though, so it's necessary to use a `logback-test.xml` in test suites anyway. I've added an example to the documentation.

**Comment by HenrikSkriver** [comment]
Hi Richard

I am using the testcontainers project in a Spring Boot based project having spring-cloud-starter-parent Brixton.M4 as the parent.  
When running my integration tests default log level is DEBUG, but I have had to had your recommendations to my application.yml file to reduce the logging.  
```
logging:
  level:
    org.apache.http: WARN
    com.github.dockerjava: WARN
    org.zeroturnaround.exec: WARN
```  

Also, I have had to add this to my pom in order to let Spring control the jackson version used to avoid breaking conflicts - might want to look into that.
```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.jaxrs</groupId>
			<artifactId>jackson-jaxrs-json-provider</artifactId>
			<version>${jackson.version}</version>
		</dependency>
	</dependencies>
</dependencyManagement>
``` 

Should I close the bug ?

**Comment by rnorth** [comment]
Released in v0.9.9 just now.

**Comment by rnorth** [comment]
Hi @HenrikSkriver, re the Jackson version yes, that is the correct thing to do. The docker client libraries bring a fairly hefty chain of dependencies which includes Jackson, and there's a fair chance of conflicts that need to be resolved through use of dependencyManagement. 

Issue #35 tracks the problem - it's been open for a while but I'd quite like to resolve it for the next release.

**Comment by kongslund** [comment]
Spring Boot 1.3.2 will include the Jackson module in their POM as part of dependency management. See #gh-4932.
