### ISSUE TITLE
Oracle XE link broken

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#430]
on https://www.testcontainers.org/usage/database_containers.html

**Comment by jurikolo** [comment]
I confirm, https://github.com/testcontainers/testcontainers-java/blob/master/modules/oracle-xe/src/test/java/org/testcontainers/junit/SimpleOracleTest.java doesn't work for me

**Comment by kiview** [comment]
The correct repository is now at https://github.com/testcontainers/testcontainers-java-module-oracle-xe btw.
