### ISSUE TITLE
Support for --pid=host on GenericContainer?

### ISSUE THREAD

**Issue by ekkelenkamp** [testcontainers/testcontainers-java#4310]
Is it possible to start a GenericContainer with the --pid=host flag as can be specified with docker run.
I couldn't find anything in the API that would allow that.

**Comment by bsideup** [comment]
@ekkelenkamp See withCreateContainerCmdModifier

**Comment by ekkelenkamp** [comment]
Thanks a lot. That was just what I needed. This is what I used:

`withCreateContainerCmdModifier(cmd -> cmd.getHostConfig().withPidMode("host")).`
