### ISSUE TITLE
Add specialized container support for DB2

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#432]
Based on https://hub.docker.com/r/ibmcom/db2express-c/

**Comment by THD-Thomas-Lang** [comment]
Dear testcontainer maintainers, 
i am currently helping out on issues for the very cool spring data jdbc project 
(https://github.com/spring-projects/spring-data-jdbc) 
especially on integration tests for several database vendors, including IBM DB2.

So it would be cool to have the mentioned integration within testcontainers.

Thank you guys!
Kind regards!
Thomas

**Comment by kiview** [comment]
Hi Thomas,

We have an open DB2 PR. If you like we can work on merging it. We had some
issues regarding the licensing, maybe you have some good ideas.

See
https://github.com/testcontainers/testcontainers-java/pull/860

THD-Thomas-Lang <notifications@github.com> schrieb am Di., 6. Nov. 2018,
16:55:
