### ISSUE TITLE
Add specialized container support for SQL Server

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#433]
Based on https://hub.docker.com/r/microsoft/mssql-server-linux/

**Comment by martin-g** [comment]
Like this https://github.com/testcontainers/testcontainers-java-module-mssqlserver ?

**Comment by axelfontaine** [comment]
Yes! Perfect! Thanks!

Then consider this issue like a bug report for the docs :-)

**Comment by axelfontaine** [comment]
Also note that this one is missing from Maven Central. Which I feel is yet another argument in favor of #431.

**Comment by kiview** [comment]
I see you're point, but mssqlserver module was actually a real 3rd party contribution we've integrated.
I'm not a big fan of making testcontainers itself bigger, since I'm for example looking forward to integrate testcontainers with testcontainers-spock without the JUnit dependencies :wink:

**Comment by axelfontaine** [comment]
@kiview This big difference here is that specialized containers do not add additional dependencies. Only 2 classes, which is at most 1-2 kb of bytecode before compression.

**Comment by kiview** [comment]
Point taken. Maybe we should further discuss this topic in #431.
Also in the other hand, it would help to have either a curated list of plugins, or mention the Github organization for further specialized containers.

**Comment by StefanHufschmidt** [comment]
@axelfontaine maybe there will be an extension for the MSSQL module where you can pass a SQL-script which will be initially executed on the container e.g. for a specific database structure. This extension will probably need the client library for MSSQL. The client for MSSQL is not that small I guess so I would prefer to choose each module which I need for my project.

**Comment by axelfontaine** [comment]
@StefanHufschmidt Not necessary. `sqlcmd` is already present in the Docker image and can be used as described in the "Connect to Microsoft SQL Server" example from the docs at https://hub.docker.com/r/microsoft/mssql-server-linux/
