### ISSUE TITLE
New module: Mailhog

### ISSUE THREAD

**Issue by ghost** [testcontainers/testcontainers-java#4355]
Hey there,

we have created a module for [MailHog](https://github.com/mailhog/MailHog/) in our [fork](https://github.com/subshell/testcontainers-java/tree/master). MailHog is a mail server that simply collects mails (instead of delivering them) and offes a web interface to view all mails that have been sent. It also offers an API to retrieve these mails. This makes it possible to use it in integration tests for applications that send mails. With this issue I'd like to propose that new module. 

I will open a PR and you can give us feedback on what might be improved as to fit your requirements on modules. Of course only, when you deem this a useful module :)
I could not find an issue or PR regarding mailhog so I hope this is not a duplicate or otherwise discussed topic.

**Comment by eddumelendez** [comment]
See https://github.com/testcontainers/testcontainers-java/pull/4356#issuecomment-1607899752
