### ISSUE TITLE
Kibana testcontainer using a Generic container fails to start

### ISSUE THREAD

**Issue by mraliagha** [testcontainers/testcontainers-java#4361]
I am trying to build a test container for Kibana to use it with Elasticsearch Test Container. According to [this][1] I just need to set `ELASTICSEARCH_HOSTS` environment variable for a Kibana docker to start it successfully. However, I can confirm that when I try to pass Elasticsearch container in a form of `http://localhost:62084/`it accepts the url, but Kibana container fails to start. When I check logs I could see the following entry:

    {"type":"log","@timestamp":"2021-08-03T07:59:34+00:00","tags":["error","savedobjects-service"],"pid":952,"message":"Unable to retrieve version information from Elasticsearch nodes."}

I can check the docker and see that the kibana.yml config shows the following value:

    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true

So it looks like for some reason the `ELASTICSEARCH_HOSTS` variable was not effective.

You could find the code snippet for how I am setting Kibana testContainer using a Generic TestContainer below.

    private static final int KIBANA_DEFAULT_PORT = 5601;

    public KibanaContainer withElasticsearch(Network network, String elasticHostUrl) {
        withNetwork(network);
        withEnv("ELASTICSEARCH_HOSTS", elasticHostUrl);
        setWaitStrategy(new HttpWaitStrategy()
            .forPort(KIBANA_DEFAULT_PORT)
            .forStatusCodeMatching(response -> response == HTTP_OK || response == HTTP_UNAUTHORIZED)
            .withStartupTimeout(Duration.ofSeconds(120)));
        return self();
      }

Am I hitting some sort of bug with not being able to set env variables properly? I can confirm that Elasticsearch test container is running, but for some reason Kibana generic container cannot connect to it.

  [1]: https://www.elastic.co/guide/en/kibana/current/docker.html

**Comment by bsideup** [comment]
You shouldn't be using the host URL (may and most probably won't be accessible from Kibana container), but networks:
https://www.testcontainers.org/features/networking/#advanced-networking
