### ISSUE TITLE
Using outdated MockServer account on Docker Hub

### ISSUE THREAD

**Issue by msmsimondean** [testcontainers/testcontainers-java#4362]
Hi.  The image for MockServer seems to have moved on Docker Hub:  

Old Docker image: https://hub.docker.com/r/jamesdbloom/mockserver
New Docker image: https://hub.docker.com/r/mockserver/mockserver

In addition, the GitHub account and project have changed too.  If you try browsing to the old link, you'll see you're redirected to new one: 

Old GitHub project: https://www.github.com/jamesdbloom/mockserver
New GitHub project: https://github.com/mock-server/mockserver

You can also see this in action if you click the `source repository` link on the old Docker image page above

If you look at the `README.md` on the GitHub project, it links to the new Docker image location not the old one: 

https://github.com/mock-server/mockserver#docker-hub

When I try to use the new Docker image name with Testcontainers, I get this error: 

> java.lang.IllegalStateException: Failed to verify that image 'mockserver/mockserver:mockserver-5.11.2' is a compatible substitute for 'jamesdbloom/mockserver'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
>
> DockerImageName myImage = DockerImageName.parse("mockserver/mockserver:mockserver-5.11.2").asCompatibleSubstituteFor("jamesdbloom/mockserver");
>
> and then use `myImage` instead.

**Comment by bsideup** [comment]
MockServerContainer is compatible with both:
https://github.com/testcontainers/testcontainers-java/blob/c6f0eaa12d0b99d3ed5005b3220fedfbdcee3a28/modules/mockserver/src/main/java/org/testcontainers/containers/MockServerContainer.java#L37

Just make sure that you're using the latest version of Testcontainers (1.16.0) 👍

**Comment by msmsimondean** [comment]
Thanks @bsideup.  I've just tried upgrading 1.16.0.  I still get the error but I think it's because I'm using corporate mirror of Docker Hub, which I edited out of my error output above... 😄 

Here's the error I'm getting with the mirror URL swapped for an example one: 

```
Failed to verify that image 'example.com:123/mockserver/mockserver:mockserver-5.11.2' is a compatible substitute for 'jamesdbloom/mockserver'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
>
> DockerImageName myImage = DockerImageName.parse("example.com:123/mockserver/mockserver:mockserver-5.11.2").asCompatibleSubstituteFor("jamesdbloom/mockserver");
>
> and then use `myImage` instead.

**Comment by bsideup** [comment]
@msmsimondean yeah, for that one you need to explicitly say that it is compatible.

Also, consider using Docker Registry mirroring that preserves the image names:
https://docs.docker.com/registry/recipes/mirror/
