### ISSUE TITLE
Lambdas started in Testcontainers LocalStack fail to connect to S3

### ISSUE THREAD

**Issue by idontusenumbers** [testcontainers/testcontainers-java#4371]
I'm starting a Lambda inside a LocalStack Testcontainer.

TestConatiners gives the LocalStack container a random name. It then starts the container. The container is setup to introspect it's own internal IP address that is later used to tell Lambdas where all the services are located. It uses a default container name of `localstack_main` which does not match the random docker-given random name.

```
ERROR: 'docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' localstack_main': exit code 1; output: b'\nError: No such object: localstack_main\n'
2021-08-12T22:06:03:INFO:localstack.services.awslambda.lambda_executors: Unable to get IP address of main Docker container "localstack_main": Command 'docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' localstack_main' returned non-zero exit status 1.
```

It later passes the wrong IP address (I wasn't able to figure out where it comes from) to the Lambda container it spins up:
```
LOCALSTACK_HOSTNAME=192.168.65.2
```

Later, the S3 client fails to connect:
```
Connection refused: /192.168.65.2:4566
```

I've worked around this limitation by applying a hook:

```
    public static final String LOCALSTACK_CONTAINER_NAME = "localstack-" + MyClass.class.getSimpleName() + "-" + System.currentTimeMillis();

    @Container
    public static final LocalStackContainer localstackContainer =
            new LocalStackContainer(DockerImageName.parse(LOCALSTACK_DOCKER_IMAGE_NAME))
                    .withServices(LocalStackContainer.Service.DYNAMODB, LocalStackContainer.Service.S3, LocalStackContainer.Service.LAMBDA,
                            LocalStackContainer.Service.API_GATEWAY, LocalStackContainer.Service.CLOUDWATCHLOGS, LocalStackContainer.Service.IAM)
                    .withEnv(Map.of(
                            "MAIN_CONTAINER_NAME", LOCALSTACK_CONTAINER_NAME
                    ))
                    .withCreateContainerCmdModifier(c->c.withName(LOCALSTACK_CONTAINER_NAME))
            ;
```

Am I doing something wrong? Is there a better solution?

**Comment by eddumelendez** [comment]
@idontusenumbers It's probably because `LAMBDA_DOCKER_NETWORK` env var should be also added. There is an open [PR](https://github.com/testcontainers/testcontainers-java/pull/4614/files) about clarifying this in our docs but it has not been merged yet. Can you let us know if it works for you?

**Comment by idontusenumbers** [comment]
I'm no longer working on the related project so I cannot confirm.

**Comment by eddumelendez** [comment]
Sharing a recent [blogpost](https://hashnode.localstack.cloud/cloud-integration-testing-made-easy-localstack-testcontainers) from LocalStack demonstrating usage of S3 and Lambdas with Testcontainers
