### ISSUE TITLE
Broken link to .travis.yml example file in docs

### ISSUE THREAD

**Issue by cac03** [testcontainers/testcontainers-java#4373]
Hello,

the [General Docker requirements](https://www.testcontainers.org/supported_docker_environment/) page refers to a non-existent `.travis.yml` file in the repository. See the "Linux - Travis CI" row and the "Known issues / tips" column

The file has been removed in the 5d87f611fb628a201f30690b9141188754da0699 commit

**Comment by kiview** [comment]
Hi @cac03, 
thanks for bringing this to our attention, you are completely right.  I think the Travis part should be completely removed from `General Docker requirements` page. We can think about adding it to the `Continous Integration` section if we still feel the need to have this documented.

**Comment by cac03** [comment]
@kiview, thanks for your response

Yes, I wasn't sure what exactly would be appropriate to fix this.
I've created a #4374 PR to remove the "Travis CI" part from the page

**Comment by rnorth** [comment]
@kiview I'm not so sure that removing Travis CI entirely is the right thing just because we don't have an example configuration to point people towards...

I'd say that the table certainly needs a refresh, though.
