### ISSUE TITLE
New module: YugabyteDB

### ISSUE THREAD

**Issue by srinivasa-vasu** [testcontainers/testcontainers-java#4376]
Created a new module for [YugabyteDB](https://www.yugabyte.com). It supports 2 different APIs; YSQL based on Postgres and YCQL based on Cassandra. It is an open-source distributed SQL inspired by Google Spanner's design. 

Have submitted a [PR] #4372. Would love to hear your feedback and get this integrated.

**Comment by bsideup** [comment]
Hi @srinivasa-vasu,

Thanks! I will close this issue, PR is enough, and we can discuss it in the PR going forward 👍
