### ISSUE TITLE
Tests end with MongoSocketReadException: Prematurely reached end of stream

### ISSUE THREAD

**Issue by pas2al** [testcontainers/testcontainers-java#4378]
The tests are ok, but they stop with a log entry:

`com.mongodb.MongoSocketReadException: Prematurely reached end of stream`

I use Kotlin and the JUnit 5 support from testcontainers to set up the tests and `@DynamicPropertySource` from Spring Boot to configure the container. Is that a problem I should care about and if so, how do I avoid it? Is there a way to gracefully shut down the connection? I am not sure if this is really related to testcontainers.

**Comment by krisgerhard** [comment]
Don't close mongo container manually.

**Comment by kiview** [comment]
As others have pointed out, make sure to not close the container, while it is still in use. JUnit5 support will start and stop containers. So instead, it can be better to start the container yourself (and let them run until the JVM exits). Else, you can also just ignore the log message.

**Comment by blekione** [comment]
I have the same problem even when as suggested I do not close container manually. 

I believe this is a problem with Spring Boot trying to reach MongoDB (sending heartbeat?) after all tests are completed and MongoDB container being already closed.

**Comment by imrich-olha** [comment]
I have found a workable alternative solution there: https://stackoverflow.com/a/74274007
* remove the annotation @Container
* start container automatically 

```
        static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:5.0.13");
    
        static {
            mongoDBContainer.start();
        }
    
        @DynamicPropertySource  
        static void setProperties(DynamicPropertyRegistry registry) {  
           ...
        }
```

**Comment by auvaibhavsingh** [comment]
thx @imrich-olha  Working.

**Comment by leccyril** [comment]
i had the same issue the workaround is not working for me

```
private static final MongoDBAtlasLocalContainer mongoDBContainer = new MongoDBAtlasLocalContainer("mongodb/mongodb-atlas-local:latest");

	static {
		mongoDBContainer.start();
	}

@AfterAll
	static void tearDown() {
		mongoDBContainer.stop();
	}

```

com.mongodb.MongoSocketReadException: Prematurely reached end of stream i guess we need to stop after tests :)
