### ISSUE TITLE
Podman : using network is not working

### ISSUE THREAD

**Issue by alekssd** [testcontainers/testcontainers-java#4383]
Hi,

I'm using testcontainers to create containers and a network for them. 
When running on docker, everythings work fine. but when it run on podman, an error "network not found" appears when launching a container

`Network network = Network.newNetwork();
GenericContainer<?> amq = new GenericContainer<>(ACTIVE_MQ_DOCKER_IMAGE_NAME)
        .withExposedPorts(CONTAINER_CONFIG.getPort())
        .withLogConsumer(new Slf4jLogConsumer(getLogger("ActiveMQ")))
        .withNetwork(network)
        .withNetworkAliases(CONTAINER_CONFIG.getHost());`

error on podman :
`10:43:34.844 [main] ERROR 🐳 [docker.ssqti.ca/ssq/ca/ssq/activemq/activemq:5.16.0] - Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"network not found","message":"container create: container 6c2cdcb8197b8f6f5a483d9e1f808c3ca3e08b8525b8d3629937749de300dddb has network aliases for network \"af35c13cbd6b85d4a9a74f3ed2514e0962ef0651c1723cb1b2043dbb03fa9a0c\" but is not part of that network: network not found","response":500}`

Even if network actually exists :
![image](https://user-images.githubusercontent.com/15020053/130089449-c4ea82e1-c6c2-4284-8010-fa39089c406e.png)

**Comment by bsideup** [comment]
Hi @alekssd,

Since it works fine with Docker, please report this issue to Podman, especially given that you're getting status code 500 from them.

**Comment by 0x7d7b** [comment]
Just for completeness. This issue has been fixed here: https://github.com/containers/podman/issues/11285
