### ISSUE TITLE
Docker-java client is not thread safe

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#44]
Hi!

First of all, thanks for this cool project :) Here, at ZeroTurnaround, we created something similar, but will definitely try yours as well :) Even more - you already use our library - zt-exec :)

What we discovered during our work - DockerClient is not thread safe. We heavily recommend to replace SingletonDockerClient with ThreadLocalDockerClient, or client-per-container. 

See https://github.com/docker-java/docker-java/issues/339#issuecomment-149830497

**Comment by rnorth** [comment]
Hi Sergei,
Thanks for raising this, and thanks for zt-exec - I'm a fan of JRebel too! ;)

I'm wondering if I might have luckily dodged a bullet with my own [singleton wrapper](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/SingletonDockerClient.java) but I ought to check again with this thread safety issue in mind. I'm glad to be able to learn from your experiences in this area!

Thank you
Richard

**Comment by rnorth** [comment]
Ah, I misunderstood your point on first read - yes, this is probably a problem. Using a ThreadLocal seems like a good solution - I'll most likely go that route.
Thanks for this
Richard

**Comment by rnorth** [comment]
Released in v0.9.9 just now.
