### ISSUE TITLE
GenericContainer stop() method does more than expected.

### ISSUE THREAD

**Issue by dchambon** [testcontainers/testcontainers-java#440]
Hi,

I was looking for a stop() method to be able to simulate a failure with an external system.
In my test, I want to check the exception raised because of this failure and then, resume the container.
This sounds quite simple with docker command. You can just do:
```sh
docker stop <container-id>
docker start <container-id>
```
Looking at the ResourceReaper class, it seems that it will be quite easily to expose the "stopContainer" method (which actually already exists):
```java
 private void stopContainer(String containerId, String imageName) {
        boolean running;
        try {
            InspectContainerResponse containerInfo = dockerClient.inspectContainerCmd(containerId).exec();
            running = containerInfo.getState().getRunning();
        } catch (NotFoundException e) {
            LOGGER.trace("Was going to stop container but it apparently no longer exists: {}");
            return;
        } catch (DockerException e) {
            LOGGER.trace("Error encountered when checking container for shutdown (ID: {}) - it may not have been stopped, or may already be stopped: {}", containerId, e.getMessage());
            return;
}
```
Is there a good reason to not expose this method? If yes, would it be possible to rename the stop method in the GenericContainer class, it's misleading for me and can generate confusion as it's a little bit more than just a stop command in Docker.

Thanks for your feedback !

Damien

**Comment by bsideup** [comment]
Hi @dchambon,

The method name is misleading indeed! Maybe something like `destroy()` will serve better.

The ResourceReaper is semi-internal, I wouldn't expose too many methods of it.

FYI you can do start/stop by using the docker-java client:
```
container.getDockerClient().stopContainerCmd(container.getId());
container.getDockerClient().startContainerCmd(container.getId());
```

**Comment by dchambon** [comment]
Hi @bsideup,

Thanks a lot for the tip. I will use this for my test.

**Comment by kiview** [comment]
It's also interesting to know, that the `stop()` method call isn't idempotent, leading to an exception when calling the `stop()` method on an already stopped container.

Maybe we should rename the current method into `destroy()` and a an idempotent `stop()` method? (the Docker API allows calling stop on a stopped container btw.)
