### ISSUE TITLE
Github Actions TC PostgreSQL problems

### ISSUE THREAD

**Issue by ikorennoy** [testcontainers/testcontainers-java#4458]
Hi! 
I use TC **PostgreSQLContainerProvider** for my integration tests that run in Github Actions CI. And sometimes my tests accidentally fail with the following problem:
```
 Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/0:0:0:0:0:0:0:1:49155

            Caused by:
            java.net.ConnectException: finishConnect(..) failed: Connection refused
                at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
                at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
```
and the weird thing is that this may not be the first request. In the logs I see that everything is fine and the container starts normally, some requests were executed, and then the next time I get this error. And no additional messages from TC

Do you have any idea why this might be happening?

TC version: 1.16.0
Postgres tag: 13.3

**Comment by bsideup** [comment]
@ikorennoy it looks like your database client (I would assume this is either vertx or r2dbc, judging by Netty in the stacktrace) does not handle IPv6 correctly. Consider reporting to them, and, as a workaround, try replacing `localhost` with `127.0.0.1` when `getHost()` returns `localhost`.
