### ISSUE TITLE
Port Variable Visibility

### ISSUE THREAD

**Issue by Scuilion** [testcontainers/testcontainers-java#4468]
Postgress/MySQL ports are public:
https://github.com/testcontainers/testcontainers-java/blob/c97c1e3f62643e394fec17f2d28f3c83f3ce4ff6/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L23
https://github.com/testcontainers/testcontainers-java/blob/c97c1e3f62643e394fec17f2d28f3c83f3ce4ff6/modules/mysql/src/main/java/org/testcontainers/containers/MySQLContainer.java#L29
While the Oracle port is defined as private:
https://github.com/testcontainers/testcontainers-java/blob/c97c1e3f62643e394fec17f2d28f3c83f3ce4ff6/modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java#L21

Is this intentional, or can I update the Oracle module to expose the port number?

**Comment by kiview** [comment]
What is your use case for having the Oracle port public? 
Since the recent version of the Oracle module is quite new, we tried to keep API surface minimal.

**Comment by Scuilion** [comment]
I was implementing oracle test in a project that already had postgres test. So I was curious strictly from a consistency standpoint.

**Comment by kiview** [comment]
But there was no need for you to access the constant programmatically, or?
So ultimately the answer is about being conscious with regards to the unnecessary increase of API surface with new modules or changes.

**Comment by Scuilion** [comment]
Sure there is. If you want to create a connection string to your database you'd need to know the port number.

**Comment by kiview** [comment]
For this, `OracleContainer` provides the `getJdbcUrl()` method, same as other `JdbcContainers`. In addition, it specifically provides the `getOraclePort()` and `getWebPort()` methods.

So what is your actual use case, for which those methods don't suffice?

**Comment by Scuilion** [comment]
Ah, now I'm on the same page. Thanks for the hand holding!
