### ISSUE TITLE
Can't set output directory for FLV recordings

### ISSUE THREAD

**Issue by blacky0x0** [testcontainers/testcontainers-java#448]
I use Gradle as a build tool and Selenium Webdriver:
```
    @Shared
    public BrowserWebDriverContainer chrome = new BrowserWebDriverContainer()
            .withDesiredCapabilities(DesiredCapabilities.chrome())
            .withRecordingMode(RECORD_ALL, new File("./build/"))
```
But the recording always appeared under `./.tmp-volume-1503438720097/screen.flv`.
All is fine when I use maven build tool but something goes wrong when it runs with the Gradle. 
How I can change this behavior?

**Comment by rnorth** [comment]
@blacky0x0 sorry for taking so long to respond to this. Did you get anywhere with it?

The `.tmp-volume` directory is supposed to be temporary; when the tests are complete the video files should be moved in to the folder you specify and the tmp directory should be deleted. If that's not happening, it would be a bug, though.

**Comment by blacky0x0** [comment]
I'll try to check with other versions of `testcontainers` and with maven/gradle build tools. I think this bug somehow related with Groovy's or Gradle behavior. In any case I'll provide `vanilla` examples of code but I little bit later, maybe this weekend.

**Comment by rnorth** [comment]
@blacky0x0 did you manage to find any clues?

**Comment by blacky0x0** [comment]
Sorry, not yet

**Comment by kiview** [comment]
@blacky0x0 Can you provide the example project?

**Comment by blacky0x0** [comment]
@kiview yep, I've created new repo -> https://github.com/blacky0x0/tc-spock
Also I tested with `Maven` and `Gradle` build tools without `Spock` and the flv file is always saved as expected.
So as I understand the problem appears in the last step when gradle tries to save the flv file.

**Comment by DanteGrek** [comment]
Hi all, I faced with the same issue in my project https://github.com/DanteGrek/Prototype.
