### ISSUE TITLE
junit5 with selenium testcontainer not working

### ISSUE THREAD

**Issue by shameekagarwal** [testcontainers/testcontainers-java#4486]
Goal - I want to be able to write selenium tests, using Junit 5, and testcontainers. I am writing a very simple code to just be able to check an attribute of the search bar of google's homepage.

Issue - chrome.getWebDriver(); returns null. Am I missing something?
exception - **java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.manage()" because "driver" is null.** this is caused as I try to set an implicit wait after initializing WebDriver.

my pom.xml - 

```
<properties>
    <maven.compiler.source>16</maven.compiler.source>
    <maven.compiler.target>16</maven.compiler.target>
    <test-containers.version>1.16.0</test-containers.version>
    <selenium.version>3.141.59</selenium.version>
    <junit.version>5.8.1</junit.version>
</properties>

<dependencies>

    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>${selenium.version}</version>
    </dependency>

    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers</artifactId>
        <version>${test-containers.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>selenium</artifactId>
        <version>${test-containers.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>${test-containers.version}</version>
        <scope>test</scope>
    </dependency>

</dependencies>
```

My test class - 

```
@TestInstance(Lifecycle.PER_CLASS)
@Testcontainers
public class GoogleTest {

    @Container
    public BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>()
            .withCapabilities(Config.getChromeOptions());

    private GooglePage googlePage;

    @BeforeAll
    public void setup() throws Exception {
        // ISSUE IS WITH THE LINE BELOW
        WebDriver driver = chrome.getWebDriver();
        driver.manage().timeouts().implicitlyWait(7, TimeUnit.SECONDS);
        // trying to use page object model, just navigates to the google homepage
        googlePage = new GooglePage(driver);
    }

    @Test
    public void testTitle() throws Exception {
        WebElement element = googlePage.getSearchBar();
        Thread.sleep(5000);
        assertEquals(element.getAttribute("role"), "combobox");
    }

}
```

[link to code if you need it](https://drive.google.com/file/d/15Blts1Ek-ShF3gzXZ9mwzp9BRHJ6wHPb/view)

**Comment by kiview** [comment]
Hey @shameekagarwal,
please share your logs, so we can ensure that the `BrowserWebDriverContainer` did start correctly.

**Comment by shameekagarwal** [comment]
> Hey @shameekagarwal, please share your logs, so we can ensure that the `BrowserWebDriverContainer` did start correctly.

Hi, but that is all I have in my logs, nothing else...

**Comment by shameekagarwal** [comment]
got my mistake, if using junit5, [fields should be private static final](https://www.testcontainers.org/test_framework_integration/junit_5/#:~:text=private%20static%20final) I think...

I was still using [public](https://www.testcontainers.org/modules/webdriver_containers/#:~:text=The%20following%20field%20in%20your%20JUnit%20UI%20test%20class%20will%20prepare%20a%20container%20running%20Chrome%3A)

**Comment by kiview** [comment]
@shameekagarwal 
If you got it working that's great, but this is not related to the visibility modifier. However, using the `static` modifier has different implications and this is indeed the reason for the problem in this case.

`static` containers are shared for the whole test class (as opposed to non-static ones, which are on a per-method basis). So for the container to be available in your `@BeforeAll` method, it needs to be `static`. 

See the docs about [shared containers](https://www.testcontainers.org/test_framework_integration/junit_5/#shared-containers).
