### ISSUE TITLE
Issue with 'withExposedPorts' using multiple ports

### ISSUE THREAD

**Issue by ofirgrm** [testcontainers/testcontainers-java#4492]
`addExposedPorts` uses an array to set the `exposedPorts` declared as `LinkedHashSet`, so it maintains the order of insertions.
However, `withExposedPorts`, uses `Lists.newArrayList(ports)` which internally calls Collections.addAll(...) which does not maintain the order of insertaion.
The result is unexpected behaviour, in particular, an issue when setting the `waitingFor` strategy.  
For instance, say we call: `withExposedPorts(8080,1234)` and then set waiting strategy as: `Wait.forHttp(...)`
If Collections decides to place 1234 first, then the code will listen using port 1234, instead of 8080.

**Comment by ofirgrm** [comment]
It seems that using addExposedPort didn't solve my issue, so perhaps the bug is with the waiting strategy.
In more detail, I have a generic container with the following settings (the ones that relevant for this issue):

`  .withEnv("JAVA_TOOL_OPTIONS", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000")`
`  .addExposedPorts(8080,5000);`
`  .waitingFor(Wait.forHttp("/actuator/health"));`

What I'm experiencing is the following intermediate error, that seems to appear once in every few runs:
`STDERR: Debugger failed to attach: handshake failed - received >GET /actuator/< - expected >JDWP-Handshake<`

It looks like, test containers listen to the wrong port (5000) instead of 8080 to check the container.
It may or may not be related to the way exposed ports are implemented, but that was my initial suspicion.

I'm currently trying to reproduce the issue and debug HttpWaitStrategy.waitUntilReady()

**Comment by ofirgrm** [comment]
Good news :) I have found the bug and it's at [WaitStrategyTarget.java](https://github.com/testcontainers/testcontainers-java/blob/1.15.3/core/src/main/java/org/testcontainers/containers/wait/strategy/WaitStrategyTarget.java
)

The following code returns a set of ports **without** maintaining the order:
`        final Set<Integer> result = getExposedPorts().stream().map(this::getMappedPort).distinct().collect(Collectors.toSet());`

Collectors.toSet() doesn't maintain the order and once in a while it will return the second port first (it took me over 10 times to reproduce it and I believe it has to do with the address reference of the two Integer objects)

This should be fixed by using LinkedHashSet (same type as used to hold the ports):
`.collect(Collectors.toCollection(LinkedHashSet::new))` instead of `.collect(Collectors.toSet())`

I also suggest tracking down all the places in the code where the ports are being streamed and collected with a type that does not guarantee order.

**Comment by bsideup** [comment]
@ofirgrm http wait strategy implicitly picks *any* port, but it is recommended to use `forPort` when there is more than one. This isn't really a bug per se, as the order is never guaranteed. Does it help? :)

**Comment by ofirgrm** [comment]
I assumed there was an order guaranteed since the ports are stored using LinkedHashSet.
Using forPort will definitely solve the issue I'm having, so thanks for that!
@bsideup, I think adding a line of documentation about it at https://www.testcontainers.org/features/startup_and_waits/ can be very useful.

Thanks.
