### ISSUE TITLE
Document `GenericContainer#dependsOn`

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#4546]
See https://testcontainers.slack.com/archives/C1SUBPZK6/p1633448590117400?thread_ts=1633433982.114000&cid=C1SUBPZK6

**Comment by harshadt21** [comment]
Hi @bsideup , I would like to work on this issue. I am a newbie, will  appreciate your help to get started?

**Comment by bsideup** [comment]
Hi @harshadt21,

Thanks for volunteering to fix this!

Here is the source file of the relevant docs page:
https://github.com/testcontainers/testcontainers-java/blob/master/docs/features/startup_and_waits.md

You will find `inside_block` references - these point to a source file (usually, a test) that contains the code snipped that should be included into the docs. We just need to add a section about `dependsOn` and include a short snippet that will demonstrate the usage.

Perhaps we could also cross-reference it from https://github.com/testcontainers/testcontainers-java/blob/master/docs/features/networking.md#advanced-networking

Also see https://www.testcontainers.org/contributing_docs/ - it explains how to make contributions to the docs and how to check them locally. I hope this is helpful!

**Comment by shan-sahaj** [comment]
Hi @bsideup ,  If no one is working on this I can take this up. I use your library in our integration tests. So makes more sense to start commiting to this project.  I will start looking at it and would be waiting for a go-ahead or otherwise from you

**Comment by kiview** [comment]
Hey @shan-sahaj, contributions around the documentation for `dependsOn` would be very much appreciated, thx 🙂

**Comment by shan-sahaj** [comment]
@bsideup , I have finished the documentation and also consequently added a snippet in "../examples/junit4/generic/src/test/java/generic/WaitStrategiesTest.java" . But then when I try to build the
../examples/junit4/generic/src/test/java/generic project the "MinimumDurationStrategyTest" is always failing. I aborted building the whole project as it was taking a long time. What is going wrong?

**Comment by REslim30** [comment]
It seems like this already completed in https://github.com/testcontainers/testcontainers-java/pull/5597. It's now at the bottom of https://github.com/testcontainers/testcontainers-java/blob/master/docs/features/startup_and_waits.md. I think this issue should be closed.

**Comment by kiview** [comment]
You are right @REslim30, thank you so much for letting us know 🙂

 Fixed by #5597.
