### ISSUE TITLE
Use -bin Gradle wrapper instead of -all

### ISSUE THREAD

**Issue by vlsi** [testcontainers/testcontainers-java#4559]
Please use `gradle-*-bin.zip` in https://github.com/testcontainers/testcontainers-java/blob/d21a3df1af4afb7007f60468c44631692efecf02/gradle/wrapper/gradle-wrapper.properties#L4
`-all` consumes network traffic and space at the dev machines.

Just in case, Gradle uses `-bin`: https://github.com/gradle/gradle/blob/21f42ea268a02de4ae093b52ebaffef00cbffcad/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by mattca** [comment]
One drawback of switching to `-bin` is that `-all` contains source code and documentation which could be useful for tweaking the gradle files when devving in an IDE.

**Comment by vlsi** [comment]
IDE can download code and documentation even when `-bin` is used.

I believe Gradle core developers do use "code and documentation", and they use `-bin` distribution.
If Gradle team is OK with `-bin`, do you think it won't work for you for some reason?

**Comment by kiview** [comment]
We will close this issue for now since it does not affect users but will consider it once we update Gradle the next time. Thanks for bringing it to our attention @vlsi.
