### ISSUE TITLE
Attach container to an existing network using it's id

### ISSUE THREAD

**Issue by ratcashdev** [testcontainers/testcontainers-java#4566]
I'd like to attach a newly pulled container to an existing set of containers (started externally using docker compose) running on network 'docker_default'.
Please advice how could this be done. Thanks.

Or simply allow the compose module to attach to an existing (and running) compose 'project' started from outside and create the socat container inside it so that we are able to do port maps.

**Comment by kiview** [comment]
You can instantiate a new `Network` using the external id:
```java
Network n = new Network() {
    @Override
    String getId() {
        return "existingId" // use id of external network
    }

    @Override
    void close() throws Exception {

    }

    @Override
    Statement apply(Statement base, Description description) {
        return null
    }
}

container.withNetwork(n)
```
