### ISSUE TITLE
testcontainers patch on graviton2 (ec2 aws arm64)

### ISSUE THREAD

**Issue by welly87** [testcontainers/testcontainers-java#4575]
Hi Teams,

Currently i'm working on porting airbyte to ec2 graviton2 arm processor. One of dependencies is testcontainers as it's used a lot on the e2e test. 

I've manage to fix some lombok issues. Basically just upgrading to the new version 1.18.22. 

Here's the commits and repos.

https://github.com/weltam/testcontainers-java/commit/c95e0142acb9fa58193af284a74bdc019acc981c

**Comment by eddumelendez** [comment]
Nowadays, we are using lombok 1.18.24. That should fix your issue @welly87 ! Feel free to reopen if still having issues with latest versions of testcontainers.
