### ISSUE TITLE
Support for Selenium 4 video recording

### ISSUE THREAD

**Issue by tobiasstadler** [testcontainers/testcontainers-java#4579]
Selenium 4 has native support for recording videos (see https://github.com/SeleniumHQ/docker-selenium#video-recording-). It would be nice if testcontainers supports this as an alternative to the testcontainers video recording.

**Comment by kiview** [comment]
Hey @tobiasstadler, thanks for sharing this idea. 

This is definitely something we can explore in the future. What do you think are the advantages of using this approach as compared to the one Testcontainers currently provides?

**Comment by tobiasstadler** [comment]
Right now there are probably one. Their may (or may not) be cool features in the future. Also the native recording hopefully handles breaking changes without me noticing it.

**Comment by OLibutzki** [comment]
Might be resonable to use the Selenum feature in order to reduce the maintainability efforts for testcontainers. I'm quite sure that Selenium is going to develop the core and the recording feature hand in hand.

**Comment by moz9ovic** [comment]
@tobiasstadler I would like to take a try at this as first issue, can you assign it to me ?

**Comment by eddumelendez** [comment]
Closing in favor of #8575

**Comment by mm-kishanp** [comment]
Try using https://playwright.dev/dotnet/docs/videos
