### ISSUE TITLE
1.16.1 - Kafka container port detection fails if TESTCONTAINERS_HOST_OVERRIDE is used

### ISSUE THREAD

**Issue by jyyna** [testcontainers/testcontainers-java#4591]
Hi, 
after upgrading from version 1.16.0 to 1.16.1, when Kafka container is started on remote server running Docker daemon, it is not detected as running.
I have this environment variable set:  TESTCONTAINERS_HOST_OVERRIDE=my.docker.host

2021-10-19T15:23:02.495Z INFO ?.2.1] /main/ [traceId:,spanId:] - Creating container for image: confluentinc/cp-kafka:6.2.1
2021-10-19T15:23:02.668Z INFO ?.2.1] /main/ [traceId:,spanId:] - Starting container with ID: 2a30058d1f6b46ba0d7d2aa9e1d45f06e14cb0b1f894fef05404a467c44ac9a7
2021-10-19T15:23:03.900Z INFO ?.2.1] /main/ [traceId:,spanId:] - Container confluentinc/cp-kafka:6.2.1 is starting: 2a30058d1f6b46ba0d7d2aa9e1d45f06e14cb0b1f894fef05404a467c44ac9a7
2021-10-19T15:23:16.376Z ERROR ?.2.1] /main/ [traceId:,spanId:] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (my.docker.host ports: [49472, 49471] should be listening) 

container in fact runs on the remote server (or seems to be running), it is just not detected as running

Runs ok with version 1.16.0.

**Comment by jyyna** [comment]
> Hi @jyyna , thanks for reporting this.
> 
> Can you please try to configure it using `docker.host` in `~/.testcontainers.properties` instead and see if this solves the issue? (also see this part of the docs: https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection)
Hi,
I have DOCKER_HOST env var set to tcp://localhost:2375 and then tunneled to /var/run/docker.sock on target server:
```
export DOCKER_HOST=tcp://localhost:2375  
export TESTCONTAINERS_HOST_OVERRIDE=my.docker.host  
ssh -L 127.0.0.1:2375:/var/run/docker.sock my.docker.host
```

adding the docker.host= setting to `~/.testcontainers.properties` did not help

**Comment by jyyna** [comment]
> Yes, it should work, can you please try it out?

sure. it did not work. Cannot connect to ryuk on localhost:49888

**Comment by kiview** [comment]
Oh sorry, I thought you are setting `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`, sorry for the confusion, we will look into this.

**Comment by bsideup** [comment]
Hi @jyyna,

When container fails, in prints the logs of the container. Could you please share them?

**Comment by jyyna** [comment]
[kafka-container.log.gz](https://github.com/testcontainers/testcontainers-java/files/7381887/kafka-container.log.gz)

**Comment by jyyna** [comment]
[testrun.log.gz](https://github.com/testcontainers/testcontainers-java/files/7388635/testrun.log.gz)

**Comment by jyyna** [comment]
I'll try later today to prepare some repo with code, that will run in 1.16.0 and not with 1.16.1
