### ISSUE TITLE
cannot use pipe in execInContainer

### ISSUE THREAD

**Issue by lukasGemela** [testcontainers/testcontainers-java#4612]
Hello, 

following up on https://stackoverflow.com/questions/69569247/how-to-pipe-commands-in-testcontainers-execincontainer-metod 

I have the same issue and I could not make my command working with pipe, it's always evaluated as single command, so for example things like 

`echo 'something' | processStringCommand `

simply prints `'something' | processStringCommand   to stdout.`

Is it expected behaviour? If yes can we update documentation?

**Comment by bsideup** [comment]
piping is a property of a shell.

Try execInContainer("sh", "-c", "foo | bar")

**Comment by lukasGemela** [comment]
that did work, thanks!
