### ISSUE TITLE
Documentation not displaying properly for 'Docker wormhole pattern'

### ISSUE THREAD

**Issue by wimdeblauwe** [testcontainers/testcontainers-java#4656]
The documentation at https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/ looks like this:

![image](https://user-images.githubusercontent.com/1115823/139816904-5d1db8ff-a01e-4f16-b055-4dcf744a186d.png)

I assume the issue is that there needs to be an extra newline at https://github.com/testcontainers/testcontainers-java/blob/master/docs/supported_docker_environment/continuous_integration/dind_patterns.md?plain=1#L30

So this:

```
Where:
* `-v $PWD:$PWD` will add your current directory as a volume inside the container
* `-w $PWD` will set the current directory to this volume
* `-v /var/run/docker.sock:/var/run/docker.sock` will map the Docker socket
```

becomes:

```
Where:

* `-v $PWD:$PWD` will add your current directory as a volume inside the container
* `-w $PWD` will set the current directory to this volume
* `-v /var/run/docker.sock:/var/run/docker.sock` will map the Docker socket
```

**Comment by kiview** [comment]
Oh, you are right @wimdeblauwe, thanks for notifying us. Wonder why it happens since the GitHub markdown preview looks correct, but might be specifics of mkdocs. 

Do you want to provide the PR? 🙂

**Comment by wimdeblauwe** [comment]
See https://github.com/testcontainers/testcontainers-java/pull/4658 for PR
