### ISSUE TITLE
Method of exposing UDP port changed in 1.16.0

### ISSUE THREAD

**Issue by KyleAure** [testcontainers/testcontainers-java#4667]
I am upgrading from:
TestContainers 1.15.3 -> 1.16.2
Docker-Java 3.2.8 -> 3.2.12

In order to expose a UDP port, users are required to access the underlying docker-java command, and modify it to expose the desired port.  In my project I am doing this using a custom container class and overwriting the `configure()` method as follows: 

```java
public class KerberosContainer extends GenericContainer<KerberosContainer> {
    @Override
    protected void configure() {
        withExposedPorts(99, 464, 749); //TCP ports
        withNetworkAliases(KRB5_KDC);
        withCreateContainerCmdModifier(cmd -> {
            List<ExposedPort> ports = new ArrayList<>();
            for (ExposedPort p : cmd.getExposedPorts()) {
                ports.add(p);
            }
            ports.add(new ExposedPort(99, InternetProtocol.UDP));
            cmd.withExposedPorts(ports);
	    cmd.withHostName(KRB5_KDC);
        });
    }
}
```

Once the container is started, I try to extract the mapped port using the `InspectContainerResponse` object as follows:

```java
    @Override
    protected void containerIsStarted(InspectContainerResponse containerInfo) {
        NetworkSettings networkSettings = containerInfo.getNetworkSettings();
        Ports ports = networkSettings.getPorts();
        Map<ExposedPort, Binding[]> map = ports.getBindings();
        Binding[] bindings = map.get(new ExposedPort(99, InternetProtocol.UDP));
        Binding binding = bindings[0];  //NullPointerException
        String udp99 = binding.getHostPortSpec();

        udp_99 = Integer.valueOf(udp99);
    }
```

A NullPointerException is thrown because the `withCreateContainerCmdModifier` was not honored. 
This is apparent when inspecting the container created directly with docker:

![Screen Shot 2021-11-09 at 1 39 18 PM](https://user-images.githubusercontent.com/33664635/140993441-0a942ca2-1866-4f24-b7a7-74225cf158a8.png)

And printing out the contents of the bindings map at runtime

```txt
{
  749/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@3bcb01f9, 
  464/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@defb0e3a, 
  99/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@15c64f5f, 
  99/udp=null, 
  88/tcp=null
}
```

**Comment by KyleAure** [comment]
I believe this is also related to issue #4489

**Comment by KyleAure** [comment]
It looks like this broke because `createCommand.withPublishAllPorts(true);` was removed from the generic container configure step as part of PR #4122 
This means that in order to publish a UDP port we need to both `expose` the port and provide a `port binding`.  Whereas, before if we expose the port, it was bound automatically. 

Here is a sample of what I needed to do to work around this: 
```java
GenericContainer container = new GenericContainer<>(image)
    .withExposedPorts(8080, 8081)
    .withCreateContainerCmdModifier(cmd -> {
        //Add previously exposed ports and UDP port
        List<ExposedPort> exposedPorts = new ArrayList<>();
        for (ExposedPort p : cmd.getExposedPorts()) {
            exposedPorts.add(p);
        }
        exposedPorts.add(ExposedPort.udp(99));
        cmd.withExposedPorts(exposedPorts);

        //Add previous port bindings and UDP port binding
        Ports ports = cmd.getPortBindings();
        ports.bind(ExposedPort.udp(99), Ports.Binding.empty());
        cmd.withPortBindings(ports);
    }
```

**Comment by bsideup** [comment]
Putting "wontfix" here because it isn't a breaking change but an assumption that got changed. We never guaranteed that we will bind ports that were added through `withCreateContainerCmdModifier` and going that route means that now you are dealing with Docker's low level API and need to understand how it behaves.

**Comment by KyleAure** [comment]
Closing this issue as no work needs to be done to fix this, just a code change on the user's part.  Keeping associated PR open just in case the maintainers want to add this as a test case to prevent future regression testing.

**Comment by kiview** [comment]
Thanks @KyleAure, your help is much appreciated 🙌
