### ISSUE TITLE
[oracle-xe/OracleContainer] Complete the list of Oracle System Users to avoid as APP_USER for Oracle XE Containers

### ISSUE THREAD

**Issue by loiclefevre** [testcontainers/testcontainers-java#4682]
Hello,
The OracleContainer class checks the user names passed through the `withUsername()` method against a list of Oracle database users (currently as of 1.16.2: SYS and SYSTEM).

As a matter of fact, any user or role being common and oracle_maintained would need to be avoided (running this query as sys):

```
select distinct username from cdb_users where common='YES' and oracle_maintained='Y' 
union
select distinct role from cdb_roles where common='YES' and oracle_maintained='Y' 
order by 1;
```

ACCHK_READ
ADM_PARALLEL_EXECUTE_TASK
ANONYMOUS
APPLICATION_TRACE_VIEWER
APPQOSSYS
AQ_ADMINISTRATOR_ROLE
AQ_USER_ROLE
AUDIT_ADMIN
AUDIT_VIEWER
AUDSYS
AUTHENTICATEDUSER
AVTUNE_PKG_ROLE
BDSQL_ADMIN
BDSQL_USER
CAPTURE_ADMIN
CDB_DBA
CONNECT
CTXAPP
CTXSYS
DATAPATCH_ROLE
DATAPUMP_EXP_FULL_DATABASE
DATAPUMP_IMP_FULL_DATABASE
DBA
DBFS_ROLE
DBMS_MDX_INTERNAL
DBSFWUSER
DBSNMP
DGPDB_INT
DIP
DVF
DVSYS
DV_ACCTMGR
DV_ADMIN
DV_AUDIT_CLEANUP
DV_DATAPUMP_NETWORK_LINK
DV_GOLDENGATE_ADMIN
DV_GOLDENGATE_REDO_ACCESS
DV_MONITOR
DV_OWNER
DV_PATCH_ADMIN
DV_POLICY_OWNER
DV_SECANALYST
DV_STREAMS_ADMIN
DV_XSTREAM_ADMIN
EM_EXPRESS_ALL
EM_EXPRESS_BASIC
EXECUTE_CATALOG_ROLE
EXP_FULL_DATABASE
GATHER_SYSTEM_STATISTICS
GDS_CATALOG_SELECT
GGSYS
GGSYS_ROLE
GLOBAL_AQ_USER_ROLE
GSMADMIN_INTERNAL
GSMADMIN_ROLE
GSMCATUSER
GSMROOTUSER
GSMROOTUSER_ROLE
GSMUSER
GSMUSER_ROLE
GSM_POOLADMIN_ROLE
HS_ADMIN_EXECUTE_ROLE
HS_ADMIN_ROLE
HS_ADMIN_SELECT_ROLE
IMP_FULL_DATABASE
LBACSYS
LBAC_DBA
LOGSTDBY_ADMINISTRATOR
MAINTPLAN_APP
MDDATA
MDSYS
OEM_ADVISOR
OEM_MONITOR
OLAP_XS_ADMIN
OPTIMIZER_PROCESSING_RATE
ORACLE_OCM
OUTLN
PDB_DBA
PPLB_ROLE
PROVISIONER
RDFCTX_ADMIN
RECOVERY_CATALOG_OWNER
RECOVERY_CATALOG_OWNER_VPD
RECOVERY_CATALOG_USER
REMOTE_SCHEDULER_AGENT
RESOURCE
SCHEDULER_ADMIN
SELECT_CATALOG_ROLE
SODA_APP
SYS
SYS$UMF
SYSBACKUP
SYSDG
SYSKM
SYSRAC
SYSTEM
SYSUMF_ROLE
XDB
XDBADMIN
XDB_SET_INVOKER
XDB_WEBSERVICES
XDB_WEBSERVICES_OVER_HTTP
XDB_WEBSERVICES_WITH_PUBLIC
XS$NULL
XS_CACHE_ADMIN
XS_CONNECT
XS_NAMESPACE_ADMIN
XS_SESSION_ADMIN

Any attempt to create such a user (done by the container-entrypoint.sh script used for gvenzl/oracle-xe images) will indeed fail otherwise.

Thanks

**Comment by eddumelendez** [comment]
My suggestion is to add a link to the oracle database docs or docker image docs so it can be linked.
