### ISSUE TITLE
Enable ELASTICSEARCH service in LocalStackContainer

### ISSUE THREAD

**Issue by RubenCordeiro** [testcontainers/testcontainers-java#4684]
https://github.com/testcontainers/testcontainers-java/blob/ce7693e20bbc21a5e2baca58a8ee0de9223393d9/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L335

Currently the ElasticSearch service is commented out in the LocalStackContainer class, even though the service is available in the latest versions of localstack. What documentation would be required to submit a PR in order to enable this service?

Thank you in advance.

**Comment by eddumelendez** [comment]
Hi @RubenCordeiro, this is not a limitation given you can use `LocalStackContainer localstack = new LocalStackContainer(LOCALSTACK_IMAGE).withServices(LocalStackContainer.EnabledService.named("es"))`

**Comment by eddumelendez** [comment]
Closing due to not last message was not acknowledged.
