### ISSUE TITLE
Images built by `ImageFromDockerfile` are always deleted by ryuk

### ISSUE THREAD

**Issue by Mahoney** [testcontainers/testcontainers-java#4702]
despite setting `deleteOnExit = false`.

Because `ImageFromDockerfile.resolve` does a `labels.putAll(DockerClientFactory.DEFAULT_LABELS)` the `ryuk` container will delete the image despite calling it as so:
```java
GenericContainer container = new GenericContainer(
      new ImageFromDockerfile(
        "my-name", // dockerImageName
        false      // deleteOnExit
      ).withDockerfile(Paths.get("./my.dockerfile"))
    );
container.start()
```

As it also prunes, this means all the created layers are discarded so no layer caching on subsequent builds.

**Comment by loic-seguin** [comment]
Hi everyone, is there anything ongoing to solve this problem ?

**Comment by kiview** [comment]
Fixed by https://github.com/testcontainers/testcontainers-java/pull/5391.
