### ISSUE TITLE
Permissions issues in Neo4j container in Jenkins agent

### ISSUE THREAD

**Issue by mdelmoral** [testcontainers/testcontainers-java#4703]
Hi,

I'm running my tests with `mvn clean verify `command with the Testcontainers configuration below:

```
@Testcontainers
public abstract class AbstractNeo4jTestSupport {

    static Neo4jContainer<?> neo4jContainer = new Neo4jContainer<>("neo4j:4.2.4")
        .withEnv("NEO4JLABS_PLUGINS", "[\"apoc\"]")
        .withNeo4jConfig("dbms.security.procedures.unrestricted", "apoc.*")
        .withReuse(true);
    static {
        neo4jContainer.start();
    }

    @DynamicPropertySource
    static void neo4jProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.neo4j.uri", neo4jContainer::getBoltUrl);
        registry.add("spring.neo4j.authentication.username", () -> "neo4j");
        registry.add("spring.neo4j.authentication.password", neo4jContainer::getAdminPassword);
    }
...
}
```
When the tests are run in my local machine they work great. The container with Neo4j is started and the tests are green. This is the Docker version running in my local machine (OS):
```
Connected to docker:
  Server Version: 20.10.10
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 1986 MB
```
The problems arise when I run these same tests in our CI environment which is a Jenkins with standard java agents. This is the Docker version in our CI environment.
```
Connected to docker: 
  Server Version: 18.09.2
  API Version: 1.39
  Operating System: Ubuntu 16.04.2 LTS
  Total Memory: 3008 MB
```
And the errors are:
```
ERROR 🐳 [neo4j:4.2.4] - Log output from the failed container:
stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/databases': Operation not permitted
Warning: Folder mounted to "/data/databases" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/transactions': Operation not permitted
Warning: Folder mounted to "/data/transactions" is not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Installing Plugin 'apoc' from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.5/apoc-4.2.0.5-all.jar to /var/lib/neo4j/plugins/apoc.jar 
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
...
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.IllegalStateException: Container exited with code 1
```
Another difference I've seen is that Jenkins uses the `sshd` image.

I don't know if I'm missing any configuration options. 
Another possible alternative would be to upgrade Docker in our CI environment but this is the last option I would like to do. We have other tests running with MySQL and Mongo containers and they work perfectly.

Thank you!

**Comment by kiview** [comment]
Hey @mdelmoral, thanks for reporting this issue.

Can you check if you can run a Neo4j Docker container directly from Docker CLI on your CI system, rather than with Testcontainers? Could be compatibility programs with the Neo4j image with regards to your older Docker version and specifically the very old Ubuntu version (but it's just a guess).

**Comment by mdelmoral** [comment]
Hi, @kiview 
Sorry for the delay. I don't have access to the CI system and I had to request your proposed test (create a single Neo4J container). Surprisingly (for me!) the single Neo4j container did not work with the same error as Testcontainers so we can close this issue.
Sorry for this non-issue and thank you for your time.

**Comment by kiview** [comment]
Cool, thanks for trying this out and letting us know, I will close the issue 👍
