### ISSUE TITLE
`ContainerState#getContainerIpAddress()` returns a non-IP string

### ISSUE THREAD

**Issue by mateuszrzeszutek** [testcontainers/testcontainers-java#4715]
The `getContainerIpAddress()` method may return `"localhost"`, which is not an IP address (it indirectly calls the `DockerClientProviderStrategy#resolveDockerHostIpAddress()` method, which uses `"localhost"` as a fallback value for a couple of cases). The javadoc says `@return an IP address` and doesn't mention that the method can return non-IP values at all.

Also see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4745

**Comment by bsideup** [comment]
Hi @mateuszrzeszutek,

Thanks. We should really deprecate `getContainerIpAddress()` as we were providing `getHost()` for years for exactly the reason you described - confusing name of the original method.

Consider using `getHost()` everywhere, and we will mark `getContainerIpAddress()` as deprecated in future releases 👍

**Comment by mateuszrzeszutek** [comment]
Got it 👍 
Thanks for the prompt response!
