### ISSUE TITLE
[Documentation Request] Wait for Port

### ISSUE THREAD

**Issue by bearrito** [testcontainers/testcontainers-java#476]
I did not see this addressed in the documentation. What port does the Wait methods use?

**Comment by bearrito** [comment]
I think this can be closed I dug through the src and saw the following



```
 protected Integer getLivenessCheckPort() {
        if (exposedPorts.size() > 0) {
            return getMappedPort(exposedPorts.get(0));
        } else if (portBindings.size() > 0) {
            return Integer.valueOf(PortBinding.parse(portBindings.get(0)).getBinding().getHostPortSpec());
        } else {
            return null;
        }
    }
```

It seems that the answer is : The first port among exposed ports.

**Comment by bsideup** [comment]
Hi @bearrito,

It's mentioned in the docs ( https://www.testcontainers.org/usage/options.html#customizing-the-container ):
> Ordinarily Testcontainers will wait for up to 60 seconds for the container's first mapped network port to start listening.

Do you think we need to be more explicit or it is fine?
