### ISSUE TITLE
Getting DB credentials when using JDBC url

### ISSUE THREAD

**Issue by cesartl** [testcontainers/testcontainers-java#477]
When using the [Mysql JDBC url](https://www.testcontainers.org/usage/database_containers.html#jdbc-url) how can one get the usersname and password?

This is useful if you need to pause your test and debug the database.

**Comment by bsideup** [comment]
Hi @cesartl,

username and password are static, you can get them [from the source code ](https://github.com/testcontainers/testcontainers-java/blob/357d5752a134bc340b1054acedf2eb78f7f24e64/modules/mysql/src/main/java/org/testcontainers/containers/MySQLContainer.java#L13) or by doing `new MySQLContainer().getPassword()` :)

**Comment by bsideup** [comment]
FYI there is a tag at StackOverflow to ask questions:
https://stackoverflow.com/questions/tagged/testcontainers

;)

**Comment by cesartl** [comment]
ha for some reason I assumed it was dynamic.

thanks for that.
