### ISSUE TITLE
DockerComposeContainer not surfacing methods to execute commands in sub-containers

### ISSUE THREAD

**Issue by LazarLazarov** [testcontainers/testcontainers-java#4780]
After scouring the docs and lots of web searching I still can't figure out how to execute commands in the nested containers spawned by `DockerComposeContainer`. 

The [docs](https://www.testcontainers.org/modules/docker_compose/#local-compose-mode) only mention the `getServiceHost` and `getServicePort` methods which can be used to piece together a URL, but then I'd need to manually go and install `sshd` in each child container and then programatically ssh into each one to execute the commands, which seems too convoluted to be the preferred approach. 

Could someone tell me what's the best practice for running arbitrary commands agains the child containers of the `DockerComposeContainer` class? Thanks

**Comment by WilsonSunBritten** [comment]
I've recently done dockerComposeContainer.getContainerByServiceName(MY_SERVICE).get().exectInContainer(...)
