### ISSUE TITLE
Feature-request: OpenSearch testcontainer?

### ISSUE THREAD

**Issue by nightswimmings** [testcontainers/testcontainers-java#4782]
Would be nice to have OpenSearch test-container since Amazon moved out of Elastic due to license restrictions

**Comment by loicmathieu** [comment]
I'm using the following code with Opensearch, but better to have a module for it.

```java
    static GenericContainer<?> opensearchContainer = new GenericContainer<>(
        DockerImageName.parse("opensearchproject/opensearch")
            // Aiven managed version
            .withTag("1.1.0")
    );

    @BeforeAll
    public static void  start() {
        opensearchContainer.withExposedPorts(9200);
        opensearchContainer.setWaitStrategy((new HttpWaitStrategy())
                .forPort(9200)
                .forStatusCodeMatching(response -> response == 200 || response == 401));
        opensearchContainer.withEnv("discovery.type", "single-node");
        opensearchContainer.withEnv("DISABLE_INSTALL_DEMO_CONFIG", "true");
        opensearchContainer.withEnv("DISABLE_SECURITY_PLUGIN", "true");
        opensearchContainer.start();
    }

    @AfterAll
    public static void stop() {
        opensearchContainer.stop();
    }
```

**Comment by kiview** [comment]
Thanks for providing this example @loicmathieu. Indeed, in many cases using `GenericContainer` (or writing your own class if you want to avoid code duplication) is the preferred approach, especially if the image is straightforward to use. Since this seems to be the case for the OpenSearch image, I will close this issue for now.

If someone has some good arguments why there should be a dedicated container implementation instead, feel free to share them and we can consider reopening the issue.

**Comment by kiview** [comment]
Hi @reta, thanks a lot for your detailed outline. While I don't disagree with your arguments, I would not expect us to provide an OpenSearch module for the time being.

If the `GenericContainer` based approach by @loicmathieu generally works for you, I would suggest either including it in your project directly or by adding your own implementation through extending `GenericContainer`. 

Another alternative is going ahead with a community-maintained repository for the time being (we have other examples of this, such as https://github.com/dasniko/testcontainers-keycloak). If this is adopted by the community, we can always discuss integrating it directly into Testcontainers in the future.

**Comment by reta** [comment]
Now official repo and releases: https://github.com/opensearch-project/opensearch-testcontainers/
