### ISSUE TITLE
rancher-desktop: Could not find a valid Docker environment. Please see logs and check configuration

### ISSUE THREAD

**Issue by automationman666** [testcontainers/testcontainers-java#4783]
DockerClientProviderStrategy.java is unable to locate the docker environment when using rancher-desktop. 

Any suggestions on how this can be fixed? or does it require an enhancement?

**Comment by bsideup** [comment]
Last time we checked, Rancher Desktop did not expose Docker API. To run Testcontainers, you need to have Docker API available, either with Docker or alternatives to it (such as Podman).

There is nothing to fix in Testcontainers. Once/if Rancher Desktop adds support for Docker API, you should be able to point Testcontainers to it.

Also see https://www.atomicjar.com/2021/10/docker-on-windows-and-macos/

**Comment by eddumelendez** [comment]
There is [Rancher Desktop section](https://java.testcontainers.org/supported_docker_environment/#rancher-desktop) that has been added about how to set up Testcontainers.
