### ISSUE TITLE
Running from maven causes cannot access class jdk.internal.misc.Unsafe exception

### ISSUE THREAD

**Issue by ori-n** [testcontainers/testcontainers-java#480]
I'm using intellij - when I'm running a unit test using PostgreContainer from the IDE all is OK, but from maven as part of build I get the below error. Thanks

15:30:58.834 [main] DEBUG org.testcontainers.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class org.testcontainers.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @38b27cdc
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)

**Comment by bsideup** [comment]
Hi @ori-n!

I see that you're using Java 9. We haven't tried TestContainers with Java 9 yet because our dependencies are not upgraded yet (i.e. Netty, docker-java, and a few others)

Probably your IDE is configured to use Java 8, this is why it works from it

**Comment by ori-n** [comment]
thanks for the help
