### ISSUE TITLE
OracleContainer: Doesn't work after upgrading from 1.16.0 to 1.16.2

### ISSUE THREAD

**Issue by clario** [testcontainers/testcontainers-java#4808]
In the class org.testcontainers.containers.OracleContainer, this method seems to return wrong jdbcurl:
getJdbcUrl()

[DIFF](https://github.com/testcontainers/testcontainers-java/compare/1.16.0...1.16.2#diff-905e446c5771ff2
c88cbbadfc948f520073090b6d3234ef4f914364f74a0ec0fR101)

![diff](https://user-images.githubusercontent.com/264754/147756204-d229391f-3790-4191-896b-57f9a37c4eb8.png)

Username and password is removed from the jdbcurl, is this correct ? 

(I hardcoded username and password in my code, and that worked)

Kind regards 
Richard

**Comment by kiview** [comment]
You can get the username and password programmatically, using `getUsername()` and `getPassword()`. 

In addition, `getJdbcUrl()` in `OracleContainer` now behaves similar to `MySQLContainer` and `PostgreSQLContainer`, so this change aligned the implementations was and was intended.

Nevertheless, thanks for pointing this out and asking for clarification.
