### ISSUE TITLE
Cannot start a container on windows because of mount error

### ISSUE THREAD

**Issue by ori-n** [testcontainers/testcontainers-java#481]
All worked fine, and from some reason stopped working. 
I cannot start a container, and windows restart did not work. This is the error:
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"error while creating mount source path '/c/mydir/myproject/.testcontainers-tmp-XVoe9': chown /c/mydir/myproject/.testcontainers-tmp-XVoe9: no such file or directory"}

any help will be appreciated

**Comment by bsideup** [comment]
Hi @ori-n! What are you using, Docker for Windows or docker-machine (as part of Docker Toolbox)?

**Comment by ori-n** [comment]
win10 with docker for win

**Comment by kiview** [comment]
Did you share the directory with your Docker for Windows installation? There is a tab for shared drives in GUI.

**Comment by ori-n** [comment]
the share is probably the default - entire HD drive.
Again - it worked, and from some reason stopped working

**Comment by ori-n** [comment]
Funny, (or not, not sure). Restarted docker and it works again.
weird that last time I check windows restart did not help...

**Comment by kiview** [comment]
I think as a default, nothing is shared.
And I myself have problems with the Windows permissions when sharing these drives with Docker, so not sure about the maturity of this Docker feature on Windows.

Can we assume this is a Docker for Windows specific problem and has nothing to do with Testcontainers? I'd close the ticket in this case.

**Comment by ori-n** [comment]
I tried both docker on win 10 (not toolbox) and ubuntu and got the same result
________________________________

**Comment by kiview** [comment]
Can you please share your code? 
Are you sure wanted to answer to this issue, since you've stated on Nov 07 that it worked for you?

**Comment by ori-n** [comment]
Sorry my bad, posted to the wrong thread. Please close the issue.
Every time I run to this problem I restart docker for win and then it works as expected. Guess it is a docker issue
________________________________
