### ISSUE TITLE
Trying to use PostgreSQLContainer but no postgres container is being started

### ISSUE THREAD

**Issue by RobMaskell** [testcontainers/testcontainers-java#482]
Using the following code in a spring boot app test

`@Rule
 public PostgreSQLContainer postgres = new PostgreSQLContainer("postgres:alpine") 
     .withDatabaseName("postgres") 
     .withUsername("postgres") 
     .withPassword("password");
`

The tests work when I manually start a `postgres:alpine` container but when I run the code with the above rule I get exceptions like this

`org.postgresql.util.PSQLException: Connection to 192.168.1.75:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.`

The output I see from `docker events` is as follows and seems to suggest it's using a default `alpine:3.5` container and not the one I have specified?

`2017-11-05T20:25:49.602139889Z container create eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:49.961818675Z network connect 2f245451bd81f3faf19bd33bbfa4e13ec092dd637607e4aabab2c68fd21b4df2 (container=eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22, name=bridge, type=bridge)
2017-11-05T20:25:50.429203163Z container start eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:50.439917834Z container exec_create: df -P eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:50.454331797Z container exec_start: df -P eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:50.522639649Z container archive-path eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:50.701537187Z container kill eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori, signal=9)
2017-11-05T20:25:50.750975128Z container die eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (exitCode=137, image=alpine:3.5, name=confident_cori)
2017-11-05T20:25:51.153292105Z network disconnect 2f245451bd81f3faf19bd33bbfa4e13ec092dd637607e4aabab2c68fd21b4df2 (container=eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22, name=bridge, type=bridge)
2017-11-05T20:25:51.332111665Z container destroy eff497e66e117b1adcc7e5610704767cd4e32f29ce2e8d31026a4f6a1025cd22 (image=alpine:3.5, name=confident_cori)`

$ docker --version
`Docker version 17.05.0-ce, build 89658be`

uname -a
`Linux robslappy 4.4.94-040494-generic #201710211231 SMP Sat Oct 21 16:33:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Really like the idea of using testcontainers it's a great idea and exactly what I was looking for.

**Comment by bsideup** [comment]
Hi @RobMaskell,

> 192.168.1.75:5432

you should use `getJdbcUrl()` instead of trying to connect to `5432` port. TestContainers assigns random ports to ensure that parallel tests will not affect each other. 

Another option is to form the URL manually and use `getFirstMappedPort()` or `getExposedPort(0)`

**Comment by RobMaskell** [comment]
Hi @bsideup  Thanks for the response, I can try that but I'd feel better about refactoring if I saw a postgres container start up? Should that not appear in the `docker events`?

**Comment by bsideup** [comment]
@RobMaskell we perform some pre-flight checks before starting your containers, this is why you see `alpine:3.5` there. You can also disable them with `checks.disable=true` in `~/.testcontainers.properties` file :)

**Comment by RobMaskell** [comment]
I did check the logs and see some checks which must be these pre-flights but I think they all passed, my app started up and then failed, but still no `postgres:alpine` container in the events.

I'll make the changes you suggest and see what happens.

**Comment by kiview** [comment]
You can also monitor the running Docker containers directly, to get more information:
```
watch docker ps
```

**Comment by RobMaskell** [comment]
Thanks @kiview

Ok so changing to `@ClassRule` I get a `postgres:alpine` container but spring boot seems to have already created a datasource by the time the `Initializer` tries to use `postgres.getJdbcUrl()` to set the property

	@ClassRule
	public static PostgreSQLContainer postgres = new PostgreSQLContainer("postgres:alpine")
			.withDatabaseName("postgres")
			.withUsername("postgres")
			.withPassword("password");

	public static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
		@Override
		public void initialize(ConfigurableApplicationContext configurableApplicationContext) {

			EnvironmentTestUtils.addEnvironment("testcontainers", configurableApplicationContext.getEnvironment(),
					"spring.datasource.url=" + postgres.getJdbcUrl()
			);
		}
	}

Any idea how to get the container to fire up earlier before spring creates the datasource from the details in application.properties and tries to run schema.sql against a database that isn't there.

I'm using testcontainers because I trying to create multiple databases, one per tenant and it's Db specific so testcontainers is ideal. However if I use the `jdbc:tc:postgress...` method I end up with a container per tenant and that doesn't work either, although it does solve my ordering issue.

**Comment by bsideup** [comment]
@RobMaskell sure, take a look at:
https://github.com/bsideup/testcontainers-microservices-example/blob/5d28ca32d29d9fd7f3101044a02ec2660b0678fd/src/test/java/org/testcontainers/example/demo/support/AbstractIntegrationTest.java#L38

**Comment by kiview** [comment]
Here is another example of doing this:
https://github.com/testcontainers/testcontainers-java-examples/blob/master/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java

The trick is, to configure the datasource before the Spring application context is initialized, so you have to get the point in the Spring lifecycle right.

I'll close this issue, if you need further help, would you like to post a question on [Stackoverflow](https://stackoverflow.com/search?q=testcontainers) and maybe post the link in this issue, or in our Slack?

**Comment by RobMaskell** [comment]
I have it working now, thanks for the help
