### ISSUE TITLE
Misleading logs about starting reused container

### ISSUE THREAD

**Issue by pkubowicz** [testcontainers/testcontainers-java#4843]
If you correctly set up container reuse, test logs will claim a new container is started:
```
🐳 [mongo:4.4.10]                        : Creating container for image: mongo:4.4.10
🐳 [mongo:4.4.10]                        : Reusing container with ID: b86fee00345ba5f5a00afa774485bccf4e28477a310149d6ee1d6c8d1417606d and hash: 473d0fa21a22938b3ae0330a600050559c4a2be7
🐳 [mongo:4.4.10]                        : Container mongo:4.4.10 is starting: b86fee00345ba5f5a00afa774485bccf4e28477a310149d6ee1d6c8d1417606d
🐳 [mongo:4.4.10]                        : Container mongo:4.4.10 started in PT0.193984S
```

Nothing is actually started and everything is ok. But looking at logs, you may think you failed to configure reusing correctly. Or that there is a bug in Testcontainers and it starts a copy.

**Comment by kiview** [comment]
Thanks for reporting this @pkubowicz.
You are correct, the logs are misleading. From the container id, we see it is reusing the same container: `b86fee00345ba5f5a00afa774485bccf4e28477a310149d6ee1d6c8d1417606d`.

The Java code still thinks in terms of starting the container in this case, we need to check how straightforward it will be to conditionally change the logs, but you are right, it would make the DX considerably better.

**Comment by pkubowicz** [comment]
Looking at GenericContainer, I think that some logs are redundant. 'is starting' log message provides no additional details compared to 'Reusing container' log message. See my PR.

**Comment by kiview** [comment]
Thanks for the prompt PR, looks reasonable from my side 👍
