### ISSUE TITLE
Will testcontainers consider to eliminate the need to install docker on executor?

### ISSUE THREAD

**Issue by zyh0github** [testcontainers/testcontainers-java#4846]
Recently, we have been exploring using testcontainer. However, a problem is that testcontainers cannot be embedded in a project like H2 does.It seems that everyone needs to install and enable Docker on PC. Our projects are regularly deployed in various environments through pipelines. But the pipeline is maintained by another project team. During deployment, unit tests are run through the pipeline. If the testcontainer is not embedded, it is difficult to push another team to install Docker on each pipeline executor.
Will testcontainers consider to eliminate the need to install docker on executor? Like just importing testcontainers by maven then writing code correctly, we can run tests. Thank you very much.

**Comment by rnorth** [comment]
Hi @zyh0github 

The ability to run containers is fundamental to Testcontainers, and Docker is not a thing that we can just embed at the moment. I'm afraid you'll need Docker, or a compatible equivalent, available when running tests.

You might be interested in:
* we (core maintainers of Testcontainers / AtomicJar) are working on [Testcontainers Cloud](https://www.atomicjar.com/2021/11/announcing-testcontainers-cloud/) which will remove this dependency on local Docker.
* we also talked about some [compatible equivalents](https://www.atomicjar.com/2021/10/docker-on-windows-and-macos/) in a blog post (focused on MacOS, but with some points that you could extrapolate to CI)
* most cloud CI providers do include Docker already - although it sounds like you're relying on an in-house-maintained CI pipeline, so this may be less relevant. We have _some_ of the options (but not a complete list) documented [in our docs](https://www.testcontainers.org/supported_docker_environment/): <br /> <img width="296" alt="image" src="https://user-images.githubusercontent.com/132175/148209202-eded5364-415a-4a4d-a08c-b9cfb10e555e.png">

**Comment by zyh0github** [comment]
Thank you so much! We are looking forward to Testcontainers Cloud. Knowing that Docker can not be embedded at the moment, we will talk to another team to install the fundamental component we need for run tests.
Thanks!

**Comment by rnorth** [comment]
@zyh0github great, I'm glad to hear that!
