### ISSUE TITLE
Add module for Hashicorp Consul

### ISSUE THREAD

**Issue by krisiye** [testcontainers/testcontainers-java#4860]
Feature Request: Consul is often used in conjunction with HashiCorp Vault as a secret backend. It's quite common to run tests that will need testcontainers for Consul (official images provided on dockerhub by hashicorp) so that it could be integrated with other testcontainers such as Vault for the secret backend.
https://www.consul.io/

Some of the Features to include wil be:
- support for ACLs
- consul configuration as an object
- support for both new (>= 1.4.0) and legacy (< 1.4.0) ACL config
- TLS support
- cluster support

**Comment by kiview** [comment]
Hi @krisiye, are you raising this issue to ask if you should provide a PR with such a module?

**Comment by krisiye** [comment]
@kiview  - I'd be happy to contribute to a module. I have been using internal repos to provide containers for my purposes but i think it deserves to be a managed module that can exist alongside vault and iterate along. Let me know if that makes sense and i can work on a PR.

**Comment by kiview** [comment]
Can you share your current solution, so we can better assess if the implementation of a distinct module makes sense?

**Comment by krisiye** [comment]
@kiview  - Here is a module I pushed out to my fork for your review - https://github.com/testcontainers/testcontainers-java/compare/master...krisiye:issue_4860

**Comment by kiview** [comment]
Thanks a lot for sharing @krisiye. On a first look, your implementation seems fine. 

Since we are currently rethinking our approach to 3rd party modules, I'd suggest for now you publish the module yourself (e.g. like the Keycloak module: https://github.com/dasniko/testcontainers-keycloak) and we revisit this topic in the future (to ensure ongoing discoverability and compatibility).

**Comment by krisiye** [comment]
Thanks for the feedback @kiview! I will publish a module on my end. Regards!

**Comment by krisiye** [comment]
FYI - [testcontainers-consul](https://github.com/hmhco/testcontainers-consul) has been published.
`
<dependency>
  <groupId>com.hmhco</groupId>
  <artifactId>testcontainers-consul</artifactId>
  <version>0.0.4</version>
  <scope>test</scope>
</dependency>
`

**Comment by kiview** [comment]
Thanks a lot @krisiye! 🙇‍♂️ 

To everyone finding this issue, we strongly encourage you to try out and use https://github.com/hmhco/testcontainers-consul for the time being 🙂

**Comment by eddumelendez** [comment]
We already merged https://github.com/testcontainers/testcontainers-java/pull/4683 and it will be available in the next release and there is also `com.hmhco:testcontainers-consul`
