### ISSUE TITLE
Junit 5 support

### ISSUE THREAD

**Issue by Juan-EBI** [testcontainers/testcontainers-java#490]
Hello Guys

Is there pure JUnit5 support (without vintage engine) support on the roadmap? @Rule and @ClassRule are going away? (I found this question as well in one issue but was never answer)

**Comment by bsideup** [comment]
Hi @jcamilorada-EBI!

Yes, we have it on our roadmap and discuss (separately from this repo) how to achieve that, so-called TestContainers 2.0 :) This is definitely one of the biggest priorities right now for us!

Also worth mentioning that TestContainers 1.x works great with JUnit 5 when being integrated manually, here is an example from Vaadin's Sven Ruppert (in German, but the code is self-explaining):
https://jaxenter.de/vaadin-docker-junit-5-60792

Also reference: https://github.com/testcontainers/testcontainers-java/issues/87

**Comment by dnno** [comment]
Is it possible to follow the discussion of this topic somewhere?

**Comment by kiview** [comment]
Hey @dnno, you can finde the most recent and concrete discussion here:
https://github.com/rnorth/containercore/pull/1

**Comment by bsideup** [comment]
I'm closing this issue in favour of #87, but feel free to add your thoughts there :)
