### ISSUE TITLE
Support URL based init-script-path like starting with "file:/"

### ISSUE THREAD

**Issue by ryukato** [testcontainers/testcontainers-java#4916]
`ScriptUtils::runInitScript` supports only class-path resources but sometimes I guess we need to use the path in URL format like `file:`. 
So I suggest enhance the `ScriptUtils::runInitScript` like below to support URL base file path.
Please let me know there is any wired or things to be updated.

```
	public static void runInitScript(DatabaseDelegate databaseDelegate, String initScriptPath) {
		try {
			URL resource = null;
			if (initScriptPath.startsWith("file:")) {
				resource = new URL(initScriptPath);
			} else {
				resource = ScriptUtils.class.getClassLoader().getResource(initScriptPath);
			}
			if (resource == null) {
				LOGGER.warn("Could not load classpath init script: {}", initScriptPath);
				throw new ScriptLoadException("Could not load classpath init script: " + initScriptPath + ". Resource not found.");
			}
			String scripts = IOUtils.toString(resource, StandardCharsets.UTF_8);
			executeDatabaseScript(databaseDelegate, initScriptPath, scripts);
		} catch (IOException e) {
			LOGGER.warn("Could not load classpath init script: {}", initScriptPath);
			throw new ScriptLoadException("Could not load classpath init script: " + initScriptPath, e);
		} catch (ScriptException e) {
			LOGGER.error("Error while executing init script: {}", initScriptPath, e);
			throw new UncategorizedScriptException("Error while executing init script: " + initScriptPath, e);
		}
	}
```

**Comment by icougil** [comment]
Yes, I think this is something interesting to have: in our case we are having some issues, because we have files located in another modules and because of this we can't load those files :-/

**Comment by eddumelendez** [comment]
Hi,

Currently, it is recommended to use `Flyway` or `Liquibase` for database initialization. Also, most of the database images provide a directory to initialize the database. So, `withCopyToContainer` and `withCopyFileToContainer` can be used along with `Transferable.of`, `MountableFile.forClasspathResource` and `MountableFile.forHostPath`.

**Comment by icougil** [comment]
In our case we were using `Flyway` , but because we had the files located in other modules we could't load them...
