### ISSUE TITLE
withLocalCompose(false) not working for version 3 of local-compose.yml

### ISSUE THREAD

**Issue by rrrrrrrrramba** [testcontainers/testcontainers-java#492]
I am trying to figure out why `DockerComposeContainer` configured as `withLocalCompose(false)` is not working.

I have a very simple `docker-compose.yml`:
```
version: "3"
services:
  postgresql:
    image: "postgres:10"
    ports:
      - 5432
```

I start as following:

`new DockerComposeContainer(...).withLocalCompose(false).withPull(false).starting(null)`

I get the following generic error:

```
20:45:31.061 [main] ERROR 🐳 [docker/compose:1.8.0] - Could not start container
java.lang.IllegalStateException: Container did not start correctly.
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:231)
	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:184)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:182)
	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:432)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:152)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:128)
	at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:112)
```

When using `withLocalCompose(true)`, it works fine.

Docker version: `Docker version 17.09.0-ce, build afdb6d4`

Any idea what is wrong or what I can do to investigate this? The strange this is that a few days ago, something similar was working. I am 100% sure that I was testing with `withLocalCompose(false)`, as I remember intentionally deleting docker-compose on my host to verify that everything was running in a container, as expected. I remember being amazed (as this would avoid installing docker-compose on CI servers) ;). However, I cannot really see what is different now.

Thanks!

**Comment by rrrrrrrrramba** [comment]
Interesting update! It seems to be working fine when I set version to `2` instead of `3` in `docker-compose.yml`. Is this a known issue or as expected?

**Comment by bsideup** [comment]
@rrrrrrrrramba I assume `docker/compose:1.8.0` didn't support version `3`. And yes, we need to update the image we use because it's a bit outdated :D

**Comment by rrrrrrrrramba** [comment]
Oh, I did not realize the version is fixed in `TestcontainersConfiguration`. I thought that `latest` was always used. But using a fixed version is a good idea, so you will have consistent behavior.

Maybe it is also a good ideato allow to configure the desired `docker-compose` (and other containers, as mentioned in `TestcontainersConfiguration` to use, instead of 'hardcoding' it?

**Comment by rrrrrrrrramba** [comment]
I created `tescontainers.properties` with `compose.container.image=docker/compose:1.17.1` and now it works great! Thanks for the tip.

I am now seeing the following error though:

`22:06:36.368 [dockerjava-netty-1-4] ERROR o.t.s.i.n.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dorg.testcontainers.shaded.io.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.`

**Comment by rrrrrrrrramba** [comment]
FYI, there also is no `:latest` for `docker-compose` it seems: https://hub.docker.com/r/docker/compose/tags/

**Comment by rrrrrrrrramba** [comment]
Let's close this and open a new ticket for that resource leak detection.

Thanks for helping me!

**Comment by bsideup** [comment]
@rrrrrrrrramba this "leak detection" thing is something known and comes from docker-java I think, we're not using Netty directly in TestContainers

**Comment by rrrrrrrrramba** [comment]
Oops, did not realize that. I'll close the other one :).
