### ISSUE TITLE
Replace deprecated ClickHouse Driver

### ISSUE THREAD

**Issue by tangjiangling** [testcontainers/testcontainers-java#4924]
The driver `ru.yandex.clickhouse.ClickHouseDriver` has been marked as deprecated.
Also everything in package `ru.yandex.clickhouse` will be removed starting from 0.4.0.
We should replace ru.yandex.clickhouse.ClickHouseDriver with `com.clickhouse.jdbc.ClickHouseDriver`.
You can find a note at https://github.com/ClickHouse/clickhouse-jdbc.
> Note: ru.yandex.clickhouse.ClickHouseDriver and everything under ru.yandex.clickhouse will be removed starting from 0.4.0.

**Comment by eddumelendez** [comment]
Closing because of https://github.com/testcontainers/testcontainers-java/pull/4925#issuecomment-1179475650
