### ISSUE TITLE
Can't find BigtableEmulatorContainer class

### ISSUE THREAD

**Issue by khaiqnguyen93** [testcontainers/testcontainers-java#4933]
I'm currenty use the 1.16.2 version
After mvn reload it seems I can't download and use BigtableEmulatorContainer in my source code
Although I downgrade it to 1.15.x and reload project many times but still can't see the BigtableEmulatorContainer class
Do you know how to resolve this issue?
Thank you!
<img width="423" alt="Screen Shot 2022-01-18 at 16 46 12" src="https://user-images.githubusercontent.com/25881024/149912447-023b92c5-97b6-4d9b-bc08-22e88103bcb2.png">

**Comment by khaiqnguyen93** [comment]
Suddenly found out I add the default module instead of gcloud one
https://www.testcontainers.org/modules/gcloud/#adding-this-module-to-your-project-dependencies
Hope the guideline for insert module to pj should be at the top of this page

**Comment by kiview** [comment]
This is explained in the docs:
https://www.testcontainers.org/#maven-dependencies
