### ISSUE TITLE
Contribute ArangoDB Module to Testcontainers

### ISSUE THREAD

**Issue by GoodforGod** [testcontainers/testcontainers-java#4946]
Hello guys, I am maintaining for quite time [ArangoDB Testcontainers module](https://github.com/GoodforGod/arangodb-testcontainers) and it is quite stable and is fully working.

I think it is quite stable for a long time and would like to contribute it to official Testcontainers modules so that would give more adoption for ArangoDB and visibility for such Testcontainers implementation.
I would like to contribute core functionality (without cluster containers, cause I know thats not quite related to Testcontainers)

I would like to help with maintaining it further in Testcontainers, so move to official module is more about visibility and help for community.
Is this possible? Whats your thoughts?

**Comment by GoodforGod** [comment]
@bsideup whats your thoughts?

**Comment by eddumelendez** [comment]
Hi @GoodforGod, your module is listed in [Testcontainers Module Catalog](https://testcontainers.com/modules/arangodb/) :) So, visibility is covered. Thank you so much for doing the module!
