### ISSUE TITLE
How to see the logs / console output of the containers

### ISSUE THREAD

**Issue by jens-meiss** [testcontainers/testcontainers-java#495]
hi,

is there a way to see to log message / console output of the startet containers? 

We using gitlab to run our end to end test with testcontainers, but i just see the output of the container who's actually running the test, but not the output of the startet containers. If our test fail currently i have no chance to get the logs from the containers which have been startet by testcontainers. 

Setup:

* Gitlab starts a docker container in which the test is executed (via mvn verify)
* the test start a couple of docker containers containing our microservices
* the test calls REST endpoints on the microservices
* maybe one of the microservices got a error and responds with a 500 Internal Server Error
* i just see the 500 status in my test, but not the log from the container, in which the error occured

I already configured logback as mentioned in the docs, but as far as i understand i still just see the logs of the "parent" container which is executing the test.

**Comment by bsideup** [comment]
Hi ~cornhollio~ @jens-meiss,

sure, check for instance `withLogConsumer(new SLF4JConsumer(log))`

**Comment by jens-meiss** [comment]
hehe hi,

thx for the quick response, we'r using the DockerComposeContainer to start our services, the method you mentioned is only available for the GenericContainer. Is there a ways for DockerCompose as well?

**Comment by bsideup** [comment]
@jens-meiss got it! No, unfortunately, Docker Compose support doesn't provide a way to get the logs, but we know about it and it was mentioned before ( @rnorth @kiview maybe you remember where? )

**Comment by jens-meiss** [comment]
ah ok, thx for the info, if you mention the tickets here i'll subscribe on them to get the status updates

or maybe i'll provide some merge requests for them :-)

**Comment by kiview** [comment]
@jens-meiss Maybe you can look into the solution proposed in this ticket, never got any feedback on it:
https://github.com/testcontainers/testcontainers-java/issues/352

**Comment by jens-meiss** [comment]
hi,

yes that solves my issue, now we have all the logs! thx! :-)

**Comment by kiview** [comment]
Great news, thanks for the feedback!
