### ISSUE TITLE
JdbcDatabaseContainer#optionallyMapResourceParameterAsVolume should set explicit file permissions

### ISSUE THREAD

**Issue by oehme** [testcontainers/testcontainers-java#4952]
I have a restrictive umask on my system that only allows me to read the files I create. Recently I tried to start a mysql database with Testcontainers. Testcontainers [maps a classpath resource into the config directory](https://github.com/testcontainers/testcontainers-java/blob/f9538d16b7f636420cc269ce15fd6b5742be278c/modules/mysql/src/main/java/org/testcontainers/containers/MySQLContainer.java#L64) of the container. To do this, it first extracts the contents to a temporary location and then uses whatever permissions this temp file has. Due to my umask, the temp file is only readable by me, but not by the user inside the mysql container, resulting in `mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 - Permission denied)`

I'd suggest that the config files be created with permissions that allow it to be read by the container.

**Comment by famod** [comment]
@oehme I _think_ I was just hit by this. Can you suggest a workaround? Thanks!

**Comment by oehme** [comment]
Sorry, no satisfactory workaround - I changed the umask while working on the project that was using this library
