### ISSUE TITLE
host.testcontainers.internal does not seem to work on ARM64 architecture

### ISSUE THREAD

**Issue by jennyowen** [testcontainers/testcontainers-java#4956]
Using test containers 1.16.3 and Ubuntu 20.04 on both arm64 and amd64 architectures.

I have a test which serves a file at `localhost:3000/myfile`, then inside a testcontainers docker container accesses it with `curl http://host.testcontainers.internal:3000/myfile`.

This all works fine for running on amd64 architectures, but when I run the same test on an ARM64 machine `curl http://host.testcontainers.internal:3000/myfile` returns nothing.
I checked on the arm machine that `curl localhost:3000/myfile` actually returns something, and it does.The problem is accessing that from the container.
Is this a bug or is the `host.testcontainers.internal` feature not supported on arm?

**Comment by kiview** [comment]
I don't know of other users running on ARM64 with M1 Macbook that faced this problem. Can you please share a reproducer? And did you run it on M1, or another ARM64 platform?

**Comment by jennyowen** [comment]
I've been able to reproduce the problem on `a1.large` and `t4g.2xlarge` aws instances, both running Ubuntu 20.04 (`ami-09e0d6fdf60750e33` on eu-west-1). 

The `ExposeHostTest` tests did indeed fail when I tried running them on an arm machine, and looking at what that test's trying to do, I think it should be reproducing the problem.

My reproduction code is a bit involved in how it's actually using host.testcontainers.local so I'd rather not provide a reduced version if I don't have to.

**Comment by rnorth** [comment]
This is an interesting one - maybe going to be a puzzle for us to debug 😄 

I've just tried running `ExposeHostTest` on my M1 Mac with Docker Desktop (`Server Version: 20.10.11`) and it passed.

I've also tried it against a (TCC) remote VM (which is 64-bit Ubuntu) and it worked too.

So I think that this isn't specific to ARM, but some other combination of factors.

**Comment by eddumelendez** [comment]
@jennyowen can you give a new try using testcontainers 1.17.5, please? See https://github.com/testcontainers/testcontainers-java/issues/5482

**Comment by jennyowen** [comment]
@eddumelendez updating to 1.17.5 fixes it for me. Thank you!
