### ISSUE TITLE
Enable easier configuration of recording file name formatting

### ISSUE THREAD

**Issue by ldeck** [testcontainers/testcontainers-java#500]
When using scalatest I'd like to be able to use the test `Description.getDisplayName` (perhaps with a date and/or failed/passed string) to make it easier to find the relevant file for a test.

Currently, BrowserWebDriverContainer#stopAndRetainRecording is private and we can only access currentVncRecordings via reflection if we override BrowserWebDriverContainer#failed, for example.

I'd like to suggest the following refactor:
```
private void stopAndRetainRecording(Description description) {
    File recordingFile = new File(vncRecordingDirectory, "recording-" + filenameDateFormat.format(new Date()) + ".flv");
    ....
}
```
becomes:
```
protected File toRecordingFile(File vncRecordingDirectory, Description description, boolean successful) {
    return new File(vncRecordingDirectory, "recording-" + filenameDateFormat.format(new Date()) + ".flv");
}
private void stopAndRetainRecording(Description description, boolean successful) {
    File recordingFile = toRecordingFile(vncRecordingDirectory, description, successful);
    ....
}
```

Naturally, failed and succeeded would pass along the relevant flag.

I'm happy to create a pull-request with these changes with any suggested alterations to the above.

**Comment by ldeck** [comment]
Alternative refactor:
```java
public BrowserWebDriverContainer() {
    ....
    withRecordingFileFormatter((description, succeeded) -> new File(vncRecordingDirectory, "recording-" ...);
}
public SELF withRecordingFileFormatter(BiFunction<Description, Boolean, File> recordingFileFormatter) {
        this.recordingFileFormatter = recordingFileFormatter;
        return self();
}
private void stopAndRetainRecording(Description description, boolean successful) {
    File recordingFile = recordingFileFormatter.apply(description, successful);
    ....
}
```

**Comment by rnorth** [comment]
@ldeck good idea - I'd certainly be in favour of the filenames being easier to identify (by default!)

I think your second suggested alternative looks good as an approach for customisation, but if you have time to create a PR would you mind also changing the default filename formatter? Something like this might be useful: `FAILED-ClassNameOfTest-methodNameOfTest-20171126-115603.flv`. WDYT?

**Comment by ldeck** [comment]
@rnorth sounds good.

**Comment by ldeck** [comment]
@rnorth are you happy to accept the merge or would you like anything changed?
