### ISSUE TITLE
Couchbase Docker Service will not startup on M1 MacBook

### ISSUE THREAD

**Issue by joseph-ausmann** [testcontainers/testcontainers-java#5018]
Waiting for the service always times out on M1 MacBook. 

https://github.com/testcontainers/testcontainers-java/blob/master/modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java#L343

Docker Desktop is installed and running.

**Comment by bsideup** [comment]
Hi @joseph-ausmann,

Can you start it without Testcontainers, with `docker run`-like command?

**Comment by joseph-ausmann** [comment]
ah, you are right.

https://issues.couchbase.com/browse/MB-41281

**Comment by daschl** [comment]
@joseph-ausmann ARM support is in the works and coming - watch the next versions :)
