### ISSUE TITLE
Question: move testcontainers.properties to some child folder

### ISSUE THREAD

**Issue by DJ-Glock** [testcontainers/testcontainers-java#5031]
Hi all
I've checked documentation, but was not able to find out if it's possible to move testcontainers.properties located in resources to some child folder. I tried to move it and now it's not able to find it. It tries using file from my home folder.
Can you please advise if it's possible and how can it be changed?

**Comment by kiview** [comment]
Hi @DJ-Glock, can you elaborate on your use case and what you are trying to achieve?

**Comment by DJ-Glock** [comment]
@kiview I just want to put this config into child folder. I have two sets of tests - one set uses TC, the second one - not. I want to keep thir related config files in two separate folders instead of root dir.

**Comment by kiview** [comment]
Testcontainers considers all `testcontainers.properties` files that are on the classpath, so your use case should work. Can you please share your directory structure, as well as the content of `testcontainers.properties`, that you expect to be loaded?

The best way would be to share a small reproducer:
https://github.com/testcontainers/testcontainers-java-repro

**Comment by DJ-Glock** [comment]
@kiview here you are a minimum repo. I cannot upload it to github from my corporate PC, but it's very simple, so described below.


**Steps to reproduce:**
1. Put testcontainers.properties file into integration folder.
testcontainers.properties:
```
ryuk.container.image=testcontainers/ryuk:latest
```
![image](https://user-images.githubusercontent.com/26511191/152976115-3c0b7172-cc2e-428e-b01e-f88284d93b35.png)
2. Run `mvn clean install`
3. Move testcontainers.properties into root resources folder
4. Run `mvn clean install`

You will note Difference in log:
When properties file is located in integration folder (bad example):
```
Running org.testcontainers.repro.ReproExampleTest
14:12:51.516 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/Users/kuraden/.testcontainers.properties
14:12:51.553 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: EnvironmentAndSystemPropertyClientProviderStrategy
```

When properties file is located in root folder (good example):
```
Running org.testcontainers.repro.ReproExampleTest
14:11:48.725 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/Users/kuraden/.testcontainers.properties
14:11:48.743 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/Users/kuraden/Downloads/testcontainers-java-repro-master/target/test-classes/testcontainers.properties
14:11:48.773 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: EnvironmentAndSystemPropertyClientProviderStrategy
```

You can see that in good example file was overridden by: file:/C:/Users/kuraden/Downloads/testcontainers-java-repro-master/target/test-classes/testcontainers.properties In bad one - no.

**Comment by kiview** [comment]
Hey @DJ-Glock,
after checking your example and our implementation, I'd say it works as intended. Testcontainers only reads `testcontainers.properties` that reside in the classpath root. 

I hope this does not block you and you can simply configure Testcontainers like that.

**Comment by DJ-Glock** [comment]
@kiview Sad that I cannot move it to child folder :(
Anyway I can live with that and thanks for your time!
