### ISSUE TITLE
Lack of flexibility configuring TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX for PrefixingImageNameSubstitutor

### ISSUE THREAD

**Issue by polarfish** [testcontainers/testcontainers-java#5046]
Testcontainers version: `1.16.0`

I cannot use `PrefixingImageNameSubstitutor` for my needs because it does not differentiate between `image:version` and `repository/image:version`.

### Scenario 1

1. Set environment variable `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX=docker-proxy.mycompany.com/dockerhub/`
2. Run integration tests

#### Actual result

`mysql` image is not resolved

```
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: 
Failed to initialize pool: Status 500: {"message":"unknown: repository dockerhub/mysql not found"}
```

### Scenario 2

1. Set environment variable `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX=docker-proxy.mycompany.com/dockerhub/library/`
2. Run integration tests

#### Actual result

now `mysql` image is resolved but `testcontainers/ryuk` is not

```
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: 
Failed to initialize pool: Status 500: {"message":"unknown: repository dockerhub/library/testcontainers/ryuk not found"}
```

### Expected behaviour

The configuration `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX=docker-proxy.mycompany.com/dockerhub/` should lead to next image resolutions:
```
mysql -> docker-proxy.mycompany.com/dockerhub/library/mysql
testcontainers/ryuk -> docker-proxy.mycompany.com/dockerhub/testcontainers/ryuk
```

### Workaround
To workaround this issue we are creating our own `ImageNameSubstitutor`
```
public final class MyCompanyPrefixingImageNameSubstitutor extends ImageNameSubstitutor {

    private static final String DOCKER_PROXY_URL_LIBRARY = "docker-proxy.mycompany.com/dockerhub/library/";
    private static final String DOCKER_PROXY_URL_PROJECT = "docker-proxy.mycompany.com/dockerhub/";

    @Override
    public DockerImageName apply(DockerImageName original) {
        
        // ...

        String prefix = original.getRepository().contains("/")
            ? DOCKER_PROXY_URL_PROJECT
            : DOCKER_PROXY_URL_LIBRARY;

       // ...
    }

    // ...
}
```

**Comment by kiview** [comment]
Hi @polarfish, thanks for the detailed report. 

I can confirm that `PrefixingImageNameSubstitutor` behaves as you describe it and this might lead to unintuitive behavior for [Docker Official Images](https://docs.docker.com/docker-hub/official_images/).

This is easily reproducible with a failing test in our `PrefixingImageNameSubstitutorTest`:
```java
  @Test
  public void testOfficialImage() {
      when(mockConfiguration.getEnvVarOrProperty(eq(PREFIX_PROPERTY_KEY), any())).thenReturn("someregistry.com/our-mirror/");

      final DockerImageName result = underTest.apply(DockerImageName.parse("image:tag"));

      assertEquals(
          "The prefix is applied",
          "someregistry.com/our-mirror/library/image:tag",
          result.asCanonicalNameString()
      );
  }
```

I have to check with the other maintainers if this works as intended, or if it is a general bug with regards to Docker's opinionated treatment of official images.

Does the Docker CLI with configure registry-mirror behave as expected?

**Comment by rnorth** [comment]
Hi @polarfish 
The name prefix mechanism is intentionally simplistic, with room for expansion, on the basis that we can't predict how every organisation chooses to set up a mirrored repository. 

This is mentioned in the [docs](https://www.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names):
> Consider this if:
> ... Your private registry has copies of images from Docker Hub where the names are predictable, and just adding a prefix is enough. 

With your workaround you've actually hit the [by-design way of doing things](https://www.testcontainers.org/features/image_name_substitution/#developing-a-custom-function-for-transforming-image-names-on-the-fly):
> Consider this if:
> You have complex rules about which private registry images should be used as substitutes, e.g.:
> * non-deterministic mapping of names meaning that a name prefix cannot be used

I think we could say that it would be nice to have more out of the box variants on the simple name prefix mechanism, but I fear there would be too many and too much scope for confusion. For this reason we recommend implementing a `ImageNameSubstitutor` as you have done, perhaps shared in a common JAR if you have many repos you need to apply this to.
