### ISSUE TITLE
Testcontainer does not detect custom docker sock location

### ISSUE THREAD

**Issue by vishnuramvs29** [testcontainers/testcontainers-java#5047]
I have docker environment configured using Lima.

 `limactl start docker.yaml`

Followed by `docker run hello-world` 
 
works good and sample docker container is working good.

To make Testcontainer to point to new docker location, I added the following config to testcontainer.properties

```
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
docker.host=unix:///Users/user/.lima/docker/sock/docker.sock
```

I also added the above config to /Users/user/.testcontainer.properties as well.

Once I start the container, I get the below logs

```
09:46:56.354 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:[/Users/venkavis/Desktop/new_github/nimble-notification-service/target/test-classes/testcontainers.properties]()
09:46:56.357 [main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from [~/.testcontainers.properties](), will try it first
09:46:56.656 [ducttape-0] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Pinging docker daemon...
09:46:56.678 [ducttape-0] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd:
```

The log says it successfully loaded configuration from testcontainer.properties file but actually its running  **org.testcontainers.dockerclient.DockerClientProviderStrategy** instead of **org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy**. 

Can someone help me what config I am missing here? Or the logs are shown wrongly?

**Comment by bsideup** [comment]
From the logs:
> Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first


`DockerClientProviderStrategy` is the log category. Also, what you experience with `limactl start` is Docker Context - this is Docker CLI's feature that Testcontainers knowns nothing about because it does not use Docker CLI.

See more info here:
https://github.com/testcontainers/testcontainers-java/pull/5039#issuecomment-1039041020
