### ISSUE TITLE
Extract Container runners from JUnit specific code

### ISSUE THREAD

**Issue by raphw** [testcontainers/testcontainers-java#506]
I want to suggest allowing Testcontainers as an API for starting and stopping Docker images from a Java application without depending on JUnit and to therefore remove the `TestRule` API from the container description that is JUnit (4)-specific.

I have started using Testcontainers.org for a standalone testklient and this works really nicely. With implementing my suggestion would allow for my use case but also offer a better integration for JUnit 5 that uses its own API or for using TestNG.

This would only require a minimum change in usage, one would for example write: `new ContainerRule(new SomeContainer())` rather then `new SomeContainer()`. Other than that, the code is already segregated nicely.

Is this something you would consider to implement? I would be happy to offer the refactoring in this case.

**Comment by bsideup** [comment]
Hi @raphw,

Funny that you mentioned :) 

There is an ongoing effort on it, see the proposal here:
https://github.com/rnorth/containercore/pull/1

**Comment by raphw** [comment]
Awesome! Really looking forward to seeing that published. In our case, we can spin up a full environment of a microservice applications on any machine that has Docker installed. This works really nicely. Great effort.

**Comment by bsideup** [comment]
@raphw it's still on PR stage to receive some feedback, please, leave yours if you have something to add to it, that would be incredibly helpful! 

Also, since you have really nice experience with fluent APIs (ByteBuddy FTW! :) ), maybe you can help us to design the next API for TestContainers 2.0. We have some ideas, but your input would be valuable ;)
