### ISSUE TITLE
Add documentation of networking features

### ISSUE THREAD

**Issue by arcuri82** [testcontainers/testcontainers-java#509]
Hi,
 I am starting a Docker image `x` with `GenericContainer`, and then a browser with `BrowserWebDriverContainer` which will connect to the other image. As such, I need to know the IP address of `x`. To do it, one can use:

`x.getContainerInfo().getNetworkSettings().getIpAddress()`

It works, but it is marked as deprecated. That makes sense, as an image might have different networks and IP addresses. But, in typical testing scenarios, one would expect just one. So, to avoid the deprecated method, I need to write something like:

`x.getContainerInfo().getNetworkSettings().getNetworks().values().iterator().next().getIpAddress()`

which works, but only under the assumption that there is only one network. Furthermore, it is far too verbose. It would be great to have an API to call the above with a single method, eg

`x.getInternalIpAddress()`

which could throw an IllegalStateException if more than one network exists.

**Comment by kiview** [comment]
Hey @arcuri82, for this use case, it's best to use networks.
See the unit tests for how to use them:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/test/java/org/testcontainers/containers/NetworkTest.java
You can also use network aliases and access the other container by name.

@bsideup I think we are currently lacking documentation of the networking feature?

**Comment by arcuri82** [comment]
yes, that is a much, much better approach! thx ;)

**Comment by kiview** [comment]
@arcuri82 Glad that it helped :)
@bsideup Shall we change this issue title to reflect the missing network docs?

**Comment by bsideup** [comment]
@kiview sure! That's on my own list actually, to document them (previous item was #485 btw ;) )
