### ISSUE TITLE
Add withDevice(String deviceName) to GenericContainer

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#5095]
Running a qemu Docker image requires passing `--device /dev/kvm` to the Docker client.

Currently this isn't possible with Testcontainers.

**Comment by bsideup** [comment]
Hi @axelfontaine!

This is a bit too specific and not a common use case to warrant an API for it, but for that we support customization of `CreateContainerCmd`, see https://www.testcontainers.org/features/advanced_options/#customizing-the-container

And even if some fields aren't supported you can set them as raw values:
https://github.com/testcontainers/testcontainers-java/blob/5e016c9432c71f263493d144214f5fb047268d84/modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java#L29-L33
