### ISSUE TITLE
Selenium docs suggest deprecated `getTestHostIpAddress()` instead of host exposing mechanism

### ISSUE THREAD

**Issue by GregJohnStewart** [testcontainers/testcontainers-java#5098]
Trying to get my Selenium WebDriver testcontainer up, I get the following error when I try to get the host's port using `getTestHostIpAddress()`:

`Caused by: java.lang.UnsupportedOperationException: getTestHostIpAddress() is only implemented for docker-machine right now`

I am running this on Ubuntu 20.04

Any ideas?

**Comment by bsideup** [comment]
Have a look at https://www.testcontainers.org/features/networking/#exposing-host-ports-to-the-container 

Here is an example:
https://github.com/testcontainers/testcontainers-java/blob/master/examples/selenium-container/src/test/java/SeleniumContainerTest.java

**Comment by GregJohnStewart** [comment]
Thanks, looks like it works. Maybe the documentation should reflect this?

**Comment by bsideup** [comment]
uh? 😅 Wasn't that a link to the documentation?

**Comment by GregJohnStewart** [comment]
lol I meant to the Webdriver docs, they just have you use `getTestHostIpAddress()`

**Comment by bsideup** [comment]
Ah, great point, thank you! Would you like to contribute a fix? :)

Here is the file:
https://github.com/testcontainers/testcontainers-java/blob/master/docs/modules/webdriver_containers.md

**Comment by GregJohnStewart** [comment]
While I'm at it, did we want to add an additional bit on recording? Like the fact recording doesn't seem to happen outside of the following context:

```java
@Container/@Rule
public BrowserWebDriverContainer ...
```

**Comment by kiview** [comment]
You are right, currently automatic recording based on failed tests only works in conjunction with the JUnit4 or JUnit5 module. However, you can manually trigger the saving of the recording by calling `afterTest(TestDescription description, Optional<Throwable> throwable)` on the container object. 

I think clarifying this in the docs would be great 👍

**Comment by GregJohnStewart** [comment]
Thanks! I'll look at getting that in too. Happen to know how to get those parameters in the context of an `@AfterEach` for example?

**Comment by REslim30** [comment]
It sees like the latest docs do not suggest usage of `getTestHostIpAddress()` and instead suggest usage of the host exposing mechanism: https://www.testcontainers.org/modules/webdriver_containers/
![Screenshot from 2022-08-25 21-39-10](https://user-images.githubusercontent.com/43259657/186660479-de461e65-986e-43e7-a8b7-371088641f19.png)
I think this issue can be closed.

**Comment by kiview** [comment]
@REslim30 You are right, thanks for letting us know.
