### ISSUE TITLE
.flv videos generated by testcontainers webdriver aren't scrollable

### ISSUE THREAD

**Issue by iirekm** [testcontainers/testcontainers-java#512]
for now I fix them with: `ffmpeg -i video.flv -c:v copy -c:a copy fixed.flv`

**Comment by rnorth** [comment]
Ah ok - this is useful. Perhaps we can create a new VNC recording container that uses this. Thanks very much for suggesting it.

**Comment by kiview** [comment]
This still seems valid.

**Comment by leonard84** [comment]
Yeah I also stumbled over this I'd suggest `ffmpeg -i video.flv -movflags faststart video.mp4` which transcodes it to x264 resulting in a size reduction of 75%-90%, the `-movflags faststart` will make it streamable. Either add ffmpeg to the vnc recording container or use https://hub.docker.com/r/jrottenberg/ffmpeg/ `4.1-scratch`

**Comment by artjomka** [comment]
Is this issue up for taking ? Could try to dig in into it

**Comment by leonard84** [comment]
@artjomka well https://github.com/testcontainers/vnc-recorder/issues/3 is marked with help wanted and if you fixed that, then this should be fixed as well.

**Comment by rnorth** [comment]
Reopening this, because the released version for https://github.com/testcontainers/vnc-recorder/pull/4 still needs to be trickled through to the default tag used by Testcontainers.

The released tag of the image will be: `testcontainers/vnc-recorder:1.2.0`
Build is underway and should be completed shortly.

**Comment by rnorth** [comment]
Published: https://hub.docker.com/layers/testcontainers/vnc-recorder/1.2.0/images/sha256-1e14fc21b1dd7c28978f82f90008e4a603cc62744631cd299d3f846a08821ea9?context=repo

**Comment by AB-xdev** [comment]
Any progress here?
The pr for this issue also fixes #3405
