### ISSUE TITLE
DockerImageName.assertCompatibleWith is limiting

### ISSUE THREAD

**Issue by l0co** [testcontainers/testcontainers-java#5123]
For example in KafkaContainer [here](https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L43) is a forced check of image name compatibility. This prevents from using custom images, like for example:

Dockerfile

```
FROM confluentinc/cp-kafka:4.1.0-1

... some additional image customization goes here
```

Currently one can't use such an image with testcontainers and will be rejected by `assertCompatibleWith()` check. I'd consider an option to disable this check, i.e. it might be enabled by default but "if you know what you are doing" you should be able to skip it.

**Comment by bsideup** [comment]
Have you tried following what the error says?

**Comment by l0co** [comment]
Not, because it sticked out of my screen, but see your point, thanks :)

**Comment by kiview** [comment]
Since I assume the error message is helpful enough for you to solve the issue, I will close it. Please let us know if there are still any problems.
