### ISSUE TITLE
Errors on Kubernetes 1.23 (with containerd as container runtime)

### ISSUE THREAD

**Issue by fdelbrayelle** [testcontainers/testcontainers-java#5154]
Hi there!

[Since Kubernetes 1.20](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/), Docker support is deprecated and will be totally removed from 1.24. We use GKE to manage Kubernetes so the upgrade will be done automatically.

As far as I've read, developers should not have been impacted but we made tests in Kubernetes 1.23 to check that all is OK and it seems we have some issues with a microservice using Testcontainers :

```
09:59:44.578 [testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:49153
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.testcontainers.utility.ResourceReaper.lambda$null$3(ResourceReaper.java:194)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$4(ResourceReaper.java:190)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

This is not reproductible on a Kubernetes 1.19 where Docker is not deprecated nor removed.

We tried to disable Ryuk in `pom.xml` (as indicated for this error this [issue](https://github.com/testcontainers/testcontainers-java/issues/3609)) but it has no effect :

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>verify</goal>
                <goal>integration-test</goal>
            </goals>
            <configuration>
                <environmentVariables>
                    <TESTCONTAINERS_RYUK_DISABLED>true</TESTCONTAINERS_RYUK_DISABLED>
                </environmentVariables>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Is anyone have an idea please?

Thank you by advance!

**Comment by fdelbrayelle** [comment]
We tried to launch IT with testcontainers in a local Minikube with Kubernetes 1.23 and Containerd as container runtime:

```
minikube start --kubernetes-version v1.23.0 
--network-plugin=cni 
--enable-default-cni 
--container-runtime=containerd 
--bootstrapper=kubeadm
```

But it leads to this error when launching `mvn -T 2 failsafe:integration-test failsafe:verify` :

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.87 s <<< FAILURE! - in com.ggl.merch.kafka.it.MerchandisingConsumerIT                   
[ERROR] should_consume_merchandising_message_and_process_record  Time elapsed: 0.012 s  <<< ERROR!                                                                                                                 
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration                   
        at com.ggl.merch.kafka.it.MerchandisingConsumerIT.<init>(MerchandisingConsumerIT.java:91)   
```

Anyone already had the same problem? Thank you!

**Comment by nadworny** [comment]
Exactly the same problem here. I'm using Rancher Desktop 1.1.1 on MacOS.

**Comment by atooni** [comment]
We are running into the same problem with Amazon EKS

**Comment by fdelbrayelle** [comment]
@nadworny @atooni Do you have similar errors in your logs?

**Comment by nadworny** [comment]
> @nadworny @atooni Do you have similar errors in your logs?

Yes

**Comment by atooni** [comment]
I had the message `container startup failed`. We have now decided to use the socket based communication as we are using separate clusters for dev / staging and prod. That works quite well.

**Comment by fdelbrayelle** [comment]
@atooni What do you mean by use the socked based communication? At which level?

**Comment by kiview** [comment]
It might be the case that we see very different issues here, so we should be careful to not mix things up.

Testcontainers interacts with Docker using the Docker Engine RESTful API. If another container engine is used, an appropriate API needs to be configured and made accessible for Testcontainers, if it is running in a location that differs from the default Docker location.

Here is the part from our docs, that explains how to manually configure Testcontainers to interact with a Docker Engine-like RESTful API that does not get automatically detected:
https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection

So to everyone observing problems with their setups, how is your API accessible from the process that is running the tests?

**Comment by fdelbrayelle** [comment]
Solved by putting this in our configuration:

```
- name: "TESTCONTAINERS_HOST_OVERRIDE"
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

Following [this doc](https://www.testcontainers.org/features/configuration/): 

```
    TESTCONTAINERS_HOST_OVERRIDE
    Docker's host on which ports are exposed.
    Example: docker.svc.local
```

**Comment by vinniehg** [comment]
Sorry for the question @fdelbrayelle , which configuration are you referring to ? I'm running with a similar issue in EKS and I would like to know if I could do the same thing you did. Thanks in advance.

**Comment by kiview** [comment]
@vinniehg This is about setting the environment variable `TESTCONTAINERS_HOST_OVERRIDE`. See the docs: https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection
