### ISSUE TITLE
Parallel Gradle tests have trouble finding valid Docker environment

### ISSUE THREAD

**Issue by dreis2211** [testcontainers/testcontainers-java#5174]
Hi,

I know about the [limitations](https://www.testcontainers.org/test_framework_integration/junit_5/#limitations) that JUnit 5 is not tested with a parallel setup and corresponding ticket https://github.com/testcontainers/testcontainers-java/issues/1495.

I'm opening this because it's a slightly different issue (but probably the same effects). We're not using parallel JUnit 5 tests or the testcontainers JUnit 5 extension at all, but specify `./gradlew test --parallel` to parallelize the different Gradle tasks in a multi-module setup.

We're often getting the following messages in random modules, while the others work fine (so it's not a general problem where all modules fail). There is even the chance that everything works fine, but the flakyness has increased lately
```
    15:15:41.847 [Test worker] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception TimeoutException (org.rnorth.ducttape.TimeoutException: java.util.concurrent.TimeoutException). Root cause TimeoutException (null)
    15:15:41.848 [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is set but '/run/user/997/docker.sock' does not exist.
    15:15:41.850 [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/var/lib/jenkins/.docker/run' does not exist.
    15:15:41.895 [Test worker] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/997/docker.sock' does not exist.
    15:15:41.961 [Test worker] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/usr/local/bin, /usr/bin, /bin, /usr/games])
    15:15:41.994 [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
    15:15:41.995 [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception TimeoutException (org.rnorth.ducttape.TimeoutException: java.util.concurrent.TimeoutException). Root cause TimeoutException (null)
    15:15:41.996 [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
```

Our testcontainers part looks roughly like this in a base integration test class that the tests across modules all extend from:
```
	private static final DockerImageName imageName = DockerImageName.parse("our-artifactory/postgres:latest")
			.asCompatibleSubstituteFor("postgres");

	private static final PostgreSQLContainer<?> postgresContainer = new PostgreSQLContainer<>(imageName)
		.withDatabaseName("db")
		.withUsername("user")
		.withPassword("pass")
		.withStartupAttempts(5)
		.withStartupTimeout(Duration.ofMinutes(2))
		.withLogConsumer(new Slf4jLogConsumer(log));

	static {
		// Only use init script if resource exists
		String initScript = "docker/db/init.sql";
		URL resource = ScriptUtils.class.getClassLoader().getResource(initScript);
		if (resource == null) {
			initScript = null;
		}

		postgresContainer.withInitScript(initScript).start();
	}
```

Unfortunately, I can't share more or an example project. But any help is highly appreciated.

Cheers,
Christoph

**Comment by dreis2211** [comment]
I've raised `client.ping.timeout` to 30 again - let's see if this solves things.

**Comment by dreis2211** [comment]
Raising `client.ping.timeout` to 30 again solved the issue for me. Maybe the default of 30 can be brought back or this ticket can be turned into a documentation ticket.

**Comment by kiview** [comment]
Thanks for raising this issue and documenting your findings and a workaround @dreis2211.

This is basically an issue with the Docker daemon (or the machine executing the tests) getting overloaded from the amount of concurrent Testcontainers usage (and thereby Docker usage). The default timeout should be totally fine for regular usage, but it might be worth thinking about how we can document these circumstances under high load. 

May I ask how long your build takes with `--parallel` vs completely sequential? 

With regards to the actual issue, I am closing it, but we can continue the conversation here 🙂 .

**Comment by dreis2211** [comment]
That particular build step takes ~12 minutes sequentially vs. roughly 6 minutes when we run it with `--parallel`, @kiview .

**Comment by kiview** [comment]
@dreis2211 Thanks for letting us know and generally great to hear that using `--parallel` improves your cycle time. In this case, it might indeed make sense to document the usage of this config property for those scenarios a bit more explicitly.
