### ISSUE TITLE
Unable to run test containers as DinD in EKS

### ISSUE THREAD

**Issue by sriram0721** [testcontainers/testcontainers-java#5181]
We are trying to run testcontainers in our cicd where we setup dynamic slaves ( EKS ) for executing the builds. In that, we get 
{ 404 network bridge not found } anything we need to configure extra from networking standpoint

**Comment by kiview** [comment]
Can you share the full log? And do you have a Docker daemon available?

**Comment by sriram0721** [comment]
Yes, we have docker deamon available. 

com.github.dockerjava.api.exception.NotFoundException: 
Status 404: {"message":"network bridge not found"}

**Comment by kiview** [comment]
I found this former issue and it might help with your setup as well:
https://github.com/testcontainers/testcontainers-java/issues/2921#issuecomment-668852103

Can you try this stated solution:
> To enable the docker bridge on EKS, add the `--enable-docker-bridge true` flag to the EC2 userdata script that bootstraps the EKS nodes.

**Comment by eddumelendez** [comment]
@sriram0721 any update regarding to the last comment?

**Comment by eddumelendez** [comment]
Closing due to the last message was not acknowledged.
