### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by AnkBurov** [testcontainers/testcontainers-java#523]
Hello. I'd like to bring testcontainers Cassandra support. Currently Cassandra can be used only through Generic container and there are problems with keyspace initialization - after container's launch any initial scripts can be applied only manually. It's not very convenient. 😫
So I'm inclined to write separate Cassandra container with initial script applying support. Should I do it in this repository as PR, or in separate one?

**Comment by kiview** [comment]
Hi @AnkBurov, we originally wanted to split such extensions into its own repos, but it does add some more organisational overhead and basically feels kind of clunky. For now it would be great if you simply add the support as a PR in this main repo 🙂

**Comment by AnkBurov** [comment]
Okay, thanks.
