### ISSUE TITLE
Couchbase container missing eventing service

### ISSUE THREAD

**Issue by matteosist** [testcontainers/testcontainers-java#5251]
Hi, with the latest versione 1.16.3 is not possible enable eventing service on CouchbaseContainer.

I see you already added eventing service in CouchbaseService class few month ago but never release it.

Can you please release a new version with the last changes?

Thanks,
Matteo

**Comment by kiview** [comment]
https://github.com/testcontainers/testcontainers-java/pull/4953 is merged and will be part of the next release. 
In the meantime, you can always consume unreleased versions using Jitpack:
https://www.testcontainers.org/jitpack_dependencies/
