### ISSUE TITLE
`docker run` alternative

### ISSUE THREAD

**Issue by remal** [testcontainers/testcontainers-java#5259]
I'd like to execute a command like this: `docker run schemaspy/schemaspy <options>`. Is it possible to do it via Testcontainers?

If I understand correctly, Testcontainers requires me to start the container first and then execute a command inside a running container. However, I don't want to start the container - I'd like to execute a command in the container **synchronously** and get a result.

I suppose I have to "disable" `ENTRYPOINT` and then call `execInContainer()`. If it is so, could you please explain how to "disable" `ENTRYPOINT`? Replacing `ENTRYPOINT` with some dummy command, like `touch` is not an option, as a container can be "distroless".

**Comment by bsideup** [comment]
Hi @remal,

Have a look at `OneShotStartupCheckStrategy`:
https://www.testcontainers.org/features/startup_and_waits/#one-shot-startup-strategy-example
