### ISSUE TITLE
Upgrade from Testcontainers 1.16.3 to 1.17.1 failed with NoClassDefFoundError

### ISSUE THREAD

**Issue by khmarbaise** [testcontainers/testcontainers-java#5267]
Unfortunately are facing the following issue:
```
09:29:45  java.lang.NoClassDefFoundError: org/testcontainers/shaded/org/apache/commons/lang3/SystemUtils
09:29:45  	at org.testcontainers.containers.BrowserWebDriverContainer.configure(BrowserWebDriverContainer.java:211)
09:29:45  	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
09:29:45  	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
...
09:29:45  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
09:29:45  Caused by: java.lang.ClassNotFoundException: org.testcontainers.shaded.org.apache.commons.lang3.SystemUtils
09:29:45  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
09:29:45  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
09:29:45  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
09:29:45  	... 77 more
09:29:45  
```

**Comment by bsideup** [comment]
Hi @khmarbaise,

Please make sure that `org.testcontainers:testcontainers` is also updated to `1.17.1` (you may have it forced to a lower version, eg via Quarkus)

**Comment by khmarbaise** [comment]
Hi @bsideup, first thanks for your fast answer...and the thing about "...forced to a lower versions" (no we are not using Quarkus) ..brought me into the right direction. We accidently haven't used the bom in that project (which I assumed) only two dependencies instead which might cause the issue.. I've changed to use the BOM instead ... and now it looks better...finishing the whole tests will take a few hours. I will report back.

**Comment by khmarbaise** [comment]
So I confirm that it now works fine. That was the issue.
