### ISSUE TITLE
Docker Machine 17.09.1-ce on Mac - major performance regression?

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#527]
I'm not sure of the cause, but I'm seeing catastrophic performance issues with 17.09.1-ce on Mac.

I really hope I'm doing something wrong...

[This test class](https://github.com/testcontainers/testcontainers-java/blob/diagnose-slow-docker-machine/core/src/test/java/org/testcontainers/DebugSlowMachineTest.java) illustrates the issue.

What I'm seeing is:

- the `timeExec` and `timeExecWithoutStdout` methods take almost exactly 2 minutes to run
- `timeTail` is fast; hundreds of milliseconds

**Comment by rnorth** [comment]
I believe the waiting time is stuck waiting for the exec operation to complete, FWIW.

**Comment by StefanoGuerrini** [comment]
I don't know if my problem is related with your, but after I have update docker at version _17.09.1-ce-mac42_ my tests fail with:

```
Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (0.0.0.0 ports: [32807] should be listening) at org.testcontainers.containers.wait.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49).
```

[This is my code](https://github.com/StefanoGuerrini/springboot-testcontainers-snip) to reproduce issues.

**Comment by kiview** [comment]
Hey @StefanoGuerrini,

thanks for your example, it works fine for me, also I think it's unrelated to this issue. You can join our Slack and we can try to figure out what's the problem with your environment, or you could create another issue.

**Comment by StefanoGuerrini** [comment]
Hi @kiview, thanks so much for the reply.
I have resolved my problem: In my environment there was a running docker-machine.
I found this with `docker-machine ls`, and after remove It works.
