### ISSUE TITLE
`createSubscription()` for `ProjectSubscriptionName` is deprecated

### ISSUE THREAD

**Issue by felix-seifert** [testcontainers/testcontainers-java#5289]
The method `createSubscription(ProjectSubscriptionName name, TopicName topic, PushConfig pushConfig, int ackDeadlineSeconds)` from the example is deprecated. Probably, we should use `createSubscription(String name, TopicName topic, PushConfig pushConfig, int ackDeadlineSeconds)`, i.e. replace `ProjectSubscriptionName name` with `String name`.

https://github.com/testcontainers/testcontainers-java/blob/96601379e0d1e01ab9743566545e8413e7155e81/modules/gcloud/src/test/java/org/testcontainers/containers/PubSubEmulatorContainerTest.java#L108

**Comment by eddumelendez** [comment]
@felix-seifert thanks for the report! are you willing to send a PR?

**Comment by eddumelendez** [comment]
Thanks @felix-seifert! Closing in favour of #5350

**Comment by bsideup** [comment]
Actually, let's keep it open and close when we merge the PR (it already contains "Fixes issue #xxxx" so it will close automatically)
