### ISSUE TITLE
Hbase tests example

### ISSUE THREAD

**Issue by maria-ustyugova** [testcontainers/testcontainers-java#530]
Hello!
I stumbled into a problem while trying to use testcontainers to test job, which uses hbase. Container with hbase is running correctly, but i have some problems with connection to it in the test. The problem related to hbase.zookeeper.quorum and hbase.zookeeper.property.clientPort settings. Can you make some working example testing hbase using testcontainers?
Thanks in advance

**Comment by bsideup** [comment]
Hi @maria-ustyugova,

Since HBase clients use ZooKeeper to discover the masters (very much like Kafka), I'm afraid you have to run it with static port assignments (see `FixedHostPortGenericContainer` and `withFixedExposedPort`)

Both Kafka and HBase are not NAT friendly :(

**Comment by maria-ustyugova** [comment]
I've tried to use FixedHostPortGenericContainer, as you stated, but failed to connect to embedded zookeeper.  I need to state hbase.zookeeper.quorum to establish connection, but with getContainerIpAddress i can retrieve just localhost. Maybe there are some other ways to get correct host name?

**Comment by maria-ustyugova** [comment]
I tried to connect this way. Am i right?

```java
    @ClassRule
    public static GenericContainer hbase = new FixedHostPortGenericContainer("dajobe/hbase:latest")
            .withFixedExposedPort(2181,2181);
```
.........
```java
Configuration config = HBaseConfiguration.create();
config.set("hbase.zookeeper.quorum", hbase.getContainerIpAddress());
config.set("hbase.zookeeper.property.clientPort", hbase.getMappedPort(2181).toString());
org.apache.hadoop.hbase.client.Connection connection = ConnectionFactory.createConnection(config);
HBaseAdmin.checkHBaseAvailable(config);
```

**Comment by kiview** [comment]
You don't need to use `getMappedPort` if you use `FixedHostPortGenericContainer`, you can use 2181 directly in your case (not sure what `getMappedPort` returns in this case).

Since the port is mapped to your host, localhost should work in this case.

**Comment by maria-ustyugova** [comment]
I get that, but this method also returns this port, so it doesn't affect

By the error i assume that it mapped not to correct host, because hbase can't get connection with zookeeper node

**Comment by bsideup** [comment]
@maria-ustyugova 
AFAIK HBase works this way:
1) Hey ZK, where should I connect to HBase?
2) Host "blablahost"
3) kthxbye

And while it works with NAT, with NAT happens the following:
1) your app at your host gets "blablahost"
2) but "blablahost" exists only inside that container
3) your app can't connect

to fix that, you need to hint ZK about "external" host, but I'm lacking experience with HBase to give some concrete configuration params, sorry :(

**Comment by kiview** [comment]
The hostname based problems are also mentioned in the README of your used image:
https://github.com/dajobe/hbase-docker#note

So maybe you can somehow work around by editing `/etc/hosts` (of course that's not very portable and convenient :disappointed:).

**Comment by maria-ustyugova** [comment]
Thanks for your answers, I will think about it

**Comment by maria-ustyugova** [comment]
Can i ask you one more time?
Is there any possibility to use ImageFromDockerfile with FixedHostPortGenericContainer?

**Comment by Jahnec** [comment]
Hi, I'm currently working with testcontainers & hbase and I've finally managed to have an available Hbase.
Here is my configuration : 
  /etc/hosts :
`172.17.0.2  hbase`

```
@ClassRule
public static GenericContainer hbase = new FixedHostPortGenericContainer("dajobe/hbase:latest")
      .withFixedExposedPort(2181,2181).withExtraHost("hbase", "172.17.0.2");
...
@Before
    public void initialization() throws IOException, ServiceException {
      // HBASE
      Configuration config = HBaseConfiguration.create();
      config.set("hbase.zookeeper.quorum", "hbase");
      config.set("hbase.zookeeper.property.clientPort", hbase.getMappedPort(2181).toString());
      org.apache.hadoop.hbase.client.Connection connection = ConnectionFactory.createConnection(config);
      HBaseAdmin.checkHBaseAvailable(config);
}
```

In addition with your current config, you have to specify the **extraHost** on your GenericContainer.
Once is done, don't forget to add a mapping in your /etc/hosts file.
Hope it'll help you.

**Comment by akshayarni** [comment]
@maria-ustyugova Were you able to resolve this issue? I tried what @Jahnec had suggested, but that does not seem to be working. It would be helpful if you could share your findings.

**Comment by djice** [comment]
Hi,

we build a new image of hbase to be compliant with test container.

Use this image:

docker run --env HBASE_MASTER_PORT=16000 --env HBASE_REGION_PORT=16020 jcjabouille/hbase-standalone:2.4.9

Then create this Container (in scala here)

```scala
private[test] class GenericHbase2Container
    extends GenericContainer[GenericHbase2Container](
      DockerImageName.parse("jcjabouille/jcjabouille/hbase-standalone:2.4.9")
    ) {
  private val randomMasterPort: Int = FreePortFinder.findFreeLocalPort(18000)
  private val randomRegionPort: Int = FreePortFinder.findFreeLocalPort(20000)
  private val hostName: String = InetAddress.getLocalHost.getHostName

  val hbase2Configuration: Configuration = HBaseConfiguration.create
  addExposedPort(randomMasterPort)
  addExposedPort(randomRegionPort)
  addExposedPort(2181)
  withCreateContainerCmdModifier { cmd: CreateContainerCmd =>
    cmd.withHostName(hostName)
    ()
  }
  waitingFor(Wait.forLogMessage(".*0 row.*", 1))
  withStartupTimeout(Duration.ofMinutes(10))
  withEnv("HBASE_MASTER_PORT", randomMasterPort.toString)
  withEnv("HBASE_REGION_PORT", randomRegionPort.toString)
  setPortBindings(Seq(s"$randomMasterPort:$randomMasterPort", s"$randomRegionPort:$randomRegionPort").asJava)

  override protected def doStart(): Unit = {
    super.doStart()
    hbase2Configuration.set("hbase.client.pause", "200")
    hbase2Configuration.set("hbase.client.retries.number", "10")
    hbase2Configuration.set("hbase.rpc.timeout", "3000")
    hbase2Configuration.set("hbase.client.operation.timeout", "3000")
    hbase2Configuration.set("hbase.client.scanner.timeout.period", "10000")
    hbase2Configuration.set("zookeeper.session.timeout", "10000")
    hbase2Configuration.set("hbase.zookeeper.quorum", "localhost")
    hbase2Configuration.set("hbase.zookeeper.property.clientPort", getMappedPort(2181).toString)
  }
}
```

More details here: https://hub.docker.com/r/jcjabouille/hbase-standalone
