### ISSUE TITLE
[FEATURE REQUEST] support TC_INITSCRIPT at JdbcDatabaseContainer level

### ISSUE THREAD

**Issue by AnkBurov** [testcontainers/testcontainers-java#532]
Hello. Current implementation of the jdbc:tc:* type of container initialization currently doesn't support private docker registers.

Usage of 
```Kotlin
System.setProperty("spring.datasource.url", "jdbc:tc:private.registry.org:5000/mariadb://hostname/databasename?TC_INITSCRIPT=${mariaInitScript}&TC_MY_CNF=maria-conf")
```
leads to
```Java
Caused by: java.lang.IllegalArgumentException: JDBC URL matches jdbc:tc: prefix but the database or tag name could not be identified
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:100)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)
	... 64 more
```
Is it going to be fixed / implemented? Kinda confuses that private registers can be used with general container initialization (through builder-like fluent interface) and cannot with jdbc:tc:*. 
            
upd: see comments below

**Comment by bsideup** [comment]
Hi @AnkBurov 
JDBC URL-like initialization indeed [does not support custom images](https://github.com/testcontainers/testcontainers-java/blob/95bbecc343fa13eb1ae8d9d2b165fda820c8cc8b/modules/mysql/src/main/java/org/testcontainers/containers/MySQLContainerProvider.java#L9) because we don't know what database will be inside these images

**Comment by AnkBurov** [comment]
Hello @bsideup Thanks for the super fast answer!
Sounds like that JdbcDatabaseContainer need to have new feature - initial script applying, because currently it can be used only through jdbc:tc. So it forces to use JDBC URL-like initialization which doesn't support custom images.  :persevere:

**Comment by bsideup** [comment]
@AnkBurov oh, that is true! Thanks for reporting :) Do you want to rename this issue to something like `[FEATURE REQUEST] support TC_INITSCRIPT at JdbcDatabaseContainer level` or raise another one?

**Comment by AnkBurov** [comment]
I'll just rename the issue, thanks.
