### ISSUE TITLE
Why don't we just parse docker-compose instead of configuring in tests 

### ISSUE THREAD

**Issue by eballci** [testcontainers/testcontainers-java#5355]
I think the idea behind Testcontainers is very good inspiration, it simplifies the creating test environment, but it requires extra configuration regardless docker-compose file whether existing. Usually docker-compose file using for creating production enviroment. I also think test enviroments must as close as production environment and must be created by using production configurations. But Testcontainers seperates the configurations. In my opinion this method is not sustainable in long term, in large wide projects. I think Testcontainers must parse the docker-compose file and create the necessary containers except application container. In that way we developers can create test enviroment same as production enviroment. This idea eliminates extra configuritaion in test classes.

**Comment by bsideup** [comment]
1. Not many production environments run with Docker Compose
2. It would require re-implementing the whole Docker Compose in Java
3. GenericContainer-based approach gives much more flexibility compared to a "static" YAML config
4. Some technologies like Kafka do not play well with Docker Compose
5. Why writing 10 lines of YAML when you can write `new KafkaContainer()` and be done with in
6. Many Testcontainers-based modules offer convenient extra methods (eg `getJdbcURL()`, `getBootstrapURL()`, `withExtension` in HiveMQ) that you would lose with Docker Compose
7. Some advanced features (eg exposing host's port, or **copying** files into containers) are not available in Docker Compose


If you already have a Docker Compose file, you may use Testcontainers' Docker Compose module:
https://www.testcontainers.org/modules/docker_compose/

That said, it is mostly for "getting started"/migrating perspective, and we highly recommend the GenericContainer-based approach.
