### ISSUE TITLE
Compose is not pulling from private repo

### ISSUE THREAD

**Issue by yurybubnov** [testcontainers/testcontainers-java#536]
If I use private repo in `compose.yml` file, then containerized compose if failing to pull images. The fix, I think, is to mount `$HOME/.docker` to `/root/.docker` in compose container

**Comment by iNikem** [comment]
This issue is now solved, isn't it?

**Comment by rnorth** [comment]
Yes, thanks for flagging. I'll close, but please be aware of #565 as a caveat though.

**Comment by iNikem** [comment]
Seems like compose is not the only victim: #567
