### ISSUE TITLE
Contributed modules link on website does not work

### ISSUE THREAD

**Issue by rompic** [testcontainers/testcontainers-java#538]
In the description at https://www.testcontainers.org

> Much more! Check out the various **contributed modules** or create your own custom container classes using GenericContainer as a base.

Contributed modules links to https://www.testcontainers.org/modules.md which does not seem to exist.

**Comment by rompic** [comment]
The link to GenericContainer does not work either

**Comment by kiview** [comment]
The GenericContainer link needs to be https://www.testcontainers.org/usage/generic_containers.html
