### ISSUE TITLE
OracleContainer waiting for the wrong regular expression

### ISSUE THREAD

**Issue by carstenartur** [testcontainers/testcontainers-java#5392]
The Code used looks like this

`    private void preconfigure() {
        this.waitStrategy = new LogMessageWaitStrategy()
            .withRegEx(".*DATABASE IS READY TO USE!.*\\s")
            .withTimes(1)
            .withStartupTimeout(Duration.of(DEFAULT_STARTUP_TIMEOUT_SECONDS, SECONDS));

        withConnectTimeoutSeconds(DEFAULT_CONNECT_TIMEOUT_SECONDS);
        addExposedPorts(ORACLE_PORT, APEX_HTTP_PORT);
    }`

But what I see is

`Remove password info
Docker DB configuration is complete !
configDB.sh is done at 31 sec

Done ! The database is ready for use .
# ===========================================================================  
# == Add below entries to your tnsnames.ora to access this database server ==  
# ====================== from external host =================================  `

Can it be that

**.withRegEx(".*DATABASE IS READY TO USE!.*\\s")**

does not match

**Done ! The database is ready for use .**

and because of that an oracle image always runs into the timeout?

**Comment by eddumelendez** [comment]
@carstenartur default image used by `OracleContainer` uses `gvenzl/oracle-xe:18.4.0-slim`, which one are you using?

If you are using a different one the you can use something like

```
new OracleContainer(...).waitingFor(Wait.forLogMessage("".DATABASE IS READY TO USE!.\\s"", 1))
```

**Comment by carstenartur** [comment]
I tried multiple images including the default one you mentioned. I'm surprised: you mean the default image should work?
So there is no problem with for/to ?

**Comment by eddumelendez** [comment]
Tests are using the same image as you can see [here](https://github.com/testcontainers/testcontainers-java/blob/master/modules/oracle-xe/src/test/java/org/testcontainers/junit/oracle/SimpleOracleTest.java)

Can you share a sample project that reproduces the issue, please?

**Comment by carstenartur** [comment]
OK, I think I found out what happened.
You can see the output of the older oracle standard image here:
https://faun.pub/run-sql-startup-script-on-oracle-database-container-initialization-e94ea983dccd
I had a forgotten entry in the file testcontainers.properties in the classpath:
oracle.container.image=store/oracle/database-enterprise:12.2.0.1-slim
Because of this, it didn't matter which image I made use of it always falls back to this old image that is no longer supported but still available over here. And this image does not work with the default setting as it is using 

database is ready for use

instead of 

database is ready to use

And that of course cannot work.
Thank you all for your help and your patience. Sorry to blame testcontainers to be responsible for this mismatch. It is me making use of an outdated image. If you have an idea on how to improve error handling to make it simpler for someone not deeper into it to find the reason of the problem that would be fine. Other than that I see it to be resolved as invalid.

**Comment by kiview** [comment]
Glad you figured it out @carstenartur. I would agree that this behavior is not really intuitive and it also circumvents our explicit opt-in for non-default image usage. Did you see the used image in the logs?

**Comment by carstenartur** [comment]
Yes, it is

store/oracle/database-enterprise:12.2.0.1-slim

The log created is:
13:33:35,773 [32mINFO [m [main] org.testcontainers.DockerClientFactory org.testcontainers.DockerClientFactory.check(DockerClientFactory.java:234) - ✔︎ Docker server version should be at least 1.6.0
13:33:35,773 [33mWARN [m [main] org.testcontainers.utility.ConfigurationFileImageNameSubstitutor org.testcontainers.utility.ConfigurationFileImageNameSubstitutor.apply(ConfigurationFileImageNameSubstitutor.java:31) - Image name gvenzl/oracle-xe:18.4.0-slim was substituted by configuration to store/oracle/database-enterprise:12.2.0.1-slim. This approach is deprecated and will be removed in the future
13:33:35,774 [32mINFO [m [main] org.testcontainers.utility.ImageNameSubstitutor org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor.apply(ImageNameSubstitutor.java:94) - Using store/oracle/database-enterprise:12.2.0.1-slim as a substitute image for gvenzl/oracle-xe:18.4.0-slim (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
13:33:35,775 [32mINFO [m [main] 🐳 [store/oracle/database-enterprise:12.2.0.1-slim] org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:372) - Creating container for image: store/oracle/database-enterprise:12.2.0.1-slim
13:33:35,849 [32mINFO [m [main] 🐳 [store/oracle/database-enterprise:12.2.0.1-slim] org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:436) - Container store/oracle/database-enterprise:12.2.0.1-slim is starting: 7d327333e364492add8034307be7de1b1f65c669e7794ae148f4d42b537a1486
13:37:36,789 [1;31mERROR[m [main] 🐳 [store/oracle/database-enterprise:12.2.0.1-slim] org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:524) - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*DATABASE IS READY TO USE!.*\s'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49) ~[testcontainers-1.17.2.jar:?]
