### ISSUE TITLE
[FEATURE REQUEST] Support running in pre-integration-tests

### ISSUE THREAD

**Issue by erikhakansson** [testcontainers/testcontainers-java#540]
Our test suite runs ~50 parallell tests against a complete environment containing about 10 different docker containers. To start the environment takes about 10 minutes and takes several GB of memory, meaning it's not really feasible to start one set of containers per test or even class.

Currently, we manually start our docker environment (using docker-compose) and then run integration tests using surefire against that environment.

It would be great to be able to control the environment through testcontainers-java during the Maven pre-integration-test and post-integration-test lifecycles.

I considered implementing something myself, but while it would be quite easy to start containers in the pre- phase, I'm not sure how I would stop the same containers in the post- phase.

**Comment by bsideup** [comment]
Hi @erikhakansson,

> It would be great to be able to control the environment through testcontainers-java during the Maven pre-integration-test and post-integration-test lifecycles.

It's actually not-so-great because you have to run your tests via Maven :D 

Instead (and also to keep IDE friendliness), you can start a single set of containers per execution, not per test, i.e. by using a static block:
https://github.com/bsideup/testcontainers-microservices-example/blob/5d28ca32d29d9fd7f3101044a02ec2660b0678fd/src/test/java/org/testcontainers/example/demo/support/AbstractIntegrationTest.java#L38

**Comment by kiview** [comment]
Hi @erikhakansson, 

a project which kind of does what you are looking for is the [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin). Maybe this would work better for you, although we of course intend to allow for as much use cases as possible when using testcontainers.

A possible solution for using testcontainers in this use case is having i.e. an abstract base class for integration tests, which will start the containers once on initialization. You don't have to use JUnit annotations in this case, you can manually start the containers (or compose-container) using the `start()` method.
