### ISSUE TITLE
JdbcDatabaseContainer doesn't have lazy image constructor

### ISSUE THREAD

**Issue by npetzall** [testcontainers/testcontainers-java#543]
Hi

Is there a reason why JdbcDatabaseContainer doesn't have the super constructor with Future<String> image)?

```
public JdbcDatabaseContainer(@NonNull final Future<String> image) {
        super(image);
}
```

**Comment by iNikem** [comment]
What is the use-case that requires this type of construction??

**Comment by npetzall** [comment]
I want to be able to access the instance method getJdbcDriverInstance() before the images has been pulled.

I have written a junit wrapper library and the assumeDriver function is too slow. Since I use custom JDBC containers that requires proprietary drivers they might not be available and I want that to be checked before pulling the image.

Library exists more or less to add assumptions.

With the lazy loading I can skip the image pull if the driver is missing by skipping the test before it actually pulls/starts the container.

**Comment by iNikem** [comment]
wow, I think the correct question is "why `public GenericContainer(String dockerImageName)` pulls the image?" :)

**Comment by bsideup** [comment]
@iNikem yes, @rnorth, why? :D Jokes aside, AFAIR Richard wanted tests to fail fast if image pull fails.
We briefly discussed that when I was working on #106

**Comment by rnorth** [comment]
Precisely that, to fail fast. If a test class declares multiple `@Rule`s, it seem(s/ed?) bad to spend time starting some of them, but then fail to pull a non-existent image. 

This was an old decision though - happy to revisit in light of how people want to use the tool nowadays, and whether this makes sense.

**Comment by npetzall** [comment]
So adding the suppressed constructor wouldn't be a problem.

Other if possible solution would be to query repositories to see if image exists but to do pulling in start/tryStart.
