### ISSUE TITLE
Configurable port for MySQLContainer

### ISSUE THREAD

**Issue by dhargo** [testcontainers/testcontainers-java#544]
Please add configurable port for MySQLContainer. Currently MySQLContainer has only predefined ```static final Integer MYSQL_PORT = 3306```. A setter can be added (e.g. ```public SELF withMySqlPort(Integer port)```).

**Comment by kiview** [comment]
HI @dhargo,
can you expand on the use case, where you need to set another port? 
The container is accessible by the outside using `getJdbcUrl()` or manually by getting the mapped port using `getMappedPort(MYSQL_PORT)`.

**Comment by iNikem** [comment]
Should this issue be closed due to inactivity?

**Comment by dhargo** [comment]
Sorry for inconvenience. The issue is not relevant.
