### ISSUE TITLE
can't import BrowserWebDriverContainer mavanproject

### ISSUE THREAD

**Issue by darkklin** [testcontainers/testcontainers-java#547]
Hi,
I trying to use BrowserWebDriverContainer 

but I can't import
org.testcontainers.containers.BrowserWebDriverContainer;

my pom file contain 
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers</artifactId>
    <version>1.4.3</version>
</dependency>
I don't understand why, Please help me
thanks.
![screenshot_21](https://user-images.githubusercontent.com/25209561/35070258-5767b7d2-fbe5-11e7-9901-be2ebc0eb129.png)

**Comment by kiview** [comment]
Hi @darkklin,
you need to add the `selenium` module dependency:
```
<dependency>    
  <groupId>org.testcontainers</groupId>    
  <artifactId>selenium</artifactId>    
  <version>1.5.1</version>
</dependency>
```

By the way, it's a POM file, not a porn file 😹

**Comment by darkklin** [comment]
lol haha *pom my bad.
I Will try this after work letter, Please don't close this Issue, for now, i  will update here if it's worked in end of the day, Thank you.

**Comment by darkklin** [comment]
I from the start I looked for the correct dependency and found the wrong ones.
Thank you, it' working.
