### ISSUE TITLE
atmoz/sftp How to specify SSH host key

### ISSUE THREAD

**Issue by r3dfur** [testcontainers/testcontainers-java#5478]
Hi,

i'm working with  [atmoz/sftp](https://hub.docker.com/r/atmoz/sftp)
I would mount my own host keys as described:

docker run \
    -v <host-dir>/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro \
    -v <host-dir>/id_other.pub:/home/foo/.ssh/keys/id_other.pub:ro \
    -v <host-dir>/share:/home/foo/share \
    -p 2222:22 -d atmoz/sftp \
    foo::1001

i try with:

```
    private static GenericContainer buildSFTPContainer(Path filePath) {
        return new GenericContainer<>(DockerImageName.parse("atmoz/sftp:latest"))
                .withCreateContainerCmdModifier(createContainerCmd -> {
                    createContainerCmd.withCmd("-v /tmp/keys/sftp_rsa_key:/etc/ssh/sftp_rsa_key ");
                })
                .withExposedPorts(PORT)
                .withCopyFileToContainer(MountableFile.forHostPath(filePath),
                        "/home/" + USER + REMOTE_PATH + filePath.getFileName())
                .withCommand(USER + ":1001:::upload");


    }
```
but it doesn't work.

Can you help me? 
Thanks

**Comment by WrettySV** [comment]
Hello. Sorry have you found the solution for this problem?

**Comment by eddumelendez** [comment]
Thanks for sharin @anujpradhaan ! Would you like to contribute with an [example](https://github.com/testcontainers/testcontainers-java/blob/main/examples/sftp/src/test/java/org/example/SftpContainerTest.java)?
