### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#548]
We should consider different options for a Windows CI environment because ATM we only test it manually

**Comment by AnkBurov** [comment]
Try https://www.appveyor.com/
It's free for open-source and works with Maven.

**Comment by kiview** [comment]
Hey @AnkBurov, thanks for the suggestion. We've already looked into appveyor a couple of time, but currently they aren't supporting Linux Containers (LCOW). Once the provided Windows images will support LCOW and WCOW simultaneously, this might be a good solution.

**Comment by kiview** [comment]
We are currently working on a Windows CI environment in TeamCity.

**Comment by isen-ng** [comment]
AppVeyor has LCOW support now:
https://www.appveyor.com/blog/2019/10/11/vs2019-image-with-docker-wsl-preheated/

**Comment by isen-ng** [comment]
I have confirmed this behavior with further testing.

AppVeyor's LCOW support uses the experimental feature described in https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

The problem with this experimental feature is that it is incomplete, meaning there is no way to mount `/var/run/docker.sock` into Ryuk.

Running a pure linux command gives the expected exception
```
$ docker run --rm -v //var/run/docker.sock:/var/run/docker.sock quay.io/testcontainers/ryuk:0.2.3
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock'.
```

Running the windows command gives another exception
```
$ docker run --rm -v //./pipe/docker_engine:/var/run/docker.sock quay.io/testcontainers/ryuk:0.2.3
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid volume specification: '//./pipe/docker_engine:/var/run/docker.sock': invalid mount config for type "npipe": Linux containers on Windows do not support named pipe mounts.
```

This current problem is tracked by https://github.com/moby/moby/issues/36574 

Essentially, the new experimental LCOW does not support docker in docker and cannot be used to run Ryuk and TestContainers in most cases.

Now, I just need to find a CI that runs the regular LCOW on Windows.

**Comment by bsideup** [comment]
FTR we do [test every master build on Windows](https://dev.azure.com/testcontainers/testcontainers-java/_build?definitionId=4&_a=summary), and some PRs when needed

**Comment by isen-ng** [comment]
Ohhh! you have your own Windows VM with linux containers!

**Comment by bsideup** [comment]
Well, it is not even a VM, but a mini Dell OptiPlex hosted at my place 😂

**Comment by isen-ng** [comment]
This is what I call, dedication. Up till now, I cannot find a Win10 (with GUI) ci solution for free yet.

**Comment by bsideup** [comment]
Implemented with Azure Pipelines:
https://dev.azure.com/testcontainers/testcontainers-java/_build?definitionId=4&_a=summary
