### ISSUE TITLE
Docker image builder cannot parse --platform=$BUILDPLATFORM argument from Dockerfile

### ISSUE THREAD

**Issue by yuranich** [testcontainers/testcontainers-java#5499]
Hi, could you please take a look at the issue? 

`
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
`

Dockerfile used:
`
FROM --platform=$BUILDPLATFORM scylladb/scylla:4.6.3
COPY ./create-keyspaces.sh create-keyspaces.sh
ENTRYPOINT ["sh", "/create-keyspaces.sh"]
`

Argument is taken from docker docs https://docs.docker.com/engine/reference/builder/#from

Not sure at which point $BUILDPLATFORM should be substituted but `docker-compose` works fine.
Appreciate any  suggestion, thanks.

**Comment by eddumelendez** [comment]
> Not sure at which point $BUILDPLATFORM should be substituted but docker-compose works fine.

I would say that in the docker-compose even if it was defined on the file, it was ignored by testcontainers

Regarding to the issue you have, testcontainers acts as another client but doesn't necessarily match the same behavior in every aspect as, for example, docker cli. As far as I can see, `BUILDPLATFORM` and [others](https://github.com/moby/buildkit/blob/175e8415e38228dbb75e6b54efd2c8e9fc5b1cbf/frontend/dockerfile/dockerfile2llb/platform.go#L42-L50) are resolved in `buildkit` and it is a separate tool with not the same docker image build process.

IMHO, this is not an issue and work as designed.
