### ISSUE TITLE
[Problem]:  Set  specific expose port range

### ISSUE THREAD

**Issue by baturorkun** [testcontainers/testcontainers-java#5503]
### Module

Kafka

### Testcontainers version

1.16.2

### Using the latest Testcontainers version?

Yes

### Docker version

```shell
20.10.16
```

### What happened?

I am using Testcontainer on Openshift. I created a POD by Docker DIND and set DOCKER_HOST but testcontainer dynamic exposing ports is a significant problem for us. I must open specific ports on Openshift services and limited. So I have to know the port ranges and set new ranges. But I could not find any solution for that.

**Comment by bsideup** [comment]
The port assignment is being done in Docker. See this page on how to tune it:
https://docs.docker.com/engine/reference/run/#expose-incoming-ports

> Docker binds each exposed port to a random port on the host. The range of ports are within an ephemeral port range defined by `/proc/sys/net/ipv4/ip_local_port_range`
