### ISSUE TITLE
[Feature]: Add configuration property to customize Docker registry

### ISSUE THREAD

**Issue by daniel-shuy** [testcontainers/testcontainers-java#5504]
### Module

Core

### Problem

The company I work in (and many other companies) has a private Docker registry that mirrors Docker Hub (using Artifactory). This is used to host private images, as well as to cache public Docker images, to avoid too much traffic going towards Docker Hub.

Therefore to use Testcontainers, we have to customize all the image configurations (https://www.testcontainers.org/features/configuration/#customizing-images) to pull from our internal Docker registry instead of Docker Hub, by prefixing all the image names with our Docker registry, eg.
```properties
ryuk.container.image=<registry>/testcontainers/ryuk:0.3.3
```

This makes updating Testcontainers tedious, as we will need to manually update the configured versions of the Docker images.

### Solution

It would be great if a property for customizing the Docker registry (eg. `docker.registry`) could be added, that would be prepended to all the Docker images used by Testcontainers if specified.

### Benefit

Avoids having to manually check and update the versions of all Docker images used by Testcontainers when using a private Docker registry

### Alternatives

N/A

### Would you like to help contributing this feature?

Yes

**Comment by shelajev** [comment]
Would the approach described in "Automatically modifying Docker Hub image names" [section](https://www.testcontainers.org/features/image_name_substitution/) be an appropriate solution?

**Comment by daniel-shuy** [comment]
@shelajev wasn't aware of that feature, just tried it and it works, thanks!
