### ISSUE TITLE
[Bug]: Exec in container doesn't find files when using wildcard asterix.

### ISSUE THREAD

**Issue by ZdrOStiwa** [testcontainers/testcontainers-java#5512]
### Module

Core

### Testcontainers version

1.16.2

### Using the latest Testcontainers version?

No

### Docker version

```shell
20.10.16
```

### What happened?

container.execInContainer("rm","/data/folder/*")
leads to 
"no such file or directory"

"rm /data/folder/*" inside of the container goes through succesfully.  Files are not hidden. Folder is not empty. 

container.execInContainer("rm","/data/folder/file") works correctly.

**Comment by dajudge** [comment]
I believe the wildcard feature is part of the shell (e.g. `sh` or `bash`) - the command you're executing is literally trying to delete a file called `*` in the `/data/folder/` directory.

In order to have wildcard semantics you'd probably need to execute sth like the following:

```
container.execInContainer("sh", "-c", "rm /data/folder/*")
```

**Comment by kiview** [comment]
@dajudge 's comment is right. I will therefore close the issue since the `rm` command itself has no wildcard feature built-in.

**Comment by ZdrOStiwa** [comment]
@dajudge Thank you for the explanation. Your code solves the issue.
