### ISSUE TITLE
[Enhancement]: Better WaitStrategy to ensure the Pulsar cluster is fully initialised

### ISSUE THREAD

**Issue by nahguam** [testcontainers/testcontainers-java#5513]
### Module

Pulsar

### Proposal

The current `PulsarContainer`'s `WaitStrategy` includes waiting for the metrics endpoint to be available. The metrics endpoint is activated before the cluster and default tenants and namespaces are created. On slower systems (perhaps Apple M1 silicon running under Rosetta 2 for x86 arch), if your first step after the container is ready is to start interrogating the admin API, then certain calls may get unexpected responses.

I propose to instead check the admin clusters endpoint to ensure that the `standalone` cluster has actually been created.

**Comment by eddumelendez** [comment]
Hi @nahguam thanks for opening the enhancement proposal but no need it if it comes with a PR just right after :)

**Comment by nahguam** [comment]
@eddumelendez Ok Thanks for the guidance :)
