### ISSUE TITLE
Clean up automatically when container stopped

### ISSUE THREAD

**Issue by alexcase52** [testcontainers/testcontainers-java#552]
Hi, is there a way to properly clean up once container stopped?
Would be good to have it as a setter in GenericContainer.

It could rely on [this](https://docs.docker.com/engine/reference/run/#clean-up-rm)

**Comment by bsideup** [comment]
hi @alexcase52,

Do you want it to be cleaned during the tests or after?

**Comment by alexcase52** [comment]
Immediately once the container stopped is better for me - it may retain some space. But usually it is no so important when.

**Comment by kiview** [comment]
We already have such a functionality in place (Reaper) and we will soon add a more reliable component for this running outside the JVM.

What functionality are you missing with the current implementation?

**Comment by alexcase52** [comment]
OK if you already have it. I just see some strange exited containers appeared after I started experiments with testcontainers. In my case there were postgres containers.

**Comment by kiview** [comment]
This will currently happen if you i.e. SIGKILL the JVM process.

**Comment by alexcase52** [comment]
Maybe I had this case and some guard here is desirable. Quite often I could terminate tests e.g. while debugging if I see that something failed and I've got what was wrong. Not sure how this docker --rm flag will behave.

**Comment by bsideup** [comment]
@alexcase52 
Bad news: `--rm` doesn't help (try `kill -9` your `docker run --rm` :) )
Good news: we're going to handle that! :) See #545 for the details, to be released soon

**Comment by alexcase52** [comment]
Thanks, will wait for this change

**Comment by iNikem** [comment]
I believe this can be closed now as #545 is released in 1.6.0

**Comment by kiview** [comment]
Closed by #545
