### ISSUE TITLE
ROADMAP link on documentation is broken

### ISSUE THREAD

**Issue by iNikem** [testcontainers/testcontainers-java#557]
https://www.testcontainers.org/#contributing mentions ROADMAP.md, but when clicking on that link, nothing happens.

**Comment by rnorth** [comment]
We fixed this recently but forgot to close this issue. Closing now!

**Comment by NikitaZhevnitskiy** [comment]
Hi @rnorth, link is still broken.

**Comment by kiview** [comment]
@NikitaZhevnitskiy Where do you see the ROADMAP link in the current docs?

**Comment by NikitaZhevnitskiy** [comment]
@kiview in [CONTRIBUTING](https://github.com/testcontainers/testcontainers-java/blob/master/CONTRIBUTING.md)

**Comment by kiview** [comment]
Ah thanks, you are of course right.

@rnorth Should we delete this file? It's in the new docs now after all.

**Comment by Spedge** [comment]
Here's one gtg : https://github.com/testcontainers/testcontainers-java/pull/1511
