### ISSUE TITLE
[Bug]: MSSQL server property encrypt does not contain a valid boolean value.

### ISSUE THREAD

**Issue by TheMessik** [testcontainers/testcontainers-java#5589]
### Module

MSSQLServer

### Testcontainers version

1.17.2

### Using the latest Testcontainers version?

Yes

### Host OS

EndeavourOS

### Host Arch

x86

### Docker version

```shell
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.3
 Git commit:        100c70180f
 Built:             Sat Jun 11 23:27:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       a89b84221c
  Built:            Sat Jun 11 23:27:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1.m
 runc:
  Version:          1.1.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I'm trying to run integration tests for a tool I'm developing with my team. We support a wide range of databases, among others MS SQL. Until now, running integration tests for Postgres and MySQL with Testcontainers was smooth sailing.

I start the MSSQL container through the JDBC URL `jdbc:tc:sqlserver:latest:///?TC_REUSABLE=true&user=SA&password=A_Str0ng_Required_Password`. I however can't connect to this container using the very same URL in order to set up the database schema and query it.

When creating a new connection to the container (aside from the whole process being incredibly slow compared to other databases), I get a SQLServerException `The property encrypt does not contain a valid boolean value. Only true or false can be used.`.

Adding `&encrypt=false` to the URL does not solve the issue.

If I failed to provide any details you need to help me with this, my apologies.

The testcontainers relevant dependencies in pom.xml:
```
        <dependency>
            <groupId>org.testcontainers</groupId>  <!-- for running tests with dockerized databases -->
            <artifactId>testcontainers</artifactId>
            <version>1.17.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <version>1.17.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
            <version>1.17.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mssqlserver</artifactId>
            <version>1.17.2</version>
            <scope>test</scope>
        </dependency>
```
Precise code ran:
```java
String sql = new String(Files.readAllBytes(Paths.get(Utils.getFile(sqlFile, null).getAbsolutePath())), StandardCharsets.UTF_8);
sql = sql.replaceAll(" +--.*\n*", ""); // get rid of the comments
String[] statements = sql.split(";");
System.out.println(connectionString);
final Connection conn = DriverManager.getConnection(connectionString);
System.out.println("Connection created!");
for (String statement : statements) {
    // strip the statement
    statement = statement.trim();
    if (!statement.equals("")) {
        conn.createStatement().execute(statement + ";");
    }
}
conn.close();
```
Second System.out.println call does not get executed, due to the exception happening on the line before.

Thanks for any help!

**Comment by eddumelendez** [comment]
Please update your url `jdbc:tc:sqlserver:latest:///?TC_REUSABLE=true;user=SA;password=A_Str0ng_Required_Password`

**Comment by TheMessik** [comment]
Amazing, thank you very much. Just one more question, how can I create a database with a specific name automatically?

URL ``jdbc:tc:sqlserver:latest:///TestDB`` doesn't create a TestDB database.

**Comment by eddumelendez** [comment]
MSSQL image doesn't offer a env variable to configure the database name, so, it is not possible nowadays.
