### ISSUE TITLE
[Feature]: Test containers for ImmuDB

### ISSUE THREAD

**Issue by shreelakshmijoshi** [testcontainers/testcontainers-java#5594]
### Module

New Module

### Problem

ImmuDB is a relational database in which data is immutable, secure, and auditable. It is used in many enterprise applications. However, for testing we need to connect to an in-memory immudb database which might not be feasible. 

### Solution

Creating a test container specifically for Immudb
[Here is the Link to the immubd website](https://docs.immudb.io/master/immudb.html#what-is-immudb)

### Benefit

Helps while testing the classes that depend on Immudb 

### Alternatives

There are no containers for Immudb database

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
https://hub.docker.com/r/codenotary/immudb

**Comment by eddumelendez** [comment]
[docker image](https://hub.docker.com/r/codenotary/immudb)
[github repository](https://github.com/codenotary/immudb)

**Comment by eddumelendez** [comment]
[docker image](https://hub.docker.com/r/codenotary/immudb)
[github repository](https://github.com/codenotary/immudb)

@kiview wdyt?

**Comment by kiview** [comment]
@shreelakshmijoshi 

ImmuDB looks like a nice technology, but I would like to understand what the problems are of using it with `GenericContainer`?Connections seem to be done with a specific client rather than with a JDBC driver, so no need to integrate with the Testcontainers JDBC driver feature. 

If it works straight-forward with `GenericContainer`, maybe contributing an [https://www.testcontainers.org/examples/](example) is enough?

**Comment by hariohmprasath** [comment]
> @shreelakshmijoshi
> 
> ImmuDB looks like a nice technology, but I would like to understand what the problems are of using it with `GenericContainer`?Connections seem to be done with a specific client rather than with a JDBC driver, so no need to integrate with the Testcontainers JDBC driver feature.
> 
> If it works straight-forward with `GenericContainer`, maybe contributing an [https://www.testcontainers.org/examples/](example) is enough?

@kiview and @eddumelendez, 
We dont need any special configuration for running `immudb`, since I was using this for my test run I contributed the same to the example module in this PR:
https://github.com/testcontainers/testcontainers-java/pull/5860

Please review it and let me know your thoughts.
