### ISSUE TITLE
[Bug]: Permission denied inside running Apache Pulsar container

### ISSUE THREAD

**Issue by dmytro-rusnak** [testcontainers/testcontainers-java#5603]
### Module

Pulsar

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux, MacOS

### Host Arch

x86, ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

We use Test Containers to run the Apache Pulsar docker container for testing purposes, but after updating to the latest version (Test Containers to 1.17.3 and Apache Pulsar to 2.10.0), we started getting permission errors inside the Apache Pulsar docker container to required `standalone.conf` file.
Also, these bugs are not reproducible in test containers 1.17.2 or Apache Pulsar 2.8.1.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/pulsar/bin/apply-config-from-env.py", line 104, in <module>
    f = open(conf_filename, 'w')
PermissionError: [Errno 13] Permission denied: '/pulsar/conf/standalone.conf'
```
```

### Additional Information

Sample project code to start Apache Pulsar:

PulsarContainer pulsar = new PulsarContainer(DockerImageName.parse("apachepulsar/pulsar:2.10.0"))
		.withCopyFileToContainer(MountableFile.forClasspathResource("standalone.conf"), "/pulsar/conf/standalone.conf")
		.withCommand("bin/pulsar standalone")
		.waitingFor(Wait.forListeningPort());
pulsar.start();
pulsar.execInContainer("bin/pulsar-admin", "namespaces", "set-retention", "public/default", "--size", "-1", "--time", "-1");
pulsar.execInContainer("bin/pulsar-admin", "namespaces", "set-schema-compatibility-strategy", "--compatibility", "ALWAYS_COMPATIBLE", "public/default");
pulsar.execInContainer("bin/pulsar", "initialize-transaction-coordinator-metadata", "-cs", "127.0.0.1:2181", "-c", "standalone")

**Comment by eddumelendez** [comment]
@dmytro-rusnak thanks for raising the issue! in 1.17.3, pulsar image was updated to 2.10. I wonder if you need that upgrade too? Otherwise, you can use the previous version you were using in the meantime.

**Comment by dmytro-rusnak** [comment]
@eddumelendez hi. Thanks for your reply. Previously, we used to test containers 1.17.2 and pulsar 2.10.0 and everything worked fine, but after updating the test containers to the new version 1.17.3, we started to catch the permission denied issue.
In our situation, we have two options:
1. Downgrade the test containers to 1.17.2 and keep using pulsar 2.10.0.
2. Keep using the 1.17.3 test containers, but downgrade pulsar to 2.9.3 and below (because this issue only reproduces 2.10.x).

I hope this information helps you :)

**Comment by eddumelendez** [comment]
thanks for sharing!

**Comment by eddumelendez** [comment]
[This change](https://github.com/testcontainers/testcontainers-java/blob/master/modules/pulsar/src/main/java/org/testcontainers/containers/PulsarContainer.java#L91) was introduced in the last release. The code below will fix the current issue

```
.withCopyFileToContainer(MountableFile.forClasspathResource("standalone.conf", 0777), "/pulsar/conf/standalone.conf"))
```

but  now you will be able to override config file given the prefix `PULSAR_PREFIX_<property-name>` which I would suggest as a much better way

```
PulsarContainer pulsar = new PulsarContainer(PULSAR_IMAGE)
            .withEnv("PULSAR_PREFIX_defaultNumPartitions", "2")
```

**Comment by dmytro-rusnak** [comment]
Hi @eddumelendez . I know the issue is closed, but the fix you provided didn't work for us.
For example, it fixed the permission denied, but the container still couldn't start with our standalone file and its configurations.

Do I need to create a separate ticket for this or provide additional information in this ticket?

**Comment by kiview** [comment]
@dmytro-rusnak For now, you can provide the additional information (setup code, logs) in this issue and we will look into it, thanks.

**Comment by dmytro-rusnak** [comment]
Hi @kiview . Thanks for replying me. I created a separate [project](https://github.com/dmytro-rusnak/pulsar-container-issue) as an example, but with configurations and dependencies like a real project (due to NDA, I can't share specific codes).
Also, I have shared the [stack trace and logs from the docker container](https://gist.github.com/dmytro-rusnak/7274007bc6161f38998b6bd4ba09b3d8).
Let me know if you need some additional information :)
