### ISSUE TITLE
[Enhancement]:  URL scheme support for NoSQL

### ISSUE THREAD

**Issue by smfaizalkhan** [testcontainers/testcontainers-java#5604]
### Module

MongoDB

### Proposal

Hi @rnorth @bsideup 

I have been using the JDBC URL scheme to launch test containers

I'm currently working in a project which involves NoSQL mongoDB ,So i would like to know is there support for NoSQL similar to JDBC/RJDBC .If so please share it

Regards,
Faizal

**Comment by rombert** [comment]
@smfaizalkhan - sorry, I can't answer your question, I am just a simple user and not familiar with this part of the project.

**Comment by daschl** [comment]
I'm also not involved with the MongoDB module, but if there are features to be implemented across the NoSQL modules I'm happy to help.

**Comment by eddumelendez** [comment]
@smfaizalkhan can you elaborate more, please? What's your use case and how testcontainers can help? why the current methods such as connectionString are not enough?

**Comment by smfaizalkhan** [comment]
Hi @eddumelendez 
Just like how how we have for [RDBC](https://www.testcontainers.org/modules/databases/jdbc/) like 
jdbc:tc:mysql:5.7.34:///databasename 
i wish we have something on sme lines for NoSQL

**Comment by kiview** [comment]
There is currently no SPI/driver concept for NoSQL technologies in the Java language, which would make any implementation extremely challenging (and not sure if feasible). Furthermore, to my knowledge, there is also no connection URL standard across NoSQL technologies, similar to JDBC/R2DBC.

And while I can understand that the magic JDBC-Proxy-Driver support in Testcontainers is very useful for some use cases, using Testcontainers via its programmatic API is the most powerful and flexible integration after all and can be used for all use cases.
