### ISSUE TITLE
Combine Java modules into main testcontainers-java repo

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#564]
On reflection we feel that moving modules/third-party parts into separate Git repositories was a mistake on a few levels:

- My initial thinking was to have separate versioning for the main project and modules, but this quickly turned out to be not something people want
- The level of coordination required to synchronise version numbers and perform a synchronised release, across repos, is too much. We can automate some, but not all of the process, and edge cases really hurt us.
- This has resulted in the modules neither being released independently (freely) nor in sync - so we have the worst of both worlds, sadly.

As such, we've decided we'd like to bring all modules back in to this testcontainers-java repo.

Firstly, we need permission from the authors of each of the modules where another organisation is marked as the copyright owner. We will, of course, do whatever's right and works for all concerned. If the following people wouldn't mind making their views known I'd be most grateful.

- [x] testcontainers-java-module-vault: @mikeoswald
- [x] testcontainers-java-module-mssqlserver: @StefanHufschmidt

Then, some other challenges we want to address as part of this exercise:

- [x] How do we keep the build fast?: **Gradle build cache should help a lot (#574)**
- [x] Is Maven holding us back in keeping the build fast? **see above**
- [x] What's our release process?
- [x] How do we ensure that module owners/'authoritative people' have the right involvement in reviewing changes and deciding when to make a release?: **Github [CODEOWNERS](https://help.github.com/articles/about-codeowners/) feature will help**.
- [x] Rework to documentation (add mention of modules)

cc @kiview @bsideup

**Comment by kiview** [comment]
I've already talked to @StefanHufschmidt, this should be possible for `testcontainers-java-module-mssqlserver`.

Here are some of the current ideas we've already discussed:
- Switch to Gradle as the build system and use remote cache to speed up the build time
- Release to Bintray and mirror releases to Maven Central

Regarding the permission problem for sub-module maintainers:
Would Git sub-modules help, if we keep them up-to date automatically?

**Comment by rnorth** [comment]
Thanks :)

I'm afraid I have nightmares about submodules, so would be reluctant to involve these. Unless I'm mistaken we'd also have a problem of triggering top-level builds, as a mirror image of the problem we have of triggering builds the other way right now.

I think if there's a worry about permissions let's try it and see how things go. Module owners will hopefully continue to be involved in reviewing PRs for their area of interest, and I think we should be willing to delegate some trust accordingly...

**Comment by asafm** [comment]
You have codeowners feature of GitHub

**Comment by rnorth** [comment]
@asafm - don't know how I missed that when it was announced, but that's awesome 😀

**Comment by rnorth** [comment]
@mikeoswald would you be able to comment on whether we can bring the vault module into the main Testcontainers repo? If not, or if you need time to consider, that's OK; I can leave it unmodified and not migrate it yet.

**Comment by mikeoswald** [comment]
@rnorth Sorry about the late reply. That would be fine to move it into the main repository.

**Comment by rnorth** [comment]
Awesome, thanks @mikeoswald!

**Comment by rnorth** [comment]
Regarding release process, the bintray repository is now linked to JCenter. As I can never remember the process to wire up bintray/jcenter and maven central, @bsideup it would be good if we can perform the next release together some time..!

**Comment by bsideup** [comment]
@rnorth sure! Next release is on me :)

**Comment by rnorth** [comment]
I've mentioned the Couchbase module in #269 - I don't think we'll have time to integrate right away though.

**Comment by kiview** [comment]
@rnorth Since you've finished the acutal implementation in #607 the only thing missing from the checklist is the release process.
Is the release implicitly working right now, aligning every module to the parent version on release/publish?

**Comment by bsideup** [comment]
1.7.0 released today is a first release based on Gradle & monorepo, with all modules released at once
