### ISSUE TITLE
Current Docker Compose container is outdated; newer versions won't work with Docker for Mac

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#565]
- We currently have `docker/compose:1.8.0` as the default image we use for running Docker Compose. This image is quite outdated and doesn't support compose format v3 for example.
- #537 introduced a good general change - volume mounting in the user's `~/docker/config.json` to allow access to registry credentials

This currently _works_ with Compose 1.8.0, but upon reconfiguring TC to use a more recent version of Compose (e.g. 1.18.0) on Docker for Mac, compose will complain that the `docker-credential-osxkeychain` was not on the PATH.

The reason for this is that, with modern Docker for Mac, `~/docker/config.json` references the `docker-credential-osxkeychain` credential helper. This is fine to be used by docker/other tools running on the Mac, as they can find and execute the helper on the path. However, the compose container has no such helper installed.

To fix fully, it seems to me that we would need a way for the compose container to invoke the credential helper on the Mac side - however this would be technically fiddly and would need to be done extremely carefully so as not to create a security risk.

A shorter-term workaround is to disable Docker for Mac's `Securely store docker logins in macOS keychain`. This is obviously fairly undesirable. However, this seems to be the only way to successfully use a more up to date Docker compose image.

**Comment by kiview** [comment]
Another (hackish) workaround would be to not mount `~/docker/config.json` on OSX if the configured credential store is `docker-credential-osxkeychain`. As far as I understand, this would not break existing functionality, since the old compose container also wouldn't work with `docker-credential-osxkeychain` either.
