### ISSUE TITLE
Failure in Oracle/SQL Server modules due to useSSL query param

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#568]
After upgrading the Oracle and SQL Server modules to use 1.6.0 as their base, unfortunately we had some build failures. It seems that #561 has unfortunately led to JDBC URLs being created that Oracle and SQL Server consider invalid.

In order to progress the 1.6.0 release I'm going with an ugly but necessary workaround; overriding the `createConnection` method for these classes so that `appendDisableSslConfig` is not used.

We can come up with a cleaner workaround, but for now this works and unblocks the 1.6.0 release for these modules.

This underscores the value of having a single repository with wider tests to guard against regression, as described in #564!

**Comment by npetzall** [comment]
Is it too late to revert #561.
As this might mean that any custom built DatabaseContainers subclassing JdbcContainer now faces a breaking change.

**Comment by iNikem** [comment]
I can fix this in a week or so. Unless somebody wants to do it faster, @rnorth , can you assign this to me?

**Comment by kiview** [comment]
I think GitHub only allows assigning to Members, but I think it would be nice if you fix this 🙂

**Comment by rnorth** [comment]
Thanks @iNikem. And yes, @npetzall, you're right, this will likely be a problem for people subclassing JdbcContainer. I should have some time this evening, so will do a quick 1.6.1 release with a fix.

**Comment by npetzall** [comment]
Also note that argument separator in connectionString may differ some don't even use `?`.

**Comment by iNikem** [comment]
As the original problem was specific to MySQL I think I will rework my fix to be MySQL container specific.

**Comment by rnorth** [comment]
I've made a quick PR to resolve this without a wholesale reversion - #569. Please could you take a look and let me know if it makes sense?
