### ISSUE TITLE
[Enhancement]: Conditionally register @TestContainers

### ISSUE THREAD

**Issue by drennerpfc6** [testcontainers/testcontainers-java#5683]
### Module

Core

### Proposal

The TestcontainersExtension class is currently not public. Because of this, there is no way to conditionally apply the extension.

Consider this example

```kotlin
abstract class MyBaseTest {
    companion object {
        @JvmField
        @RegisterExtension
        val someExtension = if (someCondition) {
            TestcontainersExtension()
        } else {
            DoNothingExtension()
        }      
    }
}
```

**Comment by eddumelendez** [comment]
follow https://github.com/testcontainers/testcontainers-java/issues/2045
