### ISSUE TITLE
[Bug]: DOCKER_HOST tcp://localhost:2375 is not listening

### ISSUE THREAD

**Issue by easterwood** [testcontainers/testcontainers-java#5765]
### Module

Core

### Testcontainers version

1.17.2

### Using the latest Testcontainers version?

Yes

### Host OS

Windows with WSL2 Ubuntu

### Host Arch

x86-64

### Docker version

```shell
Client: Docker Engine - Community
Version:           20.10.17
API version:       1.41
Go version:        go1.17.11
Git commit:        100c701
Built:             Mon Jun  6 23:02:57 2022
OS/Arch:           linux/amd64
Context:           default
Experimental:      true



Server: Docker Engine - Community
Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I have a Maven project which uses testcontainers to set up several Docker containers (for my integration tests) in a WSL2 Ubuntu instance. The tests are executed via maven `mvn test`. The `docker.host` property is set to `tcp://localhost:2375` in the ` .testcontainer.properties` stored in my home directory:

```
docker.host=tcp://localhost:2375
docker.tls.verify=0
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
dockerconfig.source=auto
testcontainers.hub.image.name.prefix=https://docker-hub-mirror.server.somewhere
hub.image.name.prefix https://docker-hub-mirror.server.somewhere
ryuk.container.image = docker-hub-mirror.server.somewhere/testcontainers/ryuk:0.3.3
```
With the testcontainers version 1.17.1 everything worked fine but after switching to version 1.17.2 the error message `DOCKER_HOST tcp://localhost:2375 is not listening` appears and no container is created.

Since this error message was introduced with Issue https://github.com/testcontainers/testcontainers-java/pull/5357 I think this could be related to it.

### Relevant log output

```shell
10:20:50.419 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/Users/someone/.testcontainers.properties
10:20:50.424 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/dev/projects/integrationtests/target/classes/testcontainers.properties
10:20:50.425 [main] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
10:20:50.450 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: EnvironmentAndSystemPropertyClientProviderStrategy
10:20:50.891 [main] WARN  org.testcontainers.dockerclient.DockerClientProviderStrategy - DOCKER_HOST tcp://localhost:2375 is not listening
10:20:50.891 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - strategy EnvironmentAndSystemPropertyClientProviderStrategy did not pass the test
10:20:50.897 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: NpipeSocketClientProviderStrategy
10:20:50.897 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - DOCKER_HOST socket file '//./pipe/docker_engine' does not exist
10:20:50.897 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - strategy NpipeSocketClientProviderStrategy did not pass the test
10:20:50.902 [main] INFO  org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin, C:\windows\system32, C:\windows, C:\windows\System32\Wbem, C:\windows\System32\WindowsPowerShell\v1.0\, C:\windows\System32\OpenSSH\, C:\Program Files\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files\dotnet\, C:\Program Files\apache-maven-3.8.4\bin, C:\Program Files\nodejs\, C:\Program Files\PuTTY\, C:\Users\someone\AppData\Local\Microsoft\WindowsApps, C:\Users\someone\AppData\Local\Programs\Git\cmd, C:\Users\someone\AppData\Roaming\npm])
10:20:50.902 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
10:20:50.902 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
```

**Comment by easterwood** [comment]
Cloudfilghtio also run into this problem https://github.com/cloudflightio/dockerinwsl/issues/46

**Comment by kiview** [comment]
Hi @easterwood, thanks for the report and the investigation. Did you already try out this workaround, of using IPv6?
https://github.com/cloudflightio/dockerinwsl/issues/35#issuecomment-1192496554

And just to be clear, are you using Docker Desktop, or a Docker daemon installed within WSL2?

**Comment by easterwood** [comment]
Hi @kiview 
> Hi @easterwood, thanks for the report and the investigation. Did you already try out this workaround, of using IPv6? [cloudflightio/dockerinwsl#35 (comment)](https://github.com/cloudflightio/dockerinwsl/issues/35#issuecomment-1192496554)

That worked.

----------------

> And just to be clear, are you using Docker Desktop, or a Docker daemon installed within WSL2?

Docker daemon in WSL2

**Comment by kiview** [comment]
Thanks for trying it out @easterwood. Since I have no experience about using the Docker daemon within WSL2 without Docker Desktop, looking at this comment https://github.com/cloudflightio/dockerinwsl/issues/35#issuecomment-1209388565, I'd assume this is fixed upstream in the `dockerinwsl` distribution and Testcontainers users that want to use such a Docker setup need to apply this workaround until it is fixed in the upstream, correct?

**Comment by easterwood** [comment]
> I'd assume this is already fixed upstream in the `dockerinwsl` distribution and Testcontainers users that want to use such a Docker setup need to apply this workaround until it is updated from upstream, correct? 

I had setup the Docker daemon within WSL2 with my bare hands ;) but I think it works the same like `dockerinwsl`. The workaround seems to be good enough for now. One have to do some configuring anyway.

**Comment by kiview** [comment]
Interesting that your setup has the same behavior regarding IPv6 as the `dockerinwsl` package, I wonder why it is like that? 🤔 
Either way, happy that this configuration works 🙌
