### ISSUE TITLE
[Bug]: Logwaiting strategy not working in Windows with Podman

### ISSUE THREAD

**Issue by sureshgadupu** [testcontainers/testcontainers-java#5769]
### Module

RabbitMQ

### Testcontainers version

1.17.2

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x86

### Docker version

```shell
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.40
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: linux/amd64/fedora-36
 Podman Engine:
  Version:          4.1.1
  APIVersion:       4.1.1
  Arch:             amd64
  BuildTime:        2022-07-23T07:05:59+12:00
  Experimental:     false
  GitCommit:
  GoVersion:        go1.18.4
  KernelVersion:    5.10.102.1-microsoft-standard-WSL2
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.0, commit:
  Package:          conmon-2.1.0-2.fc36.x86_64
 OCI Runtime (crun):
  Version:          crun version 1.5
commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  Package:          crun-1.5-1.fc36.x86_64
 Engine:
  Version:          4.1.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.18.4
  Git commit:
  Built:            Sat Jul 23 07:05:59 2022
  OS/Arch:          linux/amd64
  Experimental:     false
```

### What happened?

I am trying to use Podman (version 4.2)  instead of Docker to run the tests with Testcontainers.
I am trying to start the RabbitMQ containers with following code
```
static {
        rabbitMQContainer = new RabbitMQContainer("rabbitmq:3.10.6-management-alpine")
                .withStartupTimeout(Duration.of(100, SECONDS));
        rabbitMQContainer.start();

    }
```
Testcontainer is recognizing the Podman as docker environment but failing to recognize the container strartup based on the log messages.
`org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Server startup complete.*'
`

If I switch to HostPortWaitStrategy everything works fine.

.testcontainer.properties

docker.client.strategy=org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy
DOCKER_HOST = npipe:////./pipe/podman-machine-default

### Relevant log output

```shell
07:16:15.735 [docker-java-stream--2056062630] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.wire - http-outgoing-0 << "{"cause":"using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported","message":"failed to obtain logs for Container '38555297088f5eb766b2c81e22637bb0b4581456b02422ee1cd59deb30674fdc': using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported","response":500}[\n]"

....
07:17:55.731 [main] DEBUG 🐳 [rabbitmq:3.10.6-management-alpine] - Wait strategy threw an exception
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Server startup complete.*'
```

**Comment by kiview** [comment]
Thanks for raising this issue @sureshgadupu and providing the debug output that helps look into this. Looking at this response from the `/containers/{id}/logs` Docker API endpoint (which podman-service tries to provide, and which Testcontainers accesses using [docker-java](https://github.com/docker-java/docker-java/blob/a135d21fb308014adfe3ad184557354689f528b1/docker-java-core/src/main/java/com/github/dockerjava/core/exec/LogContainerCmdExec.java#L24))
```
using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported","message":"failed to obtain logs for Container '38555297088f5eb766b2c81e22637bb0b4581456b02422ee1cd59deb30674fdc': using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported","response":500
```

, it seems the logging subsystem of your podman installation is not correctly set up. The Docker documentation explains the following constraints for usage of the logs API:
> Note: This endpoint works only for containers with the json-file or journald logging driver.

I would suggest asking the podman community how to correctly configure the log driver to allow usage of `/containers/{id}/logs`, I don't think there is anything Testcontainers can do here and it expects to interact with a Docker-compatible API.

**Comment by sureshgadupu** [comment]
Thanks for providing the explanation @kiview .
I will check with Podman community

**Comment by sureshgadupu** [comment]
I was able to resolve the issue after watching the youtube [video ](https://www.youtube.com/watch?v=iOxILJIYsuY).

After setting events-backend to k8s-file in /usr/share/containers/container.conf file in virtual machine my tests are running fine.

If you are using Podman version 4.2, no need to change cgroup-manager option
