### ISSUE TITLE
[Bug]: DockerComposeContainer.getContainerByServiceName not working as expectd

### ISSUE THREAD

**Issue by BarkingBad** [testcontainers/testcontainers-java#5773]
### Module

Core

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS 12.4 (21F79)

### Host Arch

ARM (M1)

### Docker version

```shell
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I wanted to use function `getContainerByServiceName` to obtain `ContainerState` for further processing. The function mentioned earlier accepts the parameter called `serviceName`. The very same parameter name is used for e.g. `getServicePort` function. The name I used for the service was without any `_[0-9]+` suffix. For `getServicePort` it worked just fine: I got my desired port number, however, for `getContainerByServiceName` I was getting an empty `Option`. After a quick investigation, it turned out that for `getContainerByServiceName` I need to provide `_1` suffix. 

Desired behaviour:

- reuse the internal code that was checking if the name is with suffix also for `getContainerByServiceName` (I've seen in sources you have such logic somewhere for `getServicePort`) and appending it if it is missing, or...
- if it is intended, maybe the Javadoc for that function should be updated to warn users about that pitfall

**Comment by REslim30** [comment]
I can take a look at this one
