### ISSUE TITLE
[Bug]: Cannot run mariadb container on Apple Silicon (M1)

### ISSUE THREAD

**Issue by dgm90** [testcontainers/testcontainers-java#5781]
### Module

MariaDB

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

ARM

### Docker version

```shell
❯ docker version
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

In my unit tests I use `testacontainers/mariadb`, that doesn't support ARM architecture. 
I've checked the base image and it [uses the tag `10.3.6`](https://github.com/testcontainers/testcontainers-java/blob/master/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java#L18), which is `linux/amd64` (see [link](https://hub.docker.com/layers/library/mariadb/10.3.6/images/sha256-ab3aab60f76b6d2d2e2d9d2c486029b63ad7cc9517ad4567a27c66999f8a23ce?context=explore)).
I can see that ARM is supported in versions, starting from `10.3.8`.
Please update the base image so that people can use this container in their tests on macs with M1 chip. 

Here are the logs that I see just after the container is started.

### Relevant log output

```shell
runtime stack:
runtime.throw(0x4cb21f, 0x9)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc42002a000, 0xc420039fc0)
        /usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
        /usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
        /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760
runtime.main()
        /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0
```
```


### Additional Information

_No response_

**Comment by eddumelendez** [comment]
Hi @dgm90, we are deprecating the use of `new MariaDBContainer()` due to the attachments to a specific image version. Instead, we recommend the use of `new MariaDBContainer("mariadb:10.3.8")`.
