### ISSUE TITLE
[Bug] GenericContainer doesn’t properly split commands

### ISSUE THREAD

**Issue by dhoard** [testcontainers/testcontainers-java#5784]
### Module

Core

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

ALL

### Host Arch

ALL

### Docker version

```shell
N/A
```

### What happened?

GenericContainer `setCommand` uses Java String `split` to build the array of command parts. If the command contains quoted arguments/quoted arguments with escaped quotes, the container fails.

Example command:

/bin/sh test.sh “argument 1” “argument 2”

**Comment by hariohmprasath** [comment]
Hi @dhoard, 
Container.java also provides another version of `setCommand` method that allows sending in an array directly

Method signature:
```java
void setCommand(@NonNull String... commandParts);
```

Example usage:
```java
setCommand("--display=true", "-driver=\"kernel-4.0 kernel-4.1\"");
```

Will this work?

**Comment by dhoard** [comment]
@hariohmprasath sure, that method is a workaround if the parts are already split.

In my scenario, I am reading a complex/quoted command line from a file. Ideally, I should be able to pass the whole command line to `setCommand(String command)` as is.

**Comment by REslim30** [comment]
Hey @dhoard. Thanks for reporting this. This is a valid use case and it's no surprise that users would expect that `setCommand(String command)` to split a command properly as a normal command. Handling quotes `"` and `'` can be done at a fairly low cost. But there are complications around escaped quotes.

From an [SO post](https://stackoverflow.com/questions/3259143/split-a-string-containing-command-line-parameters-into-a-string-in-java/28640859#28640859):
> As documentation, translateCommandline handles both single and double quoted strings and escapes within them but does not recognize backslash in the same way as a POSIX shell because of problems that causes on DOS based systems.

I think POSIX based commands are different from DOS based commands. Though, I think it should be fine to assume POSIX based commands as docker containers are linux based. Though, there might be use cases where one might expect to run a DOS based command? I think a bit more time is required to think through this problem.

In the meantime, as a workaround - would it be possible to use one of the solutions on this [SO post](https://stackoverflow.com/questions/3259143/split-a-string-containing-command-line-parameters-into-a-string-in-java/28640859#28640859) and then passing into the alternate method `setCommand(String... commandParts)`?

**Comment by dhoard** [comment]
@REslim30 Thanks for the insight. I can see where non-POSIX commands could be a probably.

I currently have a workaround in place, so it's not blocking me.

**Comment by REslim30** [comment]
On the [dockerfile docs](https://docs.docker.com/engine/reference/builder/#run), there seems to be mention of windows containers:

> RUN <command> (shell form, the command is run in a shell, which by default is /bin/sh -c on Linux or cmd /S /C on Windows)

Will investigate further...

**Comment by REslim30** [comment]
I believe Windows containers on windows (WCOW) isn't currently supported on Test containers from this issue. That work is currently being done to support it as per https://github.com/testcontainers/testcontainers-java/issues/5621.

**Comment by dhoard** [comment]
I feel that a better approach than `withPosixCommand` and `withWindowsCommand` would be something like the following...

```
public SELF withCommand(String cmd, Function<String, String[]> cmdProcessor) {
    withCommand(cmdProcessor.apply(cmd));
    return this;
}
```  

```
public class CommandProcessor {

    public static final Function<String, String[]> POSIX = new Posix();
    public static final Function<String, String[]> WINDOWS = new Windows();

    public static class Posix implements Function<String, String[]> {

        @Override
        public String[] apply(String s) {
            // TODO
            return null;
        }
    }

    public static class Windows implements Function<String, String[]> {

        @Override
        public String[] apply(String s) {
            // TODO
            return null;
        }
    }
}
```

Example usages:

```
GenericContainer genericContainer = new GenericContainer();
genericContainer.withCommand("testing 1 2 4", CommandProcessor.POSIX);
```

```
GenericContainer genericContainer = new GenericContainer();
genericContainer.withCommand("testing 1 2 4", CommandProcessor.WINDOWS);
```

This would also allow a developer to provide a custom command processor to split commands, replace values in a command, validate command format, build dynamic commands, etc.

**Comment by REslim30** [comment]
@dhoard I like that suggestion. I think that provides good flexibility and is open to extension.

But I think at this stage we should extend the current `withCommand(String)` method, and assume that most of our users will be using linux containers (since windows containers is not supported currently). And in future, if windows containers become a thing or a certain linux distro splits commands differently, we can deprecate `withCommand(String)` and go with a style similar to what you suggested. This way we have a better understanding of the different ways a command line string can be split and we don't add a new public api that we have to support that might be the wrong abstraction.

**Comment by REslim30** [comment]
It actually might be a shell thing. From `man bash`

```
DEFINITIONS
       The following definitions are used throughout the rest of this document.
       blank  A space or tab.
       word   A sequence of characters considered as a single unit by the shell.  Also known as a token.
       name   A word consisting only of alphanumeric characters and underscores, and beginning with an alphabetic character or an underscore.  Also referred to as an iden-
              tifier.
       metacharacter
              A character that, when unquoted, separates words.  One of the following:
              |  & ; ( ) < > space tab newline
```

**Comment by eddumelendez** [comment]
Sorry for the late reply but something like this should work `withCommand("sh", "-c", "this is my command, a large one)`

**Comment by dhoard** [comment]
> Sorry for the late reply but something like this should work `withCommand("sh", "-c", "this is my command, a large one)`

@eddumelendez agreed... and the approach I took.

The lack of support for quoted arguments when using `setCommand(String)` / `withCommand(String)` is not intuitive.

Wwould you accept a Javadoc PR to make this more apparent?

**Comment by eddumelendez** [comment]
I think an improvement in our [docs](https://java.testcontainers.org/features/commands/) make sense. Please, take into account the code snippets in our docs are concentre test examples. PR is welcome :)

**Comment by eddumelendez** [comment]
Closing as this one was solved. PR for docs is welcome.
