### ISSUE TITLE
[Bug]: MongoDbContainer uses unknown command while spinup

### ISSUE THREAD

**Issue by R4V3NN0** [testcontainers/testcontainers-java#5818]
### Module

MongoDB

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

64 Bit 

### Docker version

```shell
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

While testing, the MongoDbContainer cant be spinned up, while our normal deployment with docker compose works fine. 

It seems like Testcontainers is using an unknown command while starting the docker container so it crashes immedietly. Other containers like kubemq which are spinned up work perfectly fine, so its just a problem with the MongoDbContainer. 

Im not sure if this a bug but we didnt changed anything at the configuration and 3 weeks before everything worked. Now Im back from vacation and MongoDb crashes. I added a lot of additional information at the end.

### Relevant log output

```shell
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at de.neusta.wasmuthproxy.utility.MongoResource.start(MongoResource.java:31)
	at io.quarkus.test.common.TestResourceManager.lambda$start$0(TestResourceManager.java:118)
	... 5 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	... 8 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 9 more
Caused by: org.testcontainers.containers.MongoDBContainer$ReplicaSetInitializationException: An error occurred: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown

	at org.testcontainers.containers.MongoDBContainer.checkMongoNodeExitCode(MongoDBContainer.java:97)
	at org.testcontainers.containers.MongoDBContainer.initReplicaSet(MongoDBContainer.java:132)
	at org.testcontainers.containers.MongoDBContainer.containerIsStarted(MongoDBContainer.java:86)
	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:688)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:504)
	... 11 more
```

### Configuration from our Testcontainer Resource ( we are working with Quarkus ) 

```
package de.utility;

import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;
import java.util.Map;
import org.apache.groovy.util.Maps;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.MongoDBContainer;
import org.testcontainers.junit.jupiter.Container;

public class MongoResource implements QuarkusTestResourceLifecycleManager {

    //CHECKSTYLE:OFF
    @Container
    static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:6.0.1")
            .withEnv("MONGO_INITDB_ROOT_USERNAME", "mongoadmin")
            .withEnv("MONGO_INITDB_ROOT_PASSWORD", "secret")
            .withEnv("MONGO_INITDB_DATABASE", "tarif_db")
            .withEnv("MONGO_INITDB_USER", "user")
            .withEnv("MONGO_INITDB_PASSWORD", "secret")
            .withEnv("MONGO_INITDB_LB_USER", "lb_user")
            .withEnv("MONGO_INITDB_LB_PASSWORD", "secret")
            .withClasspathResourceMapping("db/mongo-init.sh",
                    "/docker-entrypoint-initdb.d/mongo-init.sh",
                    BindMode.READ_ONLY)
            .withExposedPorts(27017)
            .withCommand("--auth");
    //CHECKSTYLE:ON

    @Override
    public Map<String, String> start() {
        MongoResource.mongoDBContainer.start();

        return Maps.of("quarkus.mongodb.connection-string", "mongodb://" + MongoResource.mongoDBContainer.getContainerIpAddress() + ":" + MongoResource.mongoDBContainer.getFirstMappedPort() + "/?uuidRepresentation=STANDARD",
                "quarkus.mongodb.credentials.username", MongoResource.mongoDBContainer.getEnvMap().get("MONGO_INITDB_USER"),
                "quarkus.mongodb.credentials.password", MongoResource.mongoDBContainer.getEnvMap().get("MONGO_INITDB_PASSWORD"),
                "quarkus.mongodb.database", MongoResource.mongoDBContainer.getEnvMap().get("MONGO_INITDB_DATABASE"),
                "liquibase.mongodb.connection-string", "mongodb://" + MongoResource.mongoDBContainer.getContainerIpAddress() + ":" + MongoResource.mongoDBContainer.getFirstMappedPort() + "/" + MongoResource.mongoDBContainer.getEnvMap().get("MONGO_INITDB_DATABASE"));
    }

    @Override
    public void stop() {
        MongoResource.mongoDBContainer.stop();
    }


}
```

### IntelliJ Logs

Sept. 02, 2022 10:47:10 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
Sept. 02, 2022 10:47:10 AM io.quarkus.agroal.deployment.AgroalProcessor build
WARN: The Agroal dependency is present but no JDBC datasources have been defined.
2022-09-02 10:46:58,032 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2022-09-02 10:46:58,550 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine)
2022-09-02 10:46:58,552 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Docker host IP address is localhost
2022-09-02 10:46:58,591 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Connected to docker: 
  Server Version: 20.10.17
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 25500 MB
2022-09-02 10:46:58,594 INFO  [org.tes.uti.ImageNameSubstitutor] (pool-3-thread-1) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2022-09-02 10:46:59,937 INFO  [org.tes.uti.RegistryAuthLocator] (pool-3-thread-1) Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2022-09-02 10:47:00,615 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2022-09-02 10:47:00,615 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Checking the system...
2022-09-02 10:47:00,617 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker server version should be at least 1.6.0
2022-09-02 10:47:00,698 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker environment should have more than 2GB free disk space
2022-09-02 10:47:00,712 INFO  [🐳 .0.1]] (pool-3-thread-1) Creating container for image: mongo:6.0.1
2022-09-02 10:47:00,712 INFO  [🐳 .2.13]] (pool-3-thread-2) Creating container for image: kubemq/kubemq:v2.2.13
2022-09-02 10:47:00,821 INFO  [🐳 .2.13]] (pool-3-thread-2) Starting container with ID: 20adaa5d70efc90ec9413671b89d1f755294a5bbaffd18f5b32a06d8f94e0850
2022-09-02 10:47:01,654 INFO  [🐳 .0.1]] (pool-3-thread-1) Starting container with ID: 373b579d4e819d1d4d12aed10a585270476ae48faefcc487b1ed00b8b2ff36d2
2022-09-02 10:47:04,079 INFO  [🐳 .2.13]] (pool-3-thread-2) Container kubemq/kubemq:v2.2.13 is starting: 20adaa5d70efc90ec9413671b89d1f755294a5bbaffd18f5b32a06d8f94e0850
2022-09-02 10:47:04,167 INFO  [🐳 .0.1]] (pool-3-thread-1) Container mongo:6.0.1 is starting: 373b579d4e819d1d4d12aed10a585270476ae48faefcc487b1ed00b8b2ff36d2
2022-09-02 10:47:05,185 INFO  [🐳 .0.1]] (pool-3-thread-1) Container mongo:6.0.1 started in PT4.4865833S
2022-09-02 10:47:07,033 INFO  [🐳 .2.13]] (pool-3-thread-2) Container kubemq/kubemq:v2.2.13 started in PT6.3346873S
2022-09-02 10:47:07,095 ERROR [org.tes.con.MongoDBContainer] (pool-3-thread-1) An error occurred: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown

2022-09-02 10:47:07,095 ERROR [🐳 .0.1]] (pool-3-thread-1) Could not start container: org.testcontainers.containers.MongoDBContainer$ReplicaSetInitializationException: An error occurred: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown

2022-09-02 10:47:07,155 ERROR [🐳 .0.1]] (pool-3-thread-1) Log output from the failed container:
about to fork child process, waiting until server is ready for connections.
forked process: 30

### Logs from Container

{"t":{"$date":"2022-09-02T08:47:04.285+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"-","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2022-09-02T08:47:04.286+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"-","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2022-09-02T08:47:04.290+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}
{"t":{"$date":"2022-09-02T08:47:04.292+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2022-09-02T08:47:04.295+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","namespace":"config.tenantMigrationDonors"}}
{"t":{"$date":"2022-09-02T08:47:04.295+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","namespace":"config.tenantMigrationRecipients"}}
{"t":{"$date":"2022-09-02T08:47:04.295+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"ShardSplitDonorService","namespace":"config.tenantSplitDonors"}}
{"t":{"$date":"2022-09-02T08:47:04.296+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
{"t":{"$date":"2022-09-02T08:47:04.296+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":30,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"373b579d4e81"}}
{"t":{"$date":"2022-09-02T08:47:04.297+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"6.0.1","gitVersion":"32f0f9c88dc44a2c8073a5bd47cf779d4bfdee6b","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2022-09-02T08:47:04.297+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
{"t":{"$date":"2022-09-02T08:47:04.297+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"127.0.0.1","port":27017,"tls":{"mode":"disabled"}},"processManagement":{"fork":true,"pidFilePath":"/tmp/docker-entrypoint-temp-mongod.pid"},"systemLog":{"destination":"file","logAppend":true,"path":"/proc/1/fd/1"}}}}
{"t":{"$date":"2022-09-02T08:47:04.298+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
{"t":{"$date":"2022-09-02T08:47:04.298+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=12238M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,remove=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=2000),statistics_log=(wait=0),json_output=(error,message),verbose=[recovery_progress:1,checkpoint_progress:1,compact_progress:1,backup:0,checkpoint:0,compact:0,evict:0,history_store:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],"}}
{"t":{"$date":"2022-09-02T08:47:04.904+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":606}}
{"t":{"$date":"2022-09-02T08:47:04.904+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2022-09-02T08:47:04.946+00:00"},"s":"I",  "c":"WT",       "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":true}}
{"t":{"$date":"2022-09-02T08:47:04.968+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
{"t":{"$date":"2022-09-02T08:47:04.969+00:00"},"s":"W",  "c":"CONTROL",  "id":22178,   "ctx":"initandlisten","msg":"/sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'","tags":["startupWarnings"]}
{"t":{"$date":"2022-09-02T08:47:04.969+00:00"},"s":"W",  "c":"CONTROL",  "id":5123300, "ctx":"initandlisten","msg":"vm.max_map_count is too low","attr":{"currentValue":65530,"recommendedMinimum":1677720,"maxConns":838860},"tags":["startupWarnings"]}
{"t":{"$date":"2022-09-02T08:47:04.969+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"admin.system.version","uuidDisposition":"provided","uuid":{"uuid":{"$uuid":"1af7eb32-2961-4d12-ba0d-084c07726dca"}},"options":{"uuid":{"$uuid":"1af7eb32-2961-4d12-ba0d-084c07726dca"}}}}
{"t":{"$date":"2022-09-02T08:47:04.998+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"collectionUUID":{"uuid":{"$uuid":"1af7eb32-2961-4d12-ba0d-084c07726dca"}},"namespace":"admin.system.version","index":"_id_","ident":"index-1-1765000806655325157","collectionIdent":"collection-0-1765000806655325157","commitTimestamp":null}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"REPL",     "id":20459,   "ctx":"initandlisten","msg":"Setting featureCompatibilityVersion","attr":{"newVersion":"6.0"}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersion":"6.0","context":"setFCV"}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":17,"maxWireVersion":17},"outgoing":{"minWireVersion":17,"maxWireVersion":17},"isInternalClient":true}}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":17,"maxWireVersion":17},"outgoing":{"minWireVersion":17,"maxWireVersion":17},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":17,"maxWireVersion":17},"outgoing":{"minWireVersion":17,"maxWireVersion":17},"isInternalClient":true}}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersion":"6.0","context":"startup"}}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
{"t":{"$date":"2022-09-02T08:47:04.999+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
{"t":{"$date":"2022-09-02T08:47:05.000+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
{"t":{"$date":"2022-09-02T08:47:05.001+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"local.startup_log","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"7d114a09-f4c4-4d32-b7bb-5866c1e884b7"}},"options":{"capped":true,"size":10485760}}}
{"t":{"$date":"2022-09-02T08:47:05.032+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"collectionUUID":{"uuid":{"$uuid":"7d114a09-f4c4-4d32-b7bb-5866c1e884b7"}},"namespace":"local.startup_log","index":"_id_","ident":"index-3-1765000806655325157","collectionIdent":"collection-2-1765000806655325157","commitTimestamp":null}}
{"t":{"$date":"2022-09-02T08:47:05.032+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}}
{"t":{"$date":"2022-09-02T08:47:05.032+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
{"t":{"$date":"2022-09-02T08:47:05.034+00:00"},"s":"I",  "c":"CONTROL",  "id":20712,   "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"NamespaceNotFound: config.system.sessions does not exist"}}
{"t":{"$date":"2022-09-02T08:47:05.035+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"LogicalSessionCacheRefresh","msg":"createCollection","attr":{"namespace":"config.system.sessions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"8a3e01ff-4a74-48d9-9460-5267af4b83ab"}},"options":{}}}
{"t":{"$date":"2022-09-02T08:47:05.035+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
{"t":{"$date":"2022-09-02T08:47:05.035+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"127.0.0.1"}}
{"t":{"$date":"2022-09-02T08:47:05.035+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
child process started successfully, parent exiting
{"t":{"$date":"2022-09-02T08:47:05.082+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"collectionUUID":{"uuid":{"$uuid":"8a3e01ff-4a74-48d9-9460-5267af4b83ab"}},"namespace":"config.system.sessions","index":"_id_","ident":"index-5-1765000806655325157","collectionIdent":"collection-4-1765000806655325157","commitTimestamp":null}}
{"t":{"$date":"2022-09-02T08:47:05.082+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"collectionUUID":{"uuid":{"$uuid":"8a3e01ff-4a74-48d9-9460-5267af4b83ab"}},"namespace":"config.system.sessions","index":"lsidTTLIndex","ident":"index-6-1765000806655325157","collectionIdent":"collection-4-1765000806655325157","commitTimestamp":null}}
{"t":{"$date":"2022-09-02T08:47:06.440+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:60726","uuid":"7b54767b-eb19-45b4-9781-ede7007027ef","connectionId":1,"connectionCount":1}}
{"t":{"$date":"2022-09-02T08:47:06.446+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"127.0.0.1:60726","client":"conn1","doc":{"driver":{"name":"nodejs|mongosh","version":"4.8.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"Node.js v16.16.0, LE (unified)","version":"4.8.1|1.5.4","application":{"name":"mongosh 1.5.4"}}}}
{"t":{"$date":"2022-09-02T08:47:06.467+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:60728","uuid":"e1e88084-61dd-4178-ba15-46848da5ec2d","connectionId":2,"connectionCount":2}}
{"t":{"$date":"2022-09-02T08:47:06.467+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:60730","uuid":"d7045c11-53d8-406e-9201-9e3f9ad527fc","connectionId":3,"connectionCount":3}}
{"t":{"$date":"2022-09-02T08:47:06.469+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"127.0.0.1:60728","client":"conn2","doc":{"driver":{"name":"nodejs|mongosh","version":"4.8.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"Node.js v16.16.0, LE (unified)","version":"4.8.1|1.5.4","application":{"name":"mongosh 1.5.4"}}}}
{"t":{"$date":"2022-09-02T08:47:06.470+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"127.0.0.1:60730","client":"conn3","doc":{"driver":{"name":"nodejs|mongosh","version":"4.8.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"Node.js v16.16.0, LE (unified)","version":"4.8.1|1.5.4","application":{"name":"mongosh 1.5.4"}}}}
{"t":{"$date":"2022-09-02T08:47:06.474+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:60732","uuid":"4ff6a303-55d4-49b2-a95c-403ae9932600","connectionId":4,"connectionCount":4}}
{"t":{"$date":"2022-09-02T08:47:06.479+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"127.0.0.1:60732","client":"conn4","doc":{"driver":{"name":"nodejs|mongosh","version":"4.8.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"Node.js v16.16.0, LE (unified)","version":"4.8.1|1.5.4","application":{"name":"mongosh 1.5.4"}}}}
{"t":{"$date":"2022-09-02T08:47:06.868+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"127.0.0.1:60726","uuid":"7b54767b-eb19-45b4-9781-ede7007027ef","connectionId":1,"connectionCount":3}}
{"t":{"$date":"2022-09-02T08:47:06.869+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn4","msg":"Connection ended","attr":{"remote":"127.0.0.1:60732","uuid":"4ff6a303-55d4-49b2-a95c-403ae9932600","connectionId":4,"connectionCount":2}}
{"t":{"$date":"2022-09-02T08:47:06.869+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn3","msg":"Connection ended","attr":{"remote":"127.0.0.1:60730","uuid":"d7045c11-53d8-406e-9201-9e3f9ad527fc","connectionId":3,"connectionCount":1}}
{"t":{"$date":"2022-09-02T08:47:06.869+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"127.0.0.1:60728","uuid":"e1e88084-61dd-4178-ba15-46848da5ec2d","connectionId":2,"connectionCount":0}}

**Comment by emmanuel099** [comment]
Support for MongoDB 6 has recently been added to Testcontainers, see https://github.com/testcontainers/testcontainers-java/pull/5771 (not released yet).

**Comment by R4V3NN0** [comment]
Oh okay. Thanks for the help. I think this bug ticket is now unnecessary so Im going to close it
