### ISSUE TITLE
[Feature]: Support for AWS Dynamodb

### ISSUE THREAD

**Issue by hariohmprasath** [testcontainers/testcontainers-java#5823]
### Module

New Module

### Problem

Dynamodb is one of the popular key-value store used to build scalable enterprise applications. Currently AWS supports a light weight version of Dynamodb that can run inside a container, as a developer I would love to test my code using the local version (with no additional cost) then deploy the code to containers running in cloud.

If you team approves this support, I would be more than happy to send a PR, please let me know

### Solution

Add support for Dynamodb in testcontainers

### Benefit

With this support, developers can run their integration tests using local containers instead of running them in cloud. Developers can use the same approach to develop and test their code locally (for free) before deploying them in cloud

### Alternatives

Connect to Dynamodb using AWS Cloud API's with actual credentials.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @hariohmprasath ! Thanks, but unfortunately, similar to #4663 #5681 we are not considering publishing a specific dynamodb module because Testcontainers already provides a [LocalStack](https://www.testcontainers.org/modules/localstack/) which offers DynamoDB.

**Comment by hariohmprasath** [comment]
> Hi @hariohmprasath ! Thanks, but unfortunately, similar to #4663 #5681 we are not considering publishing a specific dynamodb module because Testcontainers already provides a [LocalStack](https://www.testcontainers.org/modules/localstack/) which offers DynamoDB.

Got it, I should have checked the support for LocalStack before submitting this. Thanks for letting me know.
