### ISSUE TITLE
[Bug]: Redis Connection refused

### ISSUE THREAD

**Issue by vasusethia1** [testcontainers/testcontainers-java#5861]
### Module

Core

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Hi All, I am trying to run my integration tests for the redis but I am getting connection refused while querying the container. Following is the way I am doing 

 public static final DockerImageName REDIS_IMAGE = DockerImageName.parse("redis:5.0");

    @Container
    public static GenericContainer<?> redis = new GenericContainer<>(REDIS_IMAGE)
            .withFileSystemBind("src/test/resources/dump.rdb", "/var/lib/redis")
            .waitingFor(Wait.forLogMessage(".*Ready to accept connections.*\\n", 1));

### Relevant log output

```shell
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused
```

**Comment by bsideup** [comment]
Not a bug. See https://www.testcontainers.org/features/networking/#exposing-container-ports-to-the-host
