### ISSUE TITLE
Testcontainers for .net/.net-core

### ISSUE THREAD

**Issue by jehof** [testcontainers/testcontainers-java#587]
I have heared a talk about testcontainers at the DevOps Gathering 2018 and I was excited, cause this is what I am currently doing for our own integration tests in a similar way. But I am working on the .net/.net-core plattform. I have not found a tool or component, other than the [.NET Client for Docker Remote API](https://github.com/Microsoft/Docker.DotNet) to support me in setting up docker containers for our integration tests.

So are there any plans to provide an official port of testcontainers for the .net universe? I am really interested to get this ready for .net and also would like to contribute to this.

**Comment by bsideup** [comment]
Hi @jehof,

I have two good news for you:
1) Yes, we consider extending it to other platforms. No estimates or timeline yet, but we have some ideas how to do that with minimal effort
2) @swissarmykirpan has something to say & share I think ;)

**Comment by swissarmykirpan** [comment]
Hi @jehof I am currently working on this, and have got a basic implementation working already.

Is there a specific way in which you would like to use this?
Any specific docker images you want to be able to use immediately?

**Comment by jehof** [comment]
@swissarmykirpan This is a broad question, but I try to explain it with our current process.

We ran our integration tests with xUnit Framework and setup/teardown the docker containers in `CollectionFixtures ` with the **.NET Client for Docker Remote API**. The tests are run on our local developer machines with Visual Studio/Resharper or using the CLI (`dotnet test`). Developer machines have "Docker for Windows CE" installed (named pipe). Our build agent (Bamboo) runs the integration tests using a Command Task (`dotnet test`) and Docker API is accessed through URL (127.0.0.1:2375)

Docker images we are currently using are
- microsoft/mssql-server-linux
- mongo
- rabbitmq
- our own service images (through Dockerfile)

Does this answer your questions?

**Comment by Frank591** [comment]
Hello. 
I heard about the Testcontainers on one conference, and i am very impressed this project. But unfortunately my main lang now is C#. So i want to try to port Testcontainers on netcore. 
My goals: run containers like postgres, rabbitMq, nginx with waitAll functionality  from xUnit and NUnit tests. Can you tell me what classes/packages i should port first for that?
PS Sorry for my bad English

**Comment by kiview** [comment]
Hi @Frank591, cool that you like the concept :slightly_smiling_face: 
Currently @swissarmykirpan is working on a .net port, you can find it here:
https://github.com/testcontainers/testcontainers-dotnet

Maybe you can get in touch if are interested in contributing?

**Comment by Frank591** [comment]
@kiview , thanks for answer. I will try to see https://github.com/testcontainers/testcontainers-dotnet, may be i will join to work inside this repositiry.  But can you give me answer on my question "what classes/packages i should port first", because may be i will start my own port?

**Comment by kiview** [comment]
I would kindly to suggest to talk to @swissarmykirpan and look into the repo before thinking to create your own port :slightly_smiling_face: 

However, if you want to try out some things, `GenericContainer` and stuff like `WaitStrategy` would be good starting points.

**Comment by bsideup** [comment]
I would say that env detection is the hardest part :D

**Comment by franck-schmidlin** [comment]
@swissarmykirpan : what is the status of https://github.com/testcontainers/testcontainers-dotnet, ? is the current version, last publish last summer, usable?

**Comment by swissarmykirpan** [comment]
@franck-schmidlin it is useable, i've got a number of projects that are using it.
