### ISSUE TITLE
Oracle Connection String is not accepted by JDBC Container

### ISSUE THREAD

**Issue by manikmagar** [testcontainers/testcontainers-java#596]
Container Database Driver is matching the connection url against a [regex pattern](https://github.com/testcontainers/testcontainers-java/blob/master/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L40) - `jdbc:tc:([a-z]+)(:([^:]+))?://[^\\?]+(\\?.*)?` .

This is not accepting Oracle JDBC Connection String of the format - `jdbc:oracle:thin:@myhost:1521:orcl`

This is preventing to use Oracle container with JDBC URL.

**Comment by MenadKADDOUR** [comment]
Hi Guys,

I've this exact issue, using testContainer, is that fixed actually?

Thank for your help
