### ISSUE TITLE
[Enhancement]: Upgrade mockserver-client-java and fix MockServerContainerRuleTest

### ISSUE THREAD

**Issue by eddumelendez** [testcontainers/testcontainers-java#5975]
### Module

MockServer

### Proposal

# Context:

`MockServerContainerRuleTest` fails when upgrading to `5.14.0`. It is recommended to use the same server and client version. Currently, `MockServerContainerTest` uses `MockServerClient.class.getPackage().getImplementationVersion()` to get the version and use it as a tag in the docker image. This approach is different from `MockServerContainerRuleTest` and that’s why it fails.

# Proposal:

Read `MockServerClient.class.getPackage().getImplementationVersion()` and use it as a part of the tag in `MockServerContainerRuleTest`. Use image `mockserver/mockserver`

**Comment by sivaprasadreddy** [comment]
Hi @eddumelendez 
With 'org.mock-server:mockserver-client-java:5.14.0' dependency the `MockServerClient.class.getPackage().getImplementationVersion()` returns `5.14.0` but there is no `jamesdbloom/mockserver` docker image published with `5.14.0` tag yet (https://hub.docker.com/r/jamesdbloom/mockserver/tags).

**Comment by eddumelendez** [comment]
@sivaprasadreddy thanks! I've updated the description in order to use `mockserver/mockserver`

**Comment by sivaprasadreddy** [comment]
@eddumelendez Created a PR https://github.com/testcontainers/testcontainers-java/pull/5977
