### ISSUE TITLE
[Enhancement]: Publish the official Ryuk image also on AWS Public ECR

### ISSUE THREAD

**Issue by thomasdac** [testcontainers/testcontainers-java#6001]
### Module

Core

### Proposal

**Describe the enhancement request**
Publish the official Ryuk image also on AWS Public ECR.

**What you are trying to do**
My company uses AWS as its cloud environment. Our applications use TestContainers for tests. Docker Hub has a limit of 100 images downloaded per IP for anonymous users every 6 hours, and we have some limitations for using TestContainers with credentials in a GitHub action.

**The solution you'd like**
Download the Ryuk image from AWS ECR public registry, bypassing DockerHub limits and saving network bandwidth, as the machines running the test will be in the same region.

**Describe alternatives you've considered**
1 - Publish my own unofficial Ryuk image. However, it would become outdated in relation to the official image over time.
2 - Use authentication on TestContainers to get a limit of 200 images every 6 hours. As I said, we have some limitations in using credentials in GitHub actions and, even so, the limit of 200 is not enough for our use. In addition to this technical limitation, our company already uses the AWS image registry, which makes it impossible to acquire a subscription on DockerHub for images used in tests.

**Comment by bsideup** [comment]
1. Ryuk (and other images in our org) is excluded from the limits as a Sponsored OSS org: https://hub.docker.com/u/testcontainers
2. you can use ECR as a mirror: https://docs.docker.com/registry/recipes/mirror/
3. Last but not least, see this page for more options: https://www.testcontainers.org/features/image_name_substitution/
