### ISSUE TITLE
Disable request for volume sharing in Windows 10

### ISSUE THREAD

**Issue by 1605200517** [testcontainers/testcontainers-java#602]
Let's consider a simple test on Windows 10 with `testcontainers-1.6.0` which looks like the following:

```
public class FoobarTest {

	@ClassRule
	public static GenericContainer<?> broker = new GenericContainer<>("ubuntu:latest").withExposedPorts(80);
	
	@Test
	public void returnsRealFoo() {
		assertTrue(true);
	}
}
```

Then on test execution, Docker displays a pop up and asks for granting access to disk `C:`.

Why? How can I disable it?

**Comment by kiview** [comment]
Are you really using Docker Toolbox or are you using Docker for Windows?
At least Docker for Windows will automatically ask for this permission, once the Docker daemon tries to access something on the Windows Host filesystem.
Testcontainers runs some pre-flight checks (like checking if files can be mounted), so this will lead this popup. 

Here you can see how to disable the preflight checks:
https://www.testcontainers.org/usage/properties.html

**Comment by 1605200517** [comment]
The setting does not seem to activate (tried both class path - Eclipse project root - and the user home dir; there was even a file created by the plugin; adding the switch there did not work out either.)

**Comment by rnorth** [comment]
@bsideup I think we need to tweak how the Ryuk container gets started up according to this setting. Unfortunately the mount is set up regardless of whether it's going to be tested at present:
```java
new Bind(mountableFile.getResolvedPath(), new Volume("/dummy"), AccessMode.ro)
```

**Comment by bsideup** [comment]
@rnorth yes, already on my list

**Comment by bsideup** [comment]
Should be fixed by this PR:
https://github.com/testcontainers/testcontainers-java/pull/604

**Comment by kiview** [comment]
I'll try to verify this on Windows 10 (@1605200517 or would you like to check with a current jitpack snapshot release?)

**Comment by 1605200517** [comment]
go on, I am yet new to jitpack :)

**Comment by 1605200517** [comment]
@kiview  so I tried [the Jitpack example](https://github.com/testcontainers/testcontainers-java-examples) but tests fail there, added another issue.

https://github.com/testcontainers/testcontainers-java-examples/issues/12

**Comment by kiview** [comment]
Hey @1605200517, can you please clarify? Is it working for you now or not? :wink:

**Comment by 1605200517** [comment]
yes, it works! thanks
