### ISSUE TITLE
FixedHostPortGenericContainer not exposing ports

### ISSUE THREAD

**Issue by estebangarcia** [testcontainers/testcontainers-java#603]
Hi all,

I'm trying to run a container on my tests by doing:
```
@ClassRule
    public static GenericContainer pulsar = new FixedHostPortGenericContainer("apachepulsar/pulsar:1.21.0-incubating")
            .withFixedExposedPort(6650,6650)
            .withFixedExposedPort(8080,8080)
            .withCommand("bin/pulsar standalone --advertised-address 127.0.0.1");
```

The container starts but no ports are mapped.

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                  PORTS                     NAMES
c5c59331ac58        apachepulsar/pulsar:1.21.0-incubating   "bin/pulsar standalo…"   1 second ago        Up Less than a second                             zealous_kare
0edbbcbd1fd0        bsideup/moby-ryuk:0.2.2                 "/app"                   1 second ago        Up 1 second             0.0.0.0:32820->8080/tcp   testcontainers-ryuk-cb21d3ce-571a-4854-8e87-8d9b3dbc30bd
```

Any ideas on why?

Thanks

**Comment by bsideup** [comment]
Hi @estebangarcia,

Does the image have those ports exposed? Have you tried to expose them in addition to the mapping?

**Comment by estebangarcia** [comment]
Hi @bsideup,

Thanks for your response. No, the image does not explicitly expose the ports, so I was able to expose and map them by doing:

```
@ClassRule
    public static GenericContainer pulsar = new FixedHostPortGenericContainer("apachepulsar/pulsar:1.21.0-incubating")
            .withFixedExposedPort(6650,6650)
            .withFixedExposedPort(8080,8080)
            .withCommand("bin/pulsar standalone --advertised-address 127.0.0.1")
            .withExposedPorts(6650, 8080);
```

Thanks for your help.

**Comment by bsideup** [comment]
@estebangarcia FYI you can use a SocatContainer and avoid fixed port mappings, check KafkaContainer :)

**Comment by bsideup** [comment]
@estebangarcia I can also help you with a snippet if you want (was looking to experiment with Pulsar anyway :) )

**Comment by MLU-estebangrd** [comment]
Hi @estebangarcia I'm receiving your notifications via email (because of your account email), can you check if you're using esteban.garcia@m.. ? If so, it would be great (for both of us) if you change it to a personal email :)
