### ISSUE TITLE
[Enhancement]: Missing configuration property ryuk.disabled 

### ISSUE THREAD

**Issue by veita** [testcontainers/testcontainers-java#6057]
### Module

Core

### Proposal

It seems that currently there is no way to disable Ryuk via `testcontainers.properties` or `.testcontainers.properties`.

This is because the property counterpart (`ryuk.disabled`) of the environment variable `TESTCONTAINERS_RYUK_DISABLED` is not supported.

See https://www.testcontainers.org/features/configuration/

**Comment by eddumelendez** [comment]
Hi @veita this is currently on purpose. We are aware of disabling Ryuk is some CI environments. However, we haven't experienced this need in local environments. Please, take into account that Testcontainers works with Docker-API compatible runtime. For that reason, we only support it via environment variables to be explicit about disabling it in the CI definition.

**Comment by veita** [comment]
Unfortunately Ryuk does not work with Podman (https://github.com/testcontainers/moby-ryuk/issues/23).

This makes it kind of cumbersome to use testcontainers with Podman in a clean way.

**Comment by kiview** [comment]
As @eddumelendez mentioned, Testcontainers works with Docker-API compatible container runtimes (see [Docker Requirements](https://www.testcontainers.org/supported_docker_environment/#overview) in our docs). It might help to raise an issue with the podman community regarding Docker API compatibility.

**Comment by veita** [comment]
Podman provides a Docker compatible API. For rootless containers it could be enabled with
```bash
systemctl --user enable --now podman.socket
```

After playing around with testcontainers and Podman I'm actually not that sure that Ryuk really does not work in this combination (as https://github.com/testcontainers/moby-ryuk/issues/23 suggests).

With `DOCKER_HOST`/`docker.host` set to `unix:///run/user/${UID}/podman/podman.sock` I did not see any obvious errors during the test container lifecycle.
