### ISSUE TITLE
[Bug]: Error when using Docker 4.13.0 - Missing symlink it seems

### ISSUE THREAD

**Issue by FlorianKempenich** [testcontainers/testcontainers-java#6076]
### Module

MySQL

### Testcontainers version

1.15.3

### Using the latest Testcontainers version?

No

### Host OS

Mac OS

### Host Arch

x86

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.13.0 (89412)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

When trying to run a test with testcontainer, there's an error: `Could not find a valid Docker environment`

After spending a long time trying to debug the issue we found out that it's because Docker doesn't create a `docker.sock` at `/var/run` by default anymore. That behaviour is since 4.13.0 and is documented in the [release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4130)

We were able to fix the problem by manually creating a symlink: `sudo ln -s $HOME/.docker/run/docker-cli.sock /var/run/docker-cli.sock`

I'm opening this issue to bring awareness to the problem. You could
1. Update the documentation, and the error message, to inform people this symlink is now needed
2. Point `UnixSocketClientProviderStrategy` to the new location of the socket (`$HOME/.docker/run`)
3. Do anything else 😁

I hope that's helpful, if not feel free to close 👍

Best,
Flo

> Note: I could not update the version of test-containers (working on a client project), but I don't think it's version related as it's still present in the [current `main`](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/dockerclient/UnixSocketClientProviderStrategy.java). If I'm mistaken and the bug has been fixed already, sorry for the false alert 🙂

### Relevant log output

```shell
Could not find a valid Docker environment. Please see logs and check configuration
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	...
```

**Comment by eddumelendez** [comment]
Hi @FlorianKempenich! We updated our docs properly, you can see it [here](https://www.testcontainers.org/supported_docker_environment/). We also had a [discussion](https://github.com/testcontainers/testcontainers-java/discussions/6045?converting=1#discussioncomment-3983224) and was properly answered. Also, looks like the change is going to be back to Docker Desktop, see [comment](https://github.com/docker/for-mac/issues/6529#issuecomment-1292135881).

**Comment by FlorianKempenich** [comment]
Great! Thanks for the update 👍
