### ISSUE TITLE
db extra connection params are only passed to the first connection in a pool 

### ISSUE THREAD

**Issue by jeacott1** [testcontainers/testcontainers-java#610]
if you attempt to use a datasource url with extra params like:

jdbc:tc:postgresql://somehostname:someport/databasename?stringtype=unspecified

the stringtype=unspecified only gets assigned to the very first connection in the pool, all the rest get nothing.

here's a fix:
https://github.com/testcontainers/testcontainers-java/pull/609

**Comment by rnorth** [comment]
Thank you @jeacott1 for this as well. Actually @manikmagar has a PR (#594) open in a similar area. I wonder if that might also help with this problem. If it doesn't I'd be keen to fix this problem in the refactored PR that Manik has put forward.

**Comment by jeacott** [comment]
well its a trivial fix, and the problem still exists in that pr, so feel free to mod it or apply this one as you like.

**Comment by manikmagar** [comment]
Thanks for taking look. Yes, it was fixed as a part of implementation but was unaware of this bug until I saw [this ](https://github.com/testcontainers/testcontainers-java/pull/594#issuecomment-372830327) comment. I have modified a test case to test the behavior and is fixed & tested with that PR.
