### ISSUE TITLE
[Feature]:  Expose class's fetch containerInfo timeout to user.

### ISSUE THREAD

**Issue by GOODBOY008** [testcontainers/testcontainers-java#6128]
### Module

Core

### Problem

![) KXEUHVA{152NEB`_BA830](https://user-images.githubusercontent.com/13617900/200178038-dc18cbd5-1677-47e1-9ec4-90ef6d853112.png)

Some conditions container will excute long time to expose ports , but currently only wait 5 seconds to fetch containerInfo.

### Solution

Expose class's fetch containerInfo timeout to user and with defalt value.

### Benefit

We can wait more time for heavy container to started.

### Alternatives

None.

### Would you like to help contributing this feature?

Yes

**Comment by GOODBOY008** [comment]
Hi @kiview , Can you give me some advices? I'm waiting for your reply. Thank you~

**Comment by kiview** [comment]
@GOODBOY008 Can you please elaborate on your use case? This code is about container creation, it is independent of the ports becoming available (we have other code that checks for this condition). 

Even heavy containers will have the actual container normally created in sub-seconds. 

If you have a specific setup that is failing, sharing a reproducer would help:
https://github.com/testcontainers/testcontainers-java-repro

**Comment by GOODBOY008** [comment]
@kiview  Thanks for your reply , I have create a repo to reproduce my sceno. https://github.com/GOODBOY008/testcontainer-issue/tree/issue-6128 .

**Comment by eddumelendez** [comment]
Hi @GOODBOY008! thanks for sharing! the issue is related to the `host` mode. I use the the following code

```
    private Network network = Network.newNetwork();

    @Test
    public void demonstration() {

        try (
                GenericContainer<?> OB_SERVER =
                        new GenericContainer<>("oceanbase/oceanbase-ce:3.1.4")
                                .withNetwork(network)
                                .withExposedPorts(OB_SERVER_SQL_PORT, OB_SERVER_RPC_PORT)
                                .withEnv("OB_ROOT_PASSWORD", OB_SYS_PASSWORD)
                                .waitingFor(Wait.forLogMessage(".*boot success!.*", 1))
                                .withLogConsumer(new Slf4jLogConsumer(LOG));
                GenericContainer<?> LOG_PROXY =
                        new GenericContainer<>("whhe/oblogproxy:1.0.3")
                                .withNetwork(network)
                                .withExposedPorts(LOG_PROXY_PORT)
                                .withEnv("OB_SYS_USERNAME", OB_SYS_USERNAME)
                                .withEnv("OB_SYS_PASSWORD", OB_SYS_PASSWORD)
                                .waitingFor(Wait.forLogMessage(".*boot success!.*", 1))
                                .withLogConsumer(new Slf4jLogConsumer(LOG));
        ) {
            Startables.deepStart(Stream.of(OB_SERVER, LOG_PROXY)).join();
        }
    }
```

and it worked. is it helps? Otherwise, I think you can follow #5151 due to this is duplicated.

**Comment by GOODBOY008** [comment]
@eddumelendez Thanks , it's worked.
