### ISSUE TITLE
TestContainers 1.6 is not using the dockerImageName in the code

### ISSUE THREAD

**Issue by csigueros** [testcontainers/testcontainers-java#614]
Hi,

   I'm trying to use TestContainers to test a NodeJS application in a docker container. I have created a container for it and I'm trying to use it in my test as this:
`@ClassRule
public static GenericContainer redis = new GenericContainer("css/ldap-server:latest")
                    .withExposedPorts(1389);`

  If I run `docker images` I get this:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
css/ldap-server     latest              b31725ccf479        19 hours ago        681MB
node                carbon              46f2857af80b        32 hours ago        673MB
bsideup/moby-ryuk   0.2.2               a27283338f1b        8 weeks ago         9.31MB

```

 But the image that I get running is the `bsideup/moby-ryuk   0.2.2` one. This is in the logs:

`POST /containers/create?name=testcontainers-ryuk-44f26548-e88d-4585-ac6c-1e76540fa2db HTTP/1.1`

 Any clue what I'm doing wrong here?

Thanks a lot

**Comment by bsideup** [comment]
Hi @csigueros,

This is a special container we start to keep watching your containers and kill them once you stop your tests. It is super thin and doesn't add too much to your resources consumption. Both LDAP server and ryuk will stop shortly after your tests' execution.

FYI next TC version will use `quay.io/testcontainers/ryuk` image :)

**Comment by csigueros** [comment]
Thanks, but I still can't see my container running...

Anything else I should check?

**Comment by csigueros** [comment]
Forget it....I have it working now. I found some complete usage examples and it seems I wan't calling the start method on the container in the beforeTest method.

It works great now!!!

**Comment by bsideup** [comment]
@csigueros 👍  

yes, you have two call `.start()` if you're not using the JUnit Framework and it's Rule/ClassRule integration. 

Happy to know that it works for you 🎉 
 I'll close the issue since it's solved, but feel free to report if you discover something else :)
