### ISSUE TITLE
[Enhancement]: Prepend library/ to docker official images

### ISSUE THREAD

**Issue by akurth** [testcontainers/testcontainers-java#6166]
### Module

Core

### Proposal

Hello,

would it be possible to prepend "library/" to the official alpine docker image pulled in ("library/alpine"); that’s where the image is actually located.

Reason: it is often desired to use a dockerhub mirror (because of rate limits), which we achieve by setting the following property: "hub.image.name.prefix=our.company.mirror/". While this works fine for the testcontainers images, it doesn’t work for the official docker images like "alpine". We have to work around that by setting the property "tinyimage.container.image=library/alpine:3.16", which is deprecated and discouraged according to the docs.

**Comment by eddumelendez** [comment]
Closing as duplicated. See https://github.com/testcontainers/testcontainers-java/issues/5612

**Comment by akurth** [comment]
This case is a bit different than #5612.

It is perfectly fine for us to use the `asCompatibleSubstituteFor` workaround when instantiating e.g. postgres containers in our code. The "alpine" image is not actively used by ourselves though; it is implicitly used by the testcontainers framework. Since we don’t have control over this one, we have to use the deprecated property `tinyimage.container.image`.
