### ISSUE TITLE
[Enhancement]: remove usage of deprecated ru.yandex in clickhouse module

### ISSUE THREAD

**Issue by awaizman1** [testcontainers/testcontainers-java#6168]
### Module

Clickhouse

### Proposal

Since clickhouse jdbc driver v0.3.2, the ru.yandex package is deprecated (see https://github.com/ClickHouse/clickhouse-jdbc).

seems like the clickhouse module still import ru.yandex.* (will be removed from v0.4).

Came into this since new package implementation (com.clickhouse.*) is different from old one in the way it handles transactions (instead of throwing exception in Connection.setAutoCommit, it now handles it somehow).
This makes my Spring-boot tests with @JdbcTest annotation fail with test container but pass with connecting to already running container.

Thanks

**Comment by eddumelendez** [comment]
Hi @awaizman1 

There is an attempt to move and use the new driver, but for backward compatibility reasons, it has not been merged.

See https://github.com/testcontainers/testcontainers-java/pull/5666
