### ISSUE TITLE
[Bug]: FAIL_FAST_ALWAYS in DockerClientProviderStrategy is not reset between Gradle builds

### ISSUE THREAD

**Issue by renegrob** [testcontainers/testcontainers-java#6169]
### Module

Core

### Testcontainers version

1.17.5

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 22.04.1 LTS

### Host Arch

x86_64

### Docker version

```shell
Docker version 20.10.21, build baeda1f
```

### What happened?

If you use TestContainers in a Gradle build and the AtomicBoolean `FAIL_FAST_ALWAYS` in `org.testcontainers.dockerclient.DockerClientProviderStrategy` is ever set to `true` it will not be reset unless you execute `gradle --stop` or restart your machine. Gradle is an external tool and TestContainers did not anticipate that DockerClientProviderStrategy will survive multiple test runs and live as long as the Gradle daemon has not been stopped. However, keeping such an information in a singleton without any cache invalidation is in my point of view something that has to be corrected in TestContainers. It should be a rather easy fix. The current behavior makes everything fail once that `FAIL_FAST_ALWAYS` has become `true` and only a restart helps - unless you figure out that the cause is a Singleton living in the Gradle daemon process.

### Relevant log output

```
IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
```

### Additional Information

Gradle version: Gradle 7.5.1

**Comment by eddumelendez** [comment]
Closing as duplicated. See https://github.com/testcontainers/testcontainers-java/issues/5017
