### ISSUE TITLE
Docker-Machine installation on Windows can't be found

### ISSUE THREAD

**Issue by MaXal** [testcontainers/testcontainers-java#62]
Due to the following check in DockerMachineClient:

```
public boolean isInstalled() {
        return executableExists("docker-machine");
}
```
docker installation on Windows can't be found. On Windows it's necessary to use "docker-machine.exe" instead of just "docker-machine".

For example, the following code:
`Files.isExecutable(FileSystems.getDefault().getPath("C:\\Program Files\\Docker Toolbox\\docker-machine.exe")) ` 
works but 
`Files.isExecutable(FileSystems.getDefault().getPath("C:\\Program Files\\Docker Toolbox\\docker-machine"))`
doesn't.

**Comment by rnorth** [comment]
Hi,
Sorry but I've not worked on Windows support yet - this ought to be noted in the docs, and sorry that you've found out the hard way.

Docker-Machine detection will be one issue; there may potentially be other minor ones too (the volume-based screen recording feature for the selenium module is one thing that springs to mind)

I'd be happy to integrate the changes necessary to make it work, though, but it may take some time for me to do this myself. I'll have a think about this...

Richard

**Comment by rnorth** [comment]
Implementation of this needs to take #63 into account as well - there's some simplification possible.

**Comment by rnorth** [comment]
Raised #85 to track Windows support.

**Comment by rnorth** [comment]
@MaXal just to let you know, we have Windows support as an alpha release now - please see docs here if you're interested: http://testcontainers.viewdocs.io/testcontainers-java/usage/windows_support/

**Comment by MaXal** [comment]
@rnorth Thank you! I will definitely check it out.
