### ISSUE TITLE
[Enhancement]: Update orientdb-client from 3.0.x to 3.1.x or higher

### ISSUE THREAD

**Issue by ManjunathMS35** [testcontainers/testcontainers-java#6213]
### Module

OrientDB

### Proposal

The orientdb-client 3.0.x brings the net.java.dev.jna:jna-platform 4.x as a transitive dependency.

The WhiteSource security scanner recently listed jna-platform 4.x as vulnerable with below details.

JNA prior to 5.0.0 was discovered to contain an out-of-bounds read. Advapi32Util.registryGetValues does not terminate the returned string with null terminators. When it tries to identify the string content it searches for the next null-terminator and will read out-of-bounds of the buffer.

Related links: https://github.com/java-native-access/jna/issues/340 , https://github.com/java-native-access/jna/commit/12493ba771a50fae7d6303e8b58b31eacf903327

The orientdb-client 3.1.x or higher seems to be not using jna-platform at all.

Is it possible to update orientdb-client in this case?

**Comment by eddumelendez** [comment]
@ManjunathMS35 we just release testcontainers 1.17.6 which includes a dependency upgrade. Also, I would like to suggest to create your own client instead of using the one provided by OrientDBContainer.
