### ISSUE TITLE
[Enhancement]: Make ClickHouseContainer try to use new driver by default

### ISSUE THREAD

**Issue by trolley813** [testcontainers/testcontainers-java#6232]
### Module

Clickhouse

### Proposal

In #5474, support of the new `com.clickhouse.jdbc.ClickHouseDriver` was added. However, the implementation (the `getDriverClassName()` function) tries to load the older (deprecated) driver first, and the current Clickhouse JDBC distribution still (as of current version at the moment, `0.3.2-patch11`) [includes](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.2-patch11/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java) the older driver, so the newer one is actually never used.

I believe that the `getDriverClassName()` should behave the other way round: first try to load the _new_ driver and, if it's not found, fall back to the old one. This was already [noticed](https://github.com/testcontainers/testcontainers-java/pull/5474#issuecomment-1155320480) by user pan3793 but it seems that the comment was ignored.

**Comment by eddumelendez** [comment]
@trolley813 Look at this [PR](https://github.com/testcontainers/testcontainers-java/pull/5666). I am closing this and follow the conversation over there.
