### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Olex1313** [testcontainers/testcontainers-java#6240]
### Module

Clickhouse

### Proposal

I wanted to use clickhouse module with https://github.com/blynkkk/clickhouse4j, which is not currently supported, but I'm not sure why we couldn't use it instead of official drivers. 

Why not to include it to Clickhouse-module or even allow to specify driver-class-name in properties?

**Comment by eddumelendez** [comment]
@Olex1313 You can extend ClickhouseContainer and override the driver you want to use.
