### ISSUE TITLE
Experience using Oracle-XE on Windows 7 with testcontainers

### ISSUE THREAD

**Issue by smil2k** [testcontainers/testcontainers-java#627]
Hi,

I have Windows 7 and I was able to use the testcontainers-oracle rule by doing these steps:

Steps taken:

First I installed Docker Toolbox. Detailed description here:
https://docs.docker.com/toolbox/toolbox_install_windows/

+ some additional steps:
Before step 3 I copied boot2docker.iso (downloaded from: https://github.com/boot2docker/boot2docker/releases) to c:\Users\<myuser>\.docker\machine\cache directory.
(proxy issue)
 
Before step 4 I edited the docker-machine profile.
Ssh to docker machine:
docker-machine ssh default

sudo vi /var/lib/boot2docker/profile
Added proxy settings to it and set tls to no.

Then restart the docker machine.

sudo /etc/init.d/docker restart

I added containerized oracle xe dependency to pom with test scope:

<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>oracle-xe</artifactId>
    <version>1.4.3</version>
    <scope>test</scope>
</dependency>

 In test application properties I set the following properties:

spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
oracle.database.username=system
oracle.database.password=oracle
oracle.database.url=127.0.0.1
oracle.database.port=1521
oracle.database.name=xe

 and then could run the test with specifying the docker host (docker-machine ls will tell you the url for the docker):

mvn -DDOCKER_HOST=tcp://192.168.99.100:2376 test

(Most likely the DOCKER_HOST thing could be put into some machine dependent place, maybe into settings.xml.)

**Comment by kiview** [comment]
Hey @smil2k, what's the purpose of this issue, you had any problems or you just wanted to share your experience? Do you think the documentation is lacking something?

**Comment by smil2k** [comment]
Hi,

I think the documentation suggests, that it won't work. I thought that I'll share my experience with others with the required steps. 

Sorry for not being more direct at first.

Cheers,

Tamas

**Comment by kiview** [comment]
Hey @smil2k,
definitely thanks for your instructions, it could help people struggling with Testcontainers on Docker-Toolbox with Oracle I suppose.

About Docker-Toolbox support we say:
> Support is limited at present and this is not currently tested on a regular basis.

See: https://www.testcontainers.org/compatibility.html
