### ISSUE TITLE
[Enhancement]: CockroachDB now supports username/password/database via an environment variable

### ISSUE THREAD

**Issue by ahus1** [testcontainers/testcontainers-java#6299]
### Module

CockroachDB

### Proposal

The wrapper currently complains that username, password and database can't be passed to the container: 

https://github.com/testcontainers/testcontainers-java/blob/b1232fc6beeda838ab4bd3dc62580e172acb370d/modules/cockroachdb/src/main/java/org/testcontainers/containers/CockroachContainer.java#L105-L124

This issue has been closed in the meantime: 

* https://github.com/cockroachdb/cockroach/issues/19826

In this commit: https://github.com/cockroachdb/cockroach/pull/70238/commits/2862374a4743aece5707ea52d0ac17f6cb10dc7b

Now the following values can be provided via "COCKROACH_DATABASE", "COCKROACH_USER" and "COCKROACH_PASSWORD". 

I tried this with the commands "start-single-node", "--insecure", and found that in insecure mode, no password can be provided.

**Comment by eddumelendez** [comment]
JFTR, it has been available since version `22.1.0`

In this case, when version 22.1.0 or high is added then `insecure` flag should not be used.

**Comment by eddumelendez** [comment]
@vcvitaly thanks for offering. This is yours!

**Comment by simplenotezy** [comment]
Would be nice if you could comma separate for multiple databases. When running e2e tests it can be useful to create a unique database for each test suite, to allow them running concurrently. For now we worked around it using a table prefix for each suite.
