### ISSUE TITLE
Spock extension does not create video recordings of failed BrowserWebDriverContainer tests

### ISSUE THREAD

**Issue by kiview** [testcontainers/testcontainers-java#631]
`BrowserWebDriverContainer` leverages JUnit's `failed()` and `succeeded()` callbacks. These methods are not called if used with the Spock extension.

**Comment by bsideup** [comment]
FYI in my junit5 branch I created a framework agnostic test lifecycle:
https://github.com/testcontainers/testcontainers-java/blob/junit5/core/src/main/java/org/testcontainers/lifecycle/TestLifecycleAware.java

https://github.com/testcontainers/testcontainers-java/blob/a3b96542331049db76c4e9e19f9952c8e5485379/modules/selenium/src/main/java/org/testcontainers/containers/BrowserWebDriverContainer.java#L208

**Comment by rnorth** [comment]
This was released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0 🎉

Thanks for the contribution!
