### ISSUE TITLE
[Bug]: SFTP atmoz Test container Permission Denied to delete file

### ISSUE THREAD

**Issue by nimmygs** [testcontainers/testcontainers-java#6316]
### Module

Core

### Testcontainers version

1.15.2

### Using the latest Testcontainers version?

Yes

### Host OS

MAC

### Host Arch

ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.1 (90346)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Trying to create an SFTP server in testcontainer.
File is copied to sftp folder using withClasspathResourceMapping. While trying to do an sftp rm, it throws Permission denied issue:

private static final int PORT = 22;
  private static final String USER = "cppadm";
  private static final String USER_PASS = "cppadm::1000";

  private static final GenericContainer sftp =
      new GenericContainer("atmoz/sftp:latest")
.withClasspathResourceMapping("II_110227", "/home/" + USER + "/upload/II_110227/", BindMode.READ_WRITE)
          .withExposedPorts(PORT)
          .withCommand(USER_PASS);

Tried using withCopyFileToContainer and observed same permission denied issue

sftp get is working but sftp rm is not working eventhough Bindmode is READ_WRITE

The file is added to the upload folder with full permission but user and group is cppadm:
-rwxrwxrwx 1 root root 402 Dec 21 06:06 II_110227

### Relevant log output

```shell
Unexpected exception thrown: com.jcraft.jsch.SftpException: Permission denied
```

**Comment by nimmygs** [comment]
When I try to run in Gitlab, the same permission issue is hit
permission denied while trying to delete the file in upload folder

**Comment by eddumelendez** [comment]
After reading [atmoz/sftp implementation](https://github.com/atmoz/sftp/blob/master/files/create-sftp-user) I was able to understand and here it is the code

I have the following `src/test/resources/testcontainers/file.txt`

```java
@Test
void test() throws Exception {
    try (GenericContainer<?> sftp = new GenericContainer<>("atmoz/sftp:latest")
            .withCopyFileToContainer(MountableFile.forClasspathResource("testcontainers/", 0777), "/home/foo/upload/testcontainers")
            .withExposedPorts(22)
            .withCommand("foo:pass:::upload")) {
        sftp.start();
        JSch jsch = new JSch();
        Session jschSession = jsch.getSession("foo", sftp.getHost(), sftp.getMappedPort(22));
        jschSession.setPassword("pass");
        jschSession.setConfig("StrictHostKeyChecking", "no");
        jschSession.connect();
        ChannelSftp channel = (ChannelSftp) jschSession.openChannel("sftp");
        channel.connect();
        assertThat(channel.ls("/upload/testcontainers")).anyMatch(item -> item.toString().contains("file.txt"));
        assertThat(new String(channel.get("/upload/testcontainers/file.txt").readAllBytes())).contains("testcontainers");
        channel.rm("/upload/testcontainers/file.txt");
        assertThat(channel.ls("/upload/testcontainers/")).noneMatch(item -> item.toString().contains("testcontainers/file.txt"));
    }
}
```

Please, next time consider to submit a full example in order to reproduce it quickly :)

**Comment by nimmygs** [comment]
Thank you so much, it worked :)
