### ISSUE TITLE
[Bug]: `unix:///var/run/docker.sock` not listening although Docker works using CLI

### ISSUE THREAD

**Issue by rafg92** [testcontainers/testcontainers-java#6394]
### Module

postgresql, junit-jupiter

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
20.10.22
```

### What happened?

When Launching SpringBootTest using java 11 and  SpringBoot 2.7.3 the process fails to execute since it is unable to connect to the local docker engine, stating that unix:///var/run/docker.sock is not listening. 
There are no problems with docker commands starting from terminal.
Docker's post installation settings are also already bean made and so it is possible to execute docker commands without sudo.

### Relevant log output

```shell
17:34:29.189 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:~/.testcontainers.properties
17:34:29.198 [main] WARN org.testcontainers.utility.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:~/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException:~/.testcontainers.properties (No such file or directory)
17:34:29.202 [main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
17:34:29.228 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is set but '/run/user/1000/docker.sock' does not exist.
17:34:29.228 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/home/over/.docker/run' does not exist.
17:34:29.279 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/1000/docker.sock' does not exist.
17:34:29.279 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: UnixSocketClientProviderStrategy
17:34:29.304 [main] WARN org.testcontainers.dockerclient.DockerClientProviderStrategy - DOCKER_HOST unix:///var/run/docker.sock is not listening
17:34:29.304 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - strategy UnixSocketClientProviderStrategy did not pass the test
17:34:29.306 [main] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /snap/bin, /snap/bin])
17:34:29.307 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
As no valid configuration was found, execution cannot continue.
See https://www.testcontainers.org/on_failure.html for more details.
```

**Comment by eddumelendez** [comment]
I see `XDG_RUNTIME_DIR` env var set. By any chance are you using podman too? If using docker try in a new terminal without that env var, please.

**Comment by rafg92** [comment]
I'm not using podman but just docker. For what i know the XDG Base Directory Specification specifies that $XDG_RUNTIME_DIR should track the base directory relative to which user-specific runtime files and other file objects should be placed; the lifetime of the directory should (or rather must) be bound to the user being logged in and removed when the user fully logs out. How should i safely disable the env var?

Personally I think a key point could be this log line since the program is able to move forward despite the $XDG_RUNTIME_DIR:

17:34:29.304 [main] WARN org.testcontainers.dockerclient.DockerClientProviderStrategy - DOCKER_HOST unix:///var/run/docker.sock is not listening

I was wondering why is the program not able to reach the docker daemon even though it completely functional from terminal without sudo permissions?

**Comment by kiview** [comment]
@rafg92 Did you by any chance install Docker through Snap? I think this will lead to a specifically quirky configuration that makes integration with other programs problematic.

**Comment by rafg92** [comment]
Hi @kiview , I've installed docker using the apt repository according to the guide in https://docs.docker.com/engine/install/ubuntu/.
I've run the curl command and I'm pasting you the result: 

{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"20.10.22","Details":{"ApiVersion":"1.41","Arch":"amd64","BuildTime":"2022-12-15T22:25:49.000000000+00:00","Experimental":"false","GitCommit":"42c8b31","GoVersion":"go1.18.9","KernelVersion":"5.15.0-56-generic","MinAPIVersion":"1.12","Os":"linux"}},{"Name":"containerd","Version":"1.6.14","Details":{"GitCommit":"9ba4b250366a5ddde94bb7c9d1def331423aa323"}},{"Name":"runc","Version":"1.1.4","Details":{"GitCommit":"v1.1.4-0-g5fd4c4d"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"20.10.22","ApiVersion":"1.41","MinAPIVersion":"1.12","GitCommit":"42c8b31","GoVersion":"go1.18.9","Os":"linux","Arch":"amd64","KernelVersion":"5.15.0-56-generic","BuildTime":"2022-12-15T22:25:49.000000000+00:00"}

**Comment by kiview** [comment]
Thanks for sharing the output @rafg92, that looks fine and installing Docker following this guide should work.
Do you have the same issue when you try to run this reproducer project?
https://github.com/testcontainers/testcontainers-java-repro

**Comment by rafg92** [comment]
I'm running the test from Intellij IDE; I was able to run the test and it terminated successfully.
Strange thing though, I've wanted to rerun my test to check if it could be a problem of login/logoff since changing docker permissions and it seems that the program was able to set up the docker container.

Now I'm stuck with this exception when trying to connect to postgres container: 

java.lang.RuntimeException: Driver org.testcontainers.jdbc.ContainerDatabaseDriver claims to not accept jdbcUrl, jdbc:postgresql://localhost:32771/test?loggerLevel=OFF

but I think I'll take it from here :D.

Thank you for your support.

Best regards

**Comment by kiview** [comment]
Thanks for letting us know, you can ask for some more specific help in using Testcontainers in [Slack](https://slack.testcontainers.org/) or in our GH discussions.

I'll close this issue.
