### ISSUE TITLE
fail to create  custom container  with gradle on linux

### ISSUE THREAD

**Issue by gadieichhorn** [testcontainers/testcontainers-java#641]
I run linux fedora 27
Docker version 17.12.1-ce, build 7390fc6

my gradle dependency has:

    testCompile group: 'org.testcontainers', name: 'testcontainers', version: '1.7.0'

I have a custom container image I want to run as a test dependency

I created a custom contaier class

```
public class IgniteContainer extends GenericContainer<IgniteContainer> {

    public IgniteContainer() {
        super("my/local:image");
    }
}
```

My test is then:

    @ClassRule
    public static IgniteContainer ignite = new IgniteContainer().withExposedPorts(11211);

getting a test exception on the class rule line

> com.rds.IgniteServerTest > classMethod FAILED
>     java.lang.NoClassDefFoundError at IgniteServerTest.java:12
>         Caused by: java.lang.ClassNotFoundException at IgniteServerTest.java:12

I do have a docker-machine installed, do I need to set the DOCKER_HOST ? to what value?
Can I set it from gradle build or some gradle config file?

**Comment by bsideup** [comment]
@gadieichhorn you don't need a docker machine on Linux. Testcontainers will auto-detect your local Docker daemon.

However, the error you get is "ClassNotFoundException" and unrelated to Docker part of Testcontainers. Please send the full log or at least the full stacktrace of that exception.

**Comment by gadieichhorn** [comment]
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ignite:test'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
>         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:63)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
>         at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/geichhorn/Develop/gitlab/observato/observato-ignite/build/reports/tests/test/index.html
>         at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:596)
>         at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:477)
>         at org.gradle.api.tasks.testing.Test.executeTests(Test.java:520)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
>         ... 31 more
> 
>

**Comment by bsideup** [comment]
@gadieichhorn this is Gradle's exception, not what your code is throwing. Please send the exception you get from your code

**Comment by bsideup** [comment]
@gadieichhorn oh wow.... could you please try version 1.6.0? It looks like a regression in 1.7.0

**Comment by gadieichhorn** [comment]
ok, that is working... :+1:

**Comment by bsideup** [comment]
@gadieichhorn thanks for reporting! I created a PR to fix it ( #642 ).
But you can workaround version 1.7.0 by adding `commons-codec:commons-codec:1.11` dependency.

Sorry for that! We will release a hotfix ASAP!

**Comment by gadieichhorn** [comment]
ok, thats great! I will wait for the fix.

**Comment by bsideup** [comment]
@gadieichhorn released in 1.7.1

**Comment by gadieichhorn** [comment]
thanks, I will tests and provide feedback if any issues.

**Comment by gadieichhorn** [comment]
tested! works nicely. well done
