### ISSUE TITLE
[Bug]: Couchbase sample in doc is missing call to container.start()

### ISSUE THREAD

**Issue by mikereiche** [testcontainers/testcontainers-java#6414]
### Module

Couchbase

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

x64

### Docker version

```shell
% docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:44 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.1 (76265)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Couchbase documentation sample is missing call container.start().

https://www.testcontainers.org/modules/databases/couchbase/

**Comment by eddumelendez** [comment]
There is a `Test Framework Integration` section in our docs https://www.testcontainers.org/ which explain how container classes can be initialized.

* [JUnit 4](https://www.testcontainers.org/test_framework_integration/junit_4/)
* [JUnit 5](https://www.testcontainers.org/test_framework_integration/junit_5/)
* [Spock](https://www.testcontainers.org/test_framework_integration/spock/)
* [Manual Lifecycle Control](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/)
