### ISSUE TITLE
[Enhancement]: Support for 'pgsql' (PG-NG) JDBC driver

### ISSUE THREAD

**Issue by ntr-ross** [testcontainers/testcontainers-java#6424]
### Module

PostgreSQL

### Proposal

Testcontainers for PG currently rejects 'jdbc:tc:pgsql:...' URL's.

Not sure if this has been discussed before (or is on the roadmap already) but is it possible to add support for the 'pgsql' database type for use with the 'com.impossibl.pgjdbc-ng' drop-in replacement JDBC driver for PG?

**Comment by eddumelendez** [comment]
Looking at the releases, last one was on May 2021 and doesn't seem active nowadays. Source: https://impossibl.github.io/pgjdbc-ng/ For that reason, I don't think the project will support it.

**Comment by ntr-ross** [comment]
It was this discussion [here](https://github.com/impossibl/pgjdbc-ng/issues/579) (potential inclusion into org.postgresql hierarchy) that made us take it into more serious consideration for broad testing purposes.  But I can understand the reluctance to support it.
