### ISSUE TITLE
[Enhancement]: Add "commit" and "rollback" as end delimiter in splitSqlScript methode

### ISSUE THREAD

**Issue by lolojur** [testcontainers/testcontainers-java#6435]
### Module

Core
In Class ScriptUtils.java

### Proposal

The splitSqlscript parse the sql file initDB in testcontainers.

There are a part of code who read BEGIN and END statement. The result is store inside compoundStatementDepth var.

Statement must have the same number of BEGIN and END before splitting.

Unfortunely, when you have BEGIN TRANSACTION, end statement have to finish with COMMIT or ROLLBACK but never with END.

The splitting cannot be finish and throw an error.

I purpose to improve the private method 
`private static boolean containsKeywordsAtOffset(String lowercaseString, String keywords, int offset, String separator, String commentPrefix, String blockCommentStartDelimiter) ` 
and provide a list of keyword

**Comment by eddumelendez** [comment]
We highly recommend to use the database initialization such as in [PostgreSQL](https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts),  [MySQL](https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance), for example. Also, use a database change management such as [Flyway](https://flywaydb.org/) or [Liquibase](https://www.liquibase.org/)
