### ISSUE TITLE
[Enhancement]: Allow a option to increase timeout more than 120 seconds

### ISSUE THREAD

**Issue by jasvant6thstreet** [testcontainers/testcontainers-java#6436]
### Module

MySQL

### Proposal

I am using testcontainers for running one of my build step. I am having HDD on my laptop and not SSD. Starting a mysql 8 container takes more than 120 seconds and testcontainers kills the container after 120 seconds and it attempts 3 times but still it fails because startup takes more than 120 seconds. I searched the internet and even read the source code and come to a conclusion that there is no option to increase the timeout. I desperately need this feature.

**Comment by kiview** [comment]
Have you tried using `withConnectTimeoutSeconds()`?

**Comment by jasvant6thstreet** [comment]
I am starting mysql container from my pom.xml
I don't have any option to use above method there.
https://github.com/testcontainers/testcontainers-java/blob/main/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java contains the timeout at line number 40. It is a private variable and cannot be overridden. 
I am looking for an option to override it using a property file or environment variable.

**Comment by kiview** [comment]
As mentioned before, the value can be set using the  `withStartupTimeoutSeconds()` method.

> I am starting mysql container from my pom.xml

It is unclear what this means, can you share a reproducer example?

**Comment by jasvant6thstreet** [comment]
I am using testcontainer like following in my pom.xml for generating jooq classes using jooq-codegen-maven plugin:
                    <jdbc>
                        <url>jdbc:tc:mysql:8.0.23:///price_service?TC_INITSCRIPT=file:scripts/merged_schema.sql</url>
                        <driver>org.testcontainers.jdbc.ContainerDatabaseDriver</driver>
                    </jdbc>
The above usage fails due to timeout while creating docker container. I have implemented a solution for myself at https://github.com/jasvant6thstreet/testcontainers-java-jasvant
