### ISSUE TITLE
[Enhancement]: Provide Containers without SELF reference

### ISSUE THREAD

**Issue by OLibutzki** [testcontainers/testcontainers-java#6449]
### Module

Core

### Proposal

In order to support inheritance Containers have generic types for `SELF` references. That makes perfect sense in order to have the fluent API returning the specific type at hand.

From a user's perspective it's somehow annoying to deal with these generics: `PostgreSQLContainer<PostgreSQLContainer<?>>`

To be honest, when using Testcontainers for the first time I was quite confused by these (at first glance) redunant type arguments.

I would like to suggest an idea I had in the context of the Keycloak container: https://github.com/dasniko/testcontainers-keycloak/issues/98#issuecomment-1397454388

Approx. 95% of the Testconainers users use the containers as-is. Introducing the generic encourages them to add at least <?> in order to remove the raw type warning.

What about this idea I describe in the context of the `PostgreSQLContainer`, but the pattern can be applied to all containers:
1. Rename PostgreSQLContainer to AbstractPostgreSQLContainer or ExtendablePostgreSQLContainer (an abstract class).
1. Add a PostgreSQLContainer class which just extends the abstract class and provides the type argument `<PostgreSQLContainer<?>>`. This class could be final some time in order to clarify that it's not meant to be extended. 
1. Clients are free to write custom classes which extend the abstract class using a type argument which reflects the specialized type itself.

As `PostgreSQLContainer` loses its type argument and becomes final, this is a breaking change, but maybe it's something you'd like to use in 2.0.0.

**Comment by eddumelendez** [comment]
Hi @OLibutzki ! Thanks for the proposal. There is a WIP proposal regarding to how the API will look like for Testcontainers 2.0 and how all language implementation will be aligned. As soon as we have a draft available we will announce it, stay tuned. There are some inspiration from https://github.com/testcontainers/testcontainers-java/pull/4465 too
