### ISSUE TITLE
docker-java brings in kqueue native transport, which breaks on many Macs

### ISSUE THREAD

**Issue by stevenschlansker** [testcontainers/testcontainers-java#650]
The `kqueue` native transport [is bundled in](https://github.com/docker-java/docker-java/blob/master/pom.xml#L258-L263) with `docker-java`

Currently, if you try to boot testcontainers 1.7.0 on a Mac OS 10.11 host, it crashes the JVM:
```java
09:50:51.784 [main] INFO  o.t.d.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/lf/2q1nqp9x17s4mz1znkk_14xc0000gn/T/liborg-testcontainers-shaded-netty-transport-native-kqueue3987326303555751096.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/lf/2q1nqp9x17s4mz1znkk_14xc0000gn/T/liborg-testcontainers-shaded-netty-transport-native-kqueue3987326303555751096.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

Netty closed this as wontfix: https://github.com/netty/netty/issues/6837

Because testcontainers shades its dependencies, it is not possible in a downstream application to exclude the transitive dependency.  You're stuck with an unsatisfiable dependency on a native library that crashes.

I don't think `docker-java` should bring in a native transport: 
https://github.com/docker-java/docker-java/issues/1023

Testcontainers should do at least one of:
* take an updated `docker-java` that removes this
* exclude the kqueue dependency for improved compatibility with older OSes
* not shade its dependencies so end-users can select the best transport for them

**Comment by bsideup** [comment]
@stevenschlansker thanks for reporting and doing the analysis! We're not using the `kqueue` implementation on OS X 10.11, or at least we shouldn't (for <= 10.11 there is a tcp proxy)

What makes me wonder is why you have this:
```
EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties
```
Are you using docker-machine? The recommended environment on macOS is Docker for Mac, could you perhaps remove `~/.testcontainers.properties` file and try installing it? 

FYI we're planning to replace the Netty transport with some more lightweight (like OkHttp) really soon.

**Comment by stevenschlansker** [comment]
I don't have Docker installed locally -- I have a `DOCKER_HOST` pointed to a remote machine.

The file contents are:
```
#Modified by Testcontainers
#Tue Jan 09 21:55:32 UTC 2018
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
```

I tried deleting it and re-running and it came back with the same contents except an updated timestamp.

**Comment by bsideup** [comment]
Ah, ok! Any specific reason why you have to do it? 
Some features like file mounting will not work with the remote Docker because the mounted files will not be on the remote machine.

**Comment by stevenschlansker** [comment]
Only that I've been running Docker containers from this host since long before `docker-machine` even existed as a project -- `boot2docker` was very unstable, and I got used to running this way :)

**Comment by bsideup** [comment]
@stevenschlansker I do feel your pain, did something like that in past as well :D But with Docker for Mac things changed and now it works great, give it a shot! :)

**Comment by rnorth** [comment]
I'm going to close - Docker for Mac support is mature and solid, and we're now using OkHttp instead of Netty, so this specific problem should be solved.
