### ISSUE TITLE
MountableFile fails when path contains + (plus)

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#664]
As seen in https://github.com/elastic/apm-agent-java/pull/57, file mounting doesn't work when path containers `+` (plus) character. It got replaced with ` ` (space)

**Comment by bsideup** [comment]
@felixbarny yes, it should fix both methods.

> There also seems to be a problem with the sources jar which made debugging a bit harder as line numbers don't match.

Oh wow! We're running Delombok to make the sources look better (otherwise IntelliJ compains) but apparently it breaks the debugging experience. Thanks, will check what we can do to make both work 👍

**Comment by felixbarny** [comment]
Thx for the release. I'd appreciate a release for this.

**Comment by bsideup** [comment]
@felixbarny released as 1.7.2 :)

**Comment by felixbarny** [comment]
thx a lot!

**Comment by bsideup** [comment]
@felixbarny I **really** hope this is the last & only blocker for Elastic APM 😅 took much longer than supposed to take to integrate, sorry for that 😄
