### ISSUE TITLE
[Enhancement]: JPMS Support/Fix for Testcontainers :: JDBC :: PostgreSQL

### ISSUE THREAD

**Issue by Jotschi** [testcontainers/testcontainers-java#6669]
### Module

PostgreSQL

### Proposal

The automatic JPMS module generation causes a name clash between `org.testcontainers:postgresql` and `org.postgresql:postgresql` since both resulting jar files will result in automatic JPMS module name of `postgresql`.

I propose to add the `Automatic-Module-Name` header to the manifest of `org.testcontainers:postgresql`. This way the name clash could be avoided.

**Comment by eddumelendez** [comment]
Closing as duplicated. See https://github.com/testcontainers/testcontainers-java/issues/1917
