### ISSUE TITLE
Allow user to specify a custom timeout for pulling images in RemoteDockerImage

### ISSUE THREAD

**Issue by kruijs-bbraun** [testcontainers/testcontainers-java#6675]
### Module

Core

### Proposal

The `RemoteDockerImage` class defines a constant of 2 minutes which specify the maximum time allowed to retry a pull.

This timerange may be too narrow when image repositories take longer than expected to respond. 

The constant should be converted to a private field as those already present on the class and be annotated using `@With`, keeping the default assignment with two minutes duration

The change is also mentioned here: https://github.com/testcontainers/testcontainers-java/issues/3829

**Comment by rob-valor** [comment]
This would also help to _fail fast_ when pulling an images version that does not exist instead of having to wait for 2 minutes.

**Comment by eddumelendez** [comment]
Fixed via #9417
