### ISSUE TITLE
[Enhancement]: no busy wait if Docker repository returns 5xx

### ISSUE THREAD

**Issue by seregamorph** [testcontainers/testcontainers-java#6678]
### Module

Core

### Proposal

There is retry cycle in `RemoteDockerImage.resolve` in case if Docker repository responds 5xx code. This cycle has the limit on time execution, but once the situation can happen, the log is just fully of garbage messages of failed attempt to make an HTTP call. Also it makes the redundant load on a docker repo.
In our case it was a wrong configured Artifactory for Docker images, the authentication token was missing. In the log there were thousands of failure messages done while timeout did not happen.

The proposal is pretty simple: add the sleep between retries in this cycle - either constant or logarithmic.

**Comment by eddumelendez** [comment]
This has been fixed in #8453, will be part of the next release.
