### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dambldore** [testcontainers/testcontainers-java#6681]
### Module

PostgreSQL

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x64

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Hi, I am trying to use testcontainers in my spring boot app.
I also use liquibase and i have simple code there:
```
create table calendar
(
    date date primary key,
    is_weekend boolean not null,
    is_pre_holiday boolean not null,
    check( not (is_weekend and is_pre_holiday) )
);
```

Also there are insert script for this table.
So simple test to get calendar from db works fine, but this does not work correctly, it does not trow exception or return null:
```
  CalendarEntity calendarEntity = new CalendarEntity(LocalDate.of(2000, 1, 1), true, true);
  CalendarEntity savedEntity = calendarRepository.save(calendarEntity);
  assertEquals(calendarEntity, savedEntity); //it returns true
```
I want to check constraints in my integration tests, please help me if I do something wrong

### Relevant log output

```shell
Expect something like this:

ERROR:  new row for relation "calendar" violates check constraint "calendar_check"
```

**Comment by eddumelendez** [comment]
Hi, I don't see how this is related to Testcontainers. If the spring.datasource properties were set and the script executed then Testcontainers did the job well.

In the future, it is recommended to attach a project which can reproduce the issue. Feel free to join slack or report your question in stackoverflow.
