### ISSUE TITLE
[Feature]: timestream support (timestream-query, timestream-write)

### ISSUE THREAD

**Issue by SingingBush** [testcontainers/testcontainers-java#6726]
### Module

None

### Problem

Timestream isn't available as a service in _org.testcontainers.containers.localstack.LocalStackContainer.Service_ but a LocalStack Pro can support both timestream: https://docs.localstack.cloud/user-guide/aws/timestream/

### Solution

add support for Amazon Timestream

### Benefit

Users can better test against timestream

### Alternatives

do nothing

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi, you can do `LocalStackContainer.EnabledService.named("timestream")`. Starting next Testcontainers release `withServices` would be optional due to starting `localstack:localstack:0.13.0` services start lazily.

**Comment by SingingBush** [comment]
awesome, do you publish snapshots to maven central? I'd like to try this in my fork of quarkus-amazon-services as soon as possible
