### ISSUE TITLE
[Bug]: Could not find a valid Docker environment.

### ISSUE THREAD

**Issue by Sanju98** [testcontainers/testcontainers-java#6734]
### Module

Cassandra

### Testcontainers version

1.16.3

### Using the latest Testcontainers version?

No

### Host OS

Linux

### Host Arch

amd64

### Docker version

```shell
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I'm getting the below error in running a Junit test in test-containers
**_Could not find a valid Docker environment. Please see logs and check configuration_** in test-containers:1.16.3

**Environment:**
test-containers:1.16.3
docker-java-api:3.2.12
docker-java-transport:3.2.12
cassandra-test-container:1.16.3
JVM: 11.0.15
OS: Ubuntu docker image

### Relevant log output

```shell
‘-- JUnit Jupiter [OK]
  ’-- xxxxxxxxxxTest [X] Could not find a valid Docker environment. Please see logs and check configuration
Failures (1):
  JUnit Jupiter:xxxxxxxxxxTest
    ClassSource [className = ‘aa.bbbbb.cassandra.ccccc.xxxxxxxxxxTest’, filePosition = null]
    => java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
       org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$4(DockerClientProviderStrategy.java:156)
       java.base/java.util.Optional.orElseThrow(Optional.java:408)
       org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:148)
       org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:146)
       org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:188)
       org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:101)
       com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:107)
       org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
       org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:242)
       org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:229)
```

**Comment by eddumelendez** [comment]
Can you try with version 1.17.6, please?

**Comment by Sanju98** [comment]
Tried all versions from 1.15.3 to 1.17.6
Still getting the same error

**Comment by eddumelendez** [comment]
Did you follow the [post-installation steps](https://docs.docker.com/engine/install/linux-postinstall/)?

**Comment by Sanju98** [comment]
I'm running this inside a Ubuntu docker container but it's throwing `Could not find a valid Docker environment' !!!

**Comment by Sanju98** [comment]
Yes, all post-installation steps are done

**Comment by eddumelendez** [comment]
So, you are running Testcontainers inside the ubuntu container in your host. The host has docker install and everything works fine. However, test in the ubuntu container are not running. That container has docker installed? You can use https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/#docker-only-example and mount the socket

**Comment by Sanju98** [comment]
I am launching the container with the codebase the volume and mapped the socket too
I am able to pull images and execute all docker commands inside the container

I'm using a private Cassandra image from an internal artifactory of our org.
`DockerImageName dockerImageName = DockerImageName.parse(CASSANDRA_IMAGE)
                .asCompatibleSubstituteFor("cassandra");
        this.cassandraContainer = new CassandraContainer<>(dockerImageName);`

This is the output when printing the Container
`GenericContainer(exposedPorts=[9042], portBindings=[], extraHosts=[], networkMode=null, network=null, networkAliases=[tc-nz6mH5WE], image=RemoteDockerImage(imageName=abc.artifactory.eng.xyz.com/library/cassandra@sha256:xxxxxxxxxxx, imagePullPolicy=DefaultPullPolicy()), env=[MAX_HEAP_SIZE=1024M, HEAP_NEWSIZE=128M, CASSANDRA_SNITCH=GossipingPropertyFileSnitch, JVM_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0], labels={}, commandParts=[], binds=[], privilegedMode=false, volumesFroms=[], linkedContainers={}, startupCheckStrategy=org.testcontainers.containers.startupcheck.IsRunningStartupCheckStrategy@5456afaa, startupAttempts=1, workingDirectory=null, shmSize=null, copyToFileContainerPathMap={org.testcontainers.utility.MountableFile@536dbea0=/etc/cassandra/triggers/trigger.jar}, dependencies=[], dockerClient=LazyDockerClient, containerId=null, containerInfo=null, waitStrategy=org.testcontainers.containers.wait.strategy.HostPortWaitStrategy@6692b6c6, logConsumers=[], createContainerCmdModifiers=[], tmpFsMapping=null, shouldBeReused=false, hostAccessible=false)`

**Comment by eddumelendez** [comment]
So, is it working? Then, can we close the issue?

Sorry, but I think I'm not following if there is anything else to review.

**Comment by Sanju98** [comment]
I'm building the container under @Container annotation of Jupiter test-container.
The above is the output of the Cassandra container. But it's not getting completed successfully

**Comment by eddumelendez** [comment]
Can you share logs?

**Comment by eddumelendez** [comment]
Please, share more information about how you are running the test, the steps, complete logs. Can you confirm you are not using Docker Desktop for Linux? In order to ser your installations run `docker context ls`. `/var/run/docker.sock` must exists in order to run Testcontainers.

**Comment by Sanju98** [comment]
I'm not using docker desktop
Output of `docker context ls`

NAME        DESCRIPTION                                            DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm

**Comment by Sanju98** [comment]
I'm using Bazel test to run the unit tests.

`
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
public class abcTest {
@Container
private static final CassandraContainer<?> cassandraContainer = new CassandraContainerBuilder() .includeTrigger() .withStartupTimeoutMinutes(5) .build();
}
@BeforeAll
    static void setupCassandraConnection() {
        session = cassandraContainer.getCluster().connect();
    }
@Test
////test case to execute some CQL queries
`

**Comment by eddumelendez** [comment]
In order to support this case, can you share a reproducible project with detailed instructions which I can try on my side, please?

**Comment by eddumelendez** [comment]
Information was not provided in the last 3 weeks. I am closing this. Feel free to reopen it adding a small github repository which can reproduce the issue.
