### ISSUE TITLE
[Bug]: k3s > 1.24.x will not start

### ISSUE THREAD

**Issue by twuyts** [testcontainers/testcontainers-java#6770]
### Module

K3S

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 20.04 on WSL2 on Windows 11

### Host Arch

x86

### Docker version

```shell
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

k3s testcontainer will not start. Log message: 
for k3s 1.25.x
```
no-deploy flag is deprecated. Use --disable instead.
```
for k3s 1.26.x
```
flag provided but not defined: -no-deploy
```

I traced it back to this line
https://github.com/testcontainers/testcontainers-java/blob/c90daab5d80adb692f213fa5f02c108a329105d5/modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java#L44

see also https://docs.k3s.io/reference/server-config#deprecated-options

Workaround is to use k3s<=1.24.x

**Comment by vcvitaly** [comment]
It seems to be a matter of starting a container with another flag as per this docs page:
https://docs.k3s.io/faq#how-can-i-use-my-own-ingress-instead-of-traefik

**Comment by eddumelendez** [comment]
Overriding `withCommand` should fix it. Still not sure how to fix it, we can use `ComparableVersion` but we can reach out the point of abusing of it at certain point.

**Comment by deftfitf** [comment]
In my case, it worked with `withCommand` as follows.

```kotlin
DockerImageName
    .parse("rancher/k3s:v1.25.10-k3s1"))
    .withLogConsumer(Slf4jLogConsumer(logger))
    .withCommand(
        "server",
        "--disable=traefik",
        "--tls-san=${DockerClientFactory.instance().dockerHostIpAddress()}")
```

**Comment by tgeens** [comment]
`k3s:v1.25.0` is more than a year old by now: https://github.com/k3s-io/k3s/releases/tag/v1.25.0%2Bk3s1

Can we move on and flip the switch, please ?
