### ISSUE TITLE
MySQLContainer junit Rule hangs if there is no jdbc-driver on classpath

### ISSUE THREAD

**Issue by isopov** [testcontainers/testcontainers-java#678]
This is clearly a user-error, but silent hanging without any errors is not an expected behavior.

**Comment by bsideup** [comment]
@stale keep it open

**Comment by mumukiller** [comment]
I checked this one. There is an duck tape issue here .https://github.com/rnorth/duct-tape/pull/5

**Comment by mumukiller** [comment]
@rnorth could you have a look at it, please?

**Comment by rnorth** [comment]
rnorth/duct-tape#5 is merged and will be added to Testcontainers in #1433.

I'll have a look and see if the issue still occurs with this PR.
