### ISSUE TITLE
[Feature]: Add support for CrateDB 

### ISSUE THREAD

**Issue by matriv** [testcontainers/testcontainers-java#6789]
### Module

New Module

### Problem

Currently [CrateDB](https://crate.io/products/cratedb) is not supported

### Solution

Add support for [CrateDB](https://crate.io/products/cratedb) is not supported

### Benefit

Be able to do integration testing with CrateDB through testcontainers

### Alternatives

-none-

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @matriv, I see the PR was already created. So, there is no need for an issue. Also, next time please consider open a discussion first.

**Comment by matriv** [comment]
@eddumelendez Thank you!

> Also, next time please consider open a discussion first.

Apologies, thought its was straightforward since I had a basic PR ready, and it's an addition of a new module.
