### ISSUE TITLE
Container is being killed after 10 minutes without any warnings/errors

### ISSUE THREAD

**Issue by isopov** [testcontainers/testcontainers-java#679]
Maybe 10 and more minutes long tests are not that common. But stopping underlying infrastructure without any error/warning pointing to configuration properties is not user-friendly.

Observed consistently with MySQLContainer.

**Comment by kiview** [comment]
Hi @isopov, which version of testcontainers are you using?
This should not happen, since the JVM ad the ryuk container (used for killing containers, introduced with 1.6.0.) communicate with each other to indicate a heartbeat like behaviour.

**Comment by isopov** [comment]
@kiview, sorry - have failed to reproduce it again. Finally I've found that exact test that failed for me at the time I reported this issue and found a very suspicious timeout of 10 minutes in it not related to testcontainers. It does not me such stacktrace mentioning testcontainers that it gave me that time, but I'm pretty sure that root of the problem was in it. Sorry again for this report.

**Comment by kiview** [comment]
Np, glad you could solve your problem.
