### ISSUE TITLE
[Enhancement]: Update to LocalStack 2.x

### ISSUE THREAD

**Issue by laszlovandenhoek** [testcontainers/testcontainers-java#6792]
### Module

LocalStack

### Proposal

The current version of LocalStack is 1.4. The next release will be 2.0, due next week:

https://github.com/localstack/localstack/issues/7882

This release contains changes that will break Testcontainers integration at some point in the future. In particular, the `HOSTNAME_EXTERNAL` environment variable that Testcontainers uses will be deprecated, to be replaced by `LOCALSTACK_HOST`.

In 2.0, the old `HOSTNAME_EXTERNAL` variable will continue working, so this will likely not start causing issues right away. But once this backwards-compatibility support is removed, the `localstack/localstack:latest` Docker tag (effectively their nightly build) will immediately be updated.

Therefore, people using Testcontainers with LocalStack using the `localstack:latest` will have their tests start failing at some point in the future. Even though using that tag is a bad idea, this likely applies to a non-trivial number of people, because the current default version is the ancient `0.11.2`, and many fixes have been added to LocalStack since. That in itself is a good reason to update.

The solution might be as simple as updating this constant (and checking all places that reference it):

https://github.com/testcontainers/testcontainers-java/blob/3b0c1cbbf798f69ff18c22fdb9c2ce7fb0390d2a/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L33

**Comment by cstmgl** [comment]
maybe this is the wrong place to point this out but would it be possible to make the configuration of the duration of the localstack startup configurable? I get a lot of problems when running it with the default timeout of 1 minute (maybe an issue in my infrastructure but I still would like to be able to configure it)

```
$ docker ps
CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS                             PORTS                                                NAMES
0fc422fc2ead        localstack/localstack:1.1                                   "docker-entrypoint.sh"   33 seconds ago      Up 33 seconds (health: starting)   4510-4559/tcp, 5678/tcp, 0.0.0.0:51660->4566/tcp     blissful_hellman
```

```
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Ready\.
```

**Comment by eddumelendez** [comment]
@laszlovandenhoek Thanks for sharing! I just started working on this and contacted the LocalStack team because found an issue. So, this will be take into account for next release.
