### ISSUE TITLE
[Feature]: Mosquitto MQTT Server

### ISSUE THREAD

**Issue by coiouhkc** [testcontainers/testcontainers-java#6793]
### Module

New Module

### Problem

Standalone lightweight MQTT server similar to https://github.com/quarkusio/quarkus/issues/29465

### Solution

Add specific Mosquitto Container.

### Benefit

Faster bootstrap of tests

### Alternatives

Use MQTT support of HiveMQ?

### Would you like to help contributing this feature?

Yes

**Comment by kiview** [comment]
Thanks for raising the issue. Looking at the implementation in Quarkus (https://github.com/quarkusio/quarkus/blob/9e6739bb7bad632557b9c802def9bead28cafc32/extensions/smallrye-reactive-messaging-mqtt/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/mqtt/deployment/MqttDevServicesProcessor.java#L264C7-L299), it seems using `GenericContainer` is good enough and very straight forward, so for now, I don't see the need for a specific Mosquito MQTT module within Testcontainers.
