### ISSUE TITLE
[Feature]: Customize docker registry for ryuk image when using default resource reaper

### ISSUE THREAD

**Issue by Zubastick** [testcontainers/testcontainers-java#6800]
### Module

None

### Problem

Its not possible to download ryuk image when proxy repositories are used due to Ryuk image location is hardcoded.

    RyukContainer() {
        super("docker-io.artifact.swissre.com/testcontainers/ryuk:0.3.4");

### Solution

Add environment variable that will allow to change it.

Similar issue was raised for dotnet implementation and they have resolved it:

https://github.com/testcontainers/testcontainers-dotnet/issues/483

### Benefit

Will be able to use Ryuk in company restricted environments

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Please, check the [docs](https://www.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names) `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX` is what you are looking for. If it is specific to ryuk then you can also use `ryuk.container.image`. See [customizing images](https://www.testcontainers.org/features/configuration/#customizing-images)

**Comment by Zubastick** [comment]
Thanks! It works.
