### ISSUE TITLE
establishing connection with privileged user (mysql)

### ISSUE THREAD

**Issue by dfreudenberger** [testcontainers/testcontainers-java#682]
Hi there,

is there any special reason why the connection is established with a user that has access to the test schema only? I'm working on an application that needs access to tables in different schemas and is using flyway to manage the migrations. Unfortunately flyway already fails because it is unable to create the schemas.

Happy to work on a pull request if this is open for change.

Best,
Daniel

**Comment by kiview** [comment]
Hi @dfreudenberger,

We are using the official [MySQL image](https://hub.docker.com/_/mysql/).
Testcontainers itself is not really establishing the connection, it provides accessors and convenience methods (`getJdbcUrl()`) to allow your  system to connect to database inside the container.

If you want root access to the database, you can use (the hardcoded) username "root" with password "test". Would this work for your use case? And does your use case involve creating different schemas?

**Comment by dfreudenberger** [comment]
Hey again,

adding user or password to the query string doesn't have any effect. I'll wait until the PR is merged and will provide a pull request afterwards.

Best

**Comment by patrickbray** [comment]
> If you want root access to the database, you can use (the hardcoded) username "root" with password "test". Would this work for your use case? And does your use case involve creating different schemas?

@kiview Sorry to comment on an old thread but your comment seems related to what I am trying to achieve here https://stackoverflow.com/questions/65031662/mysql-testcontainers-init-script-schema-creation-failing is there anyway to create schemas in a mysql test containers instance or do I need to run a custom image with these pre-created? 

I tried connecting as root / test but this seems to hang the container startup.
