### ISSUE TITLE
[Bug]: Update from 1.17.6 to 1.18.0: database is not cleaned between the tests (both Mongo and Postgres)

### ISSUE THREAD

**Issue by dmitry-weirdo** [testcontainers/testcontainers-java#6903]
### Module

Core

### Testcontainers version

1.18.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows, Linux

### Host Arch

x86

### Docker version

```shell
Latest on Windows, also within GitLab.
```

### What happened?

After updating testcontainers `1.17.6` → `1.18.0`, the tests are now failing with the database conflicts since the data created in one test-class (from the same class AND from the different class) are now preserved between tests.

It failed in our 2 different projects: one using `MongoDBContainer` and another one using `PostgreSQLContainer`.

`GenericContainer#shouldBeReused` was `false` and remains `false`.

Please provide the option to fix this behaviour as it was in `1.17.6`.

**Comment by eddumelendez** [comment]
Can you provide a simple project that reproduces the issue? Please, take into account that if you declare `static MongoDbContainer...` then the same instance would be used buy all your tests.
