### ISSUE TITLE
[Bug]: Unable to set -Dsolr.disable.allowUrls configuraton for Solr in Testcontainers 

### ISSUE THREAD

**Issue by MUsman1992** [testcontainers/testcontainers-java#6906]
### Module

Solr

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x86-64

### Docker version

```shell
v20.10.23
```

### What happened?

I am using testcontainer to start Solr for executing my test cases. I am unable to set `-Dsolr.disable.allowUrls` option with test containers. With docker, I have to simply give the following command to set the `-Dsolr.disable.allowUrls`  option 

`docker run -p 8983:8983 -v $PWD/:/var/solr/data -v $PWD/configsets:/opt/solr-9.1.1/server/solr/configsets/ -t solr -a "-Dsolr.disable.allowUrls=true"`

But when I use testcontainers for running Solr container while executing my tests, I am unable to set this configuration `-Dsolr.disable.allowUrls` I have tried to call the withCommand and withEnv functions using several ways but nothing worked

```
// solrContainer.withCommand("/bin/sh", "-c", "#(nop) ", "CMD [\\\"solr-foreground\\\"]" , "-a", "-Dsolr.disable.allowUrls=true" );
// solrContainer.withCommand("/bin/solr",  "-Dsolr.disable.allowUrls=true" );
// solrContainer.withCommand("-Dsolr.disable.allowUrls=true" );
// solrContainer.withCommand("-a", "-Dsolr.disable.allowUrls=true" );
// solrContainer.withEnv("SOLR_OPTS", "-Dsolr.disable.allowUrls=true");
// solrContainer.withEnv("-Dsolr.disable.allowUrls", "true");
// solrContainer.withEnv("JAVA_OPTS", "-Dsolr.disable.allowUrls=true");

```
Can anyone tell me how to solve this problem as I have already spent half of my day for figuring this out? I am not sure is it a bug or not ? Kindly guide me in this reagrd? Thanks

If I use this instruction
 `solrContainer.withEnv("SOLR_OPTS", "-Dsolr.disable.allowUrls=true");`
When I hit this url: http://localhost:63918/solr/domesticanimals/select?q=*:*&shards=localhost:63918/solr/domesticanimals,localhost:63918/solr/commonanimals
I get this error:
![230491876-a6a26461-7959-46f5-b6a1-1dd65e4481a2](https://user-images.githubusercontent.com/62036653/230511840-99c52030-2a8e-4684-b3b1-986f26aae558.png)
Otherwise, in rest of all cases I got error that I have to set this option to -Dsolr.disable.allowUrls to true                                                   
![image](https://user-images.githubusercontent.com/62036653/230511975-d8e216ff-302a-4902-8bcb-4f63d4729e15.png)

**Comment by eddumelendez** [comment]
Hi @MUsman1992, thanks for reporting this but I would appreciate if we can follow just one thread. Previously, there was an [open discussion](https://github.com/testcontainers/testcontainers-java/discussions/6902) and a [stackoverflow question](https://stackoverflow.com/questions/75952188/unable-to-pass-the-dsolr-disable-allowurls-true-configuration-to-the-solr-con) about this. I will close it as duplicate and follow the discussion until it can be triaged as an real issue.
