### ISSUE TITLE
[Enhancement]: Allow @Container to be used as a meta-annotation

### ISSUE THREAD

**Issue by philwebb** [testcontainers/testcontainers-java#6913]
### Module

Core

### Proposal

Currently the `@Container` annotation in `org.testcontainers.junit.jupiter` has `@Target(ElementType.FIELD)` which prevents it being used as a meta-annotation. If `ANNOTATION_TYPE` were also added it could be possible to create composable annotations.

The `TestcontainersExtension` class uses `AnnotationSupport.isAnnotated(field, Container.class)` which already checks for meta-presence of annotations.

**Comment by philwebb** [comment]
Thanks @eddumelendez!

**Comment by eddumelendez** [comment]
@philwebb this was released as part of 1.18.1
