### ISSUE TITLE
[Enhancement]: Allow setting networkMode via env vars

### ISSUE THREAD

**Issue by BhawaniSingh** [testcontainers/testcontainers-java#6916]
### Module

Core

### Proposal

Scenario: My CI has multiple docker network configured, and based on the environment configuration, java projects should build on a given docker network.

So if there's a possibilty to specify networkmode via env vars or testcontainers.properties then it would be great.

Also, this would allow ryuk to run on a specified docker network.

I could do the implementation for this feature

**Comment by eddumelendez** [comment]
I think there is nothing that prevent you to do it in the current state. You can set the network mode programatically and in this case you can read the env vars already.
