### ISSUE TITLE
[Enhancement]: Make entrypoint configurable

### ISSUE THREAD

**Issue by robmoore-i** [testcontainers/testcontainers-java#6919]
### Module

Core

### Proposal

Thank you for making TestContainers! It is an awesome piece of software that I really enjoy using. I especially like the  flexible and extensible interface of `GenericContainer`!

My enhancement request: I want to be able to configure `entrypoint`, not just `command`.

Some of my test application's images are used as the basis for multiple different containers, each with their own specified entrypoint. Currently it is possible to configure the _command_ of a Docker container, but it is not possible to configure the _entrypoint_, which makes it impossible to run containers which start up using a different entrypoint to the one specified by the image.

Workarounds:
- I can run the container using a ProcessBuilder with `docker run` where I can pass `--entrypoint` (this is what I am doing currently)
- I can change the image building process so that no default entrypoint is set (I don't want to do this because it will blow up the scope of testing required for what I am working on)

Let me know if any suggestions/questions. Thanks!

**Comment by eddumelendez** [comment]
Hi @robmoore-i, what you are asking is already supported. See the following example

https://github.com/testcontainers/testcontainers-java/blob/1bd177f01edcee893cd1a85dba2d88663c2885a0/modules/localstack/src/test/java/org/testcontainers/containers/localstack/LocalstackContainerTest.java#L259-L263

**Comment by robmoore-i** [comment]
Excellent! Thank you! This should probably be documented somewhere. This is where I would have expected to find it: https://www.testcontainers.org/features/commands/
