### ISSUE TITLE
[Enhancement]: JUnit 4 to JUnit 5 migration

### ISSUE THREAD

**Issue by nagkumar** [testcontainers/testcontainers-java#6921]
### Module

Core

### Proposal

Currently this code of an  example

https://github.com/testcontainers/testcontainers-java/tree/main/examples/redis-backed-cache

Upgrade examples to  JUnit 5, currently the code uses junit 4

**Comment by nagkumar** [comment]
![image](https://user-images.githubusercontent.com/332234/232227963-54747f3e-a772-47a3-ba48-b3d9d1f8f222.png)

![image](https://user-images.githubusercontent.com/332234/232227995-f7c60a66-77e1-45c5-b1fa-f6b88685f90b.png)

Observe the annotations and imports, all are junit 4

even the gradle dependency shows it as junit 4.x

![image](https://user-images.githubusercontent.com/332234/232228042-edb602da-c9b6-4fad-82fd-4c7292db330a.png)

**Comment by eddumelendez** [comment]
Thanks for raising this issue, @nagkumar. Would you like to contribute and update our examples with JUnit 5?

**Comment by nagkumar** [comment]
Sure @eddumelendez sure, if you could help with your thought process to achieve this I can follow the same, such as which first few example to start with.

**Comment by eddumelendez** [comment]
> * even to upgrade gradle groovy scripts to gradle kotlinDSLs too.
* Upgrade all the dependencies in gradle script up to date versions.

Those are no goals of he issue

> if you want to retain JUnit4 along with new JUnit5 examples

Let's just use one, in this case JUnit 5.

The order doesn't matter :) If you want to submit them all at once is ok or if do you prefer one by one, it is also ok. Just let us know here so others watching can consider it.

**Comment by nagkumar** [comment]
What is the purpose of 

testcontainers-java\docs\examples

![image](https://user-images.githubusercontent.com/332234/234749276-25b7ede2-385f-4fc0-88b7-6cfc1f61c529.png)

**Comment by nagkumar** [comment]
![image](https://user-images.githubusercontent.com/332234/234749917-fab0a84d-0b21-4b32-a9a9-b13894afefc4.png)

I would recommend upgrading of all the dependencies at least to the latest as we can avoid compatibility issues and some dependencies may more actively support junit 5 than junit 4.

I shall start with redis first to test the waters..

**Comment by nagkumar** [comment]
> > * even to upgrade gradle groovy scripts to gradle kotlinDSLs too.
> 
> * Upgrade all the dependencies in gradle script up to date versions.
> 
> Those are no goals of the issue
> 
> > if you want to retain JUnit4 along with new JUnit5 examples
> 
> Let's just use one, in this case JUnit 5.
> 
> The order doesn't matter :) If you want to submit them all at once is ok or if do you prefer one by one, it is also ok. Just let us know here so others watching can consider it.

Can you pl. review my PR for this migration https://github.com/testcontainers/testcontainers-java/pull/6950#partial-pull-merging

also likes to know if you have any timeline to pull this to main?

**Comment by nagkumar** [comment]
Please reply as I do the code review let me know if can close this from myside, as wish to get away from repeat work due to delays I do see code is changing rapidly, and conflict resolving can be big time waste for all of us.

**Comment by spyder-nj** [comment]
is this issue competed or anyone still working on it , please let me know , I a new in this , if no body still there , It can be assigned to me . Thanks

**Comment by nagkumar** [comment]
> is this issue competed or anyone still working on it , please let me know , I a new in this , if no body still there , It can be assigned to me . Thanks

pl take it forward from this PR, as I have been waiting for inputs from the team without luck https://github.com/testcontainers/testcontainers-java/pull/6950#partial-pull-merging

**Comment by eddumelendez** [comment]
That's not tru @nagkumar . There is one comment left as you can see [here](https://github.com/testcontainers/testcontainers-java/pull/7040#issuecomment-1567925512) It was marked as a resolve but it wasn't.

**Comment by kavyabala23** [comment]
can I proceed with this issue

**Comment by nagkumar** [comment]
> That's not true @nagkumar . There is one comment left as you can see [here](https://github.com/testcontainers/testcontainers-java/pull/7040#issuecomment-1567925512) It was marked as a resolve but it wasn't.

I am unable to know if each junit 5 jars should be added to each example or not and also, currently junit 4 jars are not part of these examples, unable to find where they are coming from.. did ask for the same in my pr info.. pl. check once at https://github.com/testcontainers/testcontainers-java/pull/7040

**Comment by kavyabala23** [comment]
ok sure

**Comment by nagkumar** [comment]
> currently junit 4 jars are not part of these examples

I per further study on this.. why these examples work in spite of junit 4 jars were not part of the gradle build scripts is gradle automatically includes junit 3 to 5 the latest versions

```
> Task :test
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
```

However including junit jars automatically would be deprecated from Gradle  9.x. Hope this clarifies the next person to take care of it accordingly..i.e. explicit inclusion of the junit files 

```
 testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
```

in each of the example.

**Comment by eddumelendez** [comment]
Closing due to it was fixed by https://github.com/testcontainers/testcontainers-java/pull/7417
