### ISSUE TITLE
[Bug]: junit-jupiter brings junit 4 transitvely

### ISSUE THREAD

**Issue by snicoll** [testcontainers/testcontainers-java#6934]
### Module

Core

### Testcontainers version

1.18.0

### Using the latest Testcontainers version?

Yes

### Host OS

MacOs

### Host Arch

x86

### Docker version

```shell
irrelevant
```

### What happened?

Adding a dependency on ` org.testcontainers:junit-jupiter:jar:1.18.0`  (at least with Maven) brings `junit:junit:jar:4.13.2` on the test classpath. 

### Relevant log output

```shell
\- org.testcontainers:junit-jupiter:jar:1.18.0:test
[INFO]    \- org.testcontainers:testcontainers:jar:1.18.0:test
[INFO]       +- junit:junit:jar:4.13.2:test
[INFO]       |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO]       +- org.apache.commons:commons-compress:jar:1.22:test
[INFO]       +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:test
[INFO]       |  \- org.jetbrains:annotations:jar:17.0.0:test
[INFO]       +- com.github.docker-java:docker-java-api:jar:3.3.0:test
[INFO]       |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.15.0-rc3:test
[INFO]       \- com.github.docker-java:docker-java-transport-zerodep:jar:3.3.0:test
[INFO]          +- com.github.docker-java:docker-java-transport:jar:3.3.0:test
[INFO]          \- net.java.dev.jna:jna:jar:5.12.1:test
```
```


### Additional Information

_No response_

**Comment by Jotschi** [comment]
The problem is also that you can't even manually exclude it. Somehow the testcontainer jupiter API indirectly references it and custom container classes can't be compiled without junit 4 being present on the classpath. The only solution I found is 
 to add junit 4 back to the classpath.

**Comment by hantsy** [comment]
I also found this issue, it is better to upgrade Junit 5 API and support Junit 4 using Junit 5 [Vintage Engine](https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine)

**Comment by ericdriggs** [comment]
Issue is that the core module has an api dependency on junit 4.

Recommended fix:
* bump api dependency to junit 5

see:
```
dependencies {
    api 'junit:junit:4.13.2'
```
https://github.com/testcontainers/testcontainers-java/blob/main/core/build.gradle#L72

**Comment by wakingrufus** [comment]
the specific issue is that `GenericContainer` extends `FailureDetectingExternalResource` which implements `TestRule` form junit4

**Comment by ericdriggs** [comment]
Yes, a fix would require a complete refactor from Junit4 TestRule to Junit5 AfterEachCallback and BeforeEachCallback.
Since there's no common interface, this would be a major version breaking change with the consequence of requiring Junit5 and not supporting Junit4 for version `2.*.*`

[implements AfterEachCallback, BeforeEachCallback](https://www.baeldung.com/junit-5-migration)

**Comment by Illutax** [comment]
Junit 5 also supports Junit 4 via VintageEngine. See the [Junit documentation](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4).

**Comment by ericdriggs** [comment]
It seems like vintage engine might provide value to testcontainers project as a transitionary point. From a client perspective it seems roughly equivalent, since the junit4 annotations are still used and you're effectively just shifting the name of the dependency artifact from `junit4` to `junit-vintage-engine`. Am I missing something?

**Comment by kiview** [comment]
Duplicates https://github.com/testcontainers/testcontainers-java/issues/970.

There are a couple of stub dependencies for JUnit4 out there, that can be used as a workaround (e.g. https://github.com/xdev-software/testcontainers-junit4-mock).
