### ISSUE TITLE
connecting containers using network

### ISSUE THREAD

**Issue by gadieichhorn** [testcontainers/testcontainers-java#697]
Hi,

I saw you deprecated docker links, how can I "link" few containers together for testing?
I have 2 containers that operates with "links" or with docker-compose service name. The container under tests needs another container to work. (like kafka needs zookeeper). It will use the service name to make network calls. 

Do I have to use the docker-compose option or is there a simpler way to define containers to see each other directly in test class code?

```
    @ClassRule GenericContainer a = GenericContainer("mycontainerA").withXXXX???
    @ClassRule GenericContainer b = GenericContainer("mycontainerB").withXXXX???
```

a working example would be great.

adding this example to the docs will be great :)

Thanks in advance.

**Comment by bsideup** [comment]
Hi @gadieichhorn,

Yes, links are deprecated. We recommend using Networks instead. Here are some examples for Kafka:
https://github.com/testcontainers/testcontainers-java/blob/02e38b4090155fca6246c08876f470e1f1ce5021/modules/kafka/src/test/java/org/testcontainers/containers/KafkaContainerTest.java

**Comment by kiview** [comment]
I'll close this in favor of #509.

**Comment by gadieichhorn** [comment]
Ok, thanks, that was helpful, 
... but I get this error...

I used similar code to your example link. any hint will be appreciated.

```
    @ClassRule
    public static Network network = Network.newNetwork();

    @ClassRule
    public static GenericContainer zookeeper = new GenericContainer("com.rds.observato/zookeeper:latest")
            .withNetwork(network)
            .withNetworkAliases("observato-zookeeper")
            .withExtraHost("vertx", "127.0.0.1");

    @ClassRule
    public static GenericContainer kafka = new GenericContainer("com.rds.observato/kafka:latest")
            .withNetwork(network)
            .withNetworkAliases("observato-kafka")
            .withExtraHost("vertx", "127.0.0.1");
```

>     19:24:47.927 [testcontainers-netty-1-6] INFO  c.r.o.k.KafkaContainerTest - STDOUT: 16:24:47.291 [main] INFO  c.r.o.z.ZookeeperMicroservice - Zookeeper started: 0
>     19:24:47.921 [testcontainers-netty-1-5] INFO  c.r.o.k.KafkaContainerTest - STDOUT: 16:24:47.814 [main] INFO  c.r.o.k.KafkaMicroservice - Starting Kafka
>     19:24:48.179 [testcontainers-netty-1-12] ERROR c.g.d.c.a.ResultCallbackTemplate - Error during callback
>     com.github.dockerjava.api.exception.DockerException: {"message":"network c600048f-a210-40fc-9791-4e8c0ccd14f2 id 32470e9b8c05c73e5703c2810d8faccb577cdd2b26d2aba1140c21889cb4381d has active endpoints"}
> 
>         at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:111)
>         at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
>         at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
>         at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>         at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
>         at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
>         at org.testcontainers.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
>         at org.testcontainers.shaded.io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
>         at org.testcontainers.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
>         at org.testcontainers.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
>         at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
>         at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
>         at java.lang.Thread.run(Thread.java:748)
>
