### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by schauder** [testcontainers/testcontainers-java#698]
I'm getting the exception mentioned in the subject when trying to start a 1.7.2 database container. 

It looks like some repackaging/shading doesn't work properly.

Inspecting the jar with my IDE shows that there is a `org.testcontainers.shaded.org.apache.commons.lang.StringUtils` in the jar `testcontainers-1.7.2.jar`
but `ScriptUtils` from `database-commons-1.7.2.jar` tries to import `org.apache.commons.lang.StringUtils`. Again looking at the decompiled version in my IDE.

**Comment by bsideup** [comment]
Hi @schauder,

This duplicates #656, which is already fixed in master and will be released later today

**Comment by hartmut-nex** [comment]
confirm works for me with `1.7.3`

**Comment by rfelgent** [comment]
I have this problem now with versin 1.11.0 and 1.11.1 of test container.

should i open a new ticket?

**Comment by bsideup** [comment]
@rfelgent it was fixed in 1.11.2, see #1342

**Comment by rfelgent** [comment]
thx for the hint @bsideup . i will give it a try.

**Comment by jbx1** [comment]
This issue has reappeared since version 1.17.0, and is still there in versions 1.18.3 and 1.19.3

A class (in test scope) that imports `org.apache.commons.lang3.StringUtils` causes this compilation error: 
```
package org.testcontainers.shaded.org.apache.commons.lang` does not exist
org.testcontaienrs.shaded.org.apache.commons.lang.StringUtils
```

The issue goes away when downgrading to 1.16.3. 

Using `org.testcontainers:mysql` on java 11, running on MacOS (M1).
