### ISSUE TITLE
[Enhancement]: support SSH contexts

### ISSUE THREAD

**Issue by trajano** [testcontainers/testcontainers-java#7007]
### Module

Core

### Proposal

Similar to https://github.com/testcontainers/testcontainers-java/issues/5837 but I am thinking of using SSH context also provide the necessary capability using SSH to provide tunnels to the remote services for testing.

Also similar to https://github.com/testcontainers/testcontainers-node/issues/169 which was closed for inactivity and I am looking for a Java solution.

The SSH tunnel requirement should *not* be mandatory unless we expose ports and have to access the exposed ports.  This is to simply test if the service comes up and passes their healthcheck.

This will allow me to have a Docker machine outside of my laptop to run my services and free up resources on my laptop.

I am pretty sure it's not working with the context as I use because when I execute the test and do `docker ps`  after I use `docker context use [remote]`

I have also tested setting the `DOCKER_HOST` environment variable for the test and it still uses the local one.

**Comment by eddumelendez** [comment]
Please check https://github.com/testcontainers/testcontainers-java/pull/5039#issuecomment-1039041020
