### ISSUE TITLE
`KafkaContainer` with Kraft mode enabled fails using `confluentinc/cp-kafka:7.4.0`

### ISSUE THREAD

**Issue by eddumelendez** [testcontainers/testcontainers-java#7010]
`KafkaContainer` works with `confluentinc/cp-kafka:7.3.3` and fails with `confluentinc/cp-kafka:7.4.0`

output:

```
`23:59:22.222 ERROR tc.confluentinc/cp-kafka:latest - Log output from the failed container:
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
Running in KRaft mode...
CLUSTER_ID is required.
Command [/usr/local/bin/dub ensure CLUSTER_ID] FAILED !
```

_Originally posted by @eddumelendez in https://github.com/testcontainers/testcontainers-java/discussions/6915#discussioncomment-5801560_

**Comment by samnayak1** [comment]
How did you fix this? @eddumelendez

**Comment by BharatNandanvar409** [comment]
How to fix this issue??
