### ISSUE TITLE
[Enhancement]: Cassandra 4 support

### ISSUE THREAD

**Issue by wakingrufus** [testcontainers/testcontainers-java#7012]
### Module

Cassandra

### Proposal

I noticed the cassandra container only supports 2.x and 3.x. I'd like to see support for Cassandra server 4.x
I would be willing to help with this. I have experience getting cassandra 4 to run: https://github.com/jsevellec/cassandra-unit/pull/325
but I am not familiar with testcontainer's code base.

**Comment by eddumelendez** [comment]
Hi @wakingrufus, thanks for the offer! We already have [tests](https://github.com/testcontainers/testcontainers-java/blob/main/modules/cassandra/src/test/java/org/testcontainers/containers/CassandraDriver4Test.java) running with Cassandra 4. or are you talking about the `withInitScript()` support?

**Comment by wakingrufus** [comment]
> Hi @wakingrufus, thanks for the offer! We already have [tests](https://github.com/testcontainers/testcontainers-java/blob/main/modules/cassandra/src/test/java/org/testcontainers/containers/CassandraDriver4Test.java) running with Cassandra 4. or are you talking about the `withInitScript()` support?

I am not referring to cassandra datastax driver 4, but cassandra _server_ 4

**Comment by eddumelendez** [comment]
can you elaborate on what's missing in CassandraContainer to work with cassandra 4?

**Comment by eddumelendez** [comment]
> Ill try using it with a casandra4 image and report back my results

Thank you!
