### ISSUE TITLE
[Enhancement]: Override toString() for ChainedImageNameSubstitutor to return type of "wrapped" ImageNameSubstitutor

### ISSUE THREAD

**Issue by jxblum** [testcontainers/testcontainers-java#7039]
### Module

Core

### Proposal

If users [configure](https://github.com/spring-projects/spring-boot-data-geode/blob/main/spring-geode-project/spring-geode/src/test/resources/testcontainers.properties#L3) a custom `ImageNameSubstitutor` (for [example](https://github.com/spring-projects/spring-boot-data-geode/blob/main/spring-geode-project/spring-geode/src/test/java/example/app/crm/config/testcontainers/VmwHarborProxyImageNameSubstitutor.java)), then this instance will get [wrapped](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/ImageNameSubstitutor.java#L51-L55) by Testcontainers when the configuration is [evaluated](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/ImageNameSubstitutor.java#L29-L56).

If an error occurs, regardless of context (in my case, I am using Spring) then the "configured" `ImageNameSubstitutor` in the `RemoteDockerImage` instance created from an `DockerImageName` by the container, is quite "cryptic":

```
2023-05-13 02:44:13,155 ERROR g.springframework.boot.SpringApplication: 822 - Application run failed
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'CassandraContainer' defined in example.app.crm.config.TestcontainersCassandraConfiguration: 
Failed to instantiate [org.testcontainers.containers.GenericContainer]: Factory method 'cassandraContainer' threw exception with message: 
Can't get Docker image: RemoteDockerImage(
  imageName=cassandra:3.11.15, 
  imagePullPolicy=DefaultPullPolicy(), 
  imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@4904144d
)
```

It is not apparent from this ERROR log output whether the custom `ImageNameSubstitutor` was actually in use here, and users have to make an effort (logging, debugging, etc) to determine if the custom `ImageNameSubstitutor` was actually applied or not.

In my case, I had to add logging to my "custom" `ImageNameSubstitutor` to determine whether it was actually being applied and used by Testcontainers during Docker Image Name resolution since my library was being built remotely in a Jenkins CI environment where debugging is nearly impossible.

This:

```
imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@4904144d
```

... is quite useless.

The `toString()` method of the static inner `ChainedImageNameSubstitutor` class ([source](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/ImageNameSubstitutor.java#L131-L158)) could be overridden to return `getDescription()` ([source](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/ImageNameSubstitutor.java#L150-L157)).

Altneratively, the `ImageNameSubstitutor` abstract class could override the `toString()` method to return `getDescription()`, like so:

```java
abstract class ImageNameSubstitutor {

  @Override
  public String toString() {
    return getDescription();
  }
}
```

In this way, all extensions of `ImageNameSubstitutor` would benefit and also be consistent without any extra effort on behalf of your users.

**Comment by eddumelendez** [comment]
Hi @jxblum, Testcontainers for Java 1.19.1 was just released and contains this change. Thanks for the report.

**Comment by jxblum** [comment]
Hi @eddumelendez - Thank you so much.
