### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rd-rosen-ivanov** [testcontainers/testcontainers-java#7057]
### Module

Core

### Testcontainers version

1.18.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Docker version 23.0.6, build ef23cbc431
```

### What happened?

I am using MuSQL 5.7.
The generated column do not work when is used in integration test with org.testcontainers:mysql:1.18.1.

Column targets contains arrays of JS objects with attribute like this: [{"attributeName": "some value"}]
Lets add new column that have to be generated based on the previous column: ALTER TABLE table1 ADD some_field1 TEXT GENERATED ALWAYS AS (JSON_UNQUOTE(targets-> '$**.attributeValue')) STORED;
When the test runs and value is inserted into the table nothing is stored in some_field1. 

### Additional Information

Sorry if this is not a bug, but feature that is not enabled or implemented.

**Comment by eddumelendez** [comment]
Hi, Can you share a small project to reproduce the issue, please?

**Comment by rd-rosen-ivanov** [comment]
Hi @eddumelendez 
I am so sorry but I cannot just post my project since it is company owned and the time for setup of new one is nothing I have now, so if this issue is not helpful for you feel free to just close it as not reproducible.

Best regards
Rosen Ivanov
