### ISSUE TITLE
[Bug]: LocalStackContainer is deleted after test when withReuse is true

### ISSUE THREAD

**Issue by axeleroy** [testcontainers/testcontainers-java#7097]
### Module

LocalStack

### Testcontainers version

1.18.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I'm trying to debug my LocalStack container in a CI environment and for that I would like it to not be deleted after the tests so I can read its logs after.

I followed the steps described in the [doc](https://www.testcontainers.org/features/reuse/), which means opting-in Reusable Containers (`testcontainers.reuse.enable=true` in `~/.testcontainers.properties`), adding `withReuse(true)` and starting the container manually:
```java
LocalStackContainer localStackContainer =
    new LocalStackContainer(DockerImageName.parse("localstack/localstack:2.0.2"))
        .withServices(
            Service.DYNAMODB,
            LocalStackContainer.EnabledService.named("events")
        )
        .withClasspathResourceMapping("testcontainers/init-scripts", "/etc/localstack/init/ready.d",
            BindMode.READ_ONLY)
        .withEnv("DEBUG", "1")
        .withEnv("HOSTNAME", "localstack")
        .withEnv("HOSTNAME_EXTERNAL", "localstack")
        .withEnv("SKIP_SSL_CERT_DOWNLOAD", "true")
        .waitingFor(Wait
            .forLogMessage(".*localstack just finished starting.*", 1))
        .withStartupTimeout(Duration.ofMinutes(10))
        .withReuse(true);
localStackContainer.start();
```

But unfortunately, after the tests ran, `docker ps -a` doesn't show any localstack container.

### Additional Information

We are using Gradle and Junit Jupiter on a Spring Boot 2.7 project

```groovy
implementation "org.testcontainers:testcontainers:1.18.3"
implementation "org.testcontainers:junit-jupiter:1.18.3"
implementation "org.testcontainers:localstack:1.18.3"
```

**Comment by ClaudenirFreitas** [comment]
Reusable Containers is an Experimental feature and there is a note in the docs too.

> Reusable containers are not suited for CI usage and as an experimental feature not all Testcontainers features are fully working (e.g., resource cleanup or networking).

I believe the team is working on this feature.

**Comment by eddumelendez** [comment]
I'm not able to reproduce either. Please, make sure Reuse is what you need, take a look at [Singleton Container Pattern](https://java.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers).

Feel free to reopen the issue adding a reproducible project and more info.
