### ISSUE TITLE
testcontainers gradle plugin - integration tests

### ISSUE THREAD

**Issue by gadieichhorn** [testcontainers/testcontainers-java#711]
Need some help with gradle java plugin. Anyone here has experiance with gradle sourceset?

 https://github.com/gadieichhorn/gradle-java-multimodule/tree/master/buildSrc

> ./gradlew clean build e2e

still getting some exceptions with missing dependencies.

```
...

/home/geichhorn/Develop/github/gradle-java-multimodule/deploy/rest/src/integration/java/com/rds/example/gradle/deploy/DeployTest.java:16: error: cannot find symbol
    private static GenericContainer main = new GenericContainer("com.rds.example.gradle/rest:latest")
                                               ^
  symbol:   class GenericContainer
  location: class DeployTest

...

```

**happy to contribute this plugin to the project :)**
  
1. have a seperated sourcestet for integration tests (with testcontainers)
2. seperate gradel task for running these tests ('e2e')

**Comment by kiview** [comment]
Hey @gadieichhorn, 
sorry I have no experience in writing Gradle plugins.

What's the actual use case of the plugin? We are using the same approach using https://github.com/unbroken-dome/gradle-testsets-plugin, which works quite fine.

**Comment by gadieichhorn** [comment]
Thanks @kiview on wich project are you using it?

My use case is to seperate my testcontainers integration tests from all other build/test cycle. Integration tests depends on the docker build so it must run after it.

**Comment by kiview** [comment]
We are using it like this at work.

Check out the plugin, it should fit your usecase 100%, no need to write a custom plugin then.

**Comment by kiview** [comment]
I close this issue, hope the plugin solved your problem @gadieichhorn.
