### ISSUE TITLE
[Enhancement]: KafkaContainer should provide a method that allows creation of topics

### ISSUE THREAD

**Issue by trajano** [testcontainers/testcontainers-java#7161]
### Module

Kafka

### Proposal

To address the issue of https://github.com/testcontainers/testcontainers-java/issues/3647

I'd like the KafkaContainer API to provide a method like
```
.withTopic(String topicName, boolean compact, int numberOfPartitions)
```
and an alias

```
.withTopic(String topicName) // which translates to 
.withTopic(topicName, true, 1)
```

For security, Kafka may be configured to NOT allow any topics to be dynamically created when a message is sent the first time.

**Comment by eddumelendez** [comment]
This can be done through the `kafka.execInContainer(...)`, right?

**Comment by eddumelendez** [comment]
Closing due to this is currently can be performed by `execInContainer`. So far, there are no plans to add such helper methods due to it will be coupled to the `cli` provided by the image.
