### ISSUE TITLE
problem starting containers with docker-machine

### ISSUE THREAD

**Issue by adriancole** [testcontainers/testcontainers-java#717]
getting the following with latest (1.7.3)

```
18/05/30 16:21:28 INFO DockerClientFactory: Docker host IP address is 192.168.99.100
18/05/30 16:21:28 INFO DockerClientFactory: Connected to docker: 
  Server Version: 18.05.0-ce
  API Version: 1.37
  Operating System: Boot2Docker 18.05.0-ce (TCL 8.2.1); HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
  Total Memory: 2002 MB
18/05/30 16:21:40 INFO DockerClientFactory: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
        ✔ File should be mountable
---snip---
Caused by: com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"chdir to cwd (\\\"/root\\\") set in config.json failed: permission denied\": unknown"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:99)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
```

I am able to use docker normally ex with zipkin's docker-compose file

**Comment by rnorth** [comment]
Ouch, thank you for reporting and sorry you hit this. I'll try and reproduce; from the error it looks like Testcontainers and/or docker-java is trying to do something that's no longer possible in docker-machine.

As a workaround, do you have Docker for Mac (/Windows?) available to try?

**Comment by bsideup** [comment]
Hey @adriancole, I have a feeling that it relates to #680 :(
Apparently they released `18.05.0-ce` with a regression inside :(

May I kindly recommend you to try Docker for Mac? It's proven to be MUCH more stable (and faster)

**Comment by bsideup** [comment]
@adriancole FYI 18.05 is "edge" release, the latest stable is 18.03.1:
https://docs.docker.com/release-notes/docker-ce/

**Comment by adriancole** [comment]
ok suppose toolbox gave me a crap version. thanks for getting some quick
advice.

I will give docker mac a try again later.. I didn't like how it used to
clash with my local services which is why I was using the machine which
while slow was ok before.

**Comment by bsideup** [comment]
@adriancole I think there are some reports of that regression on SO as well:
https://stackoverflow.com/questions/50325096/grafana-5-1-0-docker-image-permission-issue

could you please run the following commands to verify it?
```
$ mkdir data
$ docker run -ti -p 3000:3000 --entrypoint bash --volume "$PWD/data:/var/lib/grafana" grafana/grafana:5.1.0

$ ls /var/lib/grafana
```

**Comment by rnorth** [comment]
Based on the error message alone it looks like moby/moby#32708.

That was first reported back on 17.03, more than a year ago, so I'm skeptical that it's going to be the same actual cause in our case. Still, maybe this ticket will give us some clues.

**Comment by adriancole** [comment]
heh regular docker works for me now.. I'll try docker-machine tomorrow with
the command you mentioned!

**Comment by bsideup** [comment]
@adriancole thanks! We're checking what's wrong with the edge Docker anyways, but, in general, highly recommend running Docker for Mac :)

**Comment by adriancole** [comment]
using docker-machine...

```bash
○ → docker run -ti -p 3000:3000 --entrypoint bash --volume "$PWD/data:/var/lib/grafana" grafana/grafana:5.1.0
Unable to find image 'grafana/grafana:5.1.0' locally
5.1.0: Pulling from grafana/grafana
2a72cbf407d6: Pull complete 
89f824064239: Pull complete 
b90280be2e0d: Pull complete 
Digest: sha256:a6b37f9afdd9782f1e6264acaf3b09519aad454f34ca6b0e863dd9873e11fa67
Status: Downloaded newer image for grafana/grafana:5.1.0
grafana@7aaf88a18a3f:/$ ls /var/lib/grafana
grafana@7aaf88a18a3f:/$
```

**Comment by bsideup** [comment]
@adriancole did you create `data` folder on host before running the command?

**Comment by adriancole** [comment]
yep
