### ISSUE TITLE
Add UDP support for InfluxDB module

### ISSUE THREAD

**Issue by fsanaulla** [testcontainers/testcontainers-java#719]
I can help with it.

**Comment by kiview** [comment]
Hi @fsanaulla,
 of course, help is very much appreciated. But does the official influxdb image offer support for exposing it over UDP?

**Comment by fsanaulla** [comment]
Hello @kiview. I think there is no limitation in using env variables, that can be the way of configuring UDP section.

**Comment by rnorth** [comment]
@fsanaulla are you still willing to contribute this, or should we close? It doesn't seem that anybody else has been asking for this.

**Comment by fsanaulla** [comment]
@rnorth it can be emulated by using docker-compose [link](https://github.com/fsanaulla/chronicler/blob/master/modules/udp/src/it/scala/com/github/fsanaulla/chronicler/udp/UdpClientSpec.scala).
Thank you!
