### ISSUE TITLE
[Enhancement]: Let database name be configurable in OracleContainer

### ISSUE THREAD

**Issue by aalmiray** [testcontainers/testcontainers-java#7190]
### Module

Oracle-XE

### Proposal

When using the `oracle-xe` images the default database name is `XEPDB1`.
When using the `oracle-free` images the default database name _should_ be `FREEPDB1`.

At the moment `XEPDB1` is always assumed which means `oracle-free` images can't be used with default values. One must configure a random database name for the correct value to be picked up.

Add an option to define the default database name, opting for `XEPDB1` or `FREEPDB1` if none selected. A test on the image name could be applied to determine which default database name should be chosen, that is, if it matches/contains `gvenzl/oci-oracle-free` then `FREEPDB1` is chosen, otherwise default to `XEPDB1`.

Follow up to https://github.com/spring-projects/spring-data-relational/issues/1528

**Comment by eddumelendez** [comment]
Thanks for raising the issue, @aalmiray. There is a current conversation going on with @gvenzl about the support for `Oracle Free`. I think this issue falls there

**Comment by gvenzl** [comment]
Yeah, let's use this issue here to document the progress of the discussion, @eddumelendez, as Spring wishes to monitor the outcome.

**Comment by aalmiray** [comment]
🚀
