### ISSUE TITLE
DockerComposeContainer uses `up -d` to start containers

### ISSUE THREAD

**Issue by iikirilov** [testcontainers/testcontainers-java#722]
How do I get access to the container logs? I have a complex case where I need to run a set of containers and wait until one of those containers logs "BOOTED" before then start some other containers. However there is no access to these logs. I have noticed that the containers are brought up with the the "-d" flag which hides the output of the containers. Is there a way to override this?

```
    @ClassRule
    public static TestRule startContainers() throws TimeoutException {
        WaitingConsumer consumer = new WaitingConsumer();
        serviceRegistry = new DockerComposeContainer(SERVICE_REGISTRY).withPull(false).withTailChildContainers(true).withLogConsumer("service", consumer);
        serviceRegistry.starting(Description.EMPTY);
        consumer.waitUntil(frame ->
                frame.getUtf8String().contains("BOOTED"), 5, TimeUnit.MINUTES);
        // start my other containers
    }
```

Using the code above I can only see that my containers are created, but the output from my containers are not visible. Manually running `docker attach <my_container_name>` does show output and the containers are being brought up correctly. The tip in #352 did not work for me.

**Comment by iikirilov** [comment]
This is what I am currently doing, however for one of the containers I need to override the entrypoint which I can't figure out how to do with GenericContainer.
```
container = new GenericContainer("mycontainer")
                .withNetworkMode("host")
                .withCommand("exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar arg");
```
does not override the entrypoint.

**Comment by kiview** [comment]
Hi @iikirilov, 
in order to override the the entrypoint, you need to use a `withCreateContainerCmdModifier`, like this:

```
container = new GenericContainer("mycontainer")
                .withNetworkMode("host")
                .withCreateContainerCmdModifier(cmd -> 
                    cmd.withEntrypoint("exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar arg"));
```

I'm not sure if the variable is expaned. As a workaround, you could try to use the `_JAVA_OPTIONS` environment variable (see https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts).

**Comment by iikirilov** [comment]
Thanks - I have revisited this and your suggestions are useful!
