### ISSUE TITLE
[Feature]:  allow to connect to already running container 

### ISSUE THREAD

**Issue by soulseekeer24** [testcontainers/testcontainers-java#7220]
### Module

None

### Problem

my cicd is kinda slow when multiple container and its throw a timeout for some images,

### Solution

if i can start the containers before calling the test command in gradle  and my test container can connect to this container i just started before it will solve some problems

### Benefit

a feature that may be used for improve cicd times

### Alternatives

some of the container image like mongo db dont allow to modify timeouts if those image allow me to set those timeout would be a solution for my problem

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Can you elaborate more on your current setup? Are you using a container per test method, per test class, [singleton containers](https://java.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers)?

**Comment by eddumelendez** [comment]
Closing due to no reply.
