### ISSUE TITLE
[Bug]: Default MSSQL username is `sa` not `SA`

### ISSUE THREAD

**Issue by Eng-Fouad** [testcontainers/testcontainers-java#7237]
### Module

MSSQLServer

### Testcontainers version

1.18.3

### Using the latest Testcontainers version?

Yes

### Host OS

Any

### Host Arch

Any

### Docker version

```shell
24.0.2
```

### What happened?

If `MSSQL_COLLATION` is set to a collation with case-sensetive (`_CS` not `_CI`), the username `SA` will fail to login to DB, as `sa` is the correct username.

    mssqlServerContainer.addEnv("MSSQL_COLLATION", "Arabic_100_CS_AS_KS_WS_SC_UTF8");

**Comment by eddumelendez** [comment]
Hi, thanks for raising the issue. But, no need to do it if a PR is coming afterwards.
