### ISSUE TITLE
useUnicode & characterEncoding parameters are ignored for TC_INITSCRIPT

### ISSUE THREAD

**Issue by dmart28** [testcontainers/testcontainers-java#727]
Hi!

We've noticed that starting from 1.7.0+ releases the `useUnicode` and `characterEncoding` JDBC params in the JDBC URL are being ignored while executing TC_INITSCRIPT. Probably, other params are being ignored as well. As a result, if we have some, for example, russian symbols in the init SQL file, they are passed to the MySQL as a '?' signs, while on the 1.6.0 version it's not the case. Can you suggest what's the problem, is it a bug indeed?

Thanks!

**Comment by rnorth** [comment]
Hi @dmart28 - thanks for reporting and for the PR, and sorry for taking time to follow up. I wonder if this might be resolved by the much bigger refactoring within #617. 

In any case, please could you show us a failing test that we could use to check?

**Comment by dmart28** [comment]
Hi @rnorth - I've added a test to my PR which will fail without such fix. I've also checked #617 code and it doesn't seem to me that this issue is resolved here.

**Comment by rnorth** [comment]
Released in [1.8.1](https://github.com/testcontainers/testcontainers-java/releases/tag/1.8.1)! 🎉

Thanks for your work to fix this @dmart28.
