### ISSUE TITLE
[Enhancement]: Add the ability to specify an image's platform.

### ISSUE THREAD

**Issue by shawjef3** [testcontainers/testcontainers-java#7312]
### Module

Core

### Proposal

It's possible to specify the platform for a container by using `GenericContainer#withCreateContainerCmdModifier`.
However, it's not possible to do the same when creating an image, and so it's
not possible to both create and test an image for a platform.

Add `ImageFromDockerfile#withBuildImageCmdModifier` which will make this possible.

**Comment by eddumelendez** [comment]
Hi @shawjef3, thanks for the proposal. However, for further reference, it would be ideal to discuss about this via GH Discussions and then we can decide if proceed or not with it and create an issue.

I'm closing this due to there is already an PR created.

**Comment by shawjef3** [comment]
@eddumelendez https://github.com/testcontainers/testcontainers-java/discussions/7315
