### ISSUE TITLE
[Bug]: Container re-use: serialising CreateContainerCmd sometimes results in a different hash for the same container

### ISSUE THREAD

**Issue by rcgeorge23** [testcontainers/testcontainers-java#7325]
### Module

Core

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Macos

### Host Arch

x86

### Docker version

```shell
$ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.14.1 (91661)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Container re-use feature doesn't always re-use existing containers, even though the create command is identical to the create command of the previous run.

I believe there is an issue with the way the command's hash is evaluated in `GenericContainer.hash(...)`:

```
...
        byte[] commandJson = dockerClientConfig
            .getObjectMapper()
            .copy()
            .enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
            .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS)
            .writeValueAsBytes(createCommand);
...
```

When the command is serialised, we attempt to sort the json, however the sorting options provided to object mapper do not sort the contents of json arrays in the serialised command.

So the first time we generate the hash, we might be basing it on a command that looks like this:
```
...
   "Env":[
      "KAFKA_BOOTSTRAP_SERVERS=tc-3d444017:9092",
      "CONFLUENT_SCHEMA_REGISTRY_URL=http://tc-a90729fc:8081"
   ],
...
```
The second time we generate the hash for the same command, an array might be ordered differently:
```
...
   "Env":[
      "CONFLUENT_SCHEMA_REGISTRY_URL=http://tc-a90729fc:8081"
      "KAFKA_BOOTSTRAP_SERVERS=tc-3d444017:9092",
   ],
...
```
This obviously results in (sometimes) producing a different hash, and another copy of the same container being spun up.

**Comment by eddumelendez** [comment]
You can see a workaround for this [here](https://github.com/eddumelendez/spring-boot-kafka-testcontainers-reusable-mode/blob/main/producer/src/test/java/com/example/container/KafkaRaftWithExtraListenersContainer.java) then you can declare [kafka container](https://github.com/eddumelendez/spring-boot-kafka-testcontainers-reusable-mode/blob/main/producer/src/test/java/com/example/producer/ProducerApplicationTests.java#L71-L78) and [schema registry](https://github.com/eddumelendez/spring-boot-kafka-testcontainers-reusable-mode/blob/main/producer/src/test/java/com/example/producer/ProducerApplicationTests.java#L82-L93)

**Comment by rcgeorge23** [comment]
Perhaps I haven’t explained the issue very well.

This isn’t related to Kafka, those were just some environment variables I used to illustrate the point.

The issue is that when the create container command is serialised to json, any data contained in an array is not deterministically sorted, so the hash obtained on one occasion may not be the same as the hash obtained on a subsequent occasion.

**Comment by eddumelendez** [comment]
Hi, Can you share a minimal project that reproduces the issue. Based on the issue description the issue is related to the dynamic network [here](https://github.com/testcontainers/testcontainers-java/blob/main/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L163)

**Comment by rcgeorge23** [comment]
Ok, so I have now managed to work around this issue.

When creating a new instance of `GenericContainer`, if I pass a `LinkedHashMap` rather than a regular `HashMap` into `withEnv(...)`, then the ordering of the environment variables block in the create container command is consistent between test runs.
