### ISSUE TITLE
[Bug]: Testcontainers setting reuse containers to enabled overwriting user config

### ISSUE THREAD

**Issue by jogerj** [testcontainers/testcontainers-java#7330]
### Module

PostgreSQL

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

No, Quarkus bundled Testcontainers

### Host OS

Windows 11

### Host Arch

x86-64

### Docker version

```shell
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I noticed Testcontainers created a `~/testcontainers.properties` file and it resulted in containers not shutting down because it set reuse to true, but especially PostgreSQL container for some reason. I changed the file and set the value to falsel, but after some time I noticed the problem occuring again and the file was indeed overwritten by Testcontainers (with new timestamp).

Expected:

Testcontainers should not overwrite configuration files set by the user.

### Relevant log output

```shell
#Modified by Testcontainers
#Mon Jul 24 19:53:41 CEST 2023
docker.client.strategy=org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy
testcontainers.reuse.enable=true
```

**Comment by eddumelendez** [comment]
I can not reproduce the issue as we don't have any reference to set the value to true.

I found one in quarkus https://github.com/quarkusio/quarkus/blob/740e13ab4cd6350b995e819af54ae67bd71801b0/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L92
