### ISSUE TITLE
[Bug]: Kafka module cannot find java class written using java 17

### ISSUE THREAD

**Issue by alutski** [testcontainers/testcontainers-java#7331]
### Module

Kafka

### Testcontainers version

1.18.3

### Using the latest Testcontainers version?

Yes

### Host OS

WSL2 on Windows, Linux

### Host Arch

x64

### Docker version

```shell
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
```

### What happened?

Dear TestContainers team, it might be not a bug so if it's necessary please downgrade it.

We use Kafka TestContainers module and it helps us very much. Thank you for your work.

**Could you please tell me did you have any specific issues/challenges making Kafka test containers (TC) workable for java17. It looks like that Kafka TestContainers module cannot find the jar compiled using java 17.**

Let me explain the reason for this question.
Our project is Single Message Transfofmation(SMT) which is a part of Kafka Confluent Connect platform. SMT is a java class packed in jar file, when it's provided to Kafka Confluent Connect it's picked and used during a message processing. The project is written in java 8 and we use TestContainers to test it. 
For our tests we created a wrapper around `org.testcontainers.containers.GenericContainer` and build our own Kafka Confluent Connect container using `org.testcontainers.images.builder.ImageFromDockerfile`. We do it this way:
```
ImageFromDockerfile()
.withDockerfileFromBuilder { builder ->
builder
.from("artifacts.cf.saxo/docker/confluentinc/cp-kafka-connect:$confluentVersion")
```

Our tests work perfect. SMT jar is copied into the container and works as expected. All this work was done using java 8.

Now we decided to migrate our SMT which is written in java 8 and tested using TestContainers to java17 because java8 won't be supported by Confluent after version 7.4.

We use maven to build the SMT project. We built a new jar file compiled using java 17, we checked the jar on the real environment with Confluent platform run on java 17 and it works correctly.
The problem is that our TestContainers tests which reproduce the same flow we have on the real environment are failing now,  saying that a class from jar file cannot be found.  I've checked the jar, the class is there. **It looks like that Kafka TestContainers module cannot find the jar compiled using java 17.**

The only difference in two versions of our SMT project is the java version which is used and it's handled by maven plugin, all other dependencies are the same: we use the same version of TestContainers, we import the same library.
         
         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

	
we changed the config to be build using java17		
	
          <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>

The logic is the following:

1. we create Kafka Confluent Connect TC from docker image
2. copy the generated smt jar inside the container
3. communicate with Kafka Confluent Connect during the tests 

I understand that the question is a bit generic but may be you can give any hint which can lead to the described above experience.

Any obstacles which you overcame making TestContainers workable for java 17 would be really great to know.

Kind regards,
Anatol Lutski

**Comment by eddumelendez** [comment]
I saw a discussion was created https://github.com/testcontainers/testcontainers-java/discussions/7332 I'll close this and reopen if we found and issue in the library during the discussion.
