### ISSUE TITLE
[Enhancement]: Switch from Google SDK to Google CLI and update Google Client Libraries BOM

### ISSUE THREAD

**Issue by ddobrin** [testcontainers/testcontainers-java#7340]
### Module

GCloud

### Proposal

The dependencies must be updated to use the Google Cloud CLI, as well as library updates

**Comment by eddumelendez** [comment]
Hi @ddobrin, you mean switching from `gcr.io/google.com/cloudsdktool/cloud-sdk` to `gcr.io/google.com/cloudsdktool/google-cloud-cli` in our tests, right? `BigtableEmulatorContainer`, `DatastoreEmulatorContainer`, `FirestoreEmulatorContainer` and `PubSubEmulatorContainer` already support both images.

Dependabot will run tomorrow, so, I'll wait for it to update images and dependencies.

**Comment by ddobrin** [comment]
Hi @eddumelendez 
yes, that's the one.

I would suggest also updating the Google client libraries BOM:
testImplementation platform("com.google.cloud:libraries-bom:26.19.0")

and the Guava version
testImplementation 'com.google.guava:guava:32.1.1-jre'
