### ISSUE TITLE
HttpWaitStrategy uses a  random port

### ISSUE THREAD

**Issue by pavolloffay** [testcontainers/testcontainers-java#738]
It seems that `HttpWaitStrategy` uses a random.

* https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/WaitStrategyTarget.java#L13
* https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L381

it would be good to specify the port explicitly.

The docs should be fixed too https://www.testcontainers.org/usage/options.html#startup-timeout

I am on version 1.7.3

**Comment by pavolloffay** [comment]
@bsideup thanks that is a great improvement.

> Also, GenericContainer uses the first exposed port, so it's not really random:

maybe I am missing something but that port is added to a set from which the first port is being used.

**Comment by kiview** [comment]
Fixed in 1d85a3834bd937f80aad3a4cec249c027f31aeb4.
