### ISSUE TITLE
[Enhancement]: Add support for image pull policy configuration in JDBC-TC-URLs

### ISSUE THREAD

**Issue by nils-christian** [testcontainers/testcontainers-java#7404]
### Module

Core

### Proposal

Hi,

Currently the JDBC-TC-URLs do not allow to configure the pull policy. E.g. we can define an URL as following

`spring.datasource.url=jdbc:tc:postgresql:12:///MyDatabase`

This starts a Postgres with the tag 12, but does not make sure that this is actually the latest Postgres with tag 12. In my case the code always used a 12.13 instead of the newer 12.15. It should thus be possible to configure the pull policy via the URL:

`spring.datasource.url=jdbc:tc:postgresql:12:///MyDatabase?TC_PULL_POLICY=ALWAYS`

Thank you and best regards

  Nils

**Comment by eddumelendez** [comment]
Hi, Thanks for raising the PR. However, Testcontainers JDBC URL server basic scenarios and currently there is no plans to support all features that are supported in PostgreSQLContainer. It is recommended in those cases to use PostgreSQLContainer directly.
