### ISSUE TITLE
[Enhancement]: Could TestContainers work with Podman instead of Docker

### ISSUE THREAD

**Issue by jorgegarciarey** [testcontainers/testcontainers-java#7446]
### Module

Core

### Proposal

Related to https://github.com/testcontainers/testcontainers-java/discussions/7419

I had not any responde on that discussion (opened 2 weeks ago)

> I've tried to open a Slack post but my user has not permissions 😢

**Comment by eddumelendez** [comment]
I'll answer in the discussion.
