### ISSUE TITLE
[Feature]: Add Qdrant test container module

### ISSUE THREAD

**Issue by russcam** [testcontainers/testcontainers-java#7503]
### Module

New Module

### Problem

[Qdrant](https://qdrant.tech/) is a vector search engine/database that is becoming popular for search and recommendations use cases. Qdrant provides docker images but there isn't currently an official java test container. This issue proposes adding one.

### Solution

Add a qdrant module with an official java TestContainer

### Benefit

Provides a qdrant test container for folks that need it

### Alternatives

Folks who need a qdrant test container each define it themselves

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @russcam , thanks for the suggestion. Can you share the docker image and github repository, please?

Also, the following information would be useful:
* Does it provides a JDBC driver?
* Does it allow to set username, password, database name via env vars?
* Does it allow scripts execution automatically? See [Initializing a fresh instance](https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance)
* How much takes to start the service inside the container? Can be improved by adding some flags to the initialization?
* How much resources consumes? (E.g memory)

**Comment by russcam** [comment]
Hi @eddumelendez,

- GitHub repository: https://github.com/qdrant/qdrant
- Docker images: https://hub.docker.com/r/qdrant/qdrant

> * Does it provides a JDBC driver?

It supports a HTTP REST API and gRPC API. There's a [community client](https://github.com/metaloom/qdrant-java-client), but for Testcontainer tests, a HTTP client is sufficient.

> * Does it allow to set username, password, database name via env vars?

It allows setting an API key via env vars. API keys are the only current mechanism of auth.

> * Does it allow scripts execution automatically? See [Initializing a fresh instance](https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance)

It doesn't need this. Qdrant has a notion of collections in which it holds vectors and their payloads. No collections need to exist when starting Qdrant.

> * How much takes to start the service inside the container? Can be improved by adding some flags to the initialization?

It's very quick. If there are existing collections bind mounted, then Qdrant can take some time to become ready, loading collections and vectors into RAM. But I would not expect this to be a typical usage for Testcontainers.

> * How much resources consumes? (E.g memory)

Anecdotally, it's lightweight on resources.

I've opened an equivalent PR for Testcontainers for .NET, if it helps: https://github.com/testcontainers/testcontainers-dotnet/pull/994

**Comment by eddumelendez** [comment]
Hi @russcam, thanks for the information provided. I'll discuss this with the team as we are currently reviewing the modules topic.

**Comment by eddumelendez** [comment]
Hi, we have decided to not host the module. However, if you would like to host and release the module on your own you can make it available in our [Module Catalog](https://testcontainers.com/modules/)

**Comment by eddumelendez** [comment]
Hi @russcam, after revisiting this topic again we are interested in having Qdrant as a module. Would you like to contribute?
