### ISSUE TITLE
[Bug]: testcontainers do not work with `crun` 1.9

### ISSUE THREAD

**Issue by snazy** [testcontainers/testcontainers-java#7523]
### Module

Core

### Testcontainers version

(all)

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

amd64

### Docker version

```shell
podman 4.6.2
crun 1.9
```

### What happened?

All container startups fail with `crun: write to /proc/self/oom_score_adj: Permission denied` using crun 1.9.

See [docker-java issue](https://github.com/docker-java/docker-java/issues/2201).
I suspect the issue should be fixed in docker-java, requiring a bump in testcontainers-java as well, as docker-java's shaded in testcontainers-java.

**Comment by snazy** [comment]
Heads-up: docker-java does not need a patch. (Sorry for the noise)

It's an issue with crun==1.9 + podman<=4.6.2. podman>=4.6.3 should work.

**Comment by eddumelendez** [comment]
can we close those issues, then?

**Comment by snazy** [comment]
Sure

**Comment by fnordian** [comment]
Annoyingly enough, Fedora 38 ships podman 4.6.2 and crun 1.9. 

It would be nice if there was a way to modify HostConfig.

**Comment by 0xdeface** [comment]
archlinux podman 4.6.2 and crun 1.9. i also have the same problem

**Comment by fnordian** [comment]
On Fedora 38 it is possible to downgrad to crun 1.8

`sudo dnf install crun-1.8.3-2.fc38.x86_64`
