### ISSUE TITLE
[Bug]: Could not create task spotlessJava when building

### ISSUE THREAD

**Issue by BewareMyPower** [testcontainers/testcontainers-java#7526]
### Module

Core

### Testcontainers version

00cc0ea84b73642e3494e6b7a0384a5e3fa201bd

### Using the latest Testcontainers version?

Yes

### Host OS

macOS

### Host Arch

ARM64

### Docker version

```shell
No docker is used.
```

### What happened?

I tried to build the project.

```bash
$ ./gradlew build                                              
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':azure:spotlessCheck'.
> Could not create task ':azure:spotlessJavaCheck'.
   > Could not create task ':azure:spotlessJava'.
      > Running npm command 'npm install --no-audit --no-package-lock --no-fund --prefer-offline' failed with exit code: 1
```

Then I tried the way in the CI.

```bash
$ ./gradlew :testcontainers:check --no-daemon --continue --scan
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':testcontainers:spotlessCheck'.
> Could not create task ':testcontainers:spotlessJavaCheck'.
   > Could not create task ':testcontainers:spotlessJava'.
      > Running npm command 'npm install --no-audit --no-package-lock --no-fund --prefer-offline' failed with exit code: 1
```

**Comment by eddumelendez** [comment]
Hi, this is an environment issue related to your npm installation as described in the logs.

**Comment by BewareMyPower** [comment]
@eddumelendez I see no document about the `npm` version requirement in https://github.com/testcontainers/testcontainers-java/blob/main/docs/contributing.md

I tried `./gradlew spotlessApply` and met the same error. Here are my `node` and `npm` versions:

```bash
$ node --version                                             
v20.4.0
$ npm --version                                              
9.7.2
```

The document does not mention the required version for `npm`, which is not friendly to developers.

Since this issue is closed, should I open a discussion [here](https://github.com/testcontainers/testcontainers-java/discussions) for answer?

**Comment by eddumelendez** [comment]
I've been looking into spotless docs as that's the plugin using npm but can not fin more information about it, just [this](https://github.com/diffplug/spotless/tree/main/plugin-gradle#npm-detection)

When I setup my environment with brew I didn't do anything special. Also, the [codespaces setup](https://github.com/testcontainers/testcontainers-java/blob/main/.devcontainer/devcontainer.json) should work as well.

**Comment by peterhalicky** [comment]
If anyone finds this issue here like I did, the most likely cause is this: https://github.com/npm/cli/issues/6367

npm seems to not even try to download locally missing packages when it has --prefer-offline parameter on the commandline
