### ISSUE TITLE
[Bug]: Broken pipe when creating container with podman

### ISSUE THREAD

**Issue by Sgitario** [testcontainers/testcontainers-java#7539]
### Module

Core

### Testcontainers version

1.18.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
podman version is 4.6.2
```

### What happened?

This is a duplicate of https://github.com/testcontainers/testcontainers-java/issues/6640 that was closed but not fixed (I can't reopen it). 
For example, using the PostgreSQL container like:

```java
@Testcontainers
class MyTest {
  @Container
  static PostgreSQLContainer db = new PostgreSQLContainer();
  @Test
  void test() {
     // ....
  }
}
```

Will randomly fail with `Broken pipe when creating container`. 

I configured podman-docker and socket using:

```
sudo dnf install podman podman-docker
systemctl --user enable podman.socket --now
podman system service --time=0
```

Check podman socket is listening:
```
podman info | grep -A2 'remoteSocket' 
```
This command should print:
```
remoteSocket:
  exists: true
  path: /path/to/podman.sock
```

And configure testcontainers to connect to the podman socket:
``` 
export DOCKER_HOST=unix:///run/user/${UID}/podman/podman.sock
export TESTCONTAINERS_RYUK_DISABLED=true
```

**Comment by jvissers** [comment]
We are experiencing the same behavior on:

- podman version 4.6.1
- testcontainers 1.19.2

Using GenericContainer construct.

**Comment by nickbreen** [comment]
Experiencing this with:

* TestContainers java 1.20.0 
* Podman 4.9.4-rhel
* RockyLinux 8.8

**Comment by kiview** [comment]
Please open an issue with Podman about this, I will close this issue, since we are only supporting Docker runtimes officially and expect other runtimes to behave in a similar way.

**Comment by igieon** [comment]
Hi all the bug is not problem of testcontainers but your configuration of podman is because testcontaeiner cache http conection to API server if you start via podman.socket via systemd you need change:
/etc/containers/containers.conf:
```
[engine]         
service_timeout=0
```
Default timeout is 5s which you can hit

**Comment by michalvavrik** [comment]
@igieon I tried your suggestion and so far it seems that it helped. Thank you
