### ISSUE TITLE
[Bug]: Can not connect to LocalStack

### ISSUE THREAD

**Issue by zelenkooo** [testcontainers/testcontainers-java#7543]
### Module

LocalStack

### Testcontainers version

1.18.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

linux/amd64

### Docker version

```shell
#16 0.496 Docker version is: Client: Docker Engine - Community
#16 0.496  Version:           24.0.6
#16 0.496  API version:       1.43
#16 0.496  Go version:        go1.20.7
#16 0.496  Git commit:        ed223bc
#16 0.496  Built:             Mon Sep  4 12:31:44 2023
#16 0.496  OS/Arch:           linux/amd64
#16 0.496  Context:           default
```

### What happened?

Application is using testcontainers and Localstack to for AWS tests.
All was working on version 1.17.6 after upgrade to the version 1.18.0 ( or later 1.19.0 ) connection to the Localstack could not be established ( same port and endpoint as before ). With the error  : Could not connect to the endpoint URL http://docker:4566/ 

Using localstack:2.2.0 image, container has started without problems ( see logs )

and env variables :

        withEnv("SKIP_SSL_CERT_DOWNLOAD", "1")
        withEnv("SKIP_INFRA_DOWNLOADS", "1")
        withEnv("DISABLE_EVENTS", "1")

### Relevant log output

```shell
2023-09-21T19:44:05.894Z  INFO 506 --- [    Test worker] tc.localstack/localstack:2.2.0           : Container localstack/localstack:2.2.0 is starting: 2d996755a7955a87a07ecaa3208dccd62968cd228cbb2d0a111f08074090be5b
    2023-09-21T19:44:07.434Z  INFO 506 --- [    Test worker] tc.localstack/localstack:2.2.0           : Container localstack/localstack:2.2.0 started in PT2.54495621S


    java.lang.IllegalStateException: Aws sqs command create-queue failed with 
    Could not connect to the endpoint URL: "http://docker:4566/"
    .
```

**Comment by eddumelendez** [comment]
Can you share the container definition, please? So far, just env vars were shared. Also, did you update the image version when upgrading testcontainers as well?

**Comment by eddumelendez** [comment]
Closing due to lack of information.
