### ISSUE TITLE
[Bug]: Unable to build locally due to ':jdbc-test:shadowJar' dependency

### ISSUE THREAD

**Issue by beargiles** [testcontainers/testcontainers-java#7590]
### Module

MariaDB

### Testcontainers version

1.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 22.04 LTS

### Host Arch

i386

### Docker version

```shell
Docker version 24.0.5, build 24.0.5-0ubuntu1~23.04.1
```

## Summary

A local build (in docker container) produces this error on all database modules.

Source code that demonstrates this problem is attached.

```
> Task :mariadb:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':mariadb:test' (type 'Test').
  - Gradle detected a problem with the following location: '/usr/local/src/testcontainers-java/modules/jdbc-test/build/libs/jdbc-test.jar'.
    
    Reason: Task ':mariadb:test' uses this output of task ':jdbc-test:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':jdbc-test:shadowJar' as an input of ':mariadb:test'.
      2. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#dependsOn.
      3. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```

## Attempted remedies

I'm not familiar with gradle so I was a blind bull in a china shop with access to Google and tried a ton of different ideas. Most resulted in format errors, I learned a lot, but none of the ones that ran fixed the problem.

## Background

I am attempting to build 'testcontainers-java' locally. For isolation and reproducability I'm building it in a docker container - in fact I'm hoping to submit it as a potential module later.

Due to familiarity, I'm using Ubuntu 23.04. (Not Ubuntu 22.04 LTS) - but still have to explicitly download and install gradle 8..x,

I can execute 'gradle' without any problems.

I must explicitly exclude the following modules (so far) due to unmet requirements. E.g., authentication tokens for Azure, or a specific IP address for elastic search:

- azure (missing resource?)
- db2 (still attempting to start at 20+ minutes)
- elasticsearch (ip address?)
- gcloud (no notes...)

## New TestContainer containers in development

I have several new Containers at https://github.com/coyotesong/testcontainers-java-extras. At the moment it's two "cloud" databases/data lakes/whatever that provide docker images for development and testing.

- SAP HANA
- Vertica

It also includes a Container for `sqlite` even though it's a host-only database. That database is extremely popular in webapps (since it's self-contained) and using a pseudo-Container allows developers to use any resources in the TestContainer ecosystem as long as it doesn't require advanced configuration that's only available to docker images.

The modules are incomplete since there are no tests. I'm attempting to emulate the other databases but they depend on a maven module that does not appear to be published.

No problem - I can build the docker image from scratch. Hmm... I could even treat this as a new TC module!

The resulting source code is available at https://github.com/coyotesong/testcontainers-java-extras/, 'junit-test' branch. (oops - that should have been 'jdbc-test'.)

### Relevant log output

```shell
> Task :mariadb:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':mariadb:test' (type 'Test').
  - Gradle detected a problem with the following location: '/usr/local/src/testcontainers-java/modules/jdbc-test/build/libs/jdbc-test.jar'.
    
    Reason: Task ':mariadb:test' uses this output of task ':jdbc-test:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':jdbc-test:shadowJar' as an input of ':mariadb:test'.
      2. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#dependsOn.
      3. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```

**Comment by beargiles** [comment]
#
# Create docker container that can build and test the TestContainer source code.
#

# Usage notes: you must make the host's docker socket available to this image:
#
#    docker .... -v /var/run/docker.sock:/var/run/docker.sock
#
FROM ubuntu:23.04

ARG JAVA_VERSION=17
ARG GRADLE_VERSION=8.3

#
# Set standard environment variables. We do not need to
# update PATH since we use 'update-alternatives' to handle
# gradle. This allows us to co-exist with the standard
# gradle package, if necessary, since we would only need
# to change GRADLE_HOME and select a different alternative.
#
ENV GRADLE_HOME=/opt/gradle-${GRADLE_VERSION}
ENV JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-openjdk-amd64

#
# Update /etc/apt information to include the most recent docker release
#
COPY docker.list /etc/apt/source.list.d/docker.list
COPY docker-keyring.gpg /usr/share/keyrings/docker-keyring.gpg

#
# Update pages, install git, java, maven, more
#
RUN /usr/bin/apt-get update -y && /usr/bin/apt-get upgrade -y
RUN /usr/bin/apt-get install -y git npm maven \
     openjdk-${JAVA_VERSION}-jdk openjdk-${JAVA_VERSION}-jdk-headless \
     zip unzip curl wget vim

#
# Download and install recent gradle
#
WORKDIR /tmp
RUN /usr/bin/wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
RUN /usr/bin/wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip.sha256

# need to run 'unminimize' to run sha256sum

WORKDIR /opt
RUN /usr/bin/unzip /tmp/gradle-${GRADLE_VERSION}-bin.zip
RUN /usr/bin/ln -s gradle-${GRADLE_VERSION} gradle
RUN /usr/bin/update-alternatives --install /usr/bin/gradle gradle /opt/gradle-${GRADLE_VERSION}/bin/gradle 1000

#
# Download testcontainers-java source code
#
WORKDIR /usr/local/src
RUN /usr/bin/git clone https://github.com/testcontainers/testcontainers-java.git
WORKDIR /usr/local/src/testcontainers-java

#
# Build software
#
RUN gradle

#
# This must be add to settings.gradle - the tests require something
# not available in the docker image.
#
#
# file('modules').eachDir { dir ->
#   // modules where docker image fails to properly load
#   // azure: resource?
#   // db2: loooong wait
#   // elasticsearch : ip address 10.10....
#   if ( ! [ "azure", "db2", "elasticsearch", "gcloud" ].contains(dir.name) ) {
#       include dir.name
#       project(":${dir.name}").projectDir = dir
# }
#
# In addition the database modules fail with
#
#>   * What went wrong:
#>   A problem was found with the configuration of task ':mariadb:test' (type 'Test').
#>     - Gradle detected a problem with the following location: '/usr/local/src/testcontainers-java/modules/jdbc-test/build/libs/jdbc-test.jar'.
#>
#>       Reason: Task ':mariadb:test' uses this output of task ':jdbc-test:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
#>
#>       Possible solutions:
#>         1. Declare task ':jdbc-test:shadowJar' as an input of ':mariadb:test'.
#>         2. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#dependsOn.
#>         3. Declare an explicit dependency on ':jdbc-test:shadowJar' from ':mariadb:test' using Task#mustRunAfter.
#>
#>       For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
#
# But I've been unable to find the fix for this despite trying many different ideas.
#

# RUN gradle build

**Comment by beargiles** [comment]
```
deb [arch=amd64 signed-by=/usr/share/keyrings/docker-keyring.gpg] http://download.docker.com/linux/ubuntu  lunar stable
```

**Comment by beargiles** [comment]
BASE-64 encoded docker-keyring.gpg

```
AAAAIAEBAAJLQlhmAAAAAGLmvwxi5r8MAAAAAAAAAAAAAAuGAgEAAAAAAH4AAAr0AAIAHJ3IWCKf
x904hUri2I2BgDwOv82IAAAAIAAAAADTMGoBg3AZnlJ655l+oKnD8nP82AAAADwAAAAAAAAAAQAM
AAACngAAACsAAAAAAAIABAAAAAAAAAAAAAAAAAAAAAAAAAAAYua/DAAAAACZAg0EWK3aKgEQAOFa
lnz/C9nqFROJc7BAdcwCVoUdw8f2EC2vgXXLb45h1u0y62GWqrCnTbwCrJj49F9Uy1JgxuO5C67l
vLIpHTUFupiG5LeO2pCaWNn9sm9eqeaJVeHfxS4tr7PTvs/HLFCG7kFuqe1M9Ax+LKoSJT4EpurZ
aYA1QpB/7UCZlj8iu45dueovgLX6Any9+ZdC332ekJrESNo1FVh85LxByLE3MdRidvp6aOUA3IRW
VnN6qjtcqXtSvBXmKdrBNLNY2+2MSOPickvw2wvCxyks9BSFND7sFtBcDACZ4cJRNAi+9ZerDQ1y
aGHgeB5CxxAdiA4mOMNV+hjky5y+CVsiAKp/MAdb2PGZEvipsxmP5vVeh48S2G2S7hshA3Vfk/Tt
81bOWBpEvlng85cMNlOUhD8SXnyP2SnhudZEIlbSXJr5/yhyh2i9ln4OiL5/LgPlkasvhcRwhA/8
u/m4XJ/6RC2X/3hUVhUk6V4C/xb3Yp2AOSFNxMMbtzS0iRUQo1SrjxvdpDrg05lBbt9WN+grARl0
6o8TvY9rjmOtnO9QXFKl2I2Ta1ldi6QeOXHESAF0L8ndwww1ETUXg0IDcCl9XVjv+FN46eYO4NjC
v3+hsDy3TXpiWOOrmt2TLA9/gkXyZdRbl4I3W8AUfF6D1lZ6aEG1CYbFefD0z7PqFbBzpqGbABEB
AAGwDAAAZ3BnAQAAAAAAALQrRG9ja2VyIFJlbGVhc2UgKENFIGRlYikgPGRvY2tlckBkb2NrZXIu
Y29tPrAMAABncGcCAAAAAAAAiQI3BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4B
AheAAAoJEI2BgDwOv82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmq
vMqdtI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3LgkjonyUf9b
wtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m6fqcd5Fu7pxsqm0EUDK5
NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9PXRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8O
YBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMcFYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4D
QJjbxeMZbiNMG5kGECA8g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSF
bzwKB0JmebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh9svI
GfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5G34Ct5RS7Jt6LIfF
dtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoWFPIZ7d6vH+Vro6xuWEGiuMaiznap
2KhZmpkgfupyFmplh0s6knymsAYAA2dwZwC5Ag0EWK3aKgEQAOd4v1L2bi+FTduVpGNVRTIntv+p
ONxLKW8IfldQTpHaT5yQRmN8Axk8uk77+0UzYkgkwPhKJ8q5LfFyT0q1kYK58aZzCItBHN4cXu8l
QqssPlFOQ2LbfJ29ZmA+O3FD4NNPVlyfsGtAVjoWCdGhRUjHC13DVsxj/z2uwWBLnDC4wRJ3dDZF
iBvsQ4U6me7Dp1rtZqRZ/giGcXmew1gYNVogfOmKoKX65Nt/V6kKOs6UjORndndiTkIz9OIXM+TP
aUvPz1ykPxT420Kx9qBZZ+N3ZTeMNqmAf7udCcIRalE63NoocbqUDeld2LHnMbx5Fzr/QhtRJa9+
MrEss9814JLakIvch4Qjmei2EQRh1AfqzOkuiDv3EH11WcnIoltV/Feex6hipWtHPZVVtQjkGXCb
oHjQTd4ZV9RBaK7HngOynJUwyTjUzHtAneLKchrU3hkCpUwASu7JdNFPFz1dbS1iEMwD/UZi/PQS
YWmbwvNMcDqwVW0+b9mU0Jfo/VfMnCu/sNJAoPoYaUFBRf454Qny1OSR/xBMlI9R2Hw/xjEMVLkQ
4YC+GGkwFgPjaRCmpeMQL5dzJxO8YjuKamC/08NjVEILXOQGMo9rXbSs2G/+GRWT9iG4ahqOgfLL
iHtlCil1wy2k3Z2CaER6CfL0kJLDF9CZDTMrSDubpIeIozCPABEBAAGJBD4EGAEIAAkFAlit2ioC
GwICKQkQjYGAPA6/zYjBXSAEGQEIAAYFAlit2ioACgkQfqCpw/Jz/NjVYA//bAn5HSATqqxx7euN
ojPnw8mZzyCgquKvmGcSVaE+BurtxgixbmqIXIuGR2lhwyaEP2ZGI+lCfphrbDd7cHzN8hUqKlsw
GeR7/K1n0zuoeYMJyOiJKbARc3fApgiYP1Uc42yX8IbWtT0izDWO0HmDVjG4EDsz+bfpc3rHa742
00wMH0/nrJziB+xlURIoD2/7Jjb+Xjkvx39ZSRSLRheiafqHIEYjsmsEurQJffsYRg/o72usqKl/
Pvdd87skgbM4pmWWNv8P1Ff+DudFsKf7cS0fvGeT5Mr/nR64QrDxIxSDXjuwlNylCa/pTNlwzgmA
vQdsdUKiNXgL+mUQvAx10As4V5hDNOJ/qwxE9/7cNKPx+tsieMKELfI4vLTpuv3YoWibXsQiPYIB
yh6rtQ+GLaii5gHA/GHnK116EmSij6w3tEha5ro/ZZKaiflTzzxxLKVcLT4AMV2Atf0rbOsNVhQb
W+jwJfS/PEUFofA3o/Hbp+EhPX+FhQdBHXNV80NzJCZeqQ6dm++gx/P9DSz0GEUn/NToCBBshkT+
GbWymx+C+2wPV+tl/KBcn1+Ks/4xIAjzTEdJ/3WpJFk6Pg+Xdkk1urjJjG/RvWmQyp4Z2N0JiEtT
4tnjBtCakKRJV7amuUu6t6KBe2Zl+Sp69HPsWshmK72TLzCcIA/ALv/OZLXyuA//Xts60vj+IjNC
HEACgAxZWsbImK9KSOFIbHW4KiOxZ+xMCbXU/uOyu4gvrVnMxRUTZozc+aPkb5b0BxnnwSb7VaxW
cBd1RH/9syaHKvzAv8bVg7VXckQlNF3GxLF1hrh14YEFj8B2mzDbiPGE4lH6WwmmohR5v3335Hx6
4OFEcb14U7sNG7rB5q1Qnqy66mgNNFa2v/jIap50rFXepCE0tKdoDOpb/WcDeJQHiTuQJopnGF2E
NsKV/0/fuppFbjrsEsJU79ygvfJWbnR3B2s20qkwGHdmlsHW4m+CL2Ze3IE4wne/xFl4PMWIbwd0
K2D1G8i38AgWgdEfdL5Tv01PqLQo/MsiYN+zxPtGWnK4xzhR+zyCDKD2/cB7pw3d5DLFwrfDRxsH
CyH+dA1+wDq6770fs2Ft6EEyFiek1nKsfMKbPJeRq7BECqgJsYI3KRNHCy6v2BLjVNAzyywPWMWF
44l/eE4OeQpT4cqO8xE6XUMrvN2Yt03MDVy+1kf+cIL0o+PXPxALjtLHH51NlLHg40CHBtL8s3c+
gq2fws+Nj00/24NYj5NZiq5LZT4ocOsEOWyCjMNuz86MLFykPM2ZelZAcS0dTvrj05cc/tR41JPW
YJQIfmp1qeTRXWJ6MXr8J9MVTgx9ysZhP3SoUX3cze/TUFvE/4Qhjb/22Ig9ut2wBgADZ3BnAODm
qFyVHhHB3FqXEQPmt98UnWRq
```

**Comment by beargiles** [comment]
The modification to 'settings.gradle' in the docker container, before running `gradle build`.

```
file('modules').eachDir { dir ->
    // modules where docker image fails to properly load
    // azure: resource?
    // db2: loooong wait
    // elasticsearch : ip address 10.10....
    if ( ! [ "azure", "db2", "elasticsearch", "gcloud" ].contains(dir.name) ) {
        include dir.name
        project(":${dir.name}").projectDir = dir
    }
}
```

**Comment by eddumelendez** [comment]
Hi, Testcontainers uses Java 8 for development. The project provides GitHub Codespaces configuration already with everything is needed. Please, before raising an issue read the form, it clearly mentions to open a discussion first instead. About the modules, I don't think we currently have the capacity to maintain those. Please feel free to open a discussion about those modules and why would you not be able to host them, take into account there is a [Testcontainers Modules](https://testcontainers.com/modules/) where we can point to your implementations.

**Comment by beargiles** [comment]
Thanks for the gentle reminder. I've **used** TestContainers for some time, **created** some local ones, but this is the first time I've tried to develop some with actual tests instead of relying on them working well enough for my own tests. That definitely skews your perspective since you're at that point in the learning curve where you've learned just enough that it doesn't occur to you to check the introductory material again.
