### ISSUE TITLE
Unix socket access to docker should not need any configuration

### ISSUE THREAD

**Issue by mbaechler** [testcontainers/testcontainers-java#76]
Currently, when one use testcontainers on linux, he needs to configure some env variables.
There are already two strategies to handle configuration diversity : env and docker-machine.
I suggest to add a UnixSocketConfigurationStrategy that try to access docker socket if no other strategy works.

**Comment by rnorth** [comment]
Another good idea :)

Thank you!

**Comment by rnorth** [comment]
Thanks, this and #78 are merged now!
