### ISSUE TITLE
[Enhancement]: MariaDB configuration volume to be read-only for Windows compatibility

### ISSUE THREAD

**Issue by grooverdan** [testcontainers/testcontainers-java#7620]
### Module

MariaDB

### Proposal

By default, MariaDB ignores globally RW files. Per the MDEV below this can on Windows users be the defaults as unix permissions don't map to Windows permissions well.

https://jira.mariadb.org/browse/MDEV-27038

In the MariaDB I fixed (possibly only worked around) the implementation by making read-only filesystems an acceptable criteria by the server.

So as the enhancement can the volume mount in the `configure` method (`MariaDBContainer.java`) apply the mount as read-only?

**Comment by eddumelendez** [comment]
Hi @grooverdan, we encourage to use [copy files API](https://java.testcontainers.org/features/files/#copying-files) instead on mounting and the API allows to set the permission as well. What do you think about adding this note in DockerHub description, so, everyone using the image can be aware of that?

**Comment by grooverdan** [comment]
Good examples. Thanks.

Quite right about docs - its in the review queue - https://github.com/docker-library/docs/pull/2371

**Comment by eddumelendez** [comment]
Great! Should we close this issue, then?

**Comment by grooverdan** [comment]
sure. Thanks
