### ISSUE TITLE
[Bug]: Hard coded AccessKey / SecretKey in LocalStackContainer doesn't match LocalStack

### ISSUE THREAD

**Issue by internetstaff** [testcontainers/testcontainers-java#7623]
### Module

LocalStack

### Testcontainers version

1.19.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86_64

### Docker version

```shell
24.0.5
```

### What happened?

We've been configuring credentials per the examples (calling `LocalStackContainer.getAccessKey()` and `LocalStackContainer.getSecretKey()`, and everything generally works fine because LocalStack doesn't care.

Where it fails is when we set `S3_SKIP_SIGNATURE_VALIDATION` to `0` and try to test passing / failing S3 signatures.

LocalStack defaults to `test` for both access and secret key, and if the S3Client isn't set to the same, the signatures are invalid.

If `LocalStackContainer` used these same values, it seems like everything would "just work" and spare someone else debugging this. 

I may be missing a bigger picture here as to why these values don't match LocalStack. :)

**Comment by eddumelendez** [comment]
Thanks for the report, @internetstaff ! Would you like to contribute?

**Comment by fokion** [comment]
I can have a look if you want @eddumelendez

**Comment by eddumelendez** [comment]
@fokion the issue is yours. Please, consider adding tests.

**Comment by fokion** [comment]
Working towards this draft PR https://github.com/testcontainers/testcontainers-java/pull/7718
