### ISSUE TITLE
Browser started by BrowserWebDriverContainer can't connect to localhost

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#764]
Hi,

In my test I start Tomcat (on localhost) and then use a BrowserWebDriverContainer and do a `webDriver.get("http://localhost:8080/...')`. 

In the VNC recording, I can see that the issue is that the docker container running the browser can't connect to localhost.

Is there a network setup I can use to allow that?

Thanks

**Comment by vmassol** [comment]
FTR I start BrowserWebDriverContainer as follows:

```
        BrowserWebDriverContainer webDriverContainer = new BrowserWebDriverContainer<>()
            .withDesiredCapabilities(DesiredCapabilities.chrome())
            .withNetwork(Network.SHARED)
            .withNetworkAliases("vnchost")
            .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.SKIP, null)
            .withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger(this.getClass())));
```

**Comment by vmassol** [comment]
I understand why this is happening: the browser is running inside the container and thus localhost points to itself and not the host. So basically I need to find the host IP.

**Comment by vmassol** [comment]
Closing since this is not related to TestContainers.

**Comment by kiview** [comment]
I don't know if you find the solution yet, but the easiest and most stable way is IMO putting the browser container and the SUT (system under test) container into the same network and using the container name and Docker auto DNS.

**Comment by vmassol** [comment]
Thanks @kiview but for the moment the SUT is running on the host and not inside a container. That's my next step. Right now I have done like this but it's not working for everyone apparently since I have a user saying that his browser cannot connect to his host:

```
    private String getIP() throws Exception
    {
        InetAddress inet = InetAddress.getLocalHost();
        InetAddress[] ips = InetAddress.getAllByName(inet.getCanonicalHostName());
        if (ips  != null ) {
            for (int i = 0; i < ips.length; i++) {
                if (!ips[i].getHostAddress().equals("127.0.0.1")) {
                    return ips[i].getHostAddress();
                }
            }
        }

        throw new RuntimeException(String.format("Failed to find IP address of host. Found [%s]",
            StringUtils.join(ips, ',')));
    }
```

**Comment by kiview** [comment]
You can normally interact with the host if you are using the gateway IP address of the Docker bridge network. On Linux this is normally `172.17.0.1` and can also be obtained by inspecting the container.

I have no idea how this works in case of Windows or Mac though.

**Comment by vmassol** [comment]
I didn't know there was a reserved and fixed IP in Docker to represent the gateway bridge network so that's cool. I've tried it though (on Mac) and it exists but it doesn't point to the XWiki webapp apparently.

**Comment by vmassol** [comment]
hmm forget that I think I'm making a mistake. I'm using the URL in 2 places: 
* in the test to verify if XWiki is started, here I should use localhost since it's not running in the container
* in the test through WebDriver to navigate the page, and here I should use `172.17.0.1`.

I'll try this.

**Comment by vmassol** [comment]
FTR I've now tested and `172.17.0.1` doesn't work but `docker.for.mac.localhost` works. However it'll work only on Mac.

**Comment by bsideup** [comment]
@vmassol there is `host.docker.internal` for Mac & Windows, but no such for Linux :(

**Comment by vmassol** [comment]
I'm going to use the following for now:

```
    private String getHost()
    {
        return SystemUtils.IS_OS_LINUX ? "172.17.0.1" : "host.docker.internal";
    }
```

Thanks!

PS: I'll validate with a coworker later on that it does work on Linux ;)

**Comment by kiview** [comment]
Sounds like it is worth a try. We also have sometimes similar constructs,
since CI and local might behave a bit different in our case.

Vincent Massol <notifications@github.com> schrieb am Di., 3. Juli 2018,
18:07:

**Comment by vmassol** [comment]
> since CI and local might behave a bit different in our case.

About that, we're hitting a snag. I'm working so that we can have XWiki functional UI tests execute locally on developer machines and in various environments (various DBs, various Servlet Containers and various Browsers). However those tests also execute on our CI (http://ci.xwiki.org)... and we've realized that our Jenkins agents are actually running in containers themselves (vsphere to be precise)... So this means being able to install Docker inside vsphere which doesn't seem easy to do (we're still researching that). Worse come worse we could move our agents to use Docker but that would still mean running Docker inside Docker which is not ideal either (although I've found this blog post which seems to say it's possible https://getintodevops.com/blog/the-simple-way-to-run-docker-in-docker-for-ci).

So I was wondering what users of TestContainers are doing. Does it mean your CI agents run directly on physical machines and not in containers?

Thanks

**Comment by kiview** [comment]
It's very much possible and there are different good solutions how to do it
with Testcontainers.

We are ourselves running Gitlab Ci with docker build containers, using
docker socket mounting.

I will try to give you a more detailed explanation tomorrow, since I'm
currently in the cinema ;)
Also feel free to join our slack channel for getting you a kickstart how to
best use Testcontainers for your use case, we have a very helpful community
there.

Vincent Massol <notifications@github.com> schrieb am Di., 3. Juli 2018,
18:50:

**Comment by kiview** [comment]
Hey @vmassol,

so the problem is, I don't know how VSphere containers work. Since it's docker based, it should be possible to use an approach similar to Docker socket mounting into the container.

Regarding Docker in Docker, there are normally two approaches:
You can either run Docker with socket mounting (as specified in your linked article), which will make every spawned container a sibling container (not a child!). This works very well, but you have certain limitations when you want to mount files from within your build container (the spawned container will mount from the host in this case).

The alternative is running a complete Docker daemon inside a container. Although not recommended by Docker themselves, Gitlab even advocates this approach. You have quite nice isolation here, but you are losing your Docker layer cache, which might make build to slow.

So in the end, when you are running normal Docker containers, there are some standard patterns on how to solve this and they both work quite well with Testcontainers (and are used by the community).

**Comment by vmassol** [comment]
One detail: I mixed up between vsphere and vserver.... We're actually using vserver and not vsphere: https://en.wikipedia.org/wiki/Linux-VServer

**Comment by kiview** [comment]
I see. I have no experience with VServer, but it sounds like this is the underlying technology of the kernel that Docker uses? Or kind of a predecessor alternative? 

Might be possible if you are using a recent kernel with VServer:
https://serverfault.com/questions/845902/running-lxc-or-docker-containers-with-a-vserver-container

**Comment by vmassol** [comment]
> Might be possible if you are using a recent kernel with VServer:

Yes we've found this SO thread too (there aren't that many when you google) and we're going yo try this first and if it doesn't work we might move to docker instead of vserver. Thanks for the help, much appreciated!

**Comment by kiview** [comment]
No problem, I'd be happy if we'd be able to figure out a working solution for you :slightly_smiling_face: 
So the reason for you using VServer are more or less historic ones?

**Comment by vmassol** [comment]
> So the reason for you using VServer are more or less historic ones?

Exactly. I wasn't the one who set that up and the infra guy who did has left the company a long time ago ;) So we could move to another solution. However it's work so we'll try to make docker in vserver work first before switching.
