### ISSUE TITLE
Issue using DockerComposeContainer + Spring

### ISSUE THREAD

**Issue by adrienzieba** [testcontainers/testcontainers-java#765]
I try to use `DockerComposeContainer` with spring and I cannot make it work correctly. 
When I run only one test class using IDE everything is fine but when I try to run all tests, I have the following error (IDE and using mvn command)

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: java.lang.NullPointerException: containerId was not specified
```

It works correctly if I use `GenericContainer` instead.

I created a repo to reproduce the problem : https://github.com/adrienzieba/testcontainers-test
Abstract class : https://github.com/adrienzieba/testcontainers-test/blob/master/src/test/java/com/example/AbstractIntegrationTest.java

Do I need to do something different with `DockerComposeContainer`?

**Comment by bsideup** [comment]
Hi! Is you put it to "AbstractTest" class, you should remove ClassRule and
just call ".start()" in "static {}" block. Otherwise, you start an
environment per test class.

Also, it is wrong to use "localhost" there because it's not always true :)

**Comment by adrienzieba** [comment]
@bsideup Thanks for the quick answer. i'll change to have use `dockerComposeContainer.getServiceHost(MONGO_CONTAINER_NAME, MONGO_PORT)` instead f localhost :)

Actually, my goal was to start an environment per test class. I don't have real use case yet but I thought that sometimes it is easier to start a new container instead cleaning existing one. With `GenericContainer`, I am able to use the ClassRule but not with `DockerComposeContainer`.

Finally I modified the code to start the container inside initialize method :
```
public void initialize(ConfigurableApplicationContext configurableApplicationContext) {
            DockerComposeContainer dockerComposeContainer = new DockerComposeContainer(new File("src/test/resources/docker-compose-mongo.yml"))
                        .withExposedService(MONGO_CONTAINER_NAME, MONGO_PORT);
                dockerComposeContainer.start();
            final ConfigurableEnvironment environment = configurableApplicationContext.getEnvironment();
            String mongoHost = String.format("mongodb.host=%s", dockerComposeContainer.getServiceHost(MONGO_CONTAINER_NAME, MONGO_PORT));
            String mongoPort = String.format("mongodb.port=%s", dockerComposeContainer.getServicePort(MONGO_CONTAINER_NAME, MONGO_PORT));
            TestPropertySourceUtils.addInlinedPropertiesToEnvironment(environment, mongoHost, mongoPort);
        }
```

**Comment by adrienzieba** [comment]
Another question
When we use the `@ClassRule`, Junit knows when it has to stop the container.
Here we just do a `start()`. So, how is manages the container when the tests end?

**Comment by kiview** [comment]
@adrienzieba You can call the corresponding `stop()` method e.g. in a method annotated with `@AfterClass`. Also keep in mind, that Testcontainers is starting an additional helper container (`ryuk`) which will also stop and clean all Testcontainers containers if the JVM exits.
