### ISSUE TITLE
Prefix Maven artifact names with 'testcontainers-'

### ISSUE THREAD

**Issue by unguiculus** [testcontainers/testcontainers-java#770]
I'd suggest to follow best practices and change Maven artifact names to have a `testcontainers-` prefix. By looking at their names, artifacts like `mysql-1.8.0` or `kafka-1.8.0` cannot be identified as testcontainers artifacts. Also, there's a risk of name clashes, since the groupId is not part of the file name.

Here's an example for good artifact names:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.sonatype.nexus%22

Since this could be considered a breaking change, it would probably have to wait till the next major release.

**Comment by bsideup** [comment]
Hi @unguiculus,

The problem was already reported in #737, I suggest moving the conversation there if you don't mind :)

But thanks for your points about the implications of not having it 👍 That's something we definitely would like to solve
