### ISSUE TITLE
[Bug]: Kafka container fails to start after upgrade to 1.19.1

### ISSUE THREAD

**Issue by melix** [testcontainers/testcontainers-java#7789]
### Module

Kafka

### Testcontainers version

1.19.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Cloud integration: v1.0.23
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I'm trying to upgrade [Micronaut Test Resources](https://github.com/micronaut-projects/micronaut-test-resources) to test containers 1.19.2.

After this upgrade, one test is failing with:

`Unexpected handshake request with client mechanism PLAIN, enabled mechanisms are []` (see https://github.com/micronaut-projects/micronaut-test-resources/actions/runs/6842478040)

This happens whenever on a test which requires to set an environment variable on the container:

https://github.com/micronaut-projects/micronaut-test-resources/blob/e527b06ac452e5c63348418386b5f24b899c377d/test-resources-kafka/src/test/resources/application-custom.yml#L6

So this all behaves as if the environment variable was ignored in 1.19.1. It also happens with 1.19.0, but the test passes with 1.18.3.

**Comment by eddumelendez** [comment]
Thanks for the report, @melix. It was fixed in https://github.com/testcontainers/testcontainers-java/pull/7748 and I have also added some tests related to sasl https://github.com/testcontainers/testcontainers-java/pull/7763. This is not released yet, but it will be soon.
