### ISSUE TITLE
Add some DEBUG loggers for connection strategies

### ISSUE THREAD

**Issue by mbaechler** [testcontainers/testcontainers-java#78]
I spent some time figuring out why I got an SSLException when trying to make my test container to work.
It appears to be a simple library version conflict on bouncycaste, but the exception cause is not logger at all.
It should be possible to log the exception causes when log level is debug.

**Comment by rnorth** [comment]
Good idea - this would be useful. As we're suggesting in the docs that people set root log level to INFO, this shouldn't have an effect on log noise for normal usage.

Thanks for this!
