### ISSUE TITLE
[Feature]: k3s container - configurable port

### ISSUE THREAD

**Issue by Obirah** [testcontainers/testcontainers-java#7814]
### Module

K3S

### Problem

I want to start k3s containers in parallel so that I can run integration tests for my Quarkus-based Kubernetes operator with one k3s for each test suite.

### Solution

Make the kube port configurable in the constructor of `K3sContainer` (with 6443 being the default of course) and set the `--https-listen-port` in the k3s command. Adapt all other portions of `K3sContainer` that use the static port number so that they use the configured one.

### Benefit

Being able to run parallel k3s containers:
* The k8s resources of different test suites do not interfere with each other if there is one k3s container per suite.
* The test setup is horizontally scalable.

### Alternatives

Keep on running sequential tests or run all tests against one k3s container in parallel and write more boilerplate code in order to keep the k8s resources clean.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @Obirah, I think you have raised in the issue in the wrong repo. Testcontainers main feature is being able to run multiple containers in random ports and this is applied to our preconfigured modules. You can see that [K3sContainer expose port 6443](https://github.com/testcontainers/testcontainers-java/blob/main/modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java#L27) from the container side but in the host a random will be provided. You need to ask about it on Quarkus, see [their implementation](https://github.com/quarkusio/quarkus/blob/2737a2ba76e840f6dc42b614e8ffe9328e37350a/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/DevServicesKubernetesProcessor.java#L330)

**Comment by Obirah** [comment]
> Hi @Obirah, I think you have raised in the issue in the wrong repo. Testcontainers main feature is being able to run multiple containers in random ports and this is applied to our preconfigured modules. You can see that [K3sContainer expose port 6443](https://github.com/testcontainers/testcontainers-java/blob/main/modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java#L27) from the container side but in the host a random will be provided. You need to ask about it on Quarkus, see [their implementation](https://github.com/quarkusio/quarkus/blob/2737a2ba76e840f6dc42b614e8ffe9328e37350a/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/DevServicesKubernetesProcessor.java#L330)

Thank you for the quick response! I'm not using Quarkus devservices. I'm following the approach from [this article](https://www.atomicjar.com/2023/09/testcontainers-the-simplest-way-to-test-kubernetes-operators/) and hence would like to create K3sContainers with differents ports in my `K3sResource` class.

**Comment by eddumelendez** [comment]
As I mentioned, K3sContainer already works on random ports, you don't need to configure anything else. However, this could be how Quarkus managed things. You can ask in the proper channel but definitely not an issue in Testcontainers.

**Comment by Obirah** [comment]
> As I mentioned, K3sContainer already works on random ports, you don't need to configure anything else. However, this could be how Quarkus managed things. You can ask in the proper channel but definitely not an issue in Testcontainers.

Can you point me towards where the random ports are determined/set? This might help me to debug where Quarkus might interfere.
