### ISSUE TITLE
[Bug]: localstack/localstack:stable tag doesn't work as expected

### ISSUE THREAD

**Issue by sha1n** [testcontainers/testcontainers-java#7821]
### Module

LocalStack

### Testcontainers version

1.19.2

### Using the latest Testcontainers version?

Yes

### Host OS

macos

### Host Arch

ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

The Localstack project started publishing `stable` image tag. Unlike `latest`, `stable` points at the latest release rather than the latest build. The current implementation of `LocalStackContainer` contains several conditionals around the image version, which assume either `latest` or semver. At least one of those misinterprets the `stable` tag and enables "legacy mode" when it's specified, which breaks things (I guess it's because of the port number resolution).

Here is the code:

```java
    private static boolean shouldRunInLegacyMode(String version) {
        if (version.equals("latest")) {
            return false;
        } else {
            ComparableVersion comparableVersion = new ComparableVersion(version);
            if (comparableVersion.isSemanticVersion()) {
                boolean versionRequiresLegacyMode = comparableVersion.isLessThan("0.11");
                return versionRequiresLegacyMode;
            } else {
                log.warn("Version {} is not a semantic version, LocalStack will run in legacy mode.", version);
                log.warn("Consider using \"LocalStackContainer(DockerImageName dockerImageName, boolean legacyMode)\" constructor if you want to disable legacy mode.");
                return true;
            }
        }
    }
```

### Additional Information

If we agree to fix this, I'm willing to provide a PR.

**Comment by eddumelendez** [comment]
Hi, as mentioned in [Testcontainers best practices](https://www.atomicjar.com/2023/11/testcontainers-best-practices/), we don't recommend the use of `latest`. In this case, `stable` plays a similar role as a mutable image. Upgrades in our opinion should happen with awareness, otherwise, test can be broken by an unexpected change. For that reason, I'm closing this issue.

**Comment by sha1n** [comment]
Thanks @eddumelendez!
I understand the approach and I 100% agree with it most of the time. When I have full control over the version of a product in production, I use the same version in my testing environment. For example, if I use Postgres 13 in production, I am going to use the `postgres:13` image in CI. With `localstack` since it represents an AWS service that changes continuously, I prefer to use a floating version, so I can be as closer to the actual public service version as possible. That's the idea behind what I'm trying to do.
Since you already support `latest`, it basically has the same semantics, so it would be easy to add this as well.
