### ISSUE TITLE
[Bug]: Build fails when "version" is omitted from docker-compose.yml

### ISSUE THREAD

**Issue by bernhof** [testcontainers/testcontainers-java#7825]
### Module

Core

### Testcontainers version

1.19.1

### Using the latest Testcontainers version?

Yes

### Host OS

Alpine Linux v3.18

### Host Arch

x86

### Docker version

```shell
Server Version: 24.0.6
```

### What happened?

We use DockerComposeContainer, and builds fail in our CI environment with the following error:

    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image docker/compose:1.29.2

### Relevant log output

```shell
11:24:41.098 [Test worker] ERROR tc.docker/compose:1.29.2 - Log output from the failed container:
Creating network "pbqs5beuh5ua_default" with the default driver
Pulling <name of image> (<registry url>)...
Head "<manifest url>": denied: access forbidden
```

### Additional Information

Many hours of trial and error revealed the following fix:

Our docker-compose.yml did not contain a "version" element (which is not required by the compose specification). If I add "version: '3'" to my docker-compose.yml file, the build succeeds in the CI environment:

```
version: '3' # must add this
services:
    ...
```

After adding the version element, I see the following log message in our CI environment, which seems to be the main difference between the failing and succeeding builds:

```
o.t.containers.ComposeDelegate - Preemptively checking local images for '<image name>', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
```

If version is ommitted from docker-compose.yml, testcontainers should assume latest compose file version, or at least log a warning that point us in the right direction.

**Comment by eddumelendez** [comment]
Hi, I think you want to use ComposeContainer instead which support [Compose v2](https://www.docker.com/blog/announcing-compose-v2-general-availability/). Please, see the changes on the blogpost entry. We have a [test](https://github.com/testcontainers/testcontainers-java/blob/7112db5c6e493306360818d6bfc261df92c49255/core/src/test/java/org/testcontainers/junit/ComposeContainerScalingTest.java) for that case, see the [compose file](https://github.com/testcontainers/testcontainers-java/blob/7112db5c6e493306360818d6bfc261df92c49255/core/src/test/resources/composev2/scaled-compose-test.yml).

**Comment by bernhof** [comment]
Despite now using `ComposeContainer` and compose v2, removing the version attribute from compose.yaml still causes the build to fail as stated in the issue.

The error is the same and it does not do preemptive image pull if version is omitted.

**Comment by wimdeblauwe** [comment]
Please consider re-opening this issue. We are also using `ComposeContainer` and our tests fail if we remove the version from our `docker-compose.yaml`. The reason is that without the version number in the file, the method `getDependencyImages()` from the class `DockerComposeFiles` returns no images. When the version number is present, the correct number of images is present in the returned `Set`.

The reason is probably due to `ParsedDockerComposeFile` checking if a `version` key is present in the YAML. Given Docker is now actively warning if a version is present, it would be better to revise the logic there I think.
