### ISSUE TITLE
How to configure containers to be accessible from host?

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#787]
Hi guys,

I'm having a hard time configuring my container using TestContainers so that it's accessible from my host computer at `http://localhost:8080`.

Here's what I did:

```
    private void startServletEngine(ExtensionContext extensionContext, File sourceWARDirectory)
    {
        UITest uiTestAnnotation = extensionContext.getRequiredTestClass().getAnnotation(UITest.class);
        GenericContainer servletContainer;
        switch (uiTestAnnotation.servletEngine()) {
            case TOMCAT:
                servletContainer = new GenericContainer<>("tomcat:latest")
                    .withFileSystemBind(sourceWARDirectory.toString(), "/usr/local/tomcat/webapps/xwiki");
                break;
            default:
                throw new RuntimeException(String.format("Servlet engine [%s] is not yet supported!",
                    uiTestAnnotation.servletEngine()));
        }

        // Note: Testcontainers will wait for up to 60 seconds for the container's first mapped network port to start
        // listening.
        servletContainer
            .withNetwork(Network.SHARED)
            .withNetworkAliases("xwikiweb")
            .withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger(this.getClass())))
            .withExposedPorts(8080)
//            .waitingFor(
//                Wait.forHttp("/xwiki/bin/get/Main/WebHome")
//                    .forStatusCode(200))
            .start();
    }
```

Any idea? I've tried to expose the port to the host with `withExposedPorts` (BTW I didn't find how to say the equivalent of `-p 8080:8080` on the docker command line). Am I using `withExposedPorts` in a wrong way?

Thanks

**Comment by bsideup** [comment]
Hi @vmassol,

If you **really** want to do that - use `FixedHostPortGenericContainer` (or check its code to see how to do that)

However, this will make your tests fail on many environments where port 8080 is already taken and will disallow running it in parallel on CI systems.

**Comment by vmassol** [comment]
@bsideup ok. What's the recommended approach when you need to perform some actions on the container? In the XWiki case, I need to do 2 things:
1) verify if XWiki is started already or not. If not then start the DB, the Servlet container, etc.
2) provision XWiki by calling the XWiki REST API

Actually I'm probably confused about something. Are the tests executed inside a container, i.e. inside the shared network? If so then points 1) and 2) will also execute inside since they're located in my JUnit5 extension.

**Comment by bsideup** [comment]
@vmassol please read here:
https://www.testcontainers.org/usage/generic_containers.html#accessing-a-container-from-tests

**Comment by vmassol** [comment]
haha thanks, I had missed this, trying.

**Comment by bsideup** [comment]
@vmassol FYI `waitingFor` is precisely for the `1)` :)

**Comment by vmassol** [comment]
Seems to be working, thanks! I have other issues now but I can progress.

BTW sorry I forgot there was a slack chat and I opened a discussion issue here instead of asking on the chat. Will try to remember for next time.

**Comment by vmassol** [comment]
@bsideup BTW you'll be pleased to know that I blogged about TestContainers here: https://massol.myxwiki.org/xwiki/bin/view/Blog/EnvironmentTestingExperimentations ;)
