### ISSUE TITLE
Spring Boot's Script-based Initialization doesn't work

### ISSUE THREAD

**Issue by emeraldhieu** [testcontainers/testcontainers-java#7922]
### Module

PostgreSQL

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

x86

### Docker version

```shell
Docker version 24.0.6
```

### What happened?

Spring Boot's Script-based Initialization that requires "schema.sql" on the classpath doesn't work.

```
spring:
  sql:
    init:
      mode: always
```

I've had "schema.sql" in the classpath but the test doesn't seem to recognize the file.

See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-initialize-a-database-using-spring-jdbc

**Comment by eddumelendez** [comment]
Hi, you should report this in the spring boot project and attach a project that reproduces the issue.
