### ISSUE TITLE
Spring boot Junit postgres jdbcurl only starts container once.

### ISSUE THREAD

**Issue by jeacott1** [testcontainers/testcontainers-java#796]
Hi All,
  I'm seeing some behaviour I consider odd. 
In a Junit test in spring boot I'm using a postgres jdbc url + the tc: bit, but my postgres container only starts once for the class and not once per test.

I'd expect to see 'Starting container with ID ...' per test, but I'm not.

has anyone else seen this?

**Comment by kiview** [comment]
Hey @jeacott1,
so the JDBC based containers will keep running as long as there is an open connection to them. If the Spring-Context isn't reinitialized, this should be for the entirety of the Spring-Boot tests.

Is this a feature you desire? You can of course always use a container object directly.

**Comment by jeacott1** [comment]
thanks for clearing that up.

I'd very much like to reset my pg container between tests without restarting the world (ie @DirtiesContext(classMode=ClassMode.AFTER_EACH_TEST_METHOD) everytime.

running a startup script @Before that drops/creates everything works ok but I need to manage things like postgres cache by calling DISCARD ALL for example each time. I'd prefer to just restart the container.

an explicit option to restart the container as though all the connections were closed would be very handy.

Cheers.

**Comment by kiview** [comment]
Hi @jeacott1,
yes you can definitely use `@Rule` or manually call `start()/stop()` on your container instance. 
But also in this case make sure, that you re-initialize the datasource, because after the container restart, the JDBC connection pool will have broken connections AFAIK. I don't know what's the easiest way to do it in Spring TBH, would be cool if you can share your solution :slightly_smiling_face:.

**Comment by jeacott1** [comment]
the pool should create new connections (as though there was a network glitch) when the connections are broken by a disappeared container without any intervention. 
for now however I am still leaving the container up per class and drop/create everything for every test. I do have to call DISCARD ALL pre-drop to prevent horrid postgres driver schema cache errors though.

**Comment by sivaprasadreddy** [comment]
Wow, thanks for the super quick answer.

**Comment by kiview** [comment]
Closing, since both questions have been answered.
