### ISSUE TITLE
[Enhancement]: Repackage AWS SDK  in localstack

### ISSUE THREAD

**Issue by hantsy** [testcontainers/testcontainers-java#7960]
### Module

LocalStack

### Proposal

Repackage the AWS SDK in the testcontainers localstack module, such as add a `testcontainers` prefix, in a previous experience, there are some API conflict in the project, due to the different version issues.

**Comment by eddumelendez** [comment]
Hi @hantsy , can you explain a little bit more? Recent versions of LocalStack module doesn't provide transitive dependencies for AWS SDK.

**Comment by hantsy** [comment]
Like wiremock, there is a `standalone` version to repackage all deps with a `wiremock` prefix in the new package, esp, the Jaskson module, to avoid the deps conflicts in my Spring project when running tests.

I will try the new version later, to check if the issue is still there.

**Comment by eddumelendez** [comment]
I'm closing this issue because AWS SDK is not provided anymore in LocalStack.
