### ISSUE TITLE
[Bug]: some properties not being picked up from class testcontainers.properties file

### ISSUE THREAD

**Issue by StanClowes** [testcontainers/testcontainers-java#7967]
### Module

Core

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:23 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### What happened?

Some testcontainers.properties aren't being picked up off the classpath
e.g. checks.disable  or testcontainers.reuse.enable
The code checks environment and user props via getEnvVarOrUserProperty(...)
see - 
https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L179C37-L179C60
https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L185

Where as properties such as image overrides are working as they use getEnvVarOrProperty(...)

Regards

### Relevant log output

```shell
14:04:32.167 [testcontainers-lifecycle-0] INFO org.testcontainers.DockerClientFactory -- Checking the system...
14:04:32.167 [testcontainers-lifecycle-0] INFO org.testcontainers.DockerClientFactory -- ✔︎ Docker server version should be at
```

**Comment by eddumelendez** [comment]
It works as designed.

**Comment by StanClowes** [comment]
this issue was closed stating "It works as designed."

The docs here state https://java.testcontainers.org/features/configuration/
configuration can be picked up off the class path in testcontainers.properties

The documentation even mentions checks.disable yet the bug indicates that certain properties are not picked up this way

**Comment by eddumelendez** [comment]
There are three places as the document states but certain properties are just read from specific such as the ones you mentioned.

[Disabling the startup check](https://java.testcontainers.org/features/configuration/#disabling-the-startup-checks) is clear about where should the property be located and it is the same for [reuse](https://java.testcontainers.org/features/reuse/).

**Comment by StanClowes** [comment]
I think the docs should be clearer but that said it's inconsistent with the initial statement under "Configuration locations"

Environment variables
.testcontainers.properties in user's home folder. Example locations:
Linux: /home/myuser/.testcontainers.properties
Windows: C:/Users/myuser/.testcontainers.properties
macOS: /Users/myuser/.testcontainers.properties
testcontainers.properties on the classpath.
