### ISSUE TITLE
[Bug]: reuse und checks cannot be configured via classpath:testcontainers.properties

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#8060]
### Module

Core

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x64

### Docker version

```shell
n/a
```

### What happened?

Placing a `testcontainers.properties` file at the root of the classpath should allow configuration of testcontainers.

For `testcontainers.reuse.enabled` and `checks.disable` this is not possible as these properties are checked using `getEnvVarOrUserProperty` (which ignores `classpathProperties`) instead of `getEnvVarOrProperty`.

Source code references:
- https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L179
- https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L185

**Comment by kiview** [comment]
Thanks for raising this issue, but this works as intended for these properties, since we believe this should be a user decision, and not a project decision.
