### ISSUE TITLE
Kafka Testcontainer should use bitnami/kafka image, or at least allow it as compatible

### ISSUE THREAD

**Issue by nightswimmings** [testcontainers/testcontainers-java#8107]
### Module

Kafka

### Proposal

Bitnami image has standard kafka version numbers and it's an standard distributor unlike confluent, a private company (who for instance, discontinued their widely used helmchart suddently in favour of a private delpoyment mechanism).
If the blocker was that bitnami kafka images did not support arm arch, they do from kafka 3.2

But at least, we would appriacte being able to make bitnami/kafka compatible as kafkacontainer, because right now it cant be used as image

**Comment by eddumelendez** [comment]
Hi, have you tried using `DockerImageName.parse("bitnami/kafka").asCompatibleSubstituteFor("confluentinc/cp-kafka")`?

**Comment by linghengqian** [comment]
- I think `at least allow it as compatible` would be better. 
- Ignoring `confluentinc/cp-kafka` completely is tricky because issues like https://issues.apache.org/jira/browse/KAFKA-7249 prove that most developers who want to use Kafka’s Docker Image will only Consider `confluentinc/cp-kafka`.

**Comment by eddumelendez** [comment]
For now, there is no plans to support other images.

**Comment by GregoryBevan** [comment]
If it can help developers who wants to use the bitnami/kafka image, here is an example of what I did on a project using Testcontainers

https://gist.github.com/GregoryBevan/53dff416517d6d7ec78d59e9316c7a8e
