### ISSUE TITLE
[Bug]: Hazelcast Client is not working

### ISSUE THREAD

**Issue by haider665** [testcontainers/testcontainers-java#8128]
### Module

Core

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Cloud integration: v1.0.31
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

According to hazelcast client example shown in test container hazelcast example in github, this application should start and run the test case based on testcontainer hazelcast client container. But the application is not starting as it expecting hazelcast running on a certain port of localhost.

**Comment by haider665** [comment]
Here is the sample code for my project

https://github.com/testcontainers/testcontainers-java/discussions/8051

**Comment by eddumelendez** [comment]
Please, do not create an issue if the discussion has been created.
