### ISSUE TITLE
[Bug]: skip-host-cache option removed in latest MySQL 8.3.0 version

### ISSUE THREAD

**Issue by swaroopar** [testcontainers/testcontainers-java#8130]
### Module

MySQL

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Github-hosted runner. Cannot check the docker version.
```

### What happened?

The latest mysql contanier 8.3.0 does not work anymore with testcontainers. It complains about an unknown config option - '--skip-host-cache'.

Tests with previous versions work fines. I don't see mention of any change to this config parameter in the 8.3.0 release notes though. 

```ssh
Error: -19T04:32:46.946550Z 0 [ERROR] [MY-000068] [Server] unknown option '--skip-host-cache'.
Error: -19T04:32:46.946911Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
Error: -19T04:32:46.946926Z 0 [ERROR] [MY-010119] [Server] Aborting
2024-01-19T04:32:48.385535Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
```

Failed Job - https://github.com/eclipse-xpanse/xpanse/actions/runs/7579264089/job/20643575357?pr=1264

Config - https://github.com/testcontainers/testcontainers-java/blob/main/modules/mysql/src/main/resources/mysql-default-conf/my.cnf#L14

**Comment by rowleya** [comment]
I am also seeing this behaviour:
Failed job: https://github.com/SpiNNakerManchester/JavaSpiNNaker/actions/runs/7581397438/job/20648969510

**Comment by wimdeblauwe** [comment]
Running into this as well. The [release note of 8.0.30](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html) does mention the deprecation of the parameter: 


> The [--skip-host-cache](https://dev.mysql.com/doc/refman/8.0/en/server-options.html#option_mysqld_skip-host-cache) server option is now deprecated, and subject to removal in a future release.
>
> Use a statement such as [SET GLOBAL host_cache_size = 0](https://dev.mysql.com/doc/refman/8.0/en/set-variable.html), or set [host_cache_size](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_host_cache_size) in the my.cnf file, instead. (WL #14359)

But indeed nothing about the actual removal in the [8.3.0 release notes](https://dev.mysql.com/doc/relnotes/mysql/8.3/en/news-8-3-0.html#mysqld-8-3-0-deprecation-removal).

**Comment by wimdeblauwe** [comment]
This PR seems to be related: https://github.com/docker-library/mysql/pull/1002

They replaced `skip-host-cache` with `host_cache_size=0` which is probably what will fix it here as well.

**Comment by wimdeblauwe** [comment]
This is a workaround that seems to work for me:

1. Create a `src/main/resources/mysql-default-conf/my.cnf` file in your project
2. Copy the contents of https://github.com/testcontainers/testcontainers-java/blob/main/modules/mysql/src/main/resources/mysql-default-conf/my.cnf into it
3. Replace the line with `skip-host-cache` with `host_cache_size=0`

After that, tests work again.

**Comment by rowleya** [comment]
My current workaround is to use mysql 8.2.0 specifically in my application-test.yml file (this is for the unit testing of a Spring Boot application):
```jdbc-url: jdbc:tc:mysql:8.2.0:///;databaseName=<database>?user=<user>&password=<password>```
