### ISSUE TITLE
[Enhancement]: Get options from an instance of PostgreSQLR2DBCDatabaseContainer 

### ISSUE THREAD

**Issue by SimoneGiusso** [testcontainers/testcontainers-java#8132]
### Module

PostgreSQL

### Proposal

Currently it is possible to get connection details  from an instance of `JdbcDatabaseContainer`. From the [doc](https://java.testcontainers.org/modules/databases/jdbc/):

"
_Now, in your test code (or a suitable setup method), you can obtain details necessary to connect to this database:_

_mysql.getJdbcUrl() provides a JDBC URL your code can connect to
mysql.getUsername() provides the username your code should pass to the driver
mysql.getPassword() provides the password your code should pass to the driver_
"

However this seems not possible with an instance of `R2DBCDatabaseContainer`.  Although there is a `@Delegate` annotation [here](https://github.com/testcontainers/testcontainers-java/blob/4ff8d1dc17d353b63ad5dda699f88acd78dfb763/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLR2DBCDatabaseContainer.java#L13) it doesn't seem I have access to the underlying container connection detail.

**Comment by eddumelendez** [comment]
Check https://java.testcontainers.org/modules/databases/r2dbc/#obtaining-connectionfactoryoptions-from-database-container-objects
