### ISSUE TITLE
[Bug]: 'Docker wormhole' pattern - docker detection failed

### ISSUE THREAD

**Issue by pekuz** [testcontainers/testcontainers-java#8214]
### Module

Core

### Testcontainers version

1.19.4

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86_64

### Docker version

```shell
docker version
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:46:45 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:44:25 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

By https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/ if no volumes are used, testcontainers should detect and use hosting docker if testcontainers are executed in a container.

In reality I got:

`UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)`

### Relevant log output

```shell
#12 411.0 15:59:09.439 INFO  [main] o.t.i.PullPolicy Image pull policy will be performed by: DefaultPullPolicy()
#12 411.0 15:59:09.444 INFO  [main] o.t.u.ImageNameSubstitutor Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
#12 411.0 15:59:09.791 INFO  [main] o.t.d.DockerMachineClientProviderStrategy docker-machine executable was not found on PATH ([/opt/java/openjdk/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin])
#12 411.0 15:59:09.791 ERROR [main] o.t.d.DockerClientProviderStrategy Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
#12 411.0 	UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
#12 411.0 	DockerDesktopClientProviderStrategy: failed with exception NullPointerException (null). Root cause NullPointerException (null)As no valid configuration was found, execution cannot continue.
#12 411.0 See https://java.testcontainers.org/on_failure.html for more details.
#12 411.0 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.259 s <<< FAILURE! - in com.hierynomus.smbj.IntegrationTest
#12 411.0 [ERROR] com.hierynomus.smbj.IntegrationTest  Time elapsed: 1.259 s  <<< ERROR!
#12 411.0 java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
#12 411.0 
#12 411.0 [INFO] 
#12 411.0 [INFO] Results:
#12 411.0 [INFO] 
#12 411.0 [ERROR] Errors: 
#12 411.0 [ERROR]   IntegrationTest » IllegalState Could not find a valid Docker environment. Plea...
#12 411.0 [INFO] 
#12 411.0 [ERROR] Tests run: 209, Failures: 0, Errors: 1, Skipped: 2
```

### Additional Information

Using SambaContainer from the https://github.com/hierynomus/smbj project if relevant.

**Comment by eddumelendez** [comment]
> if no volumes are used, testcontainers should detect and use hosting docker if testcontainers are executed in a container.

Testcontainers provides a way to detect the docker socket in some specific locations as you can see in the logs. In the case you are describing, as far as I understand, the container where the test are executed doesn't have a docker socket so test can not run. That's why mounting the socket is needed as you can see in the docs.

**Comment by pekuz** [comment]
I understand and I see it as the doc bug.

IMHO at https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/ 

> However, additional configuration is required if you use [volume mapping](https://java.testcontainers.org/features/files/).

should be reformulated. Additional configuration is needed in more cases.


And also https://java.testcontainers.org/on_failure.html should mention the d-in-d case, linking it back to https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/ .

  Hope it helps
  Cc.

**Comment by eddumelendez** [comment]
> > However, additional configuration is required if you use [volume mapping](https://java.testcontainers.org/features/files/).
>
> should be reformulated. Additional configuration is needed in more cases.

I don't get it. The doc list the two things to take into account to make it work.

Regarding to https://java.testcontainers.org/on_failure.html this is specifically to the container runtime detection and not the different patterns used.

**Comment by kiview** [comment]
You are right, the docs are misleading. The following point
> The docker socket must be available via a volume mount

is always required for the Docker Wormhole pattern to work, not only in case of using volume mounts.
Would you like to contribute the change to the docs as a PR?

**Comment by pekuz** [comment]
Such PR should be a small effort relative to already spent testing and reporting. I could handle (at backburner velocity) unless I give up on testcontainers, still exploring if it acceptably fits.

**Comment by pekuz** [comment]
By [#1112](https://github.com/testcontainers/testcontainers-java/issues/1112), I understand that testcontainers are not usable during `docker build` (which is what our CI does).  

From `docker build`, `RUN mvn install` that include testcontainers tests has no chance to succeed, no wormholing helps here. (I have tried `RUN --mount=rw,from=/var/run/docker.sock,target=/var/run/docker.sock` but to no avail.)

**Comment by pekuz** [comment]
@kiview there are 66 github repositories, which one has doc source, please?

**Comment by carlos-silva24** [comment]
Hey @pekuz, so what was stated on https://github.com/testcontainers/testcontainers-java/issues/1112 still applies right? there is still no possibility to run testcontainers during the docker build stage.

Found some things related to this like exposing docker daemon on port 2375 and using some env variables, like this: 
ENV DOCKER_HOST=tcp://host.docker.internal:2375 
ENV TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal 

but not sure if this is the best approach.
