### ISSUE TITLE
duplicate key value violates unique constraint when running tests twice

### ISSUE THREAD

**Issue by fplaten** [testcontainers/testcontainers-java#825]
Hey guys,

I'm using a custom postgres image for my integration tests and everything works fine when I run the tests for the first time.

However, the database doesn't seem to be cleaned after each test, because I get the following exception:

`PSQLException: ERROR: duplicate key value violates unique constraint`

My code:

`
@RunWith(SpringRunner.class)
@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
public abstract class AbstractIntegrationTest {

    @Rule
    public PostgreSQLContainer postgreSQLContainer =
        (PostgreSQLContainer) new PostgreSQLContainer("kartoza/postgis:9.6-2.4")
            .withUsername("postgres")
            .withPassword("postgres")
            .withStartupTimeout(Duration.ofSeconds(600));
}`

And the test:

```
public class DummyTest extends AbstractIntegrationTest {

    @Test
    @Sql(statements = {"insert into user(id, location) values('0911d31d-0095-4fdf-956c-d0172648606e', ST_GeomFromText('POINT(-71.064544 42.28787)'))"})
    public void getUser() {
        User user = findUserById("0911d31d-0095-4fdf-956c-d0172648606e");
    }

    @Test
    @Sql(statements = {"insert into user(id, location) values('0911d31d-0095-4fdf-956c-d0172648606e', ST_GeomFromText('POINT(-71.064544 42.28787)'))"})
    public void getUser2() {
        User user = findUserById("0911d31d-0095-4fdf-956c-d0172648606e");
    }
}
```

On the first run, just the second test fails, on the second run both tests fail. Is there a way to clean the database after each test? I thought @Rule does that, but it doesn't help.

**Comment by fplaten** [comment]
I solved it. If anybody's interested in the code: 

```
@After
    @Transactional
    public void cleanUp() {
        TransactionTemplate transactionTemplate = new TransactionTemplate(platformTransactionManager);
        transactionTemplate.execute(new TransactionCallbackWithoutResult() {
            @Override
            protected void doInTransactionWithoutResult(TransactionStatus status) {
                Metamodel metamodel = em.getMetamodel();

                em.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
                for (EntityType<?> e : metamodel.getEntities()) {
                    String entityTableName = e.getJavaType().getAnnotation(Table.class).name();
                    em.createNativeQuery("truncate table P2P." + entityTableName).executeUpdate();
                }
                em.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
            }
        });
    }
```

**Comment by kiview** [comment]
Hey @fplaten,
this is interesting, since `@Rule` should restart the container in between tests.

How did you inject the jdbc url into your Spring context?
