### ISSUE TITLE
Docker Toolbox does not support mounting files and fails when trying to mount dummy file in Ryuk

### ISSUE THREAD

**Issue by huksley** [testcontainers/testcontainers-java#827]
When starting ResourceReaper instance
there is an attempt to mount file (classfile, binary?!) as /dummy

Extracted from ResourceReaper.java (and edited for brewity):

```java
MountableFile mountableFile = MountableFile.forClasspathResource(ResourceReaper.class.getName().replace(".", "/") + ".class");
if (withDummyMount) {
  // Not needed for Ryuk, but we perform pre-flight checks with it (micro optimization)
  binds.add(new Bind(mountableFile.getResolvedPath(), new Volume("/dummy"), AccessMode.ro));
}
```

This results in following error up startup:

```json
{"invalid volume specification: 'C:\\Users\\Ruslan\\AppData\\Local\\Temp\\.testcontainers-tmp-8195821502169083677:/dummy:ro'"}
```

If putting `checks.disable = true` into `testcontainers.properties` when withDummyMount will be `false`
so there will be no such error.

It is OK to mount a directory, but you can not mount a file using Docker Toolbox for Windows.

**Comment by kiview** [comment]
Hopefully mostly fixed by #829.
I'll close it for now, please give feedback if the problem persist for your use cases @huksley.
