### ISSUE TITLE
[Feature]: Support custom "reuse hash" in GenericContainer

### ISSUE THREAD

**Issue by kberezin-nshl** [testcontainers/testcontainers-java#8285]
### Module

Core

### Problem

This is mostly a follow up to this [PR decision](https://github.com/testcontainers/testcontainers-java/pull/8282)

It was closed, and the reason for that is:
> the suggested approach doesn't ensure a consistent and deterministic behavior from Testcontainers due to the container configuration won't be taken into account

is simply incorrect.

Please, @eddumelendez , could you elaborate on why is it deterministic if
```
var container1 = new GenericContainer().withExposedPorts(12345);
var container2 = new GenericContainer().withExposedPorts(23456);
```

produce _different_ results according to configuration, wheraes

```
var container1 = new GenericContainer().withCustomReuseHash("hash1");
var container2 = new GenericContainer().withCustomReuseHash("hash2");
```
is not deterministic and surprises the user?

Isn't it apparent to the user that the configuration is different in both cases? I don't understand the reasoning.

### Solution

One of the solution is this [PR](https://github.com/testcontainers/testcontainers-java/pull/8282)

Another would be to be less restrictive to library users and allow them to make their own engineering decisions, like make related methods `protected` and not `final`

### Benefit

Flexibility. There is always a way to bypass whatever barriers library designer is imposed, but at what cost? 

### Alternatives

Forking the repo or wrapping everything into Java Proxies which makes the code dirty but invalidates all the protections you have in the code.

### Would you like to help contributing this feature?

Yes, I did that already: https://github.com/testcontainers/testcontainers-java/pull/8282

**Comment by kberezin-nshl** [comment]
Sorry I accidentally created the bug report before I finished writing it, hence the edits

**Comment by eddumelendez** [comment]
If a custom hash is allowed then container configuration will be ignored at all and if different hashes are configured it could lead to errors. The approach about support custom hashes is not how we would like to tackle this issue.

**Comment by kberezin-nshl** [comment]
```
var container1 = new GenericContainer().withExposedPorts(12345);
var container2 = new GenericContainer().withExposedPorts(23456);

var container3 = new GenericContainer().withCustomReuseHash("hash1");
var container4 = new GenericContainer().withCustomReuseHash("hash2");
```

> configuration will be ignored at all 
In the code snippet above I see 4 different configurations producing 4 different container hashes. Why do you think it is ignored at all?

More than that

```
var container5 = new GenericContainer().withStartupTimeout(1L);
var container6 = new GenericContainer().withStartupTimeout(1000L);
```

will produce the same hash. And it is way _less_ obvious than the proposed solution.


> The approach about support custom hashes is not how we would like to tackle this issue.
Could you elaborate on how you would like to tackle this issue?

**Comment by kberezin-nshl** [comment]
> The approach about support custom hashes is not how we would like to tackle this issue.

Could you elaborate on how you would like to tackle this issue? @eddumelendez

**Comment by eddumelendez** [comment]
> Why do you think it is ignored at all?

The current hash take the container configuration to be consistent, that's what I meant.
