### ISSUE TITLE
[Enhancement]: Make the .testcontainer.properties follow the XDG Base Directory specification

### ISSUE THREAD

**Issue by janderssonse** [testcontainers/testcontainers-java#8303]
### Module

Core

### Proposal

On Linux, many, many applications today follow in the XDG Base Specficiation for their config files. In short that means that the config file for an application would be found in the standard dir $HOME/.config/APPNAME/CONFIGFILE, (or first, if present, to another location to which the $XDG_CONFIG_HOME-env points to.

Which in this case would mean that on Linux the .testcontainer.properties would also be found on the following path: $HOME/.config/testcontainers/testcontainer.properties in most cases . 

Currently the .testcontainers.properties does not respect the standard and is only found directly in the users home folder hardcoded as such (which is fine but should be the third place too look).

The order should be:
 $XDG_CONFIG_HOME (if path set)
 then 
$HOME/.config/testcontainers/testcontainer.properties  
then 
users home dir (like current implementation).

This will lead to users having less clutter in their home directories, and with other perks that comes with following a standard, like ease of backup (of the $HOME/.config-dir) etc.

The XDG Base Specification:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

A list of apps supporting it from the arch wiki (not complete)
https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by eddumelendez** [comment]
Thanks for raising the issue, @janderssonse. However, this proposal was rejected before, See https://github.com/testcontainers/testcontainers-java/pull/6326

**Comment by janderssonse** [comment]
Thanks for your response @eddumelendez  - was there any deeper technical motivation behind the project not wishing to follow the standard, besides 'internal discussion' as refered to in #6326 ? .Curious as to why a project would not want to.

**Comment by janderssonse** [comment]
Hi  @eddumelendez was there any more detailed causes to as why this was closed, instead of "internal discussion" referred to?
