### ISSUE TITLE
[Bug]: Many custom variables do not take effect when using custom configurations

### ISSUE THREAD

**Issue by e-mhui** [testcontainers/testcontainers-java#8316]
### Module

Core

### Testcontainers version

main

### Using the latest Testcontainers version?

Yes

### Host OS

MacOs

### Host Arch

ARM

### Docker version

```shell
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.43 (downgraded from 1.44)
 Go version:        go1.21.6
 Git commit:        4debf411d1
 Built:             Tue Feb  6 20:42:40 2024
 OS/Arch:           darwin/arm64
 Context:           colima

Server: Docker Engine - Community
 Engine:
  Version:          24.0.9
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.13
  Git commit:       fca702d
  Built:            Thu Feb  1 00:48:30 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

When using [custom configurations](https://java.testcontainers.org/features/configuration/), many variables do not take effect, some can only obtain values from environment variables, and some can only obtain values from user configurations. For example:

1. `boolean useRyuk = !Boolean.parseBoolean(System.getenv("TESTCONTAINERS_RYUK_DISABLED"));`
2. `getConfigurable(propertyName, defaultValue, userProperties, classpathProperties);`
3. `getConfigurable(propertyName, defaultValue, userProperties);`

I believe that the method for retrieving variables should be unified using the `getEnvVarOrProperty method`.

**Comment by eddumelendez** [comment]
Closing as commented in https://github.com/testcontainers/testcontainers-java/pull/8317#issuecomment-1949623695. This is working as designed.
