### ISSUE TITLE
[Feature]: Add consumer for logging into file

### ISSUE THREAD

**Issue by JakubJablonski2-TomTom** [testcontainers/testcontainers-java#8320]
### Module

Core

### Problem

Debugging multiple test containers running in parallel is hard due to interleaved logs.

### Solution

Allow to configure each container to log to a separate file.
In addition to ToStringConsumer, add a ToFileConsumer which forwards all the logs to a file.

### Benefit

Extended flexibility and user friendliness

### Alternatives

Document in for clients how to implement their own LogConsumer doing the same thing.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Closing because this can be done as described [here](https://github.com/testcontainers/testcontainers-java/pull/8321#issuecomment-2401066022)
