### ISSUE TITLE
[Bug]: Containers not shut down between tests when using .withReuse(true) but env. does not support reuse

### ISSUE THREAD

**Issue by jgracin** [testcontainers/testcontainers-java#8323]
### Module

Core

### Testcontainers version

latest from master and 1.19.4

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

ARM

### Docker version

```shell
Client:
 Version:           24.0.7-rd
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.10
 Git commit:        72ffacf
 Built:             Wed Nov  1 18:41:50 2023
 OS/Arch:           darwin/arm64
 Context:           rancher-desktop

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.11
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri Nov 17 20:59:57 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

Using Spring Boot Testcontainers, when an environment does not support "reuse" but `container.withReuse(true)` is set, containers are not shutting down between tests, resulting in a pile-up of container instances that wait until all the tests are finished before being shut down.

I tracked it down to the following:

When an environment does not support container reuse (i.e. .testcontainers.properties does not have `testcontainers.reuse.enabled=true`), but a container is set up using `container.withReuse(true)`, Testcontainers-Java framework (in `GenericContainer.tryStart()`) decides that the container is not reusable. However, the `isShouldBeReused()` method continues to return `true`, because it only reflects the values set by `.withReuse()`, and not the fact that the container cannot really be reused because of the environment.

Spring Boot Testcontainers module in `TestcontainersLifecycleBeanPostProcessor.postProcessBeforeDestruction()` checks `container.isShouldBeReused()` and decides it will not shut down the container even though the container cannot be reused because the environment does not support it.

### Additional Information

I'd happily provide a PR for the fix, but I'd need some input on the desired approach. I see several options.
1. Change `.withReuse()` to take into account whether the environment and container implementation support reuse (`canBeReused()` is also the existing method). E.g.
```
public SELF withReuse(boolean reusable) {
        this.shouldBeReused =
            reusable && TestcontainersConfiguration.getInstance().environmentSupportsReuse() && canBeReused();
        return self();
    }
```

2. Leave `withReuse()` as is, but change `isShouldBeReused()` to return `reusable && TestcontainersConfiguration.getInstance().environmentSupportsReuse() && canBeReused()`.

4. Leave `withReuse()` and `isShouldBeReused()` as is, but introduce another getter `isReused()` that would hold the `reused` value determined in `tryStart()`, which would indicate whether the container has really been reused or not. This would be an API change requiring clients to change. (BTW, I've created [a related ticket](https://github.com/spring-projects/spring-boot/issues/39609) in Spring Boot Testcontainers.)

**Comment by eddumelendez** [comment]
Hi @jgracin, sorry for the delay. We would like to follow approach number 3, there is already a [reusable](https://github.com/testcontainers/testcontainers-java/blob/a69750c3d796777770bec1920018917dac792e14/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L394) variable that store the final value. Are you still willing to contribute?

**Comment by kiview** [comment]
Thanks for reporting @jgracin, it seems it has now been fixed downstream in Spring-Boot:
https://github.com/spring-projects/spring-boot/commit/f210d83062422af46bb91c256b45e12e30f6dcf1

I think it is totally fine like this and we can close the issue on our side.
