### ISSUE TITLE
Unable to pull images from AWS ECR

### ISSUE THREAD

**Issue by ffissore** [testcontainers/testcontainers-java#836]
I'm using testcontainers 1.8.3. I have a test db image on a private repo on AWS ECR.

When I run my tests with
`eval $(aws ecr get-login --no-include-email); mvn clean test`
testcontainers is unable to pull the image.

Error message is 
`com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://REPOID.dkr.ecr.eu-west-1.amazonaws.com/v2/IMAGENAME/manifests/IMAGETAG: no basic auth credentials"}`

My `.docker/config.json` is
```
{
	"auths": {
		"REPOID.dkr.ecr.eu-west-1.amazonaws.com": {
			"auth": "AUTH"
		},
		"https://index.docker.io/v1/": {
			"auth": "AUTH"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.06.0-ce (linux)"
	}
}
```

Attached a snippet of the logs [log.txt](https://github.com/testcontainers/testcontainers-java/files/2292907/log.txt)

**Comment by ffissore** [comment]
As with #835, downgrading testcontainers to 1.8.0 works around the issue

**Comment by rnorth** [comment]
Sorry you've had a problem as well, @ffissore. As this looks like the same problem as #835 I'll add your comment to that ticket and close this one.
