### ISSUE TITLE
[Enhancement]: use official kafka image

### ISSUE THREAD

**Issue by rajadilipkolli** [testcontainers/testcontainers-java#8398]
### Module

Kafka

### Proposal

From 3.7.0 version of kafka official image is being released which can be found at https://hub.docker.com/r/apache/kafka , Can we start supporting instead of using confluent.

I tried to use official image using .asCompitableSubstitue of confluent image but it is will not working.

**Comment by eddumelendez** [comment]
Thanks for raising the issue! I would like to know if Kraft mode would be enough for you or are you expecting zookeeper support?

**Comment by rajadilipkolli** [comment]
Hi @eddumelendez , as they started official image only from 3.7.0 where zookeeper is deprecated. I think only kraft mode is enough.

**Comment by Mitchell-Eaton** [comment]
Any updates on this? Our team would benefit from it. Thanks!

**Comment by rajadilipkolli** [comment]
Hi @eddumelendez , from which version this is available to use ?

**Comment by eddumelendez** [comment]
Hi, Testcontainers 1.19.8 contains `org.testcontainers.kafka.KafkaContainer`

**Comment by eddumelendez** [comment]
It's a new implementation and spring boot doesn't support it yet. There is a open PR https://github.com/spring-projects/spring-boot/issues/40695

**Comment by rajadilipkolli** [comment]
Thank you for the swift response @eddumelendez
