### ISSUE TITLE
Testcontainers binds file as a directory when run in other container

### ISSUE THREAD

**Issue by Bartoneczek** [testcontainers/testcontainers-java#842]
Hi,

I've got a problem with binding file system path in the container in Jenkins.

There is some resource file called 'config.json' in my Java project. I need to put it dynamically in '/config' directory in some container on running it. I have no problems with that on my local, using 'container.withFileSystemBind()'. I'm calling it like:

![image](https://user-images.githubusercontent.com/7407653/44344390-e3450f80-a490-11e8-84cf-69a9bb08b9ac.png)

Logs looks like:

> LIST FILES:
Element: /Users/user/Projects/my-service/build/resources/test/simulator/config.json isFile?: true isDirectory?: false
MOUNTING: /Users/user/Projects/my-service/build/resources/test/simulator/config.json TO /config/config.json

And everything works. The problem is when I'm running tests in different container. Using the same code, 'config.json' file is binded... as a directory. Executing 'ls -la /config' in container results with:

![image](https://user-images.githubusercontent.com/7407653/44344898-10de8880-a492-11e8-8879-c6801b513471.png)

And everything looks ok (in logs):

> LIST FILES:
Element: /home/jenkins/workspace/ailable-as-docker-container-TGZOBDR7RPDL3Z5RUNQLQASECTHLB5ZB76ED6GDOP2RKONZ6QKTA/build/resources/test/simulator/config.json isFile?: true isDirectory?: false
MOUNTING: /home/jenkins/workspace/ailable-as-docker-container-TGZOBDR7RPDL3Z5RUNQLQASECTHLB5ZB76ED6GDOP2RKONZ6QKTA/build/resources/test/simulator/confg.json TO /config/config.json

Do you have any idea why my file is binded as a directory?

Thanks in advance for any help and any advice!

**Comment by McKratt** [comment]
Is this thread solve your problem : https://github.com/testcontainers/testcontainers-java/issues/668 ?

**Comment by kiview** [comment]
@Bartoneczek Would `withCopyFileToContainer()` work for you? It's in general much more portable for containerized environments.

Does your build node run inside a container, using docker socket mounting? This would mean, you are mounting file from your host.

I'll close this for now, please say something, if it doesn't work you.
