### ISSUE TITLE
NullPointerEXception with slf4j for app running over tomcat version 8

### ISSUE THREAD

**Issue by balonideepak** [testcontainers/testcontainers-java#847]
Hi Team,
I am getting NullPointerException for a webapp running over tomcat version 8. I am sending request to the webapp one after the other for 10 iterations and it's failing with below exception:

Slfj jars inside WEB-INF/lib directory : 
slf4j-api-1.7.7.jar
slf4j-log4j12-1.6.1.jar

java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at org.apache.log4j.MDC.put0(MDC.java:139)
        at org.apache.log4j.MDC.put(MDC.java:74)
        at org.slf4j.impl.Log4jMDCAdapter.put(Log4jMDCAdapter.java:35)
        at org.slf4j.MDC.put(MDC.java:116)

If I add a delay of some seconds everything works fine without any exception .
Please help me in resolving the issue.

Below are the libraries inside my WEB-INF/lib directory : 
activemq-broker-5.11.1.jar
activemq-client-5.11.1.jar
activemq-core-5.7.0.jar
activemq-openwire-legacy-5.11.1.jar
activemq-protobuf-1.1.jar
annotations-2.0.1.jar
archaius-core-0.4.1.jar
asm-3.1.jar
aspectjrt-1.8.9.jar
aspectjweaver-1.7.2.jar
cglib-2.2.jar
classmate-1.3.1.jar
com.springsource.org.apache.commons.lang-2.1.0.jar
commons-beanutils-1.9.1.jar
commons-collections-3.2.1.jar
commons-configuration-1.9.jar
commons-io-2.4.jar
commons-lang-2.6.jar
commons-lang3-3.2.1.jar
commons-logging-1.2.jar
commons-net-3.1.jar
cxf-core-3.1.11.jar
cxf-rt-frontend-jaxrs-3.1.11.jar
cxf-rt-rs-service-description-swagger-3.1.11.jar
cxf-rt-transports-http-3.1.11.jar
dozer-5.5.1.jar
general-exceptions-1.0.71.jar
geronimo-j2ee-management_1.1_spec-1.0.1.jar
geronimo-jms_1.1_spec-1.1.1.jar
guava-18.0.jar
hamcrest-core-1.3.jar
hawtbuf-1.9.jar
hawtdispatch-1.11.jar
hawtdispatch-transport-1.11.jar
hibernate-validator-5.3.4.Final.jar
hsqldb-2.3.4.jar
hystrix-core-1.5.9.jar
ifxjdbc-3.50.JC8.jar
ifxjdbcx-3.50.JC8.jar
jackson-annotations-2.7.0.jar
jackson-core-2.7.4.jar
jackson-core-asl-1.1.1.jar
jackson-databind-2.7.4.jar
jackson-dataformat-yaml-2.8.4.jar
jackson-jaxrs-1.1.1.jar
jackson-jaxrs-base-2.8.5.jar
jackson-jaxrs-json-provider-2.8.5.jar
jackson-mapper-asl-1.1.1.jar
jackson-module-jaxb-annotations-2.8.5.jar
jasypt-1.9.0.jar
javassist-3.19.0-GA.jar
javax.annotation-api-1.2.jar
javax.el-2.2.4.jar
javax.el-api-2.2.4.jar
javax.inject-1.jar
javax.servlet-api-3.1.0.jar
javax.ws.rs-api-2.0.1.jar
jboss-logging-3.3.0.Final.jar
jcl-over-slf4j-1.7.21.jar
jersey-client-1.19.jar
jersey-core-1.19.jar
jul-to-slf4j-1.6.1.jar
junit-4.12.jar
kahadb-5.7.0.jar
log4j-1.2.16.jar
logback-classic-1.1.7.jar
logback-core-1.1.7.jar
logging-utils-0.0.1.jar
logistics-common-0.1.5.jar
metrics-annotation-3.1.2.jar
metrics-core-3.1.2.jar
metrics-graphite-3.1.2.jar
metrics-healthchecks-3.1.2.jar
metrics-json-3.1.2.jar
metrics-jvm-3.1.2.jar
metrics-servlet-3.1.2.jar
metrics-servlets-3.1.2.jar
mockito-all-1.10.19.jar
mqtt-client-1.3.jar
netty-buffer-4.1.8.Final.jar
netty-codec-4.1.8.Final.jar
netty-codec-dns-4.1.8.Final.jar
netty-codec-http-4.1.8.Final.jar
netty-codec-http2-4.1.8.Final.jar
netty-codec-socks-4.1.8.Final.jar
netty-common-4.1.8.Final.jar
netty-handler-4.1.8.Final.jar
netty-handler-proxy-4.1.8.Final.jar
netty-resolver-4.1.8.Final.jar
netty-resolver-dns-4.1.8.Final.jar
netty-transport-4.1.8.Final.jar
nextgen-common-utils-0.0.22.jar
objenesis-1.2.jar
objenesis-2.1.jar
powermock-api-mockito-1.6.3.jar
powermock-api-support-1.6.3.jar
powermock-core-1.6.3.jar
powermock-module-junit4-1.6.3.jar
powermock-module-junit4-common-1.6.3.jar
powermock-reflect-1.6.3.jar
reflections-0.9.10.jar
rxjava-1.2.0.jar
slf4j-api-1.7.7.jar
slf4j-log4j12-1.6.1.jar
snakeyaml-1.15.jar
spring-aop-4.3.6.RELEASE.jar
spring-beans-4.3.6.RELEASE.jar
spring-context-4.3.6.RELEASE.jar
spring-core-4.3.6.RELEASE.jar
spring-expression-4.3.6.RELEASE.jar
spring-jdbc-4.3.4.RELEASE.jar
spring-jms-4.3.4.RELEASE.jar
spring-messaging-4.3.4.RELEASE.jar
spring-retry-1.2.0.RELEASE.jar
spring-test-4.3.4.RELEASE.jar
spring-tx-4.3.4.RELEASE.jar
spring-web-4.3.4.RELEASE.jar
stax2-api-3.1.4.jar
surefire-api-2.16.jar
swagger-annotations-1.5.12.jar
swagger-core-1.5.12.jar
swagger-jaxrs-1.5.12.jar
swagger-models-1.5.12.jar
swagger-ui-2.2.10-1.jar
tomcat-jdbc-8.0.37.jar
tomcat-juli-8.0.37.jar
validation-api-1.1.0.Final.jar
vertx-core-3.4.1.jar
web-utils-1.0.13.jar
woodstox-core-asl-4.4.1.jar
xmlschema-core-2.2.1.jar

**Comment by bsideup** [comment]
I'm closing the issue because of no response. Feel free to re-open it 👍
