### ISSUE TITLE
TC_INITSCRIPT support relative paths

### ISSUE THREAD

**Issue by basicfu** [testcontainers/testcontainers-java#850]
I see in `ContainerDatabaseDriver` class

 * If <code>TC_INITSCRIPT</code> is set in <i>querystring</i>, it will be used as the path for an init script that
 * should be run to initialize the database after the container is created. This should be a classpath resource.

```
    URL resource = Thread.currentThread().getContextClassLoader().getResource(initScriptPath);

    if (resource == null) {
    LOGGER.warn("Could not load classpath init script: {}", initScriptPath);
    throw new SQLException("Could not load classpath init script: " + initScriptPath + ". Resource not found.");
    }
```

My initialization script has been in the project has a root directory,Don't want a copy to classpath resource,Can you add a form from the project root directory,Or use absolute paths？

**Comment by kiview** [comment]
Hey @basicfu,
you are right. Would you like to provide a PR?

Probably the regex pattern for parsing the JDBC url has to be changed accordingly:
https://github.com/testcontainers/testcontainers-java/blob/dbb92674f3dd3de0f8b8de5c2c1c88b39dd72f00/modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionUrl.java#L174

**Comment by basicfu** [comment]
@kiview sure!

**Comment by KaRkY** [comment]
Will this allow to reference a script outside from classpath?
My usecase is that I am using this for code generation while building with maven and I would like to reference a script in a directory.
