### ISSUE TITLE
DockerComposeContainer with Selenium Grid example

### ISSUE THREAD

**Issue by sskorol** [testcontainers/testcontainers-java#86]
Hi @rnorth, thanks for the good project!

However, I have several questions: 
- Do you have any samples of using DockerComposeContainer with Selenium Grid? I want to use official selenium images (hub, node-firefox-debug / node-chrome-debug) as separate containers to be able to scale them via `docker-compose scale` option. Not really sure if it's possible to pass `scale image=N` cmd args to already started containers.
- Are you planning to add TestNG support? I noticed that you strictly dependent from JUnit Rules to be able to start / stop containers before / after test execution. What would be an effort to create a similar TestNG runner?

**Comment by rnorth** [comment]
Hi,
Thank you :)

These are great questions!

* No, I've not got an example of that use case, but it's an interesting one. I think that, probably, Testcontainers should have a `.scale(String name, int size)` method on the `DockerComposeContainer` class to allow containers to be scaled. There will be a bit of work needed under the covers to make this work, but it'd be nice.
* Yes, with hindsight I wish I'd kept JUnit support as a separate module. For a future release, I think I'd like to break out JUnit support from core; this would make it much easier to use other test frameworks. In the meantime you _could_ call the `start()` and `stop()` methods on a container object from TestNG BeforeTest/AfterTest methods. Of course, Testcontainers will still carry a JUnit classpath dependency, which is ugly...

Thanks
Richard

**Comment by sskorol** [comment]
@rnorth thanks! Would be great to see these features soon.

By the way, I also noticed that `BrowserWebDriverContainer` is dependent from `selenium/standalone-firefox(chrome)-debug` images. With current approach we're able to run tests only in a single browser. But the main selenium grid's feature is in scaling. Would be nice to see some more generic container + specific child implementations. E.g. splitted hub / node / standalone containers, which could have existing class as a Base one (with some minimal updates).
