### ISSUE TITLE
[Feature]: Add support for pgvector in jdbc url's

### ISSUE THREAD

**Issue by thijslemmens** [testcontainers/testcontainers-java#8633]
### Module

PostgreSQL

### Problem

I'd like to use pgvector in my Spring boot applications. Currently, I cannot indicate this in my jdbc url like for TimeScaleDB and postgis. I would like to add support for urls like this:
jdbc:tc:pgvector:14:///

Currently, I use this
jdbc:tc:postgresql:14:///

and I wrote a ImageNameSubstitutor to swap out the image. 

### Solution

Write a JdbcDatabaseContainerProvider for PGVector

### Benefit

This makes it very easy to support PGVector in TestContainers.

### Alternatives

Creating the container in code or write a ImageNameSubstitutor.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @thijslemmens, PR is welcome
