### ISSUE TITLE
Add a reusable redash container

### ISSUE THREAD

**Issue by aahmed-se** [testcontainers/testcontainers-java#867]
https://redash.io/ is popular database integration target , need to allow it bring up and run sample queries against different database targets.

**Comment by kiview** [comment]
So something using [this](https://hub.docker.com/r/redash/redash/) image and along the lines of this docker-compose:
https://github.com/getredash/redash/blob/master/docker-compose.yml

Have you tried starting with this docker-compose?

**Comment by aahmed-se** [comment]
wanted to make a single redash container image first. Then use compose to link to data another data source container.

**Comment by rnorth** [comment]
I think that this probably doesn't warrant a new module, and there doesn't seem to be much demand. I'll close - if there's a compelling reason why this is needed we can revisit later.
