### ISSUE TITLE
Support Windows Containers

### ISSUE THREAD

**Issue by dtretyakov** [testcontainers/testcontainers-java#870]
Currently `testcontainers` library works only in Linux containers mode and does not support the following modes:
* Windows containers
* [LCOW via LinuxKit](https://blogs.msdn.microsoft.com/premier_developer/2018/04/20/running-docker-windows-and-linux-containers-simultaneously/)

The significant problem here is using [Ryuk](https://github.com/testcontainers/moby-ryuk) for resources cleanup by filters: it's used as Linux docker image and requires mounting `/var/run/docker.sock` from the host.

Possible workarounds:
* Ryuk Windows docker image. Cons - docker engine access to the container, images size will be 100+mb (nanoserver-1803).
* JVM-based implementation of resource cleaner. Cons - lack of filter methods for networks & volumes (https://github.com/docker-java/docker-java/pull/1100)

The second option could be implemented as in-process cleanup as JVM shutdown hook or as a out of process application. Pros here is using the same connection to the docker engine as `testcontainers` lib (mounting `/var/run/docker.sock` limits that ability).

**Comment by kiview** [comment]
Hey @dtretyakov,

I was also trying out Windows Containers in an experimental branch, in theory Testcontainers supports them transparently. Ryuk is of course a problem, as well as other, Linux container based, sidecar and auxiliary containers.

Since I really don't see us moving away from a sidecar container approach for certain use cases, I would assume we won't support Windows Containers before the hybrid WCOW and LCOW modes are supported.

Btw. I didn't understand why Ryuk doesn't work for LCOW? It works perfectly fine for Docker for Windows. What am I missing here?

**Comment by dtretyakov** [comment]
I've made a preliminary solution to address current problem in Windows & LCOW containers of using Ryak side container https://github.com/testcontainers/testcontainers-java/pull/872. It works in process and uses shutdown hook as mentioned by @bsideup.

@kiview, in Docker for Windows we should distinguish the following different working modes:
* **Linux Containers** - uses hyperv isolation and starts a complete Linux VM, so it's possible to mount `/var/run/docker.sock` in Ryak side container.
* **Windows Containers** - uses process or hyperv isolation to start containers. It's possible to mount named pipe to the container starting with Windows containers 1709, e.g. `docker run ... -v \\.\pipe\docker_engine:\\.\pipe\docker_engine`
* **LCOW** - uses [LinuxKit](https://github.com/linuxkit/linuxkit) project to start lightweight VM and [allows starting simultaneously Linux and Windows containers](https://blogs.msdn.microsoft.com/premier_developer/2018/04/20/running-docker-windows-and-linux-containers-simultaneously/). In this mode there is no way to mount `/var/run/docker.sock` to Ryak side container, except one [extremely hacky way](https://blogs.technet.microsoft.com/virtualization/2017/12/08/wsl-interoperability-with-docker/).

So in case of Windows & LCOW modes there is no way to start side container and bypass into it connection to the current Docker Engine.

Thus I'll try to start a child JVM process which will cleanup resources on parent JVM process termination.

Please let me know if I missed another use cases which are handled by Ryak container in current solution and after my refactoring: [RyakResourceManager.java](https://github.com/testcontainers/testcontainers-java/blob/2b7c8f83290ef8d134fc665c7eb6af34f8c4318f/core/src/main/java/org/testcontainers/RyakResourceManager.java)

**Comment by rnorth** [comment]
Thanks for the thorough explanation - this makes more sense now. 

Re this:
> Thus I'll try to start a child JVM process which will cleanup resources on parent JVM process termination.

Please could you give us a bit of time to think this over before you put too much effort into it? It sounds good in principle but I don’t want to waste your time if we think of another way. We’ll get back to you shortly.

**Comment by kiview** [comment]
Hey @dtretyakov,
thanks for your explanation regarding the different working modes on Windows. I was not aware of the fact, that we won't have the Unix socket available when using hybrid LCOW mode, but it makes sense.
Btw. I don't think their provided solution is too hacky and we might think about following a similar solution and a statically compiled Go binary.

Regarding a JVM child process:
This will still lead to orphaned Testcontainers containers in many CI scenarios, when canceling build jobs.

As mentioned above, we also have other Linux based sidecar containers for some specialized container implementations, so a Windows Container support without hybrid mode seems unreasonable for me as well. On the other hand, if we can easily achieve support for Windows Container in `GenericContainer` we might think about providing it as experimental support.

**Comment by dtretyakov** [comment]
In the latest changes of PR (https://github.com/testcontainers/testcontainers-java/pull/872) it's possible to start Windows containers as a `GenericContainer`.

To handle docker resources cleanup there used detached (not a child) side process which connects via socket to the testcontainers process. Testcontainer process termination or killing will trigger socket connection terminatin in side process and removal of docker resources matching filters. Since this side process is detached from the testcontainers process it allows gracefully cleanup resources, e.g. during debugging tests in IDE.

Currently it's missing windows-specific commands handling in `InternalCommandPortListeningCheck` due to lack of "platform" property in InspectContainerResponse (https://github.com/docker-java/docker-java/pull/1099). If somebody could review & merge changes in the `docker-java` it could help.
