### ISSUE TITLE
ability to run ResourceReaper as privileged container

### ISSUE THREAD

**Issue by kamkie** [testcontainers/testcontainers-java#871]
on our setup ryuk contener is failing to start without `--privileged` flag 
adding  withPrivileged on org/testcontainers/utility/ResourceReaper.java:78 solwes this for us 

it would be nice if this was configurable using properties/TestcontainersConfiguration

**Comment by kiview** [comment]
Just so I can understand better, why does it fail for you without the flag? Because of your daemon settings?

**Comment by kamkie** [comment]
yes, on openshift installation docker is configured in more strict way
and to access docker.sock eather `--privileged` or some `--cap-add` is required

i even don't remember exact  what capabiliti it was

**Comment by kiview** [comment]
Setting it in properties/TestcontainersConfiguration sounds good to me.

**Comment by kiview** [comment]
@kamkie Any chance you can test #894 and check if it solves your problem?

**Comment by kamkie** [comment]
I will try to find time today for that
