### ISSUE TITLE
Master snapshot not found

### ISSUE THREAD

**Issue by sscarduzio** [testcontainers/testcontainers-java#878]
Hello!
We at ReadonlyREST are a fan of testcontainers and our CI always builds against the master snapshot in order to early detect and report any behaviour changes, issues, and of course access the latest and greatest code earlier.

However, this time Gradle cannot find the dependency though.

Our dependency:
```
    compile 'com.github.testcontainers.testcontainers-java:testcontainers:master-SNAPSHOT'

```

Our CI log:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':tests-utils:compileClasspath'.
> Could not resolve com.github.testcontainers.testcontainers-java:testcontainers:master-SNAPSHOT.
  Required by:
      project :tests-utils
   > Could not resolve com.github.testcontainers.testcontainers-java:testcontainers:master-SNAPSHOT.
      > Unable to load Maven meta-data from https://jitpack.io/com/github/testcontainers/testcontainers-java/testcontainers/master-SNAPSHOT/maven-metadata.xml.
         > Could not get resource 'https://jitpack.io/com/github/testcontainers/testcontainers-java/testcontainers/master-SNAPSHOT/maven-metadata.xml'.
            > Could not GET 'https://jitpack.io/com/github/testcontainers/testcontainers-java/testcontainers/master-SNAPSHOT/maven-metadata.xml'.
               > Read timed out
```

**Comment by kiview** [comment]
Hi @sscarduzio,
I think this can sometimes happen, if Jitpack is in the process of building a new artifact. It might time out in this case.

But looks like it's available now :slightly_smiling_face: 
https://jitpack.io/#testcontainers/testcontainers-java/-SNAPSHOT

Can you try again?

**Comment by sscarduzio** [comment]
Yes you were right! Thanks!
