### ISSUE TITLE
[Enhancement]: Allow configuration of what files are copied into the container for docker compose

### ISSUE THREAD

**Issue by wimdeblauwe** [testcontainers/testcontainers-java#8847]
### Module

Core

### Proposal

The current docker compose support copies all files that are in the directory of the docker compose file into the container that runs the docker compose. This leads to Out Of Memory exceptions in case there are a lot of files in that directory (or subdirectories).

I would like to make it possible to restrict the files that are copied via an inclusion mechanism. I will open a PR with a possible implementation which we then further can discuss.

**Comment by nobvaillant** [comment]
Just a question: is there a reason, why all files of the folder where the compse file is located in, have to be copied?
