### ISSUE TITLE
GenericContainer runs in endless loop, when image does not exist

### ISSUE THREAD

**Issue by mlex** [testcontainers/testcontainers-java#89]
When using GenericContainer with an image, that does not exist on dockerhup (which happened to me because of a typo), then there is a endless loop in `GenericContainer.java:244`. It would be better to print a clear error message in this case.

To workaround https://github.com/docker/docker/issues/10708 one could retry N times before printing an error.

**Comment by rnorth** [comment]
Thanks for raising this - I'll have a look. I thought the image pull was wrapped in a loop with a max number of retries, but it seems I missed this.
