### ISSUE TITLE
[Feature]: GCLOUD pubsub emulator automatic project/topic/sub creation on startup

### ISSUE THREAD

**Issue by MV-GH** [testcontainers/testcontainers-java#8943]
### Module

GCloud

### Problem

Currently creating projects/topics/subs is quite the manual work. While this is the main goal of using a pubsub emulator in the first place.

### Solution

Many other pubsub emulators provide an easy way to setup project/topic/sub based on some defaults.

For example:
https://github.com/marcelcorso/gcloud-pubsub-emulator?tab=readme-ov-file#automatic-topic-and-subscription-creation
All that is needed is to set this ENV `PUBSUB_PROJECT1=company-dev,invoices:invoice-calculator,chats:slack-out:irc-out,notifications`

Or https://github.com/PlaytikaOSS/testcontainers-spring-boot/tree/develop/embedded-google-pubsub#readme
Which allows you specify it through yaml config file

Like so

```yaml
 embedded.google.pubsub.topics-and-subscriptions[0].topic=topic0_name
 embedded.google.pubsub.topics-and-subscriptions[0].subscription=subscription0_name
 embedded.google.pubsub.topics-and-subscriptions[1].topic=topic0_name
 embedded.google.pubsub.topics-and-subscriptions[1].subscription=subscription0_name
 embedded.google.pubsub.topics-and-subscriptions[1].dead-letter.topic=topic0_name
 embedded.google.pubsub.topics-and-subscriptions[1].dead-letter.max-attempts=5
 ``` 
 
So I would like to expose an API to do so similarly. 
 
For my usecase I only need project/topic/sub. I don't need deadletter or specific configuration of the sub/topic like message ordering. I'll leave that for a later expansion.
 
Instead of yaml config file or environment var, I am thinking of just allowing you to set a Map with topic as key and list of sub as value. 
 

### Benefit

Like mentioned before, the main feature of pubsub emulator is to emulate the topics/sub for integration testing. Allowing a user to easily create these without much manual setup. Allows for much greater all around experience.

### Alternatives

We could use a image that has this feature already baked in. But then we wouldn't be using the official gcloud image that we use right now. Doing so would also bind us to this third party. And further feature expansion would be dependent on this too.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
I think it would be nice if the gcloud emulator would offer this feature OOTB, [this](https://issuetracker.google.com/issues/new?component=187143&template=800102&pli=1) is the best place to raise this request. I understand it is quite repetitive task but it also depend of how do you want to configure the topic and subscriber, right? Sorry if talking non-sense, not an expert on this. The easy way to it if already know about pubsub would be

```java
public class MyPusSubEmulatorContainer extends PubSubEmulatorContainer {

    @Override
    protected void containerIsStarted(InspectContainerResponse containerInfo) {
        execInContainer(...)
    }

}
```

If want to use an existing image along with the PubSubEmulatorContainer then [Image Name Substitution](https://java.testcontainers.org/features/image_name_substitution/) would help to reuse existing implementation.

**Comment by MV-GH** [comment]
> I think it would be nice if the gcloud emulator would offer this feature OOTB, [this](https://issuetracker.google.com/issues/new?component=187143&template=800102&pli=1) is the best place to raise this request.

I do not have much faith in Google adding such feature, the development isn't very active

>  I understand it is quite repetitive task but it also depend of how do you want to configure the topic and subscriber, right? Sorry if talking non-sense, not an expert on this. The easy way to it if already know about pubsub would be

I do not fully understand what you mean. But if mean you topic/sub settings like ackDeadline, message ordering, filtering, ... These features aren't not needed for majority of tests. Simply leaving it to the default is more than sufficient for my usecase.

> If want to use an existing image along with the PubSubEmulatorContainer then [Image Name Substitution](https://java.testcontainers.org/features/image_name_substitution/) would help to reuse existing implementation.

This is basically the alternative but the downside is that the waiting strategy would still be on when pubsub is started and not when it is done with creating the pub/sub.


The plan is to use the API to create these. Pretty much what PlayTikka does.
See here https://github.com/PlaytikaOSS/testcontainers-spring-boot/blob/develop/embedded-google-pubsub/src/main/java/com/playtika/testcontainer/pubsub/PubSubResourcesGenerator.java

and then adapt the waiting strategy to wait until its done creating the resources.

**Comment by eddumelendez** [comment]
> I do not have much faith in Google adding such feature, the development isn't very active

It is worth trying. This module exists because the Google team created the image with emulators installed. I made the request.

> I do not fully understand what you mean. But if mean you topic/sub settings like ackDeadline, message ordering, filtering, ...

Yes, I meant that.

> The plan is to use the API to create these.

This is not an option. It will tight the Testcontainers implementation with the client library.

I don't think this is currently possible.
