### ISSUE TITLE
Gradle plugin resolution fails intermittently during CI builds

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#898]
This is a problem with Testcontainers' build process, rather than an issue with the library that users would experience.

This was mentioned in #894, but I think we've been seeing this problem quite regularly in the last few weeks. The symptom is most/all of the CI jobs for a particular revision fail at the point of downloading Gradle plugins from `https://plugins.gradle.org`. I suspect this is either due to problems with the Gradle plugin repo servers (which I think are on Bintray) or a network connectivity issue between CI and those servers.

If we can do anything to make this less likely to occur, it would make it easier for people submitting/reviewing PRs.

**Comment by rnorth** [comment]
Here's an example: https://circleci.com/gh/testcontainers/testcontainers-java/4562

**Comment by kiview** [comment]
Is there even something we can do about it? What about using some CI caching mechanism to cache the resolved plugins?
