### ISSUE TITLE
[Bug]: java.lang.ClassNotFoundException: org.testcontainers.kafka.KafkaContainer

### ISSUE THREAD

**Issue by jhchee** [testcontainers/testcontainers-java#9073]
### Module

Kafka

### Testcontainers version

1.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

MacOs

### Host Arch

X86

### Docker version

```shell
Client:
 Version:           26.1.0-rd
 API version:       1.44 (downgraded from 1.45)
 Go version:        go1.21.9
 Git commit:        cca8e72
 Built:             Tue Apr 23 16:24:24 2024
 OS/Arch:           darwin/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       e63daec8672d77ac0b2b5c262ef525c7cf17fd20
  Built:            Sun May 12 07:25:43 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.10
  GitCommit:        4e1fe7492b9df85914c389d1f15a3ceedbb280ac
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

Gotten the following error after upgrade to 1.20.1
```bash
Caused by: java.lang.ClassNotFoundException: org.testcontainers.kafka.KafkaContainer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 83 more
```

Surprisingly, `org.testcontainers.containers.KafkaContainer` works fine.

**Comment by eddumelendez** [comment]
Can you make sure you only have one Testcontainers version 1.20.1 in the classpath?

In maven: mvn dependency:tree
In gradle: ./gradlew dependencies

**Comment by jhchee** [comment]
Hi @eddumelendez thanks for your reply, the command above only produces one version output.
In addition, I have also used bom to govern the dependencies.

**Comment by jhchee** [comment]
I'm using Spring boot 2.7.18, not sure that matters.

**Comment by jhchee** [comment]
Adding the following resolves my issue
```xml
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka-test</artifactId>
</dependency>
```

@eddumelendez do you know how this helps?

**Comment by eddumelendez** [comment]
Can you share a project that reproduce it, please?

**Comment by jhchee** [comment]
Hi @eddumelendez 
I managed to resolve the issue by adding the following:
```
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka-test</artifactId>
</dependency>
```
@eddumelendez do you know how this helps?

**Comment by eddumelendez** [comment]
I don't have enough context about the issue. For better diagnostic would be great to have a small project that reproduces the issue.

**Comment by jhchee** [comment]
That's alright, I will close this bug ticket as this is resolved.
