### ISSUE TITLE
invalid volume specification on Windows with remote docker machine

### ISSUE THREAD

**Issue by trajano** [testcontainers/testcontainers-java#909]
FYI: I'm not using Docker for Windows since I need to use VirtualBox rather than HyperV in order to run emulators for Android concurrently.

I tried creating a small test driver with the following dependencies

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <version>1.9.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

`compose-test.yml` is from the examples provided (removed the `elasticsearch` because that image does not exist in the main docker registry)

```
redis:
  image: redis
```

Then I created a test file
```
public class ComposeTest {
    @ClassRule
    public static DockerComposeContainer environment =
            new DockerComposeContainer(new File("src/test/resources/compose-test.yml"))
                    .withExposedService("redis_1", 6379);
    @Test
    public void test() {
    }
}
```

I get the following error in the stack trace
`Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"invalid volume specification: 'D:/dh/mylj-ws/mylj-ws-war/src/test/resources/:/d/dh/mylj-ws/mylj-ws-war/src/test/resources/:ro'"}`

**Comment by trajano** [comment]
I also tried adding 

COMPOSE_CONVERT_WINDOWS_PATHS=0

and

COMPOSE_CONVERT_WINDOWS_PATHS=1

to the environment still didn't work.

**Comment by trajano** [comment]
also tried 

                    .withEnv("COMPOSE_CONVERT_WINDOWS_PATHS", "0")
and
                    .withEnv("COMPOSE_CONVERT_WINDOWS_PATHS", "1")

**Comment by trajano** [comment]
withLocalCompose(true) gives me

`org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 1 whilst running command: up -d`

**Comment by kiview** [comment]
So regarding your last comment, it was solved for you by using `withLocalCompose(true)`?

**Comment by trajano** [comment]
Yes it worked in the end, but some things need to be fixed, one is the examples you need to remove `elasticsearch`

Secondly, we should be able to use `withLocalCompose` default value which is `false`.
