### ISSUE TITLE
[semi-off topic] Maven plugin which spawns postgres database for other plugins

### ISSUE THREAD

**Issue by pbillen** [testcontainers/testcontainers-java#910]
Hi,

I realize this might be a bit off topic, so feel free to show me the door if this is not appropriate :).

I am using a Maven plugin which generates code given a database. The obvious problem is that this database instance is not always available, such as during CI builds. This results in a broken build. Usually, this is tackled by only executing the plugin manually. For example, whenever the database schema changes, the developer could manually build and push the artifact to the repository. Although this works, it's not always very practical in larger environments.

My idea is to introduce a Maven plugin which spawns (and runs/waits for the necessary initialization scripts) a database in a Docker container, which can be used by subsequent Maven plugins, such as the generator mentioned above.

Does any of you happen to know such plugin? My searches did not yield anything useful.

That said, I believe this could be easily done with... tadaa... Testcontainers, which already does the heavy part. In case such plugin is not already available, I might invest some time to develop this.

Best regards!

**Comment by kiview** [comment]
Hi @pbillen,
have you checked out [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin)?
It doesn't use Testcontainers, but it seems to apply to your use case.

Which Maven Plugin do you use for migrating the schema? There are normally also Java APIs available to achieve the same result, which can be used in classic Testcontainers scenarios.

**Comment by pbillen** [comment]
Hi @kiview,

I did not know about fabric8 docker-maven-plugin. I believe it does exactly what I want (and a lot, lot more). Thank you very much for providing me that information, it saves me a lot of time!

Regarding your question about schema migration: I am doing this in a Docker image as well. Given certain environment variables (host, port, role, password, ...) this image tries to initialize or migrate a database. In this image, bash scripts and Flyway are being used.

Thanks again!
