### ISSUE TITLE
[Feature]: Add ability to overwrite entrypoint

### ISSUE THREAD

**Issue by kwolsink** [testcontainers/testcontainers-java#9121]
### Module

None

### Problem

It currently seems not possible to overwrite the docker entrypoint of a given test container (as least as far as I am aware). It seems it is possible in other programming languages but not in java (dotnet example: https://github.com/testcontainers/testcontainers-dotnet/discussions/572)

### Solution

We can add a `withCommand` method to the `Container` interface. This is similar with how other languages have implemented it.

### Benefit

It allows people greater flexibility when starting containers. It also brings the java version more in line with the other versions of other programming languages.

### Alternatives

The only real alternative I am aware of is to modify the docker image to use `CMD` instead of `ENTRYPOINT` and replace it with `withCommand`. However, this has a lot of issues because ideally you wouldn't want to create a seperate image just for testing purposes.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @kwolsink, it is actually possible. Take a look at how we use it

https://github.com/testcontainers/testcontainers-java/blob/8db891a386782a682f64650f536aa2a18445a239/modules/kafka/src/test/java/org/testcontainers/containers/KafkaContainerTest.java#L197-L203


Read more in the [docs](https://java.testcontainers.org/features/advanced_options/#customizing-the-container).

**Comment by eddumelendez** [comment]
Closing giving there is no response and Testcontainers for Java already cover it.
