### ISSUE TITLE
[Enhancement]: LocalStackContainer.Service is missing GLUE

### ISSUE THREAD

**Issue by mikhailsnnt** [testcontainers/testcontainers-java#9147]
### Module

LocalStack

### Proposal

Add GLUE support according to LocalStack

**Comment by eddumelendez** [comment]
Hi, see the code snippet in [this section](https://java.testcontainers.org/modules/localstack/#hostname_external-and-hostname-sensitive-services). Use `LocalStackContainer.EnabledService.named("events")`
