### ISSUE TITLE
Exception when running tests under Windows 8

### ISSUE THREAD

**Issue by pierre-leonard** [testcontainers/testcontainers-java#919]
Hi,

I'm trying to run unit tests using testcontainers and Docker toolbox. All tests fail because of this exception:

`Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files (x86)\Git\bin"
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.testcontainers.utility.CommandLine.executableExists(CommandLine.java:67)
	at org.testcontainers.utility.DockerMachineClient.isInstalled(DockerMachineClient.java:53)`

My bash.exe is not there anyway. But even if it was, it would throw the same exception I guess. How can I update this path?

**Comment by pierre-leonard** [comment]
Solved by checking the source code. Testcontainers is actually looking for docker-machine.exe and for that, checks every directory in the path environment variable until it finds it. So '"' symbol should be removed from there. if using Eclipse, you should restart it after that.

**Comment by krmahadevan** [comment]
I stumbled into the same exact problem for someone in the team. The root cause of the problem was that there was a directory location added to the `PATH` variable which contained a `"` (double quotes in it) which was causing this problem.

**Comment by kiview** [comment]
On a side note, Docker Toolbox (as utilized on Windows 8) is not officially supported by Testcontainers anymore and not actively tested by. Also see https://www.testcontainers.org/supported_docker_environment/.

**Comment by krmahadevan** [comment]
@kiview thanks for sharing that additional context. In my case we hit this problem on windows 10. The OS is a newer one but the root cause was the same. 

Maybe we could consider wrapping this exception and putting in a more descriptive error message. I ask because we spent a couple of hours looking for the cause and only because of this defect we were able to identify the root cause.

**Comment by kiview** [comment]
I hear you, but I am not sure if Testcontainers should have additional handling for this. But I wonder, if a directory with  a `"` is added to the `PATH` in a valid way, why would `sun.nio.fs.WindowsPathParser.normalize()` fail in this case? Is this in a way an upstream Java bug?

**Comment by krmahadevan** [comment]
@kiview - Could be.. I am not sure.. But for sure it doesnt seem to be able to handle the quotes in the path, while I dont see the problem happen in OSX.

**Comment by krmahadevan** [comment]
In `org.testcontainers.utility.DockerMachineClient#isInstalled` we could try and wrap 

```
    public boolean isInstalled() {
        return executableExists(executableName);
    }
```
Within a `try..catch` and maybe give a better error message is what I was trying to check with you.

**Comment by kiview** [comment]
Maybe it is even better to simply log `InvalidPathException` and try to continue (as discussed in https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/427). We should validate, if `"` is valid in a Windows path.

**Comment by krmahadevan** [comment]
@kiview - You mean that we wrap [this](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/CommandLine.java#L66) line within a `try..catch` block, log the invalid path as a warning, and then continue iterating over the rest of the directories that are path of the `PATH` variable ?

**Comment by kiview** [comment]
Exactly. However, I'd still like to understand if this is something to be expected as an element in the Windows `PATH`, e.g. for escaping spaces. If yes, we might also assume, our way of handling the content of the Windows `PATH` here is to naïve:
https://github.com/testcontainers/testcontainers-java/blob/9c09b431d412fd154c007a65082b5c2daed80487/core/src/main/java/org/testcontainers/utility/CommandLine.java#L77

**Comment by padmajadav** [comment]
I found similar issue in Windows 10 and corrected Windows environment variable where I was seeing my PATH variables quoted in "". Removal of "" from Environment Variable --> path variable Fix the issue.
