### ISSUE TITLE
[Bug]: Allow pull timeout configuration

### ISSUE THREAD

**Issue by arnaud-thorel-of** [testcontainers/testcontainers-java#9191]
### Module

Core

### Testcontainers version

1.20

### Using the latest Testcontainers version?

Yes

### Host OS

All

### Host Arch

All

### Docker version

```shell
Latest
```

### What happened?

During CI build there is an exception when pullImage takes over than 2 minutes

Is it possible to allow pull timeout configuration (by env variable) to allow more than 2 minutes pulling ?

**Comment by pujakarakoti07** [comment]
I want to take this issue, can you please assign this to me?

**Comment by pujakarakoti07** [comment]
@arnaud-thorel-of please review this.

**Comment by pujakarakoti07** [comment]
@arnaud-thorel-of can you please review the PR?
