### ISSUE TITLE
[Feature]: New Database Tibero

### ISSUE THREAD

**Issue by birdieHyun** [testcontainers/testcontainers-java#9193]
### Module

New Module

### Problem

The problem is that there is currently no official Docker image for the Tibero database, which makes it difficult for developers who rely on this database, especially in regions like Korea where Tibero is widely used.

### Solution

The proposed solution is to create a custom Docker image for the Tibero database and integrate it into our project. This will enable developers to easily use the Tibero database in a Docker environment, streamlining development and testing processes.

### Benefit

Adding this feature will provide support for the Tibero database, which is popular in certain regions such as Korea. It will enhance the flexibility and accessibility of the project for developers who prefer or need to use Tibero, expanding our user base.

### Alternatives

One alternative is to wait for an official Docker image for Tibero, but there is no guarantee on the timeline or availability.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @birdieHyun, thanks for the suggestion. Currently, Testcontainers doesn't produce images for any module. My suggestion is that you can start building the image and produce a Testcontainers module for Tibero that you can host.  Maybe that action can raise some interest and get an official image. We can list it in the [Official Module Catalog](https://testcontainers.com/modules/)

If you have any question about how to build and release your own module, please join the [slack](https://slack.testcontainers.org/) channel and let us know. We will be happy to help you.
