### ISSUE TITLE
[Bug]: can't pull an image that only has linux/amd64 platform on ARM Mac OS

### ISSUE THREAD

**Issue by monosoul** [testcontainers/testcontainers-java#9214]
### Module

Core

### Testcontainers version

1.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

Mac OS

### Host Arch

ARM

### Docker version

```shell
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.0 (165256)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Trying to pull a Docker image that only has `linux/amd64` as a platform causes `com.github.dockerjava.api.exception.NotFoundException`.
If the image manifest in the registry doesn't contain the platform it is pulled for, the registry will return 404 with the following body: `{"message":"no match for platform in manifest: not found"}`. Docker-java will throw `com.github.dockerjava.api.exception.NotFoundException` in such case (instead of `DockerClientException`), so the fallback to x86 will never be attempted.
See: https://github.com/testcontainers/testcontainers-java/blob/0217e78eb986da4e73402288959d05f34b37546f/core/src/main/java/org/testcontainers/images/RemoteDockerImage.java#L156-L163

**Comment by eddumelendez** [comment]
Hi @monosoul , the ideal workflow would be to raise an issue or discussion, triage it and then raise the PR. Since the PR was raised first then there is no need to raise the issue later. I'm closing it in favor of #9200
