### ISSUE TITLE
[Enhancement]: Allow to override PULL_RETRY_TIME_LIMIT

### ISSUE THREAD

**Issue by arnaud-thorel-of** [testcontainers/testcontainers-java#9216]
### Module

Core

### Proposal

RemoteDockerImage set value on PULL_RETRY_TIME_LIMIT to 2 minutes max

Is it possible to override this duration directly on a specific container by setting an env variable 
PULL_RETRY_TIME_LIMIT_MINUTES = 3

**Comment by eddumelendez** [comment]
Hi @arnaud-thorel-of, I saw you already raised #9191. I'm closing this one as duplicated.
