### ISSUE TITLE
[Enhancement]: suggestion for additional container labels added by default

### ISSUE THREAD

**Issue by tomsit-ionos** [testcontainers/testcontainers-java#9219]
### Module

Core

### Context
I started playing with TC desktop and [mapping to fixed ports.](https://testcontainers.com/desktop/docs/#debug-testcontainers-based-services)
The config allows to use container label to select the right container in case u run >1 form the same image.

[ATM ](https://github.com/testcontainers/testcontainers-java/blob/0217e78eb986da4e73402288959d05f34b37546f/core/src/test/java/org/testcontainers/containers/JibTest.java#L83) there these labels are present on TC controlled containers: e.g.
```
"org.testcontainers": "true",
"org.testcontainers.lang": "java",
"org.testcontainers.sessionId": "cd4e15d6-2a33-4637-ba06-816f21226ebb",
"org.testcontainers.version": "1.19.6",
```

### Proposal

IMO it would be helpful to add the following additional labels by default, so this doesn't have to be done manually:

####  org.testcontainers.java.testClass
Example: `"org.testcontainers.java.test-class": "MyTcTest"`
Denotes the class (simple name is IMO sufficient) that is responsible for starting the container.

#### org.testcontainers.java.project
Example:  `"org.testcontainers.java.project": "my project name"`

Denotes the name of the project. However, there is no clear cut way of getting this. 
In most cases it's likely to be sufficient to get the dir name of $PWD/user.dir

**Comment by eddumelendez** [comment]
Hi, thanks for the suggestion but those labels will break reusable container feature. Also, Testcontainers is not only used in test anymore in Micronaut, Quarkus and Spring boot projects but also enable local development.
