### ISSUE TITLE
Reaper process exposed on container host network

### ISSUE THREAD

**Issue by j-o-h-n-g** [testcontainers/testcontainers-java#923]
Could you clarify if the Reaper container is exposed to the hosts network by design?  I can't see any way of modifying this behaviour, but this seems potentially dangerous so wondering if I am missing something.
```
        String ryukContainerId = client.createContainerCmd(ryukImage)
                .withHostConfig(new HostConfig().withAutoRemove(true))
                .withExposedPorts(new ExposedPort(8080))
                .withPublishAllPorts(true)
                .withName("testcontainers-ryuk-" + DockerClientFactory.SESSION_ID)
                .withLabels(Collections.singletonMap(DockerClientFactory.TESTCONTAINERS_LABEL, "true"))
                .withBinds(binds)
                .withPrivileged(TestcontainersConfiguration.getInstance().isRyukPrivileged())
                .exec()
                .getId();
```

In particular this means that if I use testcontainers-java in my code anyone running the tests end up with a reaper container exposed on their docker host.  For a developer laptop on a untrusted network this seems open to abuse.

I'm not sure why the Reaper container requires this, can the containers not communicate directly with the Reaper container inside the docker network?    Even a configuration option to disable the Reaper functionality entirely doesn't seem to exist?

**Comment by kiview** [comment]
Exposed port is needed to communicate with the Ryuk container from inside the JVM (which is running on the host).
