### ISSUE TITLE
How to start OracleContainer in a fixed  port?

### ISSUE THREAD

**Issue by renjithz** [testcontainers/testcontainers-java#925]
currently OracleContainer return JDBC_URL with random port. Because of this I am not able to connect to the DB from application. Currently my application JDBC_URL configured in a property file and and noway I can override it as part of the test. I have tried exposed ports but its not giving me a fixed port

OracleContainer mysql =
                (OracleContainer)new OracleContainer("/wnameless/oracle-xe-11g:18.04").withExposedPorts(49161);
        mysql.addExposedPort(49161);

**Comment by kiview** [comment]
Which kind of framework are you using? Maybe using the Testcontainers JDBC Url suits your use case better? https://www.testcontainers.org/usage/database_containers.html#junit-rule

We generally discourage the usage of fixed ports and therefore don't provide the option in the specialized containers implementations. 

`withExpostedPorts()` should be used in conjunction with `getMappedPorts()`.

**Comment by rnorth** [comment]
I'd agree with @kiview's suggestion of using the `tc` JDBC URL scheme here. That's what this feature is designed for: situations like this, where you can't programmatically inform your code/config of a random port.

[This test](https://github.com/testcontainers/testcontainers-java/blob/master/modules/oracle-xe/src/test/java/org/testcontainers/containers/OracleJDBCDriverTest.java) shows a concrete example.

Does this help, @renjithz?

**Comment by xenogew** [comment]
@rnorth 
Could you suggest another example?
Your link is 404 not found not.

And I've tried with `tc` Jdbc Url pattern with MyBatis with initialize datasource bean on Spring Boot.
It was thrown with `Error querying database.  Cause: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:tc:mysql:5.7.34:///databasename` pattern.
How could I access database from `tc` pattern, if I cannot fixed port?

**Comment by kiview** [comment]
@xenogew This issue is unrelated to `OracleContainer`, please create either a separate issue for this or ask a question regarding Testcontainers usage and best practices in our [GitHub discussions forum](https://github.com/testcontainers/testcontainers-java/discussions).

With regards to the original issue, I will close this, since Testcontainers advocates against the usage of fixed ports and provides programmatic access to mapped ports.
