### ISSUE TITLE
BrowserWebDriverContainer configure does overwrite no_proxy environment variable

### ISSUE THREAD

**Issue by roamingthings** [testcontainers/testcontainers-java#928]
Hi,

I've noticed that the `configure()` method of `BrowserWebDriverContainer` is setting the environment variable to `localhost` regardless of another value that might already been present. This means that it is not possible to set a custom `no_proxy` value:
```
    @Rule
    public final BrowserWebDriverContainer chromeWithProxy = (BrowserWebDriverContainer) new BrowserNoProxyWebDriverContainer()
            .withDesiredCapabilities(chrome())
            .withRecordingMode(RECORD_ALL, new File("."))
            .withEnv("HTTP_PROXY", "http://my.proxy.com:8080")
            .withEnv("HTTPS_PROXY", "https://my.proxy.com:8080")
            .withEnv("no_proxy", "localhost,.noproxy-domain.com");
```

I've implemented a fix to this issue
https://github.com/roamingthings/testcontainers-java/commit/4ed091b54a175c83de42addc72ac91487e805358

Regards,
Alex

**Comment by kiview** [comment]
Hi @roamingthings, looks good, would you like to provide the PR?
