### ISSUE TITLE
How to stream "docker logs" to logger used by JUnit?

### ISSUE THREAD

**Issue by asafm** [testcontainers/testcontainers-java#94]
When I run a Generic Container, and it has error inside, I would like to stream its "docker logs" command to the slf4j so I can see what's going on inside the docker.
Currently I put thread.sleep(), run docker ps, get the name, run docker logs and then see the error.

**Comment by rnorth** [comment]
Hi,
Yes, as-is there's no capability for streaming container stdout, but it shouldn't be too hard to add. Hopefully this is something I can add soon - any contributions would be appreciated too, though!
Richard

**Comment by bsamartins** [comment]
Logs can be redirected to a logging framework from the docker client using the log command API.

**Comment by rnorth** [comment]
@asafm: does this implementation I've added here look good to you? This includes sending logs to an SLF4J logger and waiting for expected log output, which was something I wanted to add for a while.

The implementation is hopefully flexible enough to allow a fairly broad set of behaviours and other logging frameworks to be added easily. I still need to add docs, though.

**Comment by asafm** [comment]
Just checked it. Awesome work buddy! 
Only thing I would add is prefixing each output with the container name

**Comment by asafm** [comment]
From my end the issue can be closed
