### ISSUE TITLE
How to connect to private docker registry

### ISSUE THREAD

**Issue by ayedo** [testcontainers/testcontainers-java#940]
Hi all!

I'm enjoying working with test containers so far!

Unfortunately, I cannot figure out how to configure it to authenticate with a private docker registry before pulling images? Is it possible? I could not find it in the documentation.

**Comment by rnorth** [comment]
Hi Alon,
I’m glad to hear you’re enjoying using it! 

As for private registries, things should ‘just work’. We use any credentials that have been set by docker login, or credentials obtained via the Docker credentials helper/store mechanism. 

Basically, if a docker pull works, Testcontainers should also work. 

It’s possible you’ve found an exception, and I certainly do think I need to add a bit more to the docs. 

Please let me know if you’ve tried it and if anything strange happened. 

Richard

**Comment by ayedo** [comment]
Hi Richard,

thanks for your help! 

I found a way to login before running my tests.

Alon

**Comment by fipp** [comment]
@ayedo could you share how you solved this?
