### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by stbischof** [testcontainers/testcontainers-java#9415]
### Module

Core

### Testcontainers version

1.20.2

### Using the latest Testcontainers version?

Yes

### Host OS

linux fedora silverblue

### Host Arch

x64

### Docker version

podman

### What happened?

Exception while calc getMemTotel with null

### Relevant log output

<<< ERROR: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.github.dockerjava.api.model.Info.getMemTotal()" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.github.dockerjava.api.model.Info.getMemTotal()" is null
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:228)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:108)
	at com.github.dockerjava.api.DockerClientDelegate.pingCmd(DockerClientDelegate.java:124)

### Additional Information
```
    private static boolean tryOutStrategy(List<String> configurationFailures, DockerClientProviderStrategy strategy) {
        try {
            log.debug("Trying out strategy: {}", strategy.getClass().getSimpleName());

            if (!strategy.test()) {
                log.debug("strategy {} did not pass the test", strategy.getClass().getSimpleName());
                return false;
            }

            strategy.info = strategy.getDockerClient().infoCmd().exec();
            log.info("Found Docker environment with {}", strategy.getDescription());
            log.debug(
```

the ` strategy.info `

is
```
Info(architecture=null, containers=null, containersStopped=null, containersPaused=null, containersRunning=null, cpuCfsPeriod=null, cpuCfsQuota=null, cpuShares=null, cpuSet=null, debug=null, discoveryBackend=null, dockerRootDir=null, driver=null, driverStatuses=null, systemStatus=null, plugins=null, executionDriver=null, loggingDriver=null, experimentalBuild=null, httpProxy=null, httpsProxy=null, id=null, ipv4Forwarding=null, bridgeNfIptables=null, bridgeNfIp6tables=null, images=null, indexServerAddress=null, initPath=null, initSha1=null, kernelVersion=null, labels=null, memoryLimit=null, memTotal=null, name=null, ncpu=null, nEventsListener=null, nfd=null, nGoroutines=null, noProxy=null, oomKillDisable=null, osType=null, oomScoreAdj=null, operatingSystem=null, registryConfig=null, sockets=null, swapLimit=null, systemTime=null, serverVersion=null, clusterStore=null, clusterAdvertise=null, swarm=null, isolation=null, securityOptions=null, runtimes=null)
```

**Comment by eddumelendez** [comment]
Hi, have you followed the [docs](https://java.testcontainers.org/supported_docker_environment/#podman)?

**Comment by Two4** [comment]
This issue is missing a title

**Comment by eddumelendez** [comment]
Hi @Two4, you can edit the title. There was no need to close and open a new one.

**Comment by stbischof** [comment]
Not reproduceable. Works after reboot and wait
