### ISSUE TITLE
LogMessageWaitStrategy does not match multiline frames

### ISSUE THREAD

**Issue by koschos** [testcontainers/testcontainers-java#945]
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/LogMessageWaitStrategy.java#L25

This predicate never matches multiline frames.
It should be fixed like this:

`Pattern pattern = Pattern.compile(regEx, Pattern.DOTALL);`
`Predicate<OutputFrame> waitPredicate = outputFrame ->
                pattern.matcher(outputFrame.getUtf8String()).matches();`

**Comment by kiview** [comment]
This has been fixed by #982.
