### ISSUE TITLE
Support specifying database name, user name and password in MariaDB URL, like MySQL container does

### ISSUE THREAD

**Issue by guss77** [testcontainers/testcontainers-java#949]
The current implementation of the MySQL JDBC container allows the user to override the generated database name, user name and password using the JDBC connection URL, but the MariaDB JDBC container implementation does not.

The missing piece looks to be an implementation of `JdbcDatabaseContainer newInstance(ConnectionUrl connectionUrl)` in `MariaDBContainerProvider`.

The implementation in `MySQLContainerProvider` seems to be robust and not dependant on MySQL specific semantics, so I'm pretty sure it can be just copied verbatim to support the same feature in MariaDB.

**Comment by vmassol** [comment]
I have exactly this problem too. My MySQL I have:

```
...
databaseContainer = new MySQLContainer<>();
...
        databaseContainer
            .withDatabaseName(DBNAME)
            .withUsername(DBUSERNAME)
            .withPassword(DBPASSWORD);
```

I've replaced `new MySQLContainer<>()` with `new MariaDBContainer<>()` and now it fails.

IMO the MariaDBContainer class should extend MySQLContainer since MariaDB is a dropin replacement of MySQL so the same config should apply.

**Comment by vmassol** [comment]
Something like:

```
public class MariaDBContainer<SELF extends MariaDBContainer<SELF>> extends MySQLContainer<SELF>
{
    public static final String NAME = "mariadb";

    public static final String IMAGE = "mariadb";

    public static final String DEFAULT_TAG = "10.3.6";

    public MariaDBContainer()
    {
        super(IMAGE + ":" + DEFAULT_TAG);
    }

    public MariaDBContainer(String dockerImageName)
    {
        super(dockerImageName);
    }

    @Override
    public String getDriverClassName()
    {
        return "org.mariadb.jdbc.Driver";
    }

    @Override
    public String getJdbcUrl()
    {
        return "jdbc:mariadb://" + getContainerIpAddress() + ":" + getMappedPort(MYSQL_PORT) + "/" + getDatabaseName();
    }
}
```

**Comment by guss77** [comment]
I don't think its a good idea, as that would force the MariaDB implementation to handle any feature added to the MySQL implementation - even if MariaDB doesn't support it (and there are a quite a few features that MySQL added after the fork that were not picked up by the MariaDB database project).

We have to accept that although very similar, there are now two different implementations which are somewhat incompatible (less though than how other SQL implementations are incompatible with each other).

Anyway, a fix for this issue was merged into master a few days ago and I expect it will be in the next release (I believe 1.11).

**Comment by guss77** [comment]
MariaDB is a drop in replacement for everything that relies on MySQL 5 level syntax. If you want to integrate with features added in MySQL 8 - then you need to do your homework first: MariaDB developers try to support features added by MySQL 8 on a standard basis - i.e. if they are implemented as defined by a relevant SQL standard with no weird things. 

There are quite a few things where MariaDB deviates from MySQL, for example - JSON queries (which is something I use): MySQL 8 has a `JSON` data type against which you then relatively simply just use JSON path expression as a SELECT value expression, while with MariaDB you can store JSON in any TEXT type and then use special functions to operate on. In anything that isn't an SQL standard or a MySQL 5 extended syntax, you can find that MariaDB and MySQL 8 differ a lot in their extended functions.

**Comment by vmassol** [comment]
@guss77 Thanks for this detailed explanation. I learnt stuff! :)
