### ISSUE TITLE
Use absolute numbers when checking for free disk space

### ISSUE THREAD

**Issue by gtrefs** [testcontainers/testcontainers-java#95]
The `checkDiskSpace` method in `DockerClientFactory` checks whether the local machine has enough disk space left to run a docker container. The check is done with a small alpine container which executes the command `df -P` and extracts the percentage used of the root. If the usage is above `90%` no docker container will be created. However, this seems to be quite restrictive as 10% of a 200GB disk are still 20GB which is more than plenty space to create new docker instances.

To overcome this, one could check the absolue numbers (e.g. more than 5GB have to be free).

**Comment by rnorth** [comment]
Hi,
Yes, that's a fair point - I'll amend this. I'll probably set it to 2GB, as this seems to be just about enough for most purpose and is 10% of the 20GB that a docker-machine user will get by default.
Thanks!
Richard
