### ISSUE TITLE
Can't set the shm_size for oracle xe

### ISSUE THREAD

**Issue by AlfAtGitHub** [testcontainers/testcontainers-java#952]
My oracle xe container is currently not starting because of a lack of shared memory:
"A database XE container needs at least 1 GB of shared memory (/dev/shm)."

My problem here: How can I set the shm_size (shmSize) for OracleContainer respectively GenericContainer?

I've already tried: .withCreateContainerCmdModifier(cmd -> cmd.withMemory((long) 4 * 1024 * 1024)). 

Also tried some settings within the testcontainers.properties. Unfortunately I've not found what params are available and how to set it here.

Any help welcome. Thanks.

**Comment by fzakaria** [comment]
I am also hitting the exception

Here are the logs from Docker `docker logs $ORACLE_CONTAINER -f`

```
/dev/shm (--shm-size) needs to be at least 1G
The Oracle base has been set to /u01/app/oracle
/dev/shm (--shm-size) needs to be at least 1G
The Oracle base has been set to /u01/app/oracle
/dev/shm (--shm-size) needs to be at least 1G
The Oracle base has been set to /u01/app/oracle
/dev/shm (--shm-size) needs to be at least 1G
```

**Comment by kiview** [comment]
The change in #957 makes sense of course.
But is this a change that has been introduced in a more recent Oracle XE image?

**Comment by fzakaria** [comment]
I am not using the wnameless docker image -- i've built my own docker image according to the Oracle GitHub documentation which I've linked in the pull-request; 
> https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md

Looking at his source; he's commented out 
> #memory_target=1073741824
(https://github.com/wnameless/docker-oracle-xe-11g/search?q=memory&unscoped_q=memory)

Given that you should be able to provide your own image; I think this is a worthwhile change still.

**Comment by rnorth** [comment]
Yeah, I think it makes sense to do this for the OracleContainer class. 
I’m just wondering if the solution should be to keep Testcontainers API as-is, and have the OracleContainer class use the docker-java API specifically to request shared memory...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
