### ISSUE TITLE
Create a lightweight set of tests to exercise shaded JARs

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#960]
#958 was an issue that could have been avoided if we had some integration tests that use _shaded_ JARs.

We should look to resolve this.

**Comment by kiview** [comment]
We are using the Gradle snapshopt JAR in the Maven examples project. Isn't it shaded?
We should migrate this to a Gradle subproject in the future though.

**Comment by rnorth** [comment]
I think that in this case it's just that there was no example for elasticsearch, and thus the example project ran fine.

**Comment by kiview** [comment]
Yes, the example project is definitely non representative :smile:

**Comment by mikaelhg** [comment]
Where can I add an integration test of trying to use `com.github.docker-java:docker-java` in a project which includes testcontainers?

**Comment by rnorth** [comment]
Not an integration test really, but https://github.com/testcontainers/testcontainers-java/blob/master/core/src/jarFileTest/java/org/testcontainers/JarFileShadingTest.java is for testing that the shaded JAR is well-formed. If there's something broken about the structure of the shaded JAR, this would probably be the place to create a failing test.

**Comment by mikaelhg** [comment]
Is it by purpose that `testcontainers-1.14.3.jar` from Maven Central contains the `com/github/dockerjava` classes unshaded?

**Comment by bsideup** [comment]
@mikaelhg yes. See https://github.com/testcontainers/testcontainers-java/issues/1113 for more context
