### ISSUE TITLE
Start InfluxDB from config file

### ISSUE THREAD

**Issue by fsanaulla** [testcontainers/testcontainers-java#961]
It's will be great to have an option for a running container from a configuration file.

**Comment by kiview** [comment]
Can you please explain what you mean? Example maybe?

**Comment by fsanaulla** [comment]
Hi @kiview, let me explain.
As you can see [here](https://hub.docker.com/_/influxdb/) under *Configuration* section, it's possible to start an image from the config file.
It's will be nice to have this option for `influxdb` testcontainer.

**Comment by kiview** [comment]
Okay I see. 
So what you want is to make `InfluxDBContainer` configurable using a config file?

Please mind this phrase from the docs:
> InfluxDB can be either configured from a config file or using environment variables.

This is already possible with environment variables in the current implementation.

**Comment by kiview** [comment]
@fsanaulla I'm closing the issue for now, since I think current configuration over environment variables should be sufficient. Please re-open if you want to go on discussing another approach.
