### ISSUE TITLE
[Feature request]: set fixed port for ryuk container

### ISSUE THREAD

**Issue by tomair37** [testcontainers/testcontainers-java#974]
#### Why ? 

I'm currently working on a windows 7 company computer. We use Vagrant to set fixed port between the host and the unix virtual machine whith Docker. Actually the port used by the Ryuk container is dynamic, it will be more convenient if we can set the port manually. 

#### Proposed solution

When I instanciate a Generic Container, I cannot acces the Ryuk container port. Would it be ok, if I make a pull request to add a property file (testcontainer.properties), with a property to set the port.
Or maybe have you got any more convinient way to achieve this goal.

**Comment by jtama** [comment]
This would still be usefull in secure envs, where expose ports are limited...

**Comment by shailjadon** [comment]
Random ports are difficult to manage especially if you are using remote docker host EC2 machines where we need to open the specific TCP ports which becomes extremely difficult since ports keep on changing.
