### ISSUE TITLE
published sourcecode does not bytecode

### ISSUE THREAD

**Issue by andaag** [testcontainers/testcontainers-java#978]
Trying to debug an issue with waitingFor and host mode networking, and tracing the waitUntilReady call in intellij claims the published source code does not match the bytecode.

This is using gradle with the following dependencies:
```
testCompile "org.testcontainers:testcontainers:1.9.1"
testCompile "org.testcontainers:kafka:1.9.1"
```

**Comment by iNikem** [comment]
Can you please specify what is your issue? You stated some fact about your working environment. What is the exact problem that you want for Testcontainers team to address?

**Comment by andaag** [comment]
I would like the published source to be in sync with the bytecode deployed, so I can debug things line by line. I'm guessing there is some issue in the publishing that has caused those artifacts to not be in sync.

**Comment by iNikem** [comment]
Testcontainers use Lombok for partial code generation. That is why source code does not directly correspond to the produced binary. You may try Delombok plugin for IntelliJ to somewhat alleviate this difference.

**Comment by asafm** [comment]
Don’t we rather “Delombok” - as project grows in UserBase those problems just keep growing. I mean is it worth the 100 lines saved by Lombok typed once and forgotten about ?

**Comment by andaag** [comment]
Another option, although a bit extreme one, is to start mixing in kotlin code. That takes care of the lombok for data classes case for example.. And intellij offers automatic conversion of these as well.

**Comment by michael-simons** [comment]
Spring Data uses Delombok during build https://github.com/spring-projects/spring-data-build/blob/master/parent/pom.xml#L328-L342 I think it helps a lot and is not very invasive.

**Comment by kiview** [comment]
@michael-simons I'm not that deep in this topic, but aren't we doing this here?
https://github.com/testcontainers/testcontainers-java/blob/master/build.gradle#L28

Or will this only affect local builds? (probably)

I'm sure @bsideup know more about this topic and has a well rounded opinion :wink:
