### ISSUE TITLE
CreateContainerCmdImpl is not setting AutoRemove

### ISSUE THREAD

**Issue by kamkie** [testcontainers/testcontainers-java#979]
ResourceReaper.java:69
has client.createContainerCmd(ryukImage).withHostConfig(new HostConfig().withAutoRemove(true))

but CreateContainerCmdImpl  is not reading it

```
9c0131651291        quay.io/testcontainers/ryuk:0.2.2                              "/app"                   8 minutes ago       Exited (0) 7 minutes ago                       testcontainers-ryuk-515777f2-6df8-4306-8ffc-c25d4196623d 
```

**Comment by kamkie** [comment]
i had this problem with every version after 1.5.x

**Comment by bsideup** [comment]
Hi @kamkie,

Do you still have it with the latest versions of Testcontainers?

**Comment by kamkie** [comment]
did'n check it on latest (1.10.7) yet

**Comment by kamkie** [comment]
works well on 1.11.1
