### ISSUE TITLE
Cannot find valid docker environment - ubuntu

### ISSUE THREAD

**Issue by LMKight** [testcontainers/testcontainers-java#981]
When trying to run tests with testcontainers the only thing I get is an Exception despite the fact that I have a running docker deamon:
```Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration```
In the stacktrace there is another Exception: 
```
 [main] ERROR org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - ping failed with configuration Environment variables, system properties and defaults. Resolved: 
    dockerHost=unix:///var/run/docker.sock
    apiVersion='{UNKNOWN_VERSION}'
    registryUrl='https://index.docker.io/v1/'
    registryUsername='randomUsernameThatIdidntConfigureAnywhere'
    registryPassword='null'
    registryEmail='null'
    dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=randomUsernameThatIdidntConfigureAnywhere,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/home/myname/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'
 due to org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
...
Caused by: org.testcontainers.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Permission denied: /var/run/docker.sock
```

The only thing i can read out of that is that the registryUsername is not the same username as the one that is configured in the docker deamon (running $docker info), in case that these 2 should match (luckily there is 0 documenation whether this should be the case or how to configure it)

**Comment by thebleucheese** [comment]
Are you running docker as sudo?  The default Linux Mint install runs as sudo and I got this error with it too.  Once I added my java compilation/test run user to the docker group I stopped getting this.

Now I'm getting another error related to containers not being able to start, but hopefully that's a least a step in the right direction.
