### ISSUE TITLE
DockerComposeContainer fails due to updated docker-compose naming scheme

### ISSUE THREAD

**Issue by m-thread** [testcontainers/testcontainers-java#986]
As of the release of docker-compose 1.23.0 the naming scheme of container changed. See this issue for more information: https://github.com/docker/compose/issues/6316

This seems to brake stuff in testcontainers DockerComposeContainer/SocatContainer implementation.
When trying to launch a docker-compose script we end up getting an exception like this: 'org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container se2uw5jwht66_smtp-server_1 as it is not runnining'

This is due to the fact that the container name isn't really 'se2uw5jwht66_smtp-server_1' but rather 'se2uw5jwht66_smtp-server_1_e71d646caccf' following the new naming scheme in docker-compose.

**Comment by rnorth** [comment]
Thanks @m-thread, yes, we've become aware of this unfortunate problem 😭. For now we'd recommend people hold back on updating local installations of docker-compose, and stay with 1.22.x.

We'll need to implement a solution to this, as it looks like the new behaviour is here to stay.

**Comment by m-thread** [comment]
New release of docker-compose today:
https://github.com/docker/compose/releases/tag/1.23.2

Seems like they backed off from the breaking change for now. At least partially.

**Comment by kiview** [comment]
Yes you are right, I will close this for now in the light of docker-compose 1.23.2 release.
All Testcontainers user are advised to update their docker-compose version accordingly.

Thanks to everyone contributing in this issue by providing details.
