### ISSUE TITLE
Fails to start GenericContainer if image name contains private repository URL with port 

### ISSUE THREAD

**Issue by asafm** [testcontainers/testcontainers-java#99]
Let's say my docker image name is: `dockerrepo.foobar.com:5000/coolservice:1.0.2`
The following code fails:
```
        boolean isTagNamePresent = dockerImageName.split(":").length == 2;
        Preconditions.checkArgument(isTagNamePresent, "No image tag was specified in docker image name (" + dockerImageName + "). Please provide a tag; this may be 'latest' or a specific version");
```

Since it assumed only one ':' is allowed, while it can only exists on the repository name. So the Image name template is: 
({REPOSITORY-NAME}/){NAME}:{TAG}
Where {REPOSITORY-NAME}/ is optional, and it can contains ':' since it can be a URL using hostname and port.
So the right approach is to:
1. Search for "/". If not found there's no repositoryName.
2. Cut away repository name and "/" if found.
3. Search for a single semicolon. If 0, no tag exists which by the way is perfectly legal - you can docker run from command line without a tag, but I'm ok with failing on this. If more than 1, it's not legal. If 1 then take the name after it - this is your tag.

I completely stuck on this so I'll submit a pull request

**Comment by rnorth** [comment]
Thanks - yes, this is something I wanted to fix, so thank you for raising and contributing a PR. Have you been able to verify that this works when you have a custom registry?

In the long run this could probably do with an integration test (e.g. running docker-registry in a container) but I think that can wait.

Please add your name to the AUTHORS file for credit :)

I'll try and get this into a release soon (hopefully this evening).
