### ISSUE TITLE
Add docs regarding workarounds for Ryuk image pulling in closed enterprise environments

### ISSUE THREAD

**Issue by destebanm** [testcontainers/testcontainers-java#990]
Hi!

I have used testcontainers to run a Postgre for our tests.

In my local works like a charm.

The issue starts when running in our bamboo, when we get the next error:
```
3-Nov-2018 11:35:02	11:35:02.884 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Looking up auth config for image: quay.io/testcontainers/ryuk:0.2.2
23-Nov-2018 11:35:02	11:35:02.885 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - RegistryAuthLocator has configFile: /home/bamboo/.docker/config.json (exists) and commandPathPrefix: 
23-Nov-2018 11:35:02	11:35:02.896 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - registryName [quay.io] for dockerImageName [quay.io/testcontainers/ryuk:0.2.2]
23-Nov-2018 11:35:02	11:35:02.898 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - no matching Auth Configs - falling back to defaultAuthConfig [null]
23-Nov-2018 11:35:02	11:35:02.898 [main] DEBUG org.testcontainers.dockerclient.auth.AuthDelegatingDockerClientConfig - Effective auth config [null]
23-Nov-2018 11:35:02	11:35:02.963 [tc-okhttp-stream-89468176] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
23-Nov-2018 11:35:02	com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: Forbidden"}
23-Nov-2018 11:35:02	
23-Nov-2018 11:35:02	        at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:279)
23-Nov-2018 11:35:02	        at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$1(OkHttpInvocationBuilder.java:295)
23-Nov-2018 11:35:02	        at java.lang.Thread.run(Thread.java:748)
23-Nov-2018 11:35:02	[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.847 s <<< FAILURE! - in es.openbank.notifications.repositories.MessageRepositoryTest
23-Nov-2018 11:35:02	[ERROR] es.openbank.notifications.repositories.MessageRepositoryTest  Time elapsed: 2.847 s  <<< ERROR!
23-Nov-2018 11:35:02	java.lang.ExceptionInInitializerError
23-Nov-2018 11:35:02	Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: 
23-Nov-2018 11:35:02	{"message":"Get https://quay.io/v2/: Forbidden"}

```
Why the library is trying to connect to that URL? 

I think it would be difficult that our testing environment have connection with this URL...

Thanks!!!!

**Comment by rnorth** [comment]
Quay.io is a docker registry where the Ryuk image is pulled from: https://quay.io/repository/testcontainers/ryuk

For what it’s worth, quay.io is operated by CoreOS (now part of Red Hat). 

If you or your secops team need to block access to quay then you can, as @neetkee mentioned, tell Testcontainers to pull the ryuk image from your own private registry server (somewhere that you have mirrored the image to). Hopefully this helps unblock you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by remmeier** [comment]
We have the same issue. Everything runs behind a proxy. If users configure the proxy within the docker deamon or have an internal repository that mirrors quay.io, then everything is fine. If this is not the case, then this code in `ResourceReapder` seems to be the issue:

```
String ryukContainerId = client.createContainerCmd(ryukImage)
    .withHostConfig(new HostConfig().withAutoRemove(true))
    .withExposedPorts(new ExposedPort(8080))
    .withPublishAllPorts(true)
    .withName("testcontainers-ryuk-" + DockerClientFactory.SESSION_ID)
    .withLabels(Collections.singletonMap(DockerClientFactory.TESTCONTAINERS_LABEL, "true"))
    .withBinds(binds)
    .withPrivileged(TestcontainersConfiguration.getInstance().isRyukPrivileged())
    .exec()
    .getId();

client.startContainerCmd(ryukContainerId).exec();
```

**Comment by rnorth** [comment]
@remmeier I don't think setting an `HTTP_PROXY` env var will work I'm afraid. 

I _think_ you're trying to set a proxy that Docker should use when pulling images.
The change in your branch will just set an env var that is present in the running container (i.e. after pull).

As far as I know, there is no way for us to tell Docker what proxy to use when pulling. The only options are:

* Change your docker daemon settings to use an HTTP proxy for all pulls
* Host the Ryuk container image on your internal docker registry, and configure Testcontainers to pull from that

As far as I can tell there's nothing else we can do, I'm afraid.

**Comment by remmeier** [comment]
yes, I noticed this morning as well. Second way seems the way to go. It would maybe interesting to have support for system properties and environment variables in TestcontainersConfiguration since we are getting into environment-specific properties. Or in my case I would actually like to inject the properties from a Spring Boot configuration.

**Comment by remmeier** [comment]
and regarding this ticket those two hints could be added to the documentation and then closed

**Comment by rnorth** [comment]
Yep, we'll update the docs. Thanks.
