### ISSUE TITLE
Using testcontainers on the module path fails

### ISSUE THREAD

**Issue by alexanderkjall** [testcontainers/testcontainers-java#991]
When trying to use testcontainers on the module path you get these warnings:

```
[WARNING] Can't extract module name from visible-assertions-2.1.1.jar: TtyCheck.class found in top-level directory (unnamed package not allowed in module)
[WARNING] Can't extract module name from native-lib-loader-2.0.2.jar: native.lib.loader: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from junixsocket-native-common-2.0.4.jar: junixsocket.native.common: Invalid module name: 'native' is not a Java identifier
```

And the test fails with:
```
java.lang.NoClassDefFoundError: org/rnorth/visibleassertions/VisibleAssertions
```

These are the bugs in the underlying dependencies:
* https://github.com/kohlschutter/junixsocket/issues/49
* https://github.com/scijava/native-lib-loader/issues/24
* https://github.com/rnorth/visible-assertions/issues/19

The issue can be reproduced by running the tests in this repository https://github.com/pgjdbc/pgadba with the configuration `<forkCount>0</forkCount>` commented out.

**Comment by alexanderkjall** [comment]
Yes, it looks like a duplicate, I don't know how I missed that one.

**Comment by rnorth** [comment]
I'll close this ticket, but your writeup is helpful, thank you @alexanderkjall. I'll copy it over.
