### ISSUE TITLE
Is there any available config for DNS setting ?

### ISSUE THREAD

**Issue by Ykid** [testcontainers/testcontainers-java#994]
Excuse me if this is not the proper place to ask questions. May I know if there is any available method to set `--hostname 127.0.0.1` as stated [here](https://docs.docker.com/config/containers/container-networking/#dns-services) ? 

The use case is this: I need to connect to mongodb replica set to test something, but if `--hostname 127.0.0.1` is not set, the container returns its id as hostname which does not match my connection string "mongodb://127.0.0.1:27017......" so the library throws an error. Is there any workaround ?

Thanks a lot !

**Comment by Ykid** [comment]
it seems this can do the trick

```
container
.withCreateContainerCmdModifier((t: CreateContainerCmd) => {
      t.withHostName("127.0.0.1")
    })
```

**Comment by kiview** [comment]
Hey @Ykid, great you found it.
`withCreateContainerCmdModifier` exposes the docker-java capabilities, so it can be used for most features that are not part of the Testcontainers API itself.
