### ISSUE TITLE
Load Docker image from Azure Container Registry

### ISSUE THREAD

**Issue by aTTraX** [testcontainers/testcontainers-java#997]
Good morning,
hopefully it's ok to ask for help here, because I struggle with getting my idea to run.
I have a docker image stored and build in the azurecr.io container registry and I want to use this image with testcontainers to test my application.
This means that my test should look up for the newest version of the image, download it if a newer version is available and use it for my test.
But I try to manage this since three days and can't make it.
I also did a huge google research and read a lot of already existing issues in this project, but nothing really fitted to my problem.

Can anybody please give me a hint or example code, how I can get this running?
I tried to use GenericContainer, RemoteDockerImage, FixedHostPortGenericContainer and so on, but nothing worked for me.

A big sorry if this is the wrong place to ask for help, but I don't know what to do otherwise.

**Comment by rnorth** [comment]
Hi @aTTraX, it should be pretty simple:

```
new GenericContainer("yourregistry.azurecr.io/yourimage:yourtag")
```

You'll need to be logged in to the registry for authentication, but Testcontainers/docker-java should pick up your local auth details and use those.

You could use a `latest` tag to get the latest version, but:
* we generally discourage that, as it makes the tests less repeatable
* you may notice that the image is cached

In general, it's always better to modify the tag name that you give to Testcontainers whenever a newer version is available (i.e. change the string). Unfortunately we don't have anything right now to help with that, but it's something I'd like to implement some time.

For now, could you try using the `latest` tag and see if that works well enough for you?

**Comment by aTTraX** [comment]
Hi @rnorth,
thank you for the quick response.
I tried this already many times, but I always get huge Exceptions.
Maybe my system configuration is wrong or something.
Thanks anyway

**Comment by aTTraX** [comment]
I finally made it, but I don't know why at the moment. Probably cause of authorization.
Thanks anyway
