### ISSUE TITLE
Kafka : use a lighter Kafka image and don't use socat

### ISSUE THREAD

**Issue by glandais-eptica** [testcontainers/testcontainers-java#998]
We had great success running a lightweight Kafka container and being able to use it outside of Docker network.

I've posted some configuration details there : https://github.com/wurstmeister/kafka-docker/issues/431

**Comment by bsideup** [comment]
Hi @glandais-eptica,

> outside of Docker network.
`KafkaContainer` can be used outside of Docker network already, from your host. Not sure I get this point :)

The solution you provided will not work if Docker is running on a remote host (e.g. CircleCI without `machine: true`), or probably even "inside container" scenario.

> a lightweight Kafka container
I don't think Socat adds any noticeable difference unless you have different numbers :)
